### ISSUE TITLE
How to calculate the fps of BiseNet ?

### ISSUE THREAD

**Issue by lmunan** [open-mmlab/mmsegmentation#1007]

**Comment by MengzhangLI** [comment]
You can use ./tools/benchmark.py to re-calculate FPS we showed on config file.

**Note**: This tool is still experimental and we do not guarantee that the number is correct. You may well use the result for simple comparisons, but double check it before you adopt it in technical reports or papers.

So you can compare relatively FPS between BiSeNet or other real-time models and some SOTA models such as PSPNet, DeepLabV3.

The FPS value we showed is on V100 with MMSegmentation codebase, which is not the value from real-time models paper which usually uses TensorRT and on single GPU like Titan X.

**Comment by lmunan** [comment]
Thank you.
