### ISSUE TITLE
add new module

### ISSUE THREAD

**Issue by zjk958162734** [open-mmlab/mmsegmentation#101]
Hello, I’m sorry to disturb you. That’s right. I’m currently trying to add some modules to your model. For example, I added a Conv2d to the stem of ResNetV1c,
![1](https://user-images.githubusercontent.com/60846453/91627278-ee6c9780-e9e8-11ea-91d7-0c108eb8d1c1.jpg)
 and then use your pre-trained model. It will prompt me The weight of Conv2d is not included in the pre-trained weights. I understand this.
![2](https://user-images.githubusercontent.com/60846453/91627282-f593a580-e9e8-11ea-8771-dddd49bc50b4.jpg)

 What I want to ask is, if the weight of Conv2d at this time is the system initialization, or do you define some functions to deal with these situations,
 in addition, the last saved The training weight, will it also include the Conv2d weight I defined, thank you

**Comment by xvjiarui** [comment]
Hi @zjk958162734 
1. The `Conv2d` will use the default initialization of PyTorch.
2. The weight of `Conv2d` will be saved as well.
