### ISSUE TITLE
How to get the pretrained data like demo

### ISSUE THREAD

**Issue by Allenzhang97** [open-mmlab/mmsegmentation#1010]
In the demo, the pretrained weights of deeplabv3 is provided. I have trained the cityscapes dataset on my computer but the accuracy is not good. So I am wondering whether the pretrained weights are available for other models such as hrnet.

**Comment by MengzhangLI** [comment]
Hi, for pretrained model for training, you could find its dict [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json). For our trained well models, just click link and download it in README.md [file](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/README.md)
