### ISSUE TITLE
Is there an easy way to try instance segmentation?

### ISSUE THREAD

**Issue by Keiku** [open-mmlab/mmsegmentation#1018]
I'm sorry for the newbie question. I've had to try instance segmentation (not semantic) for my work, but is there a good sample dataset or architecture? I thought it would be easy for Detectron2's PointRend, but what is there in mmsegmentation?

**Comment by MengzhangLI** [comment]
Hi, @Keiku 
For instance segmentation, current it is merged in [MMDetection](https://github.com/open-mmlab/mmdetection). You can try [SOLO](https://github.com/open-mmlab/mmdetection/blob/master/configs/solo/README.md) and [PointRend](https://github.com/open-mmlab/mmdetection/tree/master/configs/point_rend).

Hope it is useful for you.

Best,

**Comment by Keiku** [comment]
@MengzhangLI Thank you for your reply.

Is it okay for mmdetection to use `../_base_/datasets/coco_instance.py` as the basic instance segmentation dataset? Is QueryInst SOTA within mmdetection support?

**Comment by Keiku** [comment]
@MengzhangLI Sorry for the additional question. Does the above mmdetection work even if my own data does not include bbox?

**Comment by MengzhangLI** [comment]
Hi, @jshilong

could you help us to answer question above about MMDetection?

Thanks.

**Comment by Keiku** [comment]
@engzhangLI thank you for your answer. I will do so.

**Comment by Keiku** [comment]
I'm sorry. I misread English.

**Comment by MengzhangLI** [comment]
> I'm sorry. I misread English.

いいえ，ちょっと待て @jshilong さんの回答.

**Comment by Keiku** [comment]
Thank you. I wait for jshilong's reply.

**Comment by jshilong** [comment]
> Thank you. I wait for jshilong's reply.
We have supported Queryinst

https://github.com/open-mmlab/mmdetection/tree/master/configs/queryinst

**Comment by Keiku** [comment]
@jshilong Do instance segmentation task of mmdetection (for example SOLO, PointRend, Queryinst) work with custom own datasets that don't include bbox?

**Comment by MengzhangLI** [comment]
> @jshilong Do instance segmentation task of mmdetection (for example SOLO, PointRend, Queryinst) work with custom own datasets that don't include bbox?

He said at least SOLO does not need bbox but he is not sure about Queryinst. Anyway if you have instance segmentation labels, the bbox does not matter theoretically because it could be generated.

**Comment by Keiku** [comment]
Sure, I think mmdetection will work if I generate a bbox. I will practice with some datasets. Thank you for your polite answer.
