### ISSUE TITLE
STDC-seg  reproduction

### ISSUE THREAD

**Issue by chen1234520** [open-mmlab/mmsegmentation#1025]
请问STDC-seg的复现工作是否完成？这个版本的可以使用吗？https://github.com/xiexinch/mmsegmentation/tree/stdc_new @MengzhangLI  @xiexinch

**Comment by chen1234520** [comment]
> > 请问STDC-seg的复现工作是否完成？这个版本的可以使用吗？https://github.com/xiexinch/mmsegmentation/tree/stdc_new @MengzhangLI @xiexinch
> 
> Not yet. It is WIP.
> 
> But we have unofficial reproduced training results in our own settings.
> 
> You could run it without pretrained models(not provided yet) currently.
> 
> I suggest you remove `STDCHead` to `FCN` because right now I found it is useless because its loss is zero. I am checking out whether am I wrong or the original paper / codebase is misleading.
> 
> FYI: [MichaelFan01/STDC-Seg#26](https://github.com/MichaelFan01/STDC-Seg/issues/26)

Thanks.

**Comment by MengzhangLI** [comment]
> > > 请问STDC-seg的复现工作是否完成？这个版本的可以使用吗？https://github.com/xiexinch/mmsegmentation/tree/stdc_new @MengzhangLI @xiexinch
> > 
> > 
> > Not yet. It is WIP.
> > But we have unofficial reproduced training results in our own settings.
> > You could run it without pretrained models(not provided yet) currently.
> > I suggest you remove `STDCHead` to `FCN` because right now I found it is useless because its loss is zero. I am checking out whether am I wrong or the original paper / codebase is misleading.
> > FYI: [MichaelFan01/STDC-Seg#26](https://github.com/MichaelFan01/STDC-Seg/issues/26)
> 
> Thanks.

Leave out your e-mails so I can send pretrained models and config files to you.

**Comment by chen1234520** [comment]
> > > > 比如STDC -seg的复现工作是否完成？这个版本的可以使用吗？[https://github.com/xiexinch/mmsegmentation/tree/stdc_new ](https://github.com/xiexinch/mmsegmentation/tree/stdc_new) @MengzhangLI  @xiexinch
> > > 
> > > 
> > > 还没有。它是 WIP。
> > > 但是我们在我们自己的设置中有非官方的复制训练结果。
> > > 您目前可以在没有预训练模型（尚未提供）的情况下运行它。
> > > 我建议你删除`STDCHead`to`FCN`因为现在我发现它没有用，因为它的损失为零。我正在检查是我错了还是原始论文/代码库具有误导性。
> > > 仅供参考：[MichaelFan01/STDC-Seg#26](https://github.com/MichaelFan01/STDC-Seg/issues/26)
> > 
> > 
> > 谢谢。
> 
> 留下您的电子邮件，以便我可以将预训练的模型和配置文件发送给您。

chen1234520nn@foxmail.com
Thanks a lot

**Comment by fangwudi** [comment]
> > > > > 比如STDC -seg的复现工作是否完成？这个版本的可以使用吗？[https://github.com/xiexinch/mmsegmentation/tree/stdc_new ](https://github.com/xiexinch/mmsegmentation/tree/stdc_new) @MengzhangLI  @xiexinch
> > > > 
> > > > 
> > > > 还没有。它是 WIP。
> > > > 但是我们在我们自己的设置中有非官方的复制训练结果。
> > > > 您目前可以在没有预训练模型（尚未提供）的情况下运行它。
> > > > 我建议你删除`STDCHead`to`FCN`因为现在我发现它没有用，因为它的损失为零。我正在检查是我错了还是原始论文/代码库具有误导性。
> > > > 仅供参考：[MichaelFan01/STDC-Seg#26](https://github.com/MichaelFan01/STDC-Seg/issues/26)
> > > 
> > > 
> > > 谢谢。
> > 
> > 
> > 留下您的电子邮件，以便我可以将预训练的模型和配置文件发送给您。
> 
> [chen1234520nn@foxmail.com](mailto:chen1234520nn@foxmail.com) Thanks a lot

你好，我也需要，我的邮箱是fangwudi@foxmail.com， 谢谢。另外，复现pr还要大概什么时候可以完成？

**Comment by MengzhangLI** [comment]
> > > > > > 比如STDC -seg的复现工作是否完成？这个版本的可以使用吗？[https://github.com/xiexinch/mmsegmentation/tree/stdc_new ](https://github.com/xiexinch/mmsegmentation/tree/stdc_new) @MengzhangLI  @xiexinch
> > > > > 
> > > > > 
> > > > > 还没有。它是 WIP。
> > > > > 但是我们在我们自己的设置中有非官方的复制训练结果。
> > > > > 您目前可以在没有预训练模型（尚未提供）的情况下运行它。
> > > > > 我建议你删除`STDCHead`to`FCN`因为现在我发现它没有用，因为它的损失为零。我正在检查是我错了还是原始论文/代码库具有误导性。
> > > > > 仅供参考：[MichaelFan01/STDC-Seg#26](https://github.com/MichaelFan01/STDC-Seg/issues/26)
> > > > 
> > > > 
> > > > 谢谢。
> > > 
> > > 
> > > 留下您的电子邮件，以便我可以将预训练的模型和配置文件发送给您。
> > 
> > 
> > [chen1234520nn@foxmail.com](mailto:chen1234520nn@foxmail.com) Thanks a lot
> 
> 你好，我也需要，我的邮箱是[fangwudi@foxmail.com](mailto:fangwudi@foxmail.com)， 谢谢。另外，复现pr还要大概什么时候可以完成？

Maybe in the end of this month.

**Comment by MengzhangLI** [comment]
@fangwudi @chen1234520 STDC-Seg has been supported by MMSegmentation.
