### ISSUE TITLE
How to remove augmentation pipelines in the train_pipeline and val_pipeline?

### ISSUE THREAD

**Issue by Jackbrocp** [open-mmlab/mmsegmentation#1026]
I would like to train  a model without any kind of augmentation. But by default, the training pipeline includes several augmentation policies. So how to remove these?
Thx!!!

**Comment by MengzhangLI** [comment]
Hi, you could uncomment any dict of data augmentation transformation such as `RandomCrop` and `PhotoMetricDistortion` in `train_pipeline` like [here](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/cityscapes.py).

Best,

**Comment by Jackbrocp** [comment]
> Hi, you could uncomment any dict of data augmentation transformation such as `RandomCrop` and `PhotoMetricDistortion` in `train_pipeline` like [here](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/cityscapes.py).
> 
> Best,

Thx for your reply.
I have uncommented dicts of augmentation.
But I got a KeyError. The specific details is as follows:
   **File "/home/mmsegmentation-master/mmseg/datasets/pipelines/formatting.py", line 281, in __call__
    img_meta[key] = results[key]
KeyError: 'flip'**

**Comment by MengzhangLI** [comment]
Probably it is caused by calling `Collect` inside `MultiScaleFlipAug` transforms, since `flip` tag is not available there yet.

Hoping this issue is helpful to you: https://github.com/open-mmlab/mmsegmentation/issues/231.

Best,

**Comment by Jackbrocp** [comment]
> Probably it is caused by calling `Collect` inside `MultiScaleFlipAug` transforms, since `flip` tag is not available there yet.
> 
> Hoping this issue is helpful to you: #231.
> 
> Best,

OK, thank you again!
BTW, I have modified contents in 'Collect' and 'conv2d.forward()'. Finally, it can run normally.
