### ISSUE TITLE
About CUDA out of memory

### ISSUE THREAD

**Issue by chenhaiwen** [open-mmlab/mmsegmentation#1029]
when i use setr model to train my own dataset, will quote:

`File "/home/chenhaiwen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    ret = input.softmax(dim)
    result = self.forward(*input, **kwargs)
  File "/home/chenhaiwen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py", line 120, in forward_wrapper
RuntimeError: CUDA out of memory. Tried to allocate 258.00 MiB (GPU 2; 10.92 GiB total capacity; 9.96 GiB already allocated; 83.00 MiB free;
    attn_output, attn_output_weights = forward(**kwargs)
`
i ues gtx1080 11GB, and train with eight cards.
please help help childen

**Comment by MengzhangLI** [comment]
Hi, SETR needs high GPU computation capacity. So cuda out of memory is often met of it.

You could

(1) make crop size, batch size etc smaller.

(2) make `cudnn_benchmark = False` [here](https://github.com/open-mmlab/mmsegmentation/blob/7a1c9a5499dc2bfa28e506476c68cbdd0980395b/configs/_base_/default_runtime.py#L14).

(3) Using FP16,  like this set [BiSeNetV2(FP16)](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/bisenetv2/bisenetv2_fcn_fp16_4x4_1024x1024_160k_cityscapes.py).

Best,

**Comment by chenhaiwen** [comment]
thank you, those are very usful
