### ISSUE TITLE
test.py  output prediction image format

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmsegmentation#1032]
When using the test.py file to make predictions, I saved the predicted images (--show-dir), but I found that the output image format is xx.jpg.  how I can change the output  format to xx.png? 
Thanks a lot!

**Comment by MengzhangLI** [comment]
Hi, which dataset do you use?

Hoping this [link](https://github.com/open-mmlab/mmsegmentation/blob/7a1c9a5499dc2bfa28e506476c68cbdd0980395b/mmseg/datasets/custom.py#L80) is useful to you.

Best,

**Comment by wwjwy** [comment]
> Hi, which dataset do you use?
> 
> Hoping this [link](https://github.com/open-mmlab/mmsegmentation/blob/7a1c9a5499dc2bfa28e506476c68cbdd0980395b/mmseg/datasets/custom.py#L80) is useful to you.
> 
> Best,

hi, i used pascal_voc12 dataset,  the format of image is xx.jpg,  the format of mask is xx.png.  when i output the predictions, the format of output image is xx.jpg.

I notice that the output format of image(xx.jpg) is the same as input image(xx.jpg), https://github.com/open-mmlab/mmsegmentation/blob/7a1c9a5499dc2bfa28e506476c68cbdd0980395b/mmseg/apis/test.py#L120
if i change the format of image to xx.png, the image seems to be damaged in linux.
I donnot know how to do next?

**Comment by MengzhangLI** [comment]
I think another rude solution is adding some codes to transfer `result` into saving `.png` file after this line:

https://github.com/open-mmlab/mmsegmentation/blob/7a1c9a5499dc2bfa28e506476c68cbdd0980395b/mmseg/apis/test.py#L91

It is ugly but it can work easily.

**Comment by wwjwy** [comment]
Thanks a lot
