### ISSUE TITLE
Change the output shape 

### ISSUE THREAD

**Issue by LingCoderSonoscape** [open-mmlab/mmsegmentation#1033]
Hi! I tried to build a HRnet model in mmsegmentation framework. However, I am struggling in one thing. 
My model takes a grayscaled image as an input, and will generate an output with the same width and height but having 14 channels. Each channel represents one class and if the image does not belong to the class, then that channel will be blank. 
So the two challenges are:
1. How should I edit the model config file?
2. If I keep my own dataset format  as recommended format, then how should I design my test/train pipeline?

**Comment by MengzhangLI** [comment]
Hi, sorry to tell you right now MMSegmentation only support 1 or 3 channel image. We have noticed the needs of multi channels image segmentation, so we would try to support this feature in the near future. 

Best,

**Comment by MengzhangLI** [comment]
BTW, related issue: https://github.com/open-mmlab/mmsegmentation/issues/890.

**Comment by LingCoderSonoscape** [comment]
> Hi, sorry to tell you right now MMSegmentation only support 1 or 3 channel image. We have noticed the needs of multi channels image segmentation, so we would try to support this feature in the near future.
> 
> Best,

Alright I see. Thank you for your reply!

**Comment by LingCoderSonoscape** [comment]
> Hi, sorry to tell you right now MMSegmentation only support 1 or 3 channel image. We have noticed the needs of multi channels image segmentation, so we would try to support this feature in the near future.
> 
> Best,

"MMSegmentation only support 1 or 3 channel image" does it mean **_both_ the input and output** can only be 1 or 3 channels? Because in my situation, only the output has more than 3 channels and the input just has one channel.

**Comment by MengzhangLI** [comment]
I think output is ok (with some modification in evaluation) in `channels > 3` situation because the biggest challenge is data augmentation pipeline in training.

**Comment by LingCoderSonoscape** [comment]
> I think output is ok (with some modification in evaluation) in `channels > 3` situation because the biggest challenge is data augmentation pipeline in training.
> 
> You can have a try whether it works and let’s keep in touch.

Yes, you are right, the biggest problem is the pipeline generation. I will give it a try to build a custom one but might take some time.
