### ISSUE TITLE
Lovasz loss

### ISSUE THREAD

**Issue by lmunan** [open-mmlab/mmsegmentation#1036]
Hello, when I use lovasz loss, when loss_type='binary', the following problems will occur 
`IndexError: The shape of the mask [1048576] at index 0 does not match the shape of the indexed tensor [2097152] at index 0`

**Comment by lmunan** [comment]
I modified ingnore_index=None, and the problem was solved

**Comment by lmunan** [comment]
I printed some information
![2021-11-13 15-45-21屏幕截图](https://user-images.githubusercontent.com/26930245/141610753-3366382f-17d6-4a9e-b229-e71ed0a84502.png)
![2021-11-13 15-45-57屏幕截图](https://user-images.githubusercontent.com/26930245/141610757-7b26465c-9429-433b-9efb-f2a50017058f.png)

**Comment by pengzhao-life** [comment]
Hi, I run into the same problem. Any update?

**Comment by MengzhangLI** [comment]
@lmunan As for binary segmentation, `num_classes` should be set `1` rather than `2`.
