### ISSUE TITLE
warnings.warn('show==False and out_file is not specified, only '

### ISSUE THREAD

**Issue by zzjjxx994501847** [open-mmlab/mmsegmentation#104]
When I have my environment configured and ready to run demo times, I make an error
Is it because the output file is not specified?If I need to specify the output file, where do I modify it
Execute the command：
python demo/image_demo.py demo/demo.png configs/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes.py checkpoints/deeplabv3_r50-d8_512x1024_40k_cityscapes_20200605_022449-acadc2f8.pth --device cuda:0 --palette cityscapes
Error：
which: no hipcc in (/EDA/soft/anaconda3.7/bin:/EDA/soft/anaconda3.7/condabin:/usr/lib64/qt-3.3/bin:/home/zuochang2/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/home/zuochang2/.local/bin:/home/zuochang2/bin)
/EDA/soft/anaconda3.7/lib/python3.7/site-packages/mmseg/models/segmentors/base.py:265: UserWarning: show==False and out_file is not specified, only result image will be returned
  warnings.warn('show==False and out_file is not specified, only '

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Comment by xvjiarui** [comment]
Hi @zzjjxx994501847 
They are just warnings, nor errors. Did you encounter some abnormal behavior?

**Comment by zzjjxx994501847** [comment]
Yes, this warning will appear when I run it, and the final image will not pop up.I don't know what went wrong

**Comment by zyhhhy** [comment]
Maybe you can do this:
modify the mmseg\apis\inference.py file. Add the line below:
plt.savefig('./test_output/'+img_name+'.png')
before the plt.show()

**Comment by zzjjxx994501847** [comment]
I tried to do this, but the same warnings came up

**Comment by zyhhhy** [comment]
Indeed, the solution can not fix the warning. But the final image will be saved in the ./test_output folder.
You can ingore these warnings.

**Comment by zzjjxx994501847** [comment]
Thank you for your help.
I added this line of code but no image is saved in the test_output file.
Is my output path wrong

**Comment by zyhhhy** [comment]
Oh, I can give you another advice, which is the method i am using.
Modify the show_result_pyplot function like this:

def show_result_pyplot(model, img, result, palette=None, fig_size=(15, 10)):
    if hasattr(model, 'module'):
        model = model.module
    img_name=img.split("/")[-1].split(".")[0]
    print(img_name+" DONE!")
    img = show_result(model,img, result, palette=palette, show=False,out_file="./test_output/"+img_name+".png")
    # plt.figure(figsize=fig_size)
    # plt.imshow(mmcv.bgr2rgb(img))
    # plt.savefig('./test_output/'+img_name+'.png')
    # plt.show()
    # plt.close('all')

PS: 
1. You are expected to create the "test_output" folder FIRST in your working dir.
2. The warnings are still there, but I get the right image in the "test_output" folder.
Hope this can help you fix the problems.

**Comment by zzjjxx994501847** [comment]
I created the test_output file as you suggested and modified the path code.Warnings will still appear.I'm thinking about my question now that the path is specified, is there something wrong with the generated image

**Comment by xvjiarui** [comment]
Hi @zzjjxx994501847 
Are you trying on a local machine or a sever? 
I tried with my own Mac and Linux machine, it works.

**Comment by zzjjxx994501847** [comment]
I'm running it on the server

**Comment by xvjiarui** [comment]
Hi @zzjjxx994501847 
You may try jupyter notebook demo [here[(https://github.com/open-mmlab/mmsegmentation/blob/master/demo/inference_demo.ipynb) or [Colab](https://colab.research.google.com/github/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb).

**Comment by zzjjxx994501847** [comment]
Is change:
# show the results
show_result_pyplot(model, args.img, result, get_palette(args.palette))
to:
# show the results
show_result_pyplot(model, img, result, get_palette('cityscapes'))

**Comment by zzjjxx994501847** [comment]
Is change:
show_result_pyplot(model, args.img, result, get_palette(args.palette))
to:
show_result_pyplot(model, img, result, get_palette('cityscapes'))

**Comment by xvjiarui** [comment]
Hi @zzjjxx994501847 
If you are run it on the server without X window support, there will be no image.

**Comment by Linda-L** [comment]
> def show_result_pyplot(model, img, result, palette=None, fig_size=(15, 10)):
>     if hasattr(model, 'module'):
>         model = model.module
>     img_name=img.split("/")[-1].split(".")[0]
>     print(img_name+" DONE!")
>     img = show_result(model,img, result, palette=palette, show=False,out_file="./test_output/"+img_name+".png")

img = show_result(model, img, result, palette=palette, show=False,out_file="./test_output/"+img_name+".png")

hi,but I don't have this function show_result

**Comment by kanchaidexiaohuang** [comment]
> Oh, I can give you another advice, which is the method i am using. Modify the show_result_pyplot function like this:
> 
> ```
> def show_result_pyplot(model, img, result, palette=None, fig_size=(15, 10)):
>     if hasattr(model, 'module'):
>         model = model.module
>     img_name=img.split("/")[-1].split(".")[0]
>     print(img_name+" DONE!")
>     img = show_result(model,img, result, palette=palette, show=False,out_file="./test_output/"+img_name+".png")
>     # plt.figure(figsize=fig_size)
>     # plt.imshow(mmcv.bgr2rgb(img))
>     # plt.savefig('./test_output/'+img_name+'.png')
>     # plt.show()
>     # plt.close('all')
> ```
> 
> PS:
> 
> 1. You are expected to create the "test_output" folder FIRST in your working dir.
> 2. The warnings disappeared and  I got the right image in the "test_output" folder.
> 3. You can copy the show_result_pyplot function to image_demo.py for easy debug.
> 4. show_result function is in mmseg\models\segmentors\base.py
> 
> Hope this can help you fix the problems.

i have used this method successfully,here i want to say some tips:
1)open the image_demo.py 
2)modified the show_result_pyplot function at "from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot"
3)when you open "the show_result_pyplot ",and write like this :
if hasattr(model, 'module'):
        model = model.module
    img_name=img.split("/")[-1].split(".")[0]
    print(img_name+" DONE!")
    img = model.show_result(img, result, palette=palette, show=False,out_file="./test_output/"+img_name+".png")
,you will see no show_results errors and get the right picture in "./test_output/"
