### ISSUE TITLE
About fcn_head in mmseg/decode_head

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1040]
感谢作者提供的框架，在使用中关于decode_head有一些问题想要咨询······
我正在尝试使用您提供的decode_head部分进行自己的网络搭建，并试图通过已有的结构简化搭建过程，目前想要使用FCN_head作为decoder部分，采用多尺度的搭建（类似于Unet的decoder结构），但似乎无法进行，我的config如下：
FCNHEAD（in_channels=[64，128，256，512]，in_index=[0，1，2]，channels=[64，128，256，512]，num_convs=2,concat_input=True,·······）
是因为FCN当前无法支持多层的搭建吗？
感谢答复

**Comment by MengzhangLI** [comment]
Hi, the `decode_head` could only use **one feature map** as input, in your description `in_channels=[64，128，256，512]` has four feature maps. So you could use `neck` between `backbone` and `decoder head` / `auxiliary head`. You can learn from [FastFCN](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fastfcn_r50-d32_jpu_psp.py) for more details.

Best,

**Comment by Lsz-20** [comment]
> Hi, the `decode_head` could only use **one feature map** as input, in your description `in_channels=[64，128，256，512]` has four feature maps. So you could use `neck` between `backbone` and `decoder head` / `auxiliary head`. You can learn from [FastFCN](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fastfcn_r50-d32_jpu_psp.py) for more details.
> 
> Best,

Thanks for your answer ，I'll try it first
