### ISSUE TITLE
Fast-SCNN ONNX export fails

### ISSUE THREAD

**Issue by skaldesh** [open-mmlab/mmsegmentation#1044]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When specifying `--verify` during ONNX export (`pytorch2onnx.py`), the export fails, because the outputs are too different. I am using the pretrained weights and config of Fast-SCNN.

**Reproduction**

1. What command or script did you run?

    ```none
    python tools/pytorch2onnx.py \
    fast_scnn.py \
    --checkpoint pretrained-fast-scnn.pth \
    --output-file model.onnx \
    --input-img test.jpg \
    --verify \
    --shape 896 1440
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I did not modify any code, I am using the config and pretrained weights from this repo: https://github.com/open-mmlab/mmsegmentation/tree/master/configs/fastscnn

3. What dataset did you use?
None needed for export

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

I am using the Dockerfile of this repo. I tested the export with both PyTorch version 1.6.0 and 1.8.1. Both yielded the same results.

**Error traceback**

```none
Use load_from_local loader
Successfully exported ONNX model: data/output/model
/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:353: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  "based on the build flags) when instantiating InferenceSession."
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 397, in <module>
    dynamic_export=args.dynamic_export)
  File "tools/pytorch2onnx.py", line 282, in pytorch2onnx
    err_msg='The outputs are different between Pytorch and ONNX')
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1529, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 842, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05
The outputs are different between Pytorch and ONNX
Mismatched elements: 55179 / 1290240 (4.28%)
Max absolute difference: 0.68421054
Max relative difference: 12.000001
 x: array([[[0.684211, 0.684211, 0.684211, ..., 0.684211, 0.684211,
         0.684211],
        [0.684211, 0.684211, 0.684211, ..., 0.684211, 0.684211,...
 y: array([[[0.684211, 0.684211, 0.684211, ..., 0.684211, 0.684211,
         0.684211],
        [0.684211, 0.684211, 0.684211, ..., 0.684211, 0.684211,...
```

## Question
Is the image I provided as input highly relevant? It is an image of a wooden log, so not part of the cityscapes dataset the model was trained with. Is that a problem?

**Comment by MengzhangLI** [comment]
Hi, thank you very much for your feedback.

@RunningLeon Sorry to bother you, could you have a look over this issue?

From description, the PyTorch version is 1.8.1 and `The outputs are different between Pytorch and ONNX` exists, so does that mean some mmcv operations of model `FastSCNN` itself is not compatible for vanilla ONNX? 

Best,

**Comment by RunningLeon** [comment]
@skaldesh Hi, small value differences between different backend is understandable. You may first compare shown results of PyTorch and ONNXRuntime and then, compare the two models with a dataset using the tool: https://github.com/open-mmlab/mmsegmentation/blob/master/tools/deploy_test.py. Could refer to https://github.com/open-mmlab/mmsegmentation/blob/master/docs/useful_tools.md#evaluate-onnx-model

**Comment by skaldesh** [comment]
@RunningLeon Thank you, that makes sense :)
