### ISSUE TITLE
Mosaic requires MultiImageDataset because of mix_results.

### ISSUE THREAD

**Issue by lkm2835** [open-mmlab/mmsegmentation#1045]
I think mosaic or mixup need [MultiImageDataset](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L289).

Because it requires [mix_results](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L2038) for other mixed image.

All I have to do is move [MultiImageDataset](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L289)?
If not, could you advise me how to adjust it to the semantic segmentation task?

Or just add mosaic transform first?

**Comment by Junjun2016** [comment]
Hi @lkm2835 
Sorry for the late reply.

> I think mosaic or mixup need MultiImageDataset.
> 
> Because it requires mix_results for other mixed image.
> 
> All I have to do is move MultiImageDataset?

Yes, exactly, for `Mosaic` augmentation, `MultiImageDataset` is also needed, should also move this `dataset_wrappers`.

Should adjust it carefully, since it is different between detection and segmentation, especially for annotations.

**Comment by Junjun2016** [comment]
Hi @lkm2835 
[ClassBalancedDataset](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L175) may be useful for the dataset with imbalanced or long-tailed distribution such as ADE20K, we can move it to mmseg in the future.

**Comment by Junjun2016** [comment]
> I think mosaic or mixup need [MultiImageDataset](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L289).
> 
> Because it requires [mix_results](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L2038) for other mixed image.
> 
> All I have to do is move [MultiImageDataset](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L289)? If not, could you advise me how to adjust it to the semantic segmentation task?
> 
> Or just add mosaic transform first?

Should also add browse dataset for [MultiImageMixDataset](https://github.com/open-mmlab/mmdetection/blob/dev-v2.18.1/tools/misc/browse_dataset.py#L65).

**Comment by Junjun2016** [comment]
Hi @lkm2835 
Do you have time to create some PRs?

**Comment by lkm2835** [comment]
> Hi @lkm2835 Do you have time to create some PRs?

Yes, I'm preparing for PR(mosaic).

But, I still lack understanding of dataset for mmseg.
