### ISSUE TITLE
UPerHead inplace operation ReLU not compatible with PyTorch 1.10?

### ISSUE THREAD

**Issue by thelittlekid** [open-mmlab/mmsegmentation#1046]
I upgraded my PyTorch version from 1.9.0 to 1.10, and an error occurs to `mmseg.models.decode_heads.UPerHead` at back-propagation. I'm using CUDA 11.1, mmcv-full 1.3.17, mmcv 1.3.17, and mmsegmentation 0.19.0. 
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [4, 512, 32, 32]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

The following codes works fine with PyTorch 1.9.0 but failed with PyTorch 1.10. 
```
import torch
from mmseg.models.decode_heads import UPerHead
from mmseg.ops import resize

decode_head = UPerHead(
    in_channels=[96, 192, 384, 768], in_index=[0, 1, 2, 3], pool_scales=(1, 2, 3, 6),
    channels=512, dropout_ratio=0.1, num_classes=150, align_corners=False
)

fake_data = [
    torch.rand(4, 96, 128, 128), torch.rand(4, 192, 64, 64), torch.rand(4, 384, 32, 32), torch.rand(4, 768, 16, 16)
]

outputs = decode_head(fake_data)
outputs = resize(input=outputs, size=(512, 512), mode='bilinear', align_corners=False)

loss = torch.nn.MSELoss()(outputs, torch.rand(outputs.shape))
loss.backward()
```
I'm not sure whether this should results from changes from the PyTorch side or a hidden issue at UPerHead. I also tried setting the `inplace=False` for all ReLU activation inside UPerHead, but it didn't resolve the issue. Let me know if you need further info.

**Comment by wangshaonian666** [comment]
I also met the same problem. Have you solved it?

**Comment by MengzhangLI** [comment]
Hi, @wangshaonian666 @thelittlekid 

Could you update MMSegmentation and MMCV to latest version and try again?

There are some bugs in MMCV 1.3.17.

**Comment by holyseven** [comment]
Having searched for a while, I found this issue is fixed by https://github.com/open-mmlab/mmsegmentation/pull/1103.
