### ISSUE TITLE
Request for pretrained model

### ISSUE THREAD

**Issue by yi94code** [open-mmlab/mmsegmentation#1049]
Could you please provide the pretrain vit model you used in SETR, i.e., 'pretrain/vit_large_patch16_384.pth' in the config file.

**Comment by RockeyCoss** [comment]
Hi, thanks for your feedback.

The pretrained model can be found [here](https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_vit_large_p16_384-b3be5167.pth). To use it, you need to use the scripts vit2mmseg.py in mmsegmentation/tools/model_converters/   to convert the keys. The usage is:
```bash
python vit2mmseg.py src dsc
```
for example:
```bash
python vit2mmseg.py pretrained/jx_vit_large_p16_384-b3be5167.pth pretrained/vit_large_patch16_384.pth
```
Then you can use the converted pretrained model by writing
 ```python
pretrained='pretrained/vit_large_patch16_384.pth'
```
in the config.

We will support downloading the pretrained model from mmcv's model zoo as soon as possible.

Best,

**Comment by yi94code** [comment]
Thanks a lot!

Best,
