### ISSUE TITLE
dataset folder 

### ISSUE THREAD

**Issue by caodroid** [open-mmlab/mmsegmentation#105]
hello， I saw the documentation you provided, I have  one question about the datasets  folder structure of this project: the dataset structure in the ducumentation is as follows: 
```
mmsegmentation
├── mmseg
├── tools
├── configs
├── data
│   ├── cityscapes
│   │   ├── leftImg8bit
│   │   │   ├── train
│   │   │   ├── val
│   │   ├── gtFine
│   │   │   ├── train
│   │   │   ├── val
│   ├── VOCdevkit
│   │   ├── VOC2012
│   │   │   ├── JPEGImages
│   │   │   ├── SegmentationClass
│   │   │   ├── ImageSets
│   │   │   │   ├── Segmentation
│   │   ├── VOCaug
│   │   │   ├── dataset
│   │   │   │   ├── cls
│   ├── ade
│   │   ├── ADEChallengeData2016
│   │   │   ├── annotations
│   │   │   │   ├── training
│   │   │   │   ├── validation
│   │   │   ├── images
│   │   │   │   ├── training
│   │   │   │   ├── validation
```
but the current structure is like this : 
```
mmsegmentation
├── mmseg
 |       |—— apis      
 |       |—— cores
 |       |—— datasets
 |       |        |—— piplines
 |       |        |——ade.py
 |       |        |——cityscape.py
 |       |        |——voc.py
 |       |        |——costume.py
```
I'd like to know whether the folder 'data' in documentation   is the folder 'datasets' in current project , if not, where should I put my own dataset,  looking forward to your reply, thank you for your work.  and if possible could you please update the documentation?

**Comment by caodroid** [comment]
or I should build a new folder--data like the structure in the documentation?

**Comment by xvjiarui** [comment]
Hi @caodroid 
You should create a new folder called `data`.

**Comment by caodroid** [comment]
> Hi @caodroid
> You should create a new folder called `data`.

ok ，thank you！
