### ISSUE TITLE
TensorRT inference without the need for PyTorch Tensor

### ISSUE THREAD

**Issue by timothylimyl** [open-mmlab/mmsegmentation#1051]
# Describe the feature

Allowing input from pycuda instead of using pytorch tensor. TensorRT inference script then does not need to rely on PyTorch.

**Motivation**

PyTorch takes up a lot of memory space in the GPU due to CUDA context allocation. In actual inference, it is best that there is no need for PyTorch tensors (No `import torch` necessary). PyTorch in most GPU I have tested uses up to 1-1.2GiB of VRAM for EACH script call.

No need to put `torch.no_grad()` too, separate TensorRT engine away from any dependencies to PyTorch.

**Related resources**

Examples of TensorRT inferences without PyTorch: https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5_trt.py

**Comment by MengzhangLI** [comment]
Hi, thanks for your feedback.

I will record it in our memo and discuss with my colleagues. 

Let's keep in contact for this issue.

Best,

**Comment by timothylimyl** [comment]
Noted, thank you for your work!
