### ISSUE TITLE
swin 转 onnx时roll 出错

### ISSUE THREAD

**Issue by daeing** [open-mmlab/mmsegmentation#1053]
RuntimeError: Exporting the operator roll to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
torch == 1.9.1
mmcv == 1.3.17

**Comment by MengzhangLI** [comment]
Hi, thanks for your feedback.

Right now swin transformer is not supported by our deployment. We would try to support it in the future if it is necessary.

**Comment by daeing** [comment]
> Hi, thanks for your feedback.
> 
> Right now swin transformer is not supported by our deployment. We would try to support it in the future if it is necessary.

hhhhhha, I was just wondering why, I noticed your group solve this problem, but the latest version fiiled.
