### ISSUE TITLE
Which `*.py` files are involved in TTA

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#1056]
Hi, dear atuhors!
Thank you for your amazing jobs!
Could you tell me which `*.py` files are involved in TTA?
Thank you!

**Comment by MengzhangLI** [comment]
When I run the command:
`python .tools/test.py ./configs/bisenetv1/bisenetv1_r50-d32_in1k-pre_4x4_1024x1024_160k_cityscapes.py
./work_dirs/bisenetv1/bisenetv1_r50-d32_in1k-pre_4x4_1024x1024_160k_cityscapes/bisenetv1_r50-d32_in1k-pre_4x4_1024x1024_160k_cityscapes_20210917_234628-8b304447.pth
--eval
mIoU
--aug-test`

The files are shown below:

![image](https://user-images.githubusercontent.com/24582831/142805803-6153bfb6-d85b-452a-9f4f-3869366d010f.png)


The main difference is `aug_test()`:
https://github.com/open-mmlab/mmsegmentation/blob/2b2f107fd6f52f6a516747bfb1a2a83f074f2448/mmseg/models/segmentors/encoder_decoder.py#L267

**Comment by zhongqiu1245** [comment]
@MengzhangLI Thank you!

**Comment by zhongqiu1245** [comment]
@MengzhangLI Sorry to bother you again.
Could you tell me how did you display your "Main Thread"?
Thank you!

**Comment by MengzhangLI** [comment]
It is based on PyCharm and in debug mode. You can try to use it becuase it is very convenient.
