### ISSUE TITLE
[Doc] Main figure of modles in MMSegmentation

### ISSUE THREAD

**Issue by MengzhangLI** [open-mmlab/mmsegmentation#1059]
We would like to add main figure and abstract of each model in our repo. This issue is used for uploading figures for hyperlink in README.md

**Comment by MengzhangLI** [comment]
ANN:
![image](https://user-images.githubusercontent.com/24582831/142898322-3bbd578c-e488-4bae-9c14-7598adac5cbd.png)

APCNet:
![image](https://user-images.githubusercontent.com/24582831/142898638-e1c0c6ae-9270-448e-aa01-bbac3a236db5.png)

BiSeNetV1:
![image](https://user-images.githubusercontent.com/24582831/142898839-a0a78148-848a-41b2-8682-b1f61ac004ba.png)


BiSeNetV2:
![image](https://user-images.githubusercontent.com/24582831/142898966-ec4a81da-b4b0-41ee-b083-1d964582c18a.png)

CCNet:
![image](https://user-images.githubusercontent.com/24582831/142899159-b329c12a-0fde-44df-8718-def6cfb004e4.png)

CGNet:
![image](https://user-images.githubusercontent.com/24582831/142900351-89559574-79cc-4f57-8f69-5d88765ec38d.png)

DANet:
![image](https://user-images.githubusercontent.com/24582831/142900467-f832fdb9-3b7d-47d3-8e80-e6ee9303bdfb.png)

DeepLabV3:
![image](https://user-images.githubusercontent.com/24582831/142900575-f30a7755-09aa-406a-bf78-45893a61ee9a.png)

DeepLabV3+:
![image](https://user-images.githubusercontent.com/24582831/142900680-3e2c3098-8341-4760-bbfd-b1d7d29968ea.png)

DMNet:
![image](https://user-images.githubusercontent.com/24582831/142900781-6215763f-8b71-4e0b-a6b1-c41372db2aa0.png)

DNL:
![image](https://user-images.githubusercontent.com/24582831/142900944-b8d93301-d2ce-488e-a461-b0813f96be49.png)

DPT:
![image](https://user-images.githubusercontent.com/24582831/142901057-00aabea5-dab4-43d3-a14a-5f73eb5dd9b9.png)

EMANet:
![image](https://user-images.githubusercontent.com/24582831/142901186-7bfe15e2-805a-420e-81b0-74f214f20a36.png)

EncNet:
![image](https://user-images.githubusercontent.com/24582831/142901276-b364fbbf-3bdb-4000-9d31-b9a135e30935.png)

FastFCN:
![image](https://user-images.githubusercontent.com/24582831/142901374-6e0252ab-6e0f-4acd-86ad-1e9f49be3185.png)

Fast-SCNN:
![image](https://user-images.githubusercontent.com/24582831/142901444-705b4ff4-6d1e-409b-899a-37bf3a6b69ce.png)

FCN:
![image](https://user-images.githubusercontent.com/24582831/142901525-fd0d2bf4-9a47-4143-85f5-3cee8849eaa4.png)

GCNet:
![image](https://user-images.githubusercontent.com/24582831/142901601-ad17922e-2538-4b48-9f51-84a57d44b12b.png)

HRNet:
![image](https://user-images.githubusercontent.com/24582831/142901680-64c285bc-669f-4924-b054-46a2f07c5427.png)

ICNet:
![image](https://user-images.githubusercontent.com/24582831/142901772-4570455d-7b27-44ae-a690-47dd9fde8445.png)

ISANet:
![image](https://user-images.githubusercontent.com/24582831/142901868-03d80da4-b9c0-4df9-8509-5f684ba9dadc.png)

MobileNetV2:
![image](https://user-images.githubusercontent.com/24582831/142901935-fa22700e-4b77-477f-90b9-334a4197506f.png)

MobileNetV3:
![image](https://user-images.githubusercontent.com/24582831/142902036-3dc2e0c0-d475-4816-b1ac-961836b41f5c.png)

NonLocal:
![image](https://user-images.githubusercontent.com/24582831/142902128-17e29678-bf12-4ff4-b3d6-a39b47dfd253.png)

OCRNet:
![image](https://user-images.githubusercontent.com/24582831/142902197-b06b1e04-57ab-44ac-adc8-cea6695bb236.png)

PointRend:
![image](https://user-images.githubusercontent.com/24582831/142902293-5db49cdd-4b1b-4940-9067-2acd6196c700.png)

PSANet:
![image](https://user-images.githubusercontent.com/24582831/142902367-0f29e8cb-5ac0-434b-98c4-b2af7c9c2e58.png)

PSPNet:
![image](https://user-images.githubusercontent.com/24582831/142902444-9f93b99e-9261-443b-a0a4-17e78eefb525.png)

ResNest:
![image](https://user-images.githubusercontent.com/24582831/142902526-3cf33345-7e40-47a6-985e-4381857e21df.png)

SegFormer:
![image](https://user-images.githubusercontent.com/24582831/142902600-e188073e-5744-4ba9-8dbf-9316e55c74aa.png)

FPN:
![image](https://user-images.githubusercontent.com/24582831/142902694-03ed2131-9104-467b-ace1-c74c62fb7177.png)

SETR:
![image](https://user-images.githubusercontent.com/24582831/142902777-ee2d34b7-a631-4fa7-ad68-118ff5716afe.png)

SwinTransformer:
![image](https://user-images.githubusercontent.com/24582831/142902882-3fb9014c-11b6-47e9-aa14-500dfe7cbb1c.png)

UNet:
![image](https://user-images.githubusercontent.com/24582831/142902977-20fe689d-a147-4d92-9690-dbfde8b68dbe.png)

UPerNet:
![image](https://user-images.githubusercontent.com/24582831/142903077-44e8e0da-7276-4bda-bd2b-0df1680ca845.png)

ViT:
![image](https://user-images.githubusercontent.com/24582831/142903144-f80a12cc-8698-48ab-843c-49dedf558121.png)

**Comment by MengzhangLI** [comment]
ERFNet:
![image](https://user-images.githubusercontent.com/24582831/143479729-ea7951f6-1a3c-47d6-aaee-62c5759c0638.png)

**Comment by MengzhangLI** [comment]
STDC-Seg

![image](https://user-images.githubusercontent.com/24582831/143640374-d0709587-edb2-4821-bb60-340035f6ad8f.png)

**Comment by MengzhangLI** [comment]
Twins

![image](https://user-images.githubusercontent.com/24582831/145021310-57826cf5-5e03-4c7c-9081-ffa744bdae27.png)

**Comment by MengzhangLI** [comment]
segmenter

![image](https://user-images.githubusercontent.com/24582831/148507554-87eb80bd-02c7-4c31-b102-c6141e231ec8.png)

**Comment by MengzhangLI** [comment]
K-Net
![image](https://user-images.githubusercontent.com/24582831/157008300-9f40905c-b8e8-4a2a-9593-c1177fa35b2c.png)

**Comment by RockeyCoss** [comment]
HRFormer
![图片](https://user-images.githubusercontent.com/41846794/160131437-46a06d14-549b-41c4-9fc0-e4785fb63468.png)

**Comment by linfangjian01** [comment]
![image](https://user-images.githubusercontent.com/93248678/160155362-2e707c53-f797-4abb-98b0-809db566c64e.png)

**Comment by linfangjian01** [comment]
BEiT

**Comment by linfangjian01** [comment]
BEiT 
![image](https://user-images.githubusercontent.com/93248678/160155758-781c9a45-b1d7-4530-9015-88eca6645006.png)

**Comment by MengzhangLI** [comment]
MAE

![image](https://user-images.githubusercontent.com/24582831/165456416-1cba54bf-b1b5-4bdf-ad86-d6390de7f342.png)

**Comment by MengzhangLI** [comment]
MaskFormer

![image](https://user-images.githubusercontent.com/24582831/199215459-ea507126-aafe-4823-8eb1-ae6487509d5c.png)

**Comment by MengzhangLI** [comment]
SegNeXt:

![screenshot-20230131-145308](https://user-images.githubusercontent.com/24582831/215688018-5d4c8366-7793-4fdf-9397-960a09fac951.png)
