### ISSUE TITLE
Model predicts whole image as one class

### ISSUE THREAD

**Issue by Fschoeller** [open-mmlab/mmsegmentation#1061]
Hi! 
I have a custom dataset with "trail" being my only class.
I have structured my data folder as suggested in [docs/tutorials/customize_datasets.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md) with the pixel values of my annotations being 0 for background and 1 for trail.

When training a model, the model becomes lazy and predicts the whole image as being trail.

What am I doing wrong?
Thanks,

Here is my config file: 
```
_base_ = ['../segformer/segformer_mit-b0_512x512_160k_ade20k.py']

model = dict(pretrained=None, decode_head=dict(num_classes=1, loss_decode=dict(type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)))

dataset_type = 'CustomDataset'
classes = ['trail']
data_root = 'data'

img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

crop_size = (512, 1024)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(type='Resize', img_scale=(2048, 1024), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 1024),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        reduce_zero_label=False,
        data_root=data_root,
        img_dir='img_dir/train',
        ann_dir='ann_dir_trail/train',
        pipeline=train_pipeline,
        classes=classes),
    val=dict(
        type=dataset_type,
        reduce_zero_label=False,
        data_root=data_root,
        img_dir='img_dir/val',
        ann_dir='ann_dir_trail/val',
        pipeline=test_pipeline,
        classes=classes),
    test=dict(
        type=dataset_type,
        reduce_zero_label=False,
        data_root=data_root,
        img_dir='img_dir/val',
        ann_dir='ann_dir_trail/val',
        pipeline=test_pipeline,
        classes=classes))
```

**Comment by MengzhangLI** [comment]
Hi, it should be `num_classes=2`.

For example, you can see [UNet](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/unet) and its base config file:

https://github.com/open-mmlab/mmsegmentation/blob/2b2f107fd6f52f6a516747bfb1a2a83f074f2448/configs/_base_/models/fcn_unet_s5-d16.py#L31

FYI: UNet model in our config README is all about binary segmentation in medical image. If you a green hand in MMSegmentation, you may use our provided UNet model config for training, it is somewhat not too big and easy to understand.

**Comment by Fschoeller** [comment]
Thank you for the reply.
with `num_classes=2` the model predicts the whole image as background instead.  
The same happens with UNet.

![image](https://user-images.githubusercontent.com/50424441/142996965-ee5c1dd8-fb73-4ac6-a5dd-3b50976b5087.png)

**Comment by MengzhangLI** [comment]
OK, I see. I think we may train again using new config file on this customized dataset.

Or perhaps using existing models may not work well on this customized dataset.

**Comment by Fschoeller** [comment]
Existing models should work, I have trained a simple FPN segmentor successfully using another repository.

**Comment by Fschoeller** [comment]
Data also looks fine when using `tools/browse_dataset.py` :
![image](https://user-images.githubusercontent.com/50424441/143002131-4ab02f0c-9194-4b2c-af63-03b7d8972ffe.png)

**Comment by Fschoeller** [comment]
found some misleading examples in the dataset. The model seems to work after these have been removed.
Thanks.

**Comment by MengzhangLI** [comment]
> found some misleading examples in the dataset. The model seems to work after these have been removed. Thanks.

Hi, very happy you solve it!

Could you point out those misleading statements so we can fix them? 

Thank you!

**Comment by Fschoeller** [comment]
By misleading examples, I meant my dataset included some images that confused the model.
