### ISSUE TITLE
How to use 'RepeatDataset' to augment the validation and test dataset? It throws an error 'AttributeError: 'RepeatDataset' object has no attribute 'pre_eval''

### ISSUE THREAD

**Issue by bowenroom** [open-mmlab/mmsegmentation#1063]
Dear contributors:
I try to augment the validation and test dataset like train set using "RepeatDataset", but I get an error when I run the code `train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
                meta=dict())`
the error is `AttributeError: 'RepeatDataset' object has no attribute 'pre_eval'`,
the data config file is like the following
```xml
cfg.data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='RepeatDataset',
        times=100,
        dataset=dict(
            type=cfg.dataset_type,
            data_root=cfg.data_root,
            img_dir='2_Ortho_RGB/training',
            ann_dir='5_labels_for_participants/training',
            pipeline=cfg.train_pipeline
            )),
     val=dict(
        type='RepeatDataset',
        times=100,
        dataset=dict(
            type=cfg.dataset_type,
            data_root=cfg.data_root,
            img_dir='2_Ortho_RGB/validation',
            ann_dir='5_labels_for_participants/validation',
            pipeline=cfg.test_pipeline
            )
            ),           
     test=dict(
        type='RepeatDataset',
        times=100,
        dataset=dict(
            type=cfg.dataset_type,
            data_root=cfg.data_root,
            img_dir='2_Ortho_RGB/validation',
            ann_dir='5_labels_for_participants/validation',
            pipeline=cfg.test_pipeline
            )
            )
)
```
My validation and test set is so small, it only contains 5 images and I want to augment 100 times.  When I run the following code ``, everything is right and the model is training again.

![image](https://user-images.githubusercontent.com/13314638/143028149-99f91f25-1880-480e-9741-e230741d8ceb.png)

 What is wrong with it? Can I augment the validation and test set,  Looking forward your reply! BIG THANKS!!

**Comment by FreyWang** [comment]
RepeatDataset should not be used in val/test dataset, can try `MultiScaleFlipAug`

**Comment by MengzhangLI** [comment]
You just need to add `--aug-test` in your command to get data augmentation with multiple scales and flipping.

https://github.com/open-mmlab/mmsegmentation/blob/520ec8e12851bcf05e34beeaee7e58bc17346ae2/tools/test.py#L30
