### ISSUE TITLE
 Asymmetric Loss

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#1064]
**Describe the feature**
An effective Loss to balance the postive samples and negtive samples.

**Related resources**
offical paper: https://arxiv.org/abs/2009.14119
offical code: https://github.com/Alibaba-MIIL/ASL
open_mmlab code(mmcls): https://github.com/open-mmlab/mmclassification/blob/master/mmcls/models/losses/asymmetric_loss.py

Thank you!

**Comment by MengzhangLI** [comment]
Hi, it's noted but we do not have clear time schedule due to limited human resources.

PR of you is welcomed!

**Comment by MengzhangLI** [comment]
I just scaned related pr. It won't take too much time to transfer to mmsegmentation.

If time available, I would like to add it. But it would be better if you could make a pr and we review it because we want more community members getting involved.

Best,

**Comment by zhongqiu1245** [comment]
Sorry for the late reply.
I haven't create pr yet, so I am learning it.
If time available, I will create pr about Asymmetric Loss.

**Comment by MengzhangLI** [comment]
Here are some steps:

(1) Installation of MMSegmentation.
Please refer to [get_started.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/get_started.md#installation) for installation and [dataset_prepare.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/dataset_prepare.md#prepare-datasets) for dataset preparation.

(2) Making a pull request.
Usefule links: [Contributing to OpenMMLab](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) and [Chinese article from zhihu](https://zhuanlan.zhihu.com/p/339080395).

(3) Support the Asymmetric Loss. 
Usefule links: [doc of customized loss function](https://github.com/open-mmlab/mmsegmentation/blob/master/docs_zh-CN/tutorials/customize_models.md) and [PR about supporting focal loss](https://github.com/open-mmlab/mmsegmentation/pull/1024).

**Comment by zhongqiu1245** [comment]
@MengzhangLI thx！
