### ISSUE TITLE
Log evaluation metrics to wandb

### ISSUE THREAD

**Issue by Fschoeller** [open-mmlab/mmsegmentation#1068]
How do I log evaluation metrics to wandb?

Thanks

**Comment by MengzhangLI** [comment]
Sorry, right now MMSegmentation does not support wandb.

Hoping this [chinese blog](https://blog.csdn.net/jy1023408440/article/details/112870945) for mmdetection & wandb may be helpful to you.

**Comment by MengzhangLI** [comment]
Hi, you can use WandbLoggerHook from [mmcv](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/wandb.py).

FYI, here is chinese blog about [mmdetection](https://blog.csdn.net/jy1023408440/article/details/112870945).

**Comment by Fschoeller** [comment]
I am already using WandbLoggerHook, but it fails to log validation:

![image](https://user-images.githubusercontent.com/50424441/143239477-b0be8a1d-ad67-4dae-bad3-294cda11b3ba.png)

**Comment by MengzhangLI** [comment]
> I am already using WandbLoggerHook, but it fails to log validation:
> 
> ![image](https://user-images.githubusercontent.com/50424441/143239477-b0be8a1d-ad67-4dae-bad3-294cda11b3ba.png)

Hi, what is your mmcv version? Here is related [pr](https://github.com/open-mmlab/mmcv/pull/1390). 

It has not been merged yet. Could you try to modify your mmcv and test it? 

Looking forward to your reply!

**Comment by Fschoeller** [comment]
mmcv is version 1.3.18
The above pr does not work for mmsegmentation. 
If the log function is changed to 
```
@master_only
    def log(self, runner):
        tags = self.get_loggable_tags(runner)
        if tags:
            tags['global_step'] = self.get_iter(runner)
            self.wandb.log(tags, commit=self.commit)
```
it works. The logged steps will be offset though.

**Comment by MengzhangLI** [comment]
> 

Very happy this problem is solved! 

I have noted your solution above. Thank you!

**Comment by lorinczszabolcs** [comment]
For me it was solved by adding ```with_step=False``` in ```WandbLoggerHook```
