### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by joshmyersdean** [open-mmlab/mmsegmentation#1070]
Hello!

Thank you for the amazing work. Is it possible to perform inference on CPU? I tried with the installation verification script but no luck.

Thank you!

**Comment by MengzhangLI** [comment]
Hi, thanks for your appreciation. 

Currently GPU environment is necessary because some operations in mmcv needs cuda.

**Comment by joshmyersdean** [comment]
Understandable, thank you for the response!
