### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by sunshiding** [open-mmlab/mmsegmentation#1073]
Hello. I am using the latest version of mmsegmentation and encountered a problem during testing. When I execute --show-dir, an error is reported, but when I don’t execute --show-dir, the evaluation can be done normally.

python tools/test.py ./configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_10k_voc12.py ./work_dirs/deeplabv3plus_r50-d8_512x512_10k_voc12/iter_6000.pth --eval mIoU mDice mFscore --show-dir deeplabv3plus_r50-d8_512x512_10k_voc12_results

The error is as follows,

load checkpoint from local path: ./work_dirs/deeplabv3plus_r50-d8_512x512_10k_voc12/iter_10000.pth
[                                                  ] 0/115, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 229, in <module>
    main()
  File "tools/test.py", line 191, in main
    format_args=eval_kwargs)
  File "/home/sunshiding/mmsegmentation-master/mmseg/apis/test.py", line 130, in single_gpu_test
    opacity=opacity)
  File "/home/sunshiding/mmsegmentation-master/mmseg/models/segmentors/base.py", line 247, in show_result
    color_seg = np.zeros((seg.shape[0], seg.shape[1], 3), dtype=np.uint8)
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by MengzhangLI** [comment]
Hi, thanks for your feedback.

We have noticed potential bug about `--show-dir`. We would fix it as soon as possible.

**Comment by MengzhangLI** [comment]
Hi, @sunshiding. This bug is fixed by @zergzzlun. Please have a look on related PR.

Best,

**Comment by sunshiding** [comment]
> Hi, @sunshiding. This bug is fixed by @zergzzlun. Please have a look on related PR.
> 
> Best,

Thank you very much, I have modified the code according to your guidance, and this problem has been solved.

**Comment by hblab-haims** [comment]
I got the same error.

While debuging, it seems that `result` at `mmseg/models/segmentors/base.py` (in attached image) is a tuple of list of tensor, which has no shape.
![image](https://user-images.githubusercontent.com/89757661/145794670-8101595c-107f-4617-b461-8020dda44cac.png)

![image](https://user-images.githubusercontent.com/89757661/145794954-a64cc04d-920b-4a00-9e61-f508fddb716f.png)

**Comment by hblab-haims** [comment]
This PR fixed it perfectly.
https://github.com/open-mmlab/mmsegmentation/pull/1091

Please close this issue.
