### ISSUE TITLE
关于可视化的问题

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1080]
您好，小白想要求助一下：
似乎目前并未提供feature map attention map之类的操作是吗？
如果想要进行这类的可视化的话，在您提供的集成的大型框架下推荐那种方法进行呢？以及应该在哪个文档中进行修改呢？
感谢您的回复！

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Currently these visualization functions are not supported yet on MMSegmentation.
