### ISSUE TITLE
关于pretrain转换问题

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1081]
您好，我正在试图加载官方提供的预训练模型进行试验运行，但是遇到了以下问题：
使用了官方提供的模型转换器，即swin2mmseg试图对pretrain/swin_base_patch4_window7_224.pth(官方链接‘https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_base_patch4_window7_224.pth’下载的)进行转换
但是出现了报错：
![image](https://user-images.githubusercontent.com/60343452/143793138-a2b01abe-c634-4514-bd43-0f164bd2897c.png)

感谢回复

**Comment by zzr9zzr** [comment]
you should change the path to ../pretrain/swin_base_patch4_window7_224.pth
