### ISSUE TITLE
Pretraining weights

### ISSUE THREAD

**Issue by sunshiding** [open-mmlab/mmsegmentation#1082]
Hello, I have the following questions about pretraining:

1. I found the link on “https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json”, which provides a lot of model weights. Are these weights trained on ImageNet?

**Comment by MengzhangLI** [comment]
Yes, it's ImageNet but not ImageNet-21K.

**Comment by Italy2006** [comment]
> 

Do you have models pre-trained on other datasets? For example coco, mapillary
