### ISSUE TITLE
Some unexpected ops in onnx

### ISSUE THREAD

**Issue by PuNeal** [open-mmlab/mmsegmentation#1084]
Hello, I try to export unet model to onnx format and succeed. But I find some unexpected ops in the onnx format as below. Could you please tell me how to remove these ops? Thanks a lot!
![image](https://user-images.githubusercontent.com/39493003/143854255-11db2e26-ece0-4c83-80f6-b758896423cf.png)

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

@RunningLeon Sorry to bother you, could you have a look at this PR? Thanks so much!

Best,

**Comment by RunningLeon** [comment]
> Hello, I try to export unet model to onnx format and succeed. But I find some unexpected ops in the onnx format as below. Could you please tell me how to remove these ops? Thanks a lot! ![image](https://user-images.githubusercontent.com/39493003/143854255-11db2e26-ece0-4c83-80f6-b758896423cf.png)

Hi, you could use ONNX python API to load your onnx model, edit and then save it. Could refer to ONNX [tutorial](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md).
