### ISSUE TITLE
About customize collate_fn when i have multi-source dataset

### ISSUE THREAD

**Issue by MHX1203** [open-mmlab/mmsegmentation#1098]
Now i have a scene like this， I have multiple source dataset, each dataset have different label format(because different loss need), So i can not use the general collate_fn.

I used to create a dataloader packed multiple dataloader, and customize collate_fn to solve this problem before. but it can not use multi-gpu to train my model.

I wonder if mmsegmentation support customize collate_fn to pack multiple dataset with different format.

if any one can help me , i will be grateful. thanks.

**Comment by MengzhangLI** [comment]
This enhancement is not supported by MMSegmentation. You can only use multiple losses with `ignore_index` on total dataset.

**Comment by MHX1203** [comment]
Thank you very much.
