### ISSUE TITLE
关于LoveDA数据集

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1099]
您好 非常感谢您提供了新的LoveDA数据集，但是当我使用时出现了以下问题（下载的是官方提供的数据集）
![image](https://user-images.githubusercontent.com/60343452/144429513-2bef3ce7-0e4a-4f24-86d0-db48df4da2ec.png)

感谢解答

**Comment by MengzhangLI** [comment]
Please update mmcv and mmsegmentation version. I think it is caused by version conflict.
