### ISSUE TITLE
Can I use this toolbox for 3D Segmentation?

### ISSUE THREAD

**Issue by moshicaixi** [open-mmlab/mmsegmentation#1100]
I want to consult weather this toolbox is only designed for 2D image segmentation. Can I used it for 3D segmentation, such as Point Clouds Segmentation and 3D Voxel segmentation? If it can, how should I modify it for 3D usage. I'm looking forward to your reply and advice.

**Comment by MengzhangLI** [comment]
Hi, sorry to tell you right now MMSegmentation only support 2D. We want to do 3D segmentation such as medical image but it needs many code modifications, hoping we could support it in the future.

**Comment by wzr0108** [comment]
Does it support 3D segmentation now?

**Comment by thiagoribeirodamotta** [comment]
Bump
