### ISSUE TITLE
what can i do when i convert pytorch model to onnx if the size of the input of my model is more than one?

### ISSUE THREAD

**Issue by xuhaoda1995** [open-mmlab/mmsegmentation#1104]
if my header's forward_test function is this:
```
def forward_test(self, imgs, img_metas, return_loss, mask, indices):
   pass
```

when using pytorch2onnx.py, how to set the args of torch.onnx.export function. 

I try to set mask and indices into dict, but got error which got `forward() got multiple values for argument 'img_metas'`. but the code is already set partial 
```
model.forward = partial(
        model.forward,
        img_metas=img_meta_list,
        return_loss=False)
```

**Comment by MengzhangLI** [comment]
Hi, @RunningLeon sorry to bother you, could you have a look at this issue?

Thanks in advance!

Best,

**Comment by RunningLeon** [comment]
> model.forward

@xuhaoda1995 You may check what's `forward` function is like. Since you used partial function with `model.foward`, not `model.forward_test`
