### ISSUE TITLE
CascadeEncoderDecoder

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmsegmentation#1107]
Hi,
I have some questions about CascadeEncoderDecoder and I hope to get your help. I noticed that only ocrnet uses CascadeEncoderDecoder. Can I combine other decoder heads, such as aspp_head and fcn_head with the backbone of resnet50?
In addition, is the CascadeEncoderDecoder  a parallel or serial decoding method?
Thanks!

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply. Did you solve this problem?

`Can I combine other decoder heads, such as aspp_head and fcn_head with the backbone of resnet50?`

Technically it can not combine more decoder head, but you can try to modify existing `FCNHead` to other head.

Best,
