### ISSUE TITLE
Cannot add more augmentations by train options

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#1113]
We only have 11 methods at the time of definition, but we want to add some additional data enhancement methods by train options.

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=img_scale, ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]

command line is :
./tools/dist_train.sh projects/configs/landcover/fcn_hr18_1024x1024_16k_landcover.py 1 \
--options \
data.train.pipeline.12.type="add_aug" 

Bug as reported 
![image](https://user-images.githubusercontent.com/18137551/145018817-44c92d30-9b26-4f99-b373-9173a39ae66f.png)

**Comment by jianlong-yuan** [comment]
any news?

**Comment by MengzhangLI** [comment]
Sorry for late reply. Could it run well if you set `add_aug` in config file directly?

Those keys like 'RandomFlip', 'PhotoMetricDistortion' and 'RandomCrop' are defined [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/transforms.py), you can add your customization and try again. Here is related augmentation pr https://github.com/open-mmlab/mmsegmentation/pull/1022.

Hoping it is helpful to you.
