### ISSUE TITLE
训练好后如何剥离框架？

### ISSUE THREAD

**Issue by caihaunqai** [open-mmlab/mmsegmentation#1114]
您好，想请问训练某个模型之后，希望不用框架，只保留一个模型的代码来运行，能实现吗？ 比如一个inference代码加一个model就可以解决。

**Comment by MengzhangLI** [comment]
You could use [MIM](https://github.com/open-mmlab/mim).

example repo: https://github.com/azxj/SFNet#usage
Chinese article: https://zhuanlan.zhihu.com/p/374066177
