### ISSUE TITLE
Help！！！Problems encountered at the beginning of training！

### ISSUE THREAD

**Issue by tensorflowt** [open-mmlab/mmsegmentation#1117]
Hi！
I recently started running the Swin seg task with your project, but encountered the following problems at the beginning：
![481c278bf8decfccc452b72410803a9](https://user-images.githubusercontent.com/37217594/145238789-a98c1980-4e4c-4ba7-a82b-f6aae33aee3e.png)
What I understand is that my hardware doesn't have enough computing power！
My graphics card information is as follows：
![873b4e46eca59ef238e2fd8a0fe202e](https://user-images.githubusercontent.com/37217594/145238901-389aac4c-a10c-4cb2-9001-b4cea73c607d.png)
For this problem I looked up the solution on the Internet, and tried the following scheme：
1）change 
`backbone_norm_cfg = dict(type='SyncBN',requires_grad=True)`
to
`backbone_norm_cfg = dict(type='BN',requires_grad=True)`
2）Reduce batch_size, but can't find where to modify？

By the way,I was able to train the FCN model.

Can you help me ? thx!

Goodluck!

**Comment by MengzhangLI** [comment]
You may set [`cudnn_benchmarn=False`](https://github.com/open-mmlab/mmsegmentation/blob/7a1c9a5499dc2bfa28e506476c68cbdd0980395b/configs/_base_/default_runtime.py#L14). Here is related [issue](https://github.com/open-mmlab/mmsegmentation/issues/1029).

**Comment by Junjun2016** [comment]
Reduce crop size and batch size.
