### ISSUE TITLE
How to generate colorful ground truth for qualitative comparison?

### ISSUE THREAD

**Issue by yan-hao-tian** [open-mmlab/mmsegmentation#1122]
Hello, the arg "--show-dir" can generate visualization results during evaluation. Is there a tool script capable of generating correponding ground truth in color for a clear comparsion?

**Comment by MengzhangLI** [comment]
Hi, as fat as I know, related tool script is not supported. You may `PALETTE` like here: 

https://github.com/open-mmlab/mmsegmentation/blob/ff044c53f48fb39b5c52335df005df01753094f9/mmseg/datasets/cityscapes.py#L26

And find its corresponding class and `num_classes` id to draw the picture.

**Comment by rumozam** [comment]
Hey @yan-hao-tian! Did you solve this? 😊
