### ISSUE TITLE
关于版权和license

### ISSUE THREAD

**Issue by xiaoachen98** [open-mmlab/mmsegmentation#1123]
您好，我是做UDA segmentation的。
近期，我想参照 mmseg，自己实现一个基于mmcv和mmseg的UDA segmentation库，一方面用于接下来的论文发表，一方面可能用于构建UDA segmentation任务的开源库，不知道需要注意到哪些版权问题和引用问题？

**Comment by MengzhangLI** [comment]
Hi, this project is released under the [Apache 2.0 license](https://github.com/open-mmlab/mmsegmentation/blob/master/LICENSE).

UDA segmentation is in consideration of us, here is another repo using [mmseg](https://github.com/lhoyer/DAFormer). Currently we do not have clear time schedule on domain adaptation.

BTW, if you want to contribute to MMSegmentation, PR is also welcomed!

Best,

**Comment by xiaoachen98** [comment]
> 

我意思是，假如，我基于MMCV，开发了一个新的库，名为MMDASeg（一开始是为了我自己的论文服务），我可否把相关名称换为我的MMDASeg，然后贴上MMCV和MMSeg的引用。

**Comment by MengzhangLI** [comment]
Sorry, I am not sure about it. 

Personally, I think you can rename any name on your repo for pure research.
