### ISSUE TITLE
mmcv download error

### ISSUE THREAD

**Issue by mao12x** [open-mmlab/mmsegmentation#1125]
Follow the official tutorial instructions to create a virtual environment, but an error is reported when it is running. The online query says that the version of mmcv does not match. I want to ask what is going on?

![image](https://user-images.githubusercontent.com/74081747/145704938-aff225c1-5070-4462-8c23-2e4147667d0f.png)
This is the warning reported when downloading, and  my pytorch is 1.9.0, cuda is 10.1

**Comment by mao12x** [comment]
Successfully installed addict-2.4.0 mmcv-full-1.4.0 opencv-python-4.5.4.60 packaging-21.3 pyparsing-3.0.6 pyyaml-6.0 yapf-0.31.0
下载结果是这么说的，mmcv-full的版本是相对于我的pytorch和cuda版本过高了吗

**Comment by MengzhangLI** [comment]
Hi, from the error it is "ConnectTimeoutError", which is always caused by bad internet environment.

BTW, could you translate title and description of your issue into English? Using English is more appreciated for better discussion around the world.

**Comment by mao12x** [comment]
Can you tell me how to deal with it?I downloaded the corresponding mmcv on the server, but the network is not good. I directly opened the URL where I downloaded mmcv on my computer, but there is a list of downloadable ones. I don’t know which one to download? Can you tell me which one to download and download it locally, upload it to the server and install it locally?

**Comment by mao12x** [comment]
My problem has been solved. I downloaded the corresponding file to the local and then uploaded it to the server for installation.

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

If you meet same problem in the future, you could download `.whl` file and pip install it directly. Details could find [here](https://download.openmmlab.com/mmcv/dist/cpu/torch1.10.0/index.html), please check suitable versions of mmcv, python, os and so on.

Best,
