### ISSUE TITLE
about “accumulation gradient“ 

### ISSUE THREAD

**Issue by wusitong98** [open-mmlab/mmsegmentation#1132]
Accumulation gradient is a common trick when GPU memory is limited. It is widely used in ImageNet pretrain. However, some of the Transformer segmentation models consume a lot of memory. Under the condition of limited GPUs, it is urgent to use this trick to achieve the same batch size as the original paper.
Thus, I wonder if mmsegmentation can support "accumulation gradient" as an argparse option for convenience.

**Comment by Junjun2016** [comment]
Hi @wusitong98 
Please refer to https://github.com/open-mmlab/mmcv/pull/1221.
Can add this usage to our doc, please create a PR, thanks.

**Comment by wusitong98** [comment]
Ok, Thanks.  Sorry for my confusion between "issue" and "PR"

**Comment by Junjun2016** [comment]
Please create a PR to add the usage of accumulation gradient to our doc, thanks.
