### ISSUE TITLE
Is there way doing real-time inference on python/pytorch??

### ISSUE THREAD

**Issue by larcane97** [open-mmlab/mmsegmentation#1142]
Is there way doing real-time inference on python/pytorch??
I trained model and got checkpoint(weights), and I want to deploy this model on flask/fastapi.
There is mmsegmentation/utils/test.py for infernce, But It doesn't seem appropriate to use this for real-time processing.
Do you have any way for real-time processing without converting this to onnx or others??

**Comment by MengzhangLI** [comment]
No, real-time processing of MMSegmentation is based on deployment, such as tensorrt and onnx.

**Comment by larcane97** [comment]
> No, real-time processing of MMSegmentation is based on deployment, such as tensorrt and onnx.
> 
> BTW, deployment framework for total OpenMMLab codebases is on the way, please wait for some time.

Thank you for reply :)
