### ISSUE TITLE
Support for semi-supervised loss (-or- partially unlabeled data)

### ISSUE THREAD

**Issue by litaws** [open-mmlab/mmsegmentation#1147]
# Describe the feature

**Motivation**
Allow training with some unlabeled data

**Related resources**
* [Adaptive Equalization Learning (NeurIPS 2021)](https://github.com/hzhupku/SemiSeg-AEL)
* [semanticGAN (CVPR 2021)](https://github.com/nv-tlabs/semanticGAN_code)
* also mentioned here: #338

And these which are more DA than SSL, but still...
* [Self-supervised Augmentation Consistency for Adapting Semantic Segmentation(CVPR 2021)](https://github.com/visinf/da-sac)
* [PixDA (WACV 2022)](https://github.com/taveraantonio/PixDA) 

**Additional context**
Not sure if this is trivial or highly involved

**Comment by MengzhangLI** [comment]
Hi, pull requeset is welcome!

By the way, semi-supervised task needs many modification of our codebases.

**Comment by litaws** [comment]
> Hi, pull requeset is welcome!
> 
> By the way, semi-supervised task needs many modification of our codebases.

That may be true, but will have bigger impact (IMHO) compared to the latest SOTA transformer... no?

**Comment by joihn** [comment]
The new RC of MMdetection does support semi-supervised learning:
https://mmdetection.readthedocs.io/en/v3.0.0rc0/user_guides/semi_det.html

There is also a new RC of mmsegmentation but no semi supervised afaik :/
