### ISSUE TITLE
cannot import name 'get_git_hash' from 'mmcv.utils'

### ISSUE THREAD

**Issue by leizhu1989** [open-mmlab/mmsegmentation#115]
when I run the train.py ,there is a error "cannot import name 'get_git_hash' from 'mmcv.utils'  " ,should I re-installation mmcv? I use the mmdetection environment

**Comment by 22wei22** [comment]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "tools/train.py", line 10, in <module>
    from mmcv.utils import Config, DictAction, get_git_hash
ImportError: cannot import name 'get_git_hash'
请问你解决这个问题了么？我出现了相同的问题。
