### ISSUE TITLE
A suggestion about palette.

### ISSUE THREAD

**Issue by jbwang1997** [open-mmlab/mmsegmentation#1150]
When I read the implementation of the palette function, I find a personal dataset with CLASSES defined but PALETTE being None will skip generating a random palette because the `get_classes_and_palette` returns at
https://github.com/open-mmlab/mmsegmentation/blob/520ec8e12851bcf05e34beeaee7e58bc17346ae2/mmseg/datasets/custom.py#L308-L311

The `get_palette_for_custom_classes` which containing random palette generation will not execute.

As a result, a random palette will be generated in each iteration of testing at 
https://github.com/open-mmlab/mmsegmentation/blob/520ec8e12851bcf05e34beeaee7e58bc17346ae2/mmseg/models/segmentors/base.py#L246-L252

The colors of classes are different in each iteration.

**Comment by Lsz-20** [comment]
maybe the same question~
when I test and visual my dataset,the picture has been paint in random color,and I have checked the categories which load from checkpoints it seems work well

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/pull/1152
