### ISSUE TITLE
Map of scores

### ISSUE THREAD

**Issue by aloreggia** [open-mmlab/mmsegmentation#1157]
Hi,
I have a question about the output of the system. Is it possible to get the map of scores as output?

Thanks in advance,
Andrea

**Comment by MengzhangLI** [comment]
Hi, it is located here:
https://github.com/open-mmlab/mmsegmentation/blob/441be4e435127868a0c72a4e0e6b87662a4c415b/mmseg/models/segmentors/encoder_decoder.py#L242

Right now using this variable is not flexible, but you can change on your own.

Hoping my answer could help you.

Best,

**Comment by aloreggia** [comment]
Thank you for your swift reply, that is really helpful.
What I was looking is a way to output the gray-scale image representing the
mask instead of overlapping the output over the original image.

Thanks again
Andrea

Il giorno mer 22 dic 2021 alle ore 14:32 MengzhangLI <
***@***.***> ha scritto:
