### ISSUE TITLE
how to use/mix torchvision.transforms and mmseg.tranforms in config?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#1159]
Hi, dear authors!
Thank you for your amazing jobs!
Could you tell me how to use/mix torchvision.transforms and mmseg.tranforms in config?
Because I want to use RandAug. I find mmseg doesn't support it but torchvision support it. So I want to use it in mmseg. And some transforms in mmseg are wonderful, so I want mix them in config.py.
Could you tell me how do I do that?
Thank you in advance!

**Comment by zhongqiu1245** [comment]
Any news?

**Comment by RockeyCoss** [comment]
Well, to use torch.vision.transforms, you need to add a new transform class. You can refer to this transform:

https://github.com/open-mmlab/mmsegmentation/blob/fa8c93e78c1679eee558ced5047cc280adfa1c1d/mmseg/datasets/pipelines/transforms.py#L630-L700

Then you need to import this class in `mmseg/datasets/pipelines/__init__.py` and add its name to list __all__.
After doing so, you can use the transform by specifying it in the config.

**Comment by zhongqiu1245** [comment]
thank you!
