### ISSUE TITLE
Multi-category segmentation based on unet

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1165]
It seems that Multi-category segmentation cann't work on unet? when i change the dataset which has  Multi-category, it often show me 'RuntimeError: CUDA error: an illegal memory access was encountered terminate called after throwing an instance of 'c 10::Error'what():  CUDA error: an illegal memory access was encountered'

Thanks

**Comment by MengzhangLI** [comment]
`num_classes` = number of foreground classes + 1 (background)
