### ISSUE TITLE
关于多个数据集的dataset问题

### ISSUE THREAD

**Issue by xiaoachen98** [open-mmlab/mmsegmentation#1167]
您好，我目前正在做多域协作学习语义分割的公开库，遇到了一些问题，当我有三个不同的数据集D1，D2，D3时。
我想控制每次__getitem__根据index索引能够从三个数据集中各自取出一份数据，请问有没有什么比较好的实现方式。
我目前的实现方式如下：
import json
import os.path as osp

import mmcv
import numpy as np
import torch
import copy

from . import CityscapesDataset
from .builder import DATASETS

@DATASETS.register_module()
class MSDADataset(object):
    def __init__(self, sources: list, target, cfg):
        self.num_sources = len(sources)
        assert self.num_sources > 1
        self.datasets = copy.deepcopy(sources)
        self.datasets.append(target)
        self.set_adaptive_source_attr(sources)
        self.target = target
        self.ignore_index = target.ignore_index
        self.CLASSES = target.CLASSES
        self.PALETTE = target.PALETTE
        self.total_length = len(self.target)
        self.sep_sizes = [len(ds) for ds in self.datasets]
        for i in range(1, self.num_sources + 1):
            assert target.ignore_index == self.__getattribute__(f'source{i}').ignore_index
            assert target.CLASSES == self.__getattribute__(f'source{i}').CLASSES
            assert target.PALETTE == self.__getattribute__(f'source{i}').PALETTE
            self.total_length *= len(self.__getattribute__(f'source{i}'))

    def set_adaptive_source_attr(self, source_list):
        for i, v in enumerate(source_list, start=1):
            self.__setattr__(f'source{i}', v)

    @staticmethod
    def cal_rest_mul(sequence, idx):
        rest_mul = 1
        rest_sequence = [s for i, s in enumerate(sequence) if i != idx]
        for s in rest_sequence:
            rest_mul *= s
        return rest_mul

    def __getitem__(self, idx):
        source_stat = []
        out_dic = {}
        for i in range(1, self.num_sources + 1):
            source_stat.append(self.__getattribute__(f'source{i}')[idx // self.cal_rest_mul(self.sep_sizes, i - 1)])
        t = self.target[idx % len(self.target)]
        for i, src in enumerate(source_stat):
            for k, v in src.items():
                out_dic[f'source{i + 1}_' + k] = v
        t.pop('gt_semantic_seg')
        for k, v in t.items():
            out_dic['target_' + k] = v
        return out_dic

    def __len__(self):
        return self.total_length

三个数据集大小分别为25000，20000，2975。我测试了__getitem__(1000000000)是可以正常取出数据的，但是在runner.run中会报出如下错误：

`Traceback (most recent call last):
  File "/home/chenlin/anaconda3/envs/msda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
    index = self._next_index()
  File "/home/chenlin/anaconda3/envs/msda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/chenlin/anaconda3/envs/msda/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/chenlin/anaconda3/envs/msda/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 125, in __iter__
    yield from torch.randperm(n, generator=self.generator).tolist()
RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 14854770000000 bytes. Error code 12 (Cannot allocate memory)`

不知道怎么适配mmseg框架去解决这个问题，是否需要重写一个runner类来重新改变一下获取每批数据的方式，万分感谢！

**Comment by MengzhangLI** [comment]
Hope this link may help you: https://github.com/lhoyer/DAFormer
