### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by dsitnik** [open-mmlab/mmsegmentation#1168]
Hi, 

How do I train a model without loading pretrained weights (i.e. random initialization)? What do I need to change in the config file? 

Thank you in advance!

**Comment by MengzhangLI** [comment]
The point is setting the `pretrained` or `init_cfg` to `None`, for example. 

https://github.com/open-mmlab/mmsegmentation/blob/fa8c93e78c1679eee558ced5047cc280adfa1c1d/configs/_base_/models/bisenetv2.py#L5-L13

So, you just need to set these keys to `None` in your config file.
