### ISSUE TITLE
much lower mIoU using default config

### ISSUE THREAD

**Issue by lidehuihxjz** [open-mmlab/mmsegmentation#1169]
When I use defualt config files to train segmentation models, I got much lower mIoU than pronunced in mmsegmentation. There are compared results and train logs. Is there something wrong with my training?
![image](https://user-images.githubusercontent.com/41275301/147524245-dd21b662-2417-4002-9453-a06d22683036.png)
[pspnet_r101-d8_512x1024_80k_cityscapes.log](https://github.com/open-mmlab/mmsegmentation/files/7782564/pspnet_r101-d8_512x1024_80k_cityscapes.log)
[danet_r101-d8_512x1024_80k_cityscapes.log](https://github.com/open-mmlab/mmsegmentation/files/7782565/danet_r101-d8_512x1024_80k_cityscapes.log)
[deeplabv3plus_r101-d8_512x1024_80k_cityscapes.log](https://github.com/open-mmlab/mmsegmentation/files/7782566/deeplabv3plus_r101-d8_512x1024_80k_cityscapes.log)

**Comment by MengzhangLI** [comment]
How many GPU number did you use?

Default GPU number of those config files are 4, aka the batch size is 4 x 4 = 16.

**Comment by lidehuihxjz** [comment]
> How many GPU number did you use?
> 
> Default GPU number of those config files are 4, aka the batch size is 4 x 4 = 16.

I used the batch size of 4 x 4 = 16 and reproduced the pronounced mIoU. Thanks！

**Comment by MengzhangLI** [comment]
> 

Actually batch size is 4x2 = 8, sorry for my wrong answer yesterday. You could try again, but anyway, I think the lower mIoU is caused by wrong GPU numbers so I close this issue. Feel free to contact us if you meet any problems in the future.
