### ISSUE TITLE
How to change the code to make it support NYUDv2 dataset.

### ISSUE THREAD

**Issue by zzwj66** [open-mmlab/mmsegmentation#1178]
NYUDv2 dataset is a dataset which contains RGB images and depth images. I want use mmseg to deal with multimodal fusion question.

**Comment by MengzhangLI** [comment]
Currently mmseg only supports 1-channel or 3-channel input, thus 4 channel (GRB + depth) input is not supported yet.

But we have noticed this requirements from community, here is related issue: https://github.com/open-mmlab/mmsegmentation/issues/1121

**Comment by zzwj66** [comment]
The common way for multimodal fusion is copy the depth channel into 3-channel, and then do the fusion operation with rgb-channel. So, the final input is  3-channel.
