### ISSUE TITLE
High memory problem.

### ISSUE THREAD

**Issue by PuNeal** [open-mmlab/mmsegmentation#1181]
请问数据加载的流程是怎样的？我在分布式训练模型时，每个进程的内存占用都达到了15%，内存占用很高，训练开始前的很长一段时间都保持这个状态，最后程序报错，信息如下:
```
subprocess.CalledProcessError: Command '['/home/bengui/miniconda3/bin/python', '-u', './tools/train.py', '--local_rank=2', 'configs/unet/fcn_unet_s5-d16_256x256_40k_face_parse.py', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>.
```
我使用的最新版的mmseg和1.4.2版本的mmcv

**Comment by MengzhangLI** [comment]
Hi, please provide detailed config file information.

**Comment by PuNeal** [comment]
> Hi, I think it is caused by your config file.
> 
> If it is modified by unet config file we provided, you would better check paramerters in config files to check whether it is correct.
Yeah, I used RepeatDataset in my dataset config file with 80000 times(as drive.py. And it works after i remove this dataset type.

**Comment by MengzhangLI** [comment]
Good to see you have fixed it!
