### ISSUE TITLE
Inference result is a bit too slow

### ISSUE THREAD

**Issue by calvinnguyenq** [open-mmlab/mmsegmentation#1182]
Hi, I am pretty new to how this all works, so sorry for my lack of knowledge. I am currently trying to use some of the real-time semantic segmentation cityscape models like bisenetv2 and fastscnn with the latter running at 50 images/sec using the benchmark.py. However, running the video demo on a 2048x1024p 30 fps video, I get around 9-10 fps of processing. Is there a way to make it go faster or maybe  have it run asynchronously? I have a RTX 3070 and am running on Ubuntu 20.04

**Comment by MengzhangLI** [comment]
You could try [MMDeploy](https://github.com/open-mmlab/mmdeploy)

**Comment by calvinnguyenq** [comment]
Oh, I was assuming since the benchmark.py ran at 50 images per second, the video_demo.py would also run at 50 frames per second. So this implementation and result is normal?

**Comment by MengzhangLI** [comment]
If the input size is identical, I think it should be the same. Please check our detailed code in benchmark.py and video_demo.py, not too much difference.

**Comment by calvinnguyenq** [comment]
Okay, so I did a little testing. For benchmark.py, for each iteration in the data_loader for loop, it took 0.02 seconds, so the 50 frames per second make sense (1s/0.02s = 50). The benchmark grabs from the cityscape dataset, which contains 2048x1024 images. The file also builds the model with build_segmentor() and MMDataParallel() and seems to inference with "model(return_loss=False, rescale=True, **data)"

For video_demo.py, each iteration of the while loop took 0.2 seconds, so I was getting 5 frames per second. I have a 2048x1024p 30fps video that I am running it with. The file builds the model with init_segmentor() and makes the inference with "result = inference_segmentor(model, frame)" and "frame = model.show_result(frame, result)". 

This seems a bit different to me, it seems video_demo runs a lot slower?

**Comment by MengzhangLI** [comment]
Yes, our fps in README are all made by `benchmakr.py`. We did not make comparison between it with video_demo.py.

**Comment by calvinnguyenq** [comment]
Ah okay, thank you

**Comment by rafaelbou** [comment]
Hi,
@calvinnguyenq do you manage to accelerate the `video_demo.py` performance to be like (or near) to `benchmakr.py`?

**Comment by calvinnguyenq** [comment]
@rafaelbou I couldn't get it near to the benchmark, but I did improve performance by decreasing the image size (ex: 1280x720p). I am converted my model to the TensorRT engine which improved performance significantly when using `deploy_test.py`, and now I am trying to figure out how to edit the `video_demo.py` to work with tensorrt.
