### ISSUE TITLE
Provide mit_bx.pth for Segformer

### ISSUE THREAD

**Issue by fingertap** [open-mmlab/mmsegmentation#1183]
I have trouble downloading the pretrained Segformer backbone from the google disk. Can you provide a converted version of the `mit_bx.pth` file for reproduction? Thanks in advance!

**Comment by fingertap** [comment]
Also, does the `mit_bx.pth` models are pretrained on the two datasets? If so, the comparison is not fair.

**Comment by swjtulinxi** [comment]
复议，迫切需要预训练权重

**Comment by MengzhangLI** [comment]
All pretrained models are the same with all official repos, such as Twins, SETR, Segformer, STDC and so on.

The comparison is fair. You can check its detailed weights in `.pth` model and no longer doubt without reason.

As for providing pretrained model, we would really consider providing a more convenient way to use converted pretrained models.

Best,

**Comment by fingertap** [comment]
I cannot find the `mit_bx.pth` in the official repo. The repo provide a google disk link, where I found the model names contain `cityscapes` or `ade20k`. That is why I ask about the fairness. Thank you for your explanation ;-)

Still, we just want the pretrained backbone file in your config, i.e. `mit_b0.pth` for example, to reproduce the experiments for comparison.

**Comment by swjtulinxi** [comment]
可以去淘宝找人帮下，别人可以翻墙

**Comment by MengzhangLI** [comment]
Can you open this [link](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia)? It is I copied form segformer official repo: 

![image](https://user-images.githubusercontent.com/24582831/148504099-0d77cac0-4f36-411e-84dd-5fd18e34fb55.png)

![image](https://user-images.githubusercontent.com/24582831/148504122-322511b6-b099-4cb8-9135-1f50c940d846.png)

**Comment by fingertap** [comment]
Yes.. I see. Thank you for your explanation!
