### ISSUE TITLE
In your benchmark, 11GB = 11 * 1000 MB or 11 * 1024MB?

### ISSUE THREAD

**Issue by fingertap** [open-mmlab/mmsegmentation#1184]
I cannot run non-local net on my 2080Ti with 11019MB memory. I just want to make sure the memory you report in MB. Also, why the memory you report in the benchmark is different from that in the log, e.g. [10.9GB](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/nonlocal_net#:~:text=40000-,10.9,-1.95) for nonlocal net, while in your log it is [26006](https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_512x1024_40k_cityscapes/nonlocal_r101-d8_512x1024_40k_cityscapes_20200605_210748.log.json#:~:text=1.00887%2C%20%22data_time%22%3A%200.0047%2C-,%22memory%22%3A%2026006,-%2C%20%22loss_seg_decode%22%3A%201.6631%2C%20%22acc_seg_decode)?

**Comment by MengzhangLI** [comment]
11 * 1024MB
