### ISSUE TITLE
The changelog.md link path in the readme.md is wrong.

### ISSUE THREAD

**Issue by Y-M-Y** [open-mmlab/mmsegmentation#1185]
The path now is `https://github.com/open-mmlab/mmsegmentation/blob/master/docs/changelog.md`, which is **404**.

It should be `https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/changelog.md`. It seems like the `changelog.md` has been moved to en-docs.

**Comment by MengzhangLI** [comment]
Hi, thanks for your issue. I will fix it asap.
