### ISSUE TITLE
可以在seg里注册Coco数据集吗？

### ISSUE THREAD

**Issue by WandernForte** [open-mmlab/mmsegmentation#1187]
如果可以，应该要怎么做，我现在只是在datasets的init里import了mmdet的coco数据集，但是这种方法似乎行不通
这里单指coco而不是cocostuff，当然如果被告知这两个是等效的，我也非常感谢

**Comment by MengzhangLI** [comment]
Hi, you coule follow customization dataset tutorial for new dataset.

https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/tutorials/customize_datasets.md
