### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by shengyi4** [open-mmlab/mmsegmentation#1189]
Is mAC the same as mAP in this case? Is there a feature where I can calculate AP50, AP75, and so on? Thanks!

**Comment by MeowZheng** [comment]
mAcc is the mean of accuracy https://github.com/open-mmlab/mmsegmentation/blob/dfcc0b68df67b760e8b1e518ee46bdc8a54f136f/mmseg/core/evaluation/metrics.py#L368

precision is calculated as https://github.com/open-mmlab/mmsegmentation/blob/dfcc0b68df67b760e8b1e518ee46bdc8a54f136f/mmseg/core/evaluation/metrics.py#L378

accuracy is not same as precision and mAcc is not same as AP
