### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by weiqingtangx** [open-mmlab/mmsegmentation#1192]
> ```
>python demo/image_demo.py demo/demo.jpg configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py 
>checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth --device cuda:0 --palette >cityscapes load checkpoint from local path: checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338->2966598c.pth

>Traceback (most recent call last):
>  File "/Users/weiqing.twq/Documents/mmsegmentation/demo/image_demo.py", line 40, in <module>
>    main()
>  File "/Users/weiqing.twq/Documents/mmsegmentation/demo/image_demo.py", line 27, in main
>   model = init_segmentor(args.config, args.checkpoint, device=args.device)
> File "/Users/weiqing.twq/Documents/mmsegmentation/mmseg/apis/inference.py", line 38, in init_segmentor
>    model.to(device)
>  File "/Users/weiqing.twq/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 852, in to
>    return self._apply(convert)
>  File "/Users/weiqing.twq/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 530, in _apply
>    module._apply(fn)
>  File "/Users/weiqing.twq/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 530, in _apply
>    module._apply(fn)
>  File "/Users/weiqing.twq/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 530, in _apply
>    module._apply(fn)
>  File "/Users/weiqing.twq/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 552, in _apply
>    param_applied = fn(param)
>  File "/Users/weiqing.twq/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 850, in convert
>    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
>  File "/Users/weiqing.twq/miniconda3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
>    raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled

Hi, I am new to mmsegmentation, I follow the get_start.md documation to run the demo, I get error info as above. Could you let me how to fix this problem, thank you.

**Comment by MengzhangLI** [comment]
Hi, what is your cuda, pytorch, mmcv version in your envrionment?

**Comment by weiqingtangx** [comment]
> Hi, what is your cuda, pytorch, mmcv version in your envrionment?

Sorry, I forgot tell you the demo run on M1 MacBook. I dont know how to get the version of mmcv.
And I get the info as below:

>>> import torch
>>> print(torch.__version__)
1.9.0
>>> print(torch.cuda.is_available())
False

**Comment by MengzhangLI** [comment]
To be honest, I have not ran on Mac. OpenMMLab is mainly supported Windows and Linux.

PyTorch should not support CUDA on Mac:

https://pytorch.org/get-started/locally/

![image](https://user-images.githubusercontent.com/24582831/148771896-21386d7d-7a58-40f0-accf-4baf7187c3aa.png)

**Comment by weiqingtangx** [comment]
> To be honest, I have not ran on Mac. OpenMMLab is mainly supported Windows and Linux.
> 
> PyTorch should not support CUDA on Mac:
> 
> https://pytorch.org/get-started/locally/
> 
> ![image](https://user-images.githubusercontent.com/24582831/148771896-21386d7d-7a58-40f0-accf-4baf7187c3aa.png)

So How to shut down CUDA config of mmsegmentation?
