### ISSUE TITLE
Difference between setting 'load_from' in default_runtime.py and setting 'model=dict{pretrained=...}' in net's config file.' 

### ISSUE THREAD

**Issue by nonononentity** [open-mmlab/mmsegmentation#1199]
Thank you for your code. 
I get some bugs in setting pretrained model in net's config file(Ok, maybe version problem...). 
But I can set "load_from" in configs/_base_/default_runtime.py.   
Difference between them?

**Comment by MengzhangLI** [comment]
Hi, it is version problem.

You can ignore `load_from` in `default_runtime.py`, just use `pretrained='mmcls://vit_large_p16'` or `init_cfg=dict(type='Pretrained', checkpoint='mmcls://vit_large_p16')` style pretrained keys.

Best,
