### ISSUE TITLE
OSError: checkpoints folder doesn't exsit

### ISSUE THREAD

**Issue by birdflyto** [open-mmlab/mmsegmentation#120]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
OSError: checkpoints/deeplabv3_r50-d8_512x1024_40k_cityscapes_20200605_022449-acadc2f8.pth is not a checkpoint file
**Reproduction**
1. What command or script did you run?
```python tools/test.py configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py     checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth     --show 
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
no modification 
3. What dataset did you use?
cityscapes
**Environment**
torch1.6 centos7.6 CUDA10.1 
1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xvjiarui** [comment]
Hi @birdflyto 
You need to download the checkpoint first. It's in README.md. 
Try `wget https://openmmlab.oss-accelerate.aliyuncs.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes/deeplabv3_r50-d8_512x1024_40k_cityscapes_20200605_022449-acadc2f8.pth`.

**Comment by birdflyto** [comment]
thanks, i find the way to solve the problem in MMSegmentation_Tutorial.ipynb

**Comment by sunny0414** [comment]
@birdflyto Hello ,I meet the seam problem as you ,hou did you solve it？ @birdflyto

**Comment by sylque** [comment]
> You need to download the checkpoint first. It's in README.md.

I don't think there's anything in the Readme.

Here is what seems to work for me, from Colab file [MMSegmentation_Tutorial](https://colab.research.google.com/github/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb):
```
mkdir checkpoints
wget https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth -P checkpoints
```

**Comment by wywlds** [comment]
https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth

The link is currently not usable.

**Comment by MengzhangLI** [comment]
> https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
> 
> The link is currently not usable.



![Uploading WXWorkCapture_16274687087104.png…]()

**Comment by MengzhangLI** [comment]
> https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
> 
> The link is currently not usable.

Hi, do you want to download this one? In my cases it works.

![image](https://user-images.githubusercontent.com/24582831/127309966-b381400d-b429-400e-8eef-6cc66ae28e19.png)

![image](https://user-images.githubusercontent.com/24582831/127310380-dfcc7751-26d5-4e9e-ad27-2477e80b4fc0.png)

**Comment by MengzhangLI** [comment]
> https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
> 
> The link is currently not usable.

Just give a shot:

`https://download.openmmlab.com/mmsegmentation/v0.5/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth`

**Comment by zhanglazhuan** [comment]
> > https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
> > The link is currently not usable.
> 
> Just give a shot:
> 
> `https://download.openmmlab.com/mmsegmentation/v0.5/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth`

it works, I am ok
