### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by yvonneng996** [open-mmlab/mmsegmentation#1200]
Hi,

I have a query regarding the training using the pretrained model on my dataset. Currently, I am using 'upernet_swin_base_patch4_window7_512x512_160k_ade20k.py' as my config file and 'upernet_swin_base_patch4_window7_512x512.pth' and this as the pretrained model. 
1. When I run the config files and the pretrained model right, I am quite curious which swin transformer folders are your using for the backbones. They is one in the Swin-Transformer Semantic Segmentation and the other one is inside this openmmlab: mmsegmentation. For the backbones, which one should I look into?
2. What does the BrokenPipeError means in details? After I run the cell in jupyter notebook, the error become AssertionError. What exactly does this error mean?
Really need help from your. Thank You
![image](https://user-images.githubusercontent.com/68835612/149139723-b50dfa71-8360-4950-b4fd-380c40c057cf.png)
![image](https://user-images.githubusercontent.com/68835612/149139799-9515700c-6ca3-4a8c-a53c-992ed3f6095f.png)
![image](https://user-images.githubusercontent.com/68835612/149139863-a3e925bc-d76a-423c-9cb7-16b74beaefcc.png)

**Comment by MengzhangLI** [comment]
I think it is caused by multithreading problem of Windows or Jupyter Notebook. Could you try to run on terminal.
