### ISSUE TITLE
stdc pretrain weight unable to download

### ISSUE THREAD

**Issue by BeaverCC** [open-mmlab/mmsegmentation#1202]
The download link for "STDC1 (No Pretrain)" pretrain weight in page [README.md](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/stdc/README.md) reports an error.
Could you please fix this.

**Comment by MengzhangLI** [comment]
"STDC1 (No Pretrain)" does not need pretrained weight.

And the link of pretrained model on GoogleDrive is ok:https://drive.google.com/drive/folders/1wROFwRt8qWHD4jSo8Zu1gp1d6oYJ3ns1.

Could you check it out again?

Best,

**Comment by BeaverCC** [comment]
I thought "No Pretrain" means training from scrach with mmlab and random weights, while the other two configs mean training with mmlab and loading the converted pretrain weight from GoogleDrive.
Did I get it wrong?

**Comment by MengzhangLI** [comment]
> I thought "No Pretrain" means training from scrach with mmlab and random weights, while the other two configs mean training with mmlab and loading the converted pretrain weight from GoogleDrive.
> Did I get it wrong?

Yes, you are right. But the other two confirms you need to (1) download pretrained models from GoogleDrive and (2) use our provided script to transfer the original models.

**Comment by BeaverCC** [comment]
> 

Thanks for your quick reply. But maybe I didn't make myself clear.

I trained with config "STDC1 (No Pretrain)" from scatch and get an mIoU of about 70.8. But It should be 71.52 by the [README](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/stdc/README.md#cityscapes). 
And when I click this link [model](https://download.openmmlab.com/mmsegmentation/v0.5/v0.5/stdc/stdc1_512x1024_80k_cityscapes/stdc1_512x1024_80k_cityscapes_20211125_211245-2c8ba4c5.pth), some error occurs, which implies that trained weight is somehow gone.
What I really want is the trained weight, so I won't have to train it myself.

**Comment by MengzhangLI** [comment]
> 

My bad. Let me answer your questions:

(1) The link is wrong because I attach more `v0.5` in the link. Just try to use it: https://download.openmmlab.com/mmsegmentation/v0.5/stdc/stdc1_512x1024_80k_cityscapes/stdc1_512x1024_80k_cityscapes_20211125_211245-2c8ba4c5.pth

(2) Our default setting is 4 GPU x 4 batch size per GPU = 16 batch sizes. Different batch sizes (many users only use one GPU) usually get lower results. What is your settings?

**Comment by BeaverCC** [comment]
(1) I've downloaded the weight and everything works fine. BTW, should I create a pull request for this download link?

(2) The training settings is same as the config file [stdc1_512x1024_80k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/stdc/stdc1_512x1024_80k_cityscapes.py), which says the batch size per GPU is 12, should I change that to 4? And  my GPU is P100 x 4, but I assume that won't affect the training process.

**Comment by MengzhangLI** [comment]
Yes, PR is welcome! Please make it and thank you so much.

I made wrong statement, the batch size of `stdc1_512x1024_80k_cityscapes.py` is 4 GPUs x 2 Batch sizes = 8. I think your setting is the same as mine. The gap I think is OK because it is trained from scratched thus it is not very stable.

**Comment by BeaverCC** [comment]
Sure, I've created a PR #1206 .
