### ISSUE TITLE
Can't reproduce pspnet result on cityscapes even when total batch size is same.

### ISSUE THREAD

**Issue by jiehuang165** [open-mmlab/mmsegmentation#1208]
**Describe the issue**
Can't reproduce the miou of "pspnet_r18-d8_512x1024_80k_cityscapes.py". Model zoo reports miou [74.87](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/pspnet) and is the same result when I test with the official model. 
I notice that the total batch size of official setting is 8. So I'm trying to reproduce the result with two configuration: 1) 2 gpu x 4 sample_per_gpu; 2) 4 gpu x 2 sample_per_gpu. 
The problem is cfg 1) gives miou 73.76, which I think is lower abnormally, and cfg 2) gives miou 75.03, which is quite close to official result and can be accepted. Why cfg 1) and 2)'s result are so different when the total bach size is the same as official setting (btw other model, dataset settings are also same as that of official)? Specifically, is it normal that "2 gpu x 4 sample_per_gpu" is 73.76?

**Reproduction**
1. Reproduction cmd

cfg 1):
```
NUM_GPU=2
CONFIG_FILE=configs/pspnet/pspnet_r18-d8_512x1024_80k_cityscapes.py
CUDA_VISIBLE_DEVICES=0,1 PORT=29500 ./tools/dist_train.sh ${CONFIG_FILE} ${NUM_GPU} --options data.workers_per_gpu=8 data.samples_per_gpu=4
```

cfg 2):
```
NUM_GPU=4
CONFIG_FILE=configs/pspnet/pspnet_r18-d8_512x1024_80k_cityscapes.py
CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=29500 ./tools/dist_train.sh ${CONFIG_FILE} ${NUM_GPU} --options data.workers_per_gpu=8 data.samples_per_gpu=2
```
2. What config dir you run?

```
configs/pspnet/pspnet_r18-d8_512x1024_80k_cityscapes.py
```

3. Did you make any modifications to the code or config? Did you understand what you have modified?
No. What I modify only are the `data.workers_per_gpu` and `data.samples_per_gpu`, but the total batch size is kept to 8.

4. What dataset did you use?
cityscapes

**Environment**

sys.platform: linux
Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.5.3
MMCV: 1.3.16
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.20.0+bdfbaf0

**Results**
configure1's json log (rename file extension from .log.json to .txt just for github upload support)
[20220113_185205_g2xb4.txt](https://github.com/open-mmlab/mmsegmentation/files/7874520/20220113_185205_g2xb4.txt)

configure2's json log
[20220114_094705_g4xb2.txt](https://github.com/open-mmlab/mmsegmentation/files/7874521/20220114_094705_g4xb2.txt)

**Comment by MengzhangLI** [comment]
Can you upload the those two config `.log` files? Thay have detailed config parameters.

**Comment by jiehuang165** [comment]
Sure.
[20220113_185205_g2xb4.log](https://github.com/open-mmlab/mmsegmentation/files/7874655/20220113_185205_g2xb4.log)
[20220114_094705_g4_b2.log](https://github.com/open-mmlab/mmsegmentation/files/7874656/20220114_094705_g4_b2.log)

**Comment by MengzhangLI** [comment]
I have checked two configs. Only difference is one is 4 GPUs x 2 batch sizes and the other is 2 GPUs x 4 batch sizes.

In my previous experiments, only adopt 4 GPUs x 2 batch sizes so results were usually good just as you uploaded.

I have no idea why those two results are very different. Could you repeat 2 GPUs x 4 batch sizes experiments? And I will record this phenomenon and try to figure it our later.

Best,

**Comment by jiehuang165** [comment]
Yeah, the phenomenon is strange. I'm trying to repeat the "2 GPUs x 4 batch sizes" experiment again. I will reply with repeated log asap.

**Comment by jiehuang165** [comment]
I repeat "2 GPUs x 4 batch sizes" two more trying. mIoU are 75.06 and 74.63 respectively. So the lower result 73.76 is in normal drifting range?
[20220117_090906.log](https://github.com/open-mmlab/mmsegmentation/files/7893922/20220117_090906.log)
[20220116_135003.log](https://github.com/open-mmlab/mmsegmentation/files/7893923/20220116_135003.log)

**Comment by MengzhangLI** [comment]
I think 73.76 is outlier result.
