### ISSUE TITLE
Get segmentation map

### ISSUE THREAD

**Issue by sgk-000** [open-mmlab/mmsegmentation#1211]
Thank you for your great work! I want to get segmentation map from pretrained model, it means I want to know the estimated probability for each pixel in each class,  output shape is H x W x NUM_CLASS. 

How do i get it??

Regards.

**Comment by MengzhangLI** [comment]
You can use it here:

https://github.com/open-mmlab/mmsegmentation/blob/63f83258469cbe324143af51da4397aa3223dfd0/mmseg/models/segmentors/encoder_decoder.py#L256

**Comment by sgk-000** [comment]
Thank you for rapid reply.

**Comment by sgk-000** [comment]
Thank you for repid reply. I have one more question.
Can I get img_meta from config file?? I want get that result in video_demo.py, but I don't know how to get img_meta.

Regards,

**Comment by MengzhangLI** [comment]
Sorry to tell you right now it is not supported in MMSegmentation.

MMPose made `data` transferred into `cfg` to acquire img_meta info in customdataset:

https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo.py#L63-L120

This refactor is radical but it can satisfies your needs.

What's more, if you want to support this function in MMSegmentation using a more elegant way, PR is welcome! We would review it ASAP.

Best,

**Comment by sgk-000** [comment]
Sorry to bother you again. Is there any good example of img_meta??
