### ISSUE TITLE
Early termination during training

### ISSUE THREAD

**Issue by BaeSukkyoung** [open-mmlab/mmsegmentation#1212]
I set iteration for 20,000 and training of deeplabv3plus is started, but training ends at 2,000.
What should I check ?

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/63f83258469cbe324143af51da4397aa3223dfd0/configs/_base_/schedules/schedule_20k.py#L7

Also check related number in .log file.
