### ISSUE TITLE
How to understand the relationship between Mem(GB) and memory in log

### ISSUE THREAD

**Issue by jiehuang165** [open-mmlab/mmsegmentation#1215]
What's the relationship between Mem(GB) in model zoo table and memory in log? I guess Mem(GB) and memory are the same things that represent the GPU memory occupied by model training. However, the values are quite different, for example, in model zoo PSPNet. The Mem(GB) is 6.1, while the log shows 18773 (MB).
![image](https://user-images.githubusercontent.com/82852936/149887566-796f13a8-416e-40b6-b77e-0b65f4b8bd74.png)

![image](https://user-images.githubusercontent.com/82852936/149887679-eb448e88-4321-4271-9f0e-859cc932ba50.png)

**Comment by MengzhangLI** [comment]
Mem(GB) = 'memory' / 1024 when `cudnn_benchmark = False`.

https://github.com/open-mmlab/mmsegmentation/blob/b997a13e28da5e5d4eb7639edd749c20b23b3807/configs/_base_/default_runtime.py#L14

**Comment by jiehuang165** [comment]
Thanks for replying. I get the same Mem(GB) after setting `cudnn_benchmark = False `. Btw, do you have any ideas why "memory (torch.cuda.max_memory_allocated)" becomes much larger when `cudnn_benchmark = True `?

**Comment by MengzhangLI** [comment]
cudnn_benchmark = True would make training quicker at the cost of more GPU memory.

[Chinese article](https://zhuanlan.zhihu.com/p/73711222).
