### ISSUE TITLE
errors in SETR pretrain

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1223]
There seems to be some problems with the pretraining section of the latest version of SETR,there is no problem occurring when I use the lower version of the mmseg.
in the new version, it use pretrain from:'mmcls://vit_large_p16',which cannot work well,then i try to load 'jx_vit_large_p16_384-b3be5167' and  the results of the vitmmseg conversion, but it also cann't work
![image](https://user-images.githubusercontent.com/60343452/150463123-79de97b1-8bde-4de7-8a3d-49112c374de6.png)
![image](https://user-images.githubusercontent.com/60343452/150463186-95f8c3a4-d516-4712-8ddb-a9dca0bf6066.png)

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/1049

**Comment by Lsz-20** [comment]
> #1049

Thanks

**Comment by MengzhangLI** [comment]
Maybe it is not problem of transferring keys.

Could you use .pth file here? 

https://github.com/open-mmlab/mmcv/blob/b8d78336a791a2c1dda294890da35c8a5013cc77/mmcv/model_zoo/mmcls.json#L58
