### ISSUE TITLE
The implementation of interpolatation in STDCHead isn't consistent with config setting.

### ISSUE THREAD

**Issue by jiehuang165** [open-mmlab/mmsegmentation#1230]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When calculating losses in Moudle `STDCHead`, `seg_logit` needs to be resized back to the size of `seg_label`. It has a attribute `align_corners` to control whether align_corners=True or False in "configs/_base_/models/stdc.py" line 71:
https://github.com/open-mmlab/mmsegmentation/blob/4b905cbe2fb2a8afbb7e91c5453aa5fd8ac6b060/configs/_base_/models/stdc.py#L61-L72

But in code implementation, the align_corners is forced to True, ignoring the setting in configuration file, in line 87.
https://github.com/open-mmlab/mmsegmentation/blob/4b905cbe2fb2a8afbb7e91c5453aa5fd8ac6b060/mmseg/models/decode_heads/stdc_head.py#L83-L89

**Bug fix**
Actually `STDCHead.losses` calls `BaseDecodeHead.losses`(line 88-89), and `BaseDecodeHead.losses` will resize `seg_logit` to the same size of `seg_label` using configuration's setting `align_corners`(line 239).
https://github.com/open-mmlab/mmsegmentation/blob/4b905cbe2fb2a8afbb7e91c5453aa5fd8ac6b060/mmseg/models/decode_heads/stdc_head.py#L88-L89
https://github.com/open-mmlab/mmsegmentation/blob/4b905cbe2fb2a8afbb7e91c5453aa5fd8ac6b060/mmseg/models/decode_heads/decode_head.py#L232-L239 
Therefore, there is no need to do `interpolate` in `STDCHead.losses` again. Just deleting the code block line 83-87 in "mmseg/models/decode_heads/stdc_head.py" fixes the bug.

**Comment by MengzhangLI** [comment]
Hi, thanks for your warm-hearted reminder. I would fix it asap.
