### ISSUE TITLE
error to convert hrnet model to onnx

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#1232]
**commd line :**
python tools/pytorch2onnx.py configs/hrnet/hrnet.py --checkpoint work_dirs/hrnet/latest.pth --verify --output-file work_dirs/hrnet/latest.onnx --show --shape 1024 1024

**error log:**

Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 396, in <module>
    dynamic_export=args.dynamic_export)
  File "tools/pytorch2onnx.py", line 245, in pytorch2onnx
    sess = rt.InferenceSession(output_file)
  File "/opt/conda/envs/mmsegmentation/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/envs/mmsegmentation/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
RuntimeError: /onnxruntime_src/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 0 error msg:

**Comment by MengzhangLI** [comment]
Hi, @RunningLeon sorry for bothering you!

Could you please check out this issue if your time available? 

Thank you very much!

Best,

**Comment by RunningLeon** [comment]
@jianlong-yuan Hi, please first try with config in the repo such as [configs/hrnet/fcn_hr18s_512x1024_40k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/hrnet/fcn_hr18s_512x1024_40k_cityscapes.py)

**Comment by MeowZheng** [comment]
no response for a long time
