### ISSUE TITLE
undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

### ISSUE THREAD

**Issue by MacavityT** [open-mmlab/mmsegmentation#124]
When I use the operate “python tools/train.py configs/fcn/fcn_r50-d8_512x1024_40k_cityscapes.py” for the test.

I got an error of"ImportError: /home/taiyan/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv
"

Please tell me how to solve it.

**Comment by xvjiarui** [comment]
Hi @MacavityT 
You may try to re-install mmcv-full.

**Comment by hellowangqian** [comment]
Same error and resolved by re-installing mmcv-full with the correct option [here](https://mmcv.readthedocs.io/en/latest/#install-with-pip)

**Comment by chatulBamagafaeim** [comment]
This is the the way of reinstalling: pip install mmcv-full==1.0.4 --no-binary=:all:
