### ISSUE TITLE
Is there a convenient way to create dataset from `.npy` files.

### ISSUE THREAD

**Issue by Marxlp** [open-mmlab/mmsegmentation#1240]
Currently,  `LoadImageFromFile` and `LoadAnnotations` only support file types like *.png*, *.jpeg* etc. which is supported by `cv2` or `Pillow`. Sometimes I want load data from datasets generated by other pipelines, which output *npy* files. The data type and data range many be very various.

I notice that `imdecode_backend` can be set to custom dataloader, but limited in `cv2`, `Pillow`or `turbojpeg`.  And there is a `to_float32` flag to indicates whether converting data type, which may help me convert data type, but still not very general.

I want to know whether there is a convenient way to load data using other dataloader and other data type conversion methods?

**Comment by MengzhangLI** [comment]
Hi, sorry to tell you right now this function is not supported. 

PR is welcome if you want to assist us.

Best,
