### ISSUE TITLE
how to get next data_batch in mmseg.models.segmentors.base.BaseSegmentor.forward_train?

### ISSUE THREAD

**Issue by leo-hao** [open-mmlab/mmsegmentation#1246]
I really like your work and want to make some of my own improvements based on your code, but my foundation is not very good and now I have a difficulty. 
For example, in mmseg.models.segmentors.base.BaseSegmentor.forward_train, I want to get next(data_batch), but I don't know how to get the data_batch, and iterate. At the same time, data_batch is passed in the parameter of forward_step, I don't know  it came . 
Looking forward to your reply!

**Comment by MengzhangLI** [comment]
Hi, try to set num_works=0 in dataloader.

**Comment by leo-hao** [comment]
Thanks for your suggestion,
But I am confused how can I get the data loaders  in forward_train？
I see there is runner.run(data_loaders, cfg.workflow) in mmseg.apis.train.train_segmentor. 
How can I get the data_loaders or obtained from elsewhere, or recreated a dataloader by build_dataloader with cfg.data.workers_per_gpu=0 in forward_train? 
Best wishes.

**Comment by leo-hao** [comment]
I imitated the mmseg.apis.train.train_segmentor and wrote the code in my custom forward_train.
But I don't know How to get data_batch correctly and iterate correctly.
```
dataset = build_dataset(cfg.data.train)
    
    data_loaders = [
        build_dataloader(
            ds,
            cfg.data.samples_per_gpu,
            0,# cfg.data.workers_per_gpu=0
            # cfg.gpus will be ignored if distributed
            #len(cfg.gpu_ids),
            dist=False,
            seed=cfg.seed,
            drop_last=True) for ds in dataset
    ]
```
Looking forward your reply!

**Comment by leo-hao** [comment]
I solve the problem. By set: 
```
    dataset = [build_dataset(cfg.data.train)]
    data_loaders = [
        build_dataloader(
            ds,
            cfg.data.samples_per_gpu,
            0,
            1,
            dist=False,
            seed=cfg.seed,
            drop_last=True) for ds in dataset
    ]
    iter_loaders = [IterLoader(x) for x in data_loaders]
    data_batch = next(iter_loaders)
```
