### ISSUE TITLE
binary segmentation，mcc for category is nan, iou is zero

### ISSUE THREAD

**Issue by zhangyongzhuang** [open-mmlab/mmsegmentation#1248]
![U~D1XBYJ1CQ )~(3(N5M$0W](https://user-images.githubusercontent.com/17512263/151126067-7ae2178d-5ad3-4841-9879-2d03b1d9f567.png)
I want to do edge segmentation of rocks，but got this error.
before this，I did the region segmentation of rocks in the same rock picture. Didn’t get this error.

I used the following method to transform json to label.

# ensure_dir(INPUT_DIR)
    # ensure_dir(OUTPUT_DIR)
    category_types = ["background", "chips"]
    # empty_dir(OUTPUT_DIR)
    # empty_dir(label_DIR)
    # empty_dir(side_DIR)
    """ Browse through all marked json files """
    for file in iglob(INPUT_DIR + '/*.json'):
        with open(file, 'r', encoding='utf-8') as f:

            """ Load json files """
            data = json.load(f)

            """ Save image file """
            j_name = file.split("\\")[-1]
            ts = j_name.split(".")
            title = ts[0]
            file_name = join(img_DIR, "%s.jpg"%title)
            print(file_name, file)
            img_ori = cv2.imread(file_name, cv2.IMREAD_GRAYSCALE)  #3通道变灰度图单通道
            #cv2.imshow('a',img_ori)
            size_ori = img_ori.shape
            #print(size_ori)
            """ Get image width x height """
            mask = np.zeros((size_ori[0], size_ori[1]), dtype="uint8") #全黑图
            sideImg = np.zeros((size_ori[0], size_ori[1]), dtype="uint8")

            """ Process each shape (annotation) """
            for shape in data['shapes']:
                category = shape["label"]
                points = shape["points"]
                # 填充
                points_array = np.array(points, dtype=np.int32)
                mask = cv2.fillPoly(mask, [points_array], (255, 255, 255), category_types.index(category))
                sideImg = cv2.drawContours(sideImg, [points_array], -1, (255, 255, 255), 3, category_types.index(category))

            # cv2.imshow("mak:", mask)
            # cv2.polylines
            save_name = join(label_DIR, title) + ".png"
            cv2.imwrite(save_name, mask)
            save_name = join(side_DIR, title) + ".png"
            cv2.imwrite(save_name, sideImg)

Anyone met the same error?

**Comment by SRN200722** [comment]
Have you solved it?

**Comment by zhangyongzhuang** [comment]
@SRN200722 Chinese?

**Comment by SRN200722** [comment]
> @SRN200722 Chinese?

yes

**Comment by zhangyongzhuang** [comment]
> > @SRN200722 Chinese?
> 
> yes

那行，我英语也不太好，就中文吧。我的是这样的，上述的两张标签图背景是0，前景是255，这样不行，因为就两类，所以在转标签图的时候，前景设置成1就可以了

**Comment by ilpapds** [comment]
Hello. I also experience the same problem. The background class gets 93.82 IoU and the foreground class NaN. I am trying to solve binary segmentation problem where 0 represents background class and 255 the class of foreground (lane label in reality). Could you please help me? How i read the image like grayscale, with 0 representing the background and 1 the foreground? Thank you in advance

**Comment by zhangyongzhuang** [comment]
> 

在标注文件转标签图的时候，将这个前景类的颜色的值设置为1就可以了

**Comment by zhangyongzhuang** [comment]
> Hello. I also experience the same problem. The background class gets 93.82 IoU and the foreground class NaN. I am trying to solve binary segmentation problem where 0 represents background class and 255 the class of foreground (lane label in reality). Could you please help me? How i read the image like grayscale, with 0 representing the background and 1 the foreground? Thank you in advance

把标签文件转换为标签图的时候，将前景类颜色的值设置为1就可以了
