### ISSUE TITLE
Need help regarding combining different backbones and decoders.

### ISSUE THREAD

**Issue by ajinkya-ch** [open-mmlab/mmsegmentation#1250]
How can I combine the U-Net backbone with a Uper-Net decoder? 
- I am trying to alter the config file and model file to combine them, but does not seem to work.

Can anyone guide me though a step-by-step process for building such an architecture? Thanks.

**Comment by MengzhangLI** [comment]
Use this tutorial step-by-step may be helpful for building such an architecture.

https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/config.md
