### ISSUE TITLE
FasterSCNN ONNX export invalid Stride (0)

### ISSUE THREAD

**Issue by r0l1** [open-mmlab/mmsegmentation#1253]
**Describe the bug**
Converting the FasterSCNN model to ONNX leads to an invalid average pool stride (=0). This causes the onnxruntime to segfault. Here is my issue at the onnxruntime engine repo: https://github.com/microsoft/onnxruntime/issues/10402
I updated pytorch and did some tests, however the issue persists. Hope somebody can give a quick hint :)

**Reproduction**

1. What command or script did you run?
```none
python tools/pytorch2onnx.py \
fast_scnn.py \
--checkpoint pretrained-fast-scnn.pth \
--output-file model.onnx \
--input-img test.jpg \
--verify \
--shape 128 256
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? -> Nothing changed. Tested different input sizes.
3. What dataset did you use? -> no dataset needed

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

I am using the Dockerfile of this repo. I tested the export with both PyTorch version 1.6.0 and 1.9.0, 1.10.0. All yielded the same results.

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by skaldesh** [comment]
Any updates on this? I have the same issue as OP

**Comment by RunningLeon** [comment]
@r0l1 @skaldesh  Hi, most likely because there's `AdaptiveAvgPool2d` in [PSPhead](https://github.com/open-mmlab/mmsegmentation/blob/2d8be3712ef61e62e49955ca74cc047b41e0cebe/mmseg/models/decode_heads/psp_head.py#L38) and this op would be replaced to normal avg_pool when exporting to onnx, which means the input should be fixed shape. If you run onnx model with a input shape not as 128 x 256, it may crash. Suggest to use to a fixed input shape.

**Comment by skaldesh** [comment]
Hi, I will test it out when I have time. I think, though, that I always used exactly the same size as during the export (so 128x256). We'll see :)
