### ISSUE TITLE
docker base

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmsegmentation#1256]
# Describe the feature
Do you have the docker that support nvidia-docker?
For example,
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

Because my nvidia driver is new and the docker (https://github.com/open-mmlab/mmsegmentation/blob/02d2790145275477928b97bdcc6e2bc806c095a3/docker/Dockerfile#L2) is not support for cuda 11.4.

**Comment by MeowZheng** [comment]
We have upgraded the cuda version in docker file https://github.com/open-mmlab/mmsegmentation/blob/1924470e0ea5b610bcbb301ee9036678b0ab28fc/docker/Dockerfile#L2
