### ISSUE TITLE
No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by yangdonghan50** [open-mmlab/mmsegmentation#126]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Reproduction**
python tools/train.py ./configs/sem_fpn/fpn_r50_512x512_160k_ade20k.py

**Environment**
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3: TITAN Xp
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.3.0
MMCV: 1.1.2
MMSegmentation: 0.6.0+c3e4dbc
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a

**Error traceback**
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/user/workspace/mmsegmentation/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/user/workspace/mmsegmentation/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/user/workspace/mmsegmentation/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/user/workspace/mmsegmentation/mmseg/models/backbones/__init__.py", line 1, in <module>
    from .fast_scnn import FastSCNN
  File "/home/user/workspace/mmsegmentation/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/user/workspace/mmsegmentation/mmseg/models/decode_heads/__init__.py", line 13, in <module>
    from .point_head import PointHead
  File "/home/user/workspace/mmsegmentation/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/user/workspace/mmcv/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/user/workspace/mmcv/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/user/workspace/mmcv/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/user/workspace/yes/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by xvjiarui** [comment]
Hi @yangdonghan50 
You need to install `mmcv-full` for extension ops.

**Comment by yangdonghan50** [comment]
@xvjiarui 
it works, thanks!

**Comment by Liusandian** [comment]
> @xvjiarui
> it works, thanks!

did you mean use :pip install mmcv-full? or other instructions?

**Comment by yangdonghan50** [comment]
> > @xvjiarui
> > it works, thanks!
> 
> did you mean use :pip install mmcv-full? or other instructions?

pip install mmcv-full

**Comment by yangdonghan50** [comment]
@Liusandian 
pip install mmcv-full

**Comment by neomukul** [comment]
@Liusandian @xvjiarui with mmcv-full it advise to downgrade the mmcv.
any workaround???
