### ISSUE TITLE
Support for pytorch_lightning

### ISSUE THREAD

**Issue by MuhammadIrfanAli** [open-mmlab/mmsegmentation#1260]
Hi,

Recently pytorch lightning has been gaining a lot of attention to avoid boiler plate code for model training with Pytorch. I was wondering if we are thinking to include support for pytorch lightning in the future in mmdetection or any strong reasons as to why it might not be a good idea. Thanks.

For example, I have been eyeing on [Segformer](https://arxiv.org/abs/2105.15203) and would like to simply strip out the model architecture and train with pytorch_lightning. But the model implementation in mmdetection and by NVLabs seems very OOP oriented and it makes it challenging to simply extract the architecture. Ideally something like [this](https://github.com/milesial/Pytorch-UNet/blob/master/unet/unet_model.py) would be great.

**Comment by MengzhangLI** [comment]
Hi, thanks for your advice.

As far as I know, we do not have plan for PyTorch Lightning. But our long-term appeal is making it more convenient to use (although based on framework of OpenMMLab codebases is more appreciated).  

Let me mark this issue. Feel free to contact us anytime.

Best,
