### ISSUE TITLE
Log twice with mmcv==1.4.4

### ISSUE THREAD

**Issue by whu-pzhang** [open-mmlab/mmsegmentation#1261]
The terminal text log print twice like this:

![image](https://user-images.githubusercontent.com/8895344/151665582-6a832653-ac52-4783-9cda-b0445ff3f6e6.png)

**Comment by whu-pzhang** [comment]
env info:

```
sys.platform: linux
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.0
OpenCV: 4.5.5
MMCV: 1.4.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMSegmentation: 0.21.0+29cfcd1
```

**Comment by MengzhangLI** [comment]
Hi, thanks for your feedback.

Here is realted issue on MMCV: https://github.com/open-mmlab/mmcv/issues/1000.

```
I added logger.root.handlers.clear() after calling mmcv.utils.get_logger, and that fixes the duplicate logs problem for me.
```

Could you try to use `logger.root.handlers.clear()` [here](https://github.com/open-mmlab/mmsegmentation/blob/29cfcd145c4878480f83ba89249eaca6f8856d92/mmseg/utils/logger.py#L26)?

If it still not works, could you try to use mmcv==1.3.13 to check out whether it is still logging twice?

Best,

**Comment by MengzhangLI** [comment]
As far as I know, it is more likey caused by MMCV.

Because currently main difference of MMSegmentation v0.21.0 and older versions lie in cpu training/ testing. If you use GPU to train/test, it should have no difference with previous versions of MMSegmentation.

**Comment by whu-pzhang** [comment]
> Hi, thanks for your feedback.
> 
> Here is realted issue on MMCV: [open-mmlab/mmcv#1000](https://github.com/open-mmlab/mmcv/issues/1000).
> 
> ```
> I added logger.root.handlers.clear() after calling mmcv.utils.get_logger, and that fixes the duplicate logs problem for me.
> ```
> 
> Could you try to use `logger.root.handlers.clear()` [here](https://github.com/open-mmlab/mmsegmentation/blob/29cfcd145c4878480f83ba89249eaca6f8856d92/mmseg/utils/logger.py#L26)?
> 
> If it still not works, could you try to use mmcv==1.3.13 to check out whether it is still logging twice?
> 
> Best,

thanks for your reply, I have tried your advices, the problem remains. 
Then i switch to v0.20.2, everything is fine.

**Comment by whu-pzhang** [comment]
> Hi, thanks for your feedback.
> 
> Here is realted issue on MMCV: [open-mmlab/mmcv#1000](https://github.com/open-mmlab/mmcv/issues/1000).
> 
> ```
> I added logger.root.handlers.clear() after calling mmcv.utils.get_logger, and that fixes the duplicate logs problem for me.
> ```
> 
> Could you try to use `logger.root.handlers.clear()` [here](https://github.com/open-mmlab/mmsegmentation/blob/29cfcd145c4878480f83ba89249eaca6f8856d92/mmseg/utils/logger.py#L26)?
> 
> If it still not works, could you try to use mmcv==1.3.13 to check out whether it is still logging twice?
> 
> Best,

thanks for your reply, I have tried your advices, the problem remains. 
Then i switch to v0.20.2, everything is fine.

**Comment by MengzhangLI** [comment]
It is wired, we would fix it as soon as possible.

**Comment by MengzhangLI** [comment]
Do you mean mmsegv0.20.2 + mmcv 1.4.4 works well?

**Comment by MengzhangLI** [comment]
Update: I meet this error too.

![image](https://user-images.githubusercontent.com/24582831/152786714-8f57f589-84a6-4fd2-bebc-7eb4192f4491.png)


mmcv version: 1.4.0
mmseg version: v0.21

**Comment by MengzhangLI** [comment]
Hi @whu-pzhang , thanks again for your nice remainder.

The fixing pr has been created: https://github.com/open-mmlab/mmsegmentation/pull/1267.
