### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by yvonneng996** [open-mmlab/mmsegmentation#1262]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
I have referred to the post regarding broken pipe error in this issue page and I have tried various method suggested by other people but it seems that the error does not go away.
Method 1: Change the 'cudnn_benchmark'= True to False
Method 2: Add a few line of code 
import torch
def run():
    torch.multiprocessing.freeze_support()
    print('loop')
if __name__=='__main__':
    run()

2. The bug has not been fixed in the latest version.

**Describe the bug**
I am not sure like why I always have this error have tried various method suggested by the rest but still can't solve. For them, they are able to it resolved.

**Reproduction**

1. What command or script did you run?
I create another folder in the pycharm inside the Swin-Transformer-Semantic-Segmentation and run the script that I have newly written
![image](https://user-images.githubusercontent.com/68835612/151727659-ced20010-7fa6-499d-a506-a35c84cd00d9.png)
    ```none
    A placeholder for the command.
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I have modified only the filepath and not much into the parameters yet.

3. What dataset did you use?
ADE20K dataset 

**Environment**
1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.

![image](https://user-images.githubusercontent.com/68835612/151727915-c967a3ab-1721-4e21-8197-abd64c7c2e6f.png)

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    I have installed pytorch through anaconda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.
![image](https://user-images.githubusercontent.com/68835612/151728065-ab9ebd14-e009-46a3-ad62-aa92c69ceb35.png)
![image](https://user-images.githubusercontent.com/68835612/151728103-7e56ec94-3c8c-443d-961a-41f3a76ee6e4.png)
![image](https://user-images.githubusercontent.com/68835612/151728154-d6959125-9f58-4200-b551-71963036a0f7.png)
![image](https://user-images.githubusercontent.com/68835612/151728191-308ff1eb-2137-4ecc-8c11-c8f580c165cc.png)

Appreciate if anyone can give any guide on how to solve this problem. Thank You

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by MengzhangLI** [comment]
Could you train other model in MMSegmentation? 

For example, [fcn_unet_s5-d16_64x64_40k_drive](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/unet/fcn_unet_s5-d16_64x64_40k_drive.py).

**Comment by yvonneng996** [comment]
Hi,
I have managed to get rid of this broken pipe error. But there is another error stating 'TypeError: forward_train() missing 1 required positional argument: 'gt_semantic_seg''. The error prompt is because I need validation results which computes the mIOU and mACC. The workflow is being changed from ['train',1] to [('train',1),('val',1)].
![image](https://user-images.githubusercontent.com/68835612/151914919-4ffff230-fab2-4b01-9934-684cf4a9e12c.png)

**Comment by MengzhangLI** [comment]
Seems is related with customized dataset.

**Comment by jirojito** [comment]
> 1. ve searched related issues but cannot get the expected help.
>    I have referred to the post regardin

how solved ? pls teach 💦
