### ISSUE TITLE
Do you know any jupyter notebook or python code example for inference 

### ISSUE THREAD

**Issue by kiashann** [open-mmlab/mmsegmentation#1264]
Hi, I want to use this [notebook ](https://colab.research.google.com/github/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb)but I got different error.
Could you please tell me how I can use this library?
**Do you know any code example?**

**Comment by kiashann** [comment]
@nizhib @grimoire

**Comment by kiashann** [comment]
> https://github.com/JiaYanhao/mmsegmentation/blob/fix-demo/demo/inference_demo.ipynb
> 
> https://github.com/JiaYanhao/mmsegmentation/blob/fix-demo/demo/MMSegmentation_Tutorial.ipynb
> 
> The error is being fixed. Related PR would be merged this month.
I can't run [this code](https://github.com/JiaYanhao/mmsegmentation/blob/fix-demo/demo/inference_demo.ipynb) on google colab.
I want to save segmentation mask, How I can do that?

**Comment by MengzhangLI** [comment]
https://github.com/JiaYanhao/mmsegmentation/blob/fix-demo/demo/MMSegmentation_Tutorial.ipynb is created for colab.

**Comment by kiashann** [comment]
> You can try https://github.com/JiaYanhao/mmsegmentation/blob/fix-demo/demo/MMSegmentation_Tutorial.ipynb, which is created for colab.

I saw this before. It's not work and I get some error

**Comment by MeowZheng** [comment]
we have fix the notebook error, please try the newest notebook demo again
