### ISSUE TITLE
how to use PointRend in Unet

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#1265]
Hi! dear authors!
Thank you for your amazing job!
Could you tell me how to use PointRend in Unet?
In PointRend:
```
    # model training and testing settings
    train_cfg=dict(
        num_points=2048, oversample_ratio=3, importance_sample_ratio=0.75),
    test_cfg=dict(
        mode='whole',
        subdivision_steps=2,
        subdivision_num_points=8196,
        scale_factor=2))
```
but in Unet:
```
    train_cfg=dict(),
    test_cfg=dict(mode='slide', crop_size=256, stride=170))
```
I want to use PointRend in Unet setting (mode='slide'), how do I set the config?
Thank you!

**Comment by MengzhangLI** [comment]
As far as I know:

(1) ensure each feature map from backbone match size of requirements of decoder head.

(2) try to avoid concatenation error of current unet code.
