### ISSUE TITLE
Saving the model and result to a directory

### ISSUE THREAD

**Issue by yvonneng996** [open-mmlab/mmsegmentation#1285]
Hi, 

I have query regarding the saving of checkpoint at each iteration. I have defined a location to save the model after the checkpoint but why it keeps on showing 
"FileNotFoundError: [Errno 2] No such file or directory: 'iter_100.pth'"

I am unsure why there is error prompting out. Do I need to save the checkpoint at a specified location which I am not sure when is the exact location to save the results?

![image](https://user-images.githubusercontent.com/68835612/153841884-77c77080-dd2c-497f-ae1b-b1f0d68baba9.png)

**Comment by MengzhangLI** [comment]
Hi, please checkout your `Script Path` and `Working Directory`.

![image](https://user-images.githubusercontent.com/24582831/153854414-a2625b45-f6d0-4d86-8f73-7f4afd37dc43.png)

**Comment by yvonneng996** [comment]
Hi, the script path and working directory must be similar?

**Comment by MengzhangLI** [comment]
> Hi, the script path and working directory must be similar?

Yes.
