### ISSUE TITLE
CLASSES and PALETTE in CustomDataset

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmsegmentation#129]
According to https://github.com/open-mmlab/mmsegmentation/blob/c3e4dbc2e06de3f47f75098f76772b4ee7e91e35/mmseg/datasets/custom.py#L63, `CLASSES` and `PALETTE` are set to `None`, and according to https://github.com/open-mmlab/mmsegmentation/blob/c3e4dbc2e06de3f47f75098f76772b4ee7e91e35/tools/train.py#L146, they're save to checkpoint, then according to https://github.com/open-mmlab/mmsegmentation/blob/c3e4dbc2e06de3f47f75098f76772b4ee7e91e35/tools/test.py#L115, they're loaded back, finally according to https://github.com/open-mmlab/mmsegmentation/blob/c3e4dbc2e06de3f47f75098f76772b4ee7e91e35/mmseg/models/segmentors/base.py#L239, it create a random palatte when `PALETTE` is `None`, however `CLASSES` is also `None`, which lead to error. Maybe we could set `CLASSES` with a text file, just like `CustomDataset` in [mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py)?

**Comment by xvjiarui** [comment]
Hi @hubutui 
Thanks for the advice! It will be supported in the next release.

**Comment by hubutui** [comment]
a temporary fix, we could add a line after https://github.com/open-mmlab/mmsegmentation/blob/c3e4dbc2e06de3f47f75098f76772b4ee7e91e35/tools/train.py#L135
```
datasets[0].CLASSES = ['class1', 'class2']
```

**Comment by xvjiarui** [comment]
Hi @hubutui 
It is supported by #71. You may have a try.
