### ISSUE TITLE
How to save the best weight file？

### ISSUE THREAD

**Issue by zhangyongzhuang** [open-mmlab/mmsegmentation#1291]
In generally, we save the file every few times. But I want to save the best file, what should I do ?
![微信截图_20220216111656](https://user-images.githubusercontent.com/17512263/154189577-94a8d4b2-19ee-4f60-9752-3915b490b907.png)

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/130
