### ISSUE TITLE
How to save best model during the training?

### ISSUE THREAD

**Issue by huang45** [open-mmlab/mmsegmentation#130]
How to save best model during the training? I  only see the checkpoints was saved by iters, no best model was saved.

**Comment by xvjiarui** [comment]
Hi @huang45 
It is not supported yet. But we plan to implement it soon.

**Comment by hjraad** [comment]
@xvjiarui : what's the status on this one? makes little sense not to save the best one right? Thanks.

**Comment by hannes09** [comment]
is this feature still pending?

**Comment by freepoet** [comment]
> is this feature still pending?
This feature has been added in [here](https://github.com/open-mmlab/mmcv/pull/1068) recently.

**Comment by hannes09** [comment]
The feature only mentions option to save the last several checkpoints, not the best if I understand this correctly. Can you explain how to save the best model?

**Comment by mzr1996** [comment]
> The feature only mentions option to save the last several checkpoints, not the best if I understand this correctly. Can you explain how to save the best model?

Sorry, I don't get the difference. Since the last several checkpoints are saved, just choose the best one, what other function do you need?

**Comment by hannes09** [comment]
The best checkpoint is the checkpoint with the highest mIoU.  At the moment you have to go through all checkpoints manually to find the  best one. If you try new models, datasets or you have an overfittung problem the best checkpoint can be anywherr, not in the last iterations. So saving the best checkpoint means to save only a new checkpoint if mIoU is higher than the mIoU of the last one.

**Comment by maskedmeerkat** [comment]
There already seems to be something implemented in the evaluation function
https://github.com/open-mmlab/mmsegmentation/blob/6eff94165c93705d1ef59f5742e8f4fb906451f7/mmseg/core/evaluation/eval_hooks.py#L41-L42

which is inherited from here
https://github.com/open-mmlab/mmcv/blob/44edcdd91f8940a58c9680c609febc757a50a040/mmcv/runner/hooks/evaluation.py#L282

**Comment by weiaicunzai** [comment]
Hi, I have more than one metric to eval my model during training (e.g.  F1, dice, hausdorff).  
Can I save checkpoints if any of these three metrics achieved a better result? 
Is this feature supported? I have read the source code. It seems that it currently only supports one metric during training?

**Comment by Meoooww** [comment]
> Yeah, so I just double checked. The feature, if I understood it correcly, already exists.
> 
> Just go to your scheduler config and replace the evaluation with the following `evaluation = dict(interval=16000, metric='mIoU', save_best='mIoU')`
> 
> Note: the name of the metric is case sensitive!

I tried the same code, but the model still only outputs latest.pth and did not see any pth containing "best"
