### ISSUE TITLE
HRNet v2 configs

### ISSUE THREAD

**Issue by mtchiu2** [open-mmlab/mmsegmentation#1305]
Hello,

I'm a bit confused about the model naming of HRNetv2. If I understand correctly HRNetv2 is for segmentation while HRNetv2p is for detection, and the difference is that HRNetv2p does multiple steps of average pooling on the output to produce multiple scale features similar to FPN. From mmseg's implementation it seems like it is implementing HRNetv2 instead of HRNetv2p (whereas mmdet implements the pooling step), yet in mmsegmentation/tree/master/configs/hrnet/README.md all tables named the model HRNetv2p.

Am I missing something or is this a typo?

Also I think there is a typo in mmseg/models/backbones/hrnet.py line 634:
"""Convert the model into training mode will keeping the normalization
        layer freezed."""

-->

"""Convert the model into training mode **_while_** keeping the normalization
        layer freezed."""

Thanks.

**Comment by MengzhangLI** [comment]
Hi, thanks for your nice reminder. We would fix this typo and figure it out whether it is correct names as soon as possible!
