### ISSUE TITLE
potential bug in vitjax2mmseg.py

### ISSUE THREAD

**Issue by Tsingularity** [open-mmlab/mmsegmentation#1306]
**Describe the bug**
Currently, the vitjax2mmseg.py relies on jax file name to decide how many layers it have:
```
if 'L_16-i21k' in args.src:
  num_layer = 24
else:
  num_layer = 12
```
and there's no way I can control it via command-line arguments.

However, if I download the vit-large file through the simple wget command in official github [repo](https://github.com/google-research/vision_transformer):
```
wget https://storage.googleapis.com/vit_models/imagenet21k/ViT-L_16.npz
```
it will be viewed as 12-layers by the current converter.

So just wondering, could we have a better way to decide the number of layers in the model?

thanks!

**Comment by Tsingularity** [comment]
plus, seems that the current converter also cannot handle vit-huge cause it has 32 layers.

**Comment by MengzhangLI** [comment]
Current vitjax2mmseg is serving for those 4 segmenter pretrained models.
