### ISSUE TITLE
nan loss

### ISSUE THREAD

**Issue by super233** [open-mmlab/mmsegmentation#1309]
The loss of each batch is not `nan`, however, the `nan` appears in the log automatically reported by mmsegmentation.
Why is this? Is this raised when computing the average loss of multiple batches? Where is the key code?
Is there anyone can help me? /(ㄒoㄒ)/~~

![image](https://user-images.githubusercontent.com/35358984/154973296-99a45b21-df55-429c-8221-05265543ac45.png)

**Comment by MengzhangLI** [comment]
Hi, what `t_seg_loss` is? Is it a brand new loss function you added in MMSegmentation?

**Comment by super233** [comment]
I have fixed it.

The `nan` is generated when computing the average value of loss to log.

The length of `img_metas` is always 0, and the dividing by zero has caused the `nan`.
