### ISSUE TITLE
How to save the inference video by mmcv?

### ISSUE THREAD

**Issue by huang45** [open-mmlab/mmsegmentation#131]
How to save the inference video by mmcv? Only found videoreader api of mmcv. Thanks.

**Comment by xvjiarui** [comment]
Hi @huang45 
Do you imply inference MMSeg on video input and save it? 
Currently, it is not supported yet. You may need to implement it by yourself.

**Comment by huang45** [comment]
ok, got it.

**Comment by wwdok** [comment]
I have the same question now, i was trying to run it in colab, but there is no output :
![image](https://user-images.githubusercontent.com/43233772/103433506-edfd3b00-4c2c-11eb-8a86-cc1f795fc25a.png)

**Comment by abark-electric** [comment]
@huang45 were you able to implement it? I am looking for a similar solition

**Comment by haspberry** [comment]
@abark-electric 

my code...

import argparse

import cv2
import mmcv

from mmseg.apis import inference_segmentor, init_segmentor


def parse_args():
    parser = argparse.ArgumentParser(description='MMDetection video demo')
    parser.add_argument('video', help='Video file')
    parser.add_argument('config', help='Config file')
    parser.add_argument('checkpoint', help='Checkpoint file')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument(
        '--score-thr', type=float, default=0.7, help='Bbox score threshold')
    parser.add_argument('--out', type=str, help='Output video file')
    parser.add_argument('--show', action='store_true', help='Show video')
    parser.add_argument(
        '--wait-time',
        type=float,
        default=1,
        help='The interval of show (s), 0 is block')
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    assert args.out or args.show, \
        ('Please specify at least one operation (save/show the '
         'video) with the argument "--out" or "--show"')

    model = init_segmentor(args.config, args.checkpoint, device=args.device)

    video_reader = mmcv.VideoReader(args.video)
    video_writer = None
    if args.out:
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        video_writer = cv2.VideoWriter(
            args.out, fourcc, video_reader.fps,
            (video_reader.width, video_reader.height))

    for frame in mmcv.track_iter_progress(video_reader):
        result = inference_segmentor(model, frame)
        frame = model.show_result(frame, result)
        #frame = model.show_result(frame, result, score_thr=args.score_thr)
        if args.show:
            cv2.namedWindow('video', 0)
            mmcv.imshow(frame, 'video', args.wait_time)
        if args.out:
            video_writer.write(frame)

    if video_writer:
        video_writer.release()
    cv2.destroyAllWindows()


if __name__ == '__main__':
    main()
