### ISSUE TITLE
errors happened when test segformer by using ADE20K datasets

### ISSUE THREAD

**Issue by FreedoomG** [open-mmlab/mmsegmentation#1312]
**Describe the bug**
Hi there, I want to test the Segformer and other algorithms with ADE20K datasets and find there are some errors in the code.
after I modified some codes, the last problem was COOM.

**Reproduction**

1. What command or script did you run?

python tools/test.py --config configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py --checkpoint checkpoints/segformer_mit-b0_512x512_160k_ade20k_20210726_101530-8ffa8fda.pth --eval mIoU

2. Did you make any modifications to the code or config? Did you understand what you have modified?
YES! 
The first error I met is wrong with the gt mask filename.
I modify the ade20k.py in configs/_base/datasets, replace the ann_dir from annotations/validation to images/validation, cuz I only have the images folder but not the annotation folder.

The second thing is the custom.py in mmseg/datasets, in line 154, the seg.png name was wrong so I add the _seg in the str,
"seg_map = img_name + '_seg' + seg_map_suffix"
"seg_map = img.replace(img_suffix, '_seg' + seg_map_suffix)" line 161 the same and the program use it cuz the mmcv can be used.

The third thing I changed was the the loading.py in mmseg/datasets/pipelines, cuz the png I read has the shape [w,h,c] but it need just [w,h], so I slice the tensor by "backend=self.imdecode_backend).squeeze().astype(np.uint8)[:,:,0]" in line 135.

3. What dataset did you use?
ADE20k with the categories :
for example, data/ade/ADEChallengeData2016/images/validation/a/abbey/ADE_val_00000001.jpg

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.

sys.platform: win32
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3080
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\nvcc.exe
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
GCC: n/a
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.10.0
OpenCV: 4.5.5
MMCV: 1.4.3
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.21.1+71c201b

**Error traceback**

I don't want to destroy the original file so I used test2.py instead.
cuda out of memory happened and I don't know why.

2022-02-23 09:22:25,690 - mmseg - INFO - OpenCV num_threads is `<built-in function getNumThreads>
2022-02-23 09:22:25,890 - mmseg - INFO - Loaded 2000 images
load checkpoint from local path: ../checkpoints/segformer_mit-b0_512x512_160k_ade20k_20210726_101530-8ffa8fda.pth
D:/mmsegmentation/tools/test2.py:251: UserWarning: SyncBN is only supported with DDP. To be compatible with DP, we convert SyncBN to BN. Please use dist_train.sh which can avoid this error.
  'SyncBN is only supported with DDP. To be compatible with DP, '
[                                ] 2/2000, 0.4 task/s, elapsed: 6s, ETA:  5531sTraceback (most recent call last):
  File "D:/mmsegmentation/tools/test2.py", line 305, in <module>
    main()
  File "D:/mmsegmentation/tools/test2.py", line 268, in main
    format_args=eval_kwargs)
  File "D:\mmsegmentation\mmseg\apis\test.py", line 91, in single_gpu_test
    result = model(return_loss=False, **data)
  File "C:\Users\COLORFUL\.conda\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\COLORFUL\.conda\envs\open-mmlab\lib\site-packages\mmcv\parallel\data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "C:\Users\COLORFUL\.conda\envs\open-mmlab\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\COLORFUL\.conda\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\COLORFUL\.conda\envs\open-mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "D:\mmsegmentation\mmseg\models\segmentors\base.py", line 110, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "D:\mmsegmentation\mmseg\models\segmentors\base.py", line 92, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "D:\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 256, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "D:\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 241, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "D:\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 215, in whole_inference
    warning=False)
  File "D:\mmsegmentation\mmseg\ops\wrappers.py", line 27, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "C:\Users\COLORFUL\.conda\envs\open-mmlab\lib\site-packages\torch\nn\functional.py", line 3709, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 5.01 GiB (GPU 0; 10.00 GiB total capacity; 218.46 MiB already allocated; 4.33 GiB free; 3.30 GiB reserved in total by PyTorch)

**Bug fix**

the same in modifications but I'm not sure what I have done is right.

**Comment by sainivedh19pt** [comment]
My guess would be to try reducing samples_per_gpu/batch_size

**Comment by FreedoomG** [comment]
> My guess would be to try reducing samples_per_gpu/batch_size

oh I forgot to write about it and I have modified these to 1.
