### ISSUE TITLE
关于训练结果中一个为1，另一个为nan

### ISSUE THREAD

**Issue by yanni1995** [open-mmlab/mmsegmentation#1313]
2022-02-23 10:41:11,741 - mmseg - INFO - 
+--------+-------+-------+
| Class  |  IoU  |  Acc  |
+--------+-------+-------+
| others | 100.0 | 100.0 |
|  lane  |  nan  |  nan  |

我这是两类的，其中训练结果里面一类是100，另外一类是nan，请问如何解决

**Comment by shuaikangma** [comment]
看一下你的mask图片，把0和255改成0和1试一下，或者在数据集加载的时候做一下映射应该就可以了

**Comment by yanni1995** [comment]
> 看一下你的mask图片，把0和255改成0和1试一下，或者在数据集加载的时候做一下映射应该就可以了

意思是我在数据加载的时候把0和255变成0和1是吗

**Comment by shuaikangma** [comment]
对的，训练读入的标签只能是0和1，但二分类的mask一般都是0和255，所以要在数据加载的时候改一下

---原始邮件-


  
看一下你的mask图片，把0和255改成0和1试一下，或者在数据集加载的时候做一下映射应该就可以了
  
意思是我在数据加载的时候把0和255变成0和1是吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanni1995** [comment]
> 对的，训练读入的标签只能是0和1，但二分类的mask一般都是0和255，所以要在数据加载的时候改一下
> […](#)
> ---原始邮件- 看一下你的mask图片，把0和255改成0和1试一下，或者在数据集加载的时候做一下映射应该就可以了 意思是我在数据加载的时候把0和255变成0和1是吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，能提供一个链接吗，我不太清楚mmseg框架中在哪修改关于标签转换，谢谢

**Comment by shuaikangma** [comment]
最好是直接写个脚本重新生成一份标签数据吧，在./mseg/datasets/custom.py中应该可以改，但是这封装改起来不太容易，我就是直接改数据了

**Comment by yanni1995** [comment]
> 最好是直接写个脚本重新生成一份标签数据吧，在./mseg/datasets/custom.py中应该可以改，但是这封装改起来不太容易，我就是直接改数据了

哦哦，您的意思是把标签图片的像素值在没放入框架训练之前先改为0和1对吧

**Comment by shuaikangma** [comment]
✔

**Comment by LansonChen** [comment]
@shuaikangma @yanni1995 你好，我转换成0和1的mask，现在还遇到这个问题，要怎么解决呢？

**Comment by yanni1995** [comment]
> @shuaikangma @yanni1995 你好，我转换成0和1的mask，现在还遇到这个问题，要怎么解决呢？

你的标签应该没处理好，你可以debug进去看看

**Comment by zp19990818** [comment]
> > @shuaikangma @yanni1995 你好，我转换成0和1的mask，现在还遇到这个问题，要怎么解决呢？
> 
> 你的标签应该没处理好，你可以debug进去看看

请问是直接将原本的二值mask中[255,255,255]的目标改成[1,1,1]吗？还是说修改其他的地方

**Comment by ZzzTD** [comment]
@LansonChen 您好，请问ade数据集发生这个问题的原因是什么呢
