### ISSUE TITLE
I want fixed RGB value

### ISSUE THREAD

**Issue by ikjoooon** [open-mmlab/mmsegmentation#1316]
I tried to infer with an opacity of 1.0 with a model that I trained myself.
And I got an image file.

And the object RGB value of the image should be [128,0,0].
However, RGB value are not constant.

{Example:

The trained object and RGB.
object1 [128, 0, 0] , object2[0, 0, 0]

After inference, RGB value in the image file =
[127, 0, 0], [128, 0, 0] , [129, 0, 0], [130, 0, 1] ...

}

When inferring, it seems that they try to move on smoothly from an object to another object.

I want RGB values to be constant when obtaining image files after inference.
I wish only the RGB value I set would come out.
Can I know the code or file that needs to be modified?

**Comment by MengzhangLI** [comment]
Hi, sorry for my bad comprehensive ability, I can not understand what you mean.

I suggest you follow our doc for customization dataset: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_datasets.md.
