### ISSUE TITLE
Will mmsegmentation add efficientnet as the backbone network? 

### ISSUE THREAD

**Issue by daigang896** [open-mmlab/mmsegmentation#1319]
Hello. Will mmsegmentation add efficientnet as the backbone network? I've been looking forward to it.

**Comment by MengzhangLI** [comment]
It has been supported in MMClassification: https://github.com/open-mmlab/mmclassification.

You can follow this Chinese article step to load efficientnet backbone from mmcls: https://zhuanlan.zhihu.com/p/436865195.

**Comment by daigang896** [comment]
OK, thanks. I'll try it.
