### ISSUE TITLE
Where is the path to the downloaded pretrain models?

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmsegmentation#1325]
Like the question, I cannot find the pretrain models, or if there are any infos about the pretrain models? e.g., training epochs, etc.

**Comment by mitming** [comment]
> Follow the notification in README.md of each algorithms, and some classical model like ResNet or HRNet could be found here:https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json.

@MengzhangLI,

Thanks for your reply. Indeed, where can I find these pretrain models in my computer? Besides, could you please tell me more details about the pretrain models? like the training epochs, etc

**Comment by MengzhangLI** [comment]
I dont have more information about these pretrained models.
