### ISSUE TITLE
Questions about dice Metrics in PointRend

### ISSUE THREAD

**Issue by Dominix-411** [open-mmlab/mmsegmentation#1326]
Does PointRend support dice Metric? Or somewhere I don't know. Can you please point it out. If it is not supported, please tell me where the parameters required by dice Metric are. The package of this toolbox is so good that I can't find it. thanks

**Comment by MengzhangLI** [comment]
python ./tools/test.py ${CONFIG} ${CHECKPOINT} [--eval ](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L43) mDice
