### ISSUE TITLE
question about binary segmentation

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmsegmentation#1335]
Hi,
I fail to use mmseg to binary segmentation task.
1. I create one dataset in `mmseg/datasets` like this:
```
# Copyright (c) OpenMMLab. All rights reserved.
import os.path as osp
from .builder import DATASETS
from .custom import CustomDataset

@DATASETS.register_module()
class TianchiDataset(CustomDataset):
    CLASSES = ('background', 'object')

    PALETTE = [[0, 0, 0], [255, 255, 255]]

    def __init__(self, **kwargs):
        super(TianchiDataset, self).__init__(
            img_suffix='.jpg',
            seg_map_suffix='.png',
            reduce_zero_label=False,
            **kwargs)
        assert osp.exists(self.img_dir)

```
2. How I handle my dataset？
```
.
├── annotations
│   ├── training
│   └── validation
└── images
    ├── training
    └── validation
```
To make sure you can understand what I mean, I will give all codes.
I use the following code to handle my dataset. **My dataset is gray image which pixel is between [0, 255](it is not a binary mask, it may contain piexl value=127 eg.), so I use ` // 128` to create [0,1].**
```
ann_dir = '/opt/tiger/ws/mmsegmentation/data/tianchi/ann_store/training'
img_dir = '/opt/tiger/ws/mmsegmentation/data/tianchi/images/training'
out_dir = "/opt/tiger/ws/mmsegmentation/data/tianchi"

for img_name in tqdm(os.listdir(img_dir)):
    img = mmcv.imread(osp.join(img_dir, img_name))
    mmcv.imwrite(
        img,
        osp.join(
            out_dir, 'images', 'training',
            osp.splitext(img_name)[0].replace('_training', '') +
            '.png'))

for img_name in tqdm(os.listdir(ann_dir)):
    cap = cv2.VideoCapture(osp.join(ann_dir, img_name))
    ret, img = cap.read()
    mmcv.imwrite(
        img[:, :, 0] // 128,
        osp.join(out_dir, 'annotations', 'validation',
                    osp.splitext(img_name)[0] + '.png'))
```
3. How I train and then meet problem?
I use DANet to train my dataset.
```
_base_ = [
    '../_base_/models/danet_r50-d8.py',
    '../_base_/datasets/tianchi_dataset.py', '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_20k.py'
]
model = dict(
    decode_head=dict(num_classes=2), auxiliary_head=dict(num_classes=2))
# runner = dict(type='IterBasedRunner', max_iters=20000)

```
4. Training result?
I think I have done all things I know to use mmseg.
But the validation result is strange.
**I know that I need to handle my mask to [0, n_class - 1], but it is still fails.**
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/23122139/156098661-ebee8d80-04f8-4d65-849d-0e47ae5b3689.png">
Can you give me some suggestions about this problem, I have no idea about mmseg now.

---------------------------------------------------------------------------------
By the way, mmseg works well when using DRIVE dataset, so I guess the mask handle processing maybe wrong.

**Comment by MengzhangLI** [comment]
Hi, your error report is very detailed.

So what is the value of label? I mean if your task is only binary segmentation, the annotations should only have `int` value `0` and `1`. `PALETTE` and `CLASSES` are only used for post processing such as visualization, which has nothing to do with training.

As you said, DRIVE works well, so you could also make a comparison between DRIVE and your Tianchi dataset.

Looking forward to your reply.

**Comment by Senwang98** [comment]
@MengzhangLI 
Thanks for your quick reply.
I give one mask image for better understanding.
![7](https://user-images.githubusercontent.com/23122139/156100062-ffc61a14-9425-4711-9c04-d3467920d6f5.png)

-------
This mask image is `png`, I use opencv to read it:
```
import cv2
from pprint import pprint
img = cv2.imread('train/mask/7.png', 0)

h, w = img.shape[:2]
res = {}
for i in range(h):
    for j in range(w):
        v = img[i][j]
        if v in res.keys():
            res[v] += 1
        else:
            res[v] = 1
pprint(res)
cv2.imwrite('mask_7.png', img)
```
I count all pixel value in above mask image and result:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/23122139/156100620-2d6f305b-8e73-42b1-9a26-e1d70a39ed13.png">
As you can see, this mask image is not a binary image. Namely, this mask is not a standard 0/1 mask image for my task.
I am not sure I use ` // 128` to make all pixel value into 0/1 is ok or not.

**Comment by MengzhangLI** [comment]
So I think you should clip your label value to 0 and 1 with suitable value.

In this case, I think number of `value 0` is already enough, you could just use `!=0` rather than `// 128`.

**Comment by Senwang98** [comment]
@MengzhangLI 
I do this clip operation as you say, but the validation result is still `0`.
I feel confused.
Does mmseg have some script to help developer training their own dataset?

**Comment by MengzhangLI** [comment]
Right now only has one document: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_datasets.md.

We would make docs have more contents in the future.

**Comment by ilpapds** [comment]
Hello. I also experience a similar problem. The background class gets 93.82 IoU and the foreground class NaN. I am trying to solve binary segmentation problem where 0 represents background class and 255 the class of foreground (lane label in reality). Could you please help me? How i read the image like grayscale, with 0 representing the background and 1 the foreground? Thank you in advance

**Comment by Senwang98** [comment]
Hi, @ilpapds 
I have already successfully train mmseg, but utill now I have not figure out why my current code is ok. 
I am still debuging...

**Comment by wptoux** [comment]
I have met the similar problem, maybe you could set reduce_zero_label to False in LoadAnnotations and try again.

```
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
```

**Comment by ke-dev** [comment]
@Hi, I have the same problem, has your problem been solved?
