### ISSUE TITLE
How to get the layer before final layer of a decoder head (to use as embeddings) 

### ISSUE THREAD

**Issue by Ngheissari** [open-mmlab/mmsegmentation#1339]

**Comment by MengzhangLI** [comment]
Well, you don't say.

That's what we have done last week, check out this PR:https://github.com/open-mmlab/mmsegmentation/pull/1299.

You could made similar modification on your wanted decoder head, like what we use `forward_feature()` in K-Net:https://github.com/open-mmlab/mmsegmentation/pull/1289/files.

**Comment by Ngheissari** [comment]
This is perfect :)

**Comment by MengzhangLI** [comment]
> This is perfect :)

MMSegmentation deserves your star and fork lol.
