### ISSUE TITLE
support user-defined extension without modifying the installed environment

### ISSUE THREAD

**Issue by Beanocean** [open-mmlab/mmsegmentation#134]
**Describe the feature**
First, Thanks a lot for sharing the fantastic project.

In the [fariseq-pytorch](https://github.com/pytorch) project, there is a nice feature ([--user-dir](https://github.com/pytorch/fairseq/pull/440)) to support implementing custom extensions in a user-defined directory, rather than the original environment. 

**Motivation**
Ex1. It is inconvenient when implementing a custom feature without modifying the installed environment.

**Additional context**
I noticed there is a `Registry` class in the `mmcv` project, while the extension still needs to be imported by the `__init__.py` file. As shown in the [tutorial example](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/new_modules.md#add-new-backbones)(step 2).
Notice: there is an error in step 1. of the example. The code `from ..registry import BACKBONES` should be changed as `from ..builder import BACKBONES` in current version (commit: b8c2f913e41147fdee4d695efe175d10baf7570).

The [import_user_modules()](https://github.com/pytorch/fairseq/blob/23d8502bdde88a3e58e0910e2ee49834f8478b39/fairseq/utils.py#L394) may be a good way to implement this feature. It seems that we should update the Registry instance (eg. `Registry('backbone')`) with the user-defined modules (`MobileNet`) before calling the `build_from_cfg()` function.

**Comment by xvjiarui** [comment]
Hi @Beanocean 
Thanks for your suggestion. We already have a plan on it. We may work on it next month.
