### ISSUE TITLE
Will mmsegmentation support the training of MapillaryVistas dataset?

### ISSUE THREAD

**Issue by daigang896** [open-mmlab/mmsegmentation#1340]
Hello, Will mmsegmentation support the training of MapillaryVistas dataset?

**Comment by MengzhangLI** [comment]
I really want to support CamVid but we lack enough resources. 

Would you like to make a pr about it? It seems like you use mmseg for a long time and make a lot of issues. So I guess it would not be hard for you.

Best,

**Comment by daigang896** [comment]
All right.
