### ISSUE TITLE
Wrong keynames/state dict in mit_b backbone

### ISSUE THREAD

**Issue by A-guridi** [open-mmlab/mmsegmentation#1343]
**Describe the bug**
When converting the weights from the mit_b0 backbone downloaded from the [official repo](https://github.com/NVlabs/SegFormer), the matching keys and the expected keys from the backbone do not match. The problem lies on the `mit2mmseg.py` file.

**Reproduction**

1. What command or script did you run?
Downloaded weights from official repo.
Converted them with `mit2mmseg.py`
Loaded them with `load_checkpoint(model, mit_b0.pth)` function. As soon as I loaded them, the output said that there was an error in the matching keys of the state dict. 

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, I am using the standard config from the segformer_mit_b0.py
3. What dataset did you use?
I am trying to train segformer for the potsdam dataset, but this is not relevant I think. 

**Bug fix**
After changing the `replace` functions in the `mit2mmseg.py` file and adding the string "backbone" in front of layers the output didnt complain again regarding the miss-matching state dict. 
I.e.
`new_k = k.replace(f'patch_embed{stage_i}', f'backbone.layers.{stage_i-1}.0')`
`new_k = k.replace(f'block{stage_i}', f'backbone.layers.{stage_i-1}.1')`
`new_k = k.replace(f'norm{stage_i}', f'backbone.layers.{stage_i-1}.2')`

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply. We would add transferred keys pretrained models of SegFormer as soon as possible, just lie Swin Transformer:https://github.com/open-mmlab/mmsegmentation/pull/1389.

Did you download models here: https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia ?

**Comment by A-guridi** [comment]
Yes, the weights were downloaded from that  URL.

Thanks for your help !!
