### ISSUE TITLE
demo: syntax error near unexpected

### ISSUE THREAD

**Issue by sihuo521** [open-mmlab/mmsegmentation#1345]
**1.shell**
python demo/image_demo.py demo/demo.jpg configs/deeplabv3plus/deeplabv3plus_r50-d8_512x1024_40k_cityscapes.py \
    checkpoints/deeplabv3plus_r50-d8_512x1024_40k_cityscapes_20200605_094610-d222ffcd.pth --device cuda:0 --palette cityscapes

**2. bug**
checkpoints/deeplabv3plus_r50-d8_512x1024_40k_cityscapes_20200605_094610-d222ffcd.pth: line 1: ▒▒: command not found
checkpoints/deeplabv3plus_r50-d8_512x1024_40k_cityscapes_20200605_094610-d222ffcd.pth: line 2: syntax error near unexpected token `('
little_endianq▒X'abv3plus_r50-d8_512x1024_40k_cityscapes_20200605_094610-d222ffcd.pth: line 2: `l▒F▒ j▒P.▒M▒.▒}q(Xprotocol_versionqM▒X
 

![1646365111(1)](https://user-images.githubusercontent.com/36940636/156694886-b68ac8e3-b841-4fe6-aa6d-c2cebc241753.png)

**Comment by sihuo521** [comment]
**3. env**
mmcv               1.4.6
mmcv-full          1.4.6
mmdet              2.22.0
mmsegmentation     0.21.1

**Comment by MengzhangLI** [comment]
Sorry for late reply. Seems like it is path error or syntax error in your terminal line.
