### ISSUE TITLE
Stuck in the process of data loading, waiting for a long time but not starting training

### ISSUE THREAD

**Issue by shuaikangma** [open-mmlab/mmsegmentation#1346]
Hello，in the newest version of mmegmentation(2022.3.4), I was stuck in the process of data loading, shows in the picture:
![image](https://user-images.githubusercontent.com/54463853/156747991-93499ce5-91b3-4b5b-b593-4386a5f96211.png)

I guss it maybe the mutil-gpu problem, I change the SyncBN to BN, but it still dosen't work.
If I use ctrl+c to kill it ,I will get this information:
![image](https://user-images.githubusercontent.com/54463853/156748615-3f9ce01b-ba85-4d75-8b81-3dc82d4fc6f3.png)

I used mmegmentation(a early version) to train SegFormer, it worked(use single-gpu), this time I want to try some new network, I config it in the same way, but it failed.
How can I fix this problem?
Thanks!

**Comment by MengzhangLI** [comment]
Try to use small dataset to testify whether mmseg could run normally.

Whats more, you could set below in your `tools/train.py`:

```python
# MP start method
import multiprocessing as mp
mp.set_start_method('fork')
```

Above modification could boost pre-training procedure (but I am not sure it could work in your situation).

**Comment by wptoux** [comment]
I met the same situation. It seems that turning off cudnn benchmark would solve the problem.

**Comment by shuaikangma** [comment]
Thanks for your reply.
But neither boosting pre-training procedure nor turning off all cudnn benchmark work in my situation, I run the same code on another gup server which has cuda10.2 with a bigger dataset, the problem goes away. I guess it may caused by the env or the dataset.
