### ISSUE TITLE
Stacking CascadeDecodeHeads

### ISSUE THREAD

**Issue by mtchiu2** [open-mmlab/mmsegmentation#1353]
The forward_test() function of BaseCascadeDecodeHead takes in `x` (feature map) and `prev_output` from the previous decoder head as arguments, but in `CascadeEncoderDecoder._decode_head_forward_train(...)`, line 78-79, `self.decode_head[i-1]` do not take in prev_outputs. This implies that the function assumes all decode heads except the last are BaseDecodeHead rather than BaseCascadeDecodeHead, which means we cannot stack CascadeDecodeHeads, e.g. OCRHead and PointHead.

Is this intended? Shouldn't it first distinguish which head is stacked, then decide whether to feed prev_output or not to the next head?

Thanks

**Comment by MeowZheng** [comment]
Thanks for your report, we are fixing the problems. Please review this pr https://github.com/open-mmlab/mmsegmentation/pull/1450.

**Comment by mtchiu2** [comment]
Thanks for solving the issue. The pr should fix the issue.
