### ISSUE TITLE
Difference between `fcn_unet` and `unet`, what does `s5-d16` mean?

### ISSUE THREAD

**Issue by ChenJiangxi** [open-mmlab/mmsegmentation#1355]
~~新手问题归纳：~~

~~- fcn_unet与unet有什么区别吗？~~
~~- s5-d16中的d16是什么意思呢？包括resnet50-d8中的d8是什么意思？~~
~~- 如果想构建resUnet的网络结构，只需要在cofigs里改就行吗？~~

~~先感谢大家的不吝赐教~~

Questions from beginner:

- What is difference between fcn_unet and unet?
- What does `d16` in `s5-d16` mean? Moreover, what does `d8` in `resnet50-d8` mean?
- If I want to build resUNet network, could I only modify config files?

Thanks in advance for your help~

**Comment by MengzhangLI** [comment]
Next time please use English for global discussion then I will answer your question.

(1) If use FCN to handle last feature map of UNet, it is fcn_unet. Thus, fcn_unet is vanilla unet.

(2) `d` is `strides` in backbone, if it is `d16`, it means width and height of deepest feature map is 1/16  of input shape. `d8` means 1/8.

(3) I am afraid no, you should modify `UpConvBlock` https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py#L372 and `BasicConvBlock` https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py#L389 in the code.

**Comment by scm-later** [comment]
what does s5 mean

**Comment by scm-later** [comment]
> Hi, next time please use English for global discussion then I will answer your question.
> 
> (1) If use FCN to handle last feature map of UNet, it is fcn_unet. Thus, fcn_unet is vanilla unet.
> 
> (2) `d` is `strides` in backbone, if it is `d16`, it means width and height of deepest feature map is 1/16 of input shape. `d8` means 1/8.
> 
> (3) I am afraid no, you should modify `UpConvBlock` https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py#L372 and `BasicConvBlock` https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py#L389 in the code.
> 
> Best,

what does s5 mean? thank you

**Comment by forestemperor** [comment]
> > Hi, next time please use English for global discussion then I will answer your question.
> > (1) If use FCN to handle last feature map of UNet, it is fcn_unet. Thus, fcn_unet is vanilla unet.
> > (2) `d` is `strides` in backbone, if it is `d16`, it means width and height of deepest feature map is 1/16 of input shape. `d8` means 1/8.
> > (3) I am afraid no, you should modify `UpConvBlock` https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py#L372 and `BasicConvBlock` https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py#L389 in the code.
> > Best,
> 
> what does s5 mean? thank you

i suppose s should be stride which means how many strides the backbone take to achive d16.
