### ISSUE TITLE
The outputs are different between Pytorch and ONNX

### ISSUE THREAD

**Issue by John-Yao** [open-mmlab/mmsegmentation#136]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Hi, I am trying to export onnx model by tools/pytorch2onnx.py with verify opt and met below error:

ValueError: The outputs are different between Pytorch and ONNX

And I print the difference between pytorch and onnx. The output is 0.00028228759765625

**Reproduction**
1. What command or script did you run?
```
CONFIG_FILE=pspnet_r50.py
python tools/pytorch2onnx.py ${CONFIG_FILE} --checkpoint ${CHECKPOINT} --output-file demo.onnx --shape 512 1024 --verify

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

1. environment infomation:
fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3,4,5,6,7: Tesla V100-PCIE-32GB
GCC: gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3
PyTorch: 1.5.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.1+cu101
OpenCV: 4.2.0
MMCV: 1.1.2
MMSegmentation: 0.5.1+
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1

**Error traceback**
If applicable, paste the error trackback here.
```
0.00028228759765625
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 205, in <module>
    verify=args.verify)
  File "tools/pytorch2onnx.py", line 145, in pytorch2onnx
    'The outputs are different between Pytorch and ONNX')
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xvjiarui** [comment]
Hi @John-Yao 
There may be a small inconsistency between PyTorch and ONNX, but it should be fine.

**Comment by John-Yao** [comment]
Thanks for you reply!
 
The error is got by below code:
print(np.mean(np.abs(pytorch_result-onnx_result)))

I also convert my custom model to onnx in my repo. The mean error is about 1e-4. But my colleague  got mean error of 1e-12 in his custom repo. 

I am very interested how to achieve such low error!
