### ISSUE TITLE
Does mmseg support data aug method like adding noise and blur to images?

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmsegmentation#1364]
Hello,
I want to use data aug methods like adding noise to images or blur images.
Does mmseg support these method? 
Or, I should add these methods in tranform.py?

**Comment by MengzhangLI** [comment]
These methods are not supported yet. PR is welcome.

**Comment by Senwang98** [comment]
@MengzhangLI 
mmdet support Albumentation now, mmseg maybe should support then I think.
