### ISSUE TITLE
I have searched related issues but cannot get the expected help.

### ISSUE THREAD

**Issue by victory3398** [open-mmlab/mmsegmentation#1369]
['MMCV_MAX',
 'MMCV_MIN',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'digit_version',
 'mmcv',
 'mmcv_max_version',
 'mmcv_min_version',
 'mmcv_version',
 'parse',
 'version',
 'version_info',
 'warnings']

The mmseg don't have apis package

**Comment by MengzhangLI** [comment]
Hi, could you list your detailed error report? So maybe we could help you locate your problems.

Best,

**Comment by victory3398** [comment]
> 
I install mmseg on kaggle,and to do the next : "from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot"
but can't find the apis package

the detailed error at below:

ImportError                               Traceback (most recent call last)
/tmp/ipykernel_34/1126321740.py in <module>
----> 1 from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
      2 from mmseg.core.evaluation import get_palette

/kaggle/working/mmsegmentation/mmseg/apis/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .inference import inference_segmentor, init_segmentor, show_result_pyplot
      3 from .test import multi_gpu_test, single_gpu_test
      4 from .train import (get_root_logger, init_random_seed, set_random_seed,
      5                     train_segmentor)

/kaggle/working/mmsegmentation/mmseg/apis/inference.py in <module>
      7 
      8 from mmseg.datasets.pipelines import Compose
----> 9 from mmseg.models import build_segmentor
     10 
     11 

/kaggle/working/mmsegmentation/mmseg/models/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .backbones import *  # noqa: F401,F403
      3 from .builder import (BACKBONES, HEADS, LOSSES, SEGMENTORS, build_backbone,
      4                       build_head, build_loss, build_segmentor)
      5 from .decode_heads import *  # noqa: F401,F403

/kaggle/working/mmsegmentation/mmseg/models/backbones/__init__.py in <module>
      4 from .cgnet import CGNet
      5 from .erfnet import ERFNet
----> 6 from .fast_scnn import FastSCNN
      7 from .hrnet import HRNet
      8 from .icnet import ICNet

/kaggle/working/mmsegmentation/mmseg/models/backbones/fast_scnn.py in <module>
      5 from mmcv.runner import BaseModule
      6 
----> 7 from mmseg.models.decode_heads.psp_head import PPM
      8 from mmseg.ops import resize
      9 from ..builder import BACKBONES

/kaggle/working/mmsegmentation/mmseg/models/decode_heads/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .ann_head import ANNHead
      3 from .apc_head import APCHead
      4 from .aspp_head import ASPPHead
      5 from .cc_head import CCHead

/kaggle/working/mmsegmentation/mmseg/models/decode_heads/ann_head.py in <module>
      6 from ..builder import HEADS
      7 from ..utils import SelfAttentionBlock as _SelfAttentionBlock
----> 8 from .decode_head import BaseDecodeHead
      9 
     10 

/kaggle/working/mmsegmentation/mmseg/models/decode_heads/decode_head.py in <module>
      9 from mmseg.ops import resize
     10 from ..builder import build_loss
---> 11 from ..losses import accuracy
     12 
     13 

/kaggle/working/mmsegmentation/mmseg/models/losses/__init__.py in <module>
      4                                  cross_entropy, mask_cross_entropy)
      5 from .dice_loss import DiceLoss
----> 6 from .focal_loss import FocalLoss
      7 from .lovasz_loss import LovaszLoss
      8 from .utils import reduce_loss, weight_reduce_loss, weighted_loss

/kaggle/working/mmsegmentation/mmseg/models/losses/focal_loss.py in <module>
      4 import torch.nn as nn
      5 import torch.nn.functional as F
----> 6 from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
      7 
      8 from ..builder import LOSSES

/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .bbox import bbox_overlaps
      3 from .border_align import BorderAlign, border_align
      4 from .box_iou_rotated import box_iou_rotated
      5 from .carafe import CARAFE, CARAFENaive, CARAFEPack, carafe, carafe_naive

/opt/conda/lib/python3.7/site-packages/mmcv/ops/bbox.py in <module>
      2 from ..utils import ext_loader
      3 
----> 4 ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
      5 
      6 

/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py in load_ext(name, funcs)
     11 
     12     def load_ext(name, funcs):
---> 13         ext = importlib.import_module('mmcv.' + name)
     14         for fun in funcs:
     15             assert hasattr(ext, fun), f'{fun} miss in module {name}'

/opt/conda/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ImportError: /opt/conda/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

**Comment by victory3398** [comment]
> Hi, could you list your detailed error report? So maybe we could help you locate your problems.
> 
> Best,
