### ISSUE TITLE
demo/image_demo.py didn't support STARE dataset

### ISSUE THREAD

**Issue by CCODING04** [open-mmlab/mmsegmentation#1375]
**Motivation**
`demo/image_demo.py` didn't support STARE dataset

**Comment by MengzhangLI** [comment]
Hi, thanks for your issue. Could you make a pr about it? Thanks in advance.

**Comment by CCODING04** [comment]
@MengzhangLI Already made a pr. Plz check it, thanks. 😸

**Comment by MengzhangLI** [comment]
Wow, it's so quick. Thank you so much. ;)
