### ISSUE TITLE
ConvNext inference is too slow

### ISSUE THREAD

**Issue by Siannodel** [open-mmlab/mmsegmentation#1377]
我测试了下ConcNext-tiny推理512x512图像上的耗时 需要120ms左右。
相同的机器，Swin-transformer-tiny 推理512x512图像耗时50ms左右，这个应该是比较符合文档中的测试结果的。
想知道是哪里的问题？

I tested the ConvNeXt-tiny inference time. The time-consuming on the 512x512 image takes about 120ms.

For the same machine, the swin transformer tiny inference on 512x512 image takes about 50ms, which should be in line with the test results in the document.

Want to know what the problem is?

**Comment by MengzhangLI** [comment]
Hi, first of all, could you please translate this issue into English for wider discussion in community? Thanks in advance.

To this issue, do you use FP16 in ConvNeXt config? 

I just checked the [swin](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/swin) and [convnext](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/convnext), their tiny model FPS are close, both of them are tested in V100 32G. Plus, ConvNext FP32 is very slow.

**Comment by Siannodel** [comment]
Thank you for your reply! 
I will translate the question into English later.
I didn't use fp16 in inference.  How should I use fp16?

**Comment by MengzhangLI** [comment]
> 

Just follow our default config. https://github.com/open-mmlab/mmsegmentation/blob/master/configs/convnext/upernet_convnext_tiny_fp16_512x512_160k_ade20k.py

The key operation lies in here:
https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L206

**Comment by slchenchn** [comment]
Hi, I just found that the LayerNorm is not fully compatible with Pytorch's fp16 autocast, see [this](https://discuss.pytorch.org/t/autocast-with-normalization-layers/94125/4).
So how did you solve this problem?

**Comment by MengzhangLI** [comment]
> 
Well, it works well in my situation and I did not meet problems. Do you encounter similar problems using ConvNeXt + PyTorch FP16 with our provided config?

**Comment by MengzhangLI** [comment]
> Hi, I just found that the LayerNorm is not fully compatible with Pytorch's fp16 autocast, see [this](https://discuss.pytorch.org/t/autocast-with-normalization-layers/94125/4). So how did you solve this problem?

Well, it works well in my situation and I did not meet problems. Do you encounter similar problems using ConvNeXt + PyTorch FP16 with our provided config?

**Comment by Siannodel** [comment]
I tested fp16 on TitanV, and the time consumption has not changed compared to fp32 .
But it seems that TitanV does not support fp16.
So I tested it again on the T4 machine, and there is still no speed improvement between fp16 and fp32.
At the same time, I tested swin-transformer and convnext on T4, which are twice as slow as TitanV.
