### ISSUE TITLE
Training speed gap between windows and linux

### ISSUE THREAD

**Issue by back2yes** [open-mmlab/mmsegmentation#138]
Thank you for put this awesome toolbox open-source~

I used the toolbox in both windows and ubuntu environment, but I noticed that the training speed in ubuntu is about 2x as in windows, with similar hardwares. For my task, ubuntu mmseg takes ~0.52 for a batch, while windows takes ~1.08s. At first I doubt the reason may be the data parallel part, as a N-worker dataloader is usually slower than linux. But when I disable the data parallel setting in the data loaders, the training speed was not affected much (the data loading time is very short, about ~0.006s). So I guess the reason lies somewhere else.

Can you give me some hint for boosting the windows training procedure?

**Comment by xvjiarui** [comment]
Hi @back2yes 
We haven't benchmarked on Windows machines. 
You may try `tools/benchmark.py` to see the pure inference speed different between ubuntu and windows.
