### ISSUE TITLE
How to save the whole model and load it

### ISSUE THREAD

**Issue by JaviMota** [open-mmlab/mmsegmentation#1384]
Hi

I have trained a model following your Colab and using a custom dataset. I would like to know how can I save the whole model instead of the weights and how can I load it, after modifying the config as shown in the Colab. 
Also I would like to know where I need to specify to save only the best model during the training.

Thanks in advance

Regards,
Javi

**Comment by MengzhangLI** [comment]
Hi, colab is an easy tutorials which do not have total content of framework.

If you can use command line or IDE, you could run `./tools/train.py`, for example: `python ./tools/train.py ./configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py --work-dir ./work_dirs/pspnet_r50-d8_512x1024_40k_cityscapes/`, thus the whole model would be saved in folder `./work_dirs/pspnet_r50-d8_512x1024_40k_cityscapes/`.

We may add content of saving and loading model in colab in the future.

Best,

**Comment by JaviMota** [comment]
Hi, thanks for the answer

I have tried to save the model with torch.save after training it but when I load it with torch.load, it complains about img_metas. How can I generate this img_metas file? I need to covert it to onnx and it seems I also need this img_metas file.

Thank you.

**Comment by MengzhangLI** [comment]
`img_metas` would be saved using our `--work-dir` command, so just `torch.save` would lose it.
