### ISSUE TITLE
How to use point head with other backbone models like CGNet 

### ISSUE THREAD

**Issue by tanveer6715** [open-mmlab/mmsegmentation#1386]
I want to use point head with other backbone models like CGNet. I have replace the 'FCNHead" with pointhead in the config base file but it still show an error when training is started. Kindly help to to solve this issue. I have paste the new config script  as well as the error shown when training get started.

'''
# model settings
norm_cfg = dict(type='SyncBN', eps=1e-03, requires_grad=True)
model = dict(
    type='EncoderDecoder',
    backbone=dict(
        type='CGNet',
        norm_cfg=norm_cfg,
        in_channels=3,
        num_channels=(32, 64, 128),
        num_blocks=(3, 21),
        dilations=(2, 4),
        reductions=(8, 16)),
    decode_head=
        dict(
            type='PointHead',
            in_channels=[256],
            in_index=[0],
            channels=256,
            num_fcs=3,
            norm_cfg=norm_cfg,
            coarse_pred_each_layer=True,
            dropout_ratio=-1,
            num_classes=19,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
     # model training and testing settings
    train_cfg=dict(
        num_points=2048, oversample_ratio=3, importance_sample_ratio=0.75),
    test_cfg=dict(
        mode='whole',
        subdivision_steps=2,
        subdivision_num_points=8196,
        scale_factor=2))
'''
TypeError: forward_train() missing 1 required positional argument: 'train_cfg'
    result = self.forward(*input, **kwargs)

**Comment by MeowZheng** [comment]
Just add `train_cfg=dict()` ref https://github.com/open-mmlab/mmsegmentation/blob/d6a6c39a70b4d08069712ae475ec10005716847c/configs/_base_/models/ccnet_r50-d8.py#L43

**Comment by tanveer6715** [comment]
> Just add `train_cfg=dict()` ref
> 
> https://github.com/open-mmlab/mmsegmentation/blob/d6a6c39a70b4d08069712ae475ec10005716847c/configs/_base_/models/ccnet_r50-d8.py#L43

Hi thanks for your response but I am talking about CGNet with poind head not CCNet. BTW I add "train_cfg=dict()," but it still give an error.

**Comment by MeowZheng** [comment]
I have called `build_segmentor` with input cfg you provided, but I didn't meet the problem you meet.
Below is the scrip I tested:
```python
norm_cfg = dict(type='SyncBN', eps=1e-03, requires_grad=True)
model = dict(
    type='EncoderDecoder',
    backbone=dict(
        type='CGNet',
        norm_cfg=norm_cfg,
        in_channels=3,
        num_channels=(32, 64, 128),
        num_blocks=(3, 21),
        dilations=(2, 4),
        reductions=(8, 16)),
    decode_head=dict(
        type='PointHead',
        in_channels=[256],
        in_index=[0],
        channels=256,
        num_fcs=3,
        norm_cfg=norm_cfg,
        coarse_pred_each_layer=True,
        dropout_ratio=-1,
        num_classes=19,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    # model training and testing settings
    train_cfg=dict(
        num_points=2048, oversample_ratio=3, importance_sample_ratio=0.75),
    test_cfg=dict(
        mode='whole',
        subdivision_steps=2,
        subdivision_num_points=8196,
        scale_factor=2))

from mmseg.models import build_segmentor
build_segmentor(model)
```

**Comment by MeowZheng** [comment]
long time no reply
