### ISSUE TITLE
No module named 'mmcv'

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1387]
Perhaps the code requires the number of parallel programs?
I am successfully running two models but when I try to run the third there is a reported error:
`
Traceback (most recent call last):
  File "tools/train.py", line 9, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
`
Of course my installation is correct
Looking forward to your reply

**Comment by MengzhangLI** [comment]
I think it may caused by your local environment. Please check it out on your own.

**Comment by Lsz-20** [comment]
> 
I have checked the packages i installed.
And
