### ISSUE TITLE
Calculating mIOU

### ISSUE THREAD

**Issue by JPABotermans** [open-mmlab/mmsegmentation#1391]
When calculating the mIOU should you not compute the individual IOU for different classes and then take the mean (1)? Instead of dividing the total intersection by the total union (2)? Used in 
mmsegmentation. 

Using these different methods can results in quite different values. 
For example, consider the following case;

|                     | Class A | Class B | Total |
|---------------------|---------|---------|-------|
| Intersection Pixels | 1       | 10      | 11    |
| Union Pixels        | 2       | 10      | 12    |
| IOU                 | 0.5     | 1.0     | ????  |

Using method (1) the mIOU becomes (0.5+1.0)/2 = 0.75
While using method (2) the mIOU becomes 11/12 = 0.91

I know that the cityscapes eval script uses the first method, while mmsegmentation uses the second, and I was wondering why. 

I believe in this function the intersections are added;
https://github.com/open-mmlab/mmsegmentation/blob/3d0c2eb385031680cc3891cc0ecd437aa738ab9d/mmseg/core/evaluation/metrics.py#L296

**Comment by MengzhangLI** [comment]
Hi, thanks for your reminder.

I try to answer your problem:

In https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/metrics.py#L366-L367, 
`total_area_intersect`  and `total_area_union` are both vector whose length is class numbers. If dataset is Cityscapes, it should be 19:

![image](https://user-images.githubusercontent.com/24582831/158953516-c9b45e94-936e-46ac-a80f-ce86de544905.png)

So the calculation is the same as (1) in your issue.

Best,

**Comment by JPABotermans** [comment]
Hi, Thank you for your response and your explanation! 

It definitely answers my problem. I think I was looking at the wrong function (pre_eval_to_metrics instead of total_area_to_metrics).
