### ISSUE TITLE
How to test the "mIoU" and "mIoU(ms+flip)" respectively in mmsegmentation ?

### ISSUE THREAD

**Issue by Magic-Ha** [open-mmlab/mmsegmentation#140]
I notice that in this repo, all trained models  tested with the metric "mIoU(ms+flip)". But I just cant find how to use this metric in the tutorial. Could you please give me an instruction about how to use mIoU and mIoU(ms+flip) respectively to test and evaluate my models?

**Comment by xvjiarui** [comment]
Hi @Magic-Ha 
You may pass `--aug-test` with `tools/test.py` for ms+flip test.
