### ISSUE TITLE
how to train my own data set

### ISSUE THREAD

**Issue by ywj509** [open-mmlab/mmsegmentation#1400]
I annotated json files with labelme and generated corresponding PNG images ([0,0,0] represents the background [128,0,0] represents the target), which were stored in accordance with ade20k data set format.  Run fCN_R50-D8_512X512_80k_ADE20k. py, but the training results are 100%, is there something wrong with my data set?

**Comment by MengzhangLI** [comment]
You may follow: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_datasets.md

**Comment by ywj509** [comment]
i don't understand----":::{note} The annotations are images of shape (H, W), the value pixel should fall in range [0, num_classes - 1]. You may use 'P' mode of [pillow](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#palette) to create your annotation image with color. :::''

For my single-class target segmentation, should the annotation information in the PNG image be pixel value 1

**Comment by MengzhangLI** [comment]
`For my single-class target segmentation, should the annotation information in the PNG image be pixel value 1`. Please refer to DRIVE dataset which is also single-class target on your own: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/unet/deeplabv3_unet_s5-d16_256x256_40k_hrf.py.

**Comment by payal211** [comment]
Hi @ywj509 ,

Can you please describe how you have annotate your custom dataset?
How the annotation file looks like?

Thanks in advance.
