### ISSUE TITLE
Question about auxiliary_head

### ISSUE THREAD

**Issue by ChenJiangxi** [open-mmlab/mmsegmentation#1410]
Thank you for your wonderful framework!
I have a question about the auxiliary decoder. For a auxiliary FCNdecoder to HRNet-w48, if I set `in_index = [0,1,2]`, and` in_channels=[48,96,192]`, does that mean the FCNdecoder get the output from stage3 of HRNet-w48?

Thanks in advance!

**Comment by MengzhangLI** [comment]
What is current config file, could you give me a link?

**Comment by ChenJiangxi** [comment]
There is my config file. Thanks for your reply.
https://github.com/ChenJiangxi/segmentation-on-singlegreen/blob/main/fcn_hr48_512x1024_80k_singlegreen_aux.py

**Comment by ChenJiangxi** [comment]
And I have some problems on other issue #1040 
I'm confused about this answer. The config file for FCN decoder and HRNet is:
`in_channels = [48, 96, 192, 384]` 
so I think the decode_head could only support four feature maps as input. Am I right?

**Comment by MengzhangLI** [comment]
No, you can set 

```python
in_channels=[18, 36, 72],
in_index=(0, 1, 2),
channels=sum([18, 36, 72]),
```

And theorically it could work (but it means you need to train new model on your own and I think it is necessary).


the function of it is concating all feature maps (after resizing to similar height and width) from backbone (HRNet-w48 in this case) in here: 

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/decode_heads/decode_head.py#L173
 
whose channels = #Chennel_featuremap1 + #Chennel_featuremap2 + #Chennel_featuremap3 + #Chennel_featuremap4.

See [here](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_hr18.py#L39) `channels=sum([18, 36, 72, 144]),`.

**Comment by ChenJiangxi** [comment]
I think my set is correct accordingly, which is suitable for HRNet-w48. And yours is suitable for HRNet-w18
`
in_channels=[48,96,192],
in_index=(0, 1, 2),
channels=sum([48,96,192]),
`
And  do you mean that the feature map obtained by this way is from hrnet stage 4 and not stage 3?
Thank you for your late night reply!

**Comment by ChenJiangxi** [comment]
I have this question because the config file of deeplabv3_r50-d8 can realize the auxiliary head get the feature map from layer3 of resnet, while ASPPHead get the feature map from layer4.  So I think that is  what  `in_index` works for.
[https://github.com/open-mmlab/mmsegmentation/blob/0d51115d85834e7855716986a53820a31bb168f7/configs/_base_/models/deeplabv3_r50-d8.py#L29](url)
I'm cofused about the mechanism of auxiliary head and `in_index`.

**Comment by MengzhangLI** [comment]
I totally do not suggest you modify the number of feature maps for input of decoder/auxiliary heads. 

its [decoder in_index=3 ](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/deeplabv3plus_r50-d8.py#L20) and [auxiliary in_index=2](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/deeplabv3plus_r50-d8.py#L34), which is index of feature maps of backbone (i.e., its backbone has output [OUTPUT0, OUTPUT1, OUTPUT2, OUTPUT3], OUTPUT2 is input of auxiliary head and OUTPUT3 is input of decoder head).

I strongly suggest you debug and these probelms would be solved easily.
