### ISSUE TITLE
Error occurs for training with custom dataset

### ISSUE THREAD

**Issue by erenuzyildirim** [open-mmlab/mmsegmentation#1412]
Hi,
Although I followed all rules(dataset directory, annotation files, etc. ) and important issues that you emphasize about training with a custom dataset, an error occurs when I have trained with a custom dataset. You can find terminal output:

![Screenshot from 2022-03-23 23-14-03](https://user-images.githubusercontent.com/72136203/159787720-aa1cd1c2-95f2-4bfd-a931-cf8bce035859.png)

**Comment by MengzhangLI** [comment]
The location is in MMCV, in [get_started.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/get_started.md#prerequisites). Do you match version of mmcv and mmseg?

`The compatible MMSegmentation and MMCV versions are as below. Please install the correct version of MMCV to avoid installation issues.`

| MMSegmentation version |        MMCV version        | MMClassification version |
|:----------------------:|:--------------------------:|:------------------------:|
|         master         |  mmcv-full>=1.4.4, <=1.5.0  | mmcls>=0.20.1, <=1.0.0   |
|         0.22.0         |  mmcv-full>=1.4.4, <=1.5.0  | mmcls>=0.20.1, <=1.0.0   |
|         0.21.1         |  mmcv-full>=1.4.4, <=1.5.0  | Not required             |
|         0.20.2         | mmcv-full>=1.3.13, <=1.5.0  | Not required             |
|         0.19.0         | mmcv-full>=1.3.13, <1.3.17 | Not required             |
|         0.18.0         | mmcv-full>=1.3.13, <1.3.17 | Not required             |
|         0.17.0         | mmcv-full>=1.3.7, <1.3.17  | Not required             |
|         0.16.0         | mmcv-full>=1.3.7, <1.3.17  | Not required             |
|         0.15.0         | mmcv-full>=1.3.7, <1.3.17  | Not required             |
|         0.14.1         | mmcv-full>=1.3.7, <1.3.17  | Not required             |
|         0.14.0         |  mmcv-full>=1.3.1, <1.3.2  | Not required             |
|         0.13.0         |  mmcv-full>=1.3.1, <1.3.2  | Not required             |
|         0.12.0         |  mmcv-full>=1.1.4, <1.3.2  | Not required             |
|         0.11.0         |  mmcv-full>=1.1.4, <1.3.0  | Not required             |
|         0.10.0         |  mmcv-full>=1.1.4, <1.3.0  | Not required             |
|         0.9.0          |  mmcv-full>=1.1.4, <1.3.0  | Not required             |
|         0.8.0          |  mmcv-full>=1.1.4, <1.2.0  | Not required             |
|         0.7.0          |  mmcv-full>=1.1.2, <1.2.0  | Not required             |
|         0.6.0          |  mmcv-full>=1.1.2, <1.2.0  | Not required             |

**Comment by erenuzyildirim** [comment]
Thanks for the quick reply. I matched the versions of mmseg and MMCV. Now, the versions are:
mmseg: 0.22.1(master)
MMCV: 1.4.5
mmcls: 0.21.0

But the error still occurs.

**Comment by MengzhangLI** [comment]
OK, could you train or test mmseg in your current environment?

**Comment by erenuzyildirim** [comment]
I can use inference for it but training gives error.

**Comment by MengzhangLI** [comment]
OK, it seems it is related with MMCV. Could you please attach detailed error report? Thanks in advance.

Here is an example issue: https://github.com/open-mmlab/mmsegmentation/issues/1351#issue-1160515544

**Comment by erenuzyildirim** [comment]
OK, I have already created a repo and sent an invitation to you for sharing it. You can find my setup(runner commands or scripts, modified files, dataset, etc. ) for the experiments there.

**Comment by MengzhangLI** [comment]
OK, I would check it as soon as possible.

**Comment by erenuzyildirim** [comment]
Thanks so much, I would really appreciate it.

**Comment by MengzhangLI** [comment]
Its ok. I have checked your repo. And I think perhaps it has something to do with https://github.com/open-mmlab/mmsegmentation/issues/799. Hope it could help you.

Best,

**Comment by erenuzyildirim** [comment]
Thanks, I checked in detail the issue that you linked. I applied the proposed solutions but it does not work. Actually, I think the problem that  I encountered is different than the one in the issue. They do not mention any "recursion error" that I get:

![Screenshot from 2022-03-24 15-30-15](https://user-images.githubusercontent.com/72136203/159916708-1dc47606-af68-45a5-9d98-72f89ddde262.png)

**Comment by MengzhangLI** [comment]
Sorry, I never met this error before ;(.

You did not list whole error report and based on your snapshot above, I think it is related with local environment, but I can not figure out whether it is located in openmmlab or other things.

(1) if train/inferece works well in our provided config file, it may locate in possibility of customization dataset.

(2) if train not works well in our provided config file, it may rule out possibility of customization dataset.

Could you train/test normally with our original codebase and provided config in your current conda environment? 

Let us keep in touch if meet new errors. 

Best,
