### ISSUE TITLE
Label visualization

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1413]
Perhaps allow for multi-color visualization of dataset mask in dataset related files?
For example, try to convert a black mask picture ([1,1,1], [2,2,2].......) into a mask with different colors
If not, can you provide an implementation idea?
Thanks

**Comment by MengzhangLI** [comment]
For certain dataset, give its palette and name of each label class: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/class_names.py#L268-L316

In custome dataset class, give its palette and name of each label class: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/chase_db1.py#L18-L20

**Comment by Lsz-20** [comment]
> For certain dataset, give its palette and name of each label class: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/class_names.py#L268-L316
> 
> In custome dataset class, give its palette and name of each label class: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/chase_db1.py#L18-L20

Thanks for your reply, but it seems that the answer is different.I want to know if the data set provided is a mask to render all black which py file can run to convert it to a color image

**Comment by MengzhangLI** [comment]
It is not supported yet. PR is welcome!

**Comment by Lsz-20** [comment]
> It is not supported yet. PR is welcome!

Ok,thanks.
