### ISSUE TITLE
Input Dimensions need 4D but got 3D SegFormer

### ISSUE THREAD

**Issue by dhruvmetha** [open-mmlab/mmsegmentation#1416]
Hey, I'm trying to use a custom dataset to train the segformer, I get this error when trying to call the `train_segmentor`. I'm using a single GPU, so I changed the config to 'BN' for both the head and the decoder. Would appreciate any pointers to solve this problem, thanks in advance.

Error:

`ValueError: expected 4D input (got 3D input)`

This orignates from the `self.backbone`  and further down from `self.norm`.

**Comment by dhruvmetha** [comment]
I resolved it, I need to not include 'norm_cfg' for the backbone of the model.

**Comment by tesar-tech** [comment]
This is also true for dpt net
