### ISSUE TITLE
Can not load STDC2 backbone successfully

### ISSUE THREAD

**Issue by ChenDirk** [open-mmlab/mmsegmentation#1418]
Hi,
    I convert the model with the command: `python tools/model_converters/stdc2mmseg.py ./STDCNet1446_76.47.tar ./pretrained/stdc2.pth STDC2`. But when I load the model, there are a lot of layers are not matched: `mmseg - INFO - load checkpoint from local path: ./pretrained/stdc2.pth
mmseg - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: stages.0.conv.weight, stages.0.bn.weight, stages.0.bn.bias, stages.0.bn.running_mean, stages.0.bn.running_var, stages.0.bn.num_batches_tracked, stages.1.conv.weight, stages.1.bn.weight, stages.1.bn.bias, stages.1.bn.running_mean, stages.1.bn.running_var, stages.1.bn.num_batches_tracked, stages.2.0.layers.0.conv.weight, stages.2.0.layers.0.bn.weight, stages.2.0.layers.0.bn.bias, stages.2.0.layers.0.bn.running_mean, stages.2.0.layers.0.bn.running_var, stages.2.0.layers.0.bn.num_batches_tracked, stages.2.0.layers.1.conv.weight, stages.2.0.layers.1.bn.weight, stages.2.0.layers.1.bn.bias, stages.2.0.layers.1.bn.running_mean, stages.2.0.layers.1.bn.running_var, stages.2.0.layers.1.bn.num_batches_tracked, stages.2.0.layers.2.conv.weight, stages.2.0.layers.2.bn.weight, stages.2.0.layers.2.bn.bias, stages.2.0.layers.2.bn.running_mean, stages.2.0.layers.2.bn.running_var, stages.2.0.layers.2.bn.num_batches_tracked, stages.2.0.layers.3.conv.weight, stages.2.0.layers.3.bn.weight, stages.2.0.layers.3.bn.bias, stages.2.0.layers.3.bn.running_mean, stages.2.0.layers.3.bn.running_var, stages.2.0.layers.3.bn.num_batches_tracked, stages.2.0.downsample.conv.weight, stages.2.0.downsample.bn.weight, stages.2.0.downsample.bn.bias, stages.2.0.downsample.bn.running_mean, stages.2.0.downsample.bn.running_var, stages.2.0.downsample.bn.num_batches_tracked, stages.2.1.layers.0.conv.weight, stages.2.1.layers.0.bn.weight, stages.2.1.layers.0.bn.bias, stages.2.1.layers.0.bn.running_mean, stages.2.1.layers.0.bn.running_var, stages.2.1.layers.0.bn.num_batches_tracked, stages.2.1.layers.1.conv.weight, stages.2.1.layers.1.bn.weight, stages.2.1.layers.1.bn.bias, stages.2.1.layers.1.bn.running_mean, stages.2.1.layers.1.bn.running_var, stages.2.1.layers.1.bn.num_batches_tracked, stages.2.1.layers.2.conv.weight, stages.2.1.layers.2.bn.weight, stages.2.1.layers.2.bn.bias, stages.2.1.layers.2.bn.running_mean, stages.2.1.layers.2.bn.running_var, stages.2.1.layers.2.bn.num_batches_tracked, stages.2.1.layers.3.conv.weight, stages.2.1.layers.3.bn.weight, stages.2.1.layers.3.bn.bias, stages.2.1.layers.3.bn.running_mean, stages.2.1.layers.3.bn.running_var, stages.2.1.layers.3.bn.num_batches_tracked, stages.2.2.layers.0.conv.weight, stages.2.2.layers.0.bn.weight, stages.2.2.layers.0.bn.bias, stages.2.2.layers.0.bn.running_mean, stages.2.2.layers.0.bn.running_var, stages.2.2.layers.0.bn.num_batches_tracked, stages.2.2.layers.1.conv.weight, stages.2.2.layers.1.bn.weight, stages.2.2.layers.1.bn.bias, stages.2.2.layers.1.bn.running_mean, stages.2.2.layers.1.bn.running_var, stages.2.2.layers.1.bn.num_batches_tracked, stages.2.2.layers.2.conv.weight, stages.2.2.layers.2.bn.weight, stages.2.2.layers.2.bn.bias, stages.2.2.layers.2.bn.running_mean, stages.2.2.layers.2.bn.running_var, stages.2.2.layers.2.bn.num_batches_tracked, stages.2.2.layers.3.conv.weight, stages.2.2.layers.3.bn.weight, stages.2.2.layers.3.bn.bias, stages.2.2.layers.3.bn.running_mean, stages.2.2.layers.3.bn.running_var, stages.2.2.layers.3.bn.num_batches_tracked, stages.2.3.layers.0.conv.weight, stages.2.3.layers.0.bn.weight, stages.2.3.layers.0.bn.bias, stages.2.3.layers.0.bn.running_mean, stages.2.3.layers.0.bn.running_var, stages.2.3.layers.0.bn.num_batches_tracked, stages.2.3.layers.1.conv.weight, stages.2.3.layers.1.bn.weight, stages.2.3.layers.1.bn.bias, stages.2.3.layers.1.bn.running_mean, stages.2.3.layers.1.bn.running_var, stages.2.3.layers.1.bn.num_batches_tracked, stages.2.3.layers.2.conv.weight, stages.2.3.layers.2.bn.weight, stages.2.3.layers.2.bn.bias, stages.2.3.layers.2.bn.running_mean, stages.2.3.layers.2.bn.running_var, stages.2.3.layers.2.bn.num_batches_tracked, stages.2.3.layers.3.conv.weight, stages.2.3.layers.3.bn.weight, stages.2.3.layers.3.bn.bias, stages.2.3.layers.3.bn.running_mean, stages.2.3.layers.3.bn.running_var, stages.2.3.layers.3.bn.num_batches_tracked, stages.3.0.layers.0.conv.weight, stages.3.0.layers.0.bn.weight, stages.3.0.layers.0.bn.bias, stages.3.0.layers.0.bn.running_mean, stages.3.0.layers.0.bn.running_var, stages.3.0.layers.0.bn.num_batches_tracked, stages.3.0.layers.1.conv.weight, stages.3.0.layers.1.bn.weight, stages.3.0.layers.1.bn.bias, stages.3.0.layers.1.bn.running_mean, stages.3.0.layers.1.bn.running_var, stages.3.0.layers.1.bn.num_batches_tracked, stages.3.0.layers.2.conv.weight, stages.3.0.layers.2.bn.weight, stages.3.0.layers.2.bn.bias, stages.3.0.layers.2.bn.running_mean, stages.3.0.layers.2.bn.running_var, stages.3.0.layers.2.bn.num_batches_tracked, stages.3.0.layers.3.conv.weight, stages.3.0.layers.3.bn.weight, stages.3.0.layers.3.bn.bias, stages.3.0.layers.3.bn.running_mean, stages.3.0.layers.3.bn.running_var, stages.3.0.layers.3.bn.num_batches_tracked, stages.3.0.downsample.conv.weight, stages.3.0.downsample.bn.weight, stages.3.0.downsample.bn.bias, stages.3.0.downsample.bn.running_mean, stages.3.0.downsample.bn.running_var, stages.3.0.downsample.bn.num_batches_tracked, stages.3.1.layers.0.conv.weight, stages.3.1.layers.0.bn.weight, stages.3.1.layers.0.bn.bias, stages.3.1.layers.0.bn.running_mean, stages.3.1.layers.0.bn.running_var, stages.3.1.layers.0.bn.num_batches_tracked, stages.3.1.layers.1.conv.weight, stages.3.1.layers.1.bn.weight, stages.3.1.layers.1.bn.bias, stages.3.1.layers.1.bn.running_mean, stages.3.1.layers.1.bn.running_var, stages.3.1.layers.1.bn.num_batches_tracked, stages.3.1.layers.2.conv.weight, stages.3.1.layers.2.bn.weight, stages.3.1.layers.2.bn.bias, stages.3.1.layers.2.bn.running_mean, stages.3.1.layers.2.bn.running_var, stages.3.1.layers.2.bn.num_batches_tracked, stages.3.1.layers.3.conv.weight, stages.3.1.layers.3.bn.weight, stages.3.1.layers.3.bn.bias, stages.3.1.layers.3.bn.running_mean, stages.3.1.layers.3.bn.running_var, stages.3.1.layers.3.bn.num_batches_tracked, stages.3.2.layers.0.conv.weight, stages.3.2.layers.0.bn.weight, stages.3.2.layers.0.bn.bias, stages.3.2.layers.0.bn.running_mean, stages.3.2.layers.0.bn.running_var, stages.3.2.layers.0.bn.num_batches_tracked, stages.3.2.layers.1.conv.weight, stages.3.2.layers.1.bn.weight, stages.3.2.layers.1.bn.bias, stages.3.2.layers.1.bn.running_mean, stages.3.2.layers.1.bn.running_var, stages.3.2.layers.1.bn.num_batches_tracked, stages.3.2.layers.2.conv.weight, stages.3.2.layers.2.bn.weight, stages.3.2.layers.2.bn.bias, stages.3.2.layers.2.bn.running_mean, stages.3.2.layers.2.bn.running_var, stages.3.2.layers.2.bn.num_batches_tracked, stages.3.2.layers.3.conv.weight, stages.3.2.layers.3.bn.weight, stages.3.2.layers.3.bn.bias, stages.3.2.layers.3.bn.running_mean, stages.3.2.layers.3.bn.running_var, stages.3.2.layers.3.bn.num_batches_tracked, stages.3.3.layers.0.conv.weight, stages.3.3.layers.0.bn.weight, stages.3.3.layers.0.bn.bias, stages.3.3.layers.0.bn.running_mean, stages.3.3.layers.0.bn.running_var, stages.3.3.layers.0.bn.num_batches_tracked, stages.3.3.layers.1.conv.weight, stages.3.3.layers.1.bn.weight, stages.3.3.layers.1.bn.bias, stages.3.3.layers.1.bn.running_mean, stages.3.3.layers.1.bn.running_var, stages.3.3.layers.1.bn.num_batches_tracked, stages.3.3.layers.2.conv.weight, stages.3.3.layers.2.bn.weight, stages.3.3.layers.2.bn.bias, stages.3.3.layers.2.bn.running_mean, stages.3.3.layers.2.bn.running_var, stages.3.3.layers.2.bn.num_batches_tracked, stages.3.3.layers.3.conv.weight, stages.3.3.layers.3.bn.weight, stages.3.3.layers.3.bn.bias, stages.3.3.layers.3.bn.running_mean, stages.3.3.layers.3.bn.running_var, stages.3.3.layers.3.bn.num_batches_tracked, stages.3.4.layers.0.conv.weight, stages.3.4.layers.0.bn.weight, stages.3.4.layers.0.bn.bias, stages.3.4.layers.0.bn.running_mean, stages.3.4.layers.0.bn.running_var, stages.3.4.layers.0.bn.num_batches_tracked, stages.3.4.layers.1.conv.weight, stages.3.4.layers.1.bn.weight, stages.3.4.layers.1.bn.bias, stages.3.4.layers.1.bn.running_mean, stages.3.4.layers.1.bn.running_var, stages.3.4.layers.1.bn.num_batches_tracked, stages.3.4.layers.2.conv.weight, stages.3.4.layers.2.bn.weight, stages.3.4.layers.2.bn.bias, stages.3.4.layers.2.bn.running_mean, stages.3.4.layers.2.bn.running_var, stages.3.4.layers.2.bn.num_batches_tracked, stages.3.4.layers.3.conv.weight, stages.3.4.layers.3.bn.weight, stages.3.4.layers.3.bn.bias, stages.3.4.layers.3.bn.running_mean, stages.3.4.layers.3.bn.running_var, stages.3.4.layers.3.bn.num_batches_tracked, stages.4.0.layers.0.conv.weight, stages.4.0.layers.0.bn.weight, stages.4.0.layers.0.bn.bias, stages.4.0.layers.0.bn.running_mean, stages.4.0.layers.0.bn.running_var, stages.4.0.layers.0.bn.num_batches_tracked, stages.4.0.layers.1.conv.weight, stages.4.0.layers.1.bn.weight, stages.4.0.layers.1.bn.bias, stages.4.0.layers.1.bn.running_mean, stages.4.0.layers.1.bn.running_var, stages.4.0.layers.1.bn.num_batches_tracked, stages.4.0.layers.2.conv.weight, stages.4.0.layers.2.bn.weight, stages.4.0.layers.2.bn.bias, stages.4.0.layers.2.bn.running_mean, stages.4.0.layers.2.bn.running_var, stages.4.0.layers.2.bn.num_batches_tracked, stages.4.0.layers.3.conv.weight, stages.4.0.layers.3.bn.weight, stages.4.0.layers.3.bn.bias, stages.4.0.layers.3.bn.running_mean, stages.4.0.layers.3.bn.running_var, stages.4.0.layers.3.bn.num_batches_tracked, stages.4.0.downsample.conv.weight, stages.4.0.downsample.bn.weight, stages.4.0.downsample.bn.bias, stages.4.0.downsample.bn.running_mean, stages.4.0.downsample.bn.running_var, stages.4.0.downsample.bn.num_batches_tracked, stages.4.1.layers.0.conv.weight, stages.4.1.layers.0.bn.weight, stages.4.1.layers.0.bn.bias, stages.4.1.layers.0.bn.running_mean, stages.4.1.layers.0.bn.running_var, stages.4.1.layers.0.bn.num_batches_tracked, stages.4.1.layers.1.conv.weight, stages.4.1.layers.1.bn.weight, stages.4.1.layers.1.bn.bias, stages.4.1.layers.1.bn.running_mean, stages.4.1.layers.1.bn.running_var, stages.4.1.layers.1.bn.num_batches_tracked, stages.4.1.layers.2.conv.weight, stages.4.1.layers.2.bn.weight, stages.4.1.layers.2.bn.bias, stages.4.1.layers.2.bn.running_mean, stages.4.1.layers.2.bn.running_var, stages.4.1.layers.2.bn.num_batches_tracked, stages.4.1.layers.3.conv.weight, stages.4.1.layers.3.bn.weight, stages.4.1.layers.3.bn.bias, stages.4.1.layers.3.bn.running_mean, stages.4.1.layers.3.bn.running_var, stages.4.1.layers.3.bn.num_batches_tracked, stages.4.2.layers.0.conv.weight, stages.4.2.layers.0.bn.weight, stages.4.2.layers.0.bn.bias, stages.4.2.layers.0.bn.running_mean, stages.4.2.layers.0.bn.running_var, stages.4.2.layers.0.bn.num_batches_tracked, stages.4.2.layers.1.conv.weight, stages.4.2.layers.1.bn.weight, stages.4.2.layers.1.bn.bias, stages.4.2.layers.1.bn.running_mean, stages.4.2.layers.1.bn.running_var, stages.4.2.layers.1.bn.num_batches_tracked, stages.4.2.layers.2.conv.weight, stages.4.2.layers.2.bn.weight, stages.4.2.layers.2.bn.bias, stages.4.2.layers.2.bn.running_mean, stages.4.2.layers.2.bn.running_var, stages.4.2.layers.2.bn.num_batches_tracked, stages.4.2.layers.3.conv.weight, stages.4.2.layers.3.bn.weight, stages.4.2.layers.3.bn.bias, stages.4.2.layers.3.bn.running_mean, stages.4.2.layers.3.bn.running_var, stages.4.2.layers.3.bn.num_batches_tracked`

I think the pretrained weight is not loaded sucessfully, but I don't know the reason.

**Comment by MengzhangLI** [comment]
Could you try to use latest config successfully?

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/stdc/stdc2_in1k-pre_512x1024_80k_cityscapes.py

**Comment by ChenDirk** [comment]
> Could you try to use latest config successfully?
> 
> https://github.com/open-mmlab/mmsegmentation/blob/master/configs/stdc/stdc2_in1k-pre_512x1024_80k_cityscapes.py

OK, it's work now. Thank you a lot.
