### ISSUE TITLE
数据增强transform中的RandomCrop问题

### ISSUE THREAD

**Issue by Gavin-Hanks** [open-mmlab/mmsegmentation#1429]
![image](https://user-images.githubusercontent.com/49432828/160527062-3b2e83d7-ea20-418b-b3c2-3456be8a7b37.png)
源代码问题：对于0类忽略，背景全为None情况，报错。修改如下
![image](https://user-images.githubusercontent.com/49432828/160527214-ad757173-9fb9-44da-aaa9-0fab2830b833.png)
后面的实验结果需要重新调参。

**Comment by MengzhangLI** [comment]
Hi, we have fixed related error, please check out our related [pr](https://github.com/open-mmlab/mmsegmentation/pull/1409).  

Could you try to use our latest master branch and look forward to your reply!

Best,
