### ISSUE TITLE
model size was not changed by reduce the crop size and resize 

### ISSUE THREAD

**Issue by huang45** [open-mmlab/mmsegmentation#144]
changes in the config file:

crop_size = **(512, 512)**
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', **img_scale=(860, 540)**, ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        **img_scale=(860, 540),**
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

but the model size was not changed.
The input shape was not changed:

Input shape: (3, 2048, 1024)
Flops: 7.53 GFLOPs
Params: 1.21 M

**Comment by xvjiarui** [comment]
Hi @huang45 
Are you using `tools/get_flops.py`? If so, you may try passing `--shape 860 540`

**Comment by huang45** [comment]
@xvjiarui Yes. By adding --shape 860 540, the Flops is reduced to 1.69 GFLOPs, but the Params is same. The pth file size is also not changed. Is it normal? thanks.

Input shape: (3, 860, 540)
Flops: 1.69 GFLOPs
Params: 1.21 M

**Comment by xvjiarui** [comment]
Hi @huang45 
The model size or the number of params is not related to input size.
