### ISSUE TITLE
Variable size inputs

### ISSUE THREAD

**Issue by AliKafaei** [open-mmlab/mmsegmentation#1440]
Hi, 
Does the provided network works on different size inputs similar to CNNs?
I need to estimate full image parametric distribution of ultrasound data and I cannot resize the input images since this changes the distribution of input.
Regards,
Ali

**Comment by MeowZheng** [comment]
What exactly is your image shape, and which model would you like to use? We may help you to solve the problem by revising the cfg

**Comment by AliKafaei** [comment]
My image shapes are 320*256 or 384*320. My output is not the segmentation  mask and it is a 4 channel regression. I usually use segmentation networks like Deeplab for this task and it worked by changing the last convolution layers.

**Comment by MeowZheng** [comment]
You may revise the crop_size to make sure the images are the same size, and may remove `Resize` transform to keep the distribution of input, and both of changes are in data cfg file like.
https://github.com/open-mmlab/mmsegmentation/blob/1924470e0ea5b610bcbb301ee9036678b0ab28fc/configs/_base_/datasets/ade20k_640x640.py#L6-L11
