### ISSUE TITLE
Convert Segmenter pretrained model

### ISSUE THREAD

**Issue by pdejorge** [open-mmlab/mmsegmentation#1441]
Hi,

I would like to use the Segmenter model with mmseg. However, I want to use the model pre-trained on Cityscapes (that is available on the official repo: https://github.com/rstrudel/segmenter) but has not been imported to mmseg format.

Is there a reason why it wasn't imported? Would there be an easy way to convert the weights? I noticed there's a script but only for the ViT backbone, not the whole segmenter.

Thanks in advance!

**Comment by MeowZheng** [comment]
Segmenter has been supported in MMSeg, just try it for free https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segmenter

**Comment by MengzhangLI** [comment]
Because those models are not pretrained model, they are trained-well models on Cityscapes.

Our "pretrained" model means the model pretrained on ImageNet for downstream task such as object detection and semantic segmentation. 

You can use our pretrained model and train it in cityscapes to get similar model.

**Comment by pdejorge** [comment]
Thank you @MengzhangLI  and @MeowZheng  how do I specify in the config file that I want to use some pre-trained weights for the backbone?

**Comment by valentinpatrascu** [comment]
@pdejorge did you solve this conversion problem? I'm facing the same issues and the provided answer is not very clear.

**Comment by pdejorge** [comment]
Hi @valentinpatrascu I did not mange to import the weights from the original segmenter repo, instead I re-trained on cityscapes with mmseg myself.

**Comment by valentinpatrascu** [comment]
Thank you, @pdejorge, for your quick response and clarifications. I'll use your method. Appreciate your help!
