### ISSUE TITLE
"work_dir" setting error

### ISSUE THREAD

**Issue by zhk779** [open-mmlab/mmsegmentation#1442]
Thanks for your amazing work. I have successfully train my own network.
Now I want to continue to train my model precisely ，but when I set the "work_dir"  use command below some problem has come out.
`bash tools/dist_train.sh configs/edanet/edanet_r50-d8_769x769_80k_cityscapes.py 2 --work_dir work_dirs/edanet_r50-d8_769x769_80k_cityscapes/precisely `
#ERROR:
`train.py: error: unrecognized arguments: --work_dir work_dirs/edanet_r50-d8_769x769_80k_cityscapes/precisely
usage: train.py [-h] [--work-dir WORK_DIR] [--load-from LOAD_FROM]
                [--resume-from RESUME_FROM] [--no-validate]
                [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...] | --gpu-id
                GPU_ID] [--seed SEED] [--diff_seed] [--deterministic]
                [--options OPTIONS [OPTIONS ...]]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK] [--auto-resume]
                config
train.py: error: unrecognized arguments: --work_dir work_dirs/edanet_r50-d8_769x769_80k_cityscapes/precisely
Traceback (most recent call last):
  File "/home/snow/Application/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/snow/Application/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/snow/Application/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/snow/Application/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
`
It seems like the train.py can not recognize the command "--work_dir work" 
when use the original config files like "danet_r50-d8_769x769_80k_cityscapes " it have the problem too
can you give me some advise? thanks

**Comment by MeowZheng** [comment]
use `--work-dir` instead of `--work_dir`

**Comment by zhk779** [comment]
> MeowZheng 
OMG! 
thanks for your reply! thanks very much
