### ISSUE TITLE
Forward_test in cascade_encoder

### ISSUE THREAD

**Issue by JihwanEom** [open-mmlab/mmsegmentation#1443]
Hi, thank you for your awesome works!

I have a question or suggestion in cascade_encoder.py (mmseg/models/segmentors/cascade_encoder_decoder.py)

This file overrides forward_train in encoder_decoder.py, but the **forward_test function is inherited from encoder_decoder straightly**.

I think it can be a problem when the user want to conduct forward test in cascade_encoder, cause forward_test method is not overrode suitably for cascade model. (I think "Modulelist does not have decode_forward_test attribute." error will be occur.)

Could you explain why cascade encoder decoder does not override forward_test function and how do you think about update this model which overrides forward_test function?

Thank you.
Jihwan

**Comment by MeowZheng** [comment]
`encode_decode` has been overrided in `CascadeEncoderDecoder ` ref: https://github.com/open-mmlab/mmsegmentation/blob/be8f073c844e93b60b3a5d9b67cf1b019eea0bc2/mmseg/models/segmentors/cascade_encoder_decoder.py#L51 and when model test, the `inference` will be called, and  `whole_inference` or `slide_inference` will call the overrided `encode_decode` like https://github.com/open-mmlab/mmsegmentation/blob/be8f073c844e93b60b3a5d9b67cf1b019eea0bc2/mmseg/models/segmentors/encoder_decoder.py#L203
