### ISSUE TITLE
Correct Readme

### ISSUE THREAD

**Issue by Junjun2016** [open-mmlab/mmsegmentation#1448]
https://github.com/open-mmlab/mmsegmentation/tree/master/configs/dnlnet#results-and-models-in-progress

![image](https://user-images.githubusercontent.com/16716329/161827402-38fc4f0f-0afd-43da-9079-e5b1efeb7f68.png)

Should remove in progress

**Comment by MengzhangLI** [comment]
Thx. I would collect incompleted data and make a pr to fix it.

Best,
