### ISSUE TITLE
Which file introduce variable "gt_semantic_seg" into \mmseg\models\decode_heads\decode_head.py, line 187?

### ISSUE THREAD

**Issue by yuejunpeng** [open-mmlab/mmsegmentation#1457]
We want to use the variable "gt_semantic_seg" in \mmseg\models\decode_heads\decode_head.py(line 187). However, we don't know where does the variable come from. Which file introduce variable "gt_semantic_seg" into the class BaseDecodeHead?
It will help us a lot. Thank you very much!

**Comment by MeowZheng** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/4bd32f4c3dec15b54e64197570edc3ab3fdcf164/mmseg/models/segmentors/encoder_decoder.py#L87
