### ISSUE TITLE
When evaluating the Segformer using the official config, the FPS is only half than official report.

### ISSUE THREAD

**Issue by demonsjin** [open-mmlab/mmsegmentation#1458]
**Describe the issue**

We observed that when evaluating on the ade20k dataset with the official Segformer pre-trained model and configuration, the inference speed is twice as slow as the official one, i.e., the FPS is only half of the official one.

**Reproduction**

1. What command or script did you run?

```
CUDA_VISIBLE_DEVICES=4 python ./tools/benchmark.py ./configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py ./checkpoints/segformer_mit-b5_512x512_160k_ade20k_20210726_145235-94cedf59.pth
```

2. What config dir you run?

```
./configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py 
```

3. Did you make any modifications to the code or config? Did you understand what you have modified?
    No. I did not make any modifications to the code or config.

4. What dataset did you use?
    ade20k

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmseg/utils/collect_env.py` to collect the necessary environment information and paste it here.

   sys.platform: linux
Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5: Tesla V100S-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 1.11.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu102
OpenCV: 4.5.5
MMCV: 1.4.8
MMCV Compiler: GCC 8.3
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.23.0+dfcc0b6

**Results**

If applicable, paste the related results here, e.g., what you expect and what you get.

```
Run 1:
2022-04-07 21:50:02,134 - mmseg - INFO - Loaded 2000 images
/home/wangzj/source/projects/OpenMMLab/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:225: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: ./checkpoints/segformer_mit-b5_512x512_160k_ade20k_20210726_145235-94cedf59.pth
Done image [50 / 200], fps: 4.83 img / s
Done image [100/ 200], fps: 5.58 img / s
Done image [150/ 200], fps: 5.24 img / s
Done image [200/ 200], fps: 5.14 img / s
Overall fps: 5.14 img / s
```

**Comment by RockeyCoss** [comment]
Maybe it's caused by fluctuation. Could you try running command `CUDA_VISIBLE_DEVICES=4 python ./tools/benchmark.py ./configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py ./checkpoints/segformer_mit-b5_512x512_160k_ade20k_20210726_145235-94cedf59.pth --repeat-times 10`.

**Comment by demonsjin** [comment]
> Maybe it's caused by fluctuation. Could you try running command `CUDA_VISIBLE_DEVICES=4 python ./tools/benchmark.py ./configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py ./checkpoints/segformer_mit-b5_512x512_160k_ade20k_20210726_145235-94cedf59.pth --repeat-times 10` ?

Thank you! The CPU running at full capacity is the cause of the above problems.
