### ISSUE TITLE
STDC training on fp16: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

### ISSUE THREAD

**Issue by HunterL233** [open-mmlab/mmsegmentation#1462]
在stdc1_512x1024_80k_cityscapes.py中添加了
```
optimizer_config = dict(type='Fp16OptimizerHook', loss_scale='dynamic')
fp16 = dict()
```
后再次进行训练则出现了以下报错
![avatar](https://img-blog.csdnimg.cn/97204a9e0c434537b3ee297a5d589968.png)

请问该如何修改

**Comment by MeowZheng** [comment]
Thanks for your report this bug, I'm fixing it in #1463

**Comment by HunterL233** [comment]
> Thanks for your report this bug, I'm fixing it in #1463

感谢回复

**Comment by MengzhangLI** [comment]
> > Thanks for your report this bug, I'm fixing it in #1463
> 
> 感谢回复

Hi, when you try to set `seg_label = seg_label.to(self.laplacian_kernel)`, does this fix your error?

**Comment by HunterL233** [comment]
> > > Thanks for your report this bug, I'm fixing it in #1463
> > 
> > 
> > 感谢回复
> 
> Hi, when you try to set `seg_label = seg_label.to(self.laplacian_kernel)`, does this fix your error?

yeah,it works thx so much
