### ISSUE TITLE
Why using RepeatDataset can reduce the data loading time between epochs?

### ISSUE THREAD

**Issue by Magic-Ha** [open-mmlab/mmsegmentation#1467]
I am curious about how dose RepeatDataset work to reduce data loading time.
It seems that the code of RepeatDataset just increase the length of dataset.

**Comment by MeowZheng** [comment]
`RepeatDataset` increases the length of the dataset, so it will save the time for works of the dataloader shutting down when the entire training dataset is completed and the time for workers launching for the next.

Pytorch 1.7 started to support `persistent_workers`  ref: https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader,
which also can save time for dataloader, and mmseg defaults to turning on persistent_works.
