### ISSUE TITLE
my ignore label is zero,how can i set a bunch of parameters?

### ISSUE THREAD

**Issue by York1996OutLook** [open-mmlab/mmsegmentation#147]
label zero（bg） is ignore label 
how can i set 

`    CLASSES = ('bg','freespace_road', 'road_patch', 'road_concave_convex', 'road_breakage',
               'road_crack', 'manhole_cover', 'road_mark', 'speed_bumps',
               'across_rail', 'nonstandard_obstacle',)`

'    CLASSES = ('bg','freespace_road', 'road_patch', 'road_concave_convex', 'road_breakage',
               'road_crack', 'manhole_cover', 'road_mark', 'speed_bumps',
               'across_rail', 'nonstandard_obstacle',)'

reduce_zero_label=true or false?
ignore_index=255 or 0?
num_classes=10 or 11？
            # class_weight = [0.12,   25.9,
            #                 2.0,    15.2,
            #                 31.4,   11.5,
            #                 4.4,    68.6,
            #                 10.0,   295.6
            #                 ], or 11 nums?
i got confused.

**Comment by xvjiarui** [comment]
Hi @York1996OutLook 
If you `bg` correspond to 0 in annotation, you should set `reduce_zero_label=True`. 
Then `class_weight` should be 10.

**Comment by hblab-haims** [comment]
I also use 0 as background, here my config. Hope it could help.

![image](https://user-images.githubusercontent.com/89757661/146111650-86b721a1-6953-4b54-b63e-d761076cf545.png)
