### ISSUE TITLE
ConvNeXt ONNX export causes floating point exception

### ISSUE THREAD

**Issue by r0l1** [open-mmlab/mmsegmentation#1476]
The latest mmsegmentation (master code from today) causes a floating point exception(core dumped) while exporting one of the ConvNeXt models to onnx. Sadly there is no more log information.

**Comment by RunningLeon** [comment]
@r0l1 Hi, what script you run? Could post here.

**Comment by r0l1** [comment]
Currently I am using the `pytorch2onnx.py` script. I know that it will be deprecated soon. However I strongly believe, that this is a PyTorch problem.

**Comment by r0l1** [comment]
Fixed in latest version
