### ISSUE TITLE
Segformer pretrained weight

### ISSUE THREAD

**Issue by shengyi4** [open-mmlab/mmsegmentation#1483]
Hi, I have a question about how can I find the mit-b5.pth for the segformer? Could you please send me a link to this file? Thanks!

**Comment by MengzhangLI** [comment]
Follow the usage here: https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segformer#usage

`mit-b5.pth` from [official repo](https://github.com/NVlabs/SegFormer) may be downloaded here: https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia.

**Comment by Raintell** [comment]
this link just aspired, could you please tell me where to download th mit b5 pretrained weight?
