### ISSUE TITLE
How to predict sementation without background?

### ISSUE THREAD

**Issue by Anm-pinellia** [open-mmlab/mmsegmentation#1485]
I want to train a model that using gt_imgs which contained background(its label is set as 0).
For example, [0, 1, 2, 3, 4, 5, 6, 7, 8] is the label in my dataset and 0 denotes the background and i do not want to predict a label_img with the background label 0. 

For the class code of dataset, i have set the default value of its reduce_zero_label to True.
Besides, the num_classes in the config of the model is also set to the number of classes ( set to 8) in my dataset.

I am confused that its predict results still contained the background label 0, how to fix this problem?

**Comment by MeowZheng** [comment]
I also feel confused, if you don't want to predict ladel 0, which label will assign to the pixels of background?

**Comment by Anm-pinellia** [comment]
> I also feel confused, if you don't want to predict ladel 0, which label will assign to the pixels of background?

I want to predict all pixels with foreground pixel (without label 0)

**Comment by MeowZheng** [comment]
If there are pixels belonging to the background in the image,  which label will assign to these pixels?

**Comment by Anm-pinellia** [comment]
> If there are pixels belonging to the background in the image, which label will assign to these pixels?

Thanks for your question to make me bright, I have got your idea. In my original idea, each pixel is classified into its most likely class (without background(useless pixels)).

I have tried some methods to do this work. But it seems that they all cannot work well.
So I added the background as a single category in the code of Datasets, and set reduce_zero_label = False.
In the config of model, I set the num_classes = number of classes + 1, and set class_weight to 0.1 for background.
Is this is a way to train my custom datasets?

Besides, there still existed some questiones about the parameter of reduce_zero_label. 
By reading some other issues, I have found that ignore_index in loss function seems a good way to avoid to calculate background loss. However, in the latest version segmentation. It seems that the parameter 'ignore_index' cannot be defined in config file and its default name is set to -100 in its code.
```
    def forward(self,
                cls_score,
                label,
                weight=None,
                avg_factor=None,
                reduction_override=None,
                ignore_index=-100,
                **kwargs)
```:
Therefore, I want to know if the reduce_zero_label parameter has been modified to replace background value to -100 instead of reduce all value with 1 in annotation images?

**Comment by MeowZheng** [comment]
ignore_index can be defined in decode_head cfg, ref: https://github.com/open-mmlab/mmsegmentation/blob/2aed0dec91ca14c48b8bcb9ce299dddc5d09ddc6/mmseg/models/decode_heads/decode_head.py#L45

**Comment by MeowZheng** [comment]
Sorry for the inactive reply, I think you might try the similar solution in ADE20K
https://github.com/open-mmlab/mmsegmentation/blob/ae0fac4a3601d116cdcc2ee17a5812110697ade9/mmseg/datasets/ade.py#L124-L127

**Comment by Junjun2016** [comment]
> I want to train a model that using gt_imgs which contained background(its label is set as 0). For example, [0, 1, 2, 3, 4, 5, 6, 7, 8] is the label in my dataset and 0 denotes the background and i do not want to predict a label_img with the background label 0.
> 
> For the class code of dataset, i have set the default value of its reduce_zero_label to True. Besides, the num_classes in the config of the model is also set to the number of classes ( set to 8) in my dataset.
> 
> I am confused that its predict results still contained the background label 0, how to fix this problem?

If you set reduce_zero_label to True, the prediction label 0 is the first class in your annotation, corresponding to 1 in [0, 1, 2, 3, 4, 5, 6, 7, 8].

**Comment by Anm-pinellia** [comment]
> > I want to train a model that using gt_imgs which contained background(its label is set as 0). For example, [0, 1, 2, 3, 4, 5, 6, 7, 8] is the label in my dataset and 0 denotes the background and i do not want to predict a label_img with the background label 0.
> > For the class code of dataset, i have set the default value of its reduce_zero_label to True. Besides, the num_classes in the config of the model is also set to the number of classes ( set to 8) in my dataset.
> > I am confused that its predict results still contained the background label 0, how to fix this problem?
> 
> If you set reduce_zero_label to True, the prediction label 0 is the first class in your annotation, corresponding to 1 in [0, 1, 2, 3, 4, 5, 6, 7, 8].

Thanks a lot for this suggestion. We have tested this way and tested the background as a independent class. As the results shown, it seems that reduce_zero_label and set classes to 8 can not perform well. Besides, in this way, the results label image should be added 1 to corresponding to the GT label image. In other way, see the background as a category, the networks can work well. Thanks for your comment again.
