### ISSUE TITLE
error:Input and output must have the same number of spatial dimensions

### ISSUE THREAD

**Issue by theneao** [open-mmlab/mmsegmentation#1488]
I used **deeplabv3 +** and **user-defined dataset** for training, main modified documents and the results are as follows:
Added **my_oil_spill.py** files in the **mmseg/datasets/** directory
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from mmseg.datasets.builder import DATASETS
from mmseg.datasets.custom import CustomDataset
import os.path as osp

@DATASETS.register_module()
class OILDataset(CustomDataset):
    CLASSES = ("Sea", "Look-alike","oil","land","ship")
    PALETTE = [[0, 0, 0], [255,0,0],[0,255,255],[0,153,0],[153,76,0]]

    def __init__(self, split, **kwargs):
        super().__init__(img_suffix='.jpg', seg_map_suffix='.png',
                         split=split, **kwargs)

        assert osp.exists(self.img_dir) and self.split is not None
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The image size is 1250 * 650 gray image(I don't think it's a big problem as a three-channel input), and the label file is 1250 * 650 * 3
configs/__base__/ oil_spill.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dataset_type = 'OILDataset'
data_root = '/home/tmp_2/mmsegmentation/data/Oil Spill Detection Dataset/'
img_norm_cfg = dict(
    mean=[132.221, 132.221, 132.221], std=[60.913, 60.913, 60.913], to_rgb=True)
crop_size = (650, 650)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(1250, 650), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion',contrast_range=(0.5, 1.0)),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1250, 650),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='train/images',
        ann_dir='train/labels',
        pipeline=train_pipeline,
        split="train/train.txt"),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='train/images',
        ann_dir='train/labels',
        split="train/val.txt",
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='test/images',
        ann_dir='test/labels',
        split="test/val.txt",
        pipeline=test_pipeline))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**deeplabv3plus_r50-d8_650x1250_20k_oil_spill.py**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_base_ = [
    '../_base_/models/deeplabv3plus_r50-d8.py',
    '../_base_/datasets/oil_spill.py', '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_20k.py'
]
model = dict(
    decode_head=dict(num_classes=5), auxiliary_head=dict(num_classes=5))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Error report**

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~·
Traceback (most recent call last):
  File "/home/tmp_2/mmsegmentation/tools/train.py", line 240, in <module>
    main()
  File "/home/tmp_2/mmsegmentation/tools/train.py", line 229, in main
    train_segmentor(
  File "/home/tmp_2/mmsegmentation/mmseg/apis/train.py", line 191, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/parallel/data_parallel.py", line 60, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/base.py", line 138, in train_step
    losses = self(**data_batch)
  File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 143, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 86, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "/home/tmp_2/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 204, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "/home/tmp_2/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 235, in losses
    seg_logit = resize(
  File "/home/tmp_2/mmsegmentation/mmseg/ops/wrappers.py", line 27, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/nn/functional.py", line 3835, in interpolate
    raise ValueError(
**ValueError: Input and output must have the same number of spatial dimensions, but got input with with spatial dimensions of [163, 163] and output size of torch.Size([650, 650, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I just started to learn how to use this platform. After following the tutorial, there is no place related to 163 * 163. I don't know how to modify it, but I found that modifying the **crop_size = (650, 650)** in the **configs/__base__/ oil_spill.py**
 file will make 163 * 163 change proportionally

**Comment by MeowZheng** [comment]
As deeplabv3+ outputs a quarter resolution seg_logit, 163*163 is the shape of seg_logit, and it will be resized to the resolution of seg_label 
ref: https://github.com/open-mmlab/mmsegmentation/blob/e2315839858577715dcdd59cf6b05d0a3b551882/mmseg/models/decode_heads/decode_head.py#L235-L239

The problem you met might be the gt_label is a color image which has wrong shape, and the correct shape of seg_label is (H, W) and here are some example to convert seg_label from color 
ref: https://github.com/open-mmlab/mmsegmentation/blob/e2315839858577715dcdd59cf6b05d0a3b551882/tools/convert_datasets/isaid.py#L37-L45

**Comment by theneao** [comment]
I seem to understand that there may be a problem with the format of the annotation picture, but I don't particularly understand what I should do.

Should I modify the format of my annotation image according to the referenced functions, or modify the configuration file or call some functions, because the configuration file and annotation image look no different from online tutorial and the original configuration with deeplabV+.

In addition, I have been able to train normally by modifying the file
 **mmseg/datasets/my_oil_spill.py**  
**PALETTE = [0，1，2，3，4]**
 and using the gray-scale annotation image, but due to **a single channel PALETTE error** during the test, only the PALETTE in the output file of the test can be forced to modify, and finally the result will be normal.

**Comment by MeowZheng** [comment]
yes, just convert your annotation label from image to seg_map

**Comment by javadmozaffari** [comment]
hi, I have the same problem.
how should I convert the annotation label from the image to seg_map?

**Comment by MeowZheng** [comment]
> hi, I have the same problem. how should I convert the annotation label from the image to seg_map?

I think you should

**Comment by shengyi4** [comment]
I want to follow up on this. How should we convert the annotation label from image to seg_map? Thanks!

**Comment by shengyi4** [comment]
> I seem to understand that there may be a problem with the format of the annotation picture, but I don't particularly understand what I should do.
> 
> Should I modify the format of my annotation image according to the referenced functions, or modify the configuration file or call some functions, because the configuration file and annotation image look no different from online tutorial and the original configuration with deeplabV+.
> 
> In addition, I have been able to train normally by modifying the file **mmseg/datasets/my_oil_spill.py** **PALETTE = [0，1，2，3，4]** and using the gray-scale annotation image, but due to **a single channel PALETTE error** during the test, only the PALETTE in the output file of the test can be forced to change to three channels, and finally the result will be normal.

Hi, could you please elaborate on how to do the conversion? Thanks so much!

**Comment by theneao** [comment]
Because my grayscale image can be used, it has not been modified recently.

I thought it might be a picture generated by data under a map class, but after careful search, I found that there seems to be no relevant information, and my previous image format seems to be consistent with the standard data set. After reading the document, **I found that there is a need for BGR value for PALETTE， I entered RGB value before, which should be the problem.** (I haven't tested yet, you can try)

**Comment by theneao** [comment]
The label image seems to be a single channel label image rather than a color image. The pigment value should correspond to the class name in **CLASSES**. The pigment of the first class starts from 0. **PALETTE** should be the output color during verification, which has little to do with the training annotation image.``


Irregular data sets need to be converted. You can refer to this link. [https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#prepare-datasets](url)
The self-made dataset can be marked and regenerated according to the rules

**Comment by superqf** [comment]
Use potsdam.py in tools convert_datasets to convert colored tag graphs to usable ones

> I used **deeplabv3 +** and **user-defined dataset** for training, main modified documents and the results are as follows: Added **my_oil_spill.py** files in the **mmseg/datasets/** directory
> 
> ```
> from mmseg.datasets.builder import DATASETS
> from mmseg.datasets.custom import CustomDataset
> import os.path as osp
> 
> @DATASETS.register_module()
> class OILDataset(CustomDataset):
>     CLASSES = ("Sea", "Look-alike","oil","land","ship")
>     PALETTE = [[0, 0, 0], [255,0,0],[0,255,255],[0,153,0],[153,76,0]]
> 
>     def __init__(self, split, **kwargs):
>         super().__init__(img_suffix='.jpg', seg_map_suffix='.png',
>                          split=split, **kwargs)
> 
>         assert osp.exists(self.img_dir) and self.split is not None
> ```
> 
> The image size is 1250 * 650 gray image(I don't think it's a big problem as a three-channel input), and the label file is 1250 * 650 * 3 configs/**base**/ oil_spill.py
> 
> ```
> dataset_type = 'OILDataset'
> data_root = '/home/tmp_2/mmsegmentation/data/Oil Spill Detection Dataset/'
> img_norm_cfg = dict(
>     mean=[132.221, 132.221, 132.221], std=[60.913, 60.913, 60.913], to_rgb=True)
> crop_size = (650, 650)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations'),
>     dict(type='Resize', img_scale=(1250, 650), ratio_range=(0.5, 2.0)),
>     dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
>     dict(type='RandomFlip', prob=0.5),
>     dict(type='PhotoMetricDistortion',contrast_range=(0.5, 1.0)),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_semantic_seg']),
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(1250, 650),
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> data = dict(
>     samples_per_gpu=2,
>     workers_per_gpu=2,
>     train=dict(
>         type=dataset_type,
>         data_root=data_root,
>         img_dir='train/images',
>         ann_dir='train/labels',
>         pipeline=train_pipeline,
>         split="train/train.txt"),
>     val=dict(
>         type=dataset_type,
>         data_root=data_root,
>         img_dir='train/images',
>         ann_dir='train/labels',
>         split="train/val.txt",
>         pipeline=test_pipeline),
>     test=dict(
>         type=dataset_type,
>         data_root=data_root,
>         img_dir='test/images',
>         ann_dir='test/labels',
>         split="test/val.txt",
>         pipeline=test_pipeline))
> ```
> 
> **deeplabv3plus_r50-d8_650x1250_20k_oil_spill.py**
> 
> ```
> _base_ = [
>     '../_base_/models/deeplabv3plus_r50-d8.py',
>     '../_base_/datasets/oil_spill.py', '../_base_/default_runtime.py',
>     '../_base_/schedules/schedule_20k.py'
> ]
> model = dict(
>     decode_head=dict(num_classes=5), auxiliary_head=dict(num_classes=5))
> ```
> 
> **Error report**
> 
> ```
> Traceback (most recent call last):
>   File "/home/tmp_2/mmsegmentation/tools/train.py", line 240, in <module>
>     main()
>   File "/home/tmp_2/mmsegmentation/tools/train.py", line 229, in main
>     train_segmentor(
>   File "/home/tmp_2/mmsegmentation/mmseg/apis/train.py", line 191, in train_segmentor
>     runner.run(data_loaders, cfg.workflow)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
>     iter_runner(iter_loaders[i], **kwargs)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
>     outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/parallel/data_parallel.py", line 60, in train_step
>     return self.module.train_step(*inputs[0], **kwargs[0])
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/base.py", line 138, in train_step
>     losses = self(**data_batch)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/base.py", line 108, in forward
>     return self.forward_train(img, img_metas, **kwargs)
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 143, in forward_train
>     loss_decode = self._decode_head_forward_train(x, img_metas,
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 86, in _decode_head_forward_train
>     loss_decode = self.decode_head.forward_train(x, img_metas,
>   File "/home/tmp_2/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 204, in forward_train
>     losses = self.losses(seg_logits, gt_semantic_seg)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/tmp_2/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 235, in losses
>     seg_logit = resize(
>   File "/home/tmp_2/mmsegmentation/mmseg/ops/wrappers.py", line 27, in resize
>     return F.interpolate(input, size, scale_factor, mode, align_corners)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/nn/functional.py", line 3835, in interpolate
>     raise ValueError(
> **ValueError: Input and output must have the same number of spatial dimensions, but got input with with spatial dimensions of [163, 163] and output size of torch.Size([650, 650, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.**
> ```
> 
> I just started to learn how to use this platform. After following the tutorial, there is no place related to 163 * 163. I don't know how to modify it, but I found that modifying the **crop_size = (650, 650)** in the **configs/**base**/ oil_spill.py** file will make 163 * 163 change proportionally

Use potsdam.py in tools convert_datasets to convert colored tag graphs to usable ones

**Comment by superqf** [comment]
> I used **deeplabv3 +** and **user-defined dataset** for training, main modified documents and the results are as follows: Added **my_oil_spill.py** files in the **mmseg/datasets/** directory
> 
> ```
> from mmseg.datasets.builder import DATASETS
> from mmseg.datasets.custom import CustomDataset
> import os.path as osp
> 
> @DATASETS.register_module()
> class OILDataset(CustomDataset):
>     CLASSES = ("Sea", "Look-alike","oil","land","ship")
>     PALETTE = [[0, 0, 0], [255,0,0],[0,255,255],[0,153,0],[153,76,0]]
> 
>     def __init__(self, split, **kwargs):
>         super().__init__(img_suffix='.jpg', seg_map_suffix='.png',
>                          split=split, **kwargs)
> 
>         assert osp.exists(self.img_dir) and self.split is not None
> ```
> 
> The image size is 1250 * 650 gray image(I don't think it's a big problem as a three-channel input), and the label file is 1250 * 650 * 3 configs/**base**/ oil_spill.py
> 
> ```
> dataset_type = 'OILDataset'
> data_root = '/home/tmp_2/mmsegmentation/data/Oil Spill Detection Dataset/'
> img_norm_cfg = dict(
>     mean=[132.221, 132.221, 132.221], std=[60.913, 60.913, 60.913], to_rgb=True)
> crop_size = (650, 650)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations'),
>     dict(type='Resize', img_scale=(1250, 650), ratio_range=(0.5, 2.0)),
>     dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
>     dict(type='RandomFlip', prob=0.5),
>     dict(type='PhotoMetricDistortion',contrast_range=(0.5, 1.0)),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_semantic_seg']),
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(1250, 650),
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> data = dict(
>     samples_per_gpu=2,
>     workers_per_gpu=2,
>     train=dict(
>         type=dataset_type,
>         data_root=data_root,
>         img_dir='train/images',
>         ann_dir='train/labels',
>         pipeline=train_pipeline,
>         split="train/train.txt"),
>     val=dict(
>         type=dataset_type,
>         data_root=data_root,
>         img_dir='train/images',
>         ann_dir='train/labels',
>         split="train/val.txt",
>         pipeline=test_pipeline),
>     test=dict(
>         type=dataset_type,
>         data_root=data_root,
>         img_dir='test/images',
>         ann_dir='test/labels',
>         split="test/val.txt",
>         pipeline=test_pipeline))
> ```
> 
> **deeplabv3plus_r50-d8_650x1250_20k_oil_spill.py**
> 
> ```
> _base_ = [
>     '../_base_/models/deeplabv3plus_r50-d8.py',
>     '../_base_/datasets/oil_spill.py', '../_base_/default_runtime.py',
>     '../_base_/schedules/schedule_20k.py'
> ]
> model = dict(
>     decode_head=dict(num_classes=5), auxiliary_head=dict(num_classes=5))
> ```
> 
> **Error report**
> 
> ```
> Traceback (most recent call last):
>   File "/home/tmp_2/mmsegmentation/tools/train.py", line 240, in <module>
>     main()
>   File "/home/tmp_2/mmsegmentation/tools/train.py", line 229, in main
>     train_segmentor(
>   File "/home/tmp_2/mmsegmentation/mmseg/apis/train.py", line 191, in train_segmentor
>     runner.run(data_loaders, cfg.workflow)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
>     iter_runner(iter_loaders[i], **kwargs)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
>     outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/parallel/data_parallel.py", line 60, in train_step
>     return self.module.train_step(*inputs[0], **kwargs[0])
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/base.py", line 138, in train_step
>     losses = self(**data_batch)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/base.py", line 108, in forward
>     return self.forward_train(img, img_metas, **kwargs)
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 143, in forward_train
>     loss_decode = self._decode_head_forward_train(x, img_metas,
>   File "/home/tmp_2/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 86, in _decode_head_forward_train
>     loss_decode = self.decode_head.forward_train(x, img_metas,
>   File "/home/tmp_2/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 204, in forward_train
>     losses = self.losses(seg_logits, gt_semantic_seg)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/tmp_2/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 235, in losses
>     seg_logit = resize(
>   File "/home/tmp_2/mmsegmentation/mmseg/ops/wrappers.py", line 27, in resize
>     return F.interpolate(input, size, scale_factor, mode, align_corners)
>   File "/home/tmp_2/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/nn/functional.py", line 3835, in interpolate
>     raise ValueError(
> **ValueError: Input and output must have the same number of spatial dimensions, but got input with with spatial dimensions of [163, 163] and output size of torch.Size([650, 650, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.**
> ```
> 
> I just started to learn how to use this platform. After following the tutorial, there is no place related to 163 * 163. I don't know how to modify it, but I found that modifying the **crop_size = (650, 650)** in the **configs/**base**/ oil_spill.py** file will make 163 * 163 change proportionally

This is because the label diagram is a color diagram， Use potsdam.py in tools convert_datasets to convert colored tag graphs to usable ones

**Comment by sammilei** [comment]
I met the same issue with Segmenter. My root cause was the label images are RGB but not grayscale. Once I convert them to grayscale, the error is gone and training goes smoothly.
