### ISSUE TITLE
train with swin backbone

### ISSUE THREAD

**Issue by shengyi4** [open-mmlab/mmsegmentation#1495]
I am tring to reproduce the result for uppernet + swin transformer. However, when I run: python tools/train.py configs/swin/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K.py . It shows an error like this: 
Traceback (most recent call last):
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\verifier.py", line 43, in VerifyCode
    compile(textwrap.dedent(code).encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 2
    work_dir = './work_dirs\upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K'
                                                                                                       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 11-12: truncated \uXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\verifier.py", line 46, in VerifyCode
    ast.parse(textwrap.dedent(code.lstrip('\n')).lstrip(), '<string>', 'exec')
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<string>", line 1
    work_dir = './work_dirs\upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K'
                                                                                                       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 11-12: truncated \uXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\verifier.py", line 50, in VerifyCode
    compile(normalized_code.encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 1
    work_dir = './work_dirs\upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K'
                                                                                                       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 11-12: truncated \uXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sheng\Desktop\mmsegmentation\tools\train.py", line 209, in <module>
    main()
  File "C:\Users\sheng\Desktop\mmsegmentation\tools\train.py", line 135, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\config.py", line 564, in dump
    f.write(self.pretty_text)
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\config.py", line 502, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\yapf_api.py", line 188, in FormatCode
    reformatted_source = FormatTree(
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\yapf_api.py", line 151, in FormatTree
    return reformatter.Reformat(_SplitSemicolons(llines), verify, lines)
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\reformatter.py", line 105, in Reformat
    return _FormatFinalLines(final_lines, verify)
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\reformatter.py", line 413, in _FormatFinalLines
    verifier.VerifyCode(formatted_code[-1])
  File "C:\Users\sheng\miniconda3\envs\open-mmlab\lib\site-packages\yapf\yapflib\verifier.py", line 52, in VerifyCode
    raise InternalError(sys.exc_info()[1])
yapf.yapflib.verifier.InternalError: (unicode error) 'unicodeescape' codec can't decode bytes in position 11-12: truncated \uXXXX escape (<string>, line 1)

It worked fine with other configures. Does anyone else encounter this problem? Thanks.

**Comment by MengzhangLI** [comment]
`work_dir = './work_dirs\upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K'`

I think it is caused by wrong path, perhaps caused by different OS environment (windows and linux)?

**Comment by shengyi4** [comment]
Thanks for your feedback! I am using windows. I didn't specify the path in the configuration file as well. It worked for other configurations (deep lab v3, segformer, and so on). But it doesn't work for swin.

**Comment by shengyi4** [comment]
Thanks! It works when I set the path in the command line.

**Comment by Donfugui** [comment]
excuse me ,the same error happens to me now, i wonder how you solve the issue exactly, thanks

**Comment by scm-later** [comment]
![QQ图片20220810154056](https://user-images.githubusercontent.com/89558994/183845815-89c7bce1-4a8c-45e4-94b9-b76351d4909c.png)
![QFY1EVD O939@$5(0F5593J](https://user-images.githubusercontent.com/89558994/183846560-5386c5cf-8fab-42d6-a65b-fc591996d5c6.png)
the same error happens to me now

**Comment by duduzai2019** [comment]
> ![QQ图片20220810154056](https://user-images.githubusercontent.com/89558994/183845815-89c7bce1-4a8c-45e4-94b9-b76351d4909c.png) ![QFY1EVD O939@$5(0F5593J](https://user-images.githubusercontent.com/89558994/183846560-5386c5cf-8fab-42d6-a65b-fc591996d5c6.png) 我现在也发生了同样的错误

Hi, excuse me ,the same error happens to me now, i wonder how you solve the issue exactly, thanks,

**Comment by duduzai2019** [comment]
> Thanks! It works when I set the path in the command line.

![image](https://user-images.githubusercontent.com/96464964/185569042-eb5b79e2-2047-4adf-9594-22f49107fef6.png)

**Comment by duduzai2019** [comment]
> excuse me ,the same error happens to me now, i wonder how you solve the issue exactly, thanks

![image](https://user-images.githubusercontent.com/96464964/185569096-2f9e079d-073d-4c67-8d93-95f0519aba44.png)
excuse me ,the same error happens to me now, i wonder how you solve the issue exactly, thanks

**Comment by duduzai2019** [comment]
the error is unicoder, so i find the dataset corresponds files, replace the data_root to \\ 
, after can train nomally 
![image](https://user-images.githubusercontent.com/96464964/185571221-557a6bdf-a331-40f5-8417-cf5833e776a4.png)

**Comment by zznew** [comment]
因为Swin Transformer的backone为upernet, os.path.join()会使用"\\"来拼接路径，这样就会出现\u，而\uXXXX代表一个unicode编码。所以找到代码中的os.path.join()全部修改就好了
![image](https://github.com/open-mmlab/mmsegmentation/assets/42693642/d3fba47a-7b1f-4977-b111-f13f9719fce4)
