### ISSUE TITLE
Batch size and training time

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmsegmentation#1497]
Hi,
I have a confusion and hope to get your help. During the training phase, other conditions remain the same, why does the larger the batch_size I use, the longer the training takes?
Thanks!

**Comment by MeowZheng** [comment]
The training schedule is Iter-based, which is fixed iteration number, and the time will be longer as the batch size is larger.

**Comment by wwjwy** [comment]
Thank you very much for your timely reply.
