### ISSUE TITLE
How to customize a hook to achieve dynamic loss weight?

### ISSUE THREAD

**Issue by ICE-Bro** [open-mmlab/mmsegmentation#1498]
I want to set weight related to the number of iterations for my defined loss, and found that the default hook cannot achieve this. Is there any way to customize the hook or other methods to achieve dynamic loss weight?

**Comment by PeterVennerstrom** [comment]
You could write a new hook.  There don't appear to be custom hooks in mmsegmentation already, but there are in mmdetection and they both rely on the mmcv runner class to train.  

You can use [mmdetection custom hooks](https://github.com/open-mmlab/mmdetection/tree/bde7b4b7eea9dd6ee91a486c6996b2d68662366d/mmdet/core/hook) as examples.

**Comment by ICE-Bro** [comment]
@PeterVennerstrom Thanks so much
