### ISSUE TITLE
Is there something wrong in tools/convert_datasets/isaid.py

### ISSUE THREAD

**Issue by xushilin1** [open-mmlab/mmsegmentation#1504]
I get the data following the  [tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#isaid) and run tools/convert_datasets/isaid.py.

But each label file i got from this script almost contains 0 or [0,1] values;

e.g.
```
np.unique(np.array(Image.open('data/iSAID/ann_dir/val/P0004_instance_color_RGB.png')))
array([0,1], dtype=uint8)
```

**Comment by MengzhangLI** [comment]
Some png file just have certain labels, you could use our provided ckpt to testify whether your local isaid dataset is the same with us.

https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3plus#isaid

**Comment by xushilin1** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/62c3a7dda9aab13481760c9aa9e494001ea1fa89/tools/convert_datasets/isaid.py#L136
`lab_patch` is one channel , use `mode=p` will get `lab_patch` different with origin `lab_patch`.
I've verified it pillow==9.0.0

**Comment by MengzhangLI** [comment]
Could you preprocess your iSAID dataset and use provided ckpt to testify whether it is correct?

In our default setting (patch_width=896, patch_height=896, overlap_area=384), it will generate 33978 images for training and 11644 images for validation.

https://github.com/open-mmlab/mmsegmentation/tree/master/configs/pspnet#isaid

![image](https://user-images.githubusercontent.com/24582831/165221205-c8c95633-c3f6-49d6-aaf2-4ab7389113e1.png)

**Comment by xushilin1** [comment]
I got the mIoU number you provided, but the dataset is generated by removing `mode=p`. 
When  using the `mode=p`, the generated ground truth masks almost contain 0 or [0,1].
You can generate a little label files to verify it,

**Comment by sherwincn** [comment]
I have the same question. Could you tell me how to solve the problem?

> I got the mIoU number you provided, but the dataset is generated by removing . When using the , the generated ground truth masks almost contain 0 or [0,1]. You can generate a little label files to verify it,`mode=p``mode=p`

**Comment by xushilin1** [comment]
> remove `mode=p` in this line.

https://github.com/open-mmlab/mmsegmentation/blob/62c3a7dda9aab13481760c9aa9e494001ea1fa89/tools/convert_datasets/isaid.py#L136

**Comment by sherwincn** [comment]
> lab_patch = Image.fromarray(lab_patch.astype(np.uint8)

I remove  `mode=p` in fromarry function. But the label also only has 0 or 15. Do you succeed to finish converting dataset?

**Comment by sherwincn** [comment]
> > remove `mode=p` in this line.
> 
> https://github.com/open-mmlab/mmsegmentation/blob/62c3a7dda9aab13481760c9aa9e494001ea1fa89/tools/convert_datasets/isaid.py#L136

Could you provide me the scripts? Thanks a lot.
