### ISSUE TITLE
 mmseg - INFO - Checkpoints will be saved to /mnt/DATA/tianbiao/code/mmsegmentation/work_dirs/deeplabv3_unet_s5-d16_128x128_40k_chase_db1 by HardDiskBackend.

### ISSUE THREAD

**Issue by tian-003** [open-mmlab/mmsegmentation#1505]
In python train.py, the program will stop here, all the time, will not continue to go down, what is the reason?
![image](https://user-images.githubusercontent.com/84436043/164960304-5bf9ad72-27a8-4bcd-8381-fa707c93c4cc.png)

**Comment by MengzhangLI** [comment]
It is a small model training on a small dataset, I think it is your local server problem.

**Comment by MeowZheng** [comment]
please try t below cfg for data
```
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=0,  
    persistent_workers=False
)
```

**Comment by jkasimotto** [comment]
Hi @MeowZheng, I have added the above cfg to my data file and the problem persists.
![image](https://user-images.githubusercontent.com/67080621/185774092-a8e7a7ac-a4cd-4d89-a020-dc3cf8aceac3.png)

Like @tian-003 my program stops here. 
![image](https://user-images.githubusercontent.com/67080621/185774117-262bf953-c036-46ce-89a2-8483396b99c2.png)

**Comment by jkasimotto** [comment]
Sorry disregard the above. Because I am running on CPU it is slow. I waited for a few minutes and it is working.
