### ISSUE TITLE
Questions on reproducing mIoU for DeepLabV3 MobileNetV2

### ISSUE THREAD

**Issue by Hrayo712** [open-mmlab/mmsegmentation#1508]
Hi,

I am trying to reproduce the following mIoU reported on your page:

![image](https://user-images.githubusercontent.com/34102313/165051201-d3fae352-aa70-431f-8bf8-e170169c5359.png)

To do this I am running the following command:

`python tools/test.py configs/mobilenet_v2/deeplabv3_m-v2-d8_512x1024_80k_cityscapes.py demo/checkpoints/deeplabv3_m-v2-d8_512x1024_80k_cityscapes_20200825_124836-bef03590.pth --eval cityscapes`

However, I am obtaining 74.1 mIoU, instead of 73.84, as shown in the image below

![image](https://user-images.githubusercontent.com/34102313/165051489-b5d047a3-1e5f-4865-8c3a-330c51a0f55f.png)

My questions are the following:

-   is the table outdated and this is the real number ? or am I running evaluation incorrectly ? (The fact that is higher is nice btw, just want to know :) )
-   inspection of the config file shows that on testing, this model uses the full resolution, that is: `(2048, 1024)`, instead of the crop size which used during training. i.e., `(512, 1024)`. This would mean that the mIoU is calculated with a resolution that does not correspond to what the model sees during training. Is this ok ? Furthermore, this means that during inference, (running at 512x1024), we should actually expect a lower performance, right ?

Thanks for your great work.

Regards

**Comment by MengzhangLI** [comment]
Could you report results by using 
`python tools/test.py configs/mobilenet_v2/deeplabv3_m-v2-d8_512x1024_80k_cityscapes.py demo/checkpoints/deeplabv3_m-v2-d8_512x1024_80k_cityscapes_20200825_124836-bef03590.pth --eval mIoU`? If I remember well, evaluation metric of `mIoU` and `cityscapes` are a little different.

**Comment by MengzhangLI** [comment]
The second question, it is OK because we prefer to inference on original resolution and based on my current experience, it would not make results worse obviously so you can rest assured on your cityscapes experiments.

**Comment by Hrayo712** [comment]
Hi,

Thanks for the prompt response!

Here the comparison between running the evaluation with `mIoU `vs `cityscapes`

![image](https://user-images.githubusercontent.com/34102313/165074981-ddf02a84-ea79-45b5-9ca3-304a4d5e2418.png)

On the second question:
I agree with your claim. But e.g., if we export the model to ONNX for running inference on an embedded device using the crop size resolution (for faster inference e.g.,), then performance would be worse than what's reported. So I guess I should evaluate the model using the crop size to get a better impression of what I can obtain when running inference at that resolution

**Comment by MengzhangLI** [comment]
> Hi,
> 
> Thanks for the prompt response!
> 
> Here the comparison between running the evaluation with `mIoU `vs `cityscapes`
> 
> ![image](https://user-images.githubusercontent.com/34102313/165074981-ddf02a84-ea79-45b5-9ca3-304a4d5e2418.png)
> 
> As you see, results are quite close, and still superior to what's reported on the repo
> 
> On the second question: I agree with your claim. But e.g., if we export the model to ONNX for running inference on an embedded device using the crop size resolution (for faster inference e.g.,), then performance would be worse than what's reported. So I guess I should evaluate the model using the crop size to get a better impression of what I can obtain when running inference at that resolution

As far as I know on MMSegmentation, it may also be caused by different PyTorch version (but I'm not sure whether it is the reason in your case). You can check other checkpoints we released to testify whether the difference between your local environment and out READMD shows is acceptable.

Honestly, I do not have ONNX experience, so I am looking forward to your evaluation results, if you have other problems just keep in touch with MMSegmentation  and MMDeploy.

Best,

**Comment by Hrayo712** [comment]
Hi. 

Thanks again for your input.

Just for your information: 

I've adapted the model evaluation within tools/test.py to evaluate an onnx model exported via tools/pytorch2onnx.py, and got identical results :)

Closing issue now

Regards!
