### ISSUE TITLE
About STDC2

### ISSUE THREAD

**Issue by Wc66666** [open-mmlab/mmsegmentation#1510]
I want to load the trained model built in the pytorch native interface(for some reason,some projects only support pytorch native interface),so how can i get it easliy? Thank you!

**Comment by Wc66666** [comment]
sorry,my description may not be that accurate.I mean the model is trainde on the mmseg, i need convert it to pytorch native interface.

**Comment by MeowZheng** [comment]
Could you try to use inference api in mmseg?

```python
from mmseg.apis import init_segmentor, inference_segmentor
model = init_segmentor(config_file, checkpoint_file, device='cuda:0')
img = 'demo.png'
result = inference_segmentor(model, img)
```

models in mmseg have their data protocol, so I suggest to using the high-level inference API

**Comment by Wc66666** [comment]
in fact,I  load the trained model in pytorch  native interface  not only do inference,other functions rely on the net built in  native interface.
