### ISSUE TITLE
Difference between exporting to ONNX via pytorch2onnx.py and using MMDeploy

### ISSUE THREAD

**Issue by Hrayo712** [open-mmlab/mmsegmentation#1516]
Hi,

I've come across MMDeploy, and wonder. What is the difference between exporting torch MMSeg models using tools/pytorch2onnx.py and MMdeploy ? (assuming the export works correctly in both cases)

What kind of features are introduced by mmdeploy ?

**Comment by MeowZheng** [comment]
cc @lvhan028

**Comment by lvhan028** [comment]
Hi, from the exporting onnx perspective, the major difference between mmdeploy and mmseg and other codebase is as below: 
- mmdeploy can export onnx without changing any code of mmseg. It designs a mechanism called `rewriter` that helps hacking mmseg in runtime. In the following example, the original function `mmseg.models.decode_heads.psp_head.PPM.forward` can be replaced with `ppm__forward`.
While in mmseg, if any module or function fails to export onnx, you probably have to change the code by introducing `if (torch.onnx.is_in_onnxexport())`. And it will hurt the code readability. 
```python
@FUNCTION_REWRITER.register_rewriter(
    func_name='mmseg.models.decode_heads.psp_head.PPM.forward')
def ppm__forward(ctx, self, x):
    ...
```

- mmdeploy also supports exporting different onnx models according to the real inference backend. We name this feature as backend-aware onnx. Take the well-known nms for example. 
When the inference backend is ONNX Runtime, nms can be exported as the official onnx op - [NonMaxSuppression](https://github.com/onnx/onnx/blob/main/docs/Operators.md#NonMaxSuppression). But when the backend is TensorRT, it is exported to `TRTBatchedNMS`, which improves the performance.
