### ISSUE TITLE
adding 'with_cp' option to beit

### ISSUE THREAD

**Issue by ydhongHIT** [open-mmlab/mmsegmentation#1528]
The memory cost of beit backbone is huge and you didn't implement the 'with_cp' option to save the memory. However, I add it by myself and the gpu memory doesn't get smaller. Maybe my implement has some problem or there is any reason for this phenomenon?

**Comment by MengzhangLI** [comment]
Juse because the memory on readme are set `cudnn_benchmark = False`. You could modify [it](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/default_runtime.py#L14) and try again.

By the way, I really want to support DDRNet in MMSegmentation but do not have too much time to do it, would you mind helping us making a PR to support it? Thanks in advance.

**Comment by ydhongHIT** [comment]
> Juse because the memory on readme is set `cudnn_benchmark = False`. You could modify [it](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/default_runtime.py#L14) and try again.
> 
> By the way, I really want to support DDRNet in MMSegmentation but do not have too much time to do it, would you mind helping us making a PR to support it? Thanks in advance.

Thanks for your interest. I am working on another program currently and will try to PR after finishing this. The 'cudnn_benchmark' has been set to 'True'. And setting 'with_cp' to 'True' indeed reduces the memory of some models under the same settings.

**Comment by ydhongHIT** [comment]
Setting 'cuda_benchmark' to 'False' helps, thank you! But setting 'with_cp' to 'True' indeed reduces the memory of some models even though 'cuda_benchmark' is 'True'.

**Comment by MengzhangLI** [comment]
> 

OK, thats cool! Do you have clear time schedule about your current program?

**Comment by ydhongHIT** [comment]
> > 
> 
> OK, thats cool! Do you have clear time schedule about your current program?

Maybe two or three months but not sure.

**Comment by MeowZheng** [comment]
> > Juse because the memory on readme is set `cudnn_benchmark = False`. You could modify [it](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/default_runtime.py#L14) and try again.
> > By the way, I really want to support DDRNet in MMSegmentation but do not have too much time to do it, would you mind helping us making a PR to support it? Thanks in advance.
> 
> Thanks for your interest. I am working on another program currently and will try to PR after finishing this. The 'cudnn_benchmark' has been set to 'True'. And setting 'with_cp' to 'True' indeed reduces the memory of some models under the same settings.

Thanks for suggestion, and we will add `with_cp` in BEiT, or would you like to create a nice pr to add it. If you have any implement problem, you might refer this pr https://github.com/open-mmlab/mmsegmentation/pull/1431
