### ISSUE TITLE
How to avoid automatic recovery of test time resize?

### ISSUE THREAD

**Issue by nestiank** [open-mmlab/mmsegmentation#1530]
Hello, I use (512, 512) size images for training and testing, and I want to inference with (256, 256) size images because of the contest rules. However, it seems that adding Resize process into test_pipeline like the code below does not work, as inference size persisted as (512, 512).

I think adding Resize process into test_pipeline is a kind of TTA, and I know that mmdetection automatically recovers all TTAs just before inference to avoid change of inference size or something like that. However, now I need that change.

Is there any way to permanently change test time image size without actually resizing test images?

Thanks!

```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', img_scale=(256, 256)), # Does not work(size auto-recovered)
    dict(
        type='MultiScaleFlipAug',
        img_scale=(256, 256),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True), # Does not work(size auto-recovered)
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

**Comment by nestiank** [comment]
If you don't mind, can you review my code? This code prints "512 512" and returns at L9~L10.
I believe that `single_gpu_test()` returns (512, 512) output, which is not resized.

My full project code is uploaded at:
https://github.com/boostcampaitech3/level2-semantic-segmentation-level2-cv-02/tree/juyoung_kim

```python
def make_predictions(output, cfg, loc: str) -> None:
    prediction_strings = []
    file_names = []

    coco = COCO(os.path.join(cfg.data_root, 'test.json'))

    for i, out in enumerate(output):
        if not (len(out) == 256 and len(out[0]) == 256):
            print(len(out), len(out[0])) # L9
            return # L10

if __name__ == '__main__':
    datasets = [build_dataset(cfg.data.train), build_dataset(cfg.data.test)]
    data_loader = build_dataloader(
        datasets[1],
        samples_per_gpu=1,
        workers_per_gpu=8,
        dist=False,
        shuffle=False
    )
    output = single_gpu_test(model, data_loader)
    make_predictions(output, cfg, f"./inference.csv")
```

**Comment by MeowZheng** [comment]
I think if you would like to test model with fixed input size, you can try this cfg
```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', img_scale=(256, 256))
]
```

**Comment by nestiank** [comment]
That does not work, as `single_gpu_test()` returns prediction with size of original image. I am looking for solutions that will make `single_gpu_test()` return prediction with size of (256, 256).

**Comment by MeowZheng** [comment]
I know your problem, sorry for my misunderstanding and improper solution. I think you can revise `whole_inference` and `slide_inference` and remove the code that resizes the predicted seg map as the original image.

Just add `rescale=False` in `model()` forward
https://github.com/open-mmlab/mmsegmentation/blob/bc60213d2ac4dacfe6acb29297958271679ae7a4/mmseg/apis/test.py#L91

ref:
https://github.com/open-mmlab/mmsegmentation/blob/bc60213d2ac4dacfe6acb29297958271679ae7a4/mmseg/models/segmentors/base.py#L62-L94
https://github.com/open-mmlab/mmsegmentation/blob/bc60213d2ac4dacfe6acb29297958271679ae7a4/mmseg/models/segmentors/encoder_decoder.py#L200-L217
https://github.com/open-mmlab/mmsegmentation/blob/bc60213d2ac4dacfe6acb29297958271679ae7a4/mmseg/models/segmentors/encoder_decoder.py#L155-L198

**Comment by nestiank** [comment]
It works! Thanks so much!
