### ISSUE TITLE
COCO Json

### ISSUE THREAD

**Issue by shengyi4** [open-mmlab/mmsegmentation#1544]
Hi,
I only have the coco json file for the custom coco dataset. How can I create the corresponding mask png images? Thanks.

**Comment by Muratoter** [comment]
I am also waiting for the answers to this question.

**Comment by ZhangYuef** [comment]
first download 
```
wget --directory-prefix=downloads http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip
```
unzip `/stuffthingmaps_trainval2017.zip` 
then unzip `annotations/ stuff_val2017_pixelmaps.zip`
