### ISSUE TITLE
Inference without MMCV

### ISSUE THREAD

**Issue by caihaunqai** [open-mmlab/mmsegmentation#1546]
After training with MMseg, if I continue to use simple torch to inference, can I easily extract the model code for inference, and no longer use the mmseg framework. Do I need to implement it myself or is there support?

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/1510#issuecomment-1108563801

I guess you would like to run the model in your own code, could you try to use inference api from mmseg?

```python
from mmseg.apis import init_segmentor, inference_segmentor
model = init_segmentor(config_file, checkpoint_file, device='cuda:0')
img = 'demo.png'
result = inference_segmentor(model, img)
```

models in mmseg have their data protocol, so I suggest to use the high-level inference API in mmseg

**Comment by caihaunqai** [comment]
Thank you~
