### ISSUE TITLE
MMCV&pytorch version

### ISSUE THREAD

**Issue by caihaunqai** [open-mmlab/mmsegmentation#1547]
Hello, I have installed several  versions of MMCV but it comes up with a lot errors, which seems that the version is not matched. Is the master branch must work with cuda 11? Can I use the master branch by pytorch 1.7 and cuda 10.2? If I can, which version of MMCV can I install?

**Comment by MengzhangLI** [comment]
Here is detailed relationship between MMCV and MMSegmentation version:

https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/get_started.md#prerequisites

**Comment by MeowZheng** [comment]
I suggest the latest MMCV-full, and if you would like to install latest mmcv-full with pytorch1.7 and cuda 10.2, you might try

```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html
```
please ref https://github.com/open-mmlab/mmcv#installation

**Comment by caihaunqai** [comment]
Thank you~
