### ISSUE TITLE
About the MAE backbone

### ISSUE THREAD

**Issue by k914** [open-mmlab/mmsegmentation#1552]
Hello, I was trying to use your MAE backbone code in a detection algorithm. But after I used your script [beit2mmseg.py] to convert the keys from the official MAE pre-trained model, I got the error:

Missing key(s) in state_dict: "layers.0.gamma_1", "layers.0.gamma_2", "layers.0.attn.relative_position_bias_table", "layers.0.attn.relative_position_index", "layers.1.gamma_1", "layers.1.gamma_2", "layers.1.attn.relative_position_bias_table", "layers.1.attn.relative_position_index", "layers.2.gamma_1", "layers.2.gamma_2", "layers.2.attn.relative_position_bias_table", "layers.2.attn.relative_position_index", "layers.3.gamma_1", "layers.3.gamma_2", "layers.3.attn.relative_position_bias_table", "layers.3.attn.relative_position_index", "layers.4.gamma_1", "layers.4.gamma_2", "layers.4.attn.relative_position_bias_table", "layers.4.attn.relative_position_index", "layers.5.gamma_1", "layers.5.gamma_2", "layers.5.attn.relative_position_bias_table", "layers.5.attn.relative_position_index", "layers.6.gamma_1", "layers.6.gamma_2", "layers.6.attn.relative_position_bias_table", "layers.6.attn.relative_position_index", "layers.7.gamma_1", "layers.7.gamma_2", "layers.7.attn.relative_position_bias_table", "layers.7.attn.relative_position_index", "layers.8.gamma_1", "layers.8.gamma_2", "layers.8.attn.relative_position_bias_table", "layers.8.attn.relative_position_index", "layers.9.gamma_1", "layers.9.gamma_2", "layers.9.attn.relative_position_bias_table", "layers.9.attn.relative_position_index", "layers.10.gamma_1", "layers.10.gamma_2", "layers.10.attn.relative_position_bias_table", "layers.10.attn.relative_position_index", "layers.11.gamma_1", "layers.11.gamma_2", "layers.11.attn.relative_position_bias_table", "layers.11.attn.relative_position_index". 
Unexpected key(s) in state_dict: "norm.weight", "norm.bias", "patch_embed.proj.weight", "patch_embed.proj.bias". 

Is this because I did something wrong?

**Comment by MeowZheng** [comment]
cc @YuanLiuuuuuu

**Comment by YuanLiuuuuuu** [comment]
Please set ``strict`` to ``False`` when using ``load_state_dict``

**Comment by k914** [comment]
> Please set `strict` to `False` when using `load_state_dict`

Thank you, that works.
