### ISSUE TITLE
Where are the files（VOCaug/dataset/cls） in VOC ?Does the CLS file need to be generated by ourselves?

### ISSUE THREAD

**Issue by zzjjxx994501847** [open-mmlab/mmsegmentation#156]
I converted my labeled data on Labelme into VOC data sets.
The file directory of VOC data set is：
JPEGImages
SegmentationClass
SegmentationClassPNG
SegmentationClassVisualization
SegmentationObject
SegmentationObjectPNG
SegmentationObjectVisualization
class_names.txt

I look at the VOC data set placement directory in the documentation：
│   ├── VOCdevkit
│   │   ├── VOC2012
│   │   │   ├── JPEGImages
│   │   │   ├── SegmentationClass
│   │   │   ├── ImageSets
│   │   │   │   ├── Segmentation
│   │   ├── VOCaug
│   │   │   ├── dataset
│   │   │   │   ├── cls

Where are the files（VOCaug/dataset/cls） in VOC ?Does the CLS file need to be generated by ourselves?

**Comment by xvjiarui** [comment]
`cls` is provided by VOCaug. If you are using your own dataset, it is not needed.

**Comment by Bmoradi93** [comment]
I have the same issue!
Would you please let us know what are those files and how we can get them?

**Comment by clemente0420** [comment]
same issue it's hard to run

**Comment by xxxyyynnn** [comment]
same issue it's hard to run
