### ISSUE TITLE
Does pytorch2onnx support multiple batches ？

### ISSUE THREAD

**Issue by tensorflowt** [open-mmlab/mmsegmentation#1561]
Hi！
I would like to ask, is it currently supported to convert the pth model to the onnx model in a multi-batchsize way?
Because I see that there are parameters written to dynamic input in the script pytorch2onnx，as the follow：
![a6606185f1737a41c121b6b9843fe5c](https://user-images.githubusercontent.com/37217594/167144148-a6008608-7a03-4a62-9dda-08ce992a0bdb.png)
https://github.com/open-mmlab/mmsegmentation/blob/master/tools/pytorch2onnx.py
Because the conversion of multiple batches is currently not supported through onnx2tensorrt.
![9e78997f3e8dc6c8dba488d54243264](https://user-images.githubusercontent.com/37217594/167144198-43918cc9-1ae6-4fdd-b65b-efd8f4110e53.png)
Looking forward to your reply, thank you very much!

**Comment by RunningLeon** [comment]
@tensorflowt Hi, if you want to deploy with TensorRT, do not need to set batch size in onnx. You could set `--min-shape`, and `--max-shape` of `onnx2tensorrt.py` with multi batch, such as '--min-shape 10 3 512 512`. BTW,  you could use [mmdeploy](https://github.com/open-mmlab/mmdeploy) as well.
