### ISSUE TITLE
Why does Resizing come before RandomCropping?

### ISSUE THREAD

**Issue by tldrafael** [open-mmlab/mmsegmentation#1570]
Hi, all. First, thanks for this great project.

Is there a specific reason for Resizing to happen before RandomCropping? I mean, why do not crop the image first, and then resize it to the desired resolution? 

https://github.com/open-mmlab/mmsegmentation/blob/740b54577064a4738e689d80b961c67d176bc319/configs/_base_/datasets/cityscapes.py#L10-L11

I especially asked it, because I have tried experiments with [RandomResizedCrop](RandomResizedCrop) on Pytorch, and based on the configuration of Cityscapes we could just set the area scale to (1/16, 1) and fix the aspect_ratio to (1, 1), and I also adapted my code to ensure the `cat_max_ratio` feature here, but I'm getting far worse results than using the sequence (resizing, random_cropping).

**Comment by MengzhangLI** [comment]
Hi, `Resize` (which may return different sizes by scale factor) come before `RandomCrop` could make sure the transformed data after `RandomCrop` have the same shape, which is used for consequently transformations in pipeline. 

Perhaps you could change `img_scale`, `ratio_range` and `crop_size`, here is detailed [config tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/config.md#an-example-of-pspnet).

**Comment by MengzhangLI** [comment]
> Thank you for your quick response, @MengzhangLI. So would that be the same as applying first `RandomCrop` of any size inside a scake, and then `Resize` it to a defined resolution, right?

Yes.
