### ISSUE TITLE
What type of segmentation map is support

### ISSUE THREAD

**Issue by waqarsqureshi** [open-mmlab/mmsegmentation#1572]
Here is my simple question. What type of segmentation map is supported in ground-truth segmentation. should it be a color image or a uint8 mask?

What I am able to understand that in the cityscape dataset. The index map of uint8 is only supported and not the color segmentation mask
I just did an experiment for a cityscape type dataset and I can say color maps are not supported. Is it a way to convert color maps to indexTrainIdmaps?

**Comment by timothylimyl** [comment]
Hi @waqarsqureshi ,

personally, I will use `pillow` to convert color images to uint8 mask. pseudocode example:

```
import os
import numpy as np
from PIL import Image

# Locations:
data_root = ... # put your root directory of data
ann_dir = ... # put your annotation images folder name

# Example of your palette format: 
palette = [[128,128,128],  [0,0,255], [0, 255, 0], [123,5,213]]  # Example that you have 4 class

# Go through your annotation directory containing the color images
for file in mmcv.scandir(os.path.join(data_root, ann_dir), suffix='.png'):
  seg_map = Image.open(os.path.join(data_root, ann_dir, file))
  seg_map = Image.fromarray(seg_map).convert('P')
  seg_map.putpalette(np.array(palette, dtype=np.uint8))
  seg_map.save(osp.join(data_root, ann_dir, file))
```

not too sure whether mmseg has the support for this, will have to wait for the  mmseg people to answer this. Happy to contribute a proper conversion script if there are none.

**Comment by MeowZheng** [comment]
Yes The index map of uint8 is only supported and not the color segmentation mask. For color seg mask, it can be converted to unit8 label.

For example:
https://github.com/open-mmlab/mmsegmentation/blob/214a0d327965237f260ca4703ebb84d0e1d1e36f/tools/convert_datasets/isaid.py#L37

**Comment by waqarsqureshi** [comment]
Thank you. I used a small script in OpenCV to convert. I think we can add a script in tools for others too. and mention somewhere in the documentation to help others.
