### ISSUE TITLE
Meaning of dilations and strides in backbone r50

### ISSUE THREAD

**Issue by hssandriss** [open-mmlab/mmsegmentation#1575]
Hello, 
Thank you for the great work in this library. 
I am new to mmsegmentation. I would like to ask you about details in model config like in resnet50 backbone implemented inside deeplabv3.

`
backbone=dict(
        type='ResNetV1c',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True)
`

I understand that out_indices refer to features produced at each stage or block. 
My question is mainly about dilations and strides. What do they mean in the context of stages? 
Is it that each conv layer in the corresponding stage should have that stride/dilation rate? If so can you please refer to the paper that mentions use of these values.

Thanks alot.

**Comment by MengzhangLI** [comment]
In [ResNet](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/resnet.py#L311) it shows:
```python
strides (Sequence[int]): Strides of the first block of each stage.
    Default: (1, 2, 2, 2).
dilations (Sequence[int]): Dilation of each stage.
    Default: (1, 1, 1, 1).
```
Their detailed implementation could be found below.

Ref: [Bag of Tricks for Image Classification with Convolutional Neural Networks](https://arxiv.org/pdf/1812.01187.pdf).
