### ISSUE TITLE
Any  methods or project for semi/self-suprevised methods?

### ISSUE THREAD

**Issue by xiangtaowong** [open-mmlab/mmsegmentation#1578]
Thanks for ur great work about mmsegmentation.
Do u have any  methods or project for semi/self-suprevised methods?

**Comment by MengzhangLI** [comment]
Hi, we do not have a plan for it due to limited human resources. But any PR from community is welcome!

**Comment by xiangtaowong** [comment]
> PR from community

ok, thanks for ur reply
