### ISSUE TITLE
How to freeze backbone(MAE) during finetune stage?

### ISSUE THREAD

**Issue by yitianlian** [open-mmlab/mmsegmentation#1579]
I use a pretrained MAE as my backbone and I want freeze it parameter during fintune stage.But when I add "frozen_stages=12", It will show error.How can I do?

![屏幕截图 2022-05-14 163249](https://user-images.githubusercontent.com/91449279/168417940-7fdcbe91-2096-456e-b1a0-f48f73740d2b.png)
and the error is
![InkedQQ图片20220514163345_LI](https://user-images.githubusercontent.com/91449279/168417979-e6cbd5a9-1344-4d65-ad8b-f1acc3626449.jpg)

**Comment by MengzhangLI** [comment]
Because `frozen_stages` is not supported in MAE. You could follow what HRNet did: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/hrnet.py#L570-L594, to set the parameters you want `requires_grad = False`.
