### ISSUE TITLE
MMclassification dependency

### ISSUE THREAD

**Issue by JihwanEom** [open-mmlab/mmsegmentation#1582]
Hi, sorry for several questions.

I've confirmed mmseg has mmclssification dependency from 0.22.0 version. But I'm not sure what was root cause for dependency.

Could you say specific reason for this dependency? Supporting for ConvNext? 

Thank you.
Jihwan

**Comment by MengzhangLI** [comment]
It uses ConvNeXt backbone from MMClassification:

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/upernet_convnext.py#L8

**Comment by JihwanEom** [comment]
Noted. Then I don't have to install mmcls if I never use ConvNext?

**Comment by MengzhangLI** [comment]
> 

Up to now, yes.

**Comment by JihwanEom** [comment]
Okay, thank you for your kind :) I'll close this issue. Thank you.
