### ISSUE TITLE
FP16 / Mixed precision training of HRNet+OCRHead causing significant performance drop

### ISSUE THREAD

**Issue by lorinczszabolcs** [open-mmlab/mmsegmentation#1584]
**Checklist**

1. I have searched related issues but cannot get the expected help. ✅
2. The bug has not been fixed in the latest version. ✅

**Description of the bug**
It seems like training OCRNet with HRNet backbone (not sure if it applies to other models as well, in my opinion it shouldn't), loses performance when trained using mixed precision / fp16. Tried training both with and without mixed precision. Using mixed precision the performance drops visibly. Are there any specific ops in HRNet / OCRHead that do not go well with mixed precision training?

**Reproduction**

1. What command or script did you run?
I am using a custom training script, but basically first calling ``build_dataset``, then ``build_segmentor``, finally ``train_segmentor``.

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, extended the original implementation to enable having multiple heads to predict multiple targets, apart from that I am using the original HRNet + OCRHead implementations, the heads are just simply duplicated.

4. What dataset did you use?
Custom data set, having multiple targets, one per head.

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla P100-PCIE-16GB
CUDA_HOME: None
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1
OpenCV: 4.5.5
MMCV: 1.4.2
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: not available
MMSegmentation: 0.22.1+a37f4b7

```
2.Additional info:
PyTorch is running in a docker container, based on the latest PyTorch image, no other env variables might be related in my opinion.

**Comment by linfangjian01** [comment]
How much has the performance dropped? What is the way to use FP16, dynamic or other?

**Comment by lorinczszabolcs** [comment]
Hi! Thanks for the quick reply. I am using FP16 by adding the following lines in the config:
```
# fp16 settings
optimizer_config = dict(type='Fp16OptimizerHook', loss_scale='dynamic')
# fp16 placeholder
fp16 = dict()
```

The performance has dropped from 77.81 mDice to 74.03 mDice (~5% performance drop) and from 66.25 mIoU to 62.31 mIoU (~6% performance drop).

**Comment by linfangjian01** [comment]
Yes, this does seem like a big performance reduction. I think it may be a special case caused by this model. Usually in our implementations, using fp16 does not generally result in performance degradation. In addition , I would suggest to use HRNet+other Head, or use other Backbone+OCRHead to check if the problem still exists. Also look for help from the community here to see if you can get some better suggestions.

**Comment by lorinczszabolcs** [comment]
I see, thank you for the suggestion! I will look into the different backbone and head combinations, to see if we can pinpoint the main cause.

**Comment by JihwanEom** [comment]
Hi @lorinczszabolcs, any update for this?

**Comment by lorinczszabolcs** [comment]
> Hi @lorinczszabolcs, any update for this?

Hi! I am currently running the experiments, should be ready sometime tomorrow. I will come back with the updates.

**Comment by JihwanEom** [comment]
Okay, thank you for your kind exciting :)

**Comment by lorinczszabolcs** [comment]
It seems that HRNet is the one causing the issue. The configurations and results are as follows, note the drop in performance between the last two:

**OCRHead** + ResNet50 : mDice 70.56
**OCRHead** + ResNet50 **fp16** : mDice 70.75
FCNHead + **HRNet** : mDice 72.27
FCNHead + **HRNet** **fp16** : mDice 70.95

**Comment by JihwanEom** [comment]
Looks like HRNet has weakness with FP16 training, and it is getting worse when HRNet is combined with OCRHead. (77.81 to 74.03)
Currently I don't have any opinion for HRNet in architecture perspective but I'll check it.
Thank you for sharing your valuable results, @lorinczszabolcs!

**Comment by lorinczszabolcs** [comment]
Another thing I forgot to mention: the performance drop is more prominent in classes that have small spatial extent compared to their large counterparts. (e.g. drop from to 66.74 to 53.74 or from 43.1 to 35.3 in case of small objects compared to dropping from 74.27 to 72.45 or from 80.58 to 80.55 in case of larger objects) I don't really know yet what could be the cause of this, but I thought this info might help also.

**Comment by lorinczszabolcs** [comment]
Retried the same experiment and now the problem seems to have disappeared, both settings achieve comparable performances. Closing due to these results.
