### ISSUE TITLE
KNet config bug

### ISSUE THREAD

**Issue by mtchiu2** [open-mmlab/mmsegmentation#1585]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**

In configs/knet/knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k.py, data is assigned twice, once to change the train/test time image size from 512x512 to 640x640, another to change samples_per_gpu to 2 ( which is already overridden in the _base_ config). This essentially discards the first operation and leaves the images size at 512x512:

```
data = dict(
    train=dict(pipeline=train_pipeline),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
#In K-Net implementation we use batch size 2 per GPU as default
data = dict(samples_per_gpu=2, workers_per_gpu=2)
```

**Bug fix**

Simply remove redundant `data = dict(samples_per_gpu=2, workers_per_gpu=2)` in subsequent config overrides, which appeared in all files below:

knet_s3_upernet_r50-d8_8x2_512x512_adamw_80k_ade20k.py
-> knet_s3_upernet_swin-t_8x2_512x512_adamw_80k_ade20k.py
--> knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k.py

**Comment by MengzhangLI** [comment]
The K-Net default samples per GPU is 2. Please checkout [here](https://github.com/ZwwWayne/K-Net/blob/main/configs/seg/_base_/datasets/ade20k.py#L36-L37), so you should not delete it if you want to re-implement similar results.

If you want to change image size, just change it rather than removing samples per gpu.

**Comment by mtchiu2** [comment]
That is not what I meant.

In ths latest commit, `mmsegmentation/configs/knet/knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k.py` uses `knet_s3_upernet_swin-t_8x2_512x512_adamw_80k_ade20k.py` as _base_, which already overrides `data = dict(samples_per_gpu=2, workers_per_gpu=2)`. But in `knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k.py` there are the following lines:

```
data = dict(
    train=dict(pipeline=train_pipeline),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
#In K-Net implementation we use batch size 2 per GPU as default
data = dict(samples_per_gpu=2, workers_per_gpu=2)
```

Since python assignment clears out previous values, `data` in 640x640.py only has `samples_per_gpu` and `workers_per_gpu`. Which means, when mmseg merges the cfgs, the training and testing pipeline is not overriden. So `knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k.py` still uses 512x512 as image size.

**Comment by MengzhangLI** [comment]
OK, thanks for your nice feedback.

I would check out later, if it is `512x512`, it means I would train and upload new model from new `knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k.py`.

Thanks!
