### ISSUE TITLE
Why does the resize operation is performed on cuda?

### ISSUE THREAD

**Issue by kzvdar42** [open-mmlab/mmsegmentation#1586]
Hi, first of all, thanks for all your hard work!

I was studying why does mmsegmentation code takes more GPU memory during validation, even if I set test crop 2-4 times smaller than during the training.

And I found out that in my case it's because of these lines:
https://github.com/open-mmlab/mmsegmentation/blob/44cfe04be91a04077ca7066d7857db381d3a1fa7/mmseg/models/segmentors/encoder_decoder.py#L204-L215

To mitigate this problem I made a quick durty fix from this:
https://github.com/open-mmlab/mmsegmentation/blob/44cfe04be91a04077ca7066d7857db381d3a1fa7/mmseg/apis/test.py#L91

To this:
```python
# also added `import cv2` in the imports
result = model(return_loss=False, rescale=False, **data)
result = [
    cv2.resize(r.astype(np.uint8), r_meta['ori_shape'][:2][::-1], interpolation=cv2.INTER_NEAREST)
    for r, r_meta in zip(result, data['img_metas'][0].data[0])
]
```

So, I wanted to ask why did you chose this behaviour? Looking at issues here with keywords _OOM during validation_, because of this, people struggle to use mmsegmentation, as it is counterintuitive that code uses more GPU memory during the inference time.

**Comment by MeowZheng** [comment]
`align_corners` is different in different algorithms, and from our experiments, the accuracy of models is affected by it,  but there is no align_corners in `cv2.resize`.

I suggest you might try 'slide inference' if 'whole inference` is not affordable for your device. Ref: https://github.com/open-mmlab/mmsegmentation/blob/44cfe04be91a04077ca7066d7857db381d3a1fa7/configs/beit/upernet_beit-large_fp16_8x1_640x640_160k_ade20k.py#L22

**Comment by MeowZheng** [comment]
Thanks for your feedback, we will add your suggestion to our backlog, or you might create a nice pr if you're interesting.
