### ISSUE TITLE
CustomDataset is not the dataset registry

### ISSUE THREAD

**Issue by chiba1sonny** [open-mmlab/mmsegmentation#1588]
Thanks for your great work.

**I have this error:  KeyError: 'MRSDataset is not in the dataset registry'**
My `dataset_type` is called `MRSDataset`.
1. I have made "`my_road_seg.py`" under *mmseg/datasets*. Here is my code.
![Screenshot from 2022-05-17 19-47-34](https://user-images.githubusercontent.com/68838083/168794550-ad7d6bb1-b509-46da-8f2c-1a650f37c37e.png)

2. And I add my `dataset_type` in `_init_.py` under *mmseg/datasets*. Here is my code.
![Screenshot from 2022-05-17 19-51-00](https://user-images.githubusercontent.com/68838083/168794903-ff943692-55a4-49e7-8371-6ce9b445e122.png)

**Comment by MengzhangLI** [comment]
Do not have blank line and try again

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/chase_db1.py#L7-L8

**Comment by chiba1sonny** [comment]
It still doesn't work.

**Comment by MengzhangLI** [comment]
> It still doesn't work.

Try to use 

```python
from .builder import DATASETS
from .custom import CustomDataset
```

And read the [doc](https://github.com/MengzhangLI/mmsegmentation/blob/add_doc_customization_dataset/docs/en/tutorials/customize_datasets.md#how-to-prepare-your-own-dataset). 

And based on your limited discription and reply, I could not give any further suggestion.

**Comment by chiba1sonny** [comment]
I'm sorry for the limited discription. 

Traceback (most recent call last):
  File "/home/marulab/mmsegmentation-master/tools/train.py", line 240, in <module>
    main()
  File "/home/marulab/mmsegmentation-master/tools/train.py", line 212, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/marulab/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmseg/datasets/builder.py", line 85, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/marulab/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'MRSDataset is not in the dataset registry'

**Comment by MengzhangLI** [comment]
I think it should be no `'MRSDataset is not in the dataset registry'` error if you have added `MRSDataset` in `__init__.py`.

**Comment by chiba1sonny** [comment]
> 

I followed and didn't work.

**Comment by chiba1sonny** [comment]
Alright, thank you, guys. 
Still cant fix this error.
I'm closing the issue.

**Comment by James-S-choi** [comment]
I think this error should not be happened if you edited the `__init__.py` file. If you use anaconda, maybe you should check the file under the corresponding env was indeed modified but not anywhere else~
