### ISSUE TITLE
Benchmarking timing does not make sense to me [Tested cityscape dataset]

### ISSUE THREAD

**Issue by timothylimyl** [open-mmlab/mmsegmentation#1594]
Easily tested commands to replicate

1. `python tools/benchmark.py configs/deeplabv3plus/deeplabv3plus_r50-d8_769x769_80k_cityscapes.py `

Results:
```
Done image [50 / 200], fps: 3.88 img / s
Done image [100/ 200], fps: 3.84 img / s
Done image [150/ 200], fps: 3.80 img / s
Done image [200/ 200], fps: 3.79 img / s
Overall fps: 3.79 img / s
```

2. ` python tools/benchmark.py configs/deeplabv3plus/deeplabv3plus_r50-d8_512x1024_80k_cityscapes.py `

Results:
```
Done image [50 / 200], fps: 9.29 img / s
Done image [100/ 200], fps: 9.28 img / s
Done image [150/ 200], fps: 9.28 img / s
Done image [200/ 200], fps: 9.28 img / s
Overall fps: 9.28 img / s
```

**Why is the timing so far apart? I believe it is just a difference of crop size during training right? Why would this have any effects on inference speed (testing)?**

Another example:

1. `python tools/benchmark.py configs/deeplabv3plus/deeplabv3plus_r18-d8_769x769_80k_cityscapes.py`
```
Done image [50 / 200], fps: 12.17 img / s
Done image [100/ 200], fps: 12.13 img / s
Done image [150/ 200], fps: 12.12 img / s
Done image [200/ 200], fps: 12.11 img / s
Overall fps: 12.11 img / s
```
2. ` python tools/benchmark.py configs/deeplabv3plus/deeplabv3plus_r18-d8_512x1024_80k_cityscapes.py `

```
Done image [50 / 200], fps: 29.15 img / s
Done image [100/ 200], fps: 29.31 img / s
Done image [150/ 200], fps: 29.19 img / s
Done image [200/ 200], fps: 29.20 img / s
Overall fps: 29.20 img / s
```

**Comment by MengzhangLI** [comment]
`Why is the timing so far apart? I believe it is just a difference of crop size during training right? Why would this have any effects on inference speed (testing)?`

No, you are wrong. If you read the code first you would find it makes sense because the config file is different.

deeplabv3plus_r50-d8_512x1024_80k_cityscapes.py :
```python
_base_ = [
    '../_base_/models/deeplabv3plus_r50-d8.py',
    '../_base_/datasets/cityscapes.py', '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_80k.py'
]
```

deeplabv3plus_r50-d8_769x769_80k_cityscapes.py
```python
_base_ = [
    '../_base_/models/deeplabv3plus_r50-d8.py',
    '../_base_/datasets/cityscapes_769x769.py', '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_80k.py'
]
model = dict(
    decode_head=dict(align_corners=True),
    auxiliary_head=dict(align_corners=True),
    test_cfg=dict(mode='slide', crop_size=(769, 769), stride=(513, 513)))
```

The `test_cfg` of them is different.

**Comment by timothylimyl** [comment]
Thank you for the clarification, my bad. I did read the code but never expected the changes of the data/dataset to be made in `model`. Why would this be the case?

My assumption was that the `crop_size` + cropping transform call would had been made in [cityscapes_769x769.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/cityscapes_769x769.py) under the `test_pipeline` cfg.

In regards, to the `test_cfg` and `train_cfg`, why does model need to reconfigure this?

**Comment by MeowZheng** [comment]
`slide` mode will split image as patches and predict the seg map for each patch and fuse them as the final result, `whole` will predict the full image which is not friendly for device memory

**Comment by MeowZheng** [comment]
@MengzhangLI Please add the instructions for `test_cfg` in FAQ documentation.
