### ISSUE TITLE
RuntimeError: CUDA error while training

### ISSUE THREAD

**Issue by ChengYuChuan** [open-mmlab/mmsegmentation#1600]
when I try to run this with dist_train.sh, I encountered a problem: RuntimeError: CUDA error: an illegal memory access was encountered
/mmsegmentation/tools/train.py

So, I google it for a bit.

Since I couldn't find the argument at the beginning of the train.py, I am wondering how to adjust the batch size in this case.

Could you please help me out there?

**Comment by MengzhangLI** [comment]
This bug sometimes happened by wrong `num_classes`, so do you use your customization dataset? If yes, you should set `num_classes = number of foreground classes + 1 (background)`.

**Comment by dpakprajul** [comment]
> 

This helped me!!!
