### ISSUE TITLE
What kind of situations will cause the mIoU metrics to NAN?

### ISSUE THREAD

**Issue by binging512** [open-mmlab/mmsegmentation#1601]
We add PAIP2019 dataset to mmsegmentation, the config file are modified from the ade20k dataset. However,  when we encounter the problems with the NAN value for mIoU metrics, shown in the following figure.
![图片](https://user-images.githubusercontent.com/36557512/169494861-ba6c1fb4-a4e2-4af4-8414-8abae97ca7bf.png)
This is the first evaluation during the training runtime. The second evaluation result is shown below:
![图片](https://user-images.githubusercontent.com/36557512/169499368-a9492366-5f80-47d4-b3ef-7a77c0a6677a.png)

We did the following things:
1. Arrange the training and validation images and annotations in the data folder with ade20k style. The images are RGB images with the shape of 640*640*3, the annotations are just labels with 3 categories. The value 0 stands for background, 1 for the whole tissue area and 2 for the viable area in PAIP2019. # We check the labels for several times to ensure they are in the same style as the ade20k labels.
2. We modified the ade20k dataset config in the ./configs/swin and ./configs/_base_ directory, the ade20k dataset file in ./mmseg/datasets directory to adapt to the PAIP2019 dataset.
![图片](https://user-images.githubusercontent.com/36557512/169496818-9bc70f65-493b-4ca1-bb40-f4e8879e8b89.png)
![图片](https://user-images.githubusercontent.com/36557512/169496939-f3b8d42b-8a75-475a-9cd3-f638bc61f19e.png)
![图片](https://user-images.githubusercontent.com/36557512/169497177-99de7fd3-0e68-4a8f-b899-897cf3879e2d.png)
3. Here we add a 'nothing' category to obseve the evaluation result if a label is not annotated in the labels.
4. We run the Swin Transformer with the configs above, but we get the NAN value for viable and nothing classes.
So how can we justify the evaluation metrics?

**Comment by MengzhangLI** [comment]
From your current snapshots I am not sure the reason. I suggest you could follow DRIVE dataset style and try again.

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/drive.py

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/drive.py

Looking forward to your reply.

**Comment by binging512** [comment]
Thanks very much. We found the problem. We select the wrong dataset config in the _base_ list.

**Comment by ke-dev** [comment]
I have the same problem, how did you solve it

**Comment by ke-dev** [comment]
@binging512 I have the same problem, how did you solve it

**Comment by binging512** [comment]
The ade20k dataset will reduce the zero label during training and testing. So when you are conducting binary classification tasks and set this as `True`, the zero label will be ignored.
![图片](https://user-images.githubusercontent.com/36557512/170431178-806e0aba-3a8a-45f0-ad69-40ec5c8f11f8.png)

**Comment by binging512** [comment]
> @binging512 I have the same problem, how did you solve it
The ade20k dataset will reduce the zero label during training and testing. So when you are conducting binary classification tasks and set this as `True`, the zero label will be ignored.
![图片](https://user-images.githubusercontent.com/36557512/170431178-806e0aba-3a8a-45f0-ad69-40ec5c8f11f8.png)

**Comment by binging512** [comment]
> > @binging512 I have the same problem, how did you solve it
> 
> Thanks for your reply, I set it according to your suggestion, but still get the result of nan, mine is not a binary classification ![5a821308dc94019571a50761b20a5e8](https://user-images.githubusercontent.com/59656387/170442425-cb401bcc-1c2c-433e-a5ce-4ff6f1ba5f15.png)
> 
> do you have any other better suggestion

I replied you in your issue. You'd better try to use `cv2` or `numpy` to check the pixel value in the annotation maps. The 0 IOU value may caused by the problem of the network, you can improve later, but these classes have annotations in the validation dataset. But the NAN indicates there is no pixel annotated as the classes in the validation dataset. So make sure there is no problems in your dataset.
If it is still not work, check the configs to make sure the dataset and the model are assoicated correctly. (That's the reason why NAN value appeared in my experiments.)

**Comment by ke-dev** [comment]
> > > @binging512 I have the same problem, how did you solve it
> > 
> > 
> > Thanks for your reply, I set it according to your suggestion, but still get the result of nan, mine is not a binary classification ![5a821308dc94019571a50761b20a5e8](https://user-images.githubusercontent.com/59656387/170442425-cb401bcc-1c2c-433e-a5ce-4ff6f1ba5f15.png)
> > do you have any other better suggestion
> 
> I replied you in your issue. You'd better try to use `cv2` or `numpy` to check the pixel value in the annotation maps. The 0 IOU value may caused by the problem of the network, you can improve later, but these classes have annotations in the validation dataset. But the NAN indicates there is no pixel annotated as the classes in the validation dataset. So make sure there is no problems in your dataset. If it is still not work, check the configs to make sure the dataset and the model are assoicated correctly. (That's the reason why NAN value appeared in my experiments.)

Sorry to bother you again, this is a difficult problem for me, I did some comparisons and used it, I think it is my data problem, the pixel value of each image is only about 0 to 5, but my label category has 28 indivual. Is my label image to be converted into a grayscale image, and one category corresponds to one pixel value, is this right?

**Comment by binging512** [comment]
> > > > @binging512 I have the same problem, how did you solve it
> > > 
> > > 
> > > Thanks for your reply, I set it according to your suggestion, but still get the result of nan, mine is not a binary classification ![5a821308dc94019571a50761b20a5e8](https://user-images.githubusercontent.com/59656387/170442425-cb401bcc-1c2c-433e-a5ce-4ff6f1ba5f15.png)
> > > do you have any other better suggestion
> > 
> > 
> > I replied you in your issue. You'd better try to use `cv2` or `numpy` to check the pixel value in the annotation maps. The 0 IOU value may caused by the problem of the network, you can improve later, but these classes have annotations in the validation dataset. But the NAN indicates there is no pixel annotated as the classes in the validation dataset. So make sure there is no problems in your dataset. If it is still not work, check the configs to make sure the dataset and the model are assoicated correctly. (That's the reason why NAN value appeared in my experiments.)
> 
> Sorry to bother you again, this is a difficult problem for me, I did some comparisons and used it, I think it is my data problem, the pixel value of each image is only about 0 to 5, but my label category has 28 indivual. Is my label image to be converted into a grayscale image, and one category corresponds to one pixel value, is this right?

Yes. You'd better generate a gray scale label map with the same size of your images. If your dataset have 28 classes, including the background, then you need to assign the label pixel value from 0 to 27. At last, save them as `.png` files. (Don't save them as `.jpg` files.)
