### ISSUE TITLE
How to add a classifier head?

### ISSUE THREAD

**Issue by erceguder** [open-mmlab/mmsegmentation#1605]
Hi all,

How can I add a classifier head on top of a mmsegmentation backbone? I've checked the [documents](https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_models.html#add-new-heads), yet it is stated that the new head should inherit from BaseDecodeHead, which is a segmentation head base class. I'm also aware of mmclassification but my ultimate goal is to do semantic segmentation and the classifier head I need is for pre-training purposes only.

Thanks in advance

**Comment by MengzhangLI** [comment]
You should use backbone into MMClassification. You can raise an issue in their repo about how to use their repo to pre-train and implement it in downstream segmentation task.

Ref:
https://github.com/open-mmlab/mmsegmentation/tree/master/configs/convnext

https://github.com/open-mmlab/mmclassification/tree/master/configs/convnext
