### ISSUE TITLE
Can we conduct self-training in MMSegmentation, such as Mask Region Modeling?

### ISSUE THREAD

**Issue by binging512** [open-mmlab/mmsegmentation#1608]
Can we conduct self-training in MMSegmentation, such as Mask Region Modeling? Thanks a lot.

**Comment by MengzhangLI** [comment]
MMSegmentation could use self-supervised learning model as backbone, which could be pre-trained in  [MMSelfSup](https://github.com/open-mmlab/mmselfsup) then used as backbone in downstream task. Like MAE:

https://github.com/open-mmlab/mmselfsup/tree/master/configs/selfsup/mae

https://github.com/open-mmlab/mmsegmentation/tree/master/configs/mae

If you want to know more about self-training, you could raise issue in MMSelfSup.

**Comment by binging512** [comment]
Can we copy-paste the configs in the MMSelfSup to the MMSegmentation? Or we can only conduct the self-training in MMSelfSup.

**Comment by MengzhangLI** [comment]
`Can we copy-paste the configs in the MMSelfSup to the MMSegmentation?`
No.

`Or we can only conduct the self-training in MMSelfSup.`
Yes.

**Comment by binging512** [comment]
OK, we got it. Thanks a lot.
