### ISSUE TITLE
No log file created when changing order of get_root_logger() and setup_multi_processes()

### ISSUE THREAD

**Issue by SBCV** [open-mmlab/mmsegmentation#1611]
**Describe the bug**
During training no `*.log` file is created, when changing the order of `get_root_logger(log_file=log_file, log_level=cfg.log_level)` and `setup_multi_processes(cfg)` in [mmsegmentation/tools/train.py](https://github.com/open-mmlab/mmsegmentation/blob/aa50358c71fe9c4cccdd2abe42433bdf702e757b/tools/train.py#L166-L169).

https://github.com/open-mmlab/mmsegmentation/blob/aa50358c71fe9c4cccdd2abe42433bdf702e757b/tools/train.py#L166-L169

The reason for this is that `setup_multi_processes(cfg)` calls internally `get_root_logger()` without the parameter `log_file` (and without `log_level`).

**Bug fix**
I understand that the current implementation in the master branch does not show this bug, because of the current order of the commands. But I feel that the current implementation is prone to errors.

If we change the implementation of `setup_multi_processes(...)` to
```
def setup_multi_processes(cfg, logger=None):
    """Setup multi-processing environment variables."""
    if logger is None:
        logger = get_root_logger()
    ...
```
we could change the code snippet in [mmsegmentation/tools/train.py](https://github.com/open-mmlab/mmsegmentation/blob/aa50358c71fe9c4cccdd2abe42433bdf702e757b/tools/train.py#L166-L169) (shown above) to
```
 logger = get_root_logger(log_file=log_file, log_level=cfg.log_level) 
  
 # set multi-process settings 
 setup_multi_processes(cfg, logger) 
```
and it becomes apparent that  `setup_multi_processes(cfg, logger)` depends on  `logger = get_root_logger(log_file=log_file, log_level=cfg.log_level) ` - and one can not simply change the order of the commands.

If wanted, I can submit a PR to fix this issue.

**Comment by MengzhangLI** [comment]
Thanks for your issue. PR of yours is welcome!

It is because `setup_multi_process()` was moved into current line for fixing repeat log [error](https://github.com/open-mmlab/mmsegmentation/pull/1267). We did not notice potential bug you mentioned in this issue.

Best,

**Comment by MeowZheng** [comment]
`get_root_logger` in mmseg calls `get_logger` in mmcv, and mmcv will return the same logger which has beed initialized in [mmsegmentation/tools/train.py](https://github.com/open-mmlab/mmsegmentation/blob/aa50358c71fe9c4cccdd2abe42433bdf702e757b/tools/train.py#L166-L169) with the parameter log_file. There is only one logger (initialized with `log_file`)during training.
ref:https://github.com/open-mmlab/mmcv/blob/21bada32560c7ed7b15b017dc763d862789e29a8/mmcv/utils/logging.py#L9-L16

I think it might be inaccurate for the reason that 'setup_multi_processes(cfg) calls internally get_root_logger() without the parameter log_file (and without log_level)'.

**Comment by SBCV** [comment]
> There is only one logger (initialized with log_file) during training

This explains why changing the order of the commands leads to a missing log file. (Since changing the order will create the logger without `log_file` first).

I think my PR in #1612 addresses this case accordingly - by delegating the logger object from `train.py` to `setup_multi_processes(cfg)`. If you think otherwise, let me know.

**Comment by MeowZheng** [comment]
I would like to know why changing the order of `get_root_logger` and `setup_multi_processes`?

I almost get the motivation of you PR that avoid someone changing the command order by explicitly adding an arg `logger ` in `setup_multi_processes`

**Comment by SBCV** [comment]
Ah, I see. I've integrated `mmsegmentation` into my own pipeline to compute segmentations of earth observation imagery. As starting point I used the script in `tools/train.py` and adapted it where necessary.
After a while, I realized that the `*.log` file was no longer created during training. Some debugging showed that it was caused by the order of those two commands.
However, the dependency (i.e. the required order of these commands) is currently not directly visible (i.e. `setup_multi_processes(cfg)` appears not to be dependent on the `logger`). Thus, I created this PR to improve the readability (i.e. show the actual code dependency) for future `mmsegmentation` users.

**Comment by MeowZheng** [comment]
I got it. we always initialized logger with log_file param at the very beginning of train script, as there are many times call `get_root_logger` without log_file param like `setup_multi_processes`.

I think you are right, and we should show the dependency that the logger must be initialized at the beginning of training, but #1612 only prevents the user from swapping these commands by accident. I would rather add some comments to inform users to initialize the logger as early as possible than add `logger` param in `setup_multi_processes`.

**Comment by SBCV** [comment]
I think there is already a comment regarding that - unfortunately, I didn't see it before :/

https://github.com/open-mmlab/mmsegmentation/blob/7628a61f920b6bd77f0dfe5e3074193ea3d13221/tools/train.py#L164-L170

**Comment by MeowZheng** [comment]
Thanks for you reporting the problem. We will record it in our FAQ document, but I think #1612 might not be very necessary.
I'll close this issue and #1612.

**Comment by xiexinch** [comment]
#1653
