### ISSUE TITLE
masked autoencoder customize dataset

### ISSUE THREAD

**Issue by dirtycomputer** [open-mmlab/mmsegmentation#1613]
when i want to run mae config on my own 2-classes dataset i got this:

mmsegmentation/mmseg/models/backbones/mae.py", line 246, in forward
    x = x + self.pos_embed
RuntimeError: The size of tensor a (65) must match the size of tensor b (1025) at non-singleton dimension 1
Exception in thread Thread-2:
Traceback (most recent call last):

**Comment by MengzhangLI** [comment]
Could your own dataset be trained normally on other models?

**Comment by dirtycomputer** [comment]
yes

**Comment by dirtycomputer** [comment]
I fix the bug cuz img size config

**Comment by MengzhangLI** [comment]
Cool. Happy to see you have fixed it. ;)

Try to follow DRIVE dataset setting:

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/drive.py

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/drive.py

**Comment by dirtycomputer** [comment]
But vessel Dice is almost zero 
when i train swin model on drive dataset the vessel dice is not zero

**Comment by MengzhangLI** [comment]
Check config file differences between drive and customized dataset.

**Comment by xiangtaowong** [comment]
How did u solve the problem?
After I check the config file differences, I find nothing wrong.
Looking forward to ur reply?

**Comment by xiangtaowong** [comment]
> I fix the bug cuz img size config


How did u solve the problem?
After I check the config file differences, I find nothing wrong.
Looking forward to ur reply?
