### ISSUE TITLE
Train my own data set, and NAN appears during validation

### ISSUE THREAD

**Issue by ke-dev** [open-mmlab/mmsegmentation#1615]
hi, I want to use supernet-swin-tiny to train the dataset，the order i run is
`python ./tools/train.py ./configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py`

Later I got the result as
![1653549825(1)](https://user-images.githubusercontent.com/59656387/170439130-5bc70c4c-9cdc-4365-9897-e3572b1f5363.png)

The configuration of the dataset is 
![1e1d9517d90b15613ffb45b2aa5f930](https://user-images.githubusercontent.com/59656387/170440184-af23d219-5224-4cb9-9684-5e23358f1541.png)
Here are some other settings
![c1e586c26b753297f3ec7c9cb21dfdd](https://user-images.githubusercontent.com/59656387/170439974-df3fac9e-cf18-44b0-aa78-75f806d524c8.png)

I tried setting `reduce_zero_label` to False, but the result is still nan
![e3cbb6d048ba84d33078de07ee7a774](https://user-images.githubusercontent.com/59656387/170440063-323864da-e28e-496c-a83c-3a54522abd4c.png)

Has anyone encountered a similar situation or have a better suggestion, I would be grateful。

**Comment by xiexinch** [comment]
Hi @ke-dev,
Did you modify the num_classes of the model?

**Comment by ke-dev** [comment]
> Hi @ke-dev, Did you modify the num_classes of the model? It should match the number of classes of your custom dataset.

yes, I modified the pixel value of the labeled image and num_classes, nan becomes 0, do you have a better suggestion.

**Comment by xiexinch** [comment]
> > Hi @ke-dev, Did you modify the num_classes of the model? It should match the number of classes of your custom dataset.
> 
> yes, I modified the pixel value of the labeled image and num_classes, nan becomes 0, do you have a better suggestion.

Can you provide the full config file and your training log?
And you might check whether the pretrain model is loaded successfully, or train more iterations.

**Comment by ke-dev** [comment]
> > > Hi @ke-dev, Did you modify the num_classes of the model? It should match the number of classes of your custom dataset.
> > 
> > 
> > yes, I modified the pixel value of the labeled image and num_classes, nan becomes 0, do you have a better suggestion.
> 
> Can you provide the full config file and your training log? And you might check whether the pretrain model is loaded successfully, or train more iterations.

Here is my config file and training log, It can be seen that the acc_seg is very high from the beginning.
[20220609_092510.log](https://github.com/open-mmlab/mmsegmentation/files/8875555/20220609_092510.log)

Here is my config file. 
[upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.txt](https://github.com/open-mmlab/mmsegmentation/files/8875578/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.txt)

I am sure the pretrain model is loaded successfully, and I train for full iterations, but the result becomes 0.
Here are more details about my dataset. #1632

**Comment by Rock-L21** [comment]
Hello, may I ask how to solve the problem that the above result is Nan?

**Comment by Saillxl** [comment]
@Rock-L21 do you have any soulution now？Thanks！
