### ISSUE TITLE
Hello! I met a problem.

### ISSUE THREAD

**Issue by 459737087** [open-mmlab/mmsegmentation#1619]
when I add self.fc = nn.Linear(2048, num_classes)
in mmseg/backbone/resnet.py  529 line.
It reported 

File "/usr/local/lib/python3.8/site-packages/mmseg/apis/train.py", line 191, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/usr/local/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 42, in train_step
    and self.reducer._rebuild_buckets()):

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

**Comment by MeowZheng** [comment]
Just add `find_unused_parameters=True` in your cfg

**Comment by 459737087** [comment]
Thank u! It resolved.

**Comment by AAAdecade** [comment]
> Thank u! It resolved. @MeowZheng
您好，我也遇到了相同的问题，请问应该在哪里加入：find_unused_parameters=True？求求您了 被困住好几天了

**Comment by AAAdecade** [comment]
> Just add `find_unused_parameters=True` in your cfg

您好，我也遇到了相同的问题，请问应该在哪里加入：find_unused_parameters=True？求求您了 被困住好几天了
