### ISSUE TITLE
mmcv min version

### ISSUE THREAD

**Issue by likyoo** [open-mmlab/mmsegmentation#1620]
Type object 'FileClient' has no attribute 'infer_client' before mmcv==1.3.16. [here](https://github.com/open-mmlab/mmcv/blob/v1.3.16/mmcv/fileio/file_client.py#L858) and [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L113)

Inconsistent with the requirements in mmseg [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/__init__.py#L9)

**Comment by MeowZheng** [comment]
There is prerequisites before installing mmseg, including a version tabel.
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/get_started.md#prerequisites

**Comment by likyoo** [comment]
okok, thx
