### ISSUE TITLE
'Dataset is not in the dataset registry'

### ISSUE THREAD

**Issue by liugd18** [open-mmlab/mmsegmentation#1622]
When using my custom dataset, i met this problem.
I have checked other issues and have followed the instructions given but no use.
I have created a ice.py under mmseg/datasets and also have completed the __init__.py as the following pictures shows
So what's the wrong with my steps?
![image](https://user-images.githubusercontent.com/70163367/170719193-8b9e218c-6768-4445-aee8-2a056037a83b.png)
![image](https://user-images.githubusercontent.com/70163367/170719320-ae4f5f55-fc03-45d3-9cf3-3420e3bee9e4.png)
![image](https://user-images.githubusercontent.com/70163367/170719400-f0bae500-4952-473d-bc06-ac8c9f77a95a.png)

**Comment by liugd18** [comment]
maybe the same as issue #1588 , but he failed to solve the problem in the end...

**Comment by liugd18** [comment]
maybe there is something wrong with import .xxx ?
i found this:
![image](https://user-images.githubusercontent.com/70163367/170818290-8d764415-a63c-48f2-8b2c-3609069298d7.png)

**Comment by MeowZheng** [comment]
might check your python working directory whether `yourpath/mmsegmentation`?

**Comment by liugd18** [comment]
> 

i use this:
(open-mmlab) liugd@gpu75:~/mmsegmentation-master$ python tools/train.py configs/fcn/Liugd_fcn.py --work-dir=liugd_work_dir/fcn

is there any step wrong?

![image](https://user-images.githubusercontent.com/70163367/170818972-456ff45f-fd71-463b-a22e-6ae95eac5644.png)

**Comment by RockeyCoss** [comment]
You could try running ```export PYTHONPATH="$(pwd)"```  before running python xxx

**Comment by liaoxianfu** [comment]
I also had the same problem。You can install it，running  `pip install -e .` at `mmsegmentation` dir, when you add  a new dataset.

**Comment by liugd18** [comment]
@liaoxianfu 
Thanks a lot!!!! your solution did help a lot !!!!

**Comment by twsha** [comment]
> I also had the same problem。You can install it，running `pip install -e .` at `mmsegmentation` dir, when you add a new dataset.

How to enter the mmsegmengtation package in the conda environment
![image](https://github.com/open-mmlab/mmsegmentation/assets/86956907/8d9ef27b-1769-4726-91df-be5c6a1d2a8b)
![image](https://github.com/open-mmlab/mmsegmentation/assets/86956907/657aa7a7-f827-4992-bb31-70bc5bbd02ae)
 Or run the pip install -e . command directly in the created virtual environment?
 I tried running this command directly in the virtual environment, but I still got this error。
![image](https://github.com/open-mmlab/mmsegmentation/assets/86956907/397eac35-746f-469d-aa24-25b81707bee9)
do you know how to solve it,thanks.

**Comment by Mikrokosmos0** [comment]
> You could try running `export PYTHONPATH="$(pwd)"` before running python xxx

Thanks a lot.It works.

**Comment by skycz666** [comment]
> I also had the same problem。You can install it，running `pip install -e .` at `mmsegmentation` dir, when you add a new dataset.

useful，thanks
