### ISSUE TITLE
How to get mIoU for every 50 iters?

### ISSUE THREAD

**Issue by aihcyllop** [open-mmlab/mmsegmentation#1626]
How to get mIoU for every 50 iters?
I want to know mIoU of every 50 iters to see the mIoU curves, how can I get this? Thanks!

**Comment by MeowZheng** [comment]
Please try to revise `interval=50` of evaluation cfg

https://github.com/open-mmlab/mmsegmentation/blob/ef905223b305e6448b09d4243c213a36290194e6/configs/_base_/schedules/schedule_20k.py#L9

**Comment by aihcyllop** [comment]
Yes, I have tried to revise the interval =50, but I didnt see the miou result for every 50 iters, 
it only show in the summary the final miou

or did I lost some steps?

Summary:

+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 59.44 | 17.35 | 56.38 |
+-------+-------+-------+

**Comment by aihcyllop** [comment]
I mean when I finished training, I will get the .json.
The contents are as follows:
Is that possible to let me know the iou every 50iters? Thanks! 

{"mode": "train", "epoch": 3, "iter": 50, "lr": 0.0, "memory": 9008, "data_time": 0.09655, "decode.loss_ce": 0.17214, "decode.acc_seg": 20.53491, "aux.loss_ce": 0.09334, "aux.acc_seg": 18.71436, "loss": 0.26548, "time": 0.52409, "decode.loss_ce_val": 0.22454, "decode.acc_seg_val": 19.79203, "aux.loss_ce_val": 0.09229, "aux.acc_seg_val": 15.09144, "loss_val": 0.31683}
{"mode": "train", "epoch": 5, "iter": 100, "lr": 0.0, "memory": 9008, "data_time": 0.09304, "decode.loss_ce": 0.14463, "decode.acc_seg": 18.42977, "aux.loss_ce": 0.0845, "aux.acc_seg": 18.11156, "loss": 0.22913, "time": 0.5224, "decode.loss_ce_val": 0.24127, "decode.acc_seg_val": 17.19514, "aux.loss_ce_val": 0.09711, "aux.acc_seg_val": 15.60686, "loss_val": 0.33838}
{"mode": "train", "epoch": 8, "iter": 150, "lr": 1e-05, "memory": 9008, "data_time": 0.13902, "decode.loss_ce": 0.15069, "decode.acc_seg": 21.12312, "aux.loss_ce": 0.08718, "aux.acc_seg": 18.58325, "loss": 0.23787, "time": 0.56875, "decode.loss_ce_val": 0.22417, "decode.acc_seg_val": 18.66678, "aux.loss_ce_val": 0.09199, "aux.acc_seg_val": 14.76115, "loss_val": 0.31616}

**Comment by MeowZheng** [comment]
Sorry you might not get the evaluation results after training, as model was evaluated during training
