### ISSUE TITLE
Configuration crop_size 

### ISSUE THREAD

**Issue by arslanduygu** [open-mmlab/mmsegmentation#1627]
Hi, 
I would like to ask whether there is a definite distinction between the crop size that is explicitly shown in the tables of Results and models sections of the mmsegmentation repo for different models (as in [here]( https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3#results-and-models)) and the crop size that is used in training pipeline as data augmentation. The question arises since the former is defined explicitly in the configuration as cfg.crop_size. I am confused whether the former is used as a form of data pre-processing or not. I would appreciate it if you could provide explanation on this. 

Thanks!

**Comment by linfangjian01** [comment]
In different datasets, images have different sizes. In the training phase, crop size means the image will be cropped to the "crop size" for training. In the testing phase, there are two types of tests: "slide" and "whole". The "slide" test requires a given crop size for the test, while the whole test is the original image size for the test. For more details, please refer to the specific code. The crop size reported in mmseg's readme is used to crop the image size, measure GFLOPs, Parms, Memory, etc.

**Comment by arslanduygu** [comment]
Thank you, but before coming to training, you define a crop_size `cfg.crop_size` which, to my understanding, need not be the same crop size in training here : 
```
cfg.train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='RandomCrop', crop_size=(512,1024) cat_max_ratio=0.75),
```

I am asking whether these two have different purposes? As I understand, the latter one (RandomCrop) is a random crop used as a form of data augmentation not for data preprocessing.

**Comment by linfangjian01** [comment]
cfg.crop_size generally refers to the crop_size in dict(type='RandomCrop', crop_size=(512,1024) cat_max_ratio=0.75). yep, it is a data augmentation.

**Comment by arslanduygu** [comment]
This clarifies, thanks!
