### ISSUE TITLE
why make numpy stirde positive here. is there any bug if numpy stride is negative.

### ISSUE THREAD

**Issue by haiasd** [open-mmlab/mmsegmentation#1628]
https://github.com/open-mmlab/mmsegmentation/blob/ef905223b305e6448b09d4243c213a36290194e6/mmseg/datasets/pipelines/transforms.py#L372

**Comment by MengzhangLI** [comment]
Some errors may happen like 
`ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.` if numpy stride is negative.

**Comment by haiasd** [comment]
Thank you for your reply.
