### ISSUE TITLE
Error occurred while registering custom dataset

### ISSUE THREAD

**Issue by Priyadrasta-2111CS10** [open-mmlab/mmsegmentation#1634]
While trying to register my custom dataset, I faced an issue **TypeError: __init__() got an unexpected keyword argument 'prob'** as shown below. I followed the tutorial to prepare the custom dataset mentioned here [https://github.com/MengzhangLI/mmsegmentation/blob/add_doc_customization_dataset/docs/en/tutorials/customize_datasets.md#how-to-prepare-your-own-dataset]. I am unable to figure out where does the error come from?How to fix the issue?

<img width="758" alt="image" src="https://user-images.githubusercontent.com/92008353/171467519-cb919f9d-a6f6-425a-84a1-ef28bc1e8108.png">

**Comment by MeowZheng** [comment]
Would you mind providing more details on how you implementing your own dataset and registering it?

**Comment by Priyadrasta-2111CS10** [comment]
create a new file **my_dataset.py** in **./mmseg/dataset**
<img width="574" alt="2022-06-06" src="https://user-images.githubusercontent.com/92008353/172068153-10688b8c-5705-42a6-bb85-af7fcb871fe8.png">
After creating **./mmseg/dataset/my_dataset.py**，I  added it in **./mmseg/dataset/__init__.py:**
<img width="561" alt="2022-06-06 (1)" src="https://user-images.githubusercontent.com/92008353/172068108-7efc7155-345e-4b2b-81dd-db7c2bff5338.png">
**my_dataset_config.py**  file also has been added in **./configs/_base_/datasets/**
<img width="579" alt="2022-06-06 (3)" src="https://user-images.githubusercontent.com/92008353/172068062-74ea7b00-224b-4298-8dd0-900c353b9a02.png">
After dataset preparation is finished, I imported **./configs/_base_/datasets/my_dataset_config.py** in **SETR** model config file as shown below.
<img width="578" alt="2022-06-06 (4)" src="https://user-images.githubusercontent.com/92008353/172068052-8f3ac071-3064-41cb-af71-510bdd367ca5.png">

**Comment by MeowZheng** [comment]
I found a little problem that the class num of your dataset is 3, but the num_classes of the model is 19?

Moreover, I suggest `train_pipeline=[]` and `test_pipeline=[]` and try below to check the dataset implemetation
```python
from mmcv.utils import Config
from mmseg.datasets import build_dataset
cfg = Config.fromfile('`your_dataset_cfg_file_path`')
dataset = build_dataset(cfg.data.train)
```

**Comment by Priyadrasta-2111CS10** [comment]
After the registration of the custom dataset, now I am facing this error "**AttributeError: 'ConfigDict' object has no attribute 'dist_params'**". How to fix this?

<img width="552" alt="image" src="https://user-images.githubusercontent.com/92008353/172376711-0f02446d-1ff8-47d2-9e9a-7ec850b32923.png">

**Comment by Priyadrasta-2111CS10** [comment]
The solution of yours fixed the issue for the time being. Thanks a lot
