### ISSUE TITLE
How to solve this problem in the training model -

### ISSUE THREAD

**Issue by fupogirl** [open-mmlab/mmsegmentation#1637]
**Describe the bug**
ImportError: cannot import name 'get_device' from 'mmseg.utils' (/root/miniconda3/lib/python3.8/site-packages/mmseg/utils/__init__.py)
<img width="594" alt="e110b74934e7dcc99970e839cf66a4e" src="https://user-images.githubusercontent.com/96288444/171636790-7d82f746-c6f0-430e-a3e8-733b10e568e2.png">
Please help me solve this problem!

**Comment by MengzhangLI** [comment]
You have both `/autodl-tmp/mmcv/mmsegmentation` and `/miniconda3/lib/python3.8/site-packages/mmseg/` two mmsegmentation repo/codebase. Please use `/autodl-tmp/mmcv/mmsegmentation` aka your current working path mmsegmentation.
