### ISSUE TITLE
BisenetV2

### ISSUE THREAD

**Issue by whhgws** [open-mmlab/mmsegmentation#1638]
Why is the test of bisentv2 only 70.5?
![2022-06-04 13-09-34 的屏幕截图](https://user-images.githubusercontent.com/106857950/171985426-005e4e94-033a-4ec2-a234-cac7cbacf044.png)

**Comment by MengzhangLI** [comment]
We have try to re-implement BiSeNetV2, and validation results have been aligned to some degree. If the test set is not as good as you expect, I suggest you ask author for more clarified explanation.

Discussion1: https://github.com/CoinCheung/BiSeNet/issues/173

Discussion 2: https://github.com/CoinCheung/BiSeNet/tree/master/old#diss-this-paper
