### ISSUE TITLE
Pretraining

### ISSUE THREAD

**Issue by lkyyef** [open-mmlab/mmsegmentation#1651]
When I train segformer, I don't want to use the pretraining model. How can I set it?

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py#L6-L7

```python
model = dict(
    pretrained=None, decode_head=dict(num_classes=150))
```

**Comment by lkyyef** [comment]
thanks
