### ISSUE TITLE
About labelled images

### ISSUE THREAD

**Issue by LansonChen** [open-mmlab/mmsegmentation#1652]
Do labelled images have to be single channel ?  If  I  only have regular RGB labelled images, should I convert them to single channel so as to run the program properly?

**Comment by xiexinch** [comment]
HI, @LansonChen 
The current dataset in MMSeg does not support RGB annotations. So converting them to single-channel is necessary.

**Comment by LansonChen** [comment]
OK, that's annoying. Do our lab provide any tools or util script to convert them directly? Thx a lot!

**Comment by xiexinch** [comment]
We have not yet implemented such a tool, but you may take a look at [this example](https://www.kaggle.com/code/hossamfakher/camvid-segmentation-unet), hope it can help you.

**Comment by LansonChen** [comment]
THX so much!  But I still have few questions to  bother.

> Is there any tutorial of  training own custom dataset, especially for **TIFF-format** remote sensing images. (I still don't know whether your program support TIFF-format images and annotations or not)

> I found  it hard for newbies like me to figure out  the whole config things in short time. 

> I've read your docs and tried to repeat those tutorials(almost all of them r quite easy to start, however when actual needs come ,such as train my own datasets, change the model,config the parms etc, I feel helpless), I wonder if your notebook could be more customize and  include more markdowns to tell us when,where and how to change configs that correlative.

**Comment by xiexinch** [comment]
Hi @LansonChen 
1. We use opencv as the backend for reading images by default, it supports reading tiff file. We also support other backend, such as tifffile, pillow, etc. You might need to modify the `LoadImageFromFile` at `train_pipeline` or `test_pipeline` in dataset config file.
```python
train_pipeline = [
    dict(type='LoadImageFromFile', imdecode_backend='tifffile'),
    ...
]
```
If it doesn't work, please create a new issue.

2. We provide a tutorial about the config file, https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/config.md
3. The current datasets in MMSeg are based on the `CustomDataset` class, you can use them as demos for custom datasets. We will also continue to update our documents for your convenience, if you have any ideas or suggestions, you may create issues or even pull requests to help us update documents and tutorials.

**Comment by LansonChen** [comment]
@xiexinch Thank u for your time, it helps  a lot!
