### ISSUE TITLE
onnx to tensorrt

### ISSUE THREAD

**Issue by ke-dev** [open-mmlab/mmsegmentation#1659]
Hi, developer, I followed this document to get `tmp.onnx`
[https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/useful_tools.md](url)

but when I switched from onnx to tensorrt, I got the following error message, what is the reason? this confuses me
`assert is_tensorrt_plugin_loaded(), 'TensorRT plugin should be compiled.' AssertionError: TensorRT plugin should be compiled`

my environment configuration is
`cuda 11.3，tensorrt:8.4.0.6`

the command I use is
`python tools/pytorch2onnx.py \
    ./work_dirs/topformer_tiny_448x448_160k_2x8_ade20k/topformer_tiny_448x448_160k_2x8_ade20k.py \
    --checkpoint ./work_dirs/topformer_tiny_448x448_160k_2x8_ade20k/latest.pth \
    --input-img ./imgs/ADE_train_00017328.jpg  \
    --shape 448 448\
    --show \
    --verify \
    --dynamic-export \
    --cfg-options \
      model.test_cfg.mode="whole"`

`python ./tools/onnx2tensorrt.py \
    ./work_dirs/topformer_tiny_448x448_160k_2x8_ade20k/topformer_tiny_448x448_160k_2x8_ade20k.py \
    ./tmp.onnx/ \
    --trt-file ./work_dirs/ \
    --min-shape 448 \
    --max-shape 448 \
    --input-img ./work_dirs/topformer_tiny_448x448_160k_2x8_ade20k/ADE_train_00017328.jpg  \
    --show \
    --verify`

Did this happen to you?
look forward to your reply.

**Comment by RunningLeon** [comment]
@ke-dev Hi, this means you have not built custom tensorrt plugin with mmcv-full.
1. If your model does not include custom ops for tensorrt, you could easily comment the line `assert is_tensorrt_plugin_loaded(), 'TensorRT plugin should be compiled.' ` in `./tools/onnx2tensorrt.py`.
2. You could install [mmcv-full ](https://github.com/open-mmlab/mmcv/blob/master/docs/en/deployment/tensorrt_plugin.md#build-on-linux)with custom ops for trt and ort 
```cd mmcv ## to MMCV root directory
MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 pip install -e .
```

**Comment by ke-dev** [comment]
> @ke-dev Hi, this means you have not built custom tensorrt plugin with mmcv-full.
> 
> 1. If your model does not include custom ops for tensorrt, you could easily comment the line `assert is_tensorrt_plugin_loaded(), 'TensorRT plugin should be compiled.' ` in `./tools/onnx2tensorrt.py`.
> 2. You could install [mmcv-full ](https://github.com/open-mmlab/mmcv/blob/master/docs/en/deployment/tensorrt_plugin.md#build-on-linux)with custom ops for trt and ort
> 
> ```
> MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 pip install -e .
> ```
> 
> 3. This tool would be deprecated later, welcome  to use [mmdeploy](https://github.com/open-mmlab/mmdeploy) for deployment if possible.

I'm glad to use mmdeploy, but it doesn't seem to support topformer yet, I did some attempts and got the following error
`RuntimeError: parse onnx failed:
In node 35 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
`

**Comment by RunningLeon** [comment]
@ke-dev Hi, sadly we do not have  `topformer` in mmdeploy. But you can check the onnx with [netron](https://netron.app/) and locate where is wrong. Maybe something wrong with the 35th node in onnx?

**Comment by ke-dev** [comment]
The script I use is
`python tools/pytorch2onnx.py \
    work_dirs/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py \
    --checkpoint work_dirs/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/latest.pth \
    --output-file tmp.onnx \
    --input-img demo/img/999438_0_B_0007_7680-3840-11776-7936.jpg \
    --shape 512 512 \
    --show`

`python tools/onnx2tensorrt.py \
    ./work_dirs/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py \
    tmp.onnx \
    --trt-file ./work_dirs \
    --min-shape 1 3 512 512 \
    --max-shape 1 3 512 512 \
    --input-img demo/img/999438_0_B_0007_7680-3840-11776-7936.jpg \
    --show`

**Comment by RunningLeon** [comment]
@ke-dev Hi, we do not support swin transformer backbone yet.
