### ISSUE TITLE
UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0

### ISSUE THREAD

**Issue by LansonChen** [open-mmlab/mmsegmentation#1661]
**Describe the bug**
UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0

**Reproduction**

1. What command or script did you run?

   ```
# Build the dataset
datasets = [build_dataset(cfg.data.train)]

# Build the segmentor
model = build_segmentor(cfg.model)

# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
                meta=dict())
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
YES. Not really.

3. What dataset did you use?
Own custom TIFF-format dataset-----Massachusetts Buildings Dataset

**Environment**
fatal: not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 970
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 9.1, V9.1.8
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.5
MMCV: 1.5.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1

**Error traceback**
UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pc/ProgramFilesStore/mmsegmentation-master/mmseg/datasets/custom.py", line 215, in __getitem__
    return self.prepare_train_img(idx)
  File "/home/pc/ProgramFilesStore/mmsegmentation-master/mmseg/datasets/custom.py", line 232, in prepare_train_img
    return self.pipeline(results)
  File "/home/pc/ProgramFilesStore/mmsegmentation-master/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/pc/ProgramFilesStore/mmsegmentation-master/mmseg/datasets/pipelines/loading.py", line 137, in __call__
    backend=self.imdecode_backend).squeeze().astype(np.uint8)
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/image/io.py", line 249, in imfrombytes
    img = Image.open(buff)
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/PIL/Image.py", line 3009, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f04ec6e49b0>

**Comment by LansonChen** [comment]
It happens after I convert labelled images from 3-channel  to 1-channel, by the way, the labelled images in this dataset r all tiff-format.

**Comment by MeowZheng** [comment]
There might be some wrong image files in your dataset.

**Comment by LansonChen** [comment]
YEP, I double checked the image files, it turns out 1-channel tiff-format label data is not friendly to **PIL.open() function**.So I have to change the format finally.

**Comment by erik856** [comment]
How did you tackle the problem? I am having the same issue while using a 5-channel tiff-format
