### ISSUE TITLE
AssertionError: EncoderDecoder: both backbone and segmentor set pretrained wreight

### ISSUE THREAD

**Issue by hakpr** [open-mmlab/mmsegmentation#1664]
When running the official colab tutorial, I encountered the following problems:
![2Z_B6BMABEE)C2NT@B{`8VY](https://user-images.githubusercontent.com/105533584/173289785-5e52f8bb-66de-4b2d-8176-d90d418fcf39.png)
![ZD1EED$_(~M$QV4W@UG72TL](https://user-images.githubusercontent.com/105533584/173289599-834f0efa-d472-4fd5-8a98-b22d2372f0cd.png)
I am also using the data set provided in the tutorial, and nothing else has been changed.

**Comment by LansonChen** [comment]
I've met this issue before. I don't know my method is right or not,but it works.
Try to reload config, and rerun the current cell.

**Comment by MengzhangLI** [comment]
@LansonChen @hakpr It seems like both backbone and segmentor are loaded pretrained models. Could you check out your config flie (it would also be recorded in log) to see whether it is caused by wrong config setting?

Best,

**Comment by hakpr** [comment]
Thank you. I have solved this network by modifying the number of image channels and pixel values
