### ISSUE TITLE
Did you train the weights of the backbone network on ImageNet first, and then train the entire network on different data sets? Can you provide weights trained on ImageNet?

### ISSUE THREAD

**Issue by lvlingqi** [open-mmlab/mmsegmentation#1674]

**Comment by MengzhangLI** [comment]
The pretrained weights could be found in MMCV: https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json and other files in the same folder.

Some other pretrained models are borrowed from original repo such as Swin Transformer, BEiT, SegFormer and so on, you could find related information from each README in `./configs/xxx`.
