### ISSUE TITLE
ResneSt 200 and 269

### ISSUE THREAD

**Issue by HaoIrving** [open-mmlab/mmsegmentation#168]
I want to use `ResneSt 200 and 269` as backbone, which places need I to change?

**Comment by JonathanAndradeSilva** [comment]
Try to build a py (resnest269_b32x8.py) file inside imagenet folder, for example: mmclassification/configs/imagenet/resnest269_b32x8.py

and add this into resnest269_b32x8.py:
_base_ = [
    '../_base_/models/resnest269.py', '../_base_/datasets/imagenet_bs32.py',
    '../_base_/schedules/imagenet_bs256.py', '../_base_/default_runtime.py'
]

**Comment by CagesThrottleUs** [comment]
Once you load your config file into the program as:
`cfg = Config.fromfile('ResNeSt config file)`

You just need to make the change as:
`cfg.model.backbone.depth = `

The available depths for ResNeSt are: 50,101,152 and 200.

**Comment by xvjiarui** [comment]
Hi @HaoIrving 
For ResNeSt 200/269, you also need to convert your own weights.
