### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by lkyyef** [open-mmlab/mmsegmentation#1682]
When training the model, I want to remove the part of data augmentation. How do I do it?

**Comment by MengzhangLI** [comment]
You can change corresponding part like: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/ade20k.py#L10-L15.

You should also read the docs, the part of config file is located at: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/config.md#an-example-of-pspnet.
