### ISSUE TITLE
how can I change the epoch within HRnet training config?

### ISSUE THREAD

**Issue by ChengYuChuan** [open-mmlab/mmsegmentation#1683]
I was training the NN base on this:
mmsegmentation/tree/master/configs/hrnet)/fcn_hr18_512x1024_160k_cityscapes.py

I would like to know how to change the epoch within its config file.

How can I do this?

Could you give a hint?

**Comment by xiexinch** [comment]
Hi @ChengYuChuan
You may modify the runner config or overwrite the runner config at fcn_hr18_512x1024_160k_cityscapes.py
https://github.com/open-mmlab/mmsegmentation/blob/f2ea01592061c121911ca05968bf7927a73a906b/configs/_base_/schedules/schedule_160k.py#L7
You may also read the docs about `runner`, `evaluation`, and `checkpoint_config ` 
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/config.md#an-example-of-pspnet

**Comment by ChengYuChuan** [comment]
hmm, but that is how many iterations we did, right?

how do we know how many epochs are there?

**Comment by xiexinch** [comment]
We set batch size at `samples_per_gpu`
https://github.com/open-mmlab/mmsegmentation/blob/f2ea01592061c121911ca05968bf7927a73a906b/configs/_base_/datasets/cityscapes.py#L35

**Comment by ChengYuChuan** [comment]
thank you!!

I got the point.

which means that we have 2*2 in one batch if the number of GPU is 2.

am i right?

**Comment by xiexinch** [comment]
Yes, you are right.
Besides, some config files in MMSegmentation contain a field like `4x4` or `8x1` means `nums gpu x batch size per gpu`, that can be used as a reference.

**Comment by ChengYuChuan** [comment]
thank you so much I got it.

I think I can close the issue.
