### ISSUE TITLE
Swin V2 for segmentation?

### ISSUE THREAD

**Issue by pengzhao-life** [open-mmlab/mmsegmentation#1686]
Hi, I am interested in using Swin V2 for semantic segmentation, but I only see the segmentation models and code for Swin V1. I wonder if any documents or sample code can instruct me how to use Swin V2 for semantic segmentation? Thanks!

**Comment by MengzhangLI** [comment]
Hi, we have noticed that upstream models of SwinV2 have been officially released. We plan to support it in semantic segmentation but due to lack of developing people, we do not have clear time schedule about it.
