### ISSUE TITLE
post processing segmentation map after loading for custom datasets

### ISSUE THREAD

**Issue by hssandriss** [open-mmlab/mmsegmentation#1689]
Hello, 
Thank you for the great work! 

I have a question regarding adding some post processing steps for segmentation maps after loading (during training and test). I would like to ignore some labels so add them to background class and shift all other labels by 2. 

Please point me to the right place where I should add this functionality.

Thanks,

**Comment by MeowZheng** [comment]
If you would like to revise the default label of the dataset, I think you can use label mapping when loading annotation.
