### ISSUE TITLE
how can i train Knet for my  instance segmentation task in mmdet or mmseg?

### ISSUE THREAD

**Issue by star379814385** [open-mmlab/mmsegmentation#1690]
hello!
i want to train Knet for my  instance segmentation task, but Knet is similarly not supported by  mmdet and supported by mmseg.
how can i train Knet for my instance segmentation task in mmdet or mmseg?

**Comment by MengzhangLI** [comment]
Instance Segmentation task is supported by MMDetection, and KNet PR is WIP: https://github.com/open-mmlab/mmdetection/pull/7635. Perhaps several weeks later it would be merged.

If you want to train your own instance segmentation task right now, you should use KNet official repo codebase.

**Comment by star379814385** [comment]
> 
thanks~

**Comment by star379814385** [comment]
@MengzhangLI thanks~
