### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by ke-dev** [open-mmlab/mmsegmentation#1693]
I'm going to write an inference script myself, but I don't know your code well, can you explain what operations the image needs to do before it is put into the onnx model for inference?

looking forward to your reply

**Comment by MengzhangLI** [comment]
You can read the doc: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/useful_tools.md#convert-to-onnx-experimental

And you can also raise an issue in MMDeploy if you meet new problems.
