### ISSUE TITLE
SegFormer License

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmsegmentation#1696]
Hello,

Original Segformer [repo ](https://github.com/NVlabs/SegFormer) is under an Nvidia license which doesn't permit commercial use.
However, It was then merged in MMsegmentation (apache licence), which does permits commercial use.
Which license prevails ? The later ?

**Comment by MeowZheng** [comment]
Many thanks for your kind reminder, we are consulting with our legal colleagues on this issue, and if there are any conclusions and progress, we will inform the community as soon as possible.

**Comment by MeowZheng** [comment]
We add the License info of SegFormer to emphasize that it is not commercially available.
https://github.com/open-mmlab/mmsegmentation/pull/1699
