### ISSUE TITLE
Training time issues with Segformer

### ISSUE THREAD

**Issue by FranzEricSchneider** [open-mmlab/mmsegmentation#1697]
Hello, I am trying to train a segmentation network on a small set of images. More data is coming, but right now I have 12 train images, 2 validation images, and 2 test images, all (2048 x 2448). I've tried training FCN, UNet, BiSeNet, and Segformer networks on these images, and I'm having timing issues with segformer.

**In general I'm not sure how to debug this, any suggestions on things I can try or look into would be welcome!**

For workers, the data is set with `data = dict(samples_per_gpu=8, workers_per_gpu=8)`.

Here are the timing stats with a single GeForce GTX 1080 Ti, `runner = dict(type='IterBasedRunner', max_iters=2000)`:

- FCN: says it will take 2:07 on the first 50/2000 and takes 2:10 (hours:minutes)
- UNet: says it will take 0:32 on the first 50/2000 and takes 0:29 
- BiSeNet: says it will take 2:15 on the first 50/2000 and takes 2:16
- Segformer: says it will take 3:12 on the first 50/2000 and takes 15:15

Here is a downsampled example of the output. As you can see, after the first validation check (every 500 iters) the 50-iter time goes from ~4 minutes to ~30 minutes:
```
06-21 02:07 - INFO - Iter [50/2000] lr: 5.736e-06, eta: 3:12:06, time: 5.911, data_time: 3.044, memory: 8963, decode.loss_ce: 1.0866, decode.acc_seg: 49.8389, loss: 1.0866
...
06-21 02:26 - INFO - Iter [300/2000]    lr: 3.052e-05, eta: 2:17:44, time: 4.661, data_time: 3.091, memory: 8963, decode.loss_ce: 0.3049, decode.acc_seg: 84.2509, loss: 0.3049
...
06-21 02:37 - INFO - Iter [450/2000]    lr: 4.178e-05, eta: 2:03:27, time: 4.615, data_time: 3.084, memory: 8963, decode.loss_ce: 0.2598, decode.acc_seg: 86.2928, loss: 0.2598
06-21 02:41 - INFO - Iter [500/2000]    lr: 4.494e-05, eta: 1:59:03, time: 4.608, data_time: 3.072, memory: 8963, decode.loss_ce: 0.2448, decode.acc_seg: 86.3396, loss: 0.2448

06-21 02:41 - INFO - Summary:
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 91.67 | 37.56 | 44.35 |
+-------+-------+-------+

06-21 03:11 - INFO - Iter [550/2000]    lr: 4.353e-05, eta: 3:03:16, time: 35.800, data_time: 3.106, memory: 8963, decode.loss_ce: 0.2321, decode.acc_seg: 86.8169, loss: 0.2321
...
06-21 05:38 - INFO - Iter [800/2000]    lr: 3.603e-05, eta: 5:24:28, time: 35.251, data_time: 3.069, memory: 8963, decode.loss_ce: 0.2065, decode.acc_seg: 87.9953, loss: 0.2065
...
06-21 07:06 - INFO - Iter [950/2000]    lr: 3.153e-05, eta: 5:36:25, time: 35.241, data_time: 3.072, memory: 8963, decode.loss_ce: 0.2036, decode.acc_seg: 88.6000, loss: 0.2036
06-21 07:35 - INFO - Iter [1000/2000]   lr: 3.003e-05, eta: 5:33:43, time: 35.208, data_time: 3.073, memory: 8963, decode.loss_ce: 0.1939, decode.acc_seg: 88.7738, loss: 0.1939

06-21 07:35 - INFO - Summary:
+------+-------+------+
| aAcc |  mIoU | mAcc |
+------+-------+------+
| 91.8 | 37.25 | 54.0 |
+------+-------+------+

06-21 08:05 - INFO - Iter [1050/2000]   lr: 2.853e-05, eta: 5:28:30, time: 35.224, data_time: 3.083, memory: 8963, decode.loss_ce: 0.1911, decode.acc_seg: 88.8853, loss: 0.1911
...
06-21 10:31 - INFO - Iter [1300/2000]   lr: 2.103e-05, eta: 4:34:31, time: 35.209, data_time: 3.081, memory: 8963, decode.loss_ce: 0.1858, decode.acc_seg: 89.1097, loss: 0.1858
...
06-21 11:59 - INFO - Iter [1450/2000]   lr: 1.653e-05, eta: 3:46:47, time: 35.234, data_time: 3.085, memory: 8963, decode.loss_ce: 0.1769, decode.acc_seg: 89.4635, loss: 0.1769
06-21 12:29 - INFO - Iter [1500/2000]   lr: 1.503e-05, eta: 3:29:05, time: 35.253, data_time: 3.069, memory: 8963, decode.loss_ce: 0.1833, decode.acc_seg: 89.3165, loss: 0.1833

06-21 12:29 - INFO - Summary:
+------+-------+-------+
| aAcc |  mIoU |  mAcc |
+------+-------+-------+
| 91.7 | 38.01 | 56.32 |
+------+-------+-------+

06-21 12:58 - INFO - Iter [1550/2000]   lr: 1.353e-05, eta: 3:10:38, time: 35.250, data_time: 3.084, memory: 8963, decode.loss_ce: 0.1795, decode.acc_seg: 89.2538, loss: 0.1795
...
06-21 15:25 - INFO - Iter [1800/2000]   lr: 6.030e-06, eta: 1:29:15, time: 35.073, data_time: 3.078, memory: 8963, decode.loss_ce: 0.1755, decode.acc_seg: 89.3308, loss: 0.1755
...
06-21 16:53 - INFO - Iter [1950/2000]   lr: 1.530e-06, eta: 0:22:50, time: 35.203, data_time: 3.069, memory: 8963, decode.loss_ce: 0.1741, decode.acc_seg: 89.5250, loss: 0.1741
06-21 17:22 - INFO - Iter [2000/2000]   lr: 3.000e-08, eta: 0:00:00, time: 35.244, data_time: 3.064, memory: 8963, decode.loss_ce: 0.1695, decode.acc_seg: 89.4999, loss: 0.1695
```

**Comment by MeowZheng** [comment]
I think the resolution of the test image  (2048 x 2448) is too large, which will increase the computation.

For Segformer, we always use `slide_inference` for large images, ref:
https://github.com/open-mmlab/mmsegmentation/blob/9cf2d23aa0fcb1dcf71c48fdc5943f002765e618/configs/segformer/segformer_mit-b0_8x1_1024x1024_160k_cityscapes.py#L10

**Comment by FranzEricSchneider** [comment]
That makes sense, I can make sure that is in the model config. However, I don't think that's the main issue. The main issue is that right after the first validation check the 50-iteration time goes from ~4 minutes to ~30 minutes. Something seems to change after the first validation run. Is it possible something changes about the GPU during validation? Maybe too much space is claimed or something?

Here is a run where I used `slide_inference` for the test config, and you can see the 50-iteration time jump up (the "time" field). I set validation to happen every 50 iterations to force this effect sooner. It appears that the validation step only takes a few seconds, which makes sense because there are only 3 images.

```
2022-06-23 20:51:07,617 - mmseg - INFO - Iter [50/1000]	lr: 5.592e-06, eta: 1:10:34, time: 4.457, data_time: 1.540, memory: 8963, decode.loss_ce: 1.1311, decode.acc_seg: 42.9070, loss: 1.1311
2022-06-23 20:51:14,668 - mmseg - INFO - Summary:
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 75.24 | 15.24 | 19.32 |
+-------+-------+-------+
2022-06-23 20:51:14,668 - mmseg - INFO - Iter(val) [3]	aAcc: 0.7524, mIoU: 0.1524, mAcc: 0.1932, ...
2022-06-23 21:19:49,005 - mmseg - INFO - Iter [100/1000]	lr: 1.070e-05, eta: 4:51:38, time: 34.428, data_time: 1.718, memory: 8963, decode.loss_ce: 0.7813, decode.acc_seg: 78.6825, loss: 0.7813
```

One hacky way I could fix this if no other fix appears would be to essentially disable validation runs, or maybe only validate in the last 5% of the iterations for something. Does that seem like a problem? It's losing the validation information but training would be sped up by 5-6 times.

**Comment by MeowZheng** [comment]
It's a little weird that time increased from ~4 minutes to ~30 minutes in different validation loops. I'll test it in the next few days.

**Comment by FranzEricSchneider** [comment]
Hi, after changing the `Resize` and `RandomCrop` data augmentations in the dataset config and making the train images smaller, this problem went away and the 50-iter timing is consistently ~5 minutes. I haven't carefully tested this, but my best guess is that during training the GPU was operating near max load, and the added GPU load during validation took the GPU past full. Maybe at that point it automatically switched to CPU mode or something?

On other models I've been running (UNet for sure, fairly certain I've seen this on BiSeNet as well) when the GPU is running too close to max during training then when validation comes around the run will crash with a GPU error about trying to claim space when there is none available. Maybe it's possible that Segformer experiences different behavior and continues in CPU-mode instead of crashing? This is just speculation, since things are up and running I probably won't dig into that unless it comes up again.
