### ISSUE TITLE
Other measurements besides mIoU

### ISSUE THREAD

**Issue by edizhuang** [open-mmlab/mmsegmentation#1698]
Hi,

Besides mIoU, what other measurements (options) could be used and how to?

And for accuracy, it shows per class accuracy, and simply averaged over all classes (two for my dataset). How to get overall pixel accuracy on testing data (correct predicted pixel number over all pixel number)?

Thanks,

**Comment by MengzhangLI** [comment]
- Use `--eval`, like `--eval mDice`. https://github.com/open-mmlab/mmsegmentation/tree/master/mmseg/core/evaluation
- You can get `results` [here](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L273-L282) and calculate overall pixel acc on your own.
