### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'VOCdevkit/VOCaug/dataset/trainval.txt'

### ISSUE THREAD

**Issue by blackmagicianZ** [open-mmlab/mmsegmentation#17]
https://github.com/open-mmlab/mmsegmentation/blob/1c3f54765981ba352d4cf6582edb1c8915e51d71/tools/convert_datasets/voc_aug.py#L53

Directory `VOCdevkit/VOCaug/dataset` does not exist `trainval.txt`, `trainval.txt` is the merger of `train.txt` and `val.txt`?

**Comment by xvjiarui** [comment]
Hi @blackmagicianZ 
Thanks for letting us know. You may try if #19 works.
