### ISSUE TITLE
dataset cat    val question

### ISSUE THREAD

**Issue by JNU-IFM** [open-mmlab/mmsegmentation#1701]
test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='word-trajectory/composite/composite02',
        ann_dir=['word-crop-mask/val/mask_mmseg',
                 'word-crop-mask/val/mask_mmseg']
        split=['word-trajectory/val_mmseg.txt','word-trajectory/val_mmseg.txt']
        pipeline=test_pipeline))

result is:
{"mode": "val", "epoch": 38, "iter": 1953, "lr": 0.0, "0_aAcc": 0.9963, "0_mIoU": 0.9766, "0_mAcc": 0.9869, "0_IoU.BACKGROUND": 0.996, "0_IoU.FOREGROUND": 0.9572, "0_Acc.BACKGROUND": 0.9982, "0_Acc.FOREGROUND": 0.9757, "1_aAcc": 0.9964, "1_mIoU": 0.9768, "1_mAcc": 0.9867, "1_IoU.BACKGROUND": 0.996, "1_IoU.FOREGROUND": 0.9577, "1_Acc.BACKGROUND": 0.9983, "1_Acc.FOREGROUND": 0.9752, "2_aAcc": 0.9961, "2_mIoU": 0.9755, "2_mAcc": 0.9855, "2_IoU.BACKGROUND": 0.9958, "2_IoU.FOREGROUND": 0.9553, "2_Acc.BACKGROUND": 0.9983, "2_Acc.FOREGROUND": 0.9728, "3_aAcc": 0.9962, "3_mIoU": 0.9757, "3_mAcc": 0.9855, "3_IoU.BACKGROUND": 0.9958, "3_IoU.FOREGROUND": 0.9555, "3_Acc.BACKGROUND": 0.9983, "3_Acc.FOREGROUND": 0.9727, "4_aAcc": 0.9963, "4_mIoU": 0.9765, "4_mAcc": 0.9867, "4_IoU.BACKGROUND": 0.996, "4_IoU.FOREGROUND": 0.9571, "4_Acc.BACKGROUND": 0.9983, "4_Acc.FOREGROUND": 0.9751, "5_aAcc": 0.9961, "5_mIoU": 0.9751, "5_mAcc": 0.9851, "5_IoU.BACKGROUND": 0.9957, "5_IoU.FOREGROUND": 0.9545, "5_Acc.BACKGROUND": 0.9983, "5_Acc.FOREGROUND": 0.9718, "6_aAcc": 0.9963, "6_mIoU": 0.9765, "6_mAcc": 0.9861, "6_IoU.BACKGROUND": 0.996, "6_IoU.FOREGROUND": 0.9571, "6_Acc.BACKGROUND": 0.9984, "6_Acc.FOREGROUND": 0.9738, "7_aAcc": 0.9963, "7_mIoU": 0.9763, "7_mAcc": 0.9862, "7_IoU.BACKGROUND": 0.9959, "7_IoU.FOREGROUND": 0.9567, "7_Acc.BACKGROUND": 0.9983, "7_Acc.FOREGROUND": 0.974, "8_aAcc": 0.9962, "8_mIoU": 0.9761, "8_mAcc": 0.9862, "8_IoU.BACKGROUND": 0.9959, "8_IoU.FOREGROUND": 0.9562, "8_Acc.BACKGROUND": 0.9983, "8_Acc.FOREGROUND": 0.9741, "9_aAcc": 0.9962, "9_mIoU": 0.9756, "9_mAcc": 0.9857, "9_IoU.BACKGROUND": 0.9958, "9_IoU.FOREGROUND": 0.9554, "9_Acc.BACKGROUND": 0.9983, "9_Acc.FOREGROUND": 0.9732, "10_aAcc": 0.9963, "10_mIoU": 0.9767, "10_mAcc": 0.9865, "10_IoU.BACKGROUND": 0.996, "10_IoU.FOREGROUND": 0.9574, "10_Acc.BACKGROUND": 0.9983, "10_Acc.FOREGROUND": 0.9747, "11_aAcc": 0.9963, "11_mIoU": 0.9762, "11_mAcc": 0.9861, "11_IoU.BACKGROUND": 0.9959, "11_IoU.FOREGROUND": 0.9566, "11_Acc.BACKGROUND": 0.9983, "11_Acc.FOREGROUND": 0.9739, "12_aAcc": 0.9963, "12_mIoU": 0.9766, "12_mAcc": 0.9868, "12_IoU.BACKGROUND": 0.996, "12_IoU.FOREGROUND": 0.9572, "12_Acc.BACKGROUND": 0.9983, "12_Acc.FOREGROUND": 0.9753, "13_aAcc": 0.9963, "13_mIoU": 0.9765, "13_mAcc": 0.9869, "13_IoU.BACKGROUND": 0.996, "13_IoU.FOREGROUND": 0.9571, "13_Acc.BACKGROUND": 0.9982, "13_Acc.FOREGROUND": 0.9755, "14_aAcc": 0.9962, "14_mIoU": 0.9762, "14_mAcc": 0.9863, "14_IoU.BACKGROUND": 0.9959, "14_IoU.FOREGROUND": 0.9564, "14_Acc.BACKGROUND": 0.9983, "14_Acc.FOREGROUND": 0.9743, "15_aAcc": 0.9962, "15_mIoU": 0.9762, "15_mAcc": 0.986, "15_IoU.BACKGROUND": 0.9959, "15_IoU.FOREGROUND": 0.9564, "15_Acc.BACKGROUND": 0.9983, "15_Acc.FOREGROUND": 0.9737, "16_aAcc": 0.9962, "16_mIoU": 0.9761, "16_mAcc": 0.9864, "16_IoU.BACKGROUND": 0.9959, "16_IoU.FOREGROUND": 0.9564, "16_Acc.BACKGROUND": 0.9982, "16_Acc.FOREGROUND": 0.9745, "17_aAcc": 0.9962, "17_mIoU": 0.9756, "17_mAcc": 0.9856, "17_IoU.BACKGROUND": 0.9958, "17_IoU.FOREGROUND": 0.9555, "17_Acc.BACKGROUND": 0.9983, "17_Acc.FOREGROUND": 0.9729, "18_aAcc": 0.9964, "18_mIoU": 0.977, "18_mAcc": 0.9871, "18_IoU.BACKGROUND": 0.996, "18_IoU.FOREGROUND": 0.9579, "18_Acc.BACKGROUND": 0.9983, "18_Acc.FOREGROUND": 0.9759, "19_aAcc": 0.996, "19_mIoU": 0.9749, "19_mAcc": 0.9848, "19_IoU.BACKGROUND": 0.9957, "19_IoU.FOREGROUND": 0.954, "19_Acc.BACKGROUND": 0.9983, "19_Acc.FOREGROUND": 0.9714, "20_aAcc": 0.9895, "20_mIoU": 0.9338, "20_mAcc": 0.9514, "20_IoU.BACKGROUND": 0.9886, "20_IoU.FOREGROUND": 0.8791, "20_Acc.BACKGROUND": 0.9972, "20_Acc.FOREGROUND": 0.9056}

Is it possible to output a total miou instead of a dataset individually?

**Comment by MengzhangLI** [comment]
Could you check your `.log` file like below red boxes?

![image](https://user-images.githubusercontent.com/24582831/175321190-931e7049-935c-4b5a-8d53-b23a8ddd6a8b.png)
