### ISSUE TITLE
How are the metrics computed?

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmsegmentation#1709]
I would like to understand how metrics are computed in MMSegmentation.v In particular, I would like to understand the logic behind  these two functions:

https://github.com/open-mmlab/mmsegmentation/blob/144dc3919e53d51921837e5a2a6d5ee656dccd7d/mmseg/core/evaluation/metrics.py#L26

https://github.com/open-mmlab/mmsegmentation/blob/144dc3919e53d51921837e5a2a6d5ee656dccd7d/mmseg/core/evaluation/metrics.py#L89

Is there a reference that can help me understand how these two functions work? For starters, I would like to understand what this part of code does:

```
    mask = (label != ignore_index)
    pred_label = pred_label[mask]
    label = label[mask]

    intersect = pred_label[pred_label == label]
    area_intersect = torch.histc(
        intersect.float(), bins=(num_classes), min=0, max=num_classes - 1)
    area_pred_label = torch.histc(
        pred_label.float(), bins=(num_classes), min=0, max=num_classes - 1)
    area_label = torch.histc(
        label.float(), bins=(num_classes), min=0, max=num_classes - 1)
    area_union = area_pred_label + area_label - area_intersect
    return area_intersect, area_union, area_pred_label, area_label
```

I think `pred_label ` is  a `ndarray` of shape (W, H, num_classes), containing the  segmentation map predicted by the model for each class, and similarly `label` is an array of shape (W, H, num_classes) containing Ground truth segmentation map. But I'm not sure about the rest.

**Comment by xiexinch** [comment]
Hi @AndreaPi
Sorry for the late reply. 
Here is a similar issue #1391. And I'll find other references for you.
