### ISSUE TITLE
(unet_fcn)when validation ,it will remind me The input image size (341, 512) should be divisible by the whole downsample rate 16

### ISSUE THREAD

**Issue by nicekwow** [open-mmlab/mmsegmentation#1712]
**Checklist**

1. I have searched related issues but cannot get the expected help.

**Describe the bug**

when training,its ok,but in validation it will remind me The input image size,and i changed the image_scale and crop size
**Reproduction**

1. What command or script did you run?

 python tools/train.py configs/unet/fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes.py

   ```none
   A placeholder for the command.
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

i changed the dataset,i made the crop size and image_scale to be (512*512) in train and test
3. What dataset did you use?
i used my own dataset,the num_classes=2,

**Environment**

sys.platform: win32
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3080
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc.exe
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30145 版
GCC: n/a
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,c
ode=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -o
penmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF
_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,  

TorchVision: 0.12.0
OpenCV: 4.5.5
MMCV: 1.5.3
MMCV Compiler: MSVC 192930140
MMCV CUDA Compiler: 11.3
MMSegmentation: 0.25.0+

**Error traceback**

2022-06-26 18:20:16,275 - mmseg - INFO - Checkpoints will be saved to E:\rbj\mmsegmentation\work_dirs\fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes by HardDiskBackend.
[                                                  ] 0/108, elapsed: 0s, ETA:Traceback (most recent call last):
  File "E:\rbj\mmsegmentation\tools\train.py", line 242, in <module>
    main()
  File "E:\rbj\mmsegmentation\tools\train.py", line 231, in main
    train_segmentor(
  File "e:\rbj\mmsegmentation\mmseg\apis\train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "D:\anaconda\lib\site-packages\mmcv\runner\iter_based_runner.py", line 138, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\anaconda\lib\site-packages\mmcv\runner\iter_based_runner.py", line 68, in train
    self.call_hook('after_train_iter')
  File "D:\anaconda\lib\site-packages\mmcv\runner\base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "D:\anaconda\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 262, in after_train_iter
    self._do_evaluate(runner)
  File "e:\rbj\mmsegmentation\mmseg\core\evaluation\eval_hooks.py", line 49, in _do_evaluate
    results = single_gpu_test(
  File "e:\rbj\mmsegmentation\mmseg\apis\test.py", line 91, in single_gpu_test
    result = model(return_loss=False, **data)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda\lib\site-packages\mmcv\parallel\data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "D:\anaconda\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda\lib\site-packages\mmcv\runner\fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "e:\rbj\mmsegmentation\mmseg\models\segmentors\base.py", line 110, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "e:\rbj\mmsegmentation\mmseg\models\segmentors\base.py", line 92, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "e:\rbj\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 256, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "e:\rbj\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 241, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
    seg_logit = self.encode_decode(img, img_meta)
  File "e:\rbj\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 73, in encode_decode
    x = self.extract_feat(img)
  File "e:\rbj\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 65, in extract_feat
    x = self.backbone(img)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\rbj\mmsegmentation\mmseg\models\backbones\unet.py", line 405, in forward
    self._check_input_divisible(x)
  File "e:\rbj\mmsegmentation\mmseg\models\backbones\unet.py", line 433, in _check_input_divisible
    assert (h % whole_downsample_rate == 0) \
AssertionError: The input image size (341, 512) should be divisible by the whole downsample rate 16, when num_stages is 5, strides is (1, 1, 1, 1, 1), and downsamples is (True, True, True, True).

```none
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
    dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
```

**Comment by xiexinch** [comment]
Hi @nicekwow
Sorry for the late reply.
I can't reproduce the error on other datasets. Could you provide the whole config file? It's weird that the resize operation doesn't  seems work.

**Comment by nicekwow** [comment]
> Hi @nicekwow Sorry for the late reply. I can't reproduce the error on other datasets. Could you provide the whole config file? It's weird that the resize operation doesn't seems work.
Hello,this my whole config file.
`norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='UNet',
        in_channels=3,
        base_channels=64,
        num_stages=5,
        strides=(1, 1, 1, 1, 1),
        enc_num_convs=(2, 2, 2, 2, 2),
        dec_num_convs=(2, 2, 2, 2),
        downsamples=(True, True, True, True),
        enc_dilations=(1, 1, 1, 1, 1),
        dec_dilations=(1, 1, 1, 1),
        with_cp=True,
        conv_cfg=None,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        act_cfg=dict(type='ReLU'),
        upsample_cfg=dict(type='InterpConv'),
        norm_eval=False),
    decode_head=dict(
        type='FCNHead',
        in_channels=64,
        in_index=4,
        channels=64,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole', crop_size=256, stride=170))
dataset_type = 'MydataDataset'
data_root = 'E:/rbj/stone/my_dataset'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
    dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='MydataDataset',
        data_root='E:/rbj/stone/my_dataset',
        img_dir='img/train',
        ann_dir='ann/train',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', reduce_zero_label=False),
            dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=255),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='MydataDataset',
        data_root='E:/rbj/stone/my_dataset',
        img_dir='img/val',
        ann_dir='ann/val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='MydataDataset',
        data_root='E:/rbj/stone/my_dataset',
        img_dir='img/val',
        ann_dir='ann/val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
        dict(type='TensorboardLoggerHook')
    ])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(type='AdamW', lr=1e-05, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(policy='poly', power=0.9, min_lr=0, by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=160000)
checkpoint_config = dict(by_epoch=False, interval=16000)
evaluation = dict(interval=1, metric='mIoU', pre_eval=True)
work_dir = './work_dirs\fcn_unet_s51-d16_4x4_512x1024_160k_cityscapes'
gpu_ids = [0]
auto_resume = False`

**Comment by xiexinch** [comment]
Hi @nicekwow
I test your config with some fate images, the error occurs when the image size is smaller than the image scale and setting `keep_ratio=True` in test_pipeline.
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/datasets/pipelines/transforms.py#L249

You might set `keep_ratio=False` or add `ResizeToMultiple` augmentation after `Resize`.
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/datasets/pipelines/transforms.py#L13

For example:
```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='ResizeToMultiple', size_divisor=16),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

**Comment by nicekwow** [comment]
> Hi @nicekwow I test your config with some fate images, the error occurs when the image size is smaller than the image scale and setting `keep_ratio=True` in test_pipeline.
> 
> https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/datasets/pipelines/transforms.py#L249
> 
> You might set `keep_ratio=False` or add `ResizeToMultiple` augmentation after `Resize`.
> 
> https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/datasets/pipelines/transforms.py#L13
> 
> For example:
> 
> ```python
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(512, 512),
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='ResizeToMultiple', size_divisor=16),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> ```

Thank you very much!I get it.
