### ISSUE TITLE
Model ensembling

### ISSUE THREAD

**Issue by emily-lin** [open-mmlab/mmsegmentation#1716]
Hello, 

I would like to implement ensembling (averaging) of segmentation models that are simply initialized from different random seeds. Ensembling is a commonly used strategy to help achieve strong performance on ML benchmarks. 

I checked prior threads, and it seems that ensembling is not currently supported in mmsegmentation (https://github.com/open-mmlab/mmsegmentation/issues/217). I was wondering if this would be possible to add. If not, do you have any suggestions for how best to implement this in mmsegmentation?

**Comment by MengzhangLI** [comment]
Hi, we have no plan to support model ensembling. You could change `forward_test` mentioned in https://github.com/open-mmlab/mmsegmentation/issues/217 if you want to realize it.
