### ISSUE TITLE
How to save result images in `multi_gpu_test()`?

### ISSUE THREAD

**Issue by Irvingao** [open-mmlab/mmsegmentation#1728]
# How to save result images in `multi_gpu_test()`?

**Motivation**
- My local GPU device is one RTX3060. And I wanted to **save result images** by running `test.py`.
- **Question**: 
  - When I was tring to use `python tools/test.py` for launching single GPU test, I met the problem as below. So how to slove it out?
![image](https://user-images.githubusercontent.com/58903762/176640657-e44fde01-9fb0-44c4-9d18-9e980ecbfbe4.png)

- it was successfully to run testing by `tools/dist_test.sh` with `multi_gpu_test()`. Therefore, `multi_gpu_test()` can't save result images. 
The relative code are list here:
```
    if not distributed:
        model = MMDataParallel(model, device_ids=[0])
        results = single_gpu_test(
            model,
            data_loader,
            args.show,
            args.show_dir,
            False,
            args.opacity,
            pre_eval=args.eval is not None and not eval_on_format_results,
            format_only=args.format_only or eval_on_format_results,
            format_args=eval_kwargs)
    else:
        model = MMDistributedDataParallel(
            model.cuda(),
            device_ids=[torch.cuda.current_device()],
            broadcast_buffers=False)
        results = multi_gpu_test(
            model,
            data_loader,
            args.tmpdir,
            args.gpu_collect,
            False,
            pre_eval=args.eval is not None and not eval_on_format_results,
            format_only=args.format_only or eval_on_format_results,
            format_args=eval_kwargs)```

**Comment by MeowZheng** [comment]
Try to use the latest mmseg and I think the platform with sight GPU will not initialize distributed training
