### ISSUE TITLE
Any potential issue while using RTX 30XX series ? 

### ISSUE THREAD

**Issue by StringBottle** [open-mmlab/mmsegmentation#173]
Before purchasing RTX 30XX series, I would like to check if any potential issue can occur while using RTX 30XX series. 

As far as I looked through Pytorch community, I think CUDA version compatibility could cause an error. 

I think A CUDA version issue can be resolved with further updates but I wanted to ask maintainers' opinion on this. 

Thank you.

**Comment by StringBottle** [comment]
It seems that RTX 30XX series only support CUDA 11.X series. 

https://github.com/pytorch/pytorch/issues/45028

**Comment by hellock** [comment]
It would not be hard for mmseg to support the latest GPUs as long as PyTorch itself supports it. We will keep tracking it.
