### ISSUE TITLE
Hello! about test_eval_hook.py

### ISSUE THREAD

**Issue by 459737087** [open-mmlab/mmsegmentation#1737]
line 14 ### **from mmseg.core import DistEvalHook, EvalHook**
I can't find EvalHook.py in mmseg.core.
and when I  use hook_msgs, 
I find the parameter best_score has been deleted .

**Comment by lorinczszabolcs** [comment]
In this line everything is imported from mmseg.core.evaluation:

https://github.com/open-mmlab/mmsegmentation/blob/5cb9f43c9d1c802d84ab8fa420d1f0bd5ae93177/mmseg/core/__init__.py#L4

And in this line EvalHook and DistEvalHook is imported from mmseg.core.evaluation.eval_hooks:
https://github.com/open-mmlab/mmsegmentation/blob/5cb9f43c9d1c802d84ab8fa420d1f0bd5ae93177/mmseg/core/evaluation/__init__.py#L3

So you can find them in [mmseg.core.evaluation.eval_hooks](https://github.com/open-mmlab/mmsegmentation/blob/5cb9f43c9d1c802d84ab8fa420d1f0bd5ae93177/mmseg/core/evaluation/eval_hooks.py)

Not sure what were you referring to by best_score.

**Comment by 459737087** [comment]
[https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/evaluation.py](url)
### 
        **_best_score = runner.meta['hook_msgs'].get(
            'best_score', self.init_value_map[self.rule])
        if self.compare_func(key_score, best_score):
            best_score = key_score
            runner.meta['hook_msgs']['best_score'] = best_score_**
@lorinczszabolcs

**Comment by lorinczszabolcs** [comment]
Yes, that can be found in the parent class of mmseg’s EvalHook, in https://github.com/open-mmlab/mmcv/blob/9fffcbc9cdc79736b866d17d0243f4eef7b7cadf/mmcv/runner/hooks/evaluation.py


Also, best_score is only saves if save_best parameter is set, according to this line:
https://github.com/open-mmlab/mmcv/blob/9fffcbc9cdc79736b866d17d0243f4eef7b7cadf/mmcv/runner/hooks/evaluation.py#L280
