### ISSUE TITLE
SyncBN is only supported with DDP.

### ISSUE THREAD

**Issue by waqarsqureshi** [open-mmlab/mmsegmentation#1738]
UserWarning: SyncBN is only supported with DDP. To be compatible with DP, we convert SyncBN to BN. Please use dist_train.sh which can avoid this error

I get this warning while  I run test.py. is this a warning only or an error? Can someone explain
 @MengzhangLI

**Comment by MengzhangLI** [comment]
It is just warning.

Related PR is [here](https://github.com/open-mmlab/mmsegmentation/pull/772)
