### ISSUE TITLE
What is the purpose of '_base_' in the configs 

### ISSUE THREAD

**Issue by CanyonWind** [open-mmlab/mmsegmentation#174]
Hi, thanks for the amazing repo. This might seem trivial but I do confuse about the purpose of `_base_`.

It looks like working for inheriting the configurations from other scripts and overwriting some. Could you please outline its purpose and the logics behind it? Thanks!

**Comment by xvjiarui** [comment]
Hi @CanyonWind 
Thanks for your interest. You may find more information [here](https://mmsegmentation.readthedocs.io/en/latest/config.html).
