### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#1743]
Windows, I  run python tools/train.py configs\\unet\\deeplabv3_unet_s5-d16_ce-1.0-dice-3.0_128x128_40k_chase-db1.py--gpu
-ids 0 1,but the nvidia-smi display this program only runs on GPU0,why

**Comment by MengzhangLI** [comment]
Here is doc about [Train with multiple GPUs](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/train.md#train-with-multiple-gpus).
