### ISSUE TITLE
How to ignore the index that has been ignored in the loss function during metric evaluation?

### ISSUE THREAD

**Issue by timothylimyl** [open-mmlab/mmsegmentation#1747]
If I want to ignore certain classes, I do not care for what the metrics are on these classes because the model will just end up "hallucinating" on these ignored classes and it will cause the mIoU for other classes to be skewed wrongly as it will be predicted onto the ignored pixels. 

How do I change the metric evaluation code to also ignore the pixels with the ignored index too?

**Comment by xiexinch** [comment]
Hi @timothylimyl
Might set it at dataset config.
https://github.com/open-mmlab/mmsegmentation/blob/0fa7c95fd93c38da2a5e4c0567b90538bbb35d3d/mmseg/datasets/custom.py#L60

**Comment by timothylimyl** [comment]
@xiexinch thank you. it works, metric shows `nan` for that class now.  Hopefully mmseg does not let it affect the loss.
