### ISSUE TITLE
Questions about data augmentation

### ISSUE THREAD

**Issue by lkyyef** [open-mmlab/mmsegmentation#1753]
When training data with segmenter, I wanted to remove the data augmentation part, so I deleted these statements，as follows：

# dataset settings
dataset_type = 'ADE20KDataset'
data_root = 'data/ade/ADEChallengeData2016'
img_norm_cfg = dict(
    # mean=[100.47137, 87.18856, 94.230064], std=[62.180176, 50.501316, 51.120777], to_rgb=True)
    mean=[94.044586, 98.81862, 92.09202], std=[62.172123, 59.34455, 59.738434], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
    # dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
    # dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    # dict(type='RandomFlip', prob=0.5),
    # dict(type='PhotoMetricDistortion'),
    # dict(type='Normalize', **img_norm_cfg),
    # dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]

But it reports an error and cannot run，How can I modify it？

**Comment by xiexinch** [comment]
Hi @lkyyef
Sorry for the late reply.
You might modify the `meta keys` in `Collect` method config.
```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_semantic_seg'],
        meta_keys=(
            'filename',
            'ori_filename',
            'ori_shape',
            'img_shape',
            'img_norm_cfg')),
]
```
https://github.com/open-mmlab/mmsegmentation/blob/85569442b659fa59a51a88449689b2aa1603e4ba/mmseg/datasets/pipelines/formatting.py#L250

**Comment by lkyyef** [comment]
Thank you for your answers
