### ISSUE TITLE
How to download the ADE20K dataset as mmseg required

### ISSUE THREAD

**Issue by YingYingFight** [open-mmlab/mmsegmentation#1754]
Hello!

I'm using mmsegmentation to train models on the ADE20K dataset.  However, I cannot download the ADE20K dataset, since I found the [link](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#ade20k)  to download ADE20K in the mmseg github is invalid now.

 I tried two ways to download, but there are still troubles since the dataset I downloaded has different file directories: **No annotations files in the dataset I downloaded.**

**Could you please tell me how to download the ADE20K directly so I can use mmseg?** 

1. I downloaded from the  [ADE20K official dataset](http://groups.csail.mit.edu/vision/datasets/ADE20K/): 
>ADE20K_2021_17_01
 ├── images
│   └── ADE
│       ├── training
│       └── validation
├── index_ade20k.mat
├── index_ade20k.pkl
└── objects.txt
 
2. I downloaded from [openAI website](https://deepai.org/dataset/ade20k):
> └── ADE20K_2016_07_26
    ├── images
    │   ├── training
    │   └── validation
    └── index_ade20k.mat

When the official directories  in  [mmsegmentation](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#prepare-datasets)

> ade
│   │   ├── ADEChallengeData2016
│   │   │   ├── annotations
│   │   │   │   ├── training
│   │   │   │   ├── validation
│   │   │   ├── images
│   │   │   │   ├── training
│   │   │   │   ├── validation

Thank you very much!

**Comment by fingertap** [comment]
By default the mmseg uses the older version of ADE20k. The dataset seems to get updated. See the related issue here #984 . The [link to download ADE20k](https://mmsegmentation.readthedocs.io/en/latest/dataset_prepare.html#ade20k) is now a 404 page. Need a new mirrored download source.

**Comment by fingertap** [comment]
@MengzhangLI  @xiexinch  Can you guys help?

**Comment by fingertap** [comment]
The domain is changed. New download link is [this](http://sceneparsing.csail.mit.edu/data/ADEChallengeData2016.zip). Please update the document.

**Comment by xiexinch** [comment]
Hi @fingertap,
Thanks for your report, we'll update the document soon.

And you might try this [link](https://groups.csail.mit.edu/vision/datasets/ADE20K/index.html#Download), register an account then download the dataset.

**Comment by fingertap** [comment]
This link will lead to a different dataset layout, making the dataloader of mmseg not directly applicable. See #984 .

> And you might try this [link](https://groups.csail.mit.edu/vision/datasets/ADE20K/index.html#Download), register an account then download the dataset.

It seems that their server is just dead. This link also gives a 404 page. I think this issue may be temporal. Anyway, I have a copy of the dataset file.

**Comment by YingYingFight** [comment]
> This link will lead to a different dataset layout, making the dataloader of mmseg not directly applicable. See #984 .
> 
> > And you might try this [link](https://groups.csail.mit.edu/vision/datasets/ADE20K/index.html#Download), register an account then download the dataset.
> 
> It seems that their server is just dead. This link also gives a 404 page. I think this issue may be temporal. Anyway, I have a copy of the dataset file.

Hi, @fingertap,
It seems that we met the same problem [#984](https://github.com/open-mmlab/mmsegmentation/issues/984). **And the baseline papers I read are still using the older ADE20K.**

I wonder how did you get the copy of old version dataset, which work with mmseg? Could you please share the copy of old dataset with me?

Thank you very much.

**Comment by YingYingFight** [comment]
Hi,   @xiexinch @fingertap,

I know updating the mmseg to be compatible with new version dataset requires tons of work.  Could you please share me a copy of ADE20K 2016 dataset, so that I can do the research with mmseg now?

Thank you very much!

**Comment by YingYingFight** [comment]
Problem solved by obtaining a copy of ADE20K 2016. Thank you all for your help!

**Comment by JierunChen** [comment]
> Problem solved by obtaining a copy of ADE20K 2016. Thank you all for your help!

Hi, could you kindly share how you convert the ADE20K 2016 dataset to the format as in required by mmseg? Thanks a lot.

**Comment by wenyuqing** [comment]
> Problem solved by obtaining a copy of ADE20K 2016. Thank you all for your help!

Hi,could you kindly share a copy of ADE2016? Thanks a lot。

**Comment by aungpaing98** [comment]
Hi, is there any update on this issue?

The format is completed different. it would be great if someone could share.
Thanks.

**Comment by fingertap** [comment]
According to the [author's response](https://github.com/CSAILVision/sceneparsing/issues/19#issuecomment-643068090), this dataset is under BSD-3, which allows us to redistribute. So maybe you can provide an image for download? @xiexinch 

Hi @aungpaing98 , my dataset is on a remote server with limited bandwidth. Maybe mmseg can provide a download link for users.

**Comment by aungpaing98** [comment]
@fingertap, thanks for the response.

@xiexinch, Could you provide for the download? 
If not, I would like to have some samples of the original label dataset. 
So that I can convert using custom implementation.

Thanks for your time.

**Comment by xiexinch** [comment]
Hi @fingertap, @aungpaing98, @JierunChen, @wenyuqing, @Catherine-Tranquil, @zcs15,
Might try https://opendatalab.com/home, they provide plenty of datasets for download.
https://opendatalab.com/ADE20K_2016
