### ISSUE TITLE
colab tutorial import error

### ISSUE THREAD

**Issue by alex7008uk** [open-mmlab/mmsegmentation#1763]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Can't run the colab tutorial
![image](https://user-images.githubusercontent.com/76434638/178664135-9dce1e09-6ab1-401f-938c-99093f41e9f6.png)

**Comment by MeowZheng** [comment]
Many thanks for your bug report, we are working on fixing it.

**Comment by hartvq37** [comment]
Install the latest mmcv with 1.12 torch version works for me, but building wheels took a very long time to finish.

# Install PyTorch
!conda install pytorch=1.10.0 torchvision cudatoolkit=11.1 -c pytorch
# Install MMCV
#!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10/index.html
!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.12.0/index.html

**Comment by zhouzaida** [comment]
> Install the latest mmcv with 1.12 torch version works for me, but building wheels took a very long time to finish.
> 
> # Install PyTorch
> !conda install pytorch=1.10.0 torchvision cudatoolkit=11.1 -c pytorch
> 
> # Install MMCV
> #!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10/index.html !pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.12.0/index.html

Hi, PyTorch dose not provide pre-built packages for torch1.12-cu111 (https://download.pytorch.org/whl/torch_stable.html).

The recommended way to install mmcv-full is to use openmim:
```
pip install -U openmim
mim install mmcv-full
```

**Comment by zhouzaida** [comment]
> **Checklist**
> 
> 1. I have searched related issues but cannot get the expected help.
> 2. The bug has not been fixed in the latest version.
> 
> **Describe the bug** Can't run the colab tutorial ![image](https://user-images.githubusercontent.com/76434638/178664135-9dce1e09-6ab1-401f-938c-99093f41e9f6.png)

Hi, you can install mmcv-full via openmim
```bash
pip install -U openmim
mim install mmcv-full
```

**Comment by xiexinch** [comment]
Hi @alex7008uk,
I create a new PR to solve the installation problem, you might take a look.
