### ISSUE TITLE
When I started testing the data with the model, the values of decode.loss_ce, loss, and aux.loss_ce of the model were always 0, and the values of decode.acc_seg, and aux.acc_seg were always 100.！！！！！

### ISSUE THREAD

**Issue by yzw44** [open-mmlab/mmsegmentation#1765]
![微信截图_20220713202936](https://user-images.githubusercontent.com/84362253/178734479-d0fcfd1d-f3bc-4db2-a3d2-839abaeb7db0.png)
[20220713_200505.log](https://github.com/open-mmlab/mmsegmentation/files/9110300/20220713_200505.log)
Above is the log file of my model. When I started testing the data with the model, the values of decode.loss_ce, loss, and aux.loss_ce of the model were always 0, and the values of decode.acc_seg, and aux.acc_seg were always 100. as you can see from the end of the model log.

**Comment by MeowZheng** [comment]
would you like to provide more information about your issue

**Comment by yzw44** [comment]
> would you like to provide more information about your issue
Hello, this is the log file of my model, when I start testing data with the model, the value of decode.loss_ce, loss, aux.loss_ce of the model is always 0, and the value of decode.acc_seg, and aux.acc_seg is always 100. you can see it from the end of the model log.
[20220713_200505.log](https://github.com/open-mmlab/mmsegmentation/files/9109840/20220713_200505.log)

**Comment by xiexinch** [comment]
Hi! Thank you for your quick response. I'm more curious about the reasoning behind a lack of class weighting though. Especially with the heavy imbalance of certain classes such as poles and trains in the Cityscapes dataset, it seems that class weighting would be necessary for the model to perform well as various CNN semantic segmentation architectures such as UNet or LinkNet utilize it in their experiments.

**Comment by SCG421** [comment]
Have you solved it? I had a similar problem.
