### ISSUE TITLE
Order of --out prediction

### ISSUE THREAD

**Issue by arthuremir** [open-mmlab/mmsegmentation#1768]
Hi!

What is the order of predictions in the output .pkl file? I'm unable to match predictions to corresponding images since filenames are not saved in pkl file.

**Comment by MeowZheng** [comment]
Its order is the same as the alphabetical order of the filenames of the dataset.

**Comment by jnjz** [comment]
> Its order is the same as the alphabetical order of the filenames of the dataset.

So the order is [1.jpg 100.jpg 11.jpg] or [1.jpg,11.jpg,100.jpg]?
Thx!

**Comment by MeowZheng** [comment]
Yes
