### ISSUE TITLE
overwriting the original image

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#1770]
When testing, mmsegmentation defaults to overlay the predicted mask on the original picture for display or save, how to modify the code without overwriting the original image

**Comment by MeowZheng** [comment]
I think you can set a new `show-dir`
ref: 
https://github.com/open-mmlab/mmsegmentation/blob/0e37281884193838417a43802bb7a4c854d2067e/tools/test.py#L48-L49
https://github.com/open-mmlab/mmsegmentation/blob/0e37281884193838417a43802bb7a4c854d2067e/mmseg/apis/test.py#L37
