### ISSUE TITLE
Visualize the model with tensorboard

### ISSUE THREAD

**Issue by OlwlO** [open-mmlab/mmsegmentation#1777]
I want to visualize the model after it is built, I am trying to build the model with the build_segmentor() function and visualize the model with tensorboard.But, this approach doesn't work. How can I use this framework for model visualization?

**Comment by MeowZheng** [comment]
I'm not sure what exactly you mean by model visualization, and where did you encounter difficulties?  build_segmentor or tensorboard ?

**Comment by MeowZheng** [comment]
where did you encounter difficulties? build_segmentor？

**Comment by MeowZheng** [comment]
I would like to suggest you use or refer to `inferece_segmentor`

https://github.com/open-mmlab/mmsegmentation/blob/0e37281884193838417a43802bb7a4c854d2067e/mmseg/apis/inference.py#L70

**Comment by shigejiafeimao** [comment]
> I would like to suggest you use or refer to `inferece_segmentor`
> 
> https://github.com/open-mmlab/mmsegmentation/blob/0e37281884193838417a43802bb7a4c854d2067e/mmseg/apis/inference.py#L70

how to use? the details?

**Comment by shigejiafeimao** [comment]
> I would like to suggest you use or refer to `inferece_segmentor`
> 
> https://github.com/open-mmlab/mmsegmentation/blob/0e37281884193838417a43802bb7a4c854d2067e/mmseg/apis/inference.py#L70

I also want to Visualize the model like the graph of tensorboard.but i dont know how to get the graph.
