### ISSUE TITLE
where can i get the final segment map of the model ？

### ISSUE THREAD

**Issue by ywx-hub** [open-mmlab/mmsegmentation#178]
I have already found inference function in encode_decode.py,where can print the final segment map.

but i can not find which file make segment map become to the results?

**Comment by xvjiarui** [comment]
Hi @ywx-hub 
You may refer to [image_demo.py](https://github.com/open-mmlab/mmsegmentation/blob/master/demo/image_demo.py) for example of getting segmentation map.

**Comment by ywx-hub** [comment]
> Hi @ywx-hub
> You may refer to [image_demo.py](https://github.com/open-mmlab/mmsegmentation/blob/master/demo/image_demo.py) for example of getting segmentation map.

OK，i will have a try . thank you very much!

**Comment by ywx-hub** [comment]
Sorry,i haved tried seversal times.But the function of mmseg.apis.inference_segmentor in  image_demo.py  's output is the segmentation result directly.I can not get  the segmentation feature map.

i want to merge several models,  but **forward the model** get the results directly. where can i maintain the model ,i want find the final process of  forward  (like argmax ). 

Thank you very much

**Comment by xvjiarui** [comment]
Hi @ywx-hub 
If you would like to get the output before `argmax`, you may need to modify this [func](https://github.com/open-mmlab/mmsegmentation/blob/e384ef578a6d82c99d9b1190b337c615814e928b/mmseg/models/segmentors/encoder_decoder.py#L263).
