### ISSUE TITLE
The problem of VOC12 dataset read

### ISSUE THREAD

**Issue by Mamba-ZJP** [open-mmlab/mmsegmentation#1784]
I want to ask how the MMSeg framework read the gt_semantic_seg of voc12, which directly transforms the color pixel to the index pixel?
我想问下在MMSeg框架下读VOC12 数据集的时候，他如何将RGB的彩色图片读成单通道然后每个像素都是该类别的index的。因为我在阅读源码的时候发现，源码是这样：
```
gt_semantic_seg = mmcv.imfrombytes(
            img_bytes, flag='unchanged',
            backend=self.imdecode_backend).squeeze().astype(np.uint8)
```
`imfrombytes()`并没有任何对颜色进行转换的代码

**Comment by xiexinch** [comment]
Hi @Mamba-ZJP,
For Pascal VOC 2012 dataset with augmentation images, we use `tools/convert_datasets/voc_aug.py` to generate single channel annotations. If not use augmentation images, the default image reading backend is `pillow` and we do not convert the label mask to 'RGB' mode, so it will map color to a palette index.

**Comment by Mamba-ZJP** [comment]
Thank you.
