### ISSUE TITLE
SWin wrong feature shape returned

### ISSUE THREAD

**Issue by 0reza** [open-mmlab/mmsegmentation#1786]
**Describe the bug**
It's actually a logical error.
For the purpose of returning the output of each Stage, we should use the down sampled version of the output. 

https://github.com/open-mmlab/mmsegmentation/blob/336435b80b26fb1273b5a4b5d597d1d65e2ff644/mmseg/models/backbones/swin.py#L746-L754
---
Here is the return part of the Stage:
https://github.com/open-mmlab/mmsegmentation/blob/336435b80b26fb1273b5a4b5d597d1d65e2ff644/mmseg/models/backbones/swin.py#L458-L462

For example, if we want to use UPerNet as decode_head, we need some architecture like Feature Pyramid Network.

**Bug fix**

We should use `x` and `hw_shape` instead of `out` and `out_hw_shape` in the `if` block.

**Comment by xiexinch** [comment]
Hi @0reza,
Thanks for your report, we'll fix it asap.

Hi @MeowZheng, could you take a look at this problem?

**Comment by xiexinch** [comment]
Hi @0reza,
In the original version of the Swin Transformer, downsample module (PatchMerging module) is the first layer at each stage, the output of the downsample module is not the output of each stage.

**Comment by 0reza** [comment]
Got it...
tnx @xiexinch
