### ISSUE TITLE
Schedule plug in a different loss a later training stage 

### ISSUE THREAD

**Issue by hssandriss** [open-mmlab/mmsegmentation#1795]
Hello, 

I would like to know if it's possible to specify till when a loss can be applied and define another loss to replace it. 
Say for example apply CE for 50 epochs then Focal Loss for 10 epochs end to end.

I look forward to hearing from you,
Hssan

**Comment by MengzhangLI** [comment]
It is not supported yet. Alternatively you could use multiple losses like [here](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/training_tricks.md#multiple-losses).
