### ISSUE TITLE
Semantic segmentation, predicting how to crop pictures

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmsegmentation#1796]
Identified object

To crop

Height and width depend on the size of the object

Background translucent

![111](https://user-images.githubusercontent.com/6490927/179661581-3bd69852-0a29-4c46-b30d-0c08e6e8a266.png)

**Comment by xiexinch** [comment]
Hi @monkeycc,
Could you describe your problem or requirements in detail(Datasets, usage scenarios, etc.)? According to the current description, we do not implement such a model or data augmentation method.

**Comment by monkeycc** [comment]
DeepLabV3 模型
COCO数据集

语义分割检测之后

需要后处理方法

如何进行这样的裁剪
@xiexinch

**Comment by xiexinch** [comment]
I think there are many ways to implement this method, but because of the lack of developers, we do not yet have plans to support this post-processing. You might try to implement this method yourself, and welcome to create a PR for this method. :)
