### ISSUE TITLE
KeyError: 'metric mAP is not supported

### ISSUE THREAD

**Issue by xinfu607** [open-mmlab/mmsegmentation#180]
python tools/test.py configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py \
    checkpoints/pspnet_r50-d8_512x512_20k_voc12aug_20200617_101958-ed5dfbd9.pth \
    --eval mAP

I get the following error after running the above command.
(python 3.6.8  torch 1.6.0   mmsegmentation 0.6.0 mmcv-full 1.1.4)

  ****File "/code/image_segmentation/mmsegmentation/mmsegmentation/tools/test.py", line 156, in <module>
    main()
  File "/code/image_segmentation/mmsegmentation/mmsegmentation/tools/test.py", line 152, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/code/image_segmentation/mmsegmentation/mmsegmentation/mmseg/datasets/custom.py", line 331, in evaluate
    raise KeyError('metric {} is not supported'.format(metric))
KeyError: 'metric mAP is not supported****

**Comment by xvjiarui** [comment]
Hi @xinfu607 
You should use `--eval mIoU`.

**Comment by xinfu607** [comment]
Thanks.
