### ISSUE TITLE
Error "Trying to resize storage that is not resizable" training with tools/dist_train.sh

### ISSUE THREAD

**Issue by hugobanola99** [open-mmlab/mmsegmentation#1805]
I am running the training script tools/dist_train.sh for train with multiple GPU and I get this error "RuntimeError: Trying to resize storage that is not resizable".I want to train a ViT model and I use the follow command to run the script ` ./tools/dist_train.sh configs/vit/upernet_vit-b16_mln_512x512_80k_ade20k.py 2 --work-dir work_dirs/upernet_vit-b16_mln_512x512_80k_ade20k/ --deterministic --resume-from checkpoints/upernet_vit-b16_mln_512x512_80k_ade20k_20210624_130547-0403cee1.pth`

![error_issue](https://user-images.githubusercontent.com/72133499/180281769-fc2f5132-4dcf-42fd-aab3-da60d4555ffe.png)

In the config file I only modificate the pretrained model,replaced it by the checkpoint file that I used in the above command.
```
_base_ = [
    '../_base_/models/upernet_vit-b16_ln_mln.py',
    '../_base_/datasets/ade20k.py', '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_160k.py'
]

model = dict(
    pretrained='checkpoints/upernet_vit-b16_mln_512x512_80k_ade20k_20210624_130547-0403cee1.pth',
    decode_head=dict(num_classes=150),
    auxiliary_head=dict(num_classes=150))

# AdamW optimizer, no weight decay for position embedding & layer norm
# in backbone
optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.00006,
    betas=(0.9, 0.999),
    weight_decay=0.01,
    paramwise_cfg=dict(
        custom_keys={
            'pos_embed': dict(decay_mult=0.),
            'cls_token': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))

lr_config = dict(
    _delete_=True,
    policy='poly',
    warmup='linear',
    warmup_iters=1500,
    warmup_ratio=1e-6,
    power=1.0,
    min_lr=0.0,
    by_epoch=False)


# By default, models are trained on 8 GPUs with 2 images per GPU
data = dict(samples_per_gpu=2)
```

I have also tried to run the script with a single GPU and it return another error "RuntimeError: stack expects each tensor to be equal size, but got [1, 512, 512] at entry 0 and [1, 512, 512, 512] at entry 1"

**Comment by MengzhangLI** [comment]
I never meet this error and just google it, here are some potential reasons:
(1) Certain annotation is blank. [link](https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/237).
(2) Your `num_workers` does not equal to GPU number you use. [link](https://blog.csdn.net/m0_37614787/article/details/112239556)
(3) PyTorch version problem. [link](https://github.com/pytorch/pytorch/issues/15770)
