### ISSUE TITLE
Intermittent libpng errors

### ISSUE THREAD

**Issue by FranzEricSchneider** [open-mmlab/mmsegmentation#1806]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. (Yes, found no issues related to libpng)
2. The bug has not been fixed in the latest version. (Yes)

**Describe the bug**

I am trying to run mmsegmentation repeatedly in the mmseg Docker container, with variations. I am running on the same set of images, which are a dataset of my own labeled images. Every so often the training fails partway through with a `libpng` error, even though the same set of train/validation images have been used successfully before and after the failure.

**Reproduction**

1. What command or script did you run?

I do not know how to reproduce the error, it only appears intermittently and may be a factor of my custom dataset due to being a PNG issue. Any debug suggestions would be appreciated. The error appears to have shown up 5 times in 41 runs of 6k iterations each.

2. Did you make any modifications on the code or config? Did you understand what you have modified?

No modifications have been made to code, but as I've been testing variations a variety of modifications have been made to both the dataset config (trying a variety of augmentations) and the model config (BiSeNet-v2 and Segformer). I believe I understand the modifications made, in support of that the training runs to completion ~85% of the time. ~15% of the time it fails as described below.

3. What dataset did you use?

I have a custom-labeled dataset with 2048x2448 images, 128 of them in `img_dir/train/`. It has 6 classes, and the decode heads of the model configs have been modified to reflect that.

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

```
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.6.0
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.26.0+891448f
```

**Error traceback**

In this case the error happened after 9900 iterations, I've also had it happen after 26000 iterations, as well as at the very beginning of training. When it happens right at the beginning the `libpng error: IDAT: CRC error` error is the same, but the rest of the traceback doesn't show up because the model hasn't reached that point.

```none
2022-07-18 22:51:31,796 - mmseg - INFO - Iter [9850/30000]	lr: 7.020e-03, eta: 3:48:57, time: 0.531, data_time: 0.010, memory: 9394, decode.loss_ce: 0.1976, decode.acc_seg: 92.2104, aux.loss_ce: 0.0823, aux.acc_seg: 91.9445, loss: 0.2800
2022-07-18 22:51:58,346 - mmseg - INFO - Iter [9900/30000]	lr: 7.004e-03, eta: 3:48:07, time: 0.531, data_time: 0.010, memory: 9394, decode.loss_ce: 0.2016, decode.acc_seg: 91.9323, aux.loss_ce: 0.0840, aux.acc_seg: 91.6551, loss: 0.2856
libpng error: IDAT: CRC error
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 238, in main
    meta=meta)
  File "/mmsegmentation/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 58, in train
    data_batch = next(data_loader)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 964, in _next_data
    raise StopIteration
StopIteration
```

**Bug fix**

I do not have a bug fix. After some googling CRC errors appear to be related to corruption issues within the images. However I'm not sure how that's possible. Sometimes the models are able to run just fine on these images, and I can also view the images just fine in an image viewer.

**Comment by MengzhangLI** [comment]
Thanks for your feedback. Perhaps it is caused by your local limited computational resources on large `2048x2448` shape images. Does this error happened on smaller size dataset?

**Comment by FranzEricSchneider** [comment]
(Same answer as #1807, re-posting for people only reading this issue)

That shouldn't be an issue, the network is not actually training on the full images. In the dataset augmentation I have
```
crop_size = (480, 512)
...
train_pipeline = [
    ...
    dict(type="RandomCrop", crop_size=crop_size, cat_max_ratio=0.75),
    ...
]
```
I've also checked that the training images actually use this smaller size. Sorry for not making that clear in the initial post.

**Comment by FranzEricSchneider** [comment]
The project where I was running into these is no longer active, so I don't have any new information. If anyone has any ideas feel free to post, but I'll close this now.
