### ISSUE TITLE
where is the pretrained swin weights converted from official repo?

### ISSUE THREAD

**Issue by lauraset** [open-mmlab/mmsegmentation#1808]
Hi, I didn't find the pretrained swin weights as mentioned in https://github.com/open-mmlab/mmsegmentation/blob/master/configs/swin/README.md.
Whether we need to convert it by ourself?
Thank you very much.

**Comment by xiexinch** [comment]
Hi @lauraset,
We set the link to the pre-trained weights in the configuration files.
https://github.com/open-mmlab/mmsegmentation/blob/03c244769055b1a54b6a457d95268cad58734200/configs/swin/upernet_swin_large_patch4_window7_512x512_pretrain_224x224_22K_160k_ade20k.py#L5
And we also support using the official weights provided by [SwinTransformer](https://github.com/microsoft/Swin-Transformer), the link to the pre-trained weights on the README is valid, you could download them and do a conversion using the [script](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/model_converters/swin2mmseg.py) we provide.

**Comment by lauraset** [comment]
Hi, @xiexinch . Thank you very much. I find it. I met this issue since I did not use the latest version.
