### ISSUE TITLE
Why is the size of the model file generated by the training file different from the actual file size?

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmsegmentation#1809]
Hello! I have a question here, that is, the size of the file generated by the training is twice as large as the size of the model provided by your official website. What is the reason?

**Comment by xiexinch** [comment]
Hi @chen-del,
Do you mean the config file or the model weights file?

**Comment by chen-del** [comment]
Hi @xiexinch 
I'm very sorry, I don't need to answer the above questions. I have found the reason and solved it. It is the problem of model weight preservation. Can I ask another question? For the pspnet_head decoding header, when I use the new backbone network, the backbone of yolov5 To replace renetv50, is it necessary to re-write the template class for decoding and replacement of the original pspnet_head decoding header?

**Comment by xiexinch** [comment]
Hi, I think there is no need to modify the source code of the decoder if it only replaces the backbone. You might try to modify the [base config file](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/pspnet_r50-d8.py), configure the output of the backbone, and the input of decode_head.

**Comment by chen-del** [comment]
HI@xiexinch, thank you very much!  
Can I understand that it is only necessary to modify the output structure of the mobnetv3 network under the bankbon file and the input structure of the psp_head in decode_heads. In other words, you only need to modify the output structure of mobnetv3 to correspond to psd_head, and then you can start normal training. Then the pre-training file weight parameters of the mobnetv3 network, I can use the ones you provide directly.The file example is shown below
![2736](https://user-images.githubusercontent.com/58769772/180411455-3de4380b-1df3-4d7c-8a60-63b54e4465e3.jpg)
!

**Comment by xiexinch** [comment]
Sorry... I'm not quite sure what your problem is.
And we provide many backbone replacement examples, you might read them as reference. 
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_hr18.py
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_r50-d8.py
