### ISSUE TITLE
what's the meaning of checkpoint and config file? and what is the .pth file? Does .pth represent weight file?

### ISSUE THREAD

**Issue by cunese24** [open-mmlab/mmsegmentation#1813]

**Comment by cunese24** [comment]
please help me,thanks.

**Comment by MengzhangLI** [comment]
For example, in (deeplabv3+)[https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3plus]
![image](https://user-images.githubusercontent.com/24582831/180681323-024f2468-25d8-4373-967c-f63902396e83.png), config and checkpoint could be found here.

Type of checkpoint file `.pth` in MMSegmentation.

**Comment by cunese24** [comment]
> https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3plus

hi,config file represents dataset? .pth is checkpoint file? and .pth presents model?

**Comment by MengzhangLI** [comment]
(1) config file represents dataset? No. 
(2) .pth is checkpoint file? No.
(3) .pth presents model? No.

[What is .pth file.](https://filext.com/file-extension/PTH)
[What is config file in MMSegmentation.](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/config.md)

Perhaps those docs may help you: https://github.com/open-mmlab/mmsegmentation/tree/master/docs/en

**Comment by cunese24** [comment]
> (1) config file represents dataset? No. (2) .pth is checkpoint file? No. (3) .pth presents model? No.
> 
> [What is .pth file.](https://filext.com/file-extension/PTH) [What is config file in MMSegmentation.](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/config.md)
> 
> Perhaps those docs may help you: https://github.com/open-mmlab/mmsegmentation/tree/master/docs/en

Ok,thanks.QAQ
