### ISSUE TITLE
mmsegmentation 如何实现 重叠滑窗预测,How to realize overlapping sliding window prediction

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmsegmentation#1814]
mmsegmentation 
如何实现 重叠滑窗预测

比如9000*9000
不能直接滑窗裁剪
需要重叠裁剪  会有重复部分

这个时候 怎么合并

mmsegmentation 
是否有API支持

-----------
mmsegmentation

How to realize overlapping sliding window prediction

For example, 9000*9000

Cannot directly slide window clipping

If overlapping clipping is required, there will be repeated parts

How to merge at this time

mmsegmentation

Is there API support

**Comment by MengzhangLI** [comment]
It is not supported yet. Before that, we usually cropped original big image in advance during data preparation, such as [iSAID dataset](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#isaid).

**Comment by MengzhangLI** [comment]
You can use `crop_size` and `stride` to implement overlapping slide inference. 

config: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/convnext/upernet_convnext_base_fp16_512x512_160k_ade20k.py#L9

code: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L155-L201
