### ISSUE TITLE
some questions about test.py

### ISSUE THREAD

**Issue by francishcheng** [open-mmlab/mmsegmentation#1817]
is there a way to only draw segmentation result of selected type of object, not all of it?

**Comment by MengzhangLI** [comment]
It can not be implemented automatically. You could implement it by making prediction's (whose labels are not what you want) mask as transparent color.

**Comment by francishcheng** [comment]
> It can not be implemented automatically. You could implement it by making prediction's (whose labels are not what you want) mask as transparent color.

is there a transparent RGB color scheme?

**Comment by MengzhangLI** [comment]
> > It can not be implemented automatically. You could implement it by making prediction's (whose labels are not what you want) mask as transparent color.
> 
> is there a transparent RGB color scheme?

No. You may set it manually.
