### ISSUE TITLE
Always `tools/dist_train.sh: 8: Bad substitution` Error

### ISSUE THREAD

**Issue by Aspirinkb** [open-mmlab/mmsegmentation#1819]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I follow the [使用多卡 GPU 训练](https://mmsegmentation.readthedocs.io/zh_CN/latest/train.html#id3)(https://mmsegmentation.readthedocs.io/zh_CN/latest/train.html#id3) tutorial to start my training on my GPU server which has 8 V100.  Once I run the `tools/dist_train.sh` shell script, it always run error, by following error tips:
```
tools/dist_train.sh: 8: Bad substitution
```
The run command as followed:
`sh tools/dist_train.sh ./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py 4`

**Reproduction**

1. What command or script did you run?

   ```none
   sh tools/dist_train.sh ./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py 4
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I modify the config .py for my training. 

3. What dataset did you use?
I use my custom dataset.

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.2, V11.2.142
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.13.0+cu116
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.6
MMSegmentation: 0.26.0+13d4c39
```
2. You may add addition that may be helpful for locating the problem, such as
  

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by MengzhangLI** [comment]
It is error usually happened in script. Could you try to use `CUDA_VISIBLE_DEVICES=0,1 python tools/train.py ${CONFIG_FILE} [optional arguments]`?

**Comment by Aspirinkb** [comment]
Okay, but I think the tutorials and the scripts should be fixed.

**Comment by Aspirinkb** [comment]
> It is error usually happened in script. Could you try to use `CUDA_VISIBLE_DEVICES=0,1 python tools/train.py ${CONFIG_FILE} [optional arguments]`?
What's wrong with the command?
```
sh tools/dist_train.sh ./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py 4
```
If the above command is wrong, could you fix it? Or could you give a correct way of training model on single machine with multiple GPUs?

**Comment by Aspirinkb** [comment]
> It is error usually happened in script. Could you try to use `CUDA_VISIBLE_DEVICES=0,1 python tools/train.py ${CONFIG_FILE} [optional arguments]`?
What's wrong with the command?
```
sh tools/dist_train.sh ./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py 4
```
If the above command is wrong, could you fix it? Or could you give a correct way of training model on single machine with multiple GPUs?

**Comment by thanos-sakelliou** [comment]
Had the same error. Try `bash tools/dist_train.sh` instead of sh.
