### ISSUE TITLE
mobilenet_v3 The dataset used can split the dataset for voc, if so how to modify it.

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmsegmentation#1828]
Because I see that most of the datasets are cityscapes, but there are relatively few data sets using voc_aug. If I use voc in these networks, I need to modify those places

**Comment by xiexinch** [comment]
Hi @chen-del,
You might train all models with Pascal VOC 2012 dataset, just need to inherit [the VOC config file](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/pascal_voc12_aug.py).

For example:
https://github.com/open-mmlab/mmsegmentation/blob/03c244769055b1a54b6a457d95268cad58734200/configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py#L3
then modify the `num_classes`
https://github.com/open-mmlab/mmsegmentation/blob/03c244769055b1a54b6a457d95268cad58734200/configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py#L7

**Comment by chen-del** [comment]
@xiexinch Thanks a lot, but at the same time can the config file adapt to different input sizes, eg 192x192 network input.

**Comment by chen-del** [comment]
Hi @xiexinch ,
I rethink what I said above, that is, I see that most of the size input is 1028*520 or 2048*520 but if I want this input size to be 224*224 or 320*320, then I should How to set input?

**Comment by xiexinch** [comment]
It depends on the network you used, most networks support different input sizes.
