### ISSUE TITLE
facing Recursion Error while training the custom dataset

### ISSUE THREAD

**Issue by Priyadrasta-2111CS10** [open-mmlab/mmsegmentation#1830]
I encountered the error: **RecursionError: maximum recursion depth exceeded in comparison** as shown below while training with my custom dataset. I tried to set maximum recursion depth in **train.py** to low and high values still it didn't work at all. Please provide the fix.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/92008353/180864467-86ac084f-3534-4ad3-8c4f-78470e8dd9a2.png">
The following is the code for the config file for the custom dataset

```# Your dataset type defined in ./mmseg/datasets/__init__.py
dataset_type = 'MyDataset'
# Correct path of your dataset
data_root = 'data/my_dataset'

img_norm_cfg = dict( # This img_norm_cfg is widely used because it is mean and std of ImageNet 1K pretrained model
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

crop_size = (512, 512) # Crop size of image in training

train_pipeline=[]
test_pipeline=[]
data = dict(
    samples_per_gpu=4, # Batch size of a single GPU
    workers_per_gpu=0, # Worker to pre-fetch data for each single GPU
    train=dict( # Train dataset config
        type=dataset_type, # Type of dataset, refer to mmseg/datasets/ for details.
        data_root=data_root, # The root of dataset.
        img_dir='img_dir/train', # The image directory of dataset.
        ann_dir='ann_dir/train',  # The annotation directory of dataset.
        pipeline=train_pipeline), # pipeline, this is passed by the train_pipeline created before.
    val=dict( # Validation dataset config.
        type=dataset_type,
        data_root=data_root,
        img_dir='img_dir/val',
        ann_dir='ann_dir/val',
        pipeline=test_pipeline), # Pipeline is passed by test_pipeline created before.
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='img_dir/val',
        ann_dir='ann_dir/val',
        pipeline=test_pipeline))


```
The following is the python configuration file of the intended SETR model based on SETR_MLA.
```
_base_ = [
    '../_base_/models/setr_mla.py',
    '../_base_/datasets/my_dataset_config.py', '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_80k.py'
]

# model settings
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    backbone=dict(
        type='VIT_MLA',
        model_name='vit_large_patch16_384',
        img_size=512,
        patch_size=16,
        in_chans=3,
        embed_dim=1024,
        depth=24,
        num_heads=16,
        num_classes=3,
        drop_rate=0.1,
        norm_cfg=norm_cfg,
        pos_embed_interp=True,
        align_corners=False,
        mla_channels=256,
        mla_index=(5, 11, 17, 23)
    ),
    decode_head=dict(
        type='VIT_MLAHead',
        in_channels=1024,
        channels=512,
        img_size=512, 
        mla_channels=256,
        mlahead_channels=128,
        num_classes=3,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)))
# model training and testing settings
train_cfg = dict()
test_cfg = dict(mode='whole')
optimizer = dict(lr=0.002, weight_decay=0.0,
                 paramwise_cfg=dict(custom_keys={'head': dict(lr_mult=10.)})
                 )
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
test_cfg = dict(mode='slide', crop_size=crop_size, stride=(512, 512))
find_unused_parameters = True
data = dict(samples_per_gpu=1)
test_pipeline=[]

data = dict(
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))

```

**Comment by xiexinch** [comment]
Hi @Priyadrasta-2111CS10,
Could you show the `__getitem__()` method codes in your custom dataset if possible? And might examine whether the `Collect` pipeline is in your train_pipeline.

**Comment by Priyadrasta-2111CS10** [comment]
The following is the codes of `__getitem__()` method in custom.py 
  ```def __getitem__(self, idx):
        if self.test_mode:
            return self.prepare_test_img(idx)
        else:
            return self.prepare_train_img(idx)
```
As of now, the test and train pipeline is the empty list according to the solution prescribed here https://github.com/open-mmlab/mmsegmentation/issues/1634#issuecomment-1148161525 the code for the config file for the custom dataset

And my dataset has the directory structure as shown below

<img width="184" alt="image" src="https://user-images.githubusercontent.com/92008353/181517569-960c0100-436f-4430-bf0e-2c6435a81adb.png">

and the image inside the folders are of the format **case34IMGXXXX.png** as the following
<img width="84" alt="image" src="https://user-images.githubusercontent.com/92008353/181524344-ca85a97e-f7db-4026-af58-63738cae0489.png">
Please mention what will be appropriate for the keys argument of `Collect` method of train and test pipeline.

**Comment by xiexinch** [comment]
Hi @Priyadrasta-2111CS10,
If your train_pipeline is indeed an empty list, might try to use the train_pipeline of the cityscapes dataset.
https://github.com/open-mmlab/mmsegmentation/blob/eeeaff942169dea8424cd930b4306109afdba1d0/configs/_base_/datasets/cityscapes.py#L7
When train_pipeline is empty, it does reproduce the problem.

**Comment by Priyadrasta-2111CS10** [comment]
Hi @xiexinch ,

Then it is redirecting to the initial error i.e. **TypeError: init() got an unexpected keyword argument 'prob'** raised in an earlier issue https://github.com/open-mmlab/mmsegmentation/issues/1634#issue-1256624867 where I had been asked to initialize the train and test pipeline with an empty list. So could you possibly suggest which things should be present in the train and test pipeline along with the `Collect ` method?

And when I try to initialize the pipelines as shown below, it's throwing the error **Keyerror:'filename'**
```
train_pipeline=[dict(type='Collect', keys=['img', 'gt_semantic_seg']),]
test_pipeline=[dict(type='Collect', keys=['img']),]
```

**Comment by xiexinch** [comment]
Hi @Priyadrasta-2111CS10,
**Keyerror:'filename'** occurs because of the lack of `LoadImageFromFile` method in your pipeline.
