### ISSUE TITLE
How to solve this problem in training myself dataset

### ISSUE THREAD

**Issue by Manningchan** [open-mmlab/mmsegmentation#1833]
**
KeyError: 'mydata is not in the dataset registry'
**

**Comment by MengzhangLI** [comment]
You could follow this [Vaihingen Dataset PR](https://github.com/open-mmlab/mmsegmentation/pull/1171) whose changed files show two `__init__.py` are modified by adding `xxx_dataset` class. I think this PR may help you.

**Comment by MengzhangLI** [comment]
`./mmseg/datasets/__init__.py` and `configs/_base_/datasets/mydata.py`
