### ISSUE TITLE
issue while getting the labels : segformer

### ISSUE THREAD

**Issue by driggeraaliya94** [open-mmlab/mmsegmentation#1837]
Hi, 

I am facing an issue while extracting labels. I have trained a segformer and was able to segment the images. Though, I do not understand how to extract images. 

I have got a tensor, sharing the pic of the tensor below.  Can anyone please help me to understand how to extract the labels from this array, also is this array denotes the pixel values or probabilities of each class. 
![Screenshot from 2022-07-28 16-56-27](https://user-images.githubusercontent.com/109962218/181500762-81cbc0ef-21dd-499d-b6dc-302249f7ac87.png)

**Comment by MengzhangLI** [comment]
I suggest you use IDE like PyCharm and debug the inference pipeline.
