### ISSUE TITLE
No such file or directory: '/tmp/tmpk43e4hxh/tmp7fxk8efj.py'

### ISSUE THREAD

**Issue by cunese24** [open-mmlab/mmsegmentation#1839]
No such file or directory: '/tmp/tmpk43e4hxh/tmp7fxk8efj.py'，why?
when I trained first time,it's ok. but now error report:No such file or directory: '/tmp/tmpk43e4hxh/tmp7fxk8efj.py'
please help me,thanks.

**Comment by xiexinch** [comment]
Hi @cunese24,
There is SynatixError in your config file.
#122

**Comment by cunese24** [comment]
> Hi @cunese24, There is SynatixError in your config file. #122

thanks.QAQ

**Comment by fffff515** [comment]
> > Привет @cunese24, В вашем конфигурационном файле есть SynatixError. [#122 ](https://github.com/open-mmlab/mmsegmentation/issues/122)
> 
> спасибо.QAQ

how to solve the problem please tell me i don't understand

**Comment by fffff515** [comment]
hello, i'm having a problem on startup. When you run the program, it works and does not give errors, but at the same time I don’t get QR
