### ISSUE TITLE
NotImplementedError: [Adaptive pool]:input size not accessible

### ISSUE THREAD

**Issue by dreamnever** [open-mmlab/mmsegmentation#1840]
when l wanted to use pytorch2onnx,py, l met an error reporting:NotImplementedError: [Adaptive pool]:input size not accessible.
The model l chose is swin.I only set config=configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py，checkpoint=swin99.pth，dynamic-export=True

**Comment by xiexinch** [comment]
Hi @RunningLeon, @zhouzaida,
Could you take a look at this issue if you're available?

**Comment by RunningLeon** [comment]
@dreamnever Pls. set `dynamic-export=False`. `adaptive pool` cannot be exported to ONNX with dynamic shape.
