### ISSUE TITLE
how does mmcv convert iterations to epochs?

### ISSUE THREAD

**Issue by sparshgarg23** [open-mmlab/mmsegmentation#1841]
When training hrnet we have the option of training for either 80K or 120,000K iterations on the cityscape dataset which has 2975/500/1525 train,val and test images.

As such how many epochs does it translate to,if I wanted to use an epoch based runner with a batch size of 8.

basically I am trying to understand the math behind conversion from iteration to epoch and vice versa.

**Comment by xiexinch** [comment]
Hi @sparshgarg23,
You might take a look at this issue #1683, hope it can help you.

**Comment by sparshgarg23** [comment]
hmm,#1683 actually tells us that we can change the runner to an epoch based runner if we want to use epochs.
I am more interested in looking at the calculations done .

For example in BDD100K if training has 70K images ,then with batch size 24 we get 2188 batches. Meaning that for each epoch 2188 iterations will be performed.Now if the training was done for say 10 epochs that amounts to 21,880 iterations.

 Now if we apply the same to an mmseg model like fastfcn which was trained for 80K iterations on cityscape with batch size set to 2,then this means the total number of epochs is 53?

**Comment by xiexinch** [comment]
We trained FastFCN with multi GPU, the epochs of these two models ([FastFCN + DeepLabV3](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/fastfcn/fastfcn_r50-d32_jpu_aspp_512x1024_80k_cityscapes.py), [FastFCN + DeepLabV3 (4x4)](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/fastfcn/fastfcn_r50-d32_jpu_aspp_4x4_512x1024_80k_cityscapes.py)) are 216 and 432 respectively, you might see [the training logs](https://download.openmmlab.com/mmsegmentation/v0.5/fastfcn/fastfcn_r50-d32_jpu_aspp_512x1024_80k_cityscapes/fastfcn_r50-d32_jpu_aspp_512x1024_80k_cityscapes_20210928_053722.log.json) for more infomation.
You might calculate the epochs by `Total iters / (num images / batch szie)`.

**Comment by sparshgarg23** [comment]
Thanks  ``` Total iters/(num images/batch size) ``` is what I was looking for exactly.
Since I trained on cityscape with 2 batch size ,then using your forumula the number of epochs comes out right
Thanks
