### ISSUE TITLE
How to get RGB result rather  Gray Image on ADE20k val set

### ISSUE THREAD

**Issue by HaoGuo98** [open-mmlab/mmsegmentation#1847]
how to get RGB Image rather  Gray Image on ADE20k val set?

**Comment by xiexinch** [comment]
Hi @HaoGuo98,
You might add `--show-dir` argument to the test command.
https://mmsegmentation.readthedocs.io/en/latest/inference.html#test-a-dataset

**Comment by HaoGuo98** [comment]
python tools/test.py configs/emanet/emanet_r101-d8_512x512_80k_ade20k.py work_dirs/emanet_r101-d8_512x512_80k_ade20k/iter_80000.pth 4 --show-dir ade_test 

I try to use this command but the picture cannot be saved.

**Comment by HaoGuo98** [comment]
Could you show me a  command which can generate  RGB results on val set of ADE20K?  Many thanks!

**Comment by xiexinch** [comment]
We specify in the document that `--show-dir` only supports the Single GPU test, you could try it again with a single GPU.
```shell
python tools/test.py configs/dnlnet/dnlnet_r101-d8_512x512_80k_ade20k.py work_dirs/dnl_ade.pth --show-dir ade_test
```

**Comment by HaoGuo98** [comment]
![image](https://user-images.githubusercontent.com/42510628/182361544-7f132ec8-b6b8-4b14-89ba-f42f2d4700e1.png)
the bar do not move.

**Comment by HaoGuo98** [comment]
Should i fix the warning?

**Comment by xiexinch** [comment]
> We specify in the document that `--show-dir` only supports the Single GPU test, you could try it again with a single GPU.
> 
> ```shell
> python tools/test.py configs/dnlnet/dnlnet_r101-d8_512x512_80k_ade20k.py work_dirs/dnl_ade.pth --show-dir ade_test
> ```

Hi @HaoGuo98,
Is that work?
