### ISSUE TITLE
What's the meaning of train annotations?

### ISSUE THREAD

**Issue by cunese24** [open-mmlab/mmsegmentation#1853]
Such as ADEData, the file of annotations includes some .png file, What do they present? 
if my annotations files just are txt, and just include the train png names,is that ok? i don't know the meaning and the use.

**Comment by xiexinch** [comment]
Hi @cunese24,
The annotation files are the training label. If you would like to use TXT files as the label, you need to customize a new Dataset Class.

**Comment by xiexinch** [comment]
For more information, please refer to the [documentation](https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_datasets.html#tutorial-2-customize-datasets).
