### ISSUE TITLE
how can I understand "for key in results.get('seg_fields', [])" in mmsegmentation/mmseg/datasets/pipelines/transforms.py 

### ISSUE THREAD

**Issue by ChengYuChuan** [open-mmlab/mmsegmentation#1855]
https://github.com/open-mmlab/mmsegmentation/blob/2d66179630035097dcae08ee958f60d4b5a7fcae/mmseg/datasets/pipelines/transforms.py#L286

```
for key in results.get('seg_fields', []):
            if self.keep_ratio:
                gt_seg = mmcv.imrescale(
                    results[key], results['scale'], interpolation='nearest')
            else:
                gt_seg = mmcv.imresize(
                    results[key], results['scale'], interpolation='nearest')
            results[key] = gt_seg
```

my understanding of results[key] is the label image or .pt file, am I right?
and what does it look like?

**Comment by xiexinch** [comment]
Hi @ChengYuChuan,
`results['seg_fields']` store the key for the label image.
https://github.com/open-mmlab/mmsegmentation/blob/4eaa8e69191cc293b64dafe47f1f88a7d468c93c/mmseg/datasets/pipelines/loading.py#L151

**Comment by ChengYuChuan** [comment]
got it. thanks
