### ISSUE TITLE
Error while trying to train custom dataset -__init__() error

### ISSUE THREAD

**Issue by cspearl** [open-mmlab/mmsegmentation#1857]
Hi, any help would be appreciated.
I am trying to train a custom dataset from scratch. I cloned the repo 2 days back and did the setup for custom datasets as was mentioned in docs. First model which I am trying to train is CCNet. But I am facing this error and am not being able to train at all - 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/content/drive/MyDrive/openmm/mmsegmentation/mmseg/datasets/amazon.py", line 21, in __init__
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'times'

**Comment by MeowZheng** [comment]
Would you mind proving the implementation of your dataset and the documentation link you referred to?

**Comment by MeowZheng** [comment]
I think you might print `kwargs` after `def __init__(self, **kwargs)` before `super` to check the `times` in `kwargs`

**Comment by cspearl** [comment]
> I think you might print `kwargs` after `def __init__(self, **kwargs)` before `super` to check the `times` in `kwargs`

{'times': 40000, ...} this gets printed as the first key-value pair of kwargs

**Comment by MeowZheng** [comment]
Do you use `RepeatDataet` in dataset config?
https://github.com/open-mmlab/mmsegmentation/blob/4eaa8e69191cc293b64dafe47f1f88a7d468c93c/mmseg/datasets/dataset_wrappers.py#L176

**Comment by cspearl** [comment]
> Do you use `RepeatDataet` in dataset config?
> 
> https://github.com/open-mmlab/mmsegmentation/blob/4eaa8e69191cc293b64dafe47f1f88a7d468c93c/mmseg/datasets/dataset_wrappers.py#L176

No I have not used RepeatDataset in config
My config is - 


dataset_type = 'AmazonDataset'
data_root = 'data/amazon'
  
img_norm_cfg = dict(
    mean=[101.951, 117.161, 62.96], std=[19.019, 11.592, 12.754], to_rgb=True)

img_scale = (512, 512)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=img_scale, ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        times=40000,
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            img_dir='img/train',
            ann_dir='label/train',
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='img/val',
        ann_dir='label/val',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='img/val',
        ann_dir='label/val',
        pipeline=test_pipeline))

**Comment by MeowZheng** [comment]
just remove `times=40000` from your config
```python
data = dict(
samples_per_gpu=2,
workers_per_gpu=2,
train=dict(
type=dataset_type,
times=40000,
...
```
