### ISSUE TITLE
colorful label

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#1858]
After mmseg reorganizes the vaihingen dataset with the command, the pictures in the annotation are all black. If I want to compare the prediction pictures with the label pictures, how can I get the label pictures with color

**Comment by MeowZheng** [comment]
Please check the label of prediction is all 0, as there are  `PALETTE` for this dataset, and label 0 is corresponding to [0, 0, 0] just black. 

https://github.com/open-mmlab/mmsegmentation/blob/4eaa8e69191cc293b64dafe47f1f88a7d468c93c/mmseg/datasets/isaid.py#L20-L29
