### ISSUE TITLE
How to add a new class to a pre-trained model?

### ISSUE THREAD

**Issue by abetancordelrosario** [open-mmlab/mmsegmentation#1859]
I would like to add a new class to a pre-trained model. How can I achieve it?.

I think the solution is transfer learning/fine-tune. In this case, how can I do it?.

The following link redirects to the model repository: https://github.com/wanghao9610/TMANet

**Comment by MeowZheng** [comment]
You might try to change `num_classes` in model cfg
ref: 
https://github.com/open-mmlab/mmsegmentation/blob/4eaa8e69191cc293b64dafe47f1f88a7d468c93c/configs/_base_/models/deeplabv3_r50-d8.py#L24
