### ISSUE TITLE
when I change the size of cityscapes to （4096，2048），ValueError: operands could not be broadcast together with shapes (2048,4096,3) (1024,2048,3) 

### ISSUE THREAD

**Issue by zhujiesuper** [open-mmlab/mmsegmentation#186]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when I change the size of cityscapes to （4096，2048），ValueError: operands could not be broadcast together with shapes (2048,4096,3) (1024,2048,3) ，but the size should not change，I use （4096，2048） to infer，but the seg result shape is （2048，1024）

**Reproduction**

1. What command or script did you run?

    ```none
    python tools/test.py configs/deeplabv3plus/deeplabv3plus_r50-d8_512x1024_40k_cityscapes.py checkpoints/deeplabv3plus_r50-d8_512x1024_40k_cityscapes_20200605_094610-d222ffcd.pth --show
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?
cityscapes
**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xvjiarui** [comment]
Hi @zhujiesuper 
Sorry for the late reply. 
Could you provide your config file for more details?
