### ISSUE TITLE
Have some questions about the structure?

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmsegmentation#1866]
pspnet_unet

Auxiliary_head The auxiliary decoding head uses fcn, but this will cause the structure parameters to be too large. Can the auxiliary decoding head use a lightweight method, such as changing to 8 times downsampling of movnetv2, and then replace decode_head=dict with movnetv2 16 times downsampling or 32 times downsampling, can you help me answer this question?

**Comment by xiexinch** [comment]
Sorry, I don't understand your question very well, could you describe it more clearly?
If your machine doesn't support training with an auxiliary head, you might remove it, it does not have a great impact on the final result
https://mmsegmentation.readthedocs.io/en/latest/faq.html#what-does-the-auxiliary-head-mean
