### ISSUE TITLE
How to use validation dataset to get the best model for the mmsegmentation.ipynb

### ISSUE THREAD

**Issue by Jinshan99** [open-mmlab/mmsegmentation#1867]
Hi, I want to save the best model with my own validation dataset, what could I change in the ipynb,, Thank you..

**Comment by xiexinch** [comment]
Hi @Jinshan99,
Might try `cfg.evaluation.save_best='mIoU'`.
#1650

**Comment by Jinshan99** [comment]
Hi, as I save the best, How can I find the model that I saved~~ Thank you!!

**Comment by Jinshan99** [comment]
It just said, Now best checkpoint is saved as best_mIoU_iter_200.pth. Where could I find the file,, Thank you~~

**Comment by Jinshan99** [comment]
Oh, I find it , Thank you~
