### ISSUE TITLE
About calculation of class weight 

### ISSUE THREAD

**Issue by LiShuiYu** [open-mmlab/mmsegmentation#187]
I don't understand how the document train trick calculates class weights for cityscape datasets. I saw a note saying it came from deeplab paper but I didn't find it in the original paper. Can someone tell me the specific formula?

**Comment by sumenpuyuan** [comment]
盲猜， 统计每个类别的像素个数， 然后取反？

**Comment by xvjiarui** [comment]
Hi @LiShuiYu 
It is used in the original Deeplab implementation. It may be the inverse of pixel number but I didn't check it. You may refer to official deeplab repo.
