### ISSUE TITLE
Following your descriptions, could you tell me how to turn off the Eval argument entirely when creating the .pkl result?

### ISSUE THREAD

**Issue by MIMIWAWA** [open-mmlab/mmsegmentation#1874]
Thank you for your marvelous work!

Following your descriptions, could you tell me how to turn off the Eval argument entirely when creating the .pkl result?

@dirtycomputer Did you turn off the Eval argument when you created the .pkl result? The result should be prediction results, not the evaluation metrics.

_Originally posted by @HJoonKwon in https://github.com/open-mmlab/mmsegmentation/issues/1301#issuecomment-1133828372_

Any help is appreciated.

**Comment by xiexinch** [comment]
Hi @MIMIWAWA,
You might remove the `--eval` argument.
https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html#confusion-matrix

**Comment by MIMIWAWA** [comment]
Thank you very mcuh for your reply~
