### ISSUE TITLE
what's  opacity？

### ISSUE THREAD

**Issue by cunese24** [open-mmlab/mmsegmentation#1876]
--opacity 1.0 
python tools/test.py ./configs/ocrnet/ocrnet_hr18.py \
 ocrnet_hr18.pth --show-dir work_dirs/ocrnet_hr18_mask --opacity 1.0；
what's opacity? I  could not find the intrudiction of opacity in CONFIG DOC, please help me,thanks!

**Comment by xiexinch** [comment]
Hi @cunese24,
It is a parameter for visualizing the opacity of the segmentation mask.
https://github.com/open-mmlab/mmsegmentation/blob/4eaa8e69191cc293b64dafe47f1f88a7d468c93c/mmseg/apis/inference.py#L121
