### ISSUE TITLE
How to fine-tune UNet + FCN using the provided pretrained model weights

### ISSUE THREAD

**Issue by soumya997** [open-mmlab/mmsegmentation#1878]
Hello,
Im trying to train the Unet+FCN model and finetune it using the provided model weight. For doing so, I changed the `pretrained` with the downloaded model weight file, but it is throwing error saying, 
```
2022-08-07 13:36:10,075 - mmseg - INFO - initialize UNet with init_cfg {'type': 'Pretrained', 'checkpoint': '/kaggle/working/checkpoints/fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive_20211210_201820-785de5c2.pth'}
2022-08-07 13:36:10,075 - mmcv - INFO - load model from: /kaggle/working/checkpoints/fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive_20211210_201820-785de5c2.pth
2022-08-07 13:36:10,076 - mmcv - INFO - load checkpoint from local path: /kaggle/working/checkpoints/fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive_20211210_201820-785de5c2.pth
2022-08-07 13:36:10,161 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: backbone.encoder.0.0.convs.0.conv.weight, backbone.encoder.0.0.convs.0.bn.weight, 

backbone.encoder.0.0.convs.0.bn.bias, backbone.encoder.0.0.convs.0.bn.running_mean, backbone.encoder.0.0.convs.0.bn.running_var, backbone.encoder.0.0.convs.0.bn.num_batches_tracked, 

backbone.encoder.0.0.convs.1.conv.weight, backbone.encoder.0.0.convs.1.bn.weight, backbone.encoder.0.0.convs.1.bn.bias, backbone.encoder.0.0.convs.1.bn.running_mean, backbone.encoder.0.0.convs.1.bn.running_var, 

backbone.encoder.0.0.convs.1.bn.num_batches_tracked, backbone.encoder.1.1.convs.0.conv.weight, backbone.encoder.1.1.convs.0.bn.weight, backbone.encoder.1.1.convs.0.bn.bias, backbone.encoder.1.1.convs.0.bn.running_mean, 

backbone.encoder.1.1.convs.0.bn.running_var, backbone.encoder.1.1.convs.0.bn.num_batches_tracked, backbone.encoder.1.1.convs.1.conv.weight, backbone.encoder.1.1.convs.1.bn.weight, backbone.encoder.1.1.convs.1.bn.bias, 

backbone.encoder.1.1.convs.1.bn.running_mean, backbone.encoder.1.1.convs.1.bn.running_var, backbone.encoder.1.1.convs.1.bn.num_batches_tracked, backbone.encoder.2.1.convs.0.conv.weight, backbone.encoder.2.1.convs.0.bn.weight,
```
The changes I did, by providing the model weight file path in the `pretrained` param

![sketchpad pro_A0A9CFC582395F0F43E](https://user-images.githubusercontent.com/54326088/183295512-e292c7cc-99d5-456b-9928-91c481c37574.png)

- Im not understanding what I need to do inorder to fine-tune the model [UNet + FCN], using the provided model wights [`fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive_20211210_201820-785de5c2.pth`].

- Is it fine to add the weight file [`fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive_20211210_201820-785de5c2.pth`] in the load_from parameter? Or do I need to do something additional.

- Is the  `pretrained` param for pretrained backbones, if yes then how do I specify the backbone? As it is mentioned, it is using the backbone = `UNet-S5-D16`?

cc: @MengzhangLI

**Comment by MengzhangLI** [comment]
(1) The error is caused by unmatched parameters in model and PTH file, please check the difference with your model and `fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive`. 

(2) It depends on your dataset, `fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive` is trained on DRIVE dataset which is blood vessels in retinal images, if your dataset is not that type, I suggest you train from scretch and enlarge iterations numbers.

(3) Yes, you can refer to `fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive` config file to check the backbone. `S5` means it has 5 stages feature maps and `d16` means size of smallest and largest feature map is 16 times. You could specify the backbone by changing prameters in [config file](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py#L10-L16).

**Comment by soumya997** [comment]
2. My data is related to functional tissue unit (FTU). Medical data related to different organs like lunga, kidny. You can see the dataset here, [HuBMAP+HPA](https://www.kaggle.com/competitions/hubmap-organ-segmentation/data). the data seems similar to the retina data. 
3. For adding the backbone can we do something similar to this? without changing the [config file](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py#L10-L16)

a. this
<img src="https://i.imgur.com/qkAq7id.png">

b. or this
<img src="https://i.imgur.com/13icE7i.png">

**Comment by xiexinch** [comment]
Hi @soumya997,
You might need to add `--load-from` argument to the training command, and no need to modify the configuration file, but the num_classes should be consistent with the checkpoint.
```shell
python tools/train.py configs/unet/fcn_unet_s5-d16_64x64_40k_drive.py --load-from checkpoints/fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive_20211210_201820-785de5c2.pth
```
