### ISSUE TITLE
iSAID

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#1879]
After downloading the Isaid data set, perform data set conversion according to the document, but the converted folder content is empty
![6](https://user-images.githubusercontent.com/89558994/183296135-156452ca-2d33-47d9-8c40-cfa0b9dc79bd.PNG)
![7](https://user-images.githubusercontent.com/89558994/183296314-40ecc011-4d15-4b3a-886d-061385051927.PNG)

**Comment by MengzhangLI** [comment]
Seems like the path is wrong, Win OS and Linux OS is different. `'D:/SCM/yg/is\\test\\images\\part1.zip` shows two OS path. Try to set `python tools/convert_datasets.py/isaid.py D:\SCM\yg\is`.

**Comment by scm-later** [comment]
> Seems like the path is wrong, Win OS and Linux OS is different. `'D:/SCM/yg/is\\test\\images\\part1.zip` shows two OS path. Try to set `python tools/convert_datasets.py/isaid.py D:\SCM\yg\is`.
截图是我在windows下的sh.exe中运行的，还是不可以

![3](https://user-images.githubusercontent.com/89558994/183320126-4ceb771a-178b-4056-ba28-0dc9a4579079.PNG)
并且我在windows直接使用terminal 下运行得到的文件夹依然是空

**Comment by scm-later** [comment]
> Seems like the path is wrong, Win OS and Linux OS is different. `'D:/SCM/yg/is\\test\\images\\part1.zip` shows two OS path. Try to set `python tools/convert_datasets.py/isaid.py D:\SCM\yg\is`.

截图是在windows下使用sh.exe运行的，路径应该没有问题，并且在windows下直接使用Terminal，得到的文件夹依然为空
![8](https://user-images.githubusercontent.com/89558994/183320970-66077420-67f0-4347-96a0-558e16145ea5.PNG)

**Comment by scm-later** [comment]
只需要下载DOTA-V1.0吗，DOTA-V2.0也要下载吗？
![捕获](https://user-images.githubusercontent.com/89558994/183322549-7a4b0dbf-c548-4d73-96a7-0ffd614e4b69.PNG)

**Comment by MengzhangLI** [comment]
Please use English or English & Chinese for wider discussion in community.

**Comment by MengzhangLI** [comment]
> 

Please read the [data preparation](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#prepare-datasets) first.

![image](https://user-images.githubusercontent.com/24582831/183335334-5b5d1a4b-2aa3-4443-a5db-b7ef05193cf3.png)
