### ISSUE TITLE
How to get the confusion matrix or the y_true and y_pred

### ISSUE THREAD

**Issue by Jinshan99** [open-mmlab/mmsegmentation#1880]
Hello, I want to build other metrics, so how could I get the y_true and y_pred from your train~~ Thank you

**Comment by xiexinch** [comment]
Hi @Jinshan99,
We provide a script to generate a confusion matrix.
https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html#confusion-matrix

**Comment by Jinshan99** [comment]
Hi, so how to get the result of the confusion matrix py~~,since I just get some metrics after the train_segmentor

**Comment by xiexinch** [comment]
Sorry, I'm not quite sure what your problem is. We have explained how to use this script in the [documentation](https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html#confusion-matrix). If you encounter bugs or other problems, please show the error message so that we can help you solve the problem.

**Comment by Jinshan99** [comment]
train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
                meta=dict())
from tools.confusion_matrix import calculate_confusion_matrix
calculate_confusion_matrix(datasets, results)

but --------------------------------------------------------------
NameError                           
----> 1 calculate_confusion_matrix(datasets, results)

NameError: name 'results' is not defined

**Comment by xiexinch** [comment]
Please read the [CONFUSION MATRIX](https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html#confusion-matrix) first.

1. Firstly, you might run the test script to generate prediction results. For example:
```shell
python tools/test.py configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py work_dirs/pspnet_r50-d8_512x512_20k_voc12aug/latest.pth --out results.pkl
```
2. Then, run the confusion_matirx.py script.
```shell
python tools/confusion_matrix.py configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py  results.pkl .
```
