### ISSUE TITLE
load beit pretrain model   'NoneType' object has no attribute 'interp2d'

### ISSUE THREAD

**Issue by haoxurt** [open-mmlab/mmsegmentation#1885]
Hi，I want to train beit by myself, so  I  excute  beit2mmseg.py  to get the pretrain model  for mmseg.  `python tools/model_converters/beit2mmseg.py https://conversationhub.blob.core.windows.net/beit-share-public/beit/beit_base_patch16_224_pt22k_ft22k.pth pretrain/beit_base_patch16_224_pt22k_ft22k.pth` I can excute beit2mmseg.py  successfully. However, when I can start train using the pretrain model  for mmseg, I ocuur the error.  `mmseg/models/backbones/beit.py", line 433, in _geometric_sequence_interpolation
    f = interpolate.interp2d(x, y, z, kind='cubic')
AttributeError: 'NoneType' object has no attribute 'interp2d'
`            Thanks!

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/beit.py#L21-L24

It needs scipy package.

**Comment by haoxurt** [comment]
Thanks.  I close.
