### ISSUE TITLE
Valid error

### ISSUE THREAD

**Issue by 22wei22** [open-mmlab/mmsegmentation#189]
I train network on deepfashion2 dataset and  the valid dataset has 32153 images. when validing, I find that memory utilization is very high. This error is produced. How can I valid when training?
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 32154/32153, 24.5 task/s, elapsed: 1311s, ETA:     0s/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/jovyan/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_40k_deepfashon2.py', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>.
jovyan@jupyter-qiuailuo-2d9807574:/data1/weihuan/segmentation/qiuailuo/mmsegmentation-master$ /opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by xvjiarui** [comment]
Hi @22wei22 
It seems your memory is not large enough. You may try non-distributed test.

**Comment by BboyHanat** [comment]
> Hi @22wei22
> It seems your memory is not large enough. You may try non-distributed test.

I don't know why it's encountered this warning and crushed during distributed training with samples_per_gpu=1(workers_per_gpu=1),  but It's work correctly on single gpu with  samples_per_gpu=8( workers_per_gpu=4).  Do you know about this phenomenon？ (my gpu machine memory is 64 G,   and free memory about 40 G before training ,   network is fcn_hrnet_18s ).
