### ISSUE TITLE
How to visiual loss and etc...?

### ISSUE THREAD

**Issue by cunese24** [open-mmlab/mmsegmentation#1890]
for example:
1. python tools/analyze_logs.py work-dirs/log.json --keys loss_cls --legend loss_cls --out work-dirs/losses.pdf
There is the loss_pdf but not concrete curve.
2. python tools/analyze_logs.py plot_curve work-dirs/log.json --keys loss_cls --legend loss_cls --out work-dirs/losses.pdf
REPORT####
Traceback (most recent call last):
  File "tools/analyze_logs.py", line 128, in <module>
    main()
  File "tools/analyze_logs.py", line 122, in main
    assert json_log.endswith('.json')
AssertionError

How to solve it?please help me,thanks!

**Comment by xiexinch** [comment]
Hi @cunese24,
You might try:
```shell
python tools/analyze_logs.py log.json --keys loss --legend loss_cls --out work_dirs/losses.pdf
```

**Comment by cunese24** [comment]
Thanks, Is there concretre introduction file of visual_logs? and i want to visual two or many different log.json files in one pdf_file,
if not, do i need to open the log.json files and  copy loss_numbers to visual software? I'm a xiaobai,maybe questions are stupid,haha. I'm sorry.qaq

**Comment by cunese24** [comment]
> Hi @cunese24, You might try:
> 
> ```shell
> python tools/analyze_logs.py log.json --keys loss --legend loss_cls --out work_dirs/losses.pdf
> ```

Thanks, Is there concretre introduction file of visual_logs? and i want to visual two or many different log.json files in one pdf_file,
if not, do i need to open the log.json files and copy loss_numbers to visual software? I'm a xiaobai,maybe questions are stupid,haha. I'm sorry.qaq

**Comment by xiexinch** [comment]
You might run with the following command:
```shell
python tools/analyze_logs.py log1.json log2.json --keys loss
```
And you might read our [documentation](https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html#plot-training-logs), it contains some basic introduction to visualizing logs, we'll refine it asap.
