### ISSUE TITLE
I want to add negative samples to the split samples, what kind of annotation style do I need

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmsegmentation#1891]
Filter out some special categories, mis-segmented pixels

**Comment by chen-del** [comment]
There are some similar categories, and pixel points are incorrectly segmented. Whether the dataloader of mmseg supports negative samples is the category that is all background.

**Comment by xiexinch** [comment]
Hi @chen-del,
If your data is more specific, you can customize a dataset. Please refer to the [documentation](https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_datasets.html#tutorial-2-customize-datasets).

**Comment by chen-del** [comment]
OK,thank you!
