### ISSUE TITLE
ONNX2Tensorrt Error

### ISSUE THREAD

**Issue by 22wei22** [open-mmlab/mmsegmentation#190]
I convert pytorch to onnx. It works fine. When I convert onnx to tensorrt, tensorrt Does not support resize layer with bilinear.
Do you meet the same problem?

**Comment by JPLAY0** [comment]
Because the latest tensortrt version only support onnx  opset version 7 but mmseg export version of onnx opset  version is set 11 https://github.com/onnx/onnx-tensorrt

**Comment by 22wei22** [comment]
@JPLAY0 Thanks.
Someone replace the resize layer with transpose convolution. Do you have some suggestions?

**Comment by JPLAY0** [comment]
> @JPLAY0 Thanks.
> Someone replace the resize layer with transpose convolution. Do you have some suggestions?

Modify operators that do not meet version requirements(opset 7).
