### ISSUE TITLE
How to choose loss?

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmsegmentation#1902]
Only one category is segmented, but there are too many pixels in the background category, and there are too few pixels in the category to be segmented. How to choose the appropriate loss at this time to solve the problem of sample imbalance?

**Comment by MeowZheng** [comment]
I think the simplest solution is to use `class_weights` in loss to reduce specific category effect

**Comment by chen-del** [comment]
@MeowZheng Hi, can I understand that in the class_weigt weight loss, the weight with more pixels should appropriately reduce the weight coefficient, and if there are fewer pixels, increase the weight coefficient, similar to this? Looking forward to your reply again!

**Comment by MeowZheng** [comment]
Yes you can
