### ISSUE TITLE
The acc_seg is high during the training, but the acc and miou in the evaluation are low

### ISSUE THREAD

**Issue by ladybirdhui** [open-mmlab/mmsegmentation#1904]
I still don't know the reason for this...
[794](https://github.com/open-mmlab/mmsegmentation/issues/794)'s problem is similar to mine. When I train my own dataset, the `decode.acc_seg` can reach more than 96%, but  mIoU and mAcc are only about 0.1% in evaluation .
<img width="1125" alt="截屏2022-08-10 12 38 48" src="https://user-images.githubusercontent.com/32413165/183817164-f9a30b18-3d1f-4f93-b8cb-57798ea3ded8.png">

here is my config 
<img width="458" alt="截屏2022-08-10 12 40 21" src="https://user-images.githubusercontent.com/32413165/183817266-d169f5dc-f667-4c24-bcd3-5a9b84f5c621.png">

There are four labels for my data. The background is the first, and `reduce_zero_label` is set to `False`
The value of the annotation picture is `0, 1, 2, 3`

**Comment by MeowZheng** [comment]
mIoU is not a percentage, is 0.1 or 10%, and mAcc is 82%.

**Comment by ladybirdhui** [comment]
> mIoU is not a percentage, is 0.1 or 10%, and mAcc is 82%.

Thank you. I didn't notice this. 
I think  `Acc` and `IoU` in  `per class results`  are both percentages, because  there are numbers(1.01 and 1.47)greater than one. If they are percentages, the value is much worse than the result in the training process.
The same dataset was used for training and validation.

**Comment by MeowZheng** [comment]
Sorry, I made a mistake, I have checked the code and there are percentages.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/datasets/custom.py#L441-L452

I think there might be test dataset is very different from train dataset, so `acc_seg` is much better than test dataset evaluation results.

**Comment by ladybirdhui** [comment]
I use the same dataset in tran and test...,>-<
So I am confused

>

**Comment by ladybirdhui** [comment]
I know what caused this mistake.
<img width="610" alt="截屏2022-08-12 14 42 44" src="https://user-images.githubusercontent.com/32413165/184299287-efca9c22-6aec-46ec-b27b-75e7dcf03a8d.png">
I used ada20 as my data configuration file, but did not remove `reduce_zero_label=True`
