### ISSUE TITLE
yapf.yapflib.verifier.InternalError

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#1907]
![PP2W@8WQ2` ROEYXR8Y8](https://user-images.githubusercontent.com/89558994/183847404-3129a09e-c722-4740-90a2-d860d23db25e.png)
![QFY1EVD O939@$5(0F5593J](https://user-images.githubusercontent.com/89558994/183847433-66918f27-25e0-42c3-857e-c6e73361e033.png)
how can I solve the problem

**Comment by MeowZheng** [comment]
chage `--work_dir` to `--work-dir`

**Comment by MeowZheng** [comment]
Could you provide the config and lanch command?

**Comment by scm-later** [comment]
> Could you provide the config and lanch command?
I change --work_dir to --work-dir,new error occurs,following are the config and dataset.py 
![MRU{N}U8{I3~9U9QPXXPIT7](https://user-images.githubusercontent.com/89558994/184290375-aedbd43b-9295-4288-aace-db46130081b7.png)
![VR`AW`TTR 9XHK2CMO2NF H](https://user-images.githubusercontent.com/89558994/184290587-a7c22c39-6e34-4935-9d75-c99cb77b4207.png)
![P`8IR)1U9F)A)7V$NGR1~$R](https://user-images.githubusercontent.com/89558994/184291378-40bba13d-26d4-424d-b749-0600e133ac47.png)

**Comment by xiexinch** [comment]
#1914 
#1916
