### ISSUE TITLE
How to get the predict label and the true labels after the training process

### ISSUE THREAD

**Issue by Jinshan99** [open-mmlab/mmsegmentation#1909]
Hello, after using train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
                meta=dict()), I could get the metrics results like 
aAcc: 0.9471, mIoU: 0.4736, mAcc: 0.5000, mFscore: 0.9728, mPrecision: 0.9471, mRecall: 0.5000, IoU.crack: 0.9471, IoU.non-crack: 0.0000, Acc.crack: 1.0000, Acc.non-crack: 0.0000, Fscore.crack: 0.9728, Fscore.non-crack: nan, Precision.crack: 0.9471, Precision.non-crack: nan, Recall.crack: 1.0000, Recall.non-crack: 0.0000

However, I want to get the predict label and the corresponding true label,, What could I do with it(I implemented it with the Jupiter notebook) Thank you!!!

**Comment by xiexinch** [comment]
Hi @Jinshan99,
1. You might run an evaluation to get the prediction results.
2. Might get ground truth from the dataset class.

**Comment by Jinshan99** [comment]
Hi, You might run an evaluation to get the prediction results. I have found the evaluation directory, but.. how to get the prediction results, I did not find a function to get the pred label results. And what do you mean by get from the dataset class... Thank you

**Comment by Jinshan99** [comment]
Is this function to get the predict label? Thank you!
def get_classes(dataset):
    """Get class names of a dataset."""
    alias2name = {}
    for name, aliases in dataset_aliases.items():
        for alias in aliases:
            alias2name[alias] = name

    if mmcv.is_str(dataset):
        if dataset in alias2name:
            labels = eval(alias2name[dataset] + '_classes()')
        else:
            raise ValueError(f'Unrecognized dataset: {dataset}')
    else:
        raise TypeError(f'dataset must a str, but got {type(dataset)}')
    return labels

**Comment by xiexinch** [comment]
Might evaluate a model by `single_gpu_test` or `multi_gpu_test` API
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/apis/test.py#L34
And if you would like to get the labels, might simply load the labels from files.
Or use your custom dataset class to get the info of each image.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/datasets/custom.py#L129

**Comment by Jinshan99** [comment]
Like I want to calculate TN, TP, FN, FP using the pred label and the true label~~~Thank you

**Comment by xiexinch** [comment]
I think the features we provide are more than enough for you to do this. Please refer to our [documentation](https://mmsegmentation.readthedocs.io/en/latest/api.html) for the use of the interfaces.

**Comment by Jinshan99** [comment]
Hi, I want to try this, but there is an error

from mmseg.datasets import build_dataloader
data_loaders = build_dataloader(datasets,samples_per_gpu=1, workers_per_gpu=4) 
mmseg.apis.single_gpu_test(model, data_loaders, show=False, out_dir=None, efficient_test=False, opacity=0.5, pre_eval=False, format_only=False, format_args={})


[                                                  ] 0/1, elapsed: 0s, ETA:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_101387/2122831278.py in <module>
     20 
     21 #data_loaders
---> 22 mmseg.apis.single_gpu_test(model, data_loaders, show=False, out_dir=None, efficient_test=False, opacity=0.5, pre_eval=False, format_only=False, format_args={})

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/MMsegmentation/mmseg/apis/test.py in single_gpu_test(model, data_loader, show, out_dir, efficient_test, opacity, pre_eval, format_only, format_args)
     87     loader_indices = data_loader.batch_sampler
     88 
---> 89     for batch_indices, data in zip(loader_indices, data_loader):
     90         with torch.no_grad():
     91             result = model(return_loss=False, **data)

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    650                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    651                 self._reset()  # type: ignore[call-arg]
--> 652             data = self._next_data()
    653             self._num_yielded += 1
    654             if self._dataset_kind == _DatasetKind.Iterable and \

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1345             else:
   1346                 del self._task_info[idx]
-> 1347                 return self._process_data(data)
   1348 
   1349     def _try_put_index(self):

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1371         self._try_put_index()
   1372         if isinstance(data, ExceptionWrapper):
-> 1373             data.reraise()
   1374         return data
   1375 

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    459             # instantiate since we don't know how to
    460             raise RuntimeError(msg) from None
--> 461         raise exception
    462 
    463 

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jinshan/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jinshan/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/jinshan/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 84, in collate
    return default_collate(batch)
  File "/home/jinshan/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 183, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class '__main__.CrackDataset'>

**Comment by Jinshan99** [comment]
Hi, sorry to disturbing, I also want to know how to use  self.img_infos = self.load_annotations(self.img_dir, self.img_suffix, ..) 
I write like this way:
from mmseg.datasets.custom import CustomDataset
t=TestDataset
t.load_annotations(img_dir_test,img_suffix='png',ann_dir_test, seg_map_suffix='png', split=None)

(TestDataset is built as
img_dir_test = 'TestingCracks'
ann_dir_test = 'TestingCracksGroundtruth'
#For test dataset
@DATASETS.register_module()
class TestDataset(CustomDataset):
    CLASSES = classes
    PALETTE = palette
    def __init__(self, **kwargs):# split,
        super().__init__(img_suffix='png', seg_map_suffix='png', 
                          **kwargs)#split=split,
        assert osp.exists(self.img_dir) #and self.split is not None)


However, I got the error  positional argument follows keyword argument.. How to use this to get true labels,, thank you

**Comment by Jinshan99** [comment]
After I change, it still   t.load_annotations(self.img_dir=img_dir_test,self.img_suffix='png',self.ann_dir=ann_dir_test, self.seg_map_suffix='png', self.split=None)
                      ^
SyntaxError: keyword can't be an expression

**Comment by xiexinch** [comment]
Hi @Jinshan99,


> After I change, it still t.load_annotations(self.img_dir=img_dir_test,self.img_suffix='png',self.ann_dir=ann_dir_test, self.seg_map_suffix='png', self.split=None) ^ SyntaxError: keyword can't be an expression

There may be some syntax errors in your code.
