### ISSUE TITLE
Log loss and metrics for the whole epoch for EpochBasedRunner

### ISSUE THREAD

**Issue by hssandriss** [open-mmlab/mmsegmentation#1912]
Hello, 

Great library, thanks alot!
I am using EpochBasedRunner but I am not getting loss and training metrics for the whole epoch. 
Is there a way to print only logs when epoch is finished or additionally print them after every epoch?
Thanks alot.

**Comment by xiexinch** [comment]
Hi @hssandriss,
If it is possible, please provide your config and your modified codes. I did the training with EpochBasedRunner and the logger works well.
