### ISSUE TITLE
:yapf.yapflib.verifier.InternalError

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#1916]
I download the latest version of the pre-trained models that you provide,but occurs this error:yapf.yapflib.verifier.InternalError: (unicode error) 'unicodeescape' 
![07KKT$ LQ$@)FEI_QY2H9U3](https://user-images.githubusercontent.com/89558994/184590932-de9cc503-67e8-4bdb-8074-ac7756a8296d.png)
![9O CSZKHFA9)K_6`0TF18FM](https://user-images.githubusercontent.com/89558994/184590959-3e61aec4-eb61-41ae-97d9-508cbb25006d.png)

_Originally posted by @scm-later in https://github.com/open-mmlab/mmsegmentation/issues/1914#issuecomment-1214687739_

**Comment by xiexinch** [comment]
Hi @scm-later,
Hi @scm-later,
I haven't encountered this problem yet, could you try to add `--work-dir` argument?
It would be good to provide the path to run the command. 
Ref: https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file

#1914

**Comment by scm-later** [comment]
thank you very much,add the --work-dir argument is OK

**Comment by scm-later** [comment]
thank you very much,add the --work-dir argument is OK
