### ISSUE TITLE
For Segformer, the number of layers at stage 2 for B1 and B2 is different from the one in the paper

### ISSUE THREAD

**Issue by cheul0518** [open-mmlab/mmsegmentation#1917]
The number of layers at stage 2 for B1 and B2 is **4** in the code here while it's **3** in the paper: [Table 6: Detailed settings of MiT series](https://arxiv.org/pdf/2105.15203.pdf) I'm wondering which one is correct? Thank you for your answer in advance.

**Comment by MeowZheng** [comment]
Would you like to tell us which **variable** is 3 of B1 and B2 in Table 6: Detailed settings of MiT series.

**Comment by cheul0518** [comment]
The variable L2 at stage 2 for B2 and B3 in the paper has different value compared to one in the codes. For example,  L1,**L2**,L3,L4 = [3,**3**,6,3] and [3,**3**,18,3] for B and B3 respectively in [Table6 excerpt from the the original paper](https://raw.githubusercontent.com/cheul0518/DeepLearning/main/1.png). But the number of layers in B2 is [3,**4**,6,3] in the codes: 1) [mit.py at 344line](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/mit.py#:~:text=num_layers%3D%5B3%2C%204%2C%206%2C%203%5D%2C), 2) [segformer_mit-b2_512x512_160k_ade20k.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py#:~:text=num_layers%3D%5B3%2C%204%2C%206%2C%203%5D), 3) [segformer_mit-b2_8x1_1024x1024_160k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b2_8x1_1024x1024_160k_cityscapes.py#:~:text=num_layers%3D%5B3%2C%204%2C%206%2C%203%5D). For B3, the number of layers is [3,**4**,18,3]: 1) [segformer_mit-b3_512x512_160k_ade20k.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b3_512x512_160k_ade20k.py#:~:text=num_layers%3D%5B3%2C%204%2C%2018%2C%203%5D), 2) [segformer_mit-b3_8x1_1024x1024_160k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b3_8x1_1024x1024_160k_cityscapes.py#:~:text=num_layers%3D%5B3%2C%204%2C%2018%2C%203%5D)). So I was wondering which value's actually correct. Hope it helps.

**Comment by MeowZheng** [comment]
I see. Many thanks for your report on the bug. We are working on fixing it.

@xiexinch please pay attention to this issue.

**Comment by cheul0518** [comment]
I thank for your hard work.

**Comment by xiexinch** [comment]
Hi @cheul0518,
The number of layers at stage 2 for B1 and B2 is 4 in [the official implementation](https://github.com/NVlabs/SegFormer) is 4.
https://github.com/NVlabs/SegFormer/blob/639caf64aad8241c670c3a6a820ab0a9bde02b77/mmseg/models/backbones/mix_transformer.py#L392
And their pre-trained model [PVT-V2](https://github.com/whai362/PVT/blob/c64d4edf023f1657c6067f7e591a76315fa26892/classification/pvt_v2.py#L352) also sets the number of layers at stage 2 to 4.

**Comment by cheul0518** [comment]
Hey @xiexinch , thank you very much for verifying the issue. I guess the article got the typo then.
