### ISSUE TITLE
ade20k evaluation without multiscaleflipaug

### ISSUE THREAD

**Issue by KimtaeHo3948** [open-mmlab/mmsegmentation#1919]
I'm experimenting with the ade20k dataset.
How do you process images when evaluating without multiscaleflipaug?
I think there are two ways.
1. resize(512, 512) -> normalization
2.rescale(512,512)->normalization->pad(512,512)

or other ? ,

**Comment by xiexinch** [comment]
Hi @KimtaeHo3948,
We process the images in the order of the `test_pipeline`. If the `--aug-test` argument is not added to the test command, the `random flip` will no longer take effect.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/configs/_base_/datasets/ade20k.py#L27

**Comment by KimtaeHo3948** [comment]
Hi, xiexinch 
Thank you. It seems that my question has not been conveyed properly. Again in detail.

When entering the model, the size of all inputs must be the same as 512x512.

So how do we process the image and mask to make the image 512X512 when evaluating?

When training, we do rescale(resize), random crop and padding to make it 512x512.

How do you make it 512x512 when evaluating? (Not using multiscalefilpaug.) because there is no crop, and padding in test_pipeline

![스크린샷 2022-08-16 오후 12 38 53](https://user-images.githubusercontent.com/93563329/184794126-5fe51ecf-8290-4bdd-a235-91253074b012.png)

**Comment by fingertap** [comment]
You can do it in a sliding window mode or just split the image into multiple 512x512 patches. That's controlled by the parameter `mode` in test_cfg. For example, [beit](https://github.com/open-mmlab/mmsegmentation/blob/98dfa1749bac0b5281502f4bb3832379da8feb8c/configs/beit/README.md#:~:text=Since%20relative%20position,multi%2Dscale%20inference%3A) use sliding window.

**Comment by KimtaeHo3948** [comment]
Hi @fingertap 
Thank you for answer.
I have a few more questions
1.How much stride should I give when inferance using a silding window? (I am using the ade20k dataset, and the random crop size was 512, 512 when training.)

2. When the original shape of the image is smaller than (512,512), is it padding and input to the model?

3. Is the code below correct using sliding window?
![스크린샷 2022-08-18 오후 1 14 57](https://user-images.githubusercontent.com/93563329/185293174-4dfa2502-16f7-4d31-b018-1f2c148a98de.png)

**Comment by fingertap** [comment]
Yes. You can find details in the source code.

**Comment by KimtaeHo3948** [comment]
Hi @fingertap 
Sorry for the many questions.
Can you tell me how much stride you give? (ade20k dataset, crop_size: 512x512)

**Comment by fingertap** [comment]
I always use the default setting. For example, DeepLabv3 seems to just split the image into 4 pieces and do evaluations for 4 times. That's why you will see two lines (the boundary of the four 512x512 patches) on the segmentation results.

**Comment by KimtaeHo3948** [comment]
thanks @fingertap  it helps a lot thank you
