### ISSUE TITLE
Is it possible to have multiple losses in one decoder head?

### ISSUE THREAD

**Issue by edizhuang** [open-mmlab/mmsegmentation#1925]
Hi,

Is it possible to have multiple losses in one decoder head? Could they be added as final loss for losses function to return?
For example in one decoder head file: 
```
loss = loss_1 + loss_2 #(for two different things)
return loss
```

By the way, when I read decode_head.py, does loss['acc_seg'] contribute to the learning process?

```
@force_fp32(apply_to=('seg_logit', ))
# def losses(self, seg_logit, seg_label):
def losses(self, output_1, seg_logit, seg_label):
    """Compute segmentation loss."""
    loss = dict()
    seg_logit = resize(
        input=seg_logit,
        size=seg_label.shape[2:],
        mode='bilinear',
        align_corners=self.align_corners)
    if self.sampler is not None:
        seg_weight = self.sampler.sample(seg_logit, seg_label)
    else:
        seg_weight = None
    seg_label = seg_label.squeeze(1)
    loss['loss_seg'] = self.loss_decode(
        seg_logit,
        seg_label,
        weight=seg_weight,
        ignore_index=self.ignore_index)
    loss['acc_seg'] = accuracy(seg_logit, seg_label)
    return loss
```

Thanks,

**Comment by MeowZheng** [comment]
You can use multiple losses like 
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/models/decode_heads/decode_head.py#L42-L43
loss['acc_seg']  doesn't contribute to training.

**Comment by xhlho** [comment]
> [mmsegmentation/mmseg/models/decode_heads/decode_head.py](https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/models/decode_heads/decode_head.py#L42-L43)

这种方式不知为何会产生报错：TypeError: __init__() got an unexpected keyword argument 'ignore_index'
