### ISSUE TITLE
Set interpolation for resize

### ISSUE THREAD

**Issue by LoadingBFX** [open-mmlab/mmsegmentation#1928]
How to set interpolation in train_pipeline? 

Since the Object in my dataset only has 1  pixel, the default interpolation for resize will loss most of info. is there any way to set interpolation to "area" in config file or what should I do to avoid the information losing ?  Thx!

img_scale = (512, 512)
crop_size = (64, 64)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=img_scale, ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]

**Comment by MeowZheng** [comment]
I suggest you add a new data transform what you need in https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/transforms.py
and make you own dataset config file.

Please refer this tutorial to understand and extend mmseg data transforms.
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/data_pipeline.md

**Comment by MeowZheng** [comment]
This issue is inactive for a long time, and I'll close it.
If anyone has any questions about it, just reopen it.
