### ISSUE TITLE
n channel image segmentation

### ISSUE THREAD

**Issue by MatthieuCMira** [open-mmlab/mmsegmentation#1934]
# scientific data are rarely RGB images but can vary from one to n band depending of the data. Implementing some flexibility to the models could be of a great use and open the library to the scientific community

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. scientific data are rarely RGB - flexibility is needed in the models

**Additional context**
I see three steps to implement this:
1/ change the data augmentation to allow nchannel images (using scipy.ndimage as backend?)
2/ change the first option of the model to let the user choose the number of channel (in the models and cfg file)
3/ add a "forgiving_state_restore" to upload the weights of the models

I am not familiar with this directory yet, maybe I'm forgetting an important point?

Have a good day,

M.

**Comment by MeowZheng** [comment]
I think these steps are completed enough.
