### ISSUE TITLE
Unexpected key in source state_dict when adding convolution in decoder

### ISSUE THREAD

**Issue by edizhuang** [open-mmlab/mmsegmentation#1935]
Hi,

During testing, I have "unexpected key in source state_dict" when adding extra convolution in uper_head decoder for Swin Transformer. Only the added keys are unexpected.

Do you have any idea why this happens? Training and validation is fine, only for testing with tools/test.py.

Thanks,

**Comment by xiexinch** [comment]
Hi @edizhuang,
This means that the training model and the test model are not the same, you could check if the config is the same.
And you could build a model from your config, and load your checkpoint by MMCV or PyTorch, then compare the keys to the two state_dict.

**Comment by edizhuang** [comment]
Hi,

I use the same config file. I only add convolution in the decoder. It seems that the original decoder can be memorized.

And I even have a model for more image channels (6)  instead of RGB (3), training and validation works, during testing, it says copying a param with shape torch.Size([96, 6, 4, 4]) from checkpoint, the shape in current model is torch.Size([96, 3, 4, 4]).

Is there any thing that memorizes the original model (encoder)? However, for decoder I don't think it could.

Thanks,
