### ISSUE TITLE
what does the "R-101-D16-MG124" in "DeepLabV3+   Backbone:R-101-D16-MG124" model mean?especially "R" "D" "MG"

### ISSUE THREAD

**Issue by HIT-Wang** [open-mmlab/mmsegmentation#1936]

**Comment by xiexinch** [comment]
Hi @HIT-Wang,
`R` means ResNet.
`D` and `MG` might be found at the bottom of the [README](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3plus).

**Comment by HIT-Wang** [comment]
> 你好@HIT-Wang, `R`表示 ResNet。 `D`并且`MG`可能在[README](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3plus)的底部找到。

thank you^o^
