### ISSUE TITLE
Two losses for one auxiliary decoder in config

### ISSUE THREAD

**Issue by edizhuang** [open-mmlab/mmsegmentation#1937]
Hi,

I see it is possible to have two losses for one auxiliary decoder in config, such as this for STDCHead:
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/stdc.py

I want to use it for customization. How these losses work? Separately on the decoder or sequentially?

Thanks,

**Comment by xiexinch** [comment]
Hi, @edizhuang,
You might read the source codes. Loss of auxiliary head only works for the auxiliary head, they will be calculated in the order of the list.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/models/segmentors/encoder_decoder.py#L147
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/models/decode_heads/decode_head.py#L232
