### ISSUE TITLE
Add multiple decoders

### ISSUE THREAD

**Issue by chengguanjun** [open-mmlab/mmsegmentation#1939]
Hello! I want to add decoders in parallel in my code. How do I do that? Looking forward to your reply!

**Comment by xiexinch** [comment]
Hi @chengguanjun,
If the additional decoders are not auxiliary heads, it might need to modify the source code of the [EncoderDecoder](https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/models/segmentors/encoder_decoder.py#L47) class or rewrite a new architecture based on the [BaseSegmentor](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/base.py#L13).

**Comment by chengguanjun** [comment]
@xiexinch Thank you for your reply! I read the other replies and found that auxiliary head is a deep supervision trick to improve the accuracy. Can it be modified according to my requirements? After all, it's hard for me to rewrite a new structure.

**Comment by xiexinch** [comment]
Hi @chengguanjun,
I'm not quite sure what your requirements are, could you describe them in detail?
The auxiliary heads might help to improve the performance, they're trained with a decoder in parallel. You might take a look at our [document](https://mmsegmentation.readthedocs.io/en/latest/faq.html#what-does-the-auxiliary-head-mean).

**Comment by chengguanjun** [comment]
@xiexinch Thank you for your reply! I have looked at the document, and I probably understand. Thank you very much!
