### ISSUE TITLE
What is the lable mapping for Pascal Context?

### ISSUE THREAD

**Issue by XavierCHEN34** [open-mmlab/mmsegmentation#1940]
I follow your step to process pascal context dataset using Details API. 
I got the PNGs for the masks, however, I find that the labels in the mask seem different from the labels given in 
https://cs.stanford.edu/~roozbeh/pascal-context/59_labels.txt

for example, for the following mask

![image](https://user-images.githubusercontent.com/32154409/185589707-f3dfbcff-9d57-4e2d-849c-7448811528a4.png)

```
image_path = './data/Pascal/VOCdevkit/VOC2010/SegmentationClassContext/2008_000002.png'
image = cv2.imread(image_path)
print(image.shape)
print(np.unique(image))
```

the result is   [ 0 55 58], which corresponds to 55: truck  58: window.  

So what are the mappings between indexes and names?

**Comment by xiexinch** [comment]
Hi @XavierCHEN34,
The index of the name corresponds to the index of this list.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/datasets/pascal_context.py#L70
