### ISSUE TITLE
default evaluation    sliding window vs whole image inference   , 

### ISSUE THREAD

**Issue by KimtaeHo3948** [open-mmlab/mmsegmentation#1943]
Hi i have two question

1.Which one is the default?       sliding window or whole image inference?

2. What is the default stride when using sliding window? 
i've been trained with size 512, 512  so what value should i choose for test_cfg.stride

**Comment by xiexinch** [comment]
Hi @KimtaeHo3948,
1. It has no default value, you must specify one.
2. There is also no default value for the stride, you need to do your own calculations and design.
