### ISSUE TITLE
How to set class weights in order to handle class imbalance?

### ISSUE THREAD

**Issue by cheul0518** [open-mmlab/mmsegmentation#1944]
I've developed a semantic segmentation model that segments 6 different classes including background while in most sample images the background is 90+%. So I tried to implement [class balanced loss](https://mmsegmentation.readthedocs.io/en/latest/tutorials/training_tricks.html#class-balanced-loss) but I have no idea how to compute the class weight for each class. My sample images are like sample1: (90% of class0(background), 10% of class1), sample2: (95% of class0, 5% of class2), sample3: (85% of class0, 15% of class3), and so on. That is, every sample has at most 2 classes (few times background so 1 class only). Can you give me an insight about how to set each class weight for each class in this scenario? And can you suggest other methods to solve class imbalnace? By the way, I'm developing Segformer to segment medical images.

**Comment by xiexinch** [comment]
Hi @cheul0518,
I found a similar discussion on imbalance data, just replace the numbers of samples with the number of pixels.
https://discuss.pytorch.org/t/how-to-calculate-class-weights-for-imbalanced-data/145299
Or might try to use the `Focal Loss`. Ref: https://arxiv.org/pdf/1708.02002.pdf
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/models/losses/focal_loss.py#L137

**Comment by cheul0518** [comment]
@xiexinch Thank you so much for your help!
