### ISSUE TITLE
How to train on unbalanced multi gpu?

### ISSUE THREAD

**Issue by yuanyuangoo** [open-mmlab/mmsegmentation#1946]
Hi, I am doing some training on my computer with two different GPUs, one GPU has 6G ram, and another has 12 G. When I use your training script, it only uses 6G of ram in each GPU, which is slow. Is there anyway that I can use the full capacity of the both GPUs by allocating the different amounts of data on these GPUs?

![Screenshot from 2022-08-22 08-18-54](https://user-images.githubusercontent.com/12264695/185809375-49df410d-d745-40b4-8498-5d3448d6806f.png)
?

**Comment by xiexinch** [comment]
Hi @yuanyuangoo,
We use the `torch.nn.parallel.DistributedDataParallel` API as the underlying interface, you might read their [documentation](https://pytorch.org/docs/stable/notes/ddp.html#internal-design), the model is the same on every GPU, so your requirements might be difficult to implement.

**Comment by yuanyuangoo** [comment]
Thanks.
