### ISSUE TITLE
How the final output is converted to full resolution mask? [SegFormer]

### ISSUE THREAD

**Issue by working12** [open-mmlab/mmsegmentation#1947]
If the input is `HxWx3` (RGB Image) the output is `(H/4 x W/4 x num_classes)`. But the ground truth mask is `(H,W,num_classes)`. Can you point out the code where this is being done? I am unable to locate that portion after reading the code multiple times.

**Comment by xiexinch** [comment]
Hi @working12,
Might found it at `decode_head.py`.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/models/decode_heads/decode_head.py#L235
