### ISSUE TITLE
How to use another optimizer? (Two Optimizer)

### ISSUE THREAD

**Issue by hello451** [open-mmlab/mmsegmentation#195]
Hi, Thanks for this great codebase.

I meet a problem that how to construct two optimizers? (each optimizer optimize different parameters).
I have check the docs but didn't find the answer.

Thanks a lot for your help

**Comment by hello451** [comment]
I only can find some comments in 'base_runner.py', however, I try to construct a dic containing two optimizers in config file but got the wrong. Could you please tell me how to build 2 optimizers? Or give me a simple template? Thanks a lot.

**Comment by xvjiarui** [comment]
Hi @hello451 
It is not supported or tested in MMSegmentation yet. While [MMEditing](https://github.com/open-mmlab/mmediting) could handle multiple optimizers with similar architecture. You may refer to MMEditing for examples.
