### ISSUE TITLE
Is the checkpoint file in a Segformer architecture automatically downloaded ?

### ISSUE THREAD

**Issue by cheul0518** [open-mmlab/mmsegmentation#1954]
After training, [the checkpoint](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py#:~:text=%27https%3A//download.openmmlab.com/mmsegmentation/v0.5/pretrain/segformer/mit_b2_20220624%2D66e8bf70.pth%27) wasn't downloaded because my storage capacity remained unchanged. So I manually downloaded [the checkpoint](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py#:~:text=https%3A//download.openmmlab.com/mmsegmentation/v0.5/pretrain/segformer/mit_b2_20220624%2D66e8bf70.pth) and added it by doing ```cfs.load_from = mit_b2_20220624-66e8bf70.pth```. When I started the training, I got the error: ``` mmseg - WARNING - The model and loaded state dict do not match exactly``` because of different ```num_classes```. The training's running but I'm not sure if this is correct. Can you enlighten me?

PS segformers are all pretrained with Imagenet-1K? If not, how can I pretrain it?

**Comment by xiexinch** [comment]
Hi @cheul0518,
We usually use the pre-trained models, they will be downloading to `~/.cache/torch/hub/checkpoints` by default, and no need to set `load_from`.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/configs/segformer/segformer_mit-b2_8x1_1024x1024_160k_cityscapes.py#L3

**Comment by cheul0518** [comment]
@xiexinch  I see. Thank you!
