### ISSUE TITLE
Whats the difference between 'ignore_index = 0' and 'reduce_zero_label=True'?

### ISSUE THREAD

**Issue by cheul0518** [open-mmlab/mmsegmentation#1955]
```ignore_index=0``` ignores zero label(=index 0) in evaluation, and ```reduce_zero_label=True``` ignores zero label as well.  They both normally appear as arguments at the same time. For example, class mmseg.datasets.CustomDataset has arguments of (ignore_index, reduce_zero_label). So I'm confused when I try to exclude label 0. Is there any difference between them?

**Comment by xiexinch** [comment]
Hi @cheul0518,
Might take a look at this issue #932.

**Comment by cheul0518** [comment]
@xiexinch  Thank you very much
