### ISSUE TITLE
Can input multiple images?

### ISSUE THREAD

**Issue by DotWang** [open-mmlab/mmsegmentation#1959]
Hello, I would like to input multiple images into the network at the same time, like this:

```
    for i, (input1, input2, target) in enumerate(train_loader):

        input1 = input1.cuda()
        input2 = input1.cuda()
        target = target.cuda()

        output = model.forward(input1, input2)

        loss = criterion(output, target)
        ....
```
However, I cannot find similar operations in the mmseg, can you help me?

**Comment by xiexinch** [comment]
Hi @DotWang,
We first set batch size at the `build_dataloader` function.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/datasets/builder.py#L150

Then, load batch images by `MMCV`.
https://github.com/open-mmlab/mmcv/blob/a08517790d26f8761910cac47ce8098faac7b627/mmcv/runner/iter_based_runner.py#L61

If you want to input multiple images into the network, should customize the `__getitem__` method of your `Dataset`.
https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/mmseg/datasets/custom.py#L201

**Comment by DotWang** [comment]
OK, I see, thank you very much!
