### ISSUE TITLE
Unstable tools/confusion_matrix.py 

### ISSUE THREAD

**Issue by TimoK93** [open-mmlab/mmsegmentation#1969]
Hello,

there is an instability in  https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/tools/confusion_matrix.py when there are too many classes or an high ignore-value like 255. For example, with the **Cityscapes** dataset the confusion matrix has invalid and strange values which destroys the final confusion matrix visualization.

https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/tools/confusion_matrix.py#L46-L65

In line 59 the matrix *gt_segm* can be dtype np.uint8 which allows values up to 255. Thus, only 16 classes are allowed. If you have more classes, there are random values in the resulting array *inds* in line 60. Also ignore values == 255 cause errors. I have a fix suggestion attached to the end of this issue.

Hope this helps!
Best,
Timo

**Reproduction**

To reproduce, calculate the confusion matrix with 

   ```shell
python tools/test.py ./configs/deeplabv3plus/deeplabv3plus_r50b-d8_512x1024_80k_cityscapes.py SOMEPATH/deeplabv3plus_r50b-d8_512x1024_80k_cityscapes_20201225_213645-a97e4e43.pth --out ./results.pkl

python tools/confusion_matrix.py ./configs/deeplabv3plus/deeplabv3plus_r50b-d8_512x1024_80k_cityscapes.py ./results.pkl ./
   ```
with the dataset **Cityscapes**.

**Bug fix suggestion**

```python
def calculate_confusion_matrix(dataset, results):
    """Calculate the confusion matrix.

    Args:
        dataset (Dataset): Test or val dataset.
        results (list[ndarray]): A list of segmentation results in each image.
    """
    n = len(dataset.CLASSES)
    confusion_matrix = np.zeros(shape=[n, n])
    assert len(dataset) == len(results)
    ignore_index = dataset.ignore_index
    prog_bar = mmcv.ProgressBar(len(results))
    for idx, per_img_res in enumerate(results):
        res_segm = per_img_res
        gt_segm = dataset.get_gt_seg_map_by_idx(idx).astype(int)
        gt_segm, res_segm = gt_segm.flatten(), res_segm.flatten()
        to_ignore = gt_segm == ignore_index
        gt_segm, res_segm = gt_segm[~to_ignore], res_segm[~to_ignore]
        inds = n * gt_segm + res_segm
        mat = np.bincount(inds, minlength=n**2).reshape(n, n)
        confusion_matrix += mat
        prog_bar.update()
    return confusion_matrix
```

**Comment by MeowZheng** [comment]
Many thanks for your kind reminder, but I have a little question. Why are only 16 classes allowed, when gt_segm's range is [0,255)?

**Comment by TimoK93** [comment]
Hey MeowZheng,

have a look here:
 https://github.com/open-mmlab/mmsegmentation/blob/dd42fa8d0125632371a41a87c20485494c973535/tools/confusion_matrix.py#L60
*n* is the number of classes and in *gt_segm* there are values out of *[0, ..., n, ignore_value]*. Assume you have 20 classes. Then *n x gt_segm* can have values 20*20=400 > 255 which leads to problems if dtype is uint8. The resulting value in inds will not be 400 but 400%255=145 which is not making sense. Thus, if you create a confusion matrix for Cityscapes with a pretrained model, some rows have nan values.  

Does this help?
Best,
Timo

**Comment by MeowZheng** [comment]
Thanks for your explanation. Based on my experience, data type will convert to int64 from int8 when the data is out of range [0, 255). However, converting data type explicitly is better, so please create a pr to fix it. Thanks again
