### ISSUE TITLE
Add the funtion to plot training and val logs like analyze_logs.py in mmdetection 

### ISSUE THREAD

**Issue by caodroid** [open-mmlab/mmsegmentation#197]
# Describe the feature
hope the the funtion to plot curve of training and val logs will be implement in mmsegmentation, it is really important to visualize the logs. thank you! 
**Motivation**
A clear and concise description of the motivation of the feature.
In the evaluation of  the trained model , the  training and val logs , like loss, acc, mIoU, is important and persuasive, if the logs could be visualized ,it will help users to get a more conprehensive understanding of the performence of their models.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful. 
the code is implemented as analyze_logs.py in mmdetection in your another toolkit, hope it will be implement in mmsegmentation. thank you.  [https://github.com/open-mmlab/mmdetection/blob/master/tools/analyze_logs.py](url)

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by xvjiarui** [comment]
Hi @caodroid 
We may add it in the next release. You are also welcome to create a PR to add it.
