### ISSUE TITLE
how to use beit  to train if the input size is 768x768

### ISSUE THREAD

**Issue by haoxurt** [open-mmlab/mmsegmentation#1973]
I want to use beit train ade20k  with input size 768 x 768，can I only change the input size according to official configs?  Do I need to change anything else？

**Comment by fingertap** [comment]
Hi @haoxurt ! I have a few questions on this training configs:

- Will training with 768x768 lead to large performance gain? 
- Which paper uses 768x768 as input?
- What is the memory consumption of 768x768 inputs on ADE20k?

Thanks!

**Comment by haoxurt** [comment]
There is  no  paper using 768x768 as input.  I only want to try.  I have A100 GPU  with 40G memory and  it can train with 768x768 .

**Comment by fingertap** [comment]
> There is no paper using 768x768 as input. I only want to try. I have A100 GPU with 40G memory and it can train with 768x768 .

Can you please record the memory usage for a single GPU when you start to train? I wonder whether my 3090 (24G) can handle 768x768 inputs. Thanks!

**Comment by haoxurt** [comment]
3090(24G) can’t train.  It need 39.6G .

**Comment by fingertap** [comment]
Thanks!

**Comment by xiexinch** [comment]
Hi @haoxurt,
Might modify the crop size like https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/ade20k_640x640.py.
