### ISSUE TITLE
Using swin transformer with arbitrary sizes

### ISSUE THREAD

**Issue by shengyi4** [open-mmlab/mmsegmentation#1979]
Hi,

My customer dataset has arbitrary sizes from 500*700-4608*3456(train and test). I used default upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K.py to train and test my data, but I only got 1.56 mIoU on it. I wonder if there is any set up I should config for my datasets? 

Thanks！

**Comment by xiexinch** [comment]
Hi @shengyi4,
I think you could try to crop the picture yourself with roughly the same size or check to see if there is a problem with the training configuration.

**Comment by shengyi4** [comment]
Thanks for your reply! I really appreciate it. I just followed
upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py

without changing the training part, (just changed dataset, number of class). Will it cause any problems? Thanks!

On Aug 31, 2022, at 3:22 AM, 谢昕辰 ***@***.***> wrote:

﻿

Hi @shengyi4<https://urldefense.com/v3/__https://github.com/shengyi4__;!!DZ3fjg!759vLkve2mvMZviLwVSb2Dwzt3UjuiXxOQE1QIdYLncricSvHHs04ZtU3q6z--IUKAbLB66dhsuv_KzA9HP_z4ChMTkH$>,
I think you could try to crop the picture yourself with roughly the same size or check to see if there is a problem with the training configuration.
