### ISSUE TITLE
Constant IoU of classes after every validation

### ISSUE THREAD

**Issue by cspearl** [open-mmlab/mmsegmentation#1988]
Hi, 
So I was training a few models on my custom dataset. At first it was working fine, but then all of a sudden it started showing a constant IoU of 95.51 for Background and 0.0 for class1 (binary segmentation) even after training for 20k/40k iterations. And thereafter it was the same for other models as well. 
Any help will be appreciated.

**Comment by MengzhangLI** [comment]
Could you attach your detailed `.log` file in training? Thanks in advance!

**Comment by cspearl** [comment]
> Could you attach your detailed `.log` file in training? Thanks in advance!

Hey sorry for the late response
Here is the log file attached. Please let me know what can be done. Thanks!
[20220907_100757.log](https://github.com/open-mmlab/mmsegmentation/files/9505835/20220907_100757.log)
