### ISSUE TITLE
what is pre eval?

### ISSUE THREAD

**Issue by KimtaeHo3948** [open-mmlab/mmsegmentation#1989]
![스크린샷 2022-08-29 오후 4 04 12](https://user-images.githubusercontent.com/93563329/187143241-a1a02851-d015-4951-99fa-81169e71564e.png)
Hi what is pre eval and interval?   

Are you averaging all validation data when writing the results? (In case of ade20k, is the miou calculated and averaged for the data in 2000 images?
![스크린샷 2022-08-29 오후 4 05 42](https://user-images.githubusercontent.com/93563329/187143611-92c0abb0-749d-48e9-8d7e-d67a63609a92.png)
)
Is the miou in the picture the result of 2000 vaildation images?

i used pretrained model from mmsegmentation (upernet -resnet101 -80k) but its miou is 39 not 42 , i don't understand evaluation. check the below img  
![스크린샷 2022-08-29 오후 9 20 27](https://user-images.githubusercontent.com/93563329/187200755-097527fb-dd82-47b7-94fd-e3b8fd37851d.png)

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/eval_hooks.py#L20-L21
```python
pre_eval (bool): Whether to use progressive mode to evaluate model.
    Default: False.
```

`interval` is interval of evaluation in training. For example, if `interval=8000`, each 8000 iteration the training process would do an evaluation. The validation dataset depends on your config file, default it is validation dataset in ADE20K dataset: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/ade20k.py#L43-L48.

I suggest you use IDE(such as PyCharm) to debug training/inference which would help you understanding in the future.

Best,

**Comment by ubun23** [comment]
Hi, Thanks for your wonderful work! But I still don't understand "pre_eval" and "progressive mode to evaluate model." Can you explain this in more detail.
