### ISSUE TITLE
Add a new loss, KeyError: 'MyLoss is not in the loss registry'

### ISSUE THREAD

**Issue by DreamerWangDr** [open-mmlab/mmsegmentation#199]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I want to add a new loss (Dice loss), I did as  'https://mmsegmentation.readthedocs.io/en/latest/tutorials/new_modules.html#add-new-loss' descriped, but when I train the module. A KeyError reported: 'MyLoss is not in the loss registry'.  I don't kown where the wrong is.
**Reproduction**

1. What command or script did you run?

    ```none
    A placeholder for the command.
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xvjiarui** [comment]
Hi @DreamerWangDr 
As [doc](https://mmsegmentation.readthedocs.io/en/latest/tutorials/new_modules.html#add-new-loss) stated, you should do following 
```
from .my_loss import MyLoss, my_loss
```

**Comment by DreamerWangDr** [comment]
> Hi @DreamerWangDr
> As [doc](https://mmsegmentation.readthedocs.io/en/latest/tutorials/new_modules.html#add-new-loss) stated, you should do following
> 
> ```
> from .my_loss import MyLoss, my_loss
> ``` in `mmseg/models/losses/__init__.py`.
> ```
Thanks, I have add " from .my_loss import MyLoss, my_loss" to  mmseg/models/losses/__init__.py.
But, there is no diffrence,  still KeyError: 'MyLoss is not in the loss registry'.
And, my environment is google colab.

**Comment by xvjiarui** [comment]
You may need to re-install after modification or you could install in dev mode.

**Comment by DreamerWangDr** [comment]
> You may need to re-install after modification or you could install in dev mode.

Thanks,  I don't understand you very much. Which package should i reinstall? MMcv or MMsegmentation?
If I reinstall after modification, is my modification still valid ?  Will my_loss.py disappear?

**Comment by xvjiarui** [comment]
You may try this `pip install -e .  # or "python setup.py develop"`.

**Comment by DreamerWangDr** [comment]
> You may try this `pip install -e . # or "python setup.py develop"` to install MMSeg.

Thanks,
I tried all these on MMsegementation colab Tutorial,
1,I tried '!pip install -e .' and '!python setup.py develop' as below:
`!rm -rf mmsegmentation
!git clone https://github.com/open-mmlab/mmsegmentation.git 
%cd mmsegmentation
#!pip install -e .
!python setup.py develop`
2,I add 'from .my_loss import MyLoss, my_loss' to '__init__.py' as below:
`from .my_loss import MyLoss, my_loss
from .accuracy import Accuracy, accuracy
from .cross_entropy_loss import (CrossEntropyLoss, binary_cross_entropy,
                                 cross_entropy, mask_cross_entropy)
from .utils import reduce_loss, weight_reduce_loss, weighted_loss

__all__ = [
    'accuracy', 'Accuracy', 'cross_entropy', 'binary_cross_entropy',
    'mask_cross_entropy', 'CrossEntropyLoss', 'reduce_loss',
    'weight_reduce_loss', 'weighted_loss', 'MyLoss', 'my_loss'
]
`
3,I changed loss_xxx field as below:
`cfg.model.decode_head.loss_decode=dict(type='MyLoss',loss_weight=1.0)
cfg.model.auxiliary_head.loss_decode=dict(type='MyLoss', loss_weight=0.4)`

Still KeyError: 'MyLoss is not in the loss registry'
Now, I give up.

**Comment by DreamerWangDr** [comment]
> You may try this `pip install -e . # or "python setup.py develop"` to install MMSeg.

I really don't know where my wrong is. If you have time, can you show me a correct example to add a new loss ? Or, could you test adding a new loss on MMsegmentation colab tutorial ? 
Thanks a lot.

**Comment by DreamerWangDr** [comment]
> > You may try this `pip install -e . # or "python setup.py develop"` to install MMSeg.
> 
> I really don't know where my wrong is. If you have time, can you show me a correct example to add a new loss ? Or, could you test adding a new loss on MMsegmentation colab tutorial ?
> Thanks a lot.

After i relaod the MMseg module,  KeyError: 'MyLoss is not in the loss registry' disappered.

**Comment by lmunan** [comment]
I want to know how dice loss is added, can you send me the dice loss file @DreamerWangDr

**Comment by dzyjjpy** [comment]
> > > You may try this `pip install -e . # or "python setup.py develop"` to install MMSeg.
> > 
> > 
> > I really don't know where my wrong is. If you have time, can you show me a correct example to add a new loss ? Or, could you test adding a new loss on MMsegmentation colab tutorial ?
> > Thanks a lot.
> 
> After i relaod the MMseg module, KeyError: 'MyLoss is not in the loss registry' disappered.
could you pls share how you reload the mmseg module???
