### ISSUE TITLE
What's the difference between 'load_from' and 'resume_from' in configs?

### ISSUE THREAD

**Issue by orangeccc** [open-mmlab/mmsegmentation#200]
in [docs](https://mmsegmentation.readthedocs.io/en/latest/config.html), I found
```
load_from = None  # load models as a pre-trained model from a given path. This will not resume training.
resume_from = None  # Resume checkpoints from a given path, the training will be resumed from the iteration when the checkpoint's is saved.
```
but still not sure which one I should use.

**Comment by xvjiarui** [comment]
Hi @orangeccc 
When training is interrupted somehow, `resume_from` should be used to resume training. 
If you are using some checkpoint as pretrain, you should use `load_from`.

**Comment by orangeccc** [comment]
got it, thanks !

**Comment by wanghao9610** [comment]
Hi @xvjiarui 
Will the performance drop dramatically when resume_from some checkpoint? I have met the problem that the performance of interrupted training doesn't match the performance of continuous training? Could you give me any advice or solution?

**Comment by daeunni** [comment]
This is a good question :)
