### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'ignore_index'

### ISSUE THREAD

**Issue by DreamerWangDr** [open-mmlab/mmsegmentation#201]
I add a new loss 'my_loss' to mmseg/models/losses/ as the tutorial doc did.

_my_loss.py :_

`import torch
import torch.nn as nn

from ..builder import LOSSES
from .utils import weighted_loss

@weighted_loss
def my_loss(pred, target):
    assert pred.size() == target.size() and target.numel() > 0
    loss = torch.abs(pred - target)
    return loss

@LOSSES.register_module
class MyLoss(nn.Module):

    def __init__(self, reduction='mean', loss_weight=1.0):
        super(MyLoss, self).__init__()
        self.reduction = reduction
        self.loss_weight = loss_weight

    def forward(self,
                pred,
                target,
                weight=None,
                avg_factor=None,
                reduction_override=None):
        assert reduction_override in (None, 'none', 'mean', 'sum')
        reduction = (
            reduction_override if reduction_override else self.reduction)
        loss = self.loss_weight * my_loss(
            pred, target, weight, reduction=reduction, avg_factor=avg_factor)
        return loss`

Then , when I use this loss to train the model, this TypeError appeared.

**Comment by xvjiarui** [comment]
Hi @DreamerWangDr 
Try this 
```
def my_loss(pred, target, **kwargs):
```
We will update tutorial to fix this.

**Comment by DreamerWangDr** [comment]
> Hi @DreamerWangDr
> Try this
> 
> ```
> def my_loss(pred, target, **kwargs):
> ```
> 
> We will update tutorial to fix this.

Thanks， I tried this,  still TypeError: forward() got an unexpected keyword argument 'ignore_index'.
Hope  that  Dice Loss and Focal Loss can be added to the losses module.

**Comment by xvjiarui** [comment]
Hi @DreamerWangDr 
Sorry. My mistake. You may try this
def forward(self,
            pred,
            target,
            weight=None,
            avg_factor=None,
            reduction_override=None,
            **kwargs):

**Comment by DreamerWangDr** [comment]
> Hi @DreamerWangDr
> Sorry. My mistake. You may try this
> 
> ```
> def forward(self,
>             pred,
>             target,
>             weight=None,
>             avg_factor=None,
>             reduction_override=None,
>             **kwargs):
> ```

Hi, Thanks. I tried this,  TypeError: forward() got an unexpected keyword argument 'ignore_index' disppeard.
Then , I meet an assert error at line :   assert pred.size() == target.size() and target.numel() > 0
I don't know is pred.size different from target.size or target.numel() <=0 ?
