### ISSUE TITLE
Can I use U-Net as backbone with UperNet as decode_head without modify src code?

### ISSUE THREAD

**Issue by WandernForte** [open-mmlab/mmsegmentation#2017]
it's just a lazy try.
i notice that U-Net outputs format is different from swin's.
How can I use U-Net as backbone with UperNet as decode_head **without modify src code**, or impossible?

**Comment by MengzhangLI** [comment]
Just figure out whether size of output feature map of UNet and input feature map of UperNet is the same, if yes, it could run normally.

Plus, you should notice the [`in_index`](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py#L26) means the corresponding feature map in output feature map list from Unet backbone.

**Comment by WandernForte** [comment]
> Just figure out whether size of output feature map of UNet and input feature map of UperNet is the same, if yes, it could run normally.
> 
> Plus, you should notice the [`in_index`](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py#L26) means the corresponding feature map in output feature map list from Unet backbone.

thanks, i'll have a try
