### ISSUE TITLE
关于mmseg/models/decode_heads修改问题

### ISSUE THREAD

**Issue by duduzai2019** [open-mmlab/mmsegmentation#2031]
你好，mmseg的decode_heads都封装好了，我想修改解码头的网络模型，但是无从下手，mmseg不像其它开源的代码，直接列出网络模型。请问我应该去参考哪里的历程

**Comment by xiexinch** [comment]
Hi @duduzai2019,
你可以看下我们的文档。
https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_models.html#add-new-heads

**Comment by duduzai2019** [comment]
> Hi @duduzai2019, 你可以看下我们的文档。 https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_models.html#add-new-heads

之前有看过你们写的文档，但是封装好了，不知道从哪里入手去改网络层，还有什么更好的建议吗，谢谢回复

**Comment by MeowZheng** [comment]
please discuss in #2033
