### ISSUE TITLE
About the MMSEG /models/decode_heads modification problem

### ISSUE THREAD

**Issue by duduzai2019** [open-mmlab/mmsegmentation#2033]
Hi, mmseg decode_heads are all wrapped up, I want to modify the solution dock network model, but don't know how to start, mmseg is not like other open source code, directly listed network model. Where should I refer to?

**Comment by MeowZheng** [comment]
Would you like to let me know what you want to modify? Network architecture or the output of decode head?

If it is architecture, you can modify the `__init__` to define your own network. If it is the output, there are two kinds of output type, one is loss scaler from  `forward_train` and the other is seg map from `forward_test`. If you would like to define and registry you own decode head, you can follow the documentation below.

https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_models.md
