### ISSUE TITLE
IndexError when using LovaszLoss in Binary mode

### ISSUE THREAD

**Issue by project-f-t** [open-mmlab/mmsegmentation#2034]
I use LovaszLoss in binary mode and firstly I get RuntimeError
~~~~
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
~~~~
But I could fix it by modifying like this (Lovaszloss.py)
~~~~
def flatten_binary_logits(logits, labels, ignore_index=None):
    """Flattens predictions in the batch (binary case) Remove labels equal to
    'ignore_index'."""
    logits = logits.view(-1) --> logits = logits.contiguous().view(-1)
    labels = labels.view(-1) --->  labels = labels.contiguous().view(-1)
    if ignore_index is None:
        return logits, labels
    valid = (labels != ignore_index)
    vlogits = logits[valid]
    vlabels = labels[valid]
    return vlogits, vlabels
~~~~

Then secondly I got indexError like this
~~~~
File "/content/mmsegmentation/mmseg/models/losses/lovasz_loss.py", line 38, in flatten_binary_logits
    vlogits = logits[valid]
IndexError: The shape of the mask [2359296] at index 0 does not match the shape of the indexed tensor [4718592] at index 0
~~~~

I don't see this error massage when I use CrossEntropyLoss.
How can I fix this problem?
Thanks.

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Could you have a look at this [issue](https://github.com/open-mmlab/mmsegmentation/issues/1681)?

**Comment by project-f-t** [comment]
> Hi, sorry for late reply.
> 
> 
> 
> Could you have a look at this [issue](https://github.com/open-mmlab/mmsegmentation/issues/1681)?

Thank you so much! This is what I wanted to know. 
I am very new in segmentation tasks and even in Deep Learning. And I am deeply helped by mmsegmentation to understand the field. I really appreciate for your work!!!
