### ISSUE TITLE
Unet, input image size downsample

### ISSUE THREAD

**Issue by Jing-W98** [open-mmlab/mmsegmentation#2035]
Hi, I try to train a Unet model with my dataset, but when evaluataion it reports an error

AssertionError: The input image size (1540, 1024) should be divisible by the whole downsample rate 16

How can I solve this problem?

**Comment by MeowZheng** [comment]
I suggest doing some preprocessing to resize crop or pad the images and make height and width of them divisible by 16

**Comment by Jing-W98** [comment]
Thank you! I have solved the problem.

**Comment by fegr3** [comment]
> 

hi,I faced the same error,may i know you how to solve it? Thanks!
