### ISSUE TITLE
assert rescale AssertionError

### ISSUE THREAD

**Issue by ke-dev** [open-mmlab/mmsegmentation#2038]
Hi, developers, thanks for your contribution.
When I try to increase  this, I have the following problem

![ad73fe02f48bc1a8aadf714a6937001](https://user-images.githubusercontent.com/59656387/188845463-5e5c0fdb-0769-4ac5-97a9-2cb11ec71977.png)

This is the configuration

![1662543020537](https://user-images.githubusercontent.com/59656387/188845494-9098208d-87ef-45af-b408-cc07ad47f74c.png)

looking forward to your reply,
best regards.

**Comment by MeowZheng** [comment]
In segmentor base class, `rescale` defaults to True, and mmseg test api didn't input `rescale=False` to model `forward_test`. Have you ever input `rescale=False` somewhere

refer to:
https://github.com/open-mmlab/mmsegmentation/blob/d8ea8f7460df5b7cffe0023b4e44eedaa90d9e31/mmseg/models/segmentors/encoder_decoder.py#L273-L279

**Comment by ke-dev** [comment]
> 

I haven't use `aug_test`, I will try to set `rescale=True`
