### ISSUE TITLE
mmseg/datasets/piplines/transforms.py, line197

### ISSUE THREAD

**Issue by zhezhi110** [open-mmlab/mmsegmentation#204]
（1）
mmseg/datasets/piplines/transforms.py, line197:
results['gt_semantic_seg'] = gt_seg  -->   results[key] = gt_seg

（2）
results['seg_fields'] is a List. Type Set may be better.

**Comment by xvjiarui** [comment]
Hi @zhezhi110 
Thanks for your suggestion. Could you elaborate more about the motivation? You are also very welcomed to create a PR.
