### ISSUE TITLE
Migration Guides from 0.x to 1.x

### ISSUE THREAD

**Issue by haruishi43** [open-mmlab/mmsegmentation#2043]
Been using `mmseg` for a bit and saw that you guys are updating to 1.x soon.
I'm excited to try the new version out, but my custom models, datasets, pipelines, etc... are not compatible anymore.
Are there helpful guides for migrating the code base from 0.x?
Would like to contribute if you guys have no plans yet

**Comment by MeowZheng** [comment]
Thank you for supporting new mmseg, and we are working on it, and you will see it next week.

**Comment by MeowZheng** [comment]
we have support Migration Guides [here](https://github.com/open-mmlab/mmsegmentation/tree/1.x/docs/en/migration)
