### ISSUE TITLE
Testing/Training freezes when running with gpus > 2

### ISSUE THREAD

**Issue by yuanyuangoo** [open-mmlab/mmsegmentation#2044]
I have 4 GPUs and try to run testing/training with multiple GPUs.

When I run "./tools/dist_test.sh config checkpoints 2 --eval mIoU" with 2 GPUs, it works. 
But when I run "./tools/dist_test.sh config checkpoints 4 --eval mIoU" with 4 or 3 GPUs, it freezes after 2 checkpoints are loaded "load checkpoint from local path ...".

I encounter same freezing issue when I ran training scripts.

Is any way I can solve this.

My gpus info is as below:

Thu Sep  8 14:26:10 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:09:00.0 Off |                  N/A |
| 55%   77C    P2    80W / 250W |    573MiB / 11178MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:0A:00.0 Off |                  N/A |
| 36%   66C    P2    83W / 250W |    549MiB / 11178MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    On   | 00000000:41:00.0 Off |                  N/A |
| 50%   84C    P2    90W / 250W |    613MiB / 12196MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  TITAN RTX           On   | 00000000:42:00.0 Off |                  N/A |
| 73%   86C    P2   110W / 280W |    777MiB / 24219MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2021      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A    566092      C   /usr/bin/python                   565MiB |
|    1   N/A  N/A      2021      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A    566093      C   /usr/bin/python                   541MiB |
|    2   N/A  N/A      2021      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A    566094      C   /usr/bin/python                   605MiB |
|    3   N/A  N/A      2021      G   /usr/lib/xorg/Xorg                  9MiB |
|    3   N/A  N/A      2310      G   /usr/bin/gnome-shell                4MiB |
|    3   N/A  N/A    566091      C   /usr/bin/python                   759MiB |
+-----------------------------------------------------------------------------+

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

I am not sure whether it is caused by your different GPU type. Could you run other repository (not OpenMMLab codebases) correctly using 3 or 4 GPUs?
