### ISSUE TITLE
Process of MultiScaleFlipAug and slide window 

### ISSUE THREAD

**Issue by tomp11** [open-mmlab/mmsegmentation#2045]
Thanks for the great library.

If both `MultiScaleFlipAug` and `test_cfg = dict(mode="slide", crop_size, stride)` are on, 
How process images.
window crop -> multi scale resize -> transform ?

**Comment by MengzhangLI** [comment]
`MultiScaleFlipAug` is [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/test_time_aug.py#L11), I suggest **debug** using this command:

```shell
python tools/test.py ./configs/convnext/upernet_convnext_tiny_fp16_512x512_160k_ade20k.py https://download.openmmlab.com/mmsegmentation/v0.5/convnext/upernet_convnext_tiny_fp16_512x512_160k_ade20k/upernet_convnext_tiny_fp16_512x512_160k_ade20k_20220227_124553-cad485de.pth --aug-test
```
Back to your detailed question, it would first using multi scale + flip augmentation:

For example:

```python
img_scale=(2048, 1024),
img_ratios=[0.5, 1.0],
flip=True,
transforms=[
    dict(type='Resize', keep_ratio=True),
    dict(type='RandomFlip'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]
# After MultiScaleFLipAug with above configuration, the results are wrapped into lists of the same length as followed:
dict(
    img=[...],
    img_shape=[...],
    scale=[(1024, 512), (1024, 512), (2048, 1024), (2048, 1024)]
    flip=[False, True, False, True]
    ...
)
```

Then, in each `scale` + `flip` match up, it would use [`slide`](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L156-L202) inference mode, where the input of inference function is not whole image but part of it.

**Comment by tomp11** [comment]
I understood fully, thank you!
