### ISSUE TITLE
为啥我设置了12类，它只预测11类？？？CamVid数据集

### ISSUE THREAD

**Issue by fakerlove1** [open-mmlab/mmsegmentation#2049]
`from mmseg.datasets.builder import DATASETS
from mmseg.datasets.custom import CustomDataset

CLASSES = ('Bicyclist', 'Building', 'Car', 'Column_Pole',
           'Fence', 'Pedestrian', 'Road', 'Sidewalk',
           'SignSymbol', 'Sky', 'Tree', 'backgroud')

PALETTE = [[0, 128, 192], [128, 0, 0], [64, 0, 128], [192, 192, 128],
           [64, 64, 128], [64, 64, 0], [128, 64, 128], [0, 0, 192],
           [192, 128, 128], [128, 128, 128], [128, 128, 0], [0, 0, 0]]

@DATASETS.register_module()
class Camvid12(CustomDataset):

    CLASSES =('Bicyclist','Building','Car','Column_Pole',
              'Fence','Pedestrian','Road','Sidewalk',
              'SignSymbol','Sky','Tree','backgroud')

    PALETTE = [[0, 128, 192],[128, 0, 0],[64, 0, 128],[192, 192, 128],
               [64, 64, 128],[64, 64, 0],[128, 64, 128], [0, 0, 192],
               [192, 128, 128], [128, 128, 128],[128, 128, 0],[0,0,0]]

    def __init__(self, **kwargs):
        super(Camvid12, self).__init__(
            img_suffix='.png',
            seg_map_suffix='_L.png',
            reduce_zero_label=False,
            classes=CLASSES,
            palette=PALETTE,
            **kwargs)
`

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Did you set `reduce_zero_label=True` in your config file?

If yes, you can check out what does reduce_zero_label work from [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/loading.py#L145-L149).

Best,

**Comment by svitlana1ana** [comment]
请问下你是如何将Camvid数据集转换mmseg格式的呀

**Comment by SchumacherVonHeinz** [comment]
> 请问下你是如何将Camvid数据集转换mmseg格式的呀
你好，你可以参考这个网站对数据集设置进行修改！
http://t.csdnimg.cn/bdzA8

**Comment by svitlana1ana** [comment]
> > 请问下你是如何将Camvid数据集转换mmseg格式的呀
> > 你好，你可以参考这个网站对数据集设置进行修改！
> > http://t.csdnimg.cn/bdzA8

谢谢！
