### ISSUE TITLE
What does forward_plugin do in Bottleneck?

### ISSUE THREAD

**Issue by JoyLuo** [open-mmlab/mmsegmentation#205]
`        if self.with_plugins:
            out = self.forward_plugin(out, self.after_conv1_plugin_names)`

if self.with_plugins is True, use forward_plugin after the conv in  bottleneck, What does forward_plugin do in Bottleneck?

**Comment by xvjiarui** [comment]
Hi @JoyLuo 
Please refer to [this config](https://github.com/open-mmlab/mmdetection/blob/master/configs/gcnet/mask_rcnn_r50_fpn_r16_gcb_c3-c5_1x_coco.py) for the usage of plugin.
