### ISSUE TITLE
can i use multi-scale training in mmsegmentation?

### ISSUE THREAD

**Issue by MHX1203** [open-mmlab/mmsegmentation#2053]
I 'd like to change training size every several  batch. if mmsegmentation support this training method.

hoping anyone can help me.

best wishes.

**Comment by xiexinch** [comment]
Hi @MHX1203,
We have implemented this feature.
https://mmsegmentation.readthedocs.io/en/latest/tutorials/data_pipeline.html#design-of-data-pipelines
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/transforms.py#L70

**Comment by MHX1203** [comment]
ok, thanks very much. i got it.
