### ISSUE TITLE
How can I debug for 'mmseg/datasets/custom.py'?

### ISSUE THREAD

**Issue by 9p15p** [open-mmlab/mmsegmentation#206]
System:  'Ubuntu 18.04'
IDE        :  'Pycharm 2020.2.3'

if I set a breakpoint in `mmseg/datasets/custom.py`.  the IDE can't get it in debug mode. In `nvidia-smi`, the GPU-utils is very low，it looks like that the code didn't start.

However, it can run normally.

whether run or debug,  I use `python tools/train.py configs/deeplabv3plus/deeplabv3plus_r50-d8_512x1024_40k_cityscapes.py` and I have replaced `SyncBN` with `BN`

the place I set a breakpoint In `mmseg/datasets/custom.py`
```
    def __getitem__(self, idx):
        """Get training/test data after pipeline.

        Args:
            idx (int): Index of data.

        Returns:
            dict: Training/test data (with annotation if `test_mode` is set
                False).
        """
        print('I need breakpoints')    #☆ I set a breakpoint here
        if self.test_mode:
            return self.prepare_test_img(idx)
        else:
            return self.prepare_train_img(idx)
```

Asking for some advice:
Now I want to use a new Dataset like cityscape,  the task is about video. So I need to load many imgs from the same dir at one time.  But now I can't debug in `mmseg/datasets/custom.py`. 
Do you have some idea about this ? (T_T)

the dataset directory is like
```
├── dataset
│   ├── Annotations
│       ├── f99dae3620
│       │   ├── 00000.png
│       │   ├── 00001.png
│       │   ├── 00002.png
│       │   ├──......
│       ├── s53lkj5216
│       │   ├── 00000.png
│       │   ├── 00001.png
│       │   ├── 00002.png
│       │   ├──......
│       ├── ......
│   ├── JPEGImages 
│       ├── f99dae3620
│       │   ├── 00000.jpg
│       │   ├── 00001.jpg
│       │   ├── 00002.jpg
│       │   ├──......
│       ├── s53lkj5216
│       │   ├── 00000.jpg
│       │   ├── 00001.jpg
│       │   ├── 00002.jpg
│       │   ├──......
│       ├── ......
│   └── splits
│       ├── train.txt
│       └── val.txt

```
Looking forward to your reply!
Thanks you for your great work  very much!(^_^)

**Comment by York1996OutLook** [comment]
you should inheret CustomDataset and dataset_type = 'MySegmentDataset' ,

**Comment by York1996OutLook** [comment]
you can add me qq 603997262,

**Comment by 9p15p** [comment]
> you can add me qq 603997262,

Thank you,  I have submittd.

**Comment by 9p15p** [comment]
York1996OutLook's advice works.

If we want debug, we need to replace `workers_per_gpu=2` with `workers_per_gpu=0`in `configs/_base_/datasets/cityscapes.py`.

other dataset_config_file is the same if you want to debug in other dataset.

Maybe Something wrong in multiprocessing debug.

Looking forward to expert's explanation.

**Comment by xvjiarui** [comment]
Hi @9p15p 
You may also try [pdb](https://docs.python.org/3/library/pdb.html) or ipdb. 
But in any case, we should debug in the main process.

**Comment by super233** [comment]
> Hi @9p15p You may also try [pdb](https://docs.python.org/3/library/pdb.html) or ipdb. But in any case, we should debug in the main process.

Hi, sorry to disturb you, I have added `pdb.set_trace()` in my dataset.py, however it dose not stop in the breakpoint line when runing code, what's going on?
