### ISSUE TITLE
Problems in the implementation of diceloss

### ISSUE THREAD

**Issue by 5ampere** [open-mmlab/mmsegmentation#2068]
The confusion comes from \mmsegmentation\mmseg\models\losses\dice_loss.py->dice_loss()
When there are multiple samples in the batch, it should be that dice(batch) = average(dice1, dice2, ...)
But in mmseg, it seems to be dice(batch) = [sum(Inter1 + Inter2 +...) / sum(Unit.on1 + Union2 +...)]
Why is it calculated like this？ Thanks for your reply.
![diceloss](https://user-images.githubusercontent.com/41566277/190090726-529eb286-a5a6-43e2-ac69-724236ac28f4.png)

**Comment by MeowZheng** [comment]
Many thanks for your kind reminder and the figure is very clear for us. We are working on figuring out it and if we have any processes or conclusions, we will inform you asap.

**Comment by 5ampere** [comment]
Thanks and look forward to your reply
