### ISSUE TITLE
Missing instruction to install mmengine.

### ISSUE THREAD

**Issue by saratrajput** [open-mmlab/mmsegmentation#2072]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
In the getting started docs, when I try to download the pspnet config and checkpoint files, I get the following error:

```
... line 93, in download
    raise ImportError(highlighted_error(msg))
ImportError: Please install mmengine to use the download command.
```

**Reproduction**

1. What command or script did you run?

   ```bash
   mim download mmsegmentation --config pspnet_r50-d8_512x1024_40k_cityscapes --dest .
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
-NA
3. What dataset did you use?
-NA
**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

```
... line 93, in download
    raise ImportError(highlighted_error(msg))
ImportError: Please install mmengine to use the download command.
```

**Bug fix**

It can be fixed with adding the following command before downloading the config and checkpoint files:

```
mim install mmengine
```

I've made a small PR to fix the docs if you'd like to use it.
PR: https://github.com/open-mmlab/mmsegmentation/pull/2073

**Comment by MeowZheng** [comment]
@ice-tong please have a look

**Comment by ice-tong** [comment]
Hi @saratrajput, thanks for the feedback.

Since `mmengine` is an extra requirement of `mim download`,  you should install it manually.

I totally agree with you that [the error message](https://github.com/open-mmlab/mim/blob/ffaff8a4ece8a833b20dc7c6c1a7f8647d9eec15/mim/commands/download.py#L92) would be better if it tells the user how to install `mmengine`. If you are interested, contributions are welcome. ^_^

p.s. `mim install mmengine` equivalent to `pip install mmengine`

**Comment by saratrajput** [comment]
@ice-tong Thanks. I made a PR to add the instructions to the README, but this sounds better. Let me make a small PR to add this to the error message.
