### ISSUE TITLE
how to only use cpu to run

### ISSUE THREAD

**Issue by York1996OutLook** [open-mmlab/mmsegmentation#208]
sometime use cpu to run the code,can get the meaningful error so i can fix my code.   for example ,cuda device error ,from this ,i can hard to get the useful info to know why

**Comment by xvjiarui** [comment]
Hi @York1996OutLook 
We only support CPU in the inference model. Training is not supported.

**Comment by CanyonWind** [comment]
> Hi @York1996OutLook
> We only support CPU in the inference model. Training is not supported.

Hi sorry to reopen it, but it seems `test.py` still doesn't support CPU for inference. Could you please let us know where to find that CPU inference codes? Thx

**Comment by achaiah** [comment]
Would love to see this fixed. I just ran into this issue myself and I don't see why training should be limited to the GPU. Very frequently when I'm working with new models or implement some loss function, I just want to run training locally for a few iterations to see if it works well (e.g. loss function doesn't blow up or something). Remotely debugging this on GPUs is incredibly painful and unnecessary.
