### ISSUE TITLE
IoU / Acc nan

### ISSUE THREAD

**Issue by tjdgus6255** [open-mmlab/mmsegmentation#2081]
Hello.

I want to train pretrained model(deeplabv3) using my dataset.

So. I prepared custom dataset(look like coco-stuff)  ---> '.jpg' - images folder / '.png'(gray scale) - annotations folder

But, I got an ERROR like below.

+-----------------------+-----+-----+
|         Class         | IoU | Acc |
+-----------------------+-----+-----+
|          back         | 0.0 | 0.0 |
|     circular_valve    | nan | nan |
|   fire_extinguisher   | nan | nan |
|     straight_valve    | nan | nan |
|     water_hose_box    | nan | nan |
|       water_hose      | nan | nan |
| fire_extinguisher_box | nan | nan |
|      flash_light      | nan | nan |
|         handle        | nan | nan |
|    emergency_light    | 0.0 | nan |
|      fire_hydrant     | nan | nan |
+-----------------------+-----+-----+
2022-09-16 09:50:50,191 - mmseg - INFO - Summary:
2022-09-16 09:50:50,191 - mmseg - INFO - 
+------+------+------+
| aAcc | mIoU | mAcc |
+------+------+------+
| 0.0  | 0.0  | 0.0  |
+------+------+------+
2022-09-16 09:50:50,201 - mmseg - INFO - Iter(val) [199]	aAcc: 0.0000, mIoU: 0.0000, mAcc: 0.0000, IoU.back: 0.0000, IoU.circular_valve: nan, IoU.fire_extinguisher: nan, IoU.straight_valve: nan, IoU.water_hose_box: nan, IoU.water_hose: nan, IoU.fire_extinguisher_box: nan, IoU.flash_light: nan, IoU.handle: nan, IoU.emergency_light: 0.0000, IoU.fire_hydrant: nan, Acc.back: 0.0000, Acc.circular_valve: nan, Acc.fire_extinguisher: nan, Acc.straight_valve: nan, Acc.water_hose_box: nan, Acc.water_hose: nan, Acc.fire_extinguisher_box: nan, Acc.flash_light: nan, Acc.handle: nan, Acc.emergency_light: nan, Acc.fire_hydrant: nan

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

mmsegmentation/mmseg/datasets/my_data.py
`from .builder import DATASETS
from .custom import CustomDataset

@DATASETS.register_module()
class MyDataset(CustomDataset):
    CLASSES = (
        'back', 'circular_valve', 'fire_extinguisher', 'straight_valve', 'water_hose_box', 
        'water_hose', 'fire_extinguisher_box', 'flash_light', 'handle', 'emergency_light', 'fire_hydrant')
    
    PALETTE = [[0], [1], [2], [3], [4],[5], [6], [7], [8], [9], [10]]
    '''
    PALETTE = [[255, 255, 204], [255, 255, 0], [0, 0, 255], [255, 20, 147], 
                [152, 251, 152],[255, 0, 0], [0, 255, 0], [0, 0, 0], 
                [255, 182, 193], [173, 216, 230], [152, 251, 152]]
    '''
    def __init__(self, **kwargs):
        super(MyDataset, self).__init__(
            img_suffix='.jpg', seg_map_suffix='.png', **kwargs)`

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

mmsegmentation/mmseg/datasets/__init__.py
`# Copyright (c) OpenMMLab. All rights reserved.
from .ade import ADE20KDataset
from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
from .chase_db1 import ChaseDB1Dataset
from .cityscapes import CityscapesDataset
from .coco_stuff import COCOStuffDataset
from .custom import CustomDataset
from .dark_zurich import DarkZurichDataset
from .dataset_wrappers import (ConcatDataset, MultiImageMixDataset,
                               RepeatDataset)
from .drive import DRIVEDataset
from .hrf import HRFDataset
from .isaid import iSAIDDataset
from .isprs import ISPRSDataset
from .loveda import LoveDADataset
from .night_driving import NightDrivingDataset
from .pascal_context import PascalContextDataset, PascalContextDataset59
from .potsdam import PotsdamDataset
from .stare import STAREDataset
from .voc import PascalVOCDataset
from .my_data import MyDataset

__all__ = [
    'CustomDataset', 'build_dataloader', 'ConcatDataset', 'RepeatDataset',
    'DATASETS', 'build_dataset', 'PIPELINES', 'CityscapesDataset',
    'PascalVOCDataset', 'ADE20KDataset', 'PascalContextDataset',
    'PascalContextDataset59', 'ChaseDB1Dataset', 'DRIVEDataset', 'HRFDataset',
    'STAREDataset', 'DarkZurichDataset', 'NightDrivingDataset',
    'COCOStuffDataset', 'LoveDADataset', 'MultiImageMixDataset',
    'iSAIDDataset', 'ISPRSDataset', 'PotsdamDataset', 'MyDataset'
]`

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

mmsegmentation/mmseg/core/evaluation/class_names.py
`def mydata_classes():
    return [
        'back', 'circular_valve', 'fire_extinguisher', 'straight_valve', 
        'water_hose_box', 'water_hose', 'fire_extinguisher_box', 'flash_light', 
        'handle', 'emergency_light', 'fire_hydrant'
    ]`
`def mydata_palette():
    return [[0, 0, 0], [255, 255, 0], [0, 0, 255], [255, 20, 147], 
            [152, 251, 152],[255, 0, 0], [0, 255, 0], [255, 255, 204], 
            [255, 182, 193], [173, 216, 230], [152, 251, 152]]`
`dataset_aliases = {
    'cityscapes': ['cityscapes'],
    'ade': ['ade', 'ade20k'],
    'voc': ['voc', 'pascal_voc', 'voc12', 'voc12aug'],
    'loveda': ['loveda'],
    'potsdam': ['potsdam'],
    'vaihingen': ['vaihingen'],
    'cocostuff': [
        'cocostuff', 'cocostuff10k', 'cocostuff164k', 'coco-stuff',
        'coco-stuff10k', 'coco-stuff164k', 'coco_stuff', 'coco_stuff10k',
        'coco_stuff164k'
    ],
    'isaid': ['isaid', 'iSAID'],
    'stare': ['stare', 'STARE'],
    'mydata': ['mydata']
}`

**Comment by xiexinch** [comment]
Hi @tjdgus625,
Could you provide your config file if it's possible? Since your training launched successfully, I think it is not a problem with the code, the problem may lie in the hyperparameters of the model or dataset.

**Comment by tjdgus6255** [comment]
> Hi @tjdgus625, Could you provide your config file if it's possible? Since your training launched successfully, I think it is not a problem with the code, the problem may lie in the hyperparameters of the model or dataset.

`# model settings
norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://resnet101_v1c',
    backbone=dict(
        type='ResNetV1c',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=norm_cfg,
        norm_eval=False,
        style='pytorch',
        contract_dilation=True),
    decode_head=dict(
        type='ASPPHead',
        in_channels=2048,
        in_index=3,
        channels=512,
        dilations=(1, 12, 24, 36),
        dropout_ratio=0.1,
        num_classes=19,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=19,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))

#dataset settings
dataset_type = 'MyDataset'
data_root = 'data/my_dataset'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(type='Resize', img_scale=(2048, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='img_dir/train',
        ann_dir='ann_dir/train',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='img_dir/val',
        ann_dir='ann_dir/val',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='img_dir/val',
        ann_dir='ann_dir/val',
        pipeline=test_pipeline))

# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
# learning policy
lr_config = dict(policy='poly', power=0.9, min_lr=1e-4, by_epoch=False)
# runtime settings
runner = dict(type='IterBasedRunner', max_iters=3200)
checkpoint_config = dict(by_epoch=False, interval=3200)
evaluation = dict(interval=100, metric='mIoU')

# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
        # dict(type='TensorboardLoggerHook')
        # dict(type='PaviLoggerHook') # for internal services
    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True`

Here's my config file.

**Comment by xiexinch** [comment]
Hi @tjdgus6255,
The num_classes of decode_head should be the same as the number of classes in your dataset.

**Comment by tjdgus6255** [comment]
> Hi @tjdgus6255, The num_classes of decode_head should be the same as the number of classes in your dataset.

After modifying, I still got a same error. 

When I put reduce_zero_label = False, I got an accuracy (not zero). But, in evaluation part,  I got only back's IoU and Acc

![R0004](https://user-images.githubusercontent.com/67773599/191144120-8b33d2c1-ec44-4904-9ea5-7516116ac2be.png)
![R_0004](https://user-images.githubusercontent.com/67773599/191144143-ca912fa0-f85e-4360-8331-84606e7059bc.jpg)

There are my dataset example for training. 

command line for traing
python tools/train.py configs/deeplabv3/deeplabv3_r101-d8_512x512_4x4_320k_coco-stuff164k_mydata.py --work-dir custom_model --load-from checkpoint/deeplabv3_r101-d8_512x512_4x4_320k_coco-stuff164k.pth

**Comment by tjdgus6255** [comment]
In addition, I have a question. Is it possible to train pretrained model with custom dataset?

**Comment by tjdgus6255** [comment]
Hello! I solved it. 

By converting color value to label value, It works well.

**Comment by AeBoPi** [comment]
> 

Hello！Can you tell me the details? What should i do to converting color value to label value?

**Comment by tjdgus6255** [comment]
I converted color value to label value by referring to this script ('tools/convert_datasets/isaid.py')
```
color_to_label = {
    (0, 0, 0): 0,
    (255, 255, 0): 1,
    (0, 0, 255): 2,
    (255, 0, 255): 3,
    (200, 255, 200): 4,
    (255, 0, 0): 5,
    (0, 255, 0): 6,
    (255, 255, 200): 7,
    (225, 150, 200): 8,
    (200, 255, 255): 9,
    (0, 255, 0): 10
}
```
But I don't think it's a correct solution.

If you're thinking about labeling again, I recommend you do the labeling in this site --> https://github.com/wkentaro/labelme.git

In my case, the labeling image obtained from the site did not need to go through the above process.

**Comment by AeBoPi** [comment]
OK! Thank you very much!

**Comment by Rock-L21** [comment]
> I converted color value to label value by referring to this script ('tools/convert_datasets/isaid.py')
> 
> ```
> color_to_label = {
>     (0, 0, 0): 0,
>     (255, 255, 0): 1,
>     (0, 0, 255): 2,
>     (255, 0, 255): 3,
>     (200, 255, 200): 4,
>     (255, 0, 0): 5,
>     (0, 255, 0): 6,
>     (255, 255, 200): 7,
>     (225, 150, 200): 8,
>     (200, 255, 255): 9,
>     (0, 255, 0): 10
> }
> ```
> 
> But I don't think it's a correct solution.
> 
> If you're thinking about labeling again, I recommend you do the labeling in this site --> https://github.com/wkentaro/labelme.git
> 
> In my case, the labeling image obtained from the site did not need to go through the above process.

Hello, may I ask how to convert the dataset made from labelme (the label is in json format) into a dataset format usable by MMSegmentation?

**Comment by tjdgus6255** [comment]
After annotation, you should convert files(json format) to VOC-format dataset.
``` 
labelme data_annotated --labels labels.txt --nodata --validatelabel exact --config '{shift_auto_shape_color: -2}'
./labelme2voc.py data_annotated data_dataset_voc --labels labels.txt
```

**Comment by Rock-L21** [comment]
> 注释后，您应该将文件（json 格式）转换为 VOC 格式的数据集。
> 
> ```
> labelme data_annotated --labels labels.txt --nodata --validatelabel exact --config '{shift_auto_shape_color: -2}'
> ./labelme2voc.py data_annotated data_dataset_voc --labels labels.txt
> ```

Hello, thank you very much for your reply. Where is the code snippet involving this command line?

**Comment by tjdgus6255** [comment]
Hello. I recommend that you read the README.md before asking.

**Comment by Rock-L21** [comment]
> Hello. I recommend that you read the README.md before asking.

ok, thank you very much for your reply

**Comment by EkjotSingh898** [comment]
hello! I converted the color vaue to label value. But still for some classes i was getting Nan Iou and Acc after training

**Comment by EkjotSingh898** [comment]
hello! I converted the color vaue to label value. But still for some classes i was getting Nan Iou and Acc after training

**Comment by Rock-L21** [comment]
> hello! I converted the color vaue to label value. But still for some classes i was getting Nan Iou and Acc after training

Sorry, I can't help you, I suggest you open an issue and upload the relevant configuration and logs.

**Comment by Zqsmy** [comment]
Why is my background value always 0 。
2024-03-31 15:05:24,222 - mmseg - INFO - Epoch(val) [1][100]    aAcc: 0.2471, mIoU: 0.1235, mAcc: 0.5000, IoU.background: 0.0000, IoU.skin: 0.2471, Acc.background: 0.0000, Acc.skin: 1.0000
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100/100, 3.1 task/s, elapsed: 32s, ETA:     0s2024-03-31 15:05:57,061 - mmseg - INFO - per class results:
2024-03-31 15:05:57,061 - mmseg - INFO -
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background |  0.0  |  0.0  |
|    skin    | 24.71 | 100.0 |
+------------+-------+-------+
2024-03-31 15:05:57,062 - mmseg - INFO - Summary:
2024-03-31 15:05:57,062 - mmseg - INFO -
+-------+-------+------+
|  aAcc |  mIoU | mAcc |
+-------+-------+------+
| 24.71 | 12.35 | 50.0 |
+-------+-------+------+
2024-03-31 15:05:57,062 - mmseg - INFO - Epoch(val) [1][100]    aAcc: 0.2471, mIoU: 0.1235, mAcc: 0.5000, IoU.background: 0.0000, IoU.skin: 0.2471, Acc.background: 0.0000, Acc.skin: 1.0000

**Comment by lypan1208** [comment]
I've met the similar problem on iSAID dataset, except the background, other classes got IoU and ACC 0 or nan, here's my log file:

2024/08/22 10:32:06 - mmengine - INFO - Iter(val) [11600/11644]    eta: 0:00:02  time: 0.0648  data_time: 0.0024  memory: 1224  
2024/08/22 10:32:09 - mmengine - INFO - per class results:
2024/08/22 10:32:09 - mmengine - INFO - 
+--------------------+-------+-------+
|       Class        |  IoU  |  Acc  |
+--------------------+-------+-------+
|     background     | 96.65 | 100.0 |
|        ship        |  0.0  |  0.0  |
|     store_tank     |  nan  |  nan  |
|  baseball_diamond  |  nan  |  nan  |
|    tennis_court    |  nan  |  nan  |
|  basketball_court  |  nan  |  nan  |
| Ground_Track_Field |  nan  |  nan  |
|       Bridge       |  nan  |  nan  |
|   Large_Vehicle    |  nan  |  nan  |
|   Small_Vehicle    |  nan  |  nan  |
|     Helicopter     |  nan  |  nan  |
|   Swimming_pool    |  nan  |  nan  |
|     Roundabout     |  nan  |  nan  |
| Soccer_ball_field  |  nan  |  nan  |
|       plane        |  nan  |  nan  |
|       Harbor       |  nan  |  nan  |
+--------------------+-------+-------+

tools/dataset_converters/isaid.py is as follows:
`# Copyright (c) OpenMMLab. All rights reserved.
import argparse
import glob
import os
import os.path as osp
import shutil
import tempfile
import zipfile

import mmcv
import numpy as np
from mmengine.utils import ProgressBar, mkdir_or_exist
from PIL import Image

iSAID_palette = \
    {
        0: (0, 0, 0),
        1: (0, 0, 63),
        2: (0, 63, 63),
        3: (0, 63, 0),
        4: (0, 63, 127),
        5: (0, 63, 191),
        6: (0, 63, 255),
        7: (0, 127, 63),
        8: (0, 127, 127),
        9: (0, 0, 127),
        10: (0, 0, 191),
        11: (0, 0, 255),
        12: (0, 191, 127),
        13: (0, 127, 191),
        14: (0, 127, 255),
        15: (0, 100, 155)
    }

iSAID_invert_palette = {v: k for k, v in iSAID_palette.items()}


def iSAID_convert_from_color(arr_3d, palette=iSAID_invert_palette):
    """RGB-color encoding to grayscale labels."""
    arr_2d = np.zeros((arr_3d.shape[0], arr_3d.shape[1]), dtype=np.uint8)

    for c, i in palette.items():
        m = np.all(arr_3d == np.array(c).reshape(1, 1, 3), axis=2)
        arr_2d[m] = i

    return arr_2d


def slide_crop_image(src_path, out_dir, mode, patch_H, patch_W, overlap):
    img = np.asarray(Image.open(src_path).convert('RGB'))

    img_H, img_W, _ = img.shape

    if img_H < patch_H and img_W > patch_W:

        img = mmcv.impad(img, shape=(patch_H, img_W), pad_val=0)

        img_H, img_W, _ = img.shape

    elif img_H > patch_H and img_W < patch_W:

        img = mmcv.impad(img, shape=(img_H, patch_W), pad_val=0)

        img_H, img_W, _ = img.shape

    elif img_H < patch_H and img_W < patch_W:

        img = mmcv.impad(img, shape=(patch_H, patch_W), pad_val=0)

        img_H, img_W, _ = img.shape

    for x in range(0, img_W, patch_W - overlap):
        for y in range(0, img_H, patch_H - overlap):
            x_str = x
            x_end = x + patch_W
            if x_end > img_W:
                diff_x = x_end - img_W
                x_str -= diff_x
                x_end = img_W
            y_str = y
            y_end = y + patch_H
            if y_end > img_H:
                diff_y = y_end - img_H
                y_str -= diff_y
                y_end = img_H

            img_patch = img[y_str:y_end, x_str:x_end, :]
            img_patch = Image.fromarray(img_patch.astype(np.uint8))
            image = osp.basename(src_path).split('.')[0] + '_' + str(
                y_str) + '_' + str(y_end) + '_' + str(x_str) + '_' + str(
                    x_end) + '.png'
            # print(image)
            save_path_image = osp.join(out_dir, 'img_dir', mode, str(image))
            img_patch.save(save_path_image, format='BMP')


def slide_crop_label(src_path, out_dir, mode, patch_H, patch_W, overlap):
    label = mmcv.imread(src_path, channel_order='rgb')
    label = iSAID_convert_from_color(label)
    img_H, img_W = label.shape

    if img_H < patch_H and img_W > patch_W:

        label = mmcv.impad(label, shape=(patch_H, img_W), pad_val=255)

        img_H = patch_H

    elif img_H > patch_H and img_W < patch_W:

        label = mmcv.impad(label, shape=(img_H, patch_W), pad_val=255)

        img_W = patch_W

    elif img_H < patch_H and img_W < patch_W:

        label = mmcv.impad(label, shape=(patch_H, patch_W), pad_val=255)

        img_H = patch_H
        img_W = patch_W

    for x in range(0, img_W, patch_W - overlap):
        for y in range(0, img_H, patch_H - overlap):
            x_str = x
            x_end = x + patch_W
            if x_end > img_W:
                diff_x = x_end - img_W
                x_str -= diff_x
                x_end = img_W
            y_str = y
            y_end = y + patch_H
            if y_end > img_H:
                diff_y = y_end - img_H
                y_str -= diff_y
                y_end = img_H

            lab_patch = label[y_str:y_end, x_str:x_end]
            lab_patch = Image.fromarray(lab_patch.astype(np.uint8), mode='P')

            image = osp.basename(src_path).split('.')[0].split(
                '_')[0] + '_' + str(y_str) + '_' + str(y_end) + '_' + str(
                    x_str) + '_' + str(x_end) + '_instance_color_RGB' + '.png'
            lab_patch.save(osp.join(out_dir, 'ann_dir', mode, str(image)))


def parse_args():
    parser = argparse.ArgumentParser(
        description='Convert iSAID dataset to mmsegmentation format')
    parser.add_argument('dataset_path', help='iSAID folder path')
    parser.add_argument('--tmp_dir', help='path of the temporary directory')
    parser.add_argument('-o', '--out_dir', help='output path')

    parser.add_argument(
        '--patch_width',
        default=896,
        type=int,
        help='Width of the cropped image patch')
    parser.add_argument(
        '--patch_height',
        default=896,
        type=int,
        help='Height of the cropped image patch')
    parser.add_argument(
        '--overlap_area', default=384, type=int, help='Overlap area')
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    dataset_path = args.dataset_path
    # image patch width and height
    patch_H, patch_W = args.patch_width, args.patch_height

    overlap = args.overlap_area  # overlap area

    if args.out_dir is None:
        out_dir = osp.join('data', 'iSAID')
    else:
        out_dir = args.out_dir

    print('Making directories...')
    mkdir_or_exist(osp.join(out_dir, 'img_dir', 'train'))
    mkdir_or_exist(osp.join(out_dir, 'img_dir', 'val'))
    mkdir_or_exist(osp.join(out_dir, 'img_dir', 'test'))

    mkdir_or_exist(osp.join(out_dir, 'ann_dir', 'train'))
    mkdir_or_exist(osp.join(out_dir, 'ann_dir', 'val'))
    mkdir_or_exist(osp.join(out_dir, 'ann_dir', 'test'))

    assert os.path.exists(os.path.join(dataset_path, 'train')), \
        f'train is not in {dataset_path}'
    assert os.path.exists(os.path.join(dataset_path, 'val')), \
        f'val is not in {dataset_path}'
    assert os.path.exists(os.path.join(dataset_path, 'test')), \
        f'test is not in {dataset_path}'

    with tempfile.TemporaryDirectory(dir=args.tmp_dir) as tmp_dir:
        for dataset_mode in [ 'train','val', 'test']:

            # for dataset_mode in [ 'test']:
            print(f'Extracting  {dataset_mode}ing.zip...')
            img_zipp_list = glob.glob(
                os.path.join(dataset_path, dataset_mode, 'images', '*.zip'))
            print('Find the data', img_zipp_list)
            for img_zipp in img_zipp_list:
                zip_file = zipfile.ZipFile(img_zipp)
                zip_file.extractall(os.path.join(tmp_dir, dataset_mode, 'img'))
            src_path_list = glob.glob(
                os.path.join(tmp_dir, dataset_mode, 'img', 'images', '*.png'))

            src_prog_bar = ProgressBar(len(src_path_list))
            for i, img_path in enumerate(src_path_list):
                if dataset_mode != 'test':
                    slide_crop_image(img_path, out_dir, dataset_mode, patch_H,
                                     patch_W, overlap)

                else:
                    shutil.move(img_path,
                                os.path.join(out_dir, 'img_dir', dataset_mode))
                src_prog_bar.update()

            if dataset_mode != 'test':
                label_zipp_list = glob.glob(
                    os.path.join(dataset_path, dataset_mode, 'Semantic_masks',
                                 '*.zip'))
                for label_zipp in label_zipp_list:
                    zip_file = zipfile.ZipFile(label_zipp)
                    zip_file.extractall(
                        os.path.join(tmp_dir, dataset_mode, 'lab'))

                lab_path_list = glob.glob(
                    os.path.join(tmp_dir, dataset_mode, 'lab', 'images',
                                 '*.png'))
                lab_prog_bar = ProgressBar(len(lab_path_list))
                for i, lab_path in enumerate(lab_path_list):
                    slide_crop_label(lab_path, out_dir, dataset_mode, patch_H,
                                     patch_W, overlap)
                    lab_prog_bar.update()

        print('Removing the temporary files...')

    print('Done!')


if __name__ == '__main__':
    main()
`
