### ISSUE TITLE
Even if "seg_pad_val=255 " it will run with "padding_value=0". Is this okay?

### ISSUE THREAD

**Issue by kekmodel** [open-mmlab/mmsegmentation#2087]
https://github.com/open-mmlab/mmsegmentation/blob/ee25adc2c1d73e22355d168fa09ae7bdac899a24/mmseg/datasets/pipelines/formatting.py#L209-L212

**Comment by kekmodel** [comment]
> It's OK. `pad_val` is used on image while `seg_pad_val` is on annotations.
> 
> https://github.com/open-mmlab/mmsegmentation/blob/ee25adc2c1d73e22355d168fa09ae7bdac899a24/mmseg/datasets/pipelines/transforms.py#L408-L427

https://github.com/open-mmlab/mmcv/blob/6a03918f55c1cc860bcb4d64a0e868ca13cf08ba/mmcv/parallel/data_container.py#L22-L44

DC, padding_value=0 is the default. Is this okay?

**Comment by MengzhangLI** [comment]
> > It's OK. `pad_val` is used on image while `seg_pad_val` is on annotations.
> > https://github.com/open-mmlab/mmsegmentation/blob/ee25adc2c1d73e22355d168fa09ae7bdac899a24/mmseg/datasets/pipelines/transforms.py#L408-L427
> 
> https://github.com/open-mmlab/mmcv/blob/6a03918f55c1cc860bcb4d64a0e868ca13cf08ba/mmcv/parallel/data_container.py#L22-L44
> 
> Thank you for your answer. DC, padding_value=0 is the default. Is this okay?

Yes, for sure. If you still doubt about it, you could set other value in config and have a try.
