### ISSUE TITLE
Performance gap in nonlocal network

### ISSUE THREAD

**Issue by Beanocean** [open-mmlab/mmsegmentation#209]
Hi @xvjiarui ,

Recently, I want to conduct some experiments on the nonlocal network.

After referring the issue #87, I have tried to set the random seed `--seed 0` in my experiments, but still can't reproduce the performance of the nonlocal network in cityscapes. I have run the resnet50 experiments for 5 times, and the highest score is 77.64 in single scale test mode (76.4 is the lower bound). And the experiments for 101 is 76.56. I conducted my experiments on 4 GPU cards. Should I use 8 cards for training, or is there anything else I need to pay attention to? Any response will be appreciated.

**Comment by xvjiarui** [comment]
Hi @Beanocean 
How long is your training iterations? I suggest use 80k for stable performance. Attention based model sometimes oscillate a lot. 
Btw, what is your effective batch size, 16 or 8?

**Comment by Beanocean** [comment]
@xvjiarui 

I trained the model for 40K iterations. im. I use 4 GPUs and the effective batch size is 8(=2*4).

**Comment by Beanocean** [comment]
Hi @xvjiarui ,

After training with longer iterations (80K) the performance becomes stable. and the final results are around 79 for resnet50. By the way, what's the effective batch size of the model released in [Readme.md](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/nonlocal_net/README.md), I think it should be given a clear indication.

Much thanks for your help.

**Comment by xvjiarui** [comment]
Hi @Beanocean 
All models are trained with 4 GPUs, which is stated in the beginning. For cityscapes, most models are trained with 2 images per GPU. But for some models like Fast SCNN, batch size is 8x4.

**Comment by Beanocean** [comment]
@xvjiarui 

Thanks a lot for your help.
