### ISSUE TITLE
cfg.dataset_type = ??

### ISSUE THREAD

**Issue by jhaggle** [open-mmlab/mmsegmentation#2098]
I am following this tutorial:
https://github.com/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb

I now wonder what I should set as `cfg.dataset_type` when I use my own dataset? I have first used labelme to annotate it and then the file labelme2voc.py from the labelme-repo to transform the annotations to the format required by mmsegmentation.

**Comment by MengzhangLI** [comment]
`dataset_type` is the name of your own dataset class. For example:

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/loveda.py#L2

It is defined here: 

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/loveda.py#L13
