### ISSUE TITLE
请问如何部署？（自己的训练数据集，ADE格式）

### ISSUE THREAD

**Issue by wxk514** [open-mmlab/mmsegmentation#2103]
导出onnx模型后，请问该怎么用opencv加载运行呢，有脚本么请问，谢谢！

**Comment by xiexinch** [comment]
Hi @wxk514,
推荐使用 [MMDeploy](https://github.com/open-mmlab/mmdeploy) 做部署，你可以看一下 onnx 模型测试的[文档](https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/02-how-to-run/profile_model.md)。MMSegmentation 目前只提供了一个导出脚本，没有关于部署的更多内容。

**Comment by wxk514** [comment]
好哒谢谢！
