### ISSUE TITLE
2-classed segmentation, IoU and Acc are 0.0 and nan respectively

### ISSUE THREAD

**Issue by lifan724** [open-mmlab/mmsegmentation#2111]
I set the num_classes==2 to model a 2-classes problem。The "CrossEntropyLoss" and "DiceLoss" both got validatied results show below:
+------------+-------+-------+-------+--------+-----------+--------+
|   Class    |  IoU  |  Acc  |  Dice | Fscore | Precision | Recall |
+------------+-------+-------+-------+--------+-----------+--------+
| background | 95.43 | 98.46 | 97.66 | 97.66  |   96.88   | 98.46  |
|   human    |  0.0  |  nan  |  0.0  |  nan   |    0.0    |  nan   |
+------------+-------+-------+-------+--------+-----------+--------+

where the input label of my dataset is a gray mask with 2 different values 0 and 255. The loss configs is "loss_decode=dict(
            type='DiceLoss', loss_weight=1.0)" or "loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))"

**Comment by MengzhangLI** [comment]
Hi, if you only have one foreground class, I suggest you use binary segmentation with latest MMSegmentation version and check out PR [here](https://github.com/open-mmlab/mmsegmentation/pull/2016).

**Comment by lifan724** [comment]
thx
