### ISSUE TITLE
pytorch2torchscript(dev-1.x)

### ISSUE THREAD

**Issue by chenhongming** [open-mmlab/mmsegmentation#2123]
KeyError: "class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: 'SegDataPreProcessor is not in the model registry.

The scope is 'mmengine' in the registry, however SegDataPreProcessor exists children of the  registry.
![捕获5](https://user-images.githubusercontent.com/29920966/192763324-523c943c-8f40-49ce-bea2-4639783ab93f.JPG)

thank you for your reply.

**Comment by MeowZheng** [comment]
please call `registry_all_modules` first of all

```python
from mmseg.utils import registry_all_modules

registry_all_modules()
```

**Comment by chenhongming** [comment]
Thanks, it's works.

**Comment by raykindle** [comment]
> please call `registry_all_modules` first of all
> 
> ```python
> from mmseg.utils import registry_all_modules
> 
> registry_all_modules()
> ```

应该是加载下面这个模块才对：
```python
from mmseg.utils import register_all_modules

register_all_modules()
```
