### ISSUE TITLE
using wrong gpu when training with single gpu

### ISSUE THREAD

**Issue by yzes** [open-mmlab/mmsegmentation#2127]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when run with single gpu, select gpu 1 ,the model will be put into gpu 0 first. 
My implement is below.
in path mmseg/utils/util_distribution.py
line 27

**    if device == 'cuda':
            model = model.cuda(kwargs['device_ids'][0])
**

hope your better implement, thanks

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by MengzhangLI** [comment]
Hi, you can try to follow this [doc](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/train.md#train-with-a-single-gpu) if you want to train with signle GPU.

**Comment by yzes** [comment]
thanks for your reply, but i run the commond in the doc like below
python tools/train.py myconfig --gpu-id 1
my program should just run on gpu 1 but it use some memory in gpu 0, just like the image
![image](https://user-images.githubusercontent.com/50410784/193193957-bdc530e6-b7db-40be-8551-7a7e3fd1c4f4.png)
and i found the problem is caused by the code in file mmseg/utils/util_distribution.py line 28

**Comment by MengzhangLI** [comment]
OK, copy that.

What happens in `GPU 1` when using `python tools/train.py myconfig --gpu-id 0`?

**Comment by yzes** [comment]
sorry for my late answer
when using `python tools/train.py myconfig --gpu-id 0 `
the programe won't use memory in gpu 1

**Comment by likyoo** [comment]
The same problem. But when I use the version 0.24.1, it works.

**Comment by likyoo** [comment]
And this problem can be temporary solved by `CUDA_VISIBLE_DEVICES=1 python tools/train.py ...`

**Comment by fat-921** [comment]
I meet the same problem. Have you solved it ?
