### ISSUE TITLE
the parameter of  cls_token and pos_embed in  vit  backbone dont study

### ISSUE THREAD

**Issue by liuxingyu123** [open-mmlab/mmsegmentation#2130]
when i  use the mmsegmentation for train ,i found my cls_token and pos_embed in vit is not change after init
the code is 
`self.cls_token = nn.Parameter(torch.zeros(1, 1, self.embed_dim)) 
self.pos_embed = nn.Parameter(torch.zeros(1, self.num_patches + 1, self.embed_dim))`
` trunc_normal_(self.pos_embed, std=.02)
trunc_normal_(self.cls_token, std=.02)`
is the issue because the following code? 
`@property
def no_weight_decay(self):
    return {'pos_embed', 'cls_token'}
`
my environment : mmcv:1.2.3 ,mmseg:0.6.0+

**Comment by xiexinch** [comment]
Hi @liuxingyu123,
Did you implement ViT yourself? We didn't implement ViT in v0.6.0.

**Comment by liuxingyu123** [comment]
fine, thank you for your reply.
