### ISSUE TITLE
Error in the new version of mmseg after opening the training script

### ISSUE THREAD

**Issue by zan-wang** [open-mmlab/mmsegmentation#2139]
Hi, does the new version of mmeg not support training models by itself for now? Is it because I installed mmengine in the wrong way?
Thanks for the new version of mmseg!

root@container-0b2d11bf3c-f7569f8c:~/autodl-tmp/mmsegmentation# python tools/train.py configs/aaa_dualseg/dualseg.py 
Traceback (most recent call last):
  File "tools/train.py", line 7, in <module>
    from mmengine.config import Config, DictAction
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/__init__.py", line 1, in <module>
    raise NotImplementedError('This is a project in development')
NotImplementedError: This is a project in development

**Comment by MengzhangLI** [comment]
Hi, this error usually happened when OpenMMLab 2.0 codebases was developing.

Could you update your environment (MMEngine, MMCV) to the latest version and try again?

**Comment by WangZan0899** [comment]
> Hi, this error usually happened when OpenMMLab 2.0 codebases was developing.
> 
> Could you update your environment (MMEngine, MMCV) to the latest version and try again?

Thank you very much for your advice, the method works great!

By the way, in mmseg under version 1.x, the script that generates the confusion matrix seems to need to pass in the pkl file as one of the arguments. But I don't see any way to generate a pkl file in the current test script. 
Although I also tried to set an extra parameter in the test script like other repositories to facilitate the generation of the pkl script. But unfortunately it fails. 
I think the mask information of each image predicted by the model should be saved in the pkl file, but only mIoU and other indicator information are saved in my pkl file. Can you guys refine the script that generates the confusion matrix? 
Thank you very much!!!

**Comment by MengzhangLI** [comment]
Do you mean this [script](https://github.com/open-mmlab/mmsegmentation/blob/1.x/tools/analysis_tools/confusion_matrix.py)?

**Comment by WangZan0899** [comment]
> Do you mean this [script](https://github.com/open-mmlab/mmsegmentation/blob/1.x/tools/analysis_tools/confusion_matrix.py)?

Yes! 
parser.add_argument(
        'prediction_path', help='prediction path where test .pkl result')
