### ISSUE TITLE
Increase in memory during training

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmsegmentation#2144]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
After the first validation, the memory raise from 8Gb to 20Gb

**Reproduction**

1. What command or script did you run?

   ```none
   ./tools/dist_train.sh local_cfg/mymodel.py 2
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified? Yes, I use my own decode_heads. Yes, I understand
```
_base_ = [
    '../configs/segformer/segformer_mit-b1_512x512_160k_ade20k.py'
]

data_root = "/path_to_ADE/ADEChallengeData2016"
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        data_root=data_root
    ),
    val=dict(
        data_root=data_root
    )
)

log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),]
)

model = dict(
    decode_head=dict(
        type='MyDecodeHead'
    )
)
```

3. What dataset did you use? ADEChallenge2016

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMSegmentation: 0.28.0+2d33a38
```
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
2022-10-06 03:59:15,915 - mmseg - INFO - Iter [15650/160000]	lr: 5.413e-05, eta: 14:07:13, time: 0.349, data_time: 0.005, memory: 8848, decode.loss_ce: 0.6541, decode.acc_seg: 76.4196, loss: 0.6541
2022-10-06 03:59:33,385 - mmseg - INFO - Iter [15700/160000]	lr: 5.411e-05, eta: 14:06:54, time: 0.349, data_time: 0.005, memory: 8848, decode.loss_ce: 0.6932, decode.acc_seg: 74.4584, loss: 0.6932
2022-10-06 03:59:50,901 - mmseg - INFO - Iter [15750/160000]	lr: 5.409e-05, eta: 14:06:35, time: 0.350, data_time: 0.005, memory: 8848, decode.loss_ce: 0.6689, decode.acc_seg: 75.5584, loss: 0.6689
2022-10-06 04:00:08,374 - mmseg - INFO - Iter [15800/160000]	lr: 5.408e-05, eta: 14:06:16, time: 0.349, data_time: 0.005, memory: 8848, decode.loss_ce: 0.6236, decode.acc_seg: 76.8082, loss: 0.6236
2022-10-06 04:00:25,885 - mmseg - INFO - Iter [15850/160000]	lr: 5.406e-05, eta: 14:05:58, time: 0.350, data_time: 0.005, memory: 8848, decode.loss_ce: 0.6543, decode.acc_seg: 76.0040, loss: 0.6543
2022-10-06 04:00:43,338 - mmseg - INFO - Iter [15900/160000]	lr: 5.404e-05, eta: 14:05:39, time: 0.349, data_time: 0.006, memory: 8848, decode.loss_ce: 0.6474, decode.acc_seg: 75.4578, loss: 0.6474
2022-10-06 04:01:00,800 - mmseg - INFO - Iter [15950/160000]	lr: 5.402e-05, eta: 14:05:20, time: 0.349, data_time: 0.006, memory: 8848, decode.loss_ce: 0.6407, decode.acc_seg: 75.9503, loss: 0.6407
2022-10-06 04:01:18,240 - mmseg - INFO - Saving checkpoint at 16000 iterations
2022-10-06 04:01:18,581 - mmseg - INFO - Exp name: laformer_mit-b1_4x2_512x512_160k_ade20k.py
2022-10-06 04:01:18,581 - mmseg - INFO - Iter [16000/160000]	lr: 5.400e-05, eta: 14:05:04, time: 0.356, data_time: 0.006, memory: 8848, decode.loss_ce: 0.6633, decode.acc_seg: 75.8793, loss: 0.6633
2022-10-06 04:06:49,219 - mmseg - INFO - per class results:
........
2022-10-06 04:07:06,599 - mmseg - INFO - Iter [16050/160000]	lr: 5.398e-05, eta: 14:54:10, time: 6.960, data_time: 6.619, memory: 20111, decode.loss_ce: 0.6553, decode.acc_seg: 75.6612, loss: 0.6553
2022-10-06 04:07:24,104 - mmseg - INFO - Iter [16100/160000]	lr: 5.396e-05, eta: 14:53:41, time: 0.350, data_time: 0.006, memory: 20111, decode.loss_ce: 0.6366, decode.acc_seg: 76.1472, loss: 0.6366
2022-10-06 04:07:41,615 - mmseg - INFO - Iter [16150/160000]	lr: 5.394e-05, eta: 14:53:12, time: 0.350, data_time: 0.006, memory: 20111, decode.loss_ce: 0.6853, decode.acc_seg: 74.7578, loss: 0.6853

```
This happens with MMSeg own training as well, I can see it in this training log: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b1_512x512_160k_ade20k/segformer_mit-b1_512x512_160k_ade20k_20220620_112037.log.json

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by MengzhangLI** [comment]
Hi, @iumyx2612 Sorry for late reply. This is a very good question.

After discussion and debug in the past few days, we have drawn a primitive conclusion.

First, this phenomenon is caused by peak memory on validation, it is not REAL memory in training. It is caused by mmcv in MMSeg v0.x only reports peak memory. You could found [here](https://github.com/open-mmlab/mmcv/blob/ea173c9f07f0abf6873d2b7d786fb6411843cf00/mmcv/runner/hooks/logger/text.py#L111). So the memory in log you observed it not what actually is in training.

Furthermore, in MMSeg v1.x, MMEngine introduces `torch.cuda.reset_peak_memory_stats()` (please see [here](https://github.com/open-mmlab/mmengine/blob/main/mmengine/device/utils.py#L26)) so the memory would refresh regularly. And here is my re-implememtation of SegFormer in MMSeg v1.x, you could find in validation the memory increase quickly (from 2168 to 13185) and in next training phase it decreases (to 2169) again:

![image](https://user-images.githubusercontent.com/24582831/195541795-1b95559b-35a4-4992-8b1b-c988a296df01.png)


![image](https://user-images.githubusercontent.com/24582831/195541873-cea6610f-44e2-4d04-aa67-27c946f51cff.png)

We guess it is because in training and validation phase, the input size of ADE20K is different. For most ADE20K dataset config files, in validation/inference, the input images are much longer than training.

Best,

**Comment by iumyx2612** [comment]
> Hi, @iumyx2612 Sorry for late reply. This is a very good question.
> 
> After discussion and debug in the past few days, we have drawn a primitive conclusion.
> 
> First, this phenomenon is caused by peak memory on validation, it is not REAL memory in training. It is caused by mmcv in MMSeg v0.x only reports peak memory. You could found [here](https://github.com/open-mmlab/mmcv/blob/ea173c9f07f0abf6873d2b7d786fb6411843cf00/mmcv/runner/hooks/logger/text.py#L111). So the memory in log you observed it not what actually is in training.
> 
> Furthermore, in MMSeg v1.x, MMEngine introduces `torch.cuda.reset_peak_memory_stats()` (please see [here](https://github.com/open-mmlab/mmengine/blob/main/mmengine/device/utils.py#L26)) so the memory would refresh regularly. And here is my re-implememtation of SegFormer in MMSeg v1.x, you could find in validation the memory increase quickly (from 2168 to 13185) and in next training phase it decreases (to 2169) again:
> 
> ![image](https://user-images.githubusercontent.com/24582831/195541795-1b95559b-35a4-4992-8b1b-c988a296df01.png)
> 
> ![image](https://user-images.githubusercontent.com/24582831/195541873-cea6610f-44e2-4d04-aa67-27c946f51cff.png)
> 
> We guess it is because in training and validation phase, the input size of ADE20K is different. For most ADE20K dataset config files, in validation/inference, the input images are much longer than training.
> 
> Best,

```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```
**Q1.** In validation phase, the size of images in ADE20K is resize to `(img_scale=(2048, 512))`. So the 20Gb is the memory of doing inference by Segformer ( in this case, Segformer-B1) on **one** image right?  
**Q2.** And the 20Gb is only in validation phase right? In next training phase it resets to 8Gb but MMCV forgot to use `torch.cuda.reset_peak_memory_stats()` so the log keeps showing 20Gb? 
**Q3.** Can we have this fix in MMCV next version? Or OpenMMLab team has stopped supporting MMCV? MMEngine has no English documentation so I'm unable to under MMEngine for now

**Comment by strangers66** [comment]
> > Hi, @iumyx2612 Sorry for late reply. This is a very good question.
> > After discussion and debug in the past few days, we have drawn a primitive conclusion.
> > First, this phenomenon is caused by peak memory on validation, it is not REAL memory in training. It is caused by mmcv in MMSeg v0.x only reports peak memory. You could found [here](https://github.com/open-mmlab/mmcv/blob/ea173c9f07f0abf6873d2b7d786fb6411843cf00/mmcv/runner/hooks/logger/text.py#L111). So the memory in log you observed it not what actually is in training.
> > Furthermore, in MMSeg v1.x, MMEngine introduces `torch.cuda.reset_peak_memory_stats()` (please see [here](https://github.com/open-mmlab/mmengine/blob/main/mmengine/device/utils.py#L26)) so the memory would refresh regularly. And here is my re-implememtation of SegFormer in MMSeg v1.x, you could find in validation the memory increase quickly (from 2168 to 13185) and in next training phase it decreases (to 2169) again:
> > ![image](https://user-images.githubusercontent.com/24582831/195541795-1b95559b-35a4-4992-8b1b-c988a296df01.png)
> > ![image](https://user-images.githubusercontent.com/24582831/195541873-cea6610f-44e2-4d04-aa67-27c946f51cff.png)
> > We guess it is because in training and validation phase, the input size of ADE20K is different. For most ADE20K dataset config files, in validation/inference, the input images are much longer than training.
> > Best,
> 
> ```
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(2048, 512),
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> ```
> 
> **Q1.** In validation phase, the size of images in ADE20K is resize to `(img_scale=(2048, 512))`. So the 20Gb is the memory of doing inference by Segformer ( in this case, Segformer-B1) on **one** image right? **Q2.** And the 20Gb is only in validation phase right? In next training phase it resets to 8Gb but MMCV forgot to use `torch.cuda.reset_peak_memory_stats()` so the log keeps showing 20Gb? **Q3.** Can we have this fix in MMCV next version? Or OpenMMLab team has stopped supporting MMCV? MMEngine has no English documentation so I'm unable to under MMEngine for now

Hello, have you solved this problem?
