### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])

### ISSUE THREAD

**Issue by cbwznb** [open-mmlab/mmsegmentation#2149]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

   ```none
   A placeholder for the command.
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by aldazhu** [comment]
@cbwznb 
# version
 The bug can occur in the following several versions.:
 1. mmcv2.0.0rc4, mmsegmentation1.0.0rc6, mmengine0.8.0
 2. mmcv-full1.6.1, mmsegmentation0.27.0

# bug
I tested multiple models including Deeplabv3plus, PSPNet, and UNet. The error occurred when the batch size was set to 1. However, when I increased the batch size to 2, the issue disappeared. (In mmsegmentation 0.27.0, it is referred to as 'samples_per_gpu').
There is a sandbox on my computer that prevents me from copying the configs file and the error message. I'm sorry for the inconvenience.
