### ISSUE TITLE
In RGB-D Segmentation, how to use mmsegmentation to simultaneously load RGB, HHA and its label?

### ISSUE THREAD

**Issue by dddzhzzz** [open-mmlab/mmsegmentation#2152]
Using NUY v2 Dataset as example, I need simultaneously load both RGB and HHA (or depth) as input for model. 
mmsegmentation seems like only loading one type of image and its label but loading two types of images including RGB, HHA and its label.
How can I use mmsegmentation to realize my need?  I need some suggestions.

**Comment by xiexinch** [comment]
Hi @dddzhzzz,
You might overwrite the `load_annotations()` method. https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L137

Then customize the `LoadAnnotation`  pipeline https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/loading.py#L91.

**Comment by dddzhzzz** [comment]
Thank you! I have finished it!
