### ISSUE TITLE
Replacing the trunk with a new network?

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmsegmentation#2161]
2022 segnext semantic segmentation network, updated and registered to mmseg, I will replace the backbone with mobilnetv3, which can be used. Your mobilnetv3 pre-training model is directly used as the backbone network and uses pre-training weights.

**Comment by xiexinch** [comment]
Hi @chen-del,
You might modify the backbone network at the model config, if you would not like to use pre-trained weights, just set `pretrained=None` at the model config.

**Comment by chen-del** [comment]
Hi @xiexinch
Without a pre-trained model, the segmentation effect is basically poor, I mean can I use your main intervention weights and add them to my custom network.

**Comment by xiexinch** [comment]
You need to make sure that the keys of the weight and your custom network can be matched.

**Comment by chen-del** [comment]
OK, thanks
