### ISSUE TITLE
Iteration process

### ISSUE THREAD

**Issue by zjk958162734** [open-mmlab/mmsegmentation#218]
Hello, I would like to ask, in the process of your model training, where is the specific iteration implemented in the file? In addition, since your code framework is too complicated, can you consider some relevant explanation files? ,Thank you.

**Comment by 9p15p** [comment]
From my experience,
It is mainly in segmentor, and the directory is `mmseg/models/segmentors`.
you can find `def forward`,`def forward_train`,`def forward_test` in these class.e.g `encoder_decoder.py`.
