### ISSUE TITLE
Is there a way to get both mIoU and mFScore evaluation results

### ISSUE THREAD

**Issue by AnRanbel** [open-mmlab/mmsegmentation#2188]
Hi,I want to get the evaluation results of mFScore and mIoU at the same time.Is there a way to get it? my mmseg version is 0.24.1.

**Comment by xiexinch** [comment]
Hi @AnRanbel,
For testing, you might run:
```shell
python tools/test.py  configs/xxx  checkpoints/xxx --eval mIoU mFscore
```
For training evaluation, you might add metrics to the config file, default setting at `configs/schedules/schedules_x.py`:
```python
evaluation = dict(interval=8000, metric=['mIoU', 'mFscore'], pre_eval=True)
```
