### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by zjk958162734** [open-mmlab/mmsegmentation#220]
I’m sorry to ask you a mentally handicapped question. Why did it prompt /usr/bin/python: No module named torch.distributed when I was training on Doka? I hope you can answer it, thank you

**Comment by 9p15p** [comment]
It seems you choose the default environment`/usr/bin/python`
You should use open-mmlab's environment.
If you use conda and install requirements correctly,  please input this in you terminal.
```
conda activate open-mmlab
```

and check it
```
which python

# It must be open-mmlab's python . e.g: /home/$USER/anaconda3/envs/open-mmlab/bin/python
# rather than /usr/bin/python
```

**Comment by zjk958162734** [comment]
Hello, I would also like to consult, how to get the name of the picture currently being trained during the training process, because I did not find the relevant code in your dateset function, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmsegmentation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 晚上7:41
收件人:&nbsp;"open-mmlab/mmsegmentation"<mmsegmentation@noreply.github.com&gt;;
抄送:&nbsp;"帅气| 宝贝"<958162734@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmsegmentation] Distributed training (#220)





 
It seems you choose the default environment/usr/bin/python
 You should use open-mmlab's environment.
 If you use conda and install requirements correctly,  please input this in you terminal.
 conda activate open-mmlab  
and check it
 which python # It must be open-mmlab's python . e.g: /home/$USER/anaconda3/envs/open-mmlab/bin/python # rather than /usr/bin/python

**Comment by 9p15p** [comment]
Sorry, I 'm not the contributor.

Maybe, you could add `print(...)` in your dataset's `__getitem__(idx)`, 
If there `return self.prepare_test_img(idx)` in it, e.g.
```  
  def __getitem__(self, idx):
        if self.test_mode:
            return self.prepare_test_img(idx)# todo:这个支路还未调整
        else:
            return self.prepare_train_img(idx)
```
you should add `print(...)` in `def prepare_train_img(self, idx)` to print information you need


the datasets  are usually Declared in directory`mmseg/datasets`
