### ISSUE TITLE
Pascal Context download

### ISSUE THREAD

**Issue by Limingxing00** [open-mmlab/mmsegmentation#2209]
Hi,

I cannot download Pascal Context dataset from [here](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#pascal-context).

This url (http://host.robots.ox.ac.uk/pascal/VOC/voc2010/VOCtrainval_03-May-2010.tar)  may be uncorrected.

Best,

**Comment by MengzhangLI** [comment]
Hi, thanks for your feedback. We noticed that dataset can not be downloaded successfully right now.

![image](https://user-images.githubusercontent.com/24582831/196601099-1a96e76f-f61b-40e8-9d40-5bd545827456.png)

Its IP can be connected but no response. We would update dataset downloading link as soon as possible if Pascal Context can not be downloaded.

**Comment by MeowZheng** [comment]
I can download with this url http://host.robots.ox.ac.uk/pascal/VOC/voc2010/VOCtrainval_03-May-2010.tar, please check again
