### ISSUE TITLE
How to use Dockerfile to build a mmsegmentation project in Docker? 

### ISSUE THREAD

**Issue by dddzhzzz** [open-mmlab/mmsegmentation#2217]
There is a Dockerfile  in mmsegmentation  project. 
How can I use it to build mmsegmentation's environment on Linux?

**Comment by MeowZheng** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/get_started.md#using-mmsegmentation-with-docker

**Comment by dddzhzzz** [comment]
Thank!
