### ISSUE TITLE
DeepLab implementation deviations

### ISSUE THREAD

**Issue by brdav** [open-mmlab/mmsegmentation#222]
Hello,
thanks a lot for the benchmarks! The implementation of DeepLabv3 / DeepLabv3+ deviates slightly from the official TF implementation. Specifically, you are using a 3x3 convolution to merge ASPP branches
https://github.com/open-mmlab/mmsegmentation/blob/8a174a3511df24b9f13055c5cff0c2042291e10c/mmseg/models/decode_heads/aspp_head.py#L84
whereas commonly a 1x1 conv is used to merge, followed by a decoder stage where 3x3 might be used:
https://github.com/tensorflow/models/blob/72a31e9e5c06a663a8ee7ff7cc2a41e20557c9e5/research/deeplab/model.py#L530
Any reason for these changes? I don't know whether it would have an impact on performance, in terms of FLOPS it makes a small difference for DeepLabv3+, as in this implementation a standard 3x3 conv (self.bottleneck) is used, instead of a 1x1.

**Comment by 9p15p** [comment]
the MMsegmentation's code you give seems to belong this
![image](https://user-images.githubusercontent.com/40333030/97981913-f6dcb680-1e0d-11eb-8381-ddcb7c17a0fd.png)

I' m not familiar with TensorFlow.
but according to their names and notes,
It seems that the latter code is about this part :

![image](https://user-images.githubusercontent.com/40333030/97982355-a023ac80-1e0e-11eb-91a7-25024834d85f.png)

**Comment by brdav** [comment]
Yes, the TF code deals with the 1x1 you circled in the lower image. But the 3x3 conv you circled in the upper image would be here in the mmsegmentation code (the image shows DeepLabv3+ so we need to look in sep_aspp_head.py):
https://github.com/open-mmlab/mmsegmentation/blob/f5eb7f2627d1ade09e57a1cea7af7110bc100cdc/mmseg/models/decode_heads/sep_aspp_head.py#L62
So in the mmsegmentation code, self.bottleneck refers to what you circled in the lower image (for DeepLabv3+).
