### ISSUE TITLE
Ignore specified label index in loss calculation – how to use?

### ISSUE THREAD

**Issue by jhaggle** [open-mmlab/mmsegmentation#2223]
I am following this tutorial and use my own custom data-set with two classes plus the background class:
https://github.com/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb

And I am reading about “Training tips” in this tutorial:
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/training_tricks.md

I want to try and set avg_non_ignore=True and ignore_index=0 as discussed in the section "Ignore specified label index in loss calculation". 
I therefore set it in mmsegmentation/configs/_base_/models/pspnet_r50-d8.py in both decode head dictionary and auxiliary_head. However it does not work to set it in auxiliary_head. When try to run the training I get this error:
 
![bild](https://user-images.githubusercontent.com/11705343/197415574-22f3ddf0-0500-46d6-af54-1f0779a1731b.png)

What am I doing wrong? Am I setting it in the wrong place?

If setting it only in decode_head the training works, but the whole image is divided between the two classes so about half the image is segmented as class A and the other half as class B.

**Comment by xiexinch** [comment]
Hi @jhaggle,
The pull request might help. https://github.com/open-mmlab/mmsegmentation/pull/2206/files.

**Comment by MeowZheng** [comment]
this issues is repeated with #2224

**Comment by jhaggle** [comment]
> this issues is repeated with #2224

This is not the same as #2224. This is a more specific question. I have continued trying to solve this issue. My latest attempt is to add those four lines to the config:

```
cfg.model.decode_head.update(dict(ignore_index = 3))
cfg.model.decode_head.loss_decode,update(dict(avg_non_ignore = True))
cfg.model.auxiliary_head.update(dict(ignore_index = 3))
cfg.model.auxiliary_head.loss_decode.update(dict(avg_non_ignore = True))
```

This does NOT work. Adding ONLY the first two lines work however. However, according to the tutorial (referenced above) it all four lines should be added. So please help me understand what causes this error and how it can be solved?
