### ISSUE TITLE
How to use multiple loss functions at different stages

### ISSUE THREAD

**Issue by endaoguansanlu** [open-mmlab/mmsegmentation#2225]
Hello, how should I use multiple loss functions in the training process? In the document, there is only an introduction to the combination of multiple loss functions in the final stage of the model, but if I want to use the first Block and the last Block of ResNet Each uses a loss, how should I do it? Looking forward to your reply！

**Comment by MengzhangLI** [comment]
Use `in_index` of xxx_head to control input of decoder head or auxiliary head, which are also the output feature map of backbone. Take UNet for example, [decoder head](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py#L26)
 is 4 and [auxiliary head](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py#L39) is 3.

**Comment by endaoguansanlu** [comment]
Thanks a lot for your answer! I have another question to ask for your help, can mmseg use multiple auxiliary headers at the same time?

**Comment by MengzhangLI** [comment]
> Thanks a lot for your answer! I have another question to ask for your help, can mmseg use multiple auxiliary headers at the same time?

It can be, here is an example: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/bisenetv2.py#L28-L77

**Comment by endaoguansanlu** [comment]
My problem is solved, thank you for your kind advice！！
