### ISSUE TITLE
怎么加载其他形式的pth啊？

### ISSUE THREAD

**Issue by linshuchar** [open-mmlab/mmsegmentation#2238]

**Comment by linshuchar** [comment]
![1666843765521](https://user-images.githubusercontent.com/49833212/198189787-6f139554-d131-4761-95ad-f285fb83575d.png)

**Comment by MengzhangLI** [comment]
Please use English for global discussion in community.

If you want to load third-party `.pth`, you should check out whether model weight keys of this `.pth` match up with your model defined in ./mmseg/models/.

**Comment by MeowZheng** [comment]
Do you mind telling us, what model you used and which checkpoint (pth file) you would like to load?

**Comment by linshuchar** [comment]
> Do you mind telling us, what model you used and which checkpoint (pth file) you would like to load?

https://github.com/YihengZhang-CV/LPS-Net/blob/main/LPS-Net-S.pth

**Comment by MeowZheng** [comment]
Before loading the model, you should implement LPS-Net.

**Comment by linshuchar** [comment]
> Before loading the model, you should implement LPS-Net.
我已经实现了lps-net,加载初始化模型是设置init-cfg还是在load-from选项加载。
load-from加载时候会缺少backbone.的前缀，并且后面的序号好像对不上

**Comment by linshuchar** [comment]
> Before loading the model, you should implement LPS-Net.

I have implemented lps net. Whether to set init cfg or load from the load from option to load the initialization model.

When loading load from, the prefix "backbone." is missing, and the subsequent serial number seems to be out of alignment

**Comment by linshuchar** [comment]
> Before loading the model, you should implement LPS-Net.
It seems to rewrite init_weights  can be solved

**Comment by MeowZheng** [comment]
I suggest you can load pth file with `torch.load`, it will return a data with dict type, and then you can modify the keys of the dict to match your model
