### ISSUE TITLE
the number of gpu used when training models

### ISSUE THREAD

**Issue by Counter-F** [open-mmlab/mmsegmentation#2240]
Hello, we check these three pretrained models and find they are trained with 2 gpus (shown three figures below).
![图片](https://user-images.githubusercontent.com/60919631/198308618-42b0ac80-be09-498b-a78a-5a7ee7d31a23.png)
![图片](https://user-images.githubusercontent.com/60919631/198308630-14d72547-90f5-4530-ae8c-0cd438476ca7.png)
![图片](https://user-images.githubusercontent.com/60919631/198308644-8049cd9b-57fd-4206-8cc3-24d288cf4a9b.png)

But we notice that in the [https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/model_zoo.md](model_zoo.md), you say  that you use ditributed training with 4 GPUs by defaults ( as shown below). 

**We would like to ask what is the reason to use two gpus in training three aforementioned models?** 
![图片](https://user-images.githubusercontent.com/60919631/198308544-6b28b276-5eae-4054-a437-3149cdea05da.png)

**Comment by MengzhangLI** [comment]
`samples_per_gpu` means the batch numbers on each gpu, so if 4 gpus used and `samples_per_gpu=2`, total batch sizes are  4 x 2 = 8.

Plus, `4 GPUs by default` is no longer accurate, for instance, many transformer models use 8 GPUs by default. You can checkout `log` in each markdown config and checkout detailed infomation.

![image](https://user-images.githubusercontent.com/24582831/198324514-243021d7-905b-4e5b-afd2-481b01cb8984.png)

![image](https://user-images.githubusercontent.com/24582831/198324603-fa1d8124-5049-4ced-ac7e-b10f99b08737.png)

What's more, in MMSegmentation 1.x, we rename our config names, you could tell information by its name. 

https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/configs/swin/swin-tiny-patch4-window7-in1k-pre_upernet_8xb2-160k_ade20k-512x512.py

`8xb2` means 8 GPUs x 2 samplers = 16 batch sizes.

**Comment by Counter-F** [comment]
Sorry to bother again.
What we just wanna know is why gpu_ids= range(0,1), a.k.a only gpu0 is used instead of 4 gpus, typically for these three model. We want to know is there some special reason to set only 1 gpu for those three models?

**Comment by MengzhangLI** [comment]
You should make total batch sizes the same as 4 gpus, i.e., make `samples_per_gpu` is 4 times of our original setting.

**Comment by MeowZheng** [comment]
> Sorry to bother again. What we just wanna know is why gpu_ids= range(0,1), a.k.a only gpu0 is used instead of 4 gpus, typically for these three model. We want to know is there some special reason to set only 1 gpu for those three models?

thanks for your bug report. These three models are very old for mmseg, and the `config` recorded inaccurate `gpu_ids` when training them
https://github.com/open-mmlab/mmsegmentation/blob/b2724da80bf2dc203b3db69497541ad52ce74ba0/tools/train.py#L84
but we have fix it in train.py when training model distributedly
https://github.com/open-mmlab/mmsegmentation/blob/b42c4877672f990733d5a704c907a27047229c61/tools/train.py#L155-L158
