### ISSUE TITLE
last class acc,iou is NaN

### ISSUE THREAD

**Issue by jeonjungho** [open-mmlab/mmsegmentation#2245]
i have a issue that last class acc,iou is NaN 

so i print the 4 things to calculate iou and pixel acc (total_area_intersect, total_area_union, total_area_pred_label, total_area_label)
--below picture is matched in order 4 things

i don't understand how or why last class label pixel is 0 even if last class labels exist in label images

![image](https://user-images.githubusercontent.com/39402598/198915488-9a383bdc-3478-417b-b85a-5ca50d15d35d.png)

**Comment by Zihang-Wei** [comment]
In your dataset class, is `reduce_zero_label = True`?
I also had this problem somehow.
If so, you need to adjust `num_class` of your heads
![image](https://user-images.githubusercontent.com/58259190/199483501-b373e4f4-855d-4d29-8ba4-8cc175096c2f.png)
And delete the background class inside the dataset

**Comment by jeonjungho** [comment]
i use custom dataset that has 19 class and i use 'reduce_zero_label = False' 
but still, i don't solve this problem

**Comment by jeonjungho** [comment]
still don't solve them

i use the segformer b3 with pretrained weight

data config file
mmseg/dataset/mydataset.py
![Screenshot from 2022-11-07 11-20-50](https://user-images.githubusercontent.com/39402598/200213432-97d5c3be-bab7-4d65-8b06-90d70299d35b.png)

config/_base_/datasets/mydataset.py
![Screenshot from 2022-11-07 11-24-06](https://user-images.githubusercontent.com/39402598/200213700-41e70f24-ec7c-4328-8d02-8de2683648df.png)




i convert 11,12,13 class to 1,2,1 so total class num is 19 changing transforms.py (second picture--> train_classdict)


![Screenshot from 2022-11-07 11-34-16](https://user-images.githubusercontent.com/39402598/200214727-94283316-6816-48cc-a988-2cb5883dd2a1.png)
![Screenshot from 2022-11-07 11-34-31](https://user-images.githubusercontent.com/39402598/200214729-f893a538-c08b-4f6c-ac20-09bb873645eb.png)




log file 

[20221031_030307.log](https://github.com/open-mmlab/mmsegmentation/files/9947706/20221031_030307.log)

**Comment by keepgoing365** [comment]
我遇到同样的问题，换了很多种模型还是这个问题。我已解决这个问题：
我的数据集有3类，配置如下
classes=('background','building','street'),  ###label图中像素值依次为0,1,2
palette=[[0,0,0],[120, 120, 120],[255, 255, 0]])

训练前需要将以下文件设置 reduce_zero_label=False 使得忽略label=0的类
1.  .\mmseg\datasets\your_dataset.py
2.  .\mmseg\configs\_base_\datasets\your_dataset.py

改好后训练结果如下：
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background | 67.27 | 95.26 |
|  building      | 14.15 |  17.0  |
|   street         |  4.52  |  4.89  |
+------------+-------+-------+
