### ISSUE TITLE
tools/test.py can't save result images

### ISSUE THREAD

**Issue by lishuang70345** [open-mmlab/mmsegmentation#2248]
使用--show_image参数，test正常，但是不能保存图像，路径已设置。请问有解决方法吗？

**Comment by lishuang70345** [comment]
补充：dev1.x分支

**Comment by xiexinch** [comment]
Hi @lishuang70345,
Thanks for your bug report, we will test it and feedback to you asap.

**Comment by xiexinch** [comment]
Hi @lishuang70345,
你可以在给 `SegVisualizationHook` 设置一个参数 `interval=1`.
https://github.com/open-mmlab/mmsegmentation/blob/1.x/configs/_base_/schedules/schedule_80k.py#L24

然后执行如下命令;
```shell
python tools/test.py configs/xxx checkpoints/xxx --show-dir xxx
```

**Comment by lishuang70345** [comment]
试了，还是不行。也许是我config写的有问题？但是推理都是正常的

**Comment by xiexinch** [comment]
你可以贴一下你跑的命令和config

**Comment by lishuang70345** [comment]
[segformer_mit-b0_8xb2-160k_ade20k-512x512.txt](https://github.com/open-mmlab/mmsegmentation/files/9927786/segformer_mit-b0_8xb2-160k_ade20k-512x512.txt)
我的config，命令为python .\tools\test.py .\work_dirs\segformer\segformer_mit-b0_8xb2-160k_ade20k-512x512.py .\work_dirs\segformer\iter_1600.pth --show --show-dir .\work_dirs\test_images

**Comment by xiexinch** [comment]
你去掉--show试试，只保留 --show-dir

**Comment by lishuang70345** [comment]
谢谢
