### ISSUE TITLE
is there resnet34 pretrained parameters?

### ISSUE THREAD

**Issue by InvokerLiu** [open-mmlab/mmsegmentation#2260]
In the source code of resnet I see that the depth of resnet can be 18, 34, 50, 101 and 152, but when I set the depth parameter of the model to 34 and the pretrained parameter to 'open-mmlab://resnet34_v1c', I get KeyError: 'resnet34_v1c', while when I set the depth parameter to 18 or 50, the pretrained parameter is set to 'open-mmlab://resnet18_v1c' or 'open-mmlab://resnet50_v1c' ，there is no problem

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/mmcls.json#L11

https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/torchvision_0.12.json#L35

You can download pretrained models above and have a try.

**Comment by InvokerLiu** [comment]
Thanks very much, I solved this problem with this information.

**Comment by xiaotian3** [comment]
May I ask how you solve this problem? I loaded the model using the link above, and a dimension mismatch issue occurred after running.

**Comment by xiaotian3** [comment]
> Thanks very much, I solved this problem with this information.

May I ask how you solve this problem? I loaded the model using the link above, and a dimension mismatch issue occurred after running.
