### ISSUE TITLE
segmentors

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#2261]
Using the encorder-decorder structure, I wrote a new decode head, do I need to modify the encorder-decorder.py file in the segmentors

**Comment by MengzhangLI** [comment]
No, if you just add a brand new decoder head, just add it into ./mmseg/models/decode_heads/ and `__init__.py`. But you should ensure shapes of backbone output and decoder head input are matched up.

**Comment by scm-later** [comment]
thank you very much
