### ISSUE TITLE
MAE about the mask ratio

### ISSUE THREAD

**Issue by nicekwow** [open-mmlab/mmsegmentation#2262]
When I wanted to use the MAE algorithm, I found that I couldn't find the code about the mask ratio parameter from the source code. How is the MAE mask strategy implemented in mmseg?

**Comment by MengzhangLI** [comment]
Hi, semantic segmentation is **downstram application** to test MAE performance, MMSegmentation just borrows the pretrained model which is trained with strategy in MAE paper, you can find `mask_ratio` in [MMSelfsup](https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/models/backbones/mae_vit.py#L38).

To sum up, you can modify `mask_ratio` in MMSelfSup to train a different pretrained model and use it in MMSegmentation to test its performance in MMSegmentation.

Best,

**Comment by nicekwow** [comment]
I understand, thank you very much!

**Comment by nicekwow** [comment]
> Hi, semantic segmentation is **downstram application** to test MAE performance, MMSegmentation just borrows the pretrained model which is trained with strategy in MAE paper, you can find `mask_ratio` in [MMSelfsup](https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/models/backbones/mae_vit.py#L38).
> 
> To sum up, you can modify `mask_ratio` in MMSelfSup to train a different pretrained model and use it in MMSegmentation to test its performance in MMSegmentation.
> 
> Best,

I understand, thank you very much!
