### ISSUE TITLE
what is checkpoint file when use model_ensemble.py

### ISSUE THREAD

**Issue by cksdlakstp12** [open-mmlab/mmsegmentation#2264]
Hi. I'm recently using this repository usefully. 
But I don't know what the checkpoint file is, so I'm having a hard time proceeding with the model ensemble.

```
python tools/model_ensemble.py \
  --config ${CONFIG_FILE1} ${CONFIG_FILE2} ... \
  --checkpoint ${CHECKPOINT_FILE1} ${CHECKPOINT_FILE2} ...\   <=== This is what I'm talking about here.
  --aug-test \
  --out ${OUTPUT_DIR}\
  --gpus ${GPU_USED}\
```

How can I get some example of the checkpoint file?
or Is there any document for this file?

**Comment by xiexinch** [comment]
Hi @cksdlakstp12,
The checkpoint files correspond to the config files.

An example:
The config file https://github.com/open-mmlab/mmsegmentation/blob/master/configs/ann/ann_r50-d8_512x1024_40k_cityscapes.py corresponds to the checkpoint https://download.openmmlab.com/mmsegmentation/v0.5/ann/ann_r50-d8_512x1024_40k_cityscapes/ann_r50-d8_512x1024_40k_cityscapes_20200605_095211-049fc292.pth.

**Comment by cksdlakstp12** [comment]
Thank you for your help!
According to your comment, can I use it like below?

`python tools/model_ensemble.py \
  --config ann_r50-d8_512x1024_40k_cityscapes.py ... \
  --checkpoint ann_r50-d8_512x1024_40k_cityscapes_20200605_095211-049fc292.pth ...\  
  --aug-test \
  --out ./my_output \
  --gpus 0, 1, 2 \`

**Comment by cksdlakstp12** [comment]
Thank you for your answer!
I understand how to use model_ensemble.py.
