### ISSUE TITLE
iou code --- compare gt image and result image 

### ISSUE THREAD

**Issue by sunghyun-nam** [open-mmlab/mmsegmentation#2272]
Hello. 

Is there any code to compare gt image and result image?

**Comment by MengzhangLI** [comment]
Hi, I suggest you use new MMSegmentation 1.x version and debug at this [IoU Metric line](https://github.com/open-mmlab/mmsegmentation/blob/1.x/mmseg/evaluation/metrics/iou_metric.py#L65).

**Comment by MeowZheng** [comment]
I suggest you draw the prediction and gt by `SegLocalVisualizer` and please find below doc for more details
https://github.com/open-mmlab/mmsegmentation/blob/1.x/docs/en/user_guides/visualization.md
