### ISSUE TITLE
Training errors on ade20k dataset using lraspp model

### ISSUE THREAD

**Issue by sandstorm666** [open-mmlab/mmsegmentation#2275]
![2022-11-07 21-27-28 的屏幕截图](https://user-images.githubusercontent.com/73341998/200322506-bda92c8c-5b85-44b3-8adf-6ca4087a07a3.png)
![2022-11-07 21-29-12 的屏幕截图](https://user-images.githubusercontent.com/73341998/200322558-3b8740c9-72b7-44aa-86f6-c9cdd2f16e3b.png)
but when I change the dataset from ade20K to cityscapes, it can run! mmcv is 1.3.18,mmsegmentation is 0.19.0.

**Comment by MengzhangLI** [comment]
Could you check your `num_classes` in the model when using ade20k?

Then check whether other default configs(like [pspnet](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/pspnet/pspnet_r50-d8_512x512_80k_ade20k.py)) which use ade20k can run normally.

**Comment by sandstorm666** [comment]
I tried, but failed。
![2022-11-08 14-45-02 的屏幕截图](https://user-images.git
![2022-11-08 14-46-01 的屏幕截图](https://user-images.githubusercontent.com/73341998/200493840-83867d2b-e173-44f1-934e-d0e7c4e8ba85.png)
hubusercontent.com/73341998/200493676-fa02f468-8ee7-4cf9-a51f-9bbb1410a975.png)

**Comment by sandstorm666** [comment]
I tried, but failed。
![2022-11-08 14-45-02 的屏幕截图](https://user-images.githubusercontent.com/73341998/200494033-c71ede3f-53bb-4cde-909d-b4f38b0129b1.png)
![2022-11-08 14-46-01 的屏幕截图](https://user-images.githubusercontent.com/73341998/200494042-1bbbda46-2f96-4213-89c1-59188f637d16.png)

**Comment by MengzhangLI** [comment]
> 

Can other default configs (like [pspnet](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/pspnet/pspnet_r50-d8_512x512_80k_ade20k.py)) which use ade20k run normally?

**Comment by sandstorm666** [comment]
pspnet run successfully.

**Comment by MengzhangLI** [comment]
So it is probably caused by your wrong customization config settings. 

For example, I can directly tell in [lraspp_m-v3-d8.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/lraspp_m-v3-d8.py) there is no auxiliary head but you set `num_classes=150` in your `configs/mobilenent_v3/lraspp_ade20k.py`.

**Comment by sandstorm666** [comment]
thank you. its ok
