### ISSUE TITLE
What is the function of the crop size?

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmsegmentation#2281]
@MeowZheng   What is the function of the crop size? Does the crop size refer to the sliding window clipping image in the training image? Can you directly resize to train your own data set for a fixed size

**Comment by MeowZheng** [comment]
The input image size for training is equal to `crop_size` in `RandomCrop` of data augmentation pipeline
https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/configs/_base_/datasets/ade20k.py#L11
The input size for test is resize scale for example
https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/configs/_base_/datasets/ade20k.py#L23
If you would like to use sliding windows for large image inference, you can set test_cfg in model like
https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/configs/beit/upernet_beit-large_fp16_8x1_640x640_160k_ade20k.py#L22

**Comment by APeiZou** [comment]
@MeowZheng  thanks for your reply
