### ISSUE TITLE
Error when train customer dataset .

### ISSUE THREAD

**Issue by ThorPham** [open-mmlab/mmsegmentation#2283]
I has a dataset with 6 class and when i trained bug appear like this
ValueError: size shape must match input shape. Input is 2D, size is 3
This is a my dataset config
![image](https://user-images.githubusercontent.com/33828708/200763031-8adffdb1-5e47-4ca0-bd5c-6778ca09321b.png)
I traced my bug and bug in line
https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/mmseg/ops/wrappers.py#L27
and i print the "size" in F.interpolate 
![image](https://user-images.githubusercontent.com/33828708/200763573-462b9be7-8927-4202-b0f9-73d071d78688.png)
I don't know why the last shape is different other with 3D dimension
Here is full log bug 
![image](https://user-images.githubusercontent.com/33828708/200763762-f64527ca-a406-478b-9d13-51bf803e61bb.png)
Can you help me fix ?

**Comment by MeowZheng** [comment]
I suggest you print the  `filename` at
https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/mmseg/datasets/pipelines/loading.py#L61
and https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/mmseg/datasets/pipelines/loading.py#L132
I think you might load wrong data

**Comment by ThorPham** [comment]
@MeowZheng here is log :
![image](https://user-images.githubusercontent.com/33828708/200876161-29b7f572-534a-46cd-9a29-7b9ca0e30d56.png)
and here is custom dataset 
![image](https://user-images.githubusercontent.com/33828708/200876390-5b11fa00-fd15-4c70-8bd9-6ab2fe7d44fa.png)
My dataset with 6 class and annotation is format RGB space with extension png with 6 color.

**Comment by ThorPham** [comment]
@jinwonkim93 Yes I write code read image and annotation  and check shape of them. It's ok. Can you help me some other method to test those files.
![image](https://user-images.githubusercontent.com/33828708/201044897-cfa22a18-dd5e-4d97-b30a-450ea63a37eb.png)

**Comment by ThorPham** [comment]
@jinwonkim93 @MeowZheng I know my problem. That is annotation have more than color in PALETTE

**Comment by ThorPham** [comment]
@MeowZheng I just check  shape ofresults.get('gt_semantic_seg') in VOC or coco is 2D. But my dataset is 3D.
Let me know the format dataset for the annotation i should convert

**Comment by jinwonkim93** [comment]
@ThorPham 
Check this issue.
https://github.com/open-mmlab/mmsegmentation/issues/1719

**Comment by ThorPham** [comment]
@jinwonkim93 . I done with issue. Thank you so much

**Comment by RyanYip-Kat** [comment]
![1669016197665](https://user-images.githubusercontent.com/67267063/202991675-d693e754-1f1b-4684-b609-d70178790274.jpg)

In fact, my annotation file is str_mask2, the dimension is also 2D, but after saving as an segmentation file, this error will still be reported? What's the matter, please? thank you

**Comment by ThorPham** [comment]
@RyanYip-Kat can you show log error ?

**Comment by LaBiXiaoChai** [comment]
@RyanYip-Kat You successfully saved a single-channel picture using opencv, but when you re-read, you use a three-channel reading method, so it will be displayed as a three-channel. you can use `cv2.imread("test.png", 0)`
