### ISSUE TITLE
label map issue

### ISSUE THREAD

**Issue by jeonjungho** [open-mmlab/mmsegmentation#2284]
i want to use label_map to change the old id

so i modify the Mydataset(Customdataset) class

![Screenshot from 2022-11-09 16-42-34](https://user-images.githubusercontent.com/39402598/200768631-3608c00d-e7a5-484d-a4f9-ca8f00518e9a.png)

but i got an error 

![Screenshot from 2022-11-09 16-43-57](https://user-images.githubusercontent.com/39402598/200768924-8682031e-f6ba-4da2-976d-f97c054b9fe9.png)

i think my gt-label isn't changed

**Comment by MeowZheng** [comment]
I suggest you check `seg_label` after this line whether it has anything wrong.
https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/mmseg/models/decode_heads/decode_head.py#L261

**Comment by jeonjungho** [comment]
oh i miss  the argument  "self.custom_classes = True"
then solve the problem
