### ISSUE TITLE
How to test a single image？

### ISSUE THREAD

**Issue by TT5an** [open-mmlab/mmsegmentation#2292]
请问，可以直接修改参数去测试单张或者几张不在数据集内的图片吗，如果可以要怎么操作呢

**Comment by MengzhangLI** [comment]
Hi, take my own for example, I usually create a dataset which only has one image. Also, you could checkout [our tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb) which has one image to test model performance, which may help you.

**Comment by TT5an** [comment]
非常感谢您，我已经成功解决了，我在B站刚好看到了mmsegmentation的教学视频，里边也有这个示例。
