### ISSUE TITLE
flake8 no longer exist

### ISSUE THREAD

**Issue by jinwonkim93** [open-mmlab/mmsegmentation#2307]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I am trying to pre-commit and gitlab is asking me to login. so when i check https://gitlab.com/pycqa/flake8.git it shows 404 error.
Is it only me?

**Reproduction**
pre-commit 
1. What command or script did you run?

   ```none
   A placeholder for the command.
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xiexinch** [comment]
Hi @jinwonkim93,
Perhaps we meet the same problem. https://github.com/open-mmlab/mmsegmentation/actions/runs/3468284766/jobs/5793950523#step:5:101

**Comment by jinwonkim93** [comment]
@xiexinch I think changing  https://gitlab.com/pycqa/flake8.git -> https://github.com/PyCQA/flake8.git in .pre-commit-config.yaml will fix the problem.

**Comment by xiexinch** [comment]
Thanks, I create a pr to fix it. #2308  @jinwonkim93
