### ISSUE TITLE
KeyError: 'flip' 

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmsegmentation#231]
When no flip in the pipeline dict, an KeyError will be reported in Collect (mmseg/datasets/pipelines/formating.py line 280)：
KeyError: 'flip' 

I think the code on line 280 should be changed 
from:
        img_meta[key] = results[key]
to:
        img_meta[key] = results.get(key, None)

**Comment by xvjiarui** [comment]
Hi @shuaizzZ 
In this case, you may change the input argument of `meta_keys` of the `Collect` pipeline.

**Comment by mmeendez8** [comment]
This is happening for `CustomDataset` and `test_pipeline` like:

```python
test_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(
        type="MultiScaleFlipAug",
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type="Resize", keep_ratio=keep_ratio),
            dict(type="Normalize", **img_norm_cfg),
            dict(type="ImageToTensor", keys=["img"]),
            dict(type="Collect", keys=["img"]),
        ],
    ),
]
```
Didn't have time to check in depth but it is probably something else than `meta_keys` of the `Collect` pipeline,

**Comment by Junjun2016** [comment]
> This is happening for `CustomDataset` and `test_pipeline` like:
> 
> ```python
> test_pipeline = [
>     dict(type="LoadImageFromFile"),
>     dict(
>         type="MultiScaleFlipAug",
>         img_scale=img_scale,
>         flip=False,
>         transforms=[
>             dict(type="Resize", keep_ratio=keep_ratio),
>             dict(type="Normalize", **img_norm_cfg),
>             dict(type="ImageToTensor", keys=["img"]),
>             dict(type="Collect", keys=["img"]),
>         ],
>     ),
> ]
> ```
> 
> Didn't have time to check in depth but it is probably something else than `meta_keys` of the `Collect` pipeline,

If we use `MultiScaleFlipAug` in test_pipeline, `filp` and `filp_directon` will save in the `aug_data`.

**Comment by mmeendez8** [comment]
Yes, you are right, things are saved here https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/test_time_aug.py#L117

So problem might be due to calling `Collect` inside `MultiScaleFlipAug` transforms, since `flip` tag is not available there yet.

**Comment by Junjun2016** [comment]
> Yes, you are right, things are saved here
> https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/test_time_aug.py#L117
> 
> So problem might be due to calling `Collect` inside `MultiScaleFlipAug` transforms, since `flip` tag is not available there yet.
> 
> Not sure how this is working though...
> https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/ade20k.py#L31
> 
> I need to do further checks

The `transforms` for `MultiScaleFlipAug` are appended after adding `flip` and `flip_direction` keys.
https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/datasets/pipelines/test_time_aug.py#L111-L120

**Comment by lorinczszabolcs** [comment]
> > When no flip in the pipeline dict, an KeyError will be reported in Collect (mmseg/datasets/pipelines/formating.py line 280)： KeyError: 'flip'
> > I think the code on line 280 should be changed from: img_meta[key] = results[key] to: img_meta[key] = results.get(key, None)
> 
> I did this to avoid this error. Is this the recommended solution?

You could also pass the ```meta_keys``` parameters you want to collect to ```Collect``` dict in the config to override the default ones in my opinion.
