### ISSUE TITLE
当label所有像素均为忽略时，label[label != ignore_index] 为空，再max()操作会报 RuntimeError: operation does not have an identity.

### ISSUE THREAD

**Issue by hetianle** [open-mmlab/mmsegmentation#2310]
https://github.com/open-mmlab/mmsegmentation/blob/c4c0c1f80456f2be26350e36d4c6050f24fd7608/mmseg/models/losses/cross_entropy_loss.py#L124

**Comment by xiexinch** [comment]
Hi @hetianle,
请问这是您自定义的数据集吗？这种情况是有些图的 label 全为需要忽略的背景类吗？

**Comment by hetianle** [comment]
@xiexinch 对的，自定义数据集，大概率是random crop的时候 全部crop的图像忽略区域

**Comment by xiexinch** [comment]
Hi @hetianle,
因为不知道你的数据集是什么样的，不知道调大 crop size 能不能解决这个问题。
不过这个确实是一个比较少见的 corner case，如果你有什么解决办法，欢迎提 PR 来修复这个问题。我们也会想办法修复这个 bug。
