### ISSUE TITLE
if dataset support .npy format

### ISSUE THREAD

**Issue by Wuyunfan-BUPT** [open-mmlab/mmsegmentation#2324]
def __init__(self, **kwargs):
        super(TestDataset, self).__init__(
            img_suffix='.npy',
            seg_map_suffix='.npy',
            reduce_zero_label=False,
            **kwargs)
        assert osp.exists(self.img_dir)

I define my dataset, but it is .npy file, and throws error. I want to know if mmsegmentation supprt this format data

**Comment by MengzhangLI** [comment]
Hi, if your .npy format dimension does not > 3 ([this mmcv issue](https://github.com/open-mmlab/mmcv/issues/2066) says `.npy` dimension > 3 is not supported), it could be implemented but you need to add some codes.

you could refer to this [medican image data loading PR](https://github.com/open-mmlab/mmsegmentation/pull/2176), the key lines is [here](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/datasets/transforms/loading.py#L413-L414).
