### ISSUE TITLE
how mmsegmentation put data to gpu?

### ISSUE THREAD

**Issue by medlen** [open-mmlab/mmsegmentation#2328]
Hi, I searched all mmsegmentation codes, and didn't find where mmsegmentation put data to gpu device. Can anyone help me?

**Comment by MengzhangLI** [comment]
We use MMCV to handle data loading, for example, if you use one GPU environment, your model type would be `MMDataParallel`, which inherit DataParallel from torch, it would scatter data to device (such as GPU, 'cuda: 0').

The key line is here: https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/data_parallel.py#L46-L48

**Comment by medlen** [comment]
Thanks.  I get it.
