### ISSUE TITLE
How to train Segformer from scratch? (pretrained =None)

### ISSUE THREAD

**Issue by davodogster** [open-mmlab/mmsegmentation#2329]
Hi guys,

When I try to exclude the weights and train from scratch it gives an error. Can I train it from scratch?

![image](https://user-images.githubusercontent.com/46079516/202952128-14fa4062-3438-44a3-8c98-2def77c74b29.png)

![image](https://user-images.githubusercontent.com/46079516/202952194-b50ae460-8a2b-47ed-8975-8d350740f0cb.png)

When I train it with downloaded weights it works well.

Thanks, Sam

**Comment by MengzhangLI** [comment]
I think you can try to delete the line `init_cfg = xxx` because this error usually happened when your config `.py` file has language error such as missing `,` or `;` in your dict.

You can also see red underline wave in `decode_head`, this is a signal of your wrong config format.

**Comment by davodogster** [comment]
@MengzhangLI Thanks it worked! I had an extra ) and I also deleted the line as recommended.
