### ISSUE TITLE
BUG in U-Net scripts: h_stride, w_stride = self.test_cfg.stride TypeError: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by smttsp** [open-mmlab/mmsegmentation#2337]
https://github.com/open-mmlab/mmsegmentation/blob/1bb58de01ab650d56265804dafea99564452e830/configs/_base_/models/deeplabv3_unet_s5-d16.py#L50

I am a newbie on `mmsegmentation` repo.

When I tried training U-Net using `pytorch > 1.10.0` (didn't try earlier versions but I tried `pytorch==1.11, 1.13`) I am getting the following error. 

[error.log](https://github.com/open-mmlab/mmsegmentation/files/10068729/error.log)

Shortly the error     

```
h_stride, w_stride = self.test_cfg.stride
TypeError: cannot unpack non-iterable int object
```

After installing a bunch of different versions of `cuda, pytorch, mmcv, mmcv-full, mm-segmentation` etc, I figured that the problem was actually in the `_base_/models/*unet*.py` files. 

So, replacing 

```
test_cfg=dict(mode='slide', crop_size=256, stride=170))
```

with

```
test_cfg=dict(mode='slide', crop_size=(256, 256), stride=(170, 170)))
```

resolved my problems. 

Here is where I got the idea for how to solve the issue: https://github.com/open-mmlab/mmsegmentation/issues/948#issuecomment-939725440

**Comment by xiexinch** [comment]
Hi @smttsp,
Thanks for you report. Could you create a PR to fix this problem? At [mmsegmentation/configs/_base_/models/deeplabv3_unet_s5-d16.py](https://github.com/open-mmlab/mmsegmentation/blob/1bb58de01ab650d56265804dafea99564452e830/configs/_base_/models/deeplabv3_unet_s5-d16.py#L50), we put `int` value as a placeholder, and these value modified at the sub configs.

https://github.com/open-mmlab/mmsegmentation/blob/1bb58de01ab650d56265804dafea99564452e830/configs/unet/deeplabv3_unet_s5-d16_128x128_40k_chase_db1.py#L6

**Comment by smttsp** [comment]
@xiexinch, sure, I will do that soon.

**Comment by smttsp** [comment]
@xiexinch, it seems that I don't have permission to push my branch/create PR etc. I followed the guideline:

> 1. fork and pull the latest mmsegmentation
> 2. checkout a new branch (do not use master branch for PRs)
> 3. commit your changes
> 4. create a PR

would you mind checking/granting appropriate access?

**Comment by smttsp** [comment]
@xiexinch, I created a PR.

Not sure of these steps: 

Checklist
1. Pre-commit or other linting tools are used to fix the potential lint issues: No impact on formatting
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness: couldn't find any unit-tests for configs
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMDet3D: No impact
4. The documentation has been modified accordingly, like docstring or example tutorials: I need help with this

**Comment by xiexinch** [comment]
Hi @smttsp,
Thanks for your contribution, I have approved your PR, and it will be merged soon.

**Comment by zhouyeyu** [comment]
configs/_base_/models/fcn_unet_s5-d16.py  why there is still 'int' but not tuple in the latest code?
