### ISSUE TITLE
Does mmsegmentation 1.x still support multi scale test augmentation?

### ISSUE THREAD

**Issue by weiaicunzai** [open-mmlab/mmsegmentation#2342]
Thanks for your great work.

I just wandering if mmseg 1.x still supports multi scale test time augmentation.
I realize that the multi scale test augmentation is in  ```MultiScaleFlipAug``` class. 
But in 1.x,  I have found that in the config file,  ```MultiScaleFlipAug``` is gone, and in  ``` inference```  method,  the  ```if  flip:```  code snippets are also gone.   I can not seem to find it  anywhere else.

So does 1.x still support multi scale test time aug?

**Comment by xiexinch** [comment]
Hi @weiaicunzai,
This feature will be supported in the next release, you might take a look at this PR https://github.com/open-mmlab/mmsegmentation/pull/2184

**Comment by weiaicunzai** [comment]
Thanks.
