### ISSUE TITLE
About Swin's PatchMerging implementation

### ISSUE THREAD

**Issue by NielsRogge** [open-mmlab/mmsegmentation#2350]
Hi,

So I saw mmsegmentation provides a [re-implementation](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/swin.py) of the Swin backbone. However, for the `PatchMerging` (downsampling) block, this implementation differs from the [original one](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation/blob/main/mmseg/models/backbones/swin_transformer.py) in the sense that it uses nn.Unfold (which apparently gives a 25% speedup): https://github.com/open-mmlab/mmsegmentation/blob/1bb58de01ab650d56265804dafea99564452e830/mmseg/models/utils/embed.py#L211. 

However, it also says "Instead, we need to modify pretrained models for compatibility." => could you clarify how exactly one needs to adapt the original implementation to make sure both are compatible?

Cause currently, loading one of the [checkpoints](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation/tree/main#ade20k) the original Swin authors provide into mmsegmentation does not result in correct segmentation maps.

This is related to this issue in mmdetection: https://github.com/open-mmlab/mmdetection/issues/6747

**Comment by NielsRogge** [comment]
Update: I found this which could be useful: https://github.com/open-mmlab/mmdetection/blob/31c84958f54287a8be2b99cbf87a6dcf12e57753/mmdet/models/utils/ckpt_convert.py#L85

**Comment by xiexinch** [comment]
Hi @NielsRogge,
We provide a script to convert the official checkpoints to the mmseg version.

https://github.com/open-mmlab/mmsegmentation/blob/master/tools/model_converters/swin2mmseg.py

**Comment by MengzhangLI** [comment]
Hi, @NielsRogge
We also provided well-converted ckpts URLs from config, like [tiny](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py#L5) and [large](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/swin/upernet_swin_large_patch4_window12_512x512_pretrain_384x384_22K_160k_ade20k.py#L5).

Related PR has useful training results:
https://github.com/open-mmlab/mmsegmentation/pull/1389
https://github.com/open-mmlab/mmsegmentation/pull/1471

**Comment by NielsRogge** [comment]
Thanks! I have found the conversion scripts and it's working now.
