### ISSUE TITLE
a question about channel

### ISSUE THREAD

**Issue by lkyyef** [open-mmlab/mmsegmentation#2351]
Hello, I want to train the segment with four channels of remote sensing data. How should I change the original three channels to four channels?

**Comment by xiexinch** [comment]
Hi @lkyyef,
Do you mean to change the network input channels?
Perhaps you should modify the data loading method and the network input channels.

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/bisenetv1_r18-d32.py#L7

**Comment by lkyyef** [comment]
Thanks for your quick reply!I'll give it a try.

**Comment by lkyyef** [comment]
I tried to put in_ channels are changed to 4, but an error occurs
RuntimeError: Given groups=1, weight of size [768, 4, 16, 16], expected input[2, 3, 512, 512] to have 4 channels, but got 3 channels instead

**Comment by xiexinch** [comment]
Hi @lkyyef,
Could you provide your config file? It might help us to figure out the problems.

**Comment by lkyyef** [comment]
2022-11-29 12:20:09,509 - mmseg - INFO - OpenCV num_threads is `<built-in function getNumThreads>
2022-11-29 12:20:12,542 - mmseg - INFO - Environment info:
------------------------------------------------------------
sys.platform: win32
Python: 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.105
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30145 版
GCC: n/a
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.5.5
MMCV: 1.5.2
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.24.1+
------------------------------------------------------------

2022-11-29 12:20:12,543 - mmseg - INFO - Distributed training: False
2022-11-29 12:20:12,911 - mmseg - INFO - Config:
checkpoint = 'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segmenter/vit_base_p16_384_20220308-96dfe169.pth'
backbone_norm_cfg = dict(type='LN', eps=1e-06, requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=
    'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segmenter/vit_base_p16_384_20220308-96dfe169.pth',
    backbone=dict(
        type='VisionTransformer',
        img_size=(512, 512),
        patch_size=16,
        in_channels=4,
        embed_dims=768,
        num_layers=12,
        num_heads=12,
        drop_path_rate=0.1,
        attn_drop_rate=0.0,
        drop_rate=0.0,
        final_norm=True,
        norm_cfg=dict(type='LN', eps=1e-06, requires_grad=True),
        with_cls_token=True,
        interpolate_mode='bicubic'),
    decode_head=dict(
        type='SegmenterMaskTransformerHead',
        in_channels=768,
        channels=768,
        num_classes=2,
        num_layers=2,
        num_heads=12,
        embed_dims=768,
        dropout_ratio=0.0,
        loss_decode=[
            dict(
                type='CrossEntropyLoss',
                use_sigmoid=True,
                loss_name='loss_bce',
                loss_weight=1),
            dict(type='LovaszLoss', loss_name='loss_lovasz', loss_weight=0)
        ]),
    test_cfg=dict(mode='slide', crop_size=(512, 512), stride=(480, 480)))
dataset_type = 'ADE20KDataset'
data_root = 'data/ade_tif/ADEChallengeData2016'
img_norm_cfg = dict(
    mean=[91.18793, 87.27419, 101.49602],
    std=[51.554977, 50.59908, 62.508698],
    to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
    dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[91.18793, 87.27419, 101.49602],
        std=[51.554977, 50.59908, 62.508698],
        to_rgb=True),
    dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[91.18793, 87.27419, 101.49602],
                std=[51.554977, 50.59908, 62.508698],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=4,
    train=dict(
        type='ADE20KDataset',
        data_root='data/ade_tif/ADEChallengeData2016',
        img_dir='images/training_tif',
        ann_dir='annotations/training',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', reduce_zero_label=False),
            dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[91.18793, 87.27419, 101.49602],
                std=[51.554977, 50.59908, 62.508698],
                to_rgb=True),
            dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=255),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='ADE20KDataset',
        data_root='data/ade_tif/ADEChallengeData2016',
        img_dir='images/validation_tif',
        ann_dir='annotations/validation',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[91.18793, 87.27419, 101.49602],
                        std=[51.554977, 50.59908, 62.508698],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='ADE20KDataset',
        data_root='data/ade_tif/ADEChallengeData2016',
        img_dir='images/validation_tif',
        ann_dir='annotations/validation',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[91.18793, 87.27419, 101.49602],
                        std=[51.554977, 50.59908, 62.508698],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(type='SGD', lr=0.001, momentum=0.9, weight_decay=0.0)
optimizer_config = dict()
lr_config = dict(policy='poly', power=0.9, min_lr=0.0001, by_epoch=False)
runner = dict(type='EpochBasedRunner', max_epochs=2000)
checkpoint_config = dict(by_epoch=True, interval=100)
evaluation = dict(interval=10, metric='mIoU', pre_eval=True)
work_dir = 'E:\lky_daima\logs'
gpu_ids = [0]
auto_resume = False

> 嗨@lkyyef，你能提供你的配置文件吗？它可能有助于我们找出问题所在。

**Comment by xiexinch** [comment]
Hi, @lkyyef,
You might try to modify the image decode backend.

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/loading.py#L36

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/ade20k.py#L8

https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/io.py#L213

The error occurs because the inputs of the network are still images with 3 channels.

**Comment by lkyyef** [comment]
thanks,I'll give it a try.

**Comment by lkyyef** [comment]
I am embarrassed to ask about the details of how to modify. Although I tried various modifications, they were still unsuccessful (data is four channels in tif format)

**Comment by lkyyef** [comment]
I am embarrassed to ask about the details of how to modify. Although I tried various modifications, they were still unsuccessful (data is four channels in tif format)

**Comment by lkyyef** [comment]
[label.zip](https://github.com/open-mmlab/mmsegmentation/files/10120017/label.zip)
I tried to set dict 
```
train_pipeline = [
    dict(type='LoadImageFromFile', backend='tifffile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
    dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
```
 but there was still a problem

>  RuntimeError: Given groups=1, weight of size [768, 4, 16, 16], expected input [2, 3, 512, 512] to have 4 channels, but got 3 channels instead
This is part of my data

**Comment by xiexinch** [comment]
Hi @lkyyef,
Sorry for the late reply.
Could you try to remove the `PhotoMetricDistortion` data augmentation method?

**Comment by lkyyef** [comment]
It really works. Thank you for your help

**Comment by LucasLee-ff** [comment]
Hi @xiexinch,
I still have problem with loading 4-channel image files in .png format. By changing the backend from 'cv2' to 'pillow', the code can successfully load 4-channel images at first. However, the 4-channel image will be automatically converted into 3-channel after the function '_pillow2array' (https://github.com/open-mmlab/mmcv/blob/46eb9ec5d07ea344ed43056d007a7eb71dc3ee98/mmcv/image/io.py#L257)
And changing the code inside '_pillow2array' may have effects on other data processing pipeline. Are there any ways that I can fix this with minimum changes to the mmsegmentation source code? Or will there be an update on this issue in the future? Thank you!
