### ISSUE TITLE
Some doubts on mmsegmentation 1.x

### ISSUE THREAD

**Issue by manpoyang** [open-mmlab/mmsegmentation#2354]
1.Why the per-class validate result cannot be recorded in the log file while it can be recorded on mmseg0.x
![image](https://user-images.githubusercontent.com/35774759/204233597-08a54e0e-a079-48de-a8c2-f5d32fb78d5f.png)
![image](https://user-images.githubusercontent.com/35774759/204233711-5a74cd74-8f39-4773-aadb-7414143870e3.png)

2. Multiple Datasets can be added on mmseg0.x while it cannot on mmseg1.x . And 'split' cannot be used while it is still written on the explanatory note. 

Look forward to your reply！

**Comment by MengzhangLI** [comment]
A1: Yes. In mmseg 1.x the log does not show per-class metric, we would support if it is necessary.

A2: It is because in mmseg 1.x we use `BaseSegDataset` to replace `CustomDataset`, which does not have `split` attribute anymore. `BaseSegDataset` replaces member variable `img_infos` and `split` to `data_list` and `ann_file`, respectively. You can compare mmseg 0.x and 1.x dataset config to use it.

If having any problem when using mmseg 1.x, please contact us, thanks in advance.

**Comment by manpoyang** [comment]
> A1: Yes. In mmseg 1.x the log does not show per-class metric, we would support if it is necessary.
> 
> A2: It is because in mmseg 1.x we use `BaseSegDataset` to replace `CustomDataset`, which does not have `split` attribute anymore. `BaseSegDataset` replaces member variable `img_infos` and `split` to `data_list` and `ann_file`, respectively. You can compare mmseg 0.x and 1.x dataset config to use it.
> 
> If having any problem when using mmseg 1.x, please contact us, thanks in advance.

Thanks for your quick reply!

Q1: I think it is still necessary and look forward to the new version.

Q2: If I have a dataset which contains two different image format, how can I use this dataset. In mmseg 0.x, I can train it using dataset concat like this. But in mmseg 1.x, it seems that I cannot do it this way.

![image](https://user-images.githubusercontent.com/35774759/204238383-e4658659-4465-4aee-a30e-c6a1d80c9b00.png)

Thanks again for your quick reply!

**Comment by manpoyang** [comment]
And another question please!
When I use this code (on Tutorial 3: Inference with existing models) to inference a single image, why this error occurred.

code:
![image](https://user-images.githubusercontent.com/35774759/204241596-4f41acdc-b76b-4c8b-8c43-53a0ac5b287e.png)

error:
![image](https://user-images.githubusercontent.com/35774759/204241679-e3d20fc4-2b3f-4744-a38b-a810e864df20.png)

Look forward to your reply and many thanks！

**Comment by MengzhangLI** [comment]
> > A1: Yes. In mmseg 1.x the log does not show per-class metric, we would support if it is necessary.
> > A2: It is because in mmseg 1.x we use `BaseSegDataset` to replace `CustomDataset`, which does not have `split` attribute anymore. `BaseSegDataset` replaces member variable `img_infos` and `split` to `data_list` and `ann_file`, respectively. You can compare mmseg 0.x and 1.x dataset config to use it.
> > If having any problem when using mmseg 1.x, please contact us, thanks in advance.
> 
> Thanks for your quick reply!
> 
> Q1: I think it is still necessary and look forward to the new version.
> 
> Q2: If I have a dataset which contains two different image format, how can I use this dataset. In mmseg 0.x, I can train it using dataset concat like this. But in mmseg 1.x, it seems that I cannot do it this way.
> 
> ![image](https://user-images.githubusercontent.com/35774759/204238383-e4658659-4465-4aee-a30e-c6a1d80c9b00.png)
> 
> Thanks again for your quick reply!

OK, we would consider add this feature in dev-1.x branch.

It seems your config setting is no longer supported in dev-1.x. Perhaps you should re-format all files to the same format in advance.

**Comment by MengzhangLI** [comment]
> Tutorial 3: Inference with existing models

Sorry for late reply. Could you give me this tutorial URL? If this tutorial exist in our repo, we would fix this error asap.

**Comment by MengzhangLI** [comment]
Hi, @manpoyang the PR for per-class ouput in log has been created in MMEngine:
https://github.com/open-mmlab/mmengine/pull/791
