### ISSUE TITLE
测试图片生成

### ISSUE THREAD

**Issue by zjk958162734** [open-mmlab/mmsegmentation#236]
I have a question, how do I change from the first type to the second type when I generate the test image? In addition, if I want to define the color myself, where should I modify it, thank you.

![frankfurt_000000_000294_leftImg8bit](https://user-images.githubusercontent.com/60846453/98466494-ddbb7780-220a-11eb-93f8-b63aba1ebe31.png)

![frankfurt_000000_000294_gtFine_color](https://user-images.githubusercontent.com/60846453/98466542-24a96d00-220b-11eb-90ce-93c133d66927.png)

**Comment by YLyeliang** [comment]
You should check PALLETE of your own dataset, which is a property of your dataset class. Checkout the mmseg/datasets/your_dataset.py, find the PALLETE, this is the simplest way. The second way is to generate color after inference and draw process. This is implemented in the base segmentor, show_result. 兄弟，maybe this helps.

**Comment by xvjiarui** [comment]
Hi @zjk958162734 
Sorry for the late reply. 
You may try 5 in [this](https://mmsegmentation.readthedocs.io/en/latest/getting_started.html#test-a-dataset) to get original test images.
