### ISSUE TITLE
A question about OHEM

### ISSUE THREAD

**Issue by createhappily** [open-mmlab/mmsegmentation#2360]
Hi, I see that OHEM is belong to training trick. If I use OHEM during training a CNN，can it be attributed to the improvement of the network？

**Comment by MeowZheng** [comment]
It's a little hard for me to understand your question. Do you mean that you got a high performance with OHEM, and you don't know whether OHEM is the secret sauce for the performance? I suggest doing ablation study which is the same network but without OHEM

**Comment by MeowZheng** [comment]
This issue war inactive for a long time, and I'll close it. If anyone has a similar question, just reopen it at any time
