### ISSUE TITLE
The accuracy values start at lower value when I continue the unfinished training by using "Resume_From",

### ISSUE THREAD

**Issue by EnesCeltikk** [open-mmlab/mmsegmentation#2363]
Hello,

I'm training a model with 250000 iterations in Google Colab. Since I don't have a pro membership, I can train the model an average of 8000 steps a day. The next day, when I continue my model from where I left off, the accuracy value of 80% starts from 60% and comes back to 80% after 2000 iterations. Is this normal?

Thank you.

**Comment by xiexinch** [comment]
Hi @EnesCeltikk,
Sorry for the late reply.
You might check the latest checkpoint and training logs at the `work_dir`, perhaps the training program was interrupted without saving a checkpoint, and the training resumed from the latest checkpoint which has an accuracy of 60%.
