### ISSUE TITLE
What is the best practice for using trained segmentation model on other task?

### ISSUE THREAD

**Issue by jinwonkim93** [open-mmlab/mmsegmentation#2365]
Hi, What is the best practice for using trained segmentation model on other task?

For example, if i trained bisenetv2 with mmsegmentation and i want to use this model on other task for making mask input.

I think using apis is not the  best practice because it does not accept torch tensor.

Can you give me an example?

**Comment by MeowZheng** [comment]
we have several projects in mmseg which are the best practices of using mmseg 
https://github.com/open-mmlab/mmsegmentation/tree/1.x#projects
I hope it helps for you
