### ISSUE TITLE
Some wrong with my pytorch2onnx.py

### ISSUE THREAD

**Issue by xu19971109** [open-mmlab/mmsegmentation#2366]
if I set opset-version=11:
`Exporting the operator ::fake_quantize_per_channel_affine to ONNX opset version 11 is not supported. Support for this operator was added in version 13, try exporting with this version.`
if I set opset-version=13:
`orch.onnx.CheckerError: Unrecognized attribute: axes for operator ReduceSum`
orch.onnx.CheckerError: Unrecognized attribute: axes for operator ReduceSum
Context: Bad node spec for node. Name: ReduceSum_949 OpType: ReduceSum
![image](https://user-images.githubusercontent.com/50237122/204993633-a7c1f41a-ea00-4876-b630-2811d0e410a3.png)
How could I fix it?

**Comment by MengzhangLI** [comment]
Hi, @RunningLeon could you have a look at this issue? Thanks!

**Comment by MengzhangLI** [comment]
@xu19971109 You could also raise an issue in MMDeploy. Perhaps they would help you!

Best,
