### ISSUE TITLE
setr_naive_512x512_160k_b16_ade20k.py   for  binary segmentation  occring  Miou =  0

### ISSUE THREAD

**Issue by Lenleooo** [open-mmlab/mmsegmentation#2369]
Hi, when i use setr_naive_512x512_160k_b16_ade20k.py for my binary segmentation task, i found  Miou =  0 and Acc = 0 at the Iter(val) [1000].   (The first Iter(val) [100]  can yield  Miou = 23.3 and Acc = 60.7)      I don't know why. Please help me. Thanks!

1. Here is my  /home/rouch/Projects/pythonProject/mmsegmentation/configs/setr/setr_naive_512x512_160k_b16_ade20k.py:
_base_ = [
    '../_base_/models/setr_naive.py', '../_base_/datasets/leaf.py',
    '../_base_/default_runtime.py', '../_base_/schedules/schedule_160k.py'
]
norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    pretrained=None,
    backbone=dict(
        img_size=(512, 512),
        drop_rate=0.,
        init_cfg=dict(
            type='Pretrained', checkpoint='/home/rouch/Projects/pythonProject/mmsegmentation/pretrain/vit_large_p16.pth')),
    decode_head=dict(num_classes=2),
    auxiliary_head=[
        dict(
            type='SETRUPHead',
            in_channels=1024,
            channels=256,
            in_index=0,
            num_classes=2,
            out_channels=2,
            dropout_ratio=0,
            norm_cfg=norm_cfg,
            act_cfg=dict(type='ReLU'),
            num_convs=2,
            kernel_size=1,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
        dict(
            type='SETRUPHead',
            in_channels=1024,
            channels=256,
            in_index=1,
            num_classes=2,
            out_channels=2,
            dropout_ratio=0,
            norm_cfg=norm_cfg,
            act_cfg=dict(type='ReLU'),
            num_convs=2,
            kernel_size=1,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
        dict(
            type='SETRUPHead',
            in_channels=1024,
            channels=256,
            in_index=2,
            num_classes=2,
            out_channels = 2,
            dropout_ratio=0,
            norm_cfg=norm_cfg,
            act_cfg=dict(type='ReLU'),
            num_convs=2,
            kernel_size=1,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4))
    ],
    test_cfg=dict(mode='slide', crop_size=(512, 512), stride=(341, 341)),
)

optimizer = dict(
    lr=0.01,
    weight_decay=0.0,
    paramwise_cfg=dict(custom_keys={'head': dict(lr_mult=10.)}))

# num_gpus: 8 -> batch_size: 16
data = dict(samples_per_gpu=2)

**Comment by MengzhangLI** [comment]
Hi, hope this [doc](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/faq.md#how-to-handle-binary-segmentation-task) may help you.

Best,

**Comment by Lenleooo** [comment]
Thanks for your answer. However i still can not address the problem. When training ealier, the Miou and Acc is normal. But after hundreds iters, the Miou and Acc scores are tending to 0. 
I try another model like vit, FCN, the results are normal.

**Comment by MengzhangLI** [comment]
> 

I think this phenomenon is very wired. From my point of view, SETR should perform better than FCN in many cases, perhaps some hyperparameters of SETR are not the best match up in your dataset.

To sum up, you can try to find suitable model in your customized cases.

**Comment by Lenleooo** [comment]
Thanks for your reply. when i replace the setr_pup model with setr_naive model, it works! 
As a result, it is maybe a bug in the setr_naive model. 
Thanks for your attention. MMseg is especially useful !
