### ISSUE TITLE
How to convert the pre-training parameters downloaded from the Google website and timm to network parameters in mmsegmentation format

### ISSUE THREAD

**Issue by Liwen-Xiao** [open-mmlab/mmsegmentation#2375]
How to convert the pre-training parameters downloaded from the Google website and timm to network parameters in mmsegmentation format. I tried a lot, but failed. thanks.

**Comment by xiexinch** [comment]
Hi @Liwen-Xiao,
We support using the TIMM models as the backbones. You don't need to convert pre-trained weights.

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/timm_backbone.py

And plenty of models can be downloaded from google drive, could you provide more information?

**Comment by Liwen-Xiao** [comment]
Thank you very much for your reply, the problem is now solved. Once again, I would like to express my gratitude to you&nbsp;


肖力文
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmsegmentation] How to convert the pre-training parameters downloaded from the Google website and timm to network parameters in mmsegmentation format (Issue #2375)





 
Hi @Liwen-Xiao,
 We support using the TIMM models as the backbones. You don't need to convert pre-trained weights.
 
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/timm_backbone.py
 
And plenty of models can be downloaded from google drive, could you provide more information?
