### ISSUE TITLE
MMDataParallel with multi-gpu system

### ISSUE THREAD

**Issue by szatidani** [open-mmlab/mmsegmentation#238]
I would like to train a model on a **single machine with multiple GPUs, not in a distributed** way, but **in the same process**, it is **key** for the application. Similar to DataParallel in Pytorch.
**MMDataParallel** builds on it, but currently it says:
> MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MDistributedDataParallel instead.

By any chance, are you already supporting it, just did not enable it for multiple GPUS? If not, what should be added to make MMDataParallel work with multi GPUs?

Also adding @hjraad. We would appreciate the help. 

Thanks in advance!
@xvjiarui

**Comment by YLyeliang** [comment]
The DistributedDataParallel can be used in the following two ways:

    (1) Single-Process Multi-GPU

    In this case, a single process will be
    spawned on each host/node and each process will operate on all the GPUs
    of the node where it's running. To use ``DistributedDataParallel`` in
    this way, you can simply construct the model as the following:

        >>> torch.distributed.init_process_group(backend="nccl")
        >>> model = DistributedDataParallel(model) # device_ids will include all GPU devices by default

    (2) Multi-Process Single-GPU

    This is the highly recommended way to use ``DistributedDataParallel``, with
    multiple processes, each of which operates on a single GPU. This is
    currently the fastest approach to do data parallel training using PyTorch
    and applies to both single-node(multi-GPU) and multi-node data
    parallel training. It is proven to be significantly faster than
    :class:`torch.nn.DataParallel` for single-node multi-GPU data
    parallel training.

Since MMDistributedDataParallel is inherited from torch.nn.parallel.distributed.xx, It also supports single machine multi-gpu training.

**Comment by szatidani** [comment]
@YLyeliang thanks for the prompt response!

I'm a beginner in the distributed training world, so let me just try to clarify for myself what the above means. In the **(1) case**, the system would only initialize **one "main" process** which will create the **sub-processes,** so **is that right** that they will **share** the **python interprete**r and can access the **same** variables in the **memory**?

 I've read this in the Pytorch documentation, which is a bit concerning for my task, if it would be multi-process
> If using multiple processes per machine with nccl backend, each process must have exclusive access to every GPU it uses, as sharing GPUs between processes can result in deadlocks.

So **only giving the backend** as a parameter and no ranks etc, will **create a single process training** with all the benefits of parallel training on GPU, but restricted back to ~DataParallel (roughly on a high-level)?

One last question, apart from the obvious **speed trade-off** is there **any other negative effects** using DDP like this? Like will it reach **similar performance**? Should any hyper-parameter be **adjusted**?

Thank you for your answers in advance!

**Comment by hjamalirad** [comment]
@YLyeliang : thanks for the note, but this doesn't seem to work in the current pipeline, right? Lacking gather(.) functionality means single process mutli-gpu won't work in MMsegmentation. 
@xvjiarui : we don't have a clear solution to this problem, any hint to @szatidani 's question above? Can you assign this to the right person in Open MMLab group to address? Thanks!

**Comment by JiahaoXia** [comment]
Hey guys, have you solved the problems with multi-GPUs training?

**Comment by xvjiarui** [comment]
Sorry for the late reply. 
For multi-gpu training, non-distributed with MMDP(MMDataParallel) is supported but not test. It won't create processes like distributed training does. It will scatter data to different GPUs and automatically gather them together.
