### ISSUE TITLE
How to add Distributed Modules

### ISSUE THREAD

**Issue by szatidani** [open-mmlab/mmsegmentation#239]
Is there a way in **mmseg to quickly build distributed modules** and **attach** to the existing pipeline? 
I would like to **create a distributed class** that is shared, repeated and synchronized among the processes in the same way as MMDistributedDataParallel model wrapper works. The **goal** is to have a parameter (tensor) that is **being updated based on the total loss** and **synchronized** for all processes. So each process would **access the same tensor**, from which they could make decisions **in every iteration.**

- What modules are there in mmseg to build upon?

Also adding @hjraad. We would appreciate the help.

Thanks in advance!
@xvjiarui

**Comment by xvjiarui** [comment]
Hi @szatidani 
Sorry for the late reply. 
You may try something similar to [this](https://github.com/open-mmlab/mmsegmentation/blob/79d03b15976f3886ab1f43379821227b51b787aa/mmseg/models/decode_heads/ema_head.py#L13-L19).
