### ISSUE TITLE
LoadAnnotation repr typo in 1.x

### ISSUE THREAD

**Issue by whu-pzhang** [open-mmlab/mmsegmentation#2396]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

https://github.com/open-mmlab/mmsegmentation/blob/1.x/mmseg/datasets/transforms/loading.py#L124

The LoadAnnotation repr string lack of several blanks and the braces at wrong position.

When print the Composed transforms, it looks like below. I think it is abnormal

<img width="845" alt="06787c6d241be4e6e41e4582cefd908" src="https://user-images.githubusercontent.com/8895344/206636302-cb9878e7-f4b9-4bdc-9d80-f9a3b849d2b8.png">

**Reproduction**

1. What command or script did you run?

```python
from mmengine.dataset import Compose

sup_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(type='mmseg.LoadAnnotations'),
]

sup_branch = Compose(sup_pipeline)

print(sup_branch)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

no

4. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xiexinch** [comment]
Hi @whu-pzhang,
Thanks for your report, could you create a PR to fix it? We appreciate it a lot.
