### ISSUE TITLE
TypeError: forward_test() missing 1 required positional argument: 'imgs'

### ISSUE THREAD

**Issue by yangxudong9** [open-mmlab/mmsegmentation#24]
Thanks for your work. I want to observe the performance of the model during train. So I changed the workflow from [('train', 1)] to [('train', 10), ('val', 1)] in default_runtime.py. The 'val' of 'IterBasedRunner' will call 'forward_test'. The 'forward_test' require positional argument: 'imgs'. But data_batch doesn't  have 'imgs' key. What should I do?

**Comment by xvjiarui** [comment]
Hi @yangxudong9 
By default, the model will be validated according to `interval` [here](https://github.com/open-mmlab/mmsegmentation/blob/1af2ad6a9f0a69e848c3cf8c307f75120c7f99b6/configs/_base_/schedules/schedule_40k.py#L9). 
In MMSeg, `workflow` should always be  [('train', 1)].

**Comment by yangxudong9** [comment]
@xvjiarui Thanks for your reply.
