### ISSUE TITLE
estimated timeline for 1.x release

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmsegmentation#2407]
Thanks for this repo,

the new 1.x release candidate  looks interresting, 
Is there an estimated timeline about when it will be published as a stable release  ?

**Comment by xiexinch** [comment]
Hi @joihn,
It's a good question. 

@MeowZheng could you help to answer it?

**Comment by joihn** [comment]
Any news  ?

**Comment by MeowZheng** [comment]
We will release it in Q1 2023
