### ISSUE TITLE
要同时测试1万多个图片，结果要全部加载到内存才能开始测试

### ISSUE THREAD

**Issue by York1996OutLook** [open-mmlab/mmsegmentation#241]
怎么样才能读取一部分数据就测试，然后再加载测试呢？不然占用内存太多了

**Comment by YLyeliang** [comment]
测试也是使用的data_loader的方式进行。存的只是所有图片的测试结果，这一部分占不了太多内存才对。

**Comment by zmghub** [comment]
> 怎么样才能读取一部分数据就测试，然后再加载测试呢？不然占用内存太多了

我也碰到了，我的测试集由5w来张，根本装不下，可以改写它的test接口，像其它项目那样，每次forward的结果都提前计算出混淆矩阵，也就只有（N，N）的大小，直到最后inference结束再根据混淆矩阵计算miou等指标就不会出这个问题了。

**Comment by xvjiarui** [comment]
Hi @York1996OutLook 

Please use English or English/Chinese for the issue. 

We will consider saving results in `/tmp` as an option. But we don't have a schedule for it yet.
