### ISSUE TITLE
Documentation issue in MAE tutorial example regarding upernet_mae-base[..].pth"

### ISSUE THREAD

**Issue by AngusG** [open-mmlab/mmsegmentation#2415]
I am attempting to run the "Verify the single-scale results of the model" per documentation here: https://github.com/open-mmlab/mmsegmentation/tree/master/configs/mae and everything works correctly with the exception of being unable to find this checkpoint __upernet_mae-base_fp16_8x2_512x512_160k_ade20k_20220426_174752-f92a2975.pth__. 

The previous step works fine

> python tools/model_converters/beit2mmseg.py https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth pretrain/mae_pretrain_vit_base_mmcls.pth

Any help is appreciated!

**Comment by AngusG** [comment]
Ok, I see that the weights are referenced here https://github.com/open-mmlab/mmsegmentation/blob/master/configs/mae/mae.yml#L23 but the example still doesn't quite work for me as is:

> bash tools/dist_test.sh configs/mae/upernet_mae-base_fp16_8x2_512x512_160k_ade20k.py upernet_mae-base_fp16_8x2_512x512_160k_ade20k_20220426_174752-f92a2975.pth 1 --eval mIoU

Output:
> 2022-12-16 23:51:29,694 - mmseg - INFO - Multi-processing start method is `None`
2022-12-16 23:51:29,695 - mmseg - INFO - OpenCV num_threads is `8
2022-12-16 23:51:29,733 - mmseg - INFO - Loaded 2000 images
INFO:mmseg:Loaded 2000 images
/scratch/ssd/root-mmseg/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:236: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  'Default ``avg_non_ignore`` is False, if you would like to '
load checkpoint from local path: upernet_mae-base_fp16_8x2_512x512_160k_ade20k_20220426_174752-f92a2975.pth
Traceback (most recent call last):
  File "tools/test.py", line 320, in <module>
    main()
  File "tools/test.py", line 222, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/export/mlrg/gallowaa/anaconda2-5.1/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 638, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/export/mlrg/gallowaa/anaconda2-5.1/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 572, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/export/mlrg/gallowaa/anaconda2-5.1/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 314, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/export/mlrg/gallowaa/anaconda2-5.1/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 333, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: upernet_mae-base_fp16_8x2_512x512_160k_ade20k_20220426_174752-f92a2975.pth can not be found.

**Comment by xiexinch** [comment]
> I am attempting to run the "Verify the single-scale results of the model" per documentation here: https://github.com/open-mmlab/mmsegmentation/tree/master/configs/mae and everything works correctly with the exception of being unable to find this checkpoint **upernet_mae-base_fp16_8x2_512x512_160k_ade20k_20220426_174752-f92a2975.pth**.
> 
> The previous step works fine
> 
> > python tools/model_converters/beit2mmseg.py https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth pretrain/mae_pretrain_vit_base_mmcls.pth
> 
> Any help is appreciated!

Hi @AngusG,
The pre-trained weight is used to finetune the segmentation network.

If you would like to verify our results, you might download the checkpoints:

https://download.openmmlab.com/mmsegmentation/v0.5/mae/upernet_mae-base_fp16_8x2_512x512_160k_ade20k/upernet_mae-base_fp16_8x2_512x512_160k_ade20k_20220426_174752-f92a2975.pth
