### ISSUE TITLE
Question about freeze train

### ISSUE THREAD

**Issue by WangZan0899** [open-mmlab/mmsegmentation#2419]
If I want to **freeze some layers of the encoder and some layers of the decoder at the same time**, can you tell me what is the correct way to do it?
I tried to do this by **overriding the train() method in both the encoder and decoder separately**, but I'm not sure if this works, can you give me some correct advice?
I'm not sure **if what I did caused the train() method in the encoder to be overwritten by the train() method in the decoder**.
Thanks~

I did it like this:
#############  in encoder   ###################
```
def train(self, mode=True):
        super(VisionTransformer, self).train(mode)
        if mode:
            self._freeze()
```

#############   in decoder   ###################
```
def train(self, mode=True):
        super(MyDecodeHead, self).train(mode)
        if mode:
            self._freeze()
```

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply. I think you could check out this issue: https://github.com/open-mmlab/mmsegmentation/issues/521

I think you can follow what [swin](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/swin.py#L637-L662) does both in your backbone and decoder head.

Best,
