### ISSUE TITLE
mmsegmentation using mae model with custom training data

### ISSUE THREAD

**Issue by Nirajkanth** [open-mmlab/mmsegmentation#2421]
Hi, Thank you for your amazing work.

I want to implement mae with upernet segmentation model using custom dataset. I followed the following tutorial to generate dataset
tutorial: https://colab.research.google.com/github/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb#scrollTo=eyKnYC1Z7iCV

However, I am getting an error and i couldn't solve it. 

Can you please say what was wrong in my code.  Thank you 

code:
from mmseg.datasets.builder import DATASETS
from mmseg.datasets.custom import CustomDataset

@DATASETS.register_module()
class VisA(CustomDataset):
  CLASSES = classes
  PALETTE = palette
  def __init__(self, split,**kwargs):
    super().__init__(img_suffix='.JPG', seg_map_suffix='.png', 
                     split=split, reduce_zero_label=False, **kwargs)
    assert osp.exists(self.img_dir) and self.split is not None

from mmcv import Config
cfg = Config.fromfile('configs/mae/upernet_mae-base_fp16_8x2_512x512_160k_ade20k.py')

**Error :**
2022-12-20 05:28:39,201 - mmseg - INFO - workflow: [('train', 1)], max: 100 iters
2022-12-20 05:28:39,202 - mmseg - INFO - Checkpoints will be saved to /content/mmsegmentation/work_dirs/tutorial by HardDiskBackend.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-17-1378e34063c8>](https://localhost:8080/#) in <module>
     14 # Create work_dir
     15 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 16 train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
     17                 meta=dict())

16 frames
[/content/mmsegmentation/mmseg/apis/train.py](https://localhost:8080/#) in train_segmentor(model, dataset, cfg, distributed, validate, timestamp, meta)
    192     elif cfg.load_from:
    193         runner.load_checkpoint(cfg.load_from)
--> 194     runner.run(data_loaders, cfg.workflow)

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/iter_based_runner.py](https://localhost:8080/#) in run(self, data_loaders, workflow, max_iters, **kwargs)
    142                     if mode == 'train' and self.iter >= self._max_iters:
    143                         break
--> 144                     iter_runner(iter_loaders[i], **kwargs)
    145 
    146         time.sleep(1)  # wait for some hooks like loggers to finish

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/iter_based_runner.py](https://localhost:8080/#) in train(self, data_loader, **kwargs)
     62         self.data_batch = data_batch
     63         self.call_hook('before_train_iter')
---> 64         outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
     65         if not isinstance(outputs, dict):
     66             raise TypeError('model.train_step() must return a dict')

[/usr/local/lib/python3.8/dist-packages/mmcv/parallel/data_parallel.py](https://localhost:8080/#) in train_step(self, *inputs, **kwargs)
     75 
     76         inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
---> 77         return self.module.train_step(*inputs[0], **kwargs[0])
     78 
     79     def val_step(self, *inputs, **kwargs):

[/content/mmsegmentation/mmseg/models/segmentors/base.py](https://localhost:8080/#) in train_step(self, data_batch, optimizer, **kwargs)
    136                 averaging the logs.
    137         """
--> 138         losses = self(**data_batch)
    139         loss, log_vars = self._parse_losses(losses)
    140 

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py](https://localhost:8080/#) in new_func(*args, **kwargs)
    114                                 f'method of those classes {supported_types}')
    115             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
--> 116                 return old_func(*args, **kwargs)
    117 
    118             # get the arg spec of the decorated method

[/content/mmsegmentation/mmseg/models/segmentors/base.py](https://localhost:8080/#) in forward(self, img, img_metas, return_loss, **kwargs)
    106         """
    107         if return_loss:
--> 108             return self.forward_train(img, img_metas, **kwargs)
    109         else:
    110             return self.forward_test(img, img_metas, **kwargs)

[/content/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py](https://localhost:8080/#) in forward_train(self, img, img_metas, gt_semantic_seg)
    138         """
    139 
--> 140         x = self.extract_feat(img)
    141 
    142         losses = dict()

[/content/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py](https://localhost:8080/#) in extract_feat(self, img)
     64     def extract_feat(self, img):
     65         """Extract features from images."""
---> 66         x = self.backbone(img)
     67         if self.with_neck:
     68             x = self.neck(x)

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

[/content/mmsegmentation/mmseg/models/backbones/mae.py](https://localhost:8080/#) in forward(self, inputs)
    248         outs = []
    249         for i, layer in enumerate(self.layers):
--> 250             x = layer(x)
    251             if i == len(self.layers) - 1:
    252                 if self.final_norm:

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

[/content/mmsegmentation/mmseg/models/backbones/beit.py](https://localhost:8080/#) in forward(self, x)
    223 
    224     def forward(self, x):
--> 225         x = x + self.drop_path(self.gamma_1 * self.attn(self.norm1(x)))
    226         x = x + self.drop_path(self.gamma_2 * self.ffn(self.norm2(x)))
    227         return x

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/batchnorm.py](https://localhost:8080/#) in forward(self, input)
    133 
    134     def forward(self, input: Tensor) -> Tensor:
--> 135         self._check_input_dim(input)
    136 
    137         # exponential_average_factor is set to self.momentum

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/batchnorm.py](https://localhost:8080/#) in _check_input_dim(self, input)
    405     def _check_input_dim(self, input):
    406         if input.dim() != 4:
--> 407             raise ValueError("expected 4D input (got {}D input)".format(input.dim()))
    408 
    409 

ValueError: expected 4D input (got 3D input)

**Comment by xiexinch** [comment]
Hi @Nirajkanth,
Did you make any modifications to the source code?

**Comment by Nirajkanth** [comment]
Hi, Thank you for the reply.  The above error was caused because I made a mistake when I tried to train with the custom dataset. 
I followed the following tutorial for custom training,
https://colab.research.google.com/github/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb 

I set up all the things as mentioned in this notebook and I changed the pretrained weight as mentioned here https://github.com/open-mmlab/mmsegmentation/tree/master/configs/mae 

But, I am getting the following error message in collab and could not solve it yet. 

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group. 

My code is available here, https://colab.research.google.com/drive/1lp7qRL-p7syOjeRq85OrqAWy-svHX1X-?usp=sharing 

Please help me to figure out the issue 
Thank you

**Comment by xiexinch** [comment]
Hi @Nirajkanth,
You might try to modify the norm_cfg of the neck.

https://github.com/open-mmlab/mmsegmentation/issues/2189

**Comment by Nirajkanth** [comment]
I think, there is no such norm_cfg in neck.

Config:
norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='./pretrain/mae_pretrain_vit_base_mmcls.pth',
    backbone=dict(
        type='MAE',
        img_size=(224, 224),
        patch_size=16,
        in_channels=3,
        embed_dims=768,
        num_layers=12,
        num_heads=12,
        mlp_ratio=4,
        out_indices=[3, 5, 7, 11],
        attn_drop_rate=0.0,
        drop_path_rate=0.1,
        norm_cfg=dict(type='LN', eps=1e-06),
        act_cfg=dict(type='GELU'),
        norm_eval=False,
        init_values=1.0),
    neck=dict(type='Feature2Pyramid', embed_dim=768, rescales=[4, 2, 1, 0.5]),
    decode_head=dict(
        type='UPerHead',
        in_channels=[768, 768, 768, 768],
        in_index=[0, 1, 2, 3],
        pool_scales=(1, 2, 3, 6),
        channels=768,
        dropout_ratio=0.1,
        num_classes=4,
        norm_cfg=dict(type='BN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=768,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=4,
        norm_cfg=dict(type='BN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    train_cfg=dict(),
    test_cfg=dict(mode='slide', crop_size=(224, 224), stride=(341, 341)))

This is the final confguration that  I had, (neck=dict(type='Feature2Pyramid', embed_dim=768, rescales=[4, 2, 1, 0.5]),). No norm here.. Can you please cheack ?

**Comment by xiexinch** [comment]
You might add the parameter to the config by yourself.

https://github.com/open-mmlab/mmsegmentation/blob/2cbff70167b9164e2d8bb92451d116936d0fd18c/mmseg/models/necks/featurepyramid.py#L25

**Comment by Nirajkanth** [comment]
Thank you so much for your help. 
I could able to solve by adding cfg to neck  and I was able train the model successfully.

**Comment by Mayolov** [comment]
> Thank you so much for your help. I could able to solve by adding cfg to neck and I was able train the model successfully.

@Nirajkanth If available do you mind sharing your notebook with me? I'm having a few issues.
