### ISSUE TITLE
命令行启动dist_train.sh报错

### ISSUE THREAD

**Issue by Waterman0524** [open-mmlab/mmsegmentation#243]
subprocess.CalledProcessError: Command '['/home/yjh/.conda/envs/pytorch37/bin/python', '-u', './train.py', '--local_rank=3', '4', '--launcher', 'pytorch']' returned non-zero exit status 2.

**Comment by xvjiarui** [comment]
Hi @Waterman0524 
Please use English or English/Chinese for the issue.
Could you please provide more details?

**Comment by Waterman0524** [comment]
您好，非常感谢您能够回复，我目前是一名学生，技术上还有许多问题。我在命令行运行如下命令，想启动分布式训练

产生了如下报错。

但是我在pycharm如果直接运行train.py就是单GPU训练。
然后如果不使用分布式训练的话，dataparallel好像也只支持单机单卡训练
请问这个问题有解决方案吗？
实在感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry Jiarui XU"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 中午12:05
收件人: "open-mmlab/mmsegmentation"<mmsegmentation@noreply.github.com&gt;; 
抄送: "drEZZb"<151478639@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmsegmentation] 命令行启动dist_train.sh报错 (#243)





 
Hi @Waterman0524
 Please use English or English/Chinese for the issue.
 Could you please provide more details?

**Comment by 9p15p** [comment]
I have the same question.if my `sample_per_gpu`>1. 
I don't get this error.

This is my error log
```
/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py:304: UserWarning: "flip_ratio" is deprecated in `RandomFlip.__init__`, please use "prob" instead
  f'"{src_arg_name}" is deprecated in '
/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py:304: UserWarning: "flip_ratio" is deprecated in `RandomFlip.__init__`, please use "prob" instead
  f'"{src_arg_name}" is deprecated in '
2020-11-18 17:09:10,630 - mmseg - INFO - Loaded 94493 images
2020-11-18 17:09:10,824 - mmseg - INFO - Loaded 94493 images
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
2020-11-18 17:09:11,583 - mmseg - INFO - Loaded 95 images
2020-11-18 17:09:11,584 - mmseg - INFO - Loaded 95 images
2020-11-18 17:09:11,584 - mmseg - INFO - Start running, host: lrq@lrq, work_dir: /home/lrq/ldz_project/mmsegmentation_v/work_dirs/stmnet_r50_512*1024_20k_youtubevos
2020-11-18 17:09:11,584 - mmseg - INFO - workflow: [('train', 1)], max: 20000 iters
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 157, in main
    meta=meta)
  File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 190, in train_step
    losses = self(**data_batch)
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 217, in forward
    return self.forward_train(**kwargs)
  File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 432, in forward_train
    MAX_NUM_OBJ)
  File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 135, in _decode_head_forward_train
    max_obj)
  File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/decode_heads/return_seg_decode_head.py", line 236, in forward_train
    max_obj)
  File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/decode_heads/return_seg_decode_head.py", line 170, in Soft_aggregation
    _, H, W = ps.shape
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lrq/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/stmnet/stmnet_r50_512*1024_20k_youtubevos.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

**Comment by Waterman0524** [comment]
您好，我的sample_per_gpu已经是设置的大于1了，还是报了下面这个错误，log如下：
raceback (most recent call last):
&nbsp; File "/home/yjh/.conda/envs/pytorch37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
&nbsp; &nbsp; "__main__", mod_spec)
&nbsp; File "/home/yjh/.conda/envs/pytorch37/lib/python3.7/runpy.py", line 85, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "/home/yjh/.conda/envs/pytorch37/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/home/yjh/.conda/envs/pytorch37/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
&nbsp; &nbsp; cmd=cmd)
subprocess.CalledProcessError: Command '['/home/yjh/.conda/envs/pytorch37/bin/python', '-u', 'train.py', '--local_rank=1']' returned non-zero exit status 1.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmsegmentation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 下午5:13
收件人:&nbsp;"open-mmlab/mmsegmentation"<mmsegmentation@noreply.github.com&gt;;
抄送:&nbsp;"drEZZb"<151478639@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmsegmentation] 命令行启动dist_train.sh报错 (#243)





 
I have the same question.if my sample_per_gpu&gt;1.
 I don't get this error.
 
This is my error log
 /home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py:304: UserWarning: "flip_ratio" is deprecated in `RandomFlip.__init__`, please use "prob" instead   f'"{src_arg_name}" is deprecated in ' /home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py:304: UserWarning: "flip_ratio" is deprecated in `RandomFlip.__init__`, please use "prob" instead   f'"{src_arg_name}" is deprecated in ' 2020-11-18 17:09:10,630 - mmseg - INFO - Loaded 94493 images 2020-11-18 17:09:10,824 - mmseg - INFO - Loaded 94493 images fatal: not a git repository (or any of the parent directories): .git fatal: not a git repository (or any of the parent directories): .git 2020-11-18 17:09:11,583 - mmseg - INFO - Loaded 95 images 2020-11-18 17:09:11,584 - mmseg - INFO - Loaded 95 images 2020-11-18 17:09:11,584 - mmseg - INFO - Start running, host: lrq@lrq, work_dir: /home/lrq/ldz_project/mmsegmentation_v/work_dirs/stmnet_r50_512*1024_20k_youtubevos 2020-11-18 17:09:11,584 - mmseg - INFO - workflow: [('train', 1)], max: 20000 iters Traceback (most recent call last):   File "./tools/train.py", line 161, in <module&gt;     main()   File "./tools/train.py", line 157, in main     meta=meta)   File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/apis/train.py", line 116, in train_segmentor     runner.run(data_loaders, cfg.workflow)   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run     iter_runner(iter_loaders[i], **kwargs)   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train     outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step     output = self.module.train_step(*inputs[0], **kwargs[0])   File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 190, in train_step     losses = self(**data_batch)   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl     result = self.forward(*input, **kwargs)   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func     return old_func(*args, **kwargs)   File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 217, in forward     return self.forward_train(**kwargs)   File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 432, in forward_train     MAX_NUM_OBJ)   File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/segmentors/encoder_mem_decoder.py", line 135, in _decode_head_forward_train     max_obj)   File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/decode_heads/return_seg_decode_head.py", line 236, in forward_train     max_obj)   File "/home/lrq/ldz_project/mmsegmentation_v/mmseg/models/decode_heads/return_seg_decode_head.py", line 170, in Soft_aggregation     _, H, W = ps.shape ValueError: not enough values to unpack (expected 3, got 2) Traceback (most recent call last):   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code     exec(code, run_globals)   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module&gt;     main()   File "/home/lrq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main     cmd=cmd) subprocess.CalledProcessError: Command '['/home/lrq/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/stmnet/stmnet_r50_512*1024_20k_youtubevos.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by zhongqiu1245** [comment]
You can check your the value of your sample_per_gpu. If it is too big, you will get this error.

**Comment by Lsz-20** [comment]
excuse me，I have the same question
I'm Trainning with multiple GPUs,for example:./tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM} [optional arguments] and I have 2 GPUs try to use
Traceback (most recent call last):
  File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/py37_torch1.6/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/SETR/SETR_Naive_768x768_40k_cityscapes_bs_8.py', '--launcher', 'pytorch', '--load-from=./pth/jx_vit_large_p16_384-b3be5167.pth']' returned non-zero exit status 1.

Thanks for your answer！
