### ISSUE TITLE
Segformer-B1 result is not compatible with training log

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmsegmentation#2435]
In the [config](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segformer), Segformer-B1 performance is `42.13|43.74` while in the training log the reported mIoU is `0.4326`

**Comment by MengzhangLI** [comment]
Hi, because it used `ResizeToMultiple`:

```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            # resize image to multiple of 32, improve SegFormer by 0.5-1.0 mIoU.
            dict(type='ResizeToMultiple', size_divisor=32),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

![image](https://user-images.githubusercontent.com/24582831/209660207-191473a8-f2aa-46fb-afe8-d303773b5589.png)

**Comment by iumyx2612** [comment]
> ```python
> ResizeToMultiple
> ```

So the config in the first table of ADE20K results is not compatible with the training log there?  
If I train with [segformer_mit-b1_512x512_160k_ade20k.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b1_512x512_160k_ade20k.py) can I expect to have the results `42.13`?  
In `test_pipeline` we have `MultiScaleFlipAug`, so the reported validation results in training is already ms+flip right?

**Comment by MengzhangLI** [comment]
The checkpoint of `Segformer MIT-B0` is the same, so the training is also the same, but the `test_pipeline` is different, one has `ResizeToMultiple` and the other is not. 

You can try to set 

```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            # resize image to multiple of 32, improve SegFormer by 0.5-1.0 mIoU.
            dict(type='ResizeToMultiple', size_divisor=32),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
``` 

in your config and the result in validation/ test is better than without `ResizeToMultiple` in `test_pipeline`. 

You can learn `train_pipeline` and `test_pipeline` first.

No, `MultiScaleFlipAug` worked if and only if when you setting [`--aug-test` ](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L33) in `./tools/test.py`.

**Comment by iumyx2612** [comment]
> The checkpoint of `Segformer MIT-B0` is the same, so the training is also the same, but the `test_pipeline` is different, one has `ResizeToMultiple` and the other is not.
> 
> You can try to set
> 
> ```python
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(2048, 512),
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             # resize image to multiple of 32, improve SegFormer by 0.5-1.0 mIoU.
>             dict(type='ResizeToMultiple', size_divisor=32),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> ```
> 
> in your config and the result in validation/ test is better than without `ResizeToMultiple` in `test_pipeline`.
> 
> You can learn `train_pipeline` and `test_pipeline` first.
> 
> No, `MultiScaleFlipAug` worked if and only if when you setting [`--aug-test` ](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L33) in `./tools/test.py`.

Sorry I still don't get your explanation. 
So there are two config, one has `ResizeToMultiple` and one does not right?  
The ones tested **with** `ResizeToMultiple` are reported in this table  
![image](https://user-images.githubusercontent.com/69593462/210043901-b22c639b-9e22-4eb0-9639-670a9eaea21a.png)

And the ones tested **without** `ResizeToMultiple` are reported in this table
![image](https://user-images.githubusercontent.com/69593462/210043938-30d0a4bb-352d-4d29-bdd3-1d7cfcbcdc54.png)

Am I correct?

**Comment by iumyx2612** [comment]
And one more question, in original implementation, from Segformer MiT-B2, it use 768 channels in its decoder: https://github.com/NVlabs/SegFormer/blob/master/local_configs/segformer/B2/segformer.b2.512x512.ade.160k.py#L28  
However, MMSeg implementation only uses 256, like B1 and B0 variant: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py
Why is that, and the results is still compatible with 768 channels

**Comment by MengzhangLI** [comment]
> > The checkpoint of `Segformer MIT-B0` is the same, so the training is also the same, but the `test_pipeline` is different, one has `ResizeToMultiple` and the other is not.
> > You can try to set
> > ```python
> > test_pipeline = [
> >     dict(type='LoadImageFromFile'),
> >     dict(
> >         type='MultiScaleFlipAug',
> >         img_scale=(2048, 512),
> >         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
> >         flip=False,
> >         transforms=[
> >             dict(type='Resize', keep_ratio=True),
> >             # resize image to multiple of 32, improve SegFormer by 0.5-1.0 mIoU.
> >             dict(type='ResizeToMultiple', size_divisor=32),
> >             dict(type='RandomFlip'),
> >             dict(type='Normalize', **img_norm_cfg),
> >             dict(type='ImageToTensor', keys=['img']),
> >             dict(type='Collect', keys=['img']),
> >         ])
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in your config and the result in validation/ test is better than without `ResizeToMultiple` in `test_pipeline`.
> > You can learn `train_pipeline` and `test_pipeline` first.
> > No, `MultiScaleFlipAug` worked if and only if when you setting [`--aug-test` ](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L33) in `./tools/test.py`.
> 
> Sorry I still don't get your explanation. So there are two config, one has `ResizeToMultiple` and one does not right? The ones tested **with** `ResizeToMultiple` are reported in this table ![image](https://user-images.githubusercontent.com/69593462/210043901-b22c639b-9e22-4eb0-9639-670a9eaea21a.png)
> 
> And the ones tested **without** `ResizeToMultiple` are reported in this table ![image](https://user-images.githubusercontent.com/69593462/210043938-30d0a4bb-352d-4d29-bdd3-1d7cfcbcdc54.png)
> 
> Am I correct?

The default config does not has `ResizeToMultiple` because this transform would improve performance in test/validation, which makes comparison with other models like PSPNet not fair because default setting does not include `ResizeToMultiple`. 

But SegFomemer does have this transform in its official repo and paper, so we provide two result tables with and without `ResizeToMultiple`. I really suggest you read the paper and the code if you have more questions.

**Comment by MengzhangLI** [comment]
> And one more question, in original implementation, from Segformer MiT-B2, it use 768 channels in its decoder: https://github.com/NVlabs/SegFormer/blob/master/local_configs/segformer/B2/segformer.b2.512x512.ade.160k.py#L28 However, MMSeg implementation only uses 256, like B1 and B0 variant: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py Why is that, and the results is still compatible with 768 channels

Because the most important part of SegFormer is its backbone which uses PVTv2, rather than decode head.

**Comment by iumyx2612** [comment]
Thank you for your answers
