### ISSUE TITLE
The model stucks every 8 iter, waiting a long time to continue

### ISSUE THREAD

**Issue by xu19971109** [open-mmlab/mmsegmentation#2445]
4. Reimplement a custom model with new modules implemented by yourself

**Reproduction**

1. What command or script did you run?
**I tried to reproduce DWRSeg in mmseg encoder and decoder, using torch.nn.conv2d and other torch api. The network can run successfully.But what I  confuse is the model getting stuck every 8 iter for a while(num_worker_per_gpus=8, if I setted num_worker_per_gpus = 6, the model gets stuck every 6 iter.)** 
```
 export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7;./tools/dist_train.sh config 8 --load-from=xxx.pth

```

2. What config dir you run? Did you make any modifications to the code or config? Did you understand what you have modified?

I run the config I defined. The training hyperparameter is copied from another network. I only customize the model parameters such as the kernel size, stride.

4. What dataset did you use?
cityscape

**Environment**
sys.platform: linux
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) [GCC 10.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0a0+8a1a93a
PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.4  (built against CUDA 11.6)
  - Magma 2.6.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.4.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.0a0
OpenCV: 4.5.5
MMCV: 1.6.2
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.7
MMSegmentation: 0.29.0+2a5a348

**Results**
I reduce the batch-size.
![image](https://user-images.githubusercontent.com/50237122/210059797-c350dec5-67fd-45f7-8c3a-3beb04b7fe96.png)

**Comment by xiexinch** [comment]
Hi @xu19971109,
We don't know what your code looks like, so it's hard to locate the problem. Can you provide more information?

**Comment by xu19971109** [comment]
> Hi @xu19971109, We don't know what your code looks like, so it's hard to locate the problem. Can you provide more information?

Thank you, I solved. This problem was caused by my direct augmentation on the original image size.
