### ISSUE TITLE
fastscnn pretrained model link is not valid

### ISSUE THREAD

**Issue by sumenpuyuan** [open-mmlab/mmsegmentation#245]
https://download.openmmlab.com/mmsegmentation/v0.5/fast_scnn/fast_scnn_4x8_80k_lr0.12_cityscapes-f5096c79.pth,这个链接失效了， 麻烦补一下吧~

**Comment by xvjiarui** [comment]
Hi @sumenpuyuan 
We will fix it soon.

**Comment by xvjiarui** [comment]
Fixed.
