### ISSUE TITLE
Getting 0 metric scores when inferencing on test data

### ISSUE THREAD

**Issue by ajinkya-ch** [open-mmlab/mmsegmentation#2455]
I have trained the transformer models for a custom dataset with 2 classes. But when I try testing this model on the test dataset with the same classes, it predicts almost all pixels as background. What can I do to get better results?

**Comment by MengzhangLI** [comment]
Hi, could you show your training log, or is result on validation normal?

And 2 classes segmentation always face wrong config setting problem, please check out this [doc](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/faq.md#how-to-handle-binary-segmentation-task).

**Comment by ajinkya-ch** [comment]
Validation was normal. I got the model working through the 2 class and no sigmoid layer.

**Comment by MengzhangLI** [comment]
> Validation was normal. I got the model working through the 2 class and no sigmoid layer.

So do you mean you have solved this problem?
