### ISSUE TITLE
如何在val和test的时候，对输入的图片进行Pad

### ISSUE THREAD

**Issue by lolikonloli** [open-mmlab/mmsegmentation#2470]
# mmseg 1.x分支
## 遇到的问题
我自定义了一个模型，只能输入正方形的图片，但是我的数据集并不是正方形的，我定义了如下管道，以下是我的`train_pipeline`:
```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(
        type='RandomResize',
        scale=img_scale,
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]
```
`corp_size`是正方形的，训练的时候没问题。
以下是我val和test的`pipeline`
```python
test_val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Pad', size=(384, 384), pad_val={'img': 0, 'seg': 0},),
    dict(type='PackSegInputs')
]
```
我在加载完图片和标签之后使用Pad组件将它们全部填充到正方形，但是在val和test的过程中报错了。
模型可以正确推理，输入和输出的大小都是正方形。
但是不知道为什么在BaseSegmentor的postprocess_result方法中，预测的结果会被重新resize回图片原本的尺寸，导致在后面计算IoU的时候形状对不上报错。
请问我test_val_pipeline哪里有问题吗。

**Comment by xiexinch** [comment]
Hi @lolikonloli,
在 test_pipeline 里把 Pad 删掉，然后在 datapreprocessor 的配置里设置 pad。

https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/models/data_preprocessor.py#L51

https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/configs/mask2former/mask2former_r50_8xb2-160k_ade20k-512x512.py#L14
