### ISSUE TITLE
install mmseg error

### ISSUE THREAD

**Issue by GDbbq** [open-mmlab/mmsegmentation#2478]
![image](https://user-images.githubusercontent.com/86715812/211990699-fe229253-fb07-462d-8337-931687942094.png)

![image](https://user-images.githubusercontent.com/86715812/211990824-3557fb10-0695-4340-90f0-47562ea9f095.png)
![image](https://user-images.githubusercontent.com/86715812/211991060-72f1959c-dd6c-40e9-b9dc-5df88ab1fc9e.png)

**Comment by MengzhangLI** [comment]
You can try to use command [here](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/get_started.md#verify-the-installation) which do not use `--device` args.

**Comment by MeowZheng** [comment]
@MengzhangLI please add `revert_sync_batchnorm` in image_demo.py for users with cpu
