### ISSUE TITLE
分布式训练一个epoch之后就卡住了

### ISSUE THREAD

**Issue by xjtlbc** [open-mmlab/mmsegmentation#249]
用分布式训练跑到一个epoch（固定的迭代次数）之后就卡住了，计算资源消耗变成0。有人遇到过吗

**Comment by YLyeliang** [comment]
你是几卡几机器？

**Comment by xjtlbc** [comment]
> 你是几卡几机器？

2卡的v100

**Comment by YLyeliang** [comment]
能不能发个错误日志




| |
k87974
|
|
邮箱：k87974@163.com
|

Signature is customized by Netease Mail Master

在2020年11月12日 22:53，xjtlbc 写道：

你是几卡几机器？

2卡的v100

**Comment by xjtlbc** [comment]
> 能不能发个错误日志 | | k87974 | | 邮箱：k87974@163.com | Signature is customized by Netease Mail Master 在2020年11月12日 22:53，xjtlbc 写道： 你是几卡几机器？ 2卡的v100 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

没有报错信息，日志就是正常在打，然后停止更新了，就卡住了，然后我用nvidia-smi查看发现显存还在但是计算资源变成0了。

**Comment by xvjiarui** [comment]
Hi @xjtlbc 
Please use English or Chinese/English for the issue. 
You may try to reduce the number of workers by setting `workers_per_gpu=1`.

**Comment by pengqianli** [comment]
same problem
