### ISSUE TITLE
How to train custom datasets in the original U-Net backbone or other original backbones? (Original U-Net paper or different original backbones from their original papers.)

### ISSUE THREAD

**Issue by BenoitKAO** [open-mmlab/mmsegmentation#2495]
Thank you for your marvelous work!

Could you clarify how to train custom datasets in the original U-Net backbone or other original backbones? (Original U-Net paper or different original backbones from their original papers.)

Take U-Net as an example, there are three current methods:
UNet + FCN
UNet + PSPNet
UNet + DeepLabV3

I suppose they all derived from
unet.py
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py

Please describe how to modify the backbone into the original U-Net backbone or other original backbones. (Original U-Net paper or different original backbones from their original papers.)
fcn_unet_s5-d16.py
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py
deeplabv3_unet_s5-d16.py
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/deeplabv3_unet_s5-d16.py
pspnet_unet_s5-d16.py 
https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/pspnet_unet_s5-d16.py

And also,
Could you explain the meaning of the filename of U-Net in detail?
"-S5-D16-"

I would appreciate any help.

Thank you very much again.

**Comment by MengzhangLI** [comment]
"S5" means 5 stages, which has five feature maps. "D16" means stride is 16 which means the minimum feature map is 16 times smaller than original input image size.

![image](https://user-images.githubusercontent.com/24582831/213141806-c41afc85-d53d-4985-9d5b-07b7104969bd.png)


As for UNet + certain model, take DeepLabv3 for example, its decoder head uses these feature map from UNet backbone:

![image](https://user-images.githubusercontent.com/24582831/213141902-2d77fd1e-2741-4ddb-8079-eb64610558d3.png)

**Comment by MeowZheng** [comment]
Q1. how to train custom datasets in original U-Net backbone or other original backbones

please refer to https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_datasets.md

Q2. how to modify the backbone into the original U-Net backbone or other original backbones

please refer to https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_models.md#add-new-backbones

Q3. explain the meaning of the filename of U-Net in detail? like "-S5-D16-"

filename like `pspnet_unet_s5-d16.py` means decoder head is pspnet,  backbone is unet, and @MengzhangLI have explain what "-S5-D16-" is

**Comment by BenoitKAO** [comment]
I appreciate your help very much!

**Comment by LYKlyk** [comment]
I find that the UNet provided in mmsegmentation is inconsistent with the original UNet. On the SUIM dataset (Semantic Segmentation of Underwater Imagery: Dataset and Benchmark), I find that the performance of “unet-s5-d16_*” is lower than that of "fcn_ R50-d8" (8  IoU points). May I ask if it is possible to provide a backbone network that is consistent with the original UNet?
