### ISSUE TITLE
Training in stages with a single config file

### ISSUE THREAD

**Issue by siddancha** [open-mmlab/mmsegmentation#2499]
Suppose I wanted to train my model in stages. For example, in the first stage, I want to freeze the pre-trained backbone and finetune the decoder for $N_1$ epochs. In the second stage, I want to train the entire model end-to-end for $N_2$ epochs. Is there a way to specify training in stages in a single config file?

Thanks!

**Comment by MeowZheng** [comment]
It is a little hard for dynamic training with a single cfg file.

I suggest you can train twice with 2 config files. You can follow the steps:
1. freeze backbone and train decoder
2. save the model checkpoint
3. un-freeze backbone and load the checkpoint and train the model.

**Comment by siddancha** [comment]
Thanks!
