### ISSUE TITLE
Does Segformer (or mmsegmentation in general) throw away training images with no label?

### ISSUE THREAD

**Issue by jackkwok** [open-mmlab/mmsegmentation#2501]
My CustomDataset has a mixed of images with non-zero segmentation masks and images where the mask is all zeros (i.e. no object).  Does Segformer (or mmsegmentation in general) throw away training images with all-zero segmentation masks?

Thanks.

**Comment by MengzhangLI** [comment]
Hi, MMSegmentation would treat every input images the same in training. So, it would not throw away training images with all-zero segmentation masks. You could fiter these images in dataset preparation.

**Comment by jackkwok** [comment]
Thanks.
