### ISSUE TITLE
FileNotFoundError: pretrain/mit_b5_mmseg.pth can not be found.

### ISSUE THREAD

**Issue by fangli333** [open-mmlab/mmsegmentation#2512]
hi, anyone know where I can find this checkpoint?

**Comment by MengzhangLI** [comment]
Hi, it can be downloaded automatically in new version of MMSegmentation.

You can download it [here](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py#L3).

Please remember to rename as `mit_b5.pth` and move it to `pretrain` folder.

Best,

**Comment by Wangchaoyi1998** [comment]
> Please remember to rename as `mit_b5.pth` and move it to `pretrain` folder.
hi,what is the absolute path to the 'pretrain' folder?
