### ISSUE TITLE
关于decode_foward的一些想法

### ISSUE THREAD

**Issue by zmghub** [open-mmlab/mmsegmentation#254]
# Describe the feature

**Motivation**
1. 由于其它损失函数比如refine loss，计算时会需要传入原图用以计算梯度，而现在的接口设计中：
encoder_decoder的forward_train给了参数kwargs可以传入原图，但相应的_decode_head_forward_train接口、decode_head的forward_train接口以及losses接口却都不支持传入其它参数，从而使得添加新的loss只好重写decode_head与encoder_decoder的接口。或者有什么好的建议可以实现这个功能吗？

**Comment by 9p15p** [comment]
没看懂你说的，建议新开一个文件当做修改版。

**Comment by xvjiarui** [comment]
Please use English or Chinese/English for the issue. 

We plan to refactor data pipeline next month.
