### ISSUE TITLE
【Help】Where is the conversion code of PALETTE -> label mask in custom dataset?

### ISSUE THREAD

**Issue by work-zhangzhe** [open-mmlab/mmsegmentation#2556]
I feel that the implementation of PALETTE -> label mask in the custom dataset is not very robust. In some cases, the conversion of PALETTE -> label mask will go wrong, but I can't find where the code is...

**Comment by MengzhangLI** [comment]
Hi, what do you mean "the implementation of PALETTE -> label mask"?

The palette is used for visualization, which is not used for prediction or loss calculation.
