### ISSUE TITLE
Calculate fps transmission exception

### ISSUE THREAD

**Issue by hanknewbird** [open-mmlab/mmsegmentation#2559]
After running the model using mmsegmentation, I found that the printout is as follows. This project is a binary split task. I checked the document and issues, and found that the same type of sending is not found. What should I do?

code:
- python tools/benchmark.py work_dir/bisenetv2/bisenetv2_test.py work_dir/bisenetv2/iter_6000.pth
----------------------------------------
print:
RuntimeWarning: Mean of empty slice. out=out, **kwargs)
RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount)
RuntimeWarning: Degrees of freedom <= 0 for slice **kwargs)
RuntimeWarning: invalid value encountered in true_divide subok=False)
RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount)
Average fps of 1 evaluations: nan
The variance of 1 evaluations: nan

**Comment by xiexinch** [comment]
Hi @hanknewbird,
Did you modify any codes?

**Comment by hanknewbird** [comment]
No, I didn't modify the original code. I checked the source code and found that I still need to add -- log-interval parameter, but I didn't see it in the document. Maybe I didn't find it. The following is the command when I tested FPS. You can execute the following, which should be OK
`python tools/benchmark.py work_dir/bisenetv2/bisenetv2_test.py work_dir/bisenetv2/iter_6000.pth --log-interval 1 --repeat-times 1`

**Comment by xiexinch** [comment]
Which version of mmseg did you use?

I can't reproduce the error.

```shell
# mmseg v1.0.0rc5
python tools/analysis_tools/benchmark.py configs/bisenetv2/bisenetv2_fcn_4xb4-160k_cityscapes-1024x1024.py checkpoints/bisenetv2_fcn_4x4_1024x1024_160k_cityscapes_20210902_015551-bcf10f09.pth  --log-interval 1 --repeat-times 1
```

**Comment by hanknewbird** [comment]
> Which version of mmseg did you use?
> 
> I can't reproduce the error.
> 
> ```shell
> # mmseg v1.0.0rc5
> python tools/analysis_tools/benchmark.py configs/bisenetv2/bisenetv2_fcn_4xb4-160k_cityscapes-1024x1024.py checkpoints/bisenetv2_fcn_4x4_1024x1024_160k_cityscapes_20210902_015551-bcf10f09.pth  --log-interval 1 --repeat-times 1
> ```

The mmseg version I use is 0.30.0
![image](https://user-images.githubusercontent.com/69323595/221086573-8f3b3646-940b-487d-9a4b-6844ea097168.png)
I see that the code you use feels different. I use tools/benchmark. py, while you use tools/analysis_ Tools/benchmark. py, may be the reason for the version. I suggest you look at the source code of your version first, rather than directly changing the version，or can you show me your error information, and maybe I can help you see the problem?

**Comment by xiexinch** [comment]
I test mmsegv0.30.0 with the following command:
```shell
python tools/benchmark.py configs/bisenetv2/bisenetv2_fcn_4x4_1024x1024_160k_cityscapes.py checkpoints/bisenetv2_fcn_4x4_1024x1024_160k_cityscapes_20210902_015551-bcf10f09.pth --log-interval 1 --repeat-times 1
```

results:
```shell
Done image [199/ 200], fps: 42.59 img / s
Done image [200/ 200], fps: 42.58 img / s
Overall fps: 42.58 img / s

Average fps of 1 evaluations: 42.58
The variance of 1 evaluations: 0.0
```
