### ISSUE TITLE
mmsegmentation\tools\confusion_matrix.py run err

### ISSUE THREAD

**Issue by Yangyang-luo702** [open-mmlab/mmsegmentation#2564]
I run mmsegmentation\tools\test.py and I set the code "parser.add_argument('--out',default='0204_upernet_Focalloss.pickle',help='output result file in pickle format') ",and it out put this .pkl file.
But when I want to get the confusion_matrix, the code     
if isinstance(results[0], np.ndarray):
        pass
    else:
        raise TypeError('invalid type of prediction results')
raise error:TypeError: invalid type of prediction results
What‘ should I do?

**Comment by xiexinch** [comment]
Hi @Yangyang-luo702,
Could you provide more information to us for reproducing the error? The running envs, mmseg versions, the codes you modified and etc.

**Comment by Yangyang-luo702** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmsegmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmsegmentation] mmsegmentation\tools\confusion_matrix.py run err (Issue #2564)





 
Hi @Yangyang-luo702,
 Could you provide more information to us for reproducing the error? The running envs, mmseg versions, the codes you modified and etc.

**Comment by Yangyang-luo702** [comment]
Thanks, I have solved this problem






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmsegmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmsegmentation] mmsegmentation\tools\confusion_matrix.py run err (Issue #2564)





 
Hi @Yangyang-luo702,
 Could you provide more information to us for reproducing the error? The running envs, mmseg versions, the codes you modified and etc.

**Comment by Lenleooo** [comment]
i have also encountered this problem, could you tell me how to solve it? thanks!

**Comment by shenxiangkei** [comment]
> Thanks, I have solved this problem
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-mmlab/mmsegmentation" ***@***.***&gt;; 发送时间:&nbsp;2023年2月23日(星期四) 晚上6:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [open-mmlab/mmsegmentation] mmsegmentation\tools\confusion_matrix.py run err (Issue #2564) Hi @Yangyang-luo702, Could you provide more information to us for reproducing the error? The running envs, mmseg versions, the codes you modified and etc. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

i have also encountered this problem, could you tell me how to solve it? thanks!

**Comment by Yangyang-luo702** [comment]
你可以添加我的QQ:1337237127，然后我再具体跟你说，它有一点小复杂。



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 16, 2023 20:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmsegmentation]mmsegmentation\tools\confusion_matrix.py run err (Issue #2564)




  
Thanks, I have solved this problem
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-mmlab/mmsegmentation" @.&gt;; 发送时间:&nbsp;2023年2月23日(星期四) 晚上6:48 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [open-mmlab/mmsegmentation] mmsegmentation\tools\confusion_matrix.py run err (Issue #2564) Hi @Yangyang-luo702, Could you provide more information to us for reproducing the error? The running envs, mmseg versions, the codes you modified and etc. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
i have also encountered this problem, could you tell me how to solve it? thanks!

**Comment by shenxiangkei** [comment]
Thank you very much for your reply, the problem has been solved.
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/17/2023 12:26
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [open-mmlab/mmsegmentation] mmsegmentation\tools\confusion_matrix.py run err (Issue #2564)
        
      
    
  

你可以添加我的QQ:1337237127，然后我再具体跟你说，它有一点小复杂。







---Original---

From: ***@***.***&gt;

Date: Sun, Apr 16, 2023 20:01 PM

To: ***@***.***&gt;;

Cc: ***@***.******@***.***&gt;;

Subject: Re: [open-mmlab/mmsegmentation]mmsegmentation\tools\confusion_matrix.py run err (Issue #2564)









  

Thanks, I have solved this problem

 …

 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-mmlab/mmsegmentation" @.&gt;; 发送时间:&nbsp;2023年2月23日(星期四) 晚上6:48 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [open-mmlab/mmsegmentation] mmsegmentation\tools\confusion_matrix.py run err (Issue #2564) Hi @Yangyang-luo702, Could you provide more information to us for reproducing the error? The running envs, mmseg versions, the codes you modified and etc. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;

  

i have also encountered this problem, could you tell me how to solve it? thanks!
