### ISSUE TITLE
MMsegmentation 1.x issue with `epochBasedTrainLoop`

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmsegmentation#2566]
I'm training on 1.x (RC) with the `epochBasedTrainLoop` instead of iterBased (because of personnal preference)
there is a few issue :
- the checkpoint are never saved
- validation never happens
- ETA goes into negative after 1 epoch `eta: -1 day,`

Here is a subset of my config :
```
train_cfg = dict(
    _delete_=True,
    type='EpochBasedTrainLoop', max_epochs=200, val_interval=1, val_begin=True)
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50, log_metric_by_epoch=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', by_epoch=True, interval = 1),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='SegVisualizationHook', draw=True, interval=1))
```

Everything works when using the `IterBasedTrainLoop`

**Comment by He-Yingchao** [comment]
I have the same problem with you. Have you solved it?

**Comment by joihn** [comment]
workaround : Just use the iter based loop, and do the math yourself to achieve the desired amount of epoch

**Comment by He-Yingchao** [comment]
Refer to: https://github.com/open-mmlab/mmengine/pull/926. Solved it!
