### ISSUE TITLE
Support Mapillary Dataset

### ISSUE THREAD

**Issue by Shallow2000** [open-mmlab/mmsegmentation#2572]
Thanks for your useful repository! I wonder why the repo does not support a widely used semantic segmentation dataset--Mapillary. Could you please add this dataset to your repo for a better ecosystem?  Moreover, we try to reproduce the result of ocrnet+hrnetv2 on Mapillary based on your repo but get rather worse result than https://github.com/NVIDIA/semantic-segmentation. Could you please provide several detailed support about Mapillary  implementation based on the repo? Or can the result can achieve 61.05 as  https://github.com/NVIDIA/semantic-segmentation shows?
Thank you very much!

**Comment by xiexinch** [comment]
Hi @Shallow2000,
We support it at the `projects` and it'll be moved to core lib soon. 
https://github.com/open-mmlab/mmsegmentation/tree/dev-1.x/projects/mapillary_dataset
