### ISSUE TITLE
请问为什么pytorch2onnx中dynamic_axes的batch size在axes=1上

### ISSUE THREAD

**Issue by hnsywangxin** [open-mmlab/mmsegmentation#2574]
最近在用triton部署onnx模型，出现了一些问题，运用动态batch的时候，batch size的维度顺序对应不上，我看大家基本上把batch维度放置在axes=0上，如下图：
<img width="464" alt="image" src="https://user-images.githubusercontent.com/18531174/217526216-f6d4a804-3a5f-4de9-80e2-0714cb4c909b.png">
但是mmseg却是放在axes=1上，如下
`'output': {
                    1: 'batch',
                    2: 'height',
                    3: 'width'
                }`
我用polygraphy工具看了输出如下：
<img width="412" alt="image" src="https://user-images.githubusercontent.com/18531174/217554000-7f0ddce4-4874-4c92-b5b8-b90ff029b49b.png">
triton必须要求batch在axes=0，请问有什么好的办法可以将shape转换成`shape=( 'batch', 1, 'height', 'width')`这种吗
期待您的回复，非常感谢

**Comment by RunningLeon** [comment]
@hnsywangxin Hi, you  could get it done by easily changing following codes to：
https://github.com/open-mmlab/mmsegmentation/blob/8ea3ea39ee747f3393b3798deb62b1ff36f8bcde/mmseg/models/segmentors/encoder_decoder.py#L271-L275

### changed codes, which is also implemented by [rewriter ](https://github.com/open-mmlab/mmdeploy/blob/f5a05b52191e19d67225f332c19dfd53dac55843/mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py#L31)in mmdeploy
```         # our inference backend only support 4D output
            seg_pred = seg_logit.argmax(dim=1, keepdim=True))
        if torch.onnx.is_in_onnx_export():
            return seg_pred
```

Finally, welcome to use [mmdeploy](https://github.com/open-mmlab/mmdeploy) for deployment of openmmlab models. The deployment tools in mmseg would be removed in the near future.

**Comment by hnsywangxin** [comment]
@RunningLeon 非常感谢您，确实跟您说的一样，pytorch2onnx.py转换onnx存在问题，我用mmdeploy已经能正确生成，谢谢
