### ISSUE TITLE
How to visualize the feature map in the middle layer of a model

### ISSUE THREAD

**Issue by caodroid** [open-mmlab/mmsegmentation#258]
Hi，I want to visualize or save the feature map in specific layers or modules so that  I can analyze the data distribution of the feature map，like attention map after self-attention module，or output of aspp module，so is there any method or api to do this？ thank you！

**Comment by xvjiarui** [comment]
Hi @caodroid 

Currently, there is no api for that. 

You may refer to [this example](https://github.com/xvjiarui/mmdetection/blob/gcnet_vis/tools/vis.py) which visualize the attention map of GCNet.
