### ISSUE TITLE
How to use TTA in mmsegv1.0

### ISSUE THREAD

**Issue by erdi-kilic** [open-mmlab/mmsegmentation#2580]
I want to apply TTA during inference. I did not see any documentation that I can follow.

I am getting an error when I tried [this](https://github.com/open-mmlab/mmengine/blob/main/docs/en/advanced_tutorials/test_time_augmentation.md),

![image](https://user-images.githubusercontent.com/56041436/217923781-3f890c7a-dacc-48f2-808c-c6b59d16e5df.png)

**Comment by MengzhangLI** [comment]
Hi, please follow this PR: https://github.com/open-mmlab/mmsegmentation/pull/2335

Use latest mmseg & mmengine.
