### ISSUE TITLE
Mask2Former doesn't work in the last RC

### ISSUE THREAD

**Issue by fschvart** [open-mmlab/mmsegmentation#2584]
I'm trying to train a Mask2Former model based on config files that used to work in previous RCs but for some reason it stopped working. I receive the following error: 

AttributeError: class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: 'ConfigDict' object has no attribute 'transformerlayers'

I'm running the latest mmsegmentation (1.0.0RC5), the latest mmcv and the latest mmdetection.
It seems like something did change in the config files of the Mask2Former model so that previously that attribute did appear there.

I'll appreciate your help with fixing this.

Thanks

**Comment by debasmitdas** [comment]
Exactly !! I am getting the same error.

**Comment by fschvart** [comment]
I solved it.
You need to reinstall mmdetection, not by installing rc5, but by installing the git version:

pip install git+https://github.com/open-mmlab/mmdetection.git@dev-3.x

**Comment by Caczhtus** [comment]
> I solved it. You need to reinstall mmdetection, not by installing rc5, but by installing the git version:
> 
> pip install git+https://github.com/open-mmlab/mmdetection.git@dev-3.x

I also solved this problem, but I didn't pack mmcls.

Package         Version    Source
--------------  ---------  -----------------------------------------------------------------------------------
mmcls           0.23.1     https://github.com/open-mmlab/mmclassification
mmcv            2.0.0rc4   https://github.com/open-mmlab/mmcv
mmcv-full       1.5.3      https://github.com/open-mmlab/mmcv
mmdet           3.0.0rc5   https://github.com/open-mmlab/mmdetection
mmengine        0.5.0      https://github.com/open-mmlab/mmengine
mmsegmentation  1.0.0rc5   /output/zihao-mmseg-tutorials/repo/MMSegmentation_Tutorials/20230206/mmsegmentation

**Comment by debasmitdas** [comment]
I am still getting the issue. Can you comment on the installation steps that you took ?

**Comment by helq2612** [comment]
Hi, I also meet the same problem. I use mim to install these packages, but still does not work...
`
mim install "mmdet>=3.0.0rc5"
mim install "mmengine>=0.5.0"
mim install  "mmcls>=1.0.0rc5"
mim install  "mmcv-full>=1.5.3"
mim install  "mmcv>=2.0.0rc4"
`
