### ISSUE TITLE
AttributeError: module 'mmseg.utils' has no attribute 'register_all_modules'

### ISSUE THREAD

**Issue by XxxuLimei** [open-mmlab/mmsegmentation#2585]
Hi there! When I train a model with custom dataset, it reports this error. How do I register modules without using `from mmseg.utils import register_all_modules`and `register_all_modules(init_default_scope=False)`?
THX!!!

**Comment by csatsurnh** [comment]
Hi, do you mind providing a little bit more information about your problem like the config file? Besides, generally `register_all_modules` is used to register all modules in mmseg into the registries.

**Comment by xiexinch** [comment]
> Hi there! When I train a model with custom dataset, it reports this error. How do I register modules without using `from mmseg.utils import register_all_modules`and `register_all_modules(init_default_scope=False)`? THX!!!

Hi @XxxuLimei,
We remove `register_all_modules` and support auto import modules at the latest `dev-1.x` branch.

**Comment by XxxuLimei** [comment]
> 

Thanks for answering!
I've used mmseg v1 to train model, and it works for me!
Thx again!!!
