### ISSUE TITLE
No such file or directory: 'iter_200.pth'

### ISSUE THREAD

**Issue by qjw2bqn** [open-mmlab/mmsegmentation#259]
According to the file MMSegmentation_Tutorial.ipynb, I test locally,
SystemInfo:
Window 10,
mmsegmentation 0.8
pytorch:1.6

1. Added under mmseg/datasets folder created standfordbackground.py The code content is:
![image](https://user-images.githubusercontent.com/7847058/99365878-ce1aed80-28f2-11eb-977f-db67cc18c0fc.png)

2. Add one traincustom.py under the tools folder The implementation content is as follows:

![image](https://user-images.githubusercontent.com/7847058/99365998-f9054180-28f2-11eb-90b5-ced5e44ff08f.png)

The program can train normally, but the result is different from your example,

a.something wrong with the training:
![image](https://user-images.githubusercontent.com/7847058/99366148-2c47d080-28f3-11eb-94e8-66ba1448fb02.png)

But the iter_200.pth file be created!

![image](https://user-images.githubusercontent.com/7847058/99366346-72049900-28f3-11eb-934e-7a0b00fa4653.png)

b.And I notice the output was different with your.
![image](https://user-images.githubusercontent.com/7847058/99366472-a24c3780-28f3-11eb-9290-5a5ecabf529f.png)

**Comment by xvjiarui** [comment]
Hi @qjw2bqn 

So there is no error when running from cmd?

**Comment by qjw2bqn** [comment]
Yes，The result of  running from cmd and debugger by vscode are same.
![image](https://user-images.githubusercontent.com/7847058/99493086-96bb4800-29a9-11eb-9647-47447c077b11.png)

![Uploading image.png…]()

**Comment by qjw2bqn** [comment]
I have solve it，and I finished the test.

**Comment by xiaweiguang** [comment]
> I have solved it，and I finished the test.

hello，Can you tell me how to solve this problem?
