### ISSUE TITLE
How get metrics from tested image? (error type: The shape of the mask [124, 3] at index 0...)

### ISSUE THREAD

**Issue by artgru92** [open-mmlab/mmsegmentation#2591]
Hi,

I want to test image but not show result of segmentation process but numerical values for example iou, accuracy (the same metrics as seen after tranining process for each category). I found function eval_metrics to find out solution. But probably i don't know what values should be put in function after resuolt and segmentation image maps. My function looks this: score = eval_metrics(result, gt_seg_maps, 1, 1). Image after segmentation shows every time so i think that variable "result" is okay.

Model which i used for training and testing is deeplabv3plus_r18b-d8_512x1024_80k_cityscapes.

Problem is related with shape of mask and probaly is concerned to choose correct numbers in function (thord and fourth position) - eval_metrics(result, gt_seg_maps, 1, 1). But i try many times different numerical values. But which will be correct, i dont know. So i suppose that i dont know fully what means these values.

Error which is shown is:
IndexError: The shape of the mask [124, 3] at index 0 does not match the shape of the indexed tensor [271, 124] at index 0

Could tell me how fixed this? Or explain what I might have done wrong?

Thank you.

**Comment by MeowZheng** [comment]
I think the shape of segmentation is [271,124,3], but the predicted segmentation mask is [271,124]
I suggest you should convert the color segmentation picture into single channel segmentation mask
here is an example:
https://github.com/open-mmlab/mmsegmentation/blob/b2fdae7ce794483e590e8ec8dfb63e86877ab115/tools/convert_datasets/isaid.py#L37-L45
Moreover, about `eval_metrics`, we have listed descriptions of all input arguments. If you still have problems after reading the descriptions, just let me know the problem is about which argument and we'll fix the description.
https://github.com/open-mmlab/mmsegmentation/blob/b2fdae7ce794483e590e8ec8dfb63e86877ab115/mmseg/core/evaluation/metrics.py#L257-L283

**Comment by artgru92** [comment]
1)
Images which i used second time to train have size 271 x 124 pixels ([271, 124]. The same process of conversion i did for test image. But i have the same error:
__The shape of the mask [124, 3] at index 0 does not match the shape of the indexed tensor [271, 124] at index 0.__ 
Maybe i paste all information what i received:

D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\Scripts\python.exe D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\test_model_TestDataset.py 
D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\models\losses\cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\/work_dirs_loading_data_png_1layer/tutorial/latest.pth
The model and loaded state dict do not match exactly

size mismatch for decode_head.conv_seg.weight: copying a param with shape torch.Size([5, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 128, 1, 1]).
size mismatch for decode_head.conv_seg.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([19]).
size mismatch for auxiliary_head.conv_seg.weight: copying a param with shape torch.Size([5, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 64, 1, 1]).
size mismatch for auxiliary_head.conv_seg.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([19]).
Traceback (most recent call last):
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\test_model_TestDataset.py", line 39, in <module>
    score = eval_metrics(result, gt_seg_maps, 5, 200)
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\core\evaluation\metrics.py", line 286, in eval_metrics
    total_area_label = total_intersect_and_union(
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\core\evaluation\metrics.py", line 122, in total_intersect_and_union
    intersect_and_union(
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\core\evaluation\metrics.py", line 76, in intersect_and_union
    pred_label = pred_label[mask]
IndexError: The shape of the mask [124, 3] at index 0 does not match the shape of the indexed tensor [271, 124] at index 0

Process finished with exit code 1

2) The most important code lines are:

img = mmcv.imread('Label_3_image.png')
gt_seg_maps = mmcv.imread('Label_3.png')
result = inference_segmentor(model, img)
score = eval_metrics(result, gt_seg_maps, 5)

Yes i have 5 classes. But in this case i have error what i missed one required positional argument 'ignore_index' like this:

Traceback (most recent call last):
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\test_model_TestDataset.py", line 39, in <module>
    score = eval_metrics(result, gt_seg_maps, 5)
TypeError: eval_metrics() missing 1 required positional argument: 'ignore_index'

I know that definition "ignore_index" is: _ignore_index (int): Index that will be ignored in evaluation._

But when i put in value 1, example: 
score = eval_metrics(result, gt_seg_maps, 1, 5) 
I get the same problem which is in topic: IndexError: The shape of the mask [124, 3] at index 0 does not match the shape of the indexed tensor [271, 124] at index 0

So what exactly "ignore_index" value is? (update: i was testing values from 1 to 10 and i have the same problem). What index should be ignored?

**Comment by artgru92** [comment]
Images which i used second time to train have size 271 x 124 pixels ([271, 124]. The same process of conversion i did for test image. But i have the same error:
__The shape of the mask [124, 3] at index 0 does not match the shape of the indexed tensor [271, 124] at index 0.__ 
Maybe i paste all information what i received:

D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\Scripts\python.exe D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\test_model_TestDataset.py 
D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\models\losses\cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\/work_dirs_loading_data_png_1layer/tutorial/latest.pth
The model and loaded state dict do not match exactly

size mismatch for decode_head.conv_seg.weight: copying a param with shape torch.Size([5, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 128, 1, 1]).
size mismatch for decode_head.conv_seg.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([19]).
size mismatch for auxiliary_head.conv_seg.weight: copying a param with shape torch.Size([5, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 64, 1, 1]).
size mismatch for auxiliary_head.conv_seg.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([19]).
Traceback (most recent call last):
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\test_model_TestDataset.py", line 50, in <module>
    score = eval_metrics(result, gt_seg_maps, 1, 5)
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\core\evaluation\metrics.py", line 286, in eval_metrics
    total_area_label = total_intersect_and_union(
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\core\evaluation\metrics.py", line 122, in total_intersect_and_union
    intersect_and_union(
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\core\evaluation\metrics.py", line 76, in intersect_and_union
    pred_label = pred_label[mask]
IndexError: The shape of the mask [124, 3] at index 0 does not match the shape of the indexed tensor [271, 124] at index 0

Process finished with exit code 1

The most important code lines for testing are:

img = mmcv.imread('Label_3_image.png')
gt_seg_maps = mmcv.imread('Label_3.png')
result = inference_segmentor(model, img)
score = eval_metrics(result, gt_seg_maps, 5)

I have 5 classes. But in this case i have error what i missed one required positional argument 'ignore_index' like this:

Traceback (most recent call last):
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\test_model_TestDataset.py", line 39, in <module>
    score = eval_metrics(result, gt_seg_maps, 5)
TypeError: eval_metrics() missing 1 required positional argument: 'ignore_index'

I know that definition "ignore_index" is: _ignore_index (int): Index that will be ignored in evaluation._

But when i put in value 1, example: 
score = eval_metrics(result, gt_seg_maps, 5, 1) 
I get the same problem which is in topic: IndexError: The shape of the mask [124, 3] at index 0 does not match the shape of the indexed tensor [271, 124] at index 0

So what exactly "ignore_index" value is? (update: i was testing values from 1 to 10 and i have the same problem). What index should be ignored?

**Comment by artgru92** [comment]
Ok to sum up my issue, i found solution by using this (bolded) code lines:

img = mmcv.imread('Label_112_image.png')
gt_seg_maps = mmcv.imread('Label_112.png')
gt_seg_maps2 = mmcv.rgb2gray(gt_seg_maps)
**result = np.array(result)
x, y, z = result.shape
result = np.reshape(result, (y, z))**
score = eval_metrics(result, gt_seg_maps2, 5, 1)

I noticed that matrix of result is [1 271 124] but label image have dimension [271 124]. 

So this issue can be considered as solved, thx for help.
