### ISSUE TITLE
使用mask2former出现报错

### ISSUE THREAD

**Issue by ArkhamKnight-AI** [open-mmlab/mmsegmentation#2614]
AttributeError: class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: 'ConfigDict' object has no attribute 'transformerlayers'
请问这个错误是什么意思？

**Comment by MeowZheng** [comment]
please refer this issue https://github.com/open-mmlab/mmsegmentation/issues/2619
