### ISSUE TITLE
AttributeError: class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: 'ConfigDict' object has no attribute 'transformerlayers'

### ISSUE THREAD

**Issue by Xie-Muxi** [open-mmlab/mmsegmentation#2619]
Pytorch: 1.13.1 + cu117
MMCV: 2.0.0rc4
GCC: 9.3
MMSegmentation: 1.0.0rc5

Error:
AttributeError: class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: 'ConfigDict' object has no attribute 'transformerlayers'

```
config_file = 'configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py'
checkpoint_file = 'https://download.openmmlab.com/mmsegmentation/v0.5/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-dc2c2ddd.pth'

from mmseg.apis import init_model
model = init_model(config_file, checkpoint_file, device='cuda:0')
```

MMSegmentation 安装方式：
```
git clone https://github.com/open-mmlab/mmsegmentation.git -b dev-1.x

pip install -v -e .
```

**Comment by Xie-Muxi** [comment]
config文件的问题

**Comment by zsc1220** [comment]
> config
您好，我也遇到了相同的问题，请教一下config具体是什么问题呢？

**Comment by zsc1220** [comment]
@Xie-Muxi 您好，我也遇到了相同的问题，请教一下config具体是什么问题呢？我用的就是mmseg自带的config文件

**Comment by Xie-Muxi** [comment]
> 

我也不太清楚诶，换一个模型就能正常运行，就像报错中提到的，打开mask2former_head.py文件中查看中也确实没有这个对象

**Comment by zsc1220** [comment]
找到问题所在了，目前只能下载mmdet dev-3.x的代码并安装才行，直接mim install mmdet >=3.0.0rc5，行不通

**Comment by huanruizhang123** [comment]
> 找到问题所在了，目前只能下载mmdet dev-3.x的代码并安装才行，直接mim install mmdet >=3.0.0rc5，行不通



I have encountered this problem now. If you install the code directly, mmdet==3..0.0 will be installed. If pip install mmdet==3.0.0rc5, the above problem will occur. How can I solve it?

![image](https://github.com/open-mmlab/mmsegmentation/assets/124413465/bf6426a9-aa1d-482c-9ffc-026697790b99)
![image](https://github.com/open-mmlab/mmsegmentation/assets/124413465/c2975ec8-043b-4ff9-bb60-01b9e0b85ca9)
![image](https://github.com/open-mmlab/mmsegmentation/assets/124413465/3e44fd4b-809f-42e1-9b84-d191ff435666)

**Comment by zsc1220** [comment]
@huanruizhang123 use this command to download mmdet code。
git clone -b dev-3.x https://github.com/open-mmlab/mmdetection.git

**Comment by zsc1220** [comment]
@huanruizhang123 
Now you can use the following command directly：mim install mmdet

**Comment by hanfei66520** [comment]
AssertionError: class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: class `UPerHead` in mmseg/models/decode_heads/uper_head.py:

I don't know why? There was no such mistake before, but suddenly it went wrong.
