### ISSUE TITLE
Train on one-fourth of the original resolution

### ISSUE THREAD

**Issue by ChristophReich1996** [open-mmlab/mmsegmentation#2623]
Hi mmsegmentation community, I would like to train DeepLabV3 on one-fourth of the original resolution of the Cityscapes dataset. However, adapting the [Cityscapes config](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/cityscapes.py) is somewhat not clear to me. In perticular, I would like to achieve the following behavior: 
1. downscale the original samples to one-fourth (with some delta for augmentation) of the original resolution
2. and randomly crop image patches of the shape $224\times 224$.

I ended up with the following config:
```python
crop_size = (224, 224)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(512, 256), ratio_range=(0.75, 1.25)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 256),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

Is the provided config following the desired behavior?

Additionally, what rough performance drop, over training on the native resolution, can I expect?

Thanks for the help!

**Comment by csatsurnh** [comment]
Hi @ChristophReich1996 , according to the config provided, image would be randomly resized by the multiplication of `img_scale` and a random ratio inside `ratio_range`, for more detailed information, you can refer to the resize api documentation https://mmsegmentation.readthedocs.io/en/latest/api.html#mmseg.datasets.pipelines.Resize
As for the performance drop, it's a relatively open question, we haven't done such related experiments, we recommend to discuss with the community or google on it.

**Comment by ChristophReich1996** [comment]
Hi @csatsurnh, Thanks for your response. This clarifies my question, thanks!
