### ISSUE TITLE
error may occur if calc intersection with one-class-datasets in semantic segmentation

### ISSUE THREAD

**Issue by fenrir-z** [open-mmlab/mmsegmentation#2643]
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/metrics.py#L82

if num_classes == 2, this line is working fine, showing the number of 0 and 1 in pred_label

but if num_classes == 1, this line will be like:

```
area_pred_label = torch.histc(pred_label.float(), bins=1, min=0, max=0)
```

according to [torch.histc's document](https://pytorch.org/docs/stable/generated/torch.histc.html#torch-histc): If [min](https://pytorch.org/docs/stable/generated/torch.min.html#torch.min) and [max](https://pytorch.org/docs/stable/generated/torch.max.html#torch.max) are both zero, the minimum and maximum values of the data are used.

it's actually using min=0 and max=255, and result has only one value, counting all elements between 0 and 255, but only count of 0s is needed here.

**Comment by MeowZheng** [comment]
Why set num_classes = 1? would you like to provide more detailed settings about your project?
As my knowledge, if there is only one class in the dataset, there is nothing that model training.

If x is the pixel value and F(x) is the model, and the F(x) is just a **Constant Function**, as every x inputs the model F(x) is just 1, as there only one classes. Is that your project setting?
