### ISSUE TITLE
What do I do if I just want to load the model parameters of DeeplabV3+ from your model-zoo into my own model defined with torch

### ISSUE THREAD

**Issue by xiaoachen98** [open-mmlab/mmsegmentation#265]
What do I do if I just want to load the model parameters of DeeplabV3+ from your model-zoo into my own model defined with torch and don't want to involve your MMCV, MMSEG, etc.?Because it will take more time to learn your code style and migrate to my joint task.I sincerely look forward to your reply.

**Comment by xiaoachen98** [comment]
I mean my own DeeplabV3+ model defined with torch, it is only used as baseline and can be regarded as a small group piece in my whole work.
-------------------------------------------
我想请问一下，我只是想用已经训练好的deeplabv3+的参数来作为baseline，我自己用torch定义了一个DeeplabV3+的类（继承torch.nn.Module类，也是encoder decoder结构），请问怎么把你训练好的pth文件参数导入到我定义的model中

**Comment by xvjiarui** [comment]
Hi @xiaoachen98 
You need to convert all keys in the checkpoint file to your own one.
