### ISSUE TITLE
在README.md中添加 关于docs的索引

### ISSUE THREAD

**Issue by AI-Tianlong** [open-mmlab/mmsegmentation#2664]
# Describe the feature
我觉得，可以在主界面这里将docs中这些优质的文档添加一个可折叠目录到这里，就类似模型的这种折叠形式就好，会很方便快速的帮助刚接触到mmseg的朋友们找到合适的教程和文档。期待有更好的展示方式😁
![image](https://user-images.githubusercontent.com/50650583/222324746-d47111a7-22fb-444c-b27a-3a1cd6dc5ddf.png)

**Comment by MeowZheng** [comment]
Thanks for your suggestion, and would you like to create a nice to do this~

**Comment by AI-Tianlong** [comment]
PR #3083

**Comment by AI-Tianlong** [comment]
Completed, see PR #3083 #3483  Please close this issue.
