### ISSUE TITLE
ValueError: Input and output must have the same number of spatial dimensions

### ISSUE THREAD

**Issue by shireen1512** [open-mmlab/mmsegmentation#2671]
Hello, i'm trying to train OCRnet on a custom dataset on colab (grayscale png masks already converted to color)
in the training process i get the following error : 

//
[/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in interpolate(input, size, scale_factor, mode, align_corners, recompute_scale_factor, antialias)
   3852         if isinstance(size, (list, tuple)):
   3853             if len(size) != dim:
-> 3854                 raise ValueError(
   3855                     "Input and output must have the same number of spatial dimensions, but got "
   3856                     f"input with with spatial dimensions of {list(input.shape[2:])} and output size of {size}. "
ValueError: Input and output must have the same number of spatial dimensions, but got input with with spatial dimensions of [64, 64] and output size of torch.Size([256, 256, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.
//

the shape of my dataset is (512, 512, 3)
here is my cfg below, could someone help me with this please? thank you in advance. 

from mmseg.apis import set_random_seed
from mmseg.utils import get_device

##### Since we use only one GPU, BN is used instead of SyncBN
cfg.norm_cfg = dict(type='BN', requires_grad=True)
cfg.model.backbone.norm_cfg = cfg.norm_cfg

##### modify num classes of the model in decode head
for head in cfg.model.decode_head:
    head['num_classes'] = 5
    head['norm_cfg'] = cfg.norm_cfg

##### Modify dataset type and path (function defined before)
cfg.dataset_type = 'myDataset'
cfg.data_root = data_root

cfg.data.samples_per_gpu = 8
cfg.data.workers_per_gpu=8

cfg.img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

cfg.crop_size = (256, 256)
cfg.train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(320, 240), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=cfg.crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **cfg.img_norm_cfg),
    dict(type='Pad', size=cfg.crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]

cfg.test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(320, 240),
        ##### img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **cfg.img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

cfg.data.train.type = cfg.dataset_type
cfg.data.train.data_root = cfg.data_root
cfg.data.train.img_dir = img_dir
cfg.data.train.ann_dir = ann_dir
cfg.data.train.pipeline = cfg.train_pipeline
cfg.data.train.split = 'splits/train.txt'

cfg.data.val.type = cfg.dataset_type
cfg.data.val.data_root = cfg.data_root
cfg.data.val.img_dir = img_dir
cfg.data.val.ann_dir = ann_dir
cfg.data.val.pipeline = cfg.test_pipeline
cfg.data.val.split = 'splits/val.txt'

cfg.data.test.type = cfg.dataset_type
cfg.data.test.data_root = cfg.data_root
cfg.data.test.img_dir = img_dir
cfg.data.test.ann_dir = ann_dir
cfg.data.test.pipeline = cfg.test_pipeline
cfg.data.test.split = 'splits/val.txt'

#####We can still use the pre-trained Mask RCNN model though we do not need to
##### use the mask branch
cfg.load_from = 'checkpoints/ocrnet_hr48_512x1024_160k_cityscapes_20200602_191037-dfbf1b0c.pth'

##### Set up working dir to save files and logs.
cfg.work_dir = './work_dirs/tutorial'

cfg.runner.max_iters = 200
cfg.log_config.interval = 10
cfg.evaluation.interval = 200
cfg.checkpoint_config.interval = 200

##### Set seed to facitate reproducing the result
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)
cfg.device = get_device()

##### Let's have a look at the final config used for training
print(f'Config:\n{cfg.pretty_text}')

**Comment by MeowZheng** [comment]
> Hello, i'm trying to train OCRnet on a custom dataset on colab (grayscale png masks already converted to color)
> in the training process i get the following error 

The gt segmentation mask must be a 2D map, whose pixels include label indices (integers) rather than RGB 3 vector.

**Comment by hejunen** [comment]
Hello,I have encountered the same problem, can you tell me how to do it?

**Comment by shireen1512** [comment]
so i think i solved this problem. the problem was that when i tried to convert my dataset to mask of segmentation, it gave me masks with shape of (H, W, color), but the code accepts (H, W) even though it displays masks in color ( i did not understand how that works) . so, with this code i convert my grayscale pngs to colored masks : 
`import os.path as osp
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# define paths and parameters
data_root = 'dataset'
img_dir = 'images'
ann_dir = 'labels'
classes = ('background', 'building', 'road', 'sidewalk', 'vegetation')
palette = [[0, 0, 0], [120, 120, 120], [0, 0, 200], [100, 150, 225], 
           [100, 200, 0]]

for file in mmcv.scandir(osp.join(data_root, ann_dir), suffix='.png'):
    # load grayscale image
    seg_map = np.array(Image.open(osp.join(data_root, ann_dir, file)).convert('L'))
    # create color image with palette
    seg_img = Image.fromarray(seg_map).convert('P')
    seg_img.putpalette(np.array(palette, dtype=np.uint8))
    # save color image with the same filename as the original file
    seg_img.save(osp.join(data_root, ann_dir, file))`

and then if i check my masks with this : 
`import numpy as np
from PIL import Image

# Load image
img = Image.open('dataset/labels/004_jpg.rf.e6421a9b011dc682aa943403eee4575a.png')

# Convert image to NumPy array
img_array = np.array(img)

# Print tensor shape
print(img_array.shape)`

it must be a 2D array e.g. (512, 512)

**Comment by imxtx** [comment]
> > Hello, i'm trying to train OCRnet on a custom dataset on colab (grayscale png masks already converted to color)
> > in the training process i get the following error
> 
> The gt segmentation mask must be a 2D map, whose pixels include label indices (integers) rather than RGB 3 vector.

The [documentation](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_datasets.md) should be improved with examples, I spent several days to tackle the save problem due to vague documentation.
