### ISSUE TITLE
Errors when using tools/analysis_tools/get_flops.py

### ISSUE THREAD

**Issue by ArkhamKnight-AI** [open-mmlab/mmsegmentation#2672]
I used the official config in configs/mask2former/mask2former_r50_8xb2-160k_ade20k-512x512.py to run get_flops.py, the following error arised:
E:\mmsegmentation\mmseg\models\builder.py:44: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
Traceback (most recent call last):
  File "E:/mmsegmentation/tools/analysis_tools/get_flops.py", line 60, in <module>
    main()
  File "E:/mmsegmentation/tools/analysis_tools/get_flops.py", line 37, in main
    model = build_segmentor(
  File "E:\mmsegmentation\mmseg\models\builder.py", line 47, in build_segmentor
    assert cfg.get('train_cfg') is None or train_cfg is None, \
AssertionError: train_cfg specified in both outer field and model field

the argument I used in commond line is:
--config
../../configs/mask2former/mask2former_r50_8xb2-160k_ade20k-512x512.py
--shape
900 900

Why this error arised? Looking forward for reply soon! Thank you!

**Comment by MeowZheng** [comment]
we are working on updating get_flop.

**Comment by MeowZheng** [comment]
we have supported it in #2706

**Comment by Gu-EH** [comment]
> 

It is still error: NotImplementedError: MaskFormer and Mask2Former are not supported yet.
When delete this line of code, new error arise：
 File "/home/geh/code/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 237, in _forward
    return self.decode_head.forward(x)
    TypeError: forward() missing 1 required positional argument: 'batch_data_samples'
