### ISSUE TITLE
Why are the codes of accuracy and recall the same？

### ISSUE THREAD

**Issue by Lucaslifeday** [open-mmlab/mmsegmentation#2692]
mmseg/core/evaluation/metrics.py : 

acc = total_area_intersect / total_area_label
recall = total_area_intersect / total_area_label

The calculation formula of accuracy in the paper：Accuracy =（TP+TN）/ (TP+FP+TN+FN)
The calculation formula of recall in the paper:         Recall = TP / (TP+FN)

The two calculation formulas and results in the paper are different.

**Comment by Lucaslifeday** [comment]
This line of code all_acc = total_area_intersect.sum() / total_area_label.sum()
represent Accuracy =（TP+TN）/ (TP+FP+TN+FN)  ？

**Comment by MeowZheng** [comment]
> total_area_intersect

yes

**Comment by Lucaslifeday** [comment]
Thank you very much.
