### ISSUE TITLE
Visualisation of feature distribution

### ISSUE THREAD

**Issue by leo-hao** [open-mmlab/mmsegmentation#2716]
When I reproduce the code model  through mmsegmentation, I would like to show the distribution of the features using a method like following t-sne, but I don't know how to implement it, can any of you give me some help?
![image](https://user-images.githubusercontent.com/20486586/223422730-b990f489-dbf9-4ecd-9353-445e6996cd75.png)

**Comment by MeowZheng** [comment]
It is a good feature for mmseg, we are planning to support it. I suggest you might leave an issue to DAFormer for asking more specific suggestions.
