### ISSUE TITLE
What number should I start with to label my dataset?

### ISSUE THREAD

**Issue by xu19971109** [open-mmlab/mmsegmentation#2719]
I see in focal loss that ignore label is replaced with 0, but 0 is my usage class. 
So what number  do you suggest I start with to make my category?

![image](https://user-images.githubusercontent.com/50237122/223666852-c7eac7b5-f560-45df-ac6f-15701716c461.png)

**Comment by MeowZheng** [comment]
The label index should start from 0.

**Comment by xu19971109** [comment]
> 

Thank you.
