### ISSUE TITLE
some confusions about pretraining & skills for finetuning

### ISSUE THREAD

**Issue by LixiangHello** [open-mmlab/mmsegmentation#2736]
1.您好，我想问一下，在mmseg搭建好了模型，怎么在imagenet，coco等数据集上进行预训练呀？
2.使用预训练模型初始化模型，微调的时候有什么技巧嘛？

谢谢，急需指导^-^

**Comment by MeowZheng** [comment]
可以参考使用 [mmclassification](https://github.com/open-mmlab/mmclassification) 算法库做预训练
