### ISSUE TITLE
programmer friendly configuration system

### ISSUE THREAD

**Issue by rayleizhu** [open-mmlab/mmsegmentation#2746]
# Describe the feature

**Motivation**

The current configuration system does not provide a context of **which arguments are applicable in a specific section**. 

Here is an example case to illustrate this.  A user may want to keep track of the best-performing checkpoint during training. Though he can guess it may have some argument in `checkpoint_config` section, there is no simple way to find it out. He needs to **search the whole mmcv library** to figure it out, which breaks his workflow.  This process will occur again and again until he becomes an adept user of to open-mmlab series, hence he **remembers almost every function signature**. 

It is not a good idea to require a programmer to remember many trivial routines. They should focus on the logic. 

**Related resources**

This problem is actually not difficult to solve. [Detectron2](https://github.com/facebookresearch/detectron2) has a simple and elegant solution, implemented by [`Lazycall` ](https://github.com/facebookresearch/detectron2/blob/17e95486fdfee2408b2c0b6d2dd5b775f91e814f/detectron2/config/lazy.py#L25). The key idea is to let users configure some object **as if they are doing the instantiation within a python file**, while the object is **actually converted to a dictionary (which is similar as current configuration system used by open-mmlab series)**. As a result, code editors (e.g. VSCode or PyCharm) can easily find the function prototypes or signatures. See the screenshot below.

![image](https://user-images.githubusercontent.com/19933627/224676853-4cdc6558-3366-456a-b911-728f19a4dd49.png)

**Comment by xiexinch** [comment]
Hi @rayleizhu,
This feature is under development, but the implementation will not be the same as Detectron 2.

**Comment by rayleizhu** [comment]
Happy to hear that.

Users do not care implementation. Just the user experience matters.

Best,
Lei

On 13 Mar 2023, at 6:58 PM, 谢昕辰 ***@***.***> wrote:

﻿

Hi @rayleizhu<https://github.com/rayleizhu>,
This feature is under development, but the implementation will not be the same as Detectron 2.
