### ISSUE TITLE
How can I get accesss to the groundtruth in the forward function of my decode head?

### ISSUE THREAD

**Issue by QChhh123** [open-mmlab/mmsegmentation#2759]
I want to use groundtruth data to improve some parameters in my model, but I can't find the way to transport ground truth data into my model. If the revision of the source code is necessary, please tell me how. Thank you very much!

**Comment by xiexinch** [comment]
Hi @QChhh123,
In mmseg 1.x, you might get the labels at `DataSamples`.

https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/models/segmentors/base.py#L62

https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/models/segmentors/encoder_decoder.py#L159

**Comment by QChhh123** [comment]
Sorry, I am poor at coding. I don't know which parts of my code need to be revised. Can you  provide some examples for me that used groundtruth in the forward part.

**Comment by xiexinch** [comment]
Welcome to join our community for help!
https://github.com/open-mmlab/mmsegmentation/blob/master/README_zh-CN.md#%E6%AC%A2%E8%BF%8E%E5%8A%A0%E5%85%A5-openmmlab-%E7%A4%BE%E5%8C%BA

**Comment by QChhh123** [comment]
I have solved this problem. Override the forward_train() method works.
