### ISSUE TITLE
Segformer

### ISSUE THREAD

**Issue by Lucky-zi-lin** [open-mmlab/mmsegmentation#2764]
Self. attn is calculated in EfficientMultiheadAttention in Segformer. The specific code is out=self. attn (query=x_q, key=x_kv, value=x_kv) [0], where key and value are the same, while some versions of the code first perform self. kv=nn. Linear (dim, dim * 2, bias=qkv_bias) on the full connection layer, and then index to distinguish k, v=kv [0], kv [1]. Why is mmsegmentation designed like that?

**Comment by xiexinch** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/2761
