### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Serenagirl** [open-mmlab/mmsegmentation#277]
训练时设置
checkpoint_config = dict(by_epoch=False, interval=500)
evaluation = dict(interval=500, metric='mIoU')
当完成500个iter并保存后报错：

![QQ截图20201125151214](https://user-images.githubusercontent.com/36497153/100194906-794e2700-2f31-11eb-817b-3ee0e5b561ea.png)

**Comment by YLyeliang** [comment]
As you can see from the last line. Python raised a fileNotFoundError. Make sure your label file and image file share the same name in your validation dataset.
