### ISSUE TITLE
document error：config file does not exist

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmsegmentation#2779]
If you feel we have helped you, give us a STAR! :satisfied:

**Describe the issue**
when I test PSPNet on PASCAL VOC (without saving the test results) and evaluate the mIoU in the "https://mmsegmentation.readthedocs.io/en/latest/inference.html"

file "configs/pspnet/pspnet_r50-d8_512x1024_20k_voc12aug.py" does not exist   

maybe can use pspnet_r50-d8_512x512_20k_voc12aug.py

**Reproduction**

1. What command or script did you run?
```
python tools/test.py configs/pspnet/pspnet_r50-d8_512x1024_20k_voc12aug.py \
    checkpoints/pspnet_r50-d8_512x1024_20k_voc12aug_20200605_003338-c57ef100.pth \
    --eval mAP
```

**Comment by xiexinch** [comment]
Hi @pekopoke,
Thanks for your report, we will update it soon.
