### ISSUE TITLE
Dataset Prediction Problem

### ISSUE THREAD

**Issue by Ma-lele** [open-mmlab/mmsegmentation#2782]
![image](https://user-images.githubusercontent.com/81337214/226856134-13c8f952-f788-4cc5-9f31-a9e7b0851e54.png)
when I use the image_dmon.py to prdict the dataset, the output contains the original images.I want the output does not contain the original image，how can I get this result？

**Comment by xiexinch** [comment]
Hi @Ma-lele,
You might set the opacity to 1.
https://github.com/open-mmlab/mmsegmentation/blob/1ea397509e6498c3a4142438941f067283374ebd/demo/image_demo.py#L17

**Comment by Ma-lele** [comment]
> 

It works! Thank you.
