### ISSUE TITLE
How do I turn off all data enhancement methods?

### ISSUE THREAD

**Issue by Lucaslifeday** [open-mmlab/mmsegmentation#2788]
For example, these data enhancement methods
dict(type='Resize', img_scale=(2048, 1024), ratio_range=(0.5, 2.0)),
dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
dict(type='RandomFlip', prob=0.5),
dict(type='PhotoMetricDistortion'),
dict(type='Normalize', **img_norm_cfg),
dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),

But I comment them out and get an error

**Comment by xiexinch** [comment]
Hi @Lucaslifeday,
You might remove the corresponding meta keys to be collected.
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/formatting.py#L259

**Comment by Lucaslifeday** [comment]
Thank you for your reply.
