### ISSUE TITLE
support MMSeginferencer in master repo

### ISSUE THREAD

**Issue by jinwonkim93** [open-mmlab/mmsegmentation#2789]
# Describe the feature

**Motivation**
A clear and concise description of the motivation of the feature.
MMSeginferencer seems to be develop in dev branch.
is there plan for moving it to master?
https://github.com/open-mmlab/mmsegmentation/pull/2658
if there is things to help I can try.
**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by jinwonkim93** [comment]
is 1.x branch recommend to use rather than master?

**Comment by xiexinch** [comment]
Hi @jinwonkim93,
Thank you for your concern, we plan to switch the 1.x branch to the main branch next week. Recent updates are on the 1.x branch, so it is recommended to use the 1.x branch for development and research.

**Comment by jinwonkim93** [comment]
oh thanks, MMseginferencer looks cool but i am having hard time implementing it with old config. 
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/26476095/227450642-e11b34a7-291b-42b7-b89e-47c85dd8cd68.png">
