### ISSUE TITLE
Is Mmsegmentation for all types of images or only city shapes?

### ISSUE THREAD

**Issue by hakanerten09** [open-mmlab/mmsegmentation#279]
Hi,
Is Mmsegmentation for all types of images or only city shapes?
Can i use it with tiff images and for satellite images?
If it is used for satellite images, what can i do for high resolution images?

thanks.

**Comment by YLyeliang** [comment]
It supports much of the image types, including tiff & satellite images. You just need to prepare your dataset according to tutorial(prepare your dataset), and use the `custom_data` type.

**Comment by hakanerten09** [comment]
Thanks a lot...
