### ISSUE TITLE
Troubling Implementing Upernet_vit-b16_mln on custom dataset

### ISSUE THREAD

**Issue by mattyhatch** [open-mmlab/mmsegmentation#2792]
If you feel we have helped you, give us a STAR! :satisfied:

**Notice**

There are several common situations in the reimplementation issues as below

1. Reimplement a model in the model zoo using the provided configs
2. Reimplement a model in the model zoo on other datasets (e.g., custom datasets)
3. Reimplement a custom model but all the components are implemented in MMSegmentation
4. Reimplement a custom model with new modules implemented by yourself

There are several things to do for different cases as below.

- For cases 1 & 3, please follow the steps in the following sections thus we could help to quickly identify the issue.
- For cases 2 & 4, please understand that we are not able to do much help here because we usually do not know the full code, and the users should be responsible for the code they write.
- One suggestion for cases 2 & 4 is that the users should first check whether the bug lies in the self-implemented code or the original code. For example, users can first make sure that the same model runs well on supported datasets. If you still need help, please describe what you have done and what you obtain in the issue, and follow the steps in the following sections, and try as clear as possible so that we can better help you.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

A clear and concise description of the problem you meet and what you have done:
I have been trying to configure the upernet_vit-b16_ln_mln_512x512 model to work with a 2 class semantic segmentation Tomato dataset instead of the original ADE20K dataset. I have gotten it to work with the ADE20K dataset but having trouble converting it over to work with my custom dataset. The weirdest part about this error though is when I run the script with my tomato dataset which has 2 classes, but keep the num_classes variable 4 or greater within configs/__base__/models/upernet_vit-b16_ln_mln.py and configs/vit/upernet_vit-b16_mln_512x512_80k_ade20k.py, the script runs through the entire training and validation processes, with the obvious caveat being that the information we get back in validation is nonsense because it is converging to the wrong number of classes. Here is the error stacktrace that I am getting which happens right when the training iterations start:
Traceback (most recent call last):
  File "C:\Users\matty\mmsegmentation\tools\train.py", line 243, in <module>
    main()
  File "C:\Users\matty\mmsegmentation\tools\train.py", line 232, in main
    train_segmentor(
  File "c:\users\matty\mmsegmentation\mmseg\apis\train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\matty\miniconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "C:\Users\matty\miniconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "C:\Users\matty\miniconda3\lib\site-packages\mmcv\parallel\data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "c:\users\matty\mmsegmentation\mmseg\models\segmentors\base.py", line 138, in train_step
    losses = self(**data_batch)
  File "C:\Users\matty\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\matty\miniconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\matty\mmsegmentation\mmseg\models\segmentors\base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "c:\users\matty\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 144, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "c:\users\matty\mmsegmentation\mmseg\models\segmentors\encoder_decoder.py", line 87, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "c:\users\matty\mmsegmentation\mmseg\models\decode_heads\decode_head.py", line 243, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "C:\Users\matty\miniconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 208, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\matty\mmsegmentation\mmseg\models\decode_heads\decode_head.py", line 310, in losses
    loss['acc_seg'] = accuracy(
  File "c:\users\matty\mmsegmentation\mmseg\models\losses\accuracy.py", line 49, in accuracy
    correct = correct[:, target != ignore_index]
RuntimeError: CUDA error: an illegal memory access was encountered

**Reproduction**

1. What command or script did you run?

```
python tools/train.py ./configs/vit/upernet_vit-b16_mln_512x512_80k_ade20k.py --work-dir word-dirs/upernet_vit-b16_mln_512x512_80k_ade20k/upernet_vit-b16_mln_512x512_80k_ade20k.py --gpus 1
```

2. What config dir you run?

```
 configs/vit/upernet_vit-b16_mln_512x512_80k_ade20k.py
```

3. Did you make any modifications to the code or config? Did you understand what you have modified?
-I have changed the image and crop size to 200x200 within configs/__base__/models/upernet_vit-b16_ln_mln.py and configs/__base__/datasets/ade20k.py(which worked when I ran the ADE20K dataset at this size)
-I created my custom dataset within the CustomDataset class in mmseg, which has a palette of [[2,2,2],[1,1,1]] and classes of ["sunlit-leaves","not sunlit-leaves"]
-As stated before, changed num_classes to 2 in both configs/__base__/models/upernet_vit-b16_ln_mln.py and  configs/vit/upernet_vit-b16_mln_512x512_80k_ade20k.py
-Changed dataset_type in the ade20k.py config file to "CustomDataset" and set the dataset_root to the folder of my tomatoes
5. What dataset did you use?
Link to google drive that contains it:https://drive.google.com/drive/folders/11nRdd9Zk_LYCM5ytGjttR7ki5Hhyk5Jf?usp=sharing
The images zip folder holds the training images while the labels.zip folder holds the training masks.

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmseg/utils/collect_env.py` to collect the necessary environment information and paste it here.
sys.platform: win32
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: Quadro RTX 5000
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.8
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32215 for x64
GCC: n/a
PyTorch: 1.13.1+cu116
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1+cu116
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: MSVC 192829924
MMCV CUDA Compiler: 11.6
MMSegmentation: 0.30.0+186572a
2. You may add an addition that may be helpful for locating the problem, such as
   1. How you installed PyTorch \[e.g., pip, conda, source\]
         Installed using conda
   2. Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Results**

If applicable, paste the related results here, e.g., what you expect and what you get.

```
A placeholder for results comparison
```

**Issue fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by mattyhatch** [comment]
I figured it out! I have only 2 classes in my custom dataset which means that my label values need to be in the range [0, num_classes-1](so [0,1] in my case), but I was using label values of 79 and 150. Using get_semantic_bitmap() from segments.utils, I was able to convert the label values to 0 and 1(Which make the picture look pitch black as 0 is black and 1 is a slightly different shade of black but don't be worried) and was able to run it in training.

**Comment by akianfar** [comment]
@mattyhatch Hey there, just wanted to say that I got the same problem as you.
would you kindly share the code because I don't seem to able to solve it

**Comment by mattyhatch** [comment]
import cv2
import os
import numpy as np
from segments.utils import get_semantic_bitmap
import PIL as PIL
from PIL import Image
# Convert to Grayscale
#img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
annotationsList = os.listdir()
for image in annotationsList:
    if image == "crop.py" or image == "greyscale.py":
        continue
    temp = cv2.imread(image)
    image1 = cv2.cvtColor(temp,cv2.COLOR_BGR2GRAY)
    print(np.unique(image1))
    image1 = PIL.Image.fromarray(get_semantic_bitmap(
                image1,
                [{'id': 79, 'category_id': 0}, {'id': 150, 'category_id': 1}] ,
            ).astype(np.uint8))
    print(np.unique(image1))
    cv2.imwrite(image,image1)
    
@akianfar I put this script inside of the annotations folder I was trying to convert and ran it, where 79 and 150 are the previous values of the mask, and it changes those values to 0 and 1 respectively. Prints out unique values of each mask before and after so then you can confirm it converts properly. Hope this helps!

**Comment by akianfar** [comment]
@mattyhatch Thanks a lot mate
