### ISSUE TITLE
somethings about baesliine

### ISSUE THREAD

**Issue by zjk958162734** [open-mmlab/mmsegmentation#280]
Hello, I have some questions I want to consult. First, in the baseline, what is the difference between MIOU and MIOU(ms+flip)? Second, how should I get the value of MIOU(ms+flip)? Third, if If I am not mistaken, your MIOU should be obtained on the val dataset. Do you have a baseline obtained by running it on the test dataset? Thank you!

**Comment by YLyeliang** [comment]
1.The result of MIoU is obtained by simple_test with no test time augmentation. While MiOU(ms+flip) used TTA to augment the test images, and multiple score results are obtained, then an average of these results is calculated to get the final result.
2. like above said.
3. The MIoU is obtained on the test dataset.

**Comment by xvjiarui** [comment]
@YLyeliang Thx! Y

@zjk958162734 
The cityscapes results are from val set. You may get mIoU(ms+flip) by `--aug-test` for `test.py`.

**Comment by tjyuyao** [comment]
> The cityscapes results are from val set. 

@xvjiarui 
Thank you for your information. How may I verify this in the code?
