### ISSUE TITLE
Pretrained ViT model not found when reproduce result with DPT model

### ISSUE THREAD

**Issue by Jumponthemoon** [open-mmlab/mmsegmentation#2803]
Hi, I met some problems when i try to reproduce the result for DPT model. It gives the following error with the pretrained model not found:

![https://user-images.githubusercontent.com/39290403/228292806-cb1e8dc2-b557-4041-871d-2d2dcc34470f.png](https://user-images.githubusercontent.com/39290403/228292806-cb1e8dc2-b557-4041-871d-2d2dcc34470f.png)

Then i checked the model base file and found the pretrained model should be under "pretrain/xxx":

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/f6549261-5e36-4f74-8141-495edbe30ca1/Untitled.png)

But i can't find the “pretrain” folder and  for other model file, it is specified with “open-mmlab://xxx”

![https://user-images.githubusercontent.com/39290403/228293025-b5286bbc-57ec-4058-9ef4-deec8f6a4e92.png](https://user-images.githubusercontent.com/39290403/228293025-b5286bbc-57ec-4058-9ef4-deec8f6a4e92.png)

I’m wondering what’s the difference and how can i download the pretrained vit-b16_p16_224-80ecf9dd.pth file?

**Comment by Jumponthemoon** [comment]
Second pic corrupted,uploaded here:
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/f6549261-5e36-4f74-8141-495edbe30ca1/Untitled.png]

**Comment by Jumponthemoon** [comment]
Second picture was corrupted,uploaded again here:
![image](https://user-images.githubusercontent.com/39290403/228296390-f3acf550-9a4e-40ed-9155-3030ce59a7a2.png)

**Comment by xiexinch** [comment]
Hi @Jumponthemoon,
You might download the pre-trained weights from timm repo. https://github.com/pprp/timm/blob/v0.1-vt3p-weights/timm/models/vision_transformer.py

And please follow the [usage](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/vit#usage) document to process the pre-trained weights.
