### ISSUE TITLE
Problem in /tools/convert_datasets/vaihingen.py

### ISSUE THREAD

**Issue by heikeyuhuajia** [open-mmlab/mmsegmentation#2811]
About the clip_big_image() function in the tools/convert_datasets/vaihingen.py file. In the clip_big_image() function, for example, given one 5120 x 5120 original image, the clip size is 512, and the stride size is 256; thus, it would generate 20x20 = **400** images whose sizes are all 512x512. But according to the official https://mmsegmentation.readthedocs.io/zh_CN/latest/dataset_prepare.html. But according to the official website, the Vaihingen training set is only **344** sheets after the default configuration organization. Why is the number of images processed by the code different from the theoretical one?

**Comment by heikeyuhuajia** [comment]
I get it, and I need to do the math manually. Thank you very much!

**Comment by SAULALA** [comment]
In our default setting (clip_size=512, stride_size=256), it will generate 344 images for training and 398 images for validation.
this is incorrect @csatsurnh 

in tools\dataset_converters\vaihingen.py   
   xmin = x * cs
   ymin = y * cs
should be
   xmin = x * ss
   ymin = y * ss

it will generate 1046 images for training and 1208 images for validation.
the same problem in potsdam.py
