### ISSUE TITLE
how to use --palette 

### ISSUE THREAD

**Issue by shireen1512** [open-mmlab/mmsegmentation#2818]
hello, 
i'm trying to run inference with a pre-trained custom model (trained on colab), but i receive this error : 

**UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: weight.pth
Traceback (most recent call last):
  File "demo/image_demo.py", line 46, in <module>
    main()
  File "demo/image_demo.py", line 30, in main
    model = init_segmentor(args.config, args.checkpoint, device=args.device)
  File "/home/shireen/github/mmsegmentation/mmseg/apis/inference.py", line 36, in init_segmentor
    model.PALETTE = checkpoint['meta']['PALETTE']
KeyError: 'PALETTE'**

can _--palette_ be used for this ? i have a palette.txt file as below : 

0 0 0
120 120 120
0 0 200
150 100 225
100 150 225
200 100 0
100 200 0

but it does not accept it when i use --palette palette.txt in the command. i didn't find any further info about this flag. i would appreciate it if someone helps. 🙏

**Comment by csatsurnh** [comment]
Hi @shireen1512, --palette support can be found here https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/class_names.py and alias could be used for indication. However if you want to use your own palette, you may need to customize it in the dataset settings.
