### ISSUE TITLE
Support for Segment Anything

### ISSUE THREAD

**Issue by jinwonkim93** [open-mmlab/mmsegmentation#2842]
# Support for Segment Anything

**Motivation**
A clear and concise description of the motivation of the feature.
- There is a recent paper  https://ai.facebook.com/blog/segment-anything-foundation-model-image-segmentation/ 
- Supporting a model for easy fine-tuning and dataset will be very helpful to everyone.

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.
- https://github.com/facebookresearch/segment-anything

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by davidblom603** [comment]
Great to see this on the backlog. Any idea when this can be picked up?

**Comment by jinwonkim93** [comment]
@davidblom603  https://github.com/open-mmlab/mmsegmentation/tree/main/projects/sam_inference_demo.

i will close this issue.
