### ISSUE TITLE
Assertion error for lr policy

### ISSUE THREAD

**Issue by rubeea** [open-mmlab/mmsegmentation#286]
Thanks for your error report and we appreciate it a lot.

**Checklist**

I have searched related issues but cannot get the expected help.

**Describe the bug**
Getting assertion error related to some lr policy

**Reproduction**
I am trying to train my custom dataset (with two classes background and the object class) with modified pspnet_r50-d8_512x1024_40k_cityscapes config for my custom dataset. The error comes on the train_segmentor function shown below:

    ```
train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
                meta=meta)
    ```

2. Yes I modified the config according to the mmsegmentation tutorial notebook but I am using binary cross entropy loss that is with sigmoid=True instead of the categorical cross entropy loss.
3. Powerline dataset PLDU. Available at: https://drive.google.com/drive/folders/1XjoWvHm2I8Y4RV_i9gEd93ZP-KryjJlm

**Environment**

fatal: not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
CUDA available: True
GPU 0: Tesla K80
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1+cu101
OpenCV: 4.1.2
MMCV: 1.2.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.8.0+
**Error traceback**

If applicable, paste the error trackback here.

/usr/local/lib/python3.6/dist-packages/mmcv/utils/misc.py:304: UserWarning: "flip_ratio" is deprecated in `RandomFlip.__init__`, please use "prob" instead
  f'"{src_arg_name}" is deprecated in '
2020-11-30 12:57:22,273 - mmseg - INFO - Loaded 439 images
2020-11-30 12:57:23,279 - mmseg - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-24-8a17d9dc3df2> in <module>()
     27 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
     28 train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
---> 29                 meta=meta)

2 frames
/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py in register_lr_hook(self, lr_config)
    346     def register_lr_hook(self, lr_config):
    347         if isinstance(lr_config, dict):
--> 348             assert 'policy' in lr_config
    349             policy_type = lr_config.pop('policy')
    350             # If the type of policy is all in lower case, e.g., 'cyclic',

AssertionError: 

Kindly help in resolving the issue.

**Comment by YLyeliang** [comment]
It seems like your error happened in building the lr hook. If that's true, you should check your modified config file,  check your lr_config=dict(policy='xx',...). Make sure it's correct according to the original schedule config.
And, when you use binary cross-entropy loss(BCE), your class number should be 1, not 2 of background and object. Besides, the score in testing time also needed to change to sigmoid and set a threshold to predict the fore or background.

**Comment by rubeea** [comment]
> It seems like your error happened in building the lr hook. If that's true, you should check your modified config file, check your lr_config=dict(policy='xx',...). Make sure it's correct according to the original schedule config.
> And, when you use binary cross-entropy loss(BCE), your class number should be 1, not 2 of background and object. Besides, the score in testing time also needed to change to sigmoid and set a threshold to predict the fore or background.

Hi thanks and yes I fixed the policy issue by modifying the optimizer. However, I was wondering that why should I keep the number of classes as 1? because in other sample datasets with only one object class and the other background class, the number of classes is equal to 2. Kindly elaborate on this part. Thanks

**Comment by YLyeliang** [comment]
> > It seems like your error happened in building the lr hook. If that's true, you should check your modified config file, check your lr_config=dict(policy='xx',...). Make sure it's correct according to the original schedule config.
> > And, when you use binary cross-entropy loss(BCE), your class number should be 1, not 2 of background and object. Besides, the score in testing time also needed to change to sigmoid and set a threshold to predict the fore or background.
> 
> Hi thanks and yes I fixed the policy issue by modifying the optimizer. However, I was wondering that why should I keep the number of classes as 1? because in other sample datasets with only one object class and the other background class, the number of classes is equal to 2. Kindly elaborate on this part. Thanks

The reason number of classes should be 1 is that you used sigmoid instead of softmax. The sigmoid output the scores of the object belong to fore or background.  Your output of sigmoid on logits will limit the score to [0,1]. Then, a threshold will be set to determine the classes, normally it's 0.5( In this case, it's equal softmax in two classes segmentation task). In this case, 1 channel can be represented to fore or background according to the score in this channel. While, in the softmax way, each channel represents a class, and argmx on the channel will find the best matched classes.
And the BCE loss, if you read the documentation, you will find that the shape of input and target should be the same. In the cumstom_dataset, the shape of the target would be [N,1,H,W]. where channel-1 represents the classes index.  In this case, the shape of the target and input are not the same.
Hope that helps.

**Comment by rubeea** [comment]
When setting number of classes to 1 on my dataset, the train gives me an error. I have prepared my dataset according to the DRIVE and STARE datasets in the mmsegmentation datasets directory that also deal with binary class problems and consist of two classes (background and the object class). Nevertheless, I am currently using weighted cross entropy loss (due to the unbalanced nature of my dataset) and it seems to train ok. However, I have one more question, if I attempt to use dcn (deformable convolutions) in the backbone, I get the following error:

missing keys in source state_dict: layer2.0.conv2.conv_offset.weight, layer2.0.conv2.conv_offset.bias, layer2.1.conv2.conv_offset.weight, layer2.1.conv2.conv_offset.bias, layer2.2.conv2.conv_offset.weight, layer2.2.conv2.conv_offset.bias, layer2.3.conv2.conv_offset.weight, layer2.3.conv2.conv_offset.bias, layer3.0.conv2.conv_offset.weight, layer3.0.conv2.conv_offset.bias, layer3.1.conv2.conv_offset.weight, layer3.1.conv2.conv_offset.bias, layer3.2.conv2.conv_offset.weight, layer3.2.conv2.conv_offset.bias, layer3.3.conv2.conv_offset.weight, layer3.3.conv2.conv_offset.bias, layer3.4.conv2.conv_offset.weight, layer3.4.conv2.conv_offset.bias, layer3.5.conv2.conv_offset.weight, layer3.5.conv2.conv_offset.bias, layer4.0.conv2.conv_offset.weight, layer4.0.conv2.conv_offset.bias, layer4.1.conv2.conv_offset.weight, layer4.1.conv2.conv_offset.bias, layer4.2.conv2.conv_offset.weight, layer4.2.conv2.conv_offset.bias

Any help on this will be appreciated. Thanks

**Comment by rubeea** [comment]
> > > It seems like your error happened in building the lr hook. If that's true, you should check your modified config file, check your lr_config=dict(policy='xx',...). Make sure it's correct according to the original schedule config.
> > > And, when you use binary cross-entropy loss(BCE), your class number should be 1, not 2 of background and object. Besides, the score in testing time also needed to change to sigmoid and set a threshold to predict the fore or background.
> > 
> > 
> > Hi thanks and yes I fixed the policy issue by modifying the optimizer. However, I was wondering that why should I keep the number of classes as 1? because in other sample datasets with only one object class and the other background class, the number of classes is equal to 2. Kindly elaborate on this part. Thanks
> 
> The reason number of classes should be 1 is that you used sigmoid instead of softmax. The sigmoid output the scores of the object belong to fore or background. Your output of sigmoid on logits will limit the score to [0,1]. Then, a threshold will be set to determine the classes, normally it's 0.5( In this case, it's equal softmax in two classes segmentation task). In this case, 1 channel can be represented to fore or background according to the score in this channel. While, in the softmax way, each channel represents a class, and argmx on the channel will find the best matched classes.
> And the BCE loss, if you read the documentation, you will find that the shape of input and target should be the same. In the cumstom_dataset, the shape of the target would be [N,1,H,W]. where channel-1 represents the classes index. In this case, the shape of the target and input are not the same.
> Hope that helps.
When setting number of classes to 1 on my dataset, the trainer gives me an error may be due to the class wise pixel distribution in my images to be in the range of [0,num_of_classes-1] that is [0,1] for 2 classes. If I set the num of classes to 1, then show should I label the pixels in my image according to the formula above (mmsegmentation format). I have prepared my dataset according to the DRIVE and STARE datasets in the mmsegmentation datasets directory that also deal with binary class problems and consist of two classes (background and the object class). Nevertheless, I am currently using weighted cross entropy loss (due to the unbalanced nature of my dataset) and it seems to train ok. However, I have one more question, if I attempt to use dcn (deformable convolutions) in the backbone, I get the following error:

missing keys in source state_dict: layer2.0.conv2.conv_offset.weight, layer2.0.conv2.conv_offset.bias, layer2.1.conv2.conv_offset.weight, layer2.1.conv2.conv_offset.bias, layer2.2.conv2.conv_offset.weight, layer2.2.conv2.conv_offset.bias, layer2.3.conv2.conv_offset.weight, layer2.3.conv2.conv_offset.bias, layer3.0.conv2.conv_offset.weight, layer3.0.conv2.conv_offset.bias, layer3.1.conv2.conv_offset.weight, layer3.1.conv2.conv_offset.bias, layer3.2.conv2.conv_offset.weight, layer3.2.conv2.conv_offset.bias, layer3.3.conv2.conv_offset.weight, layer3.3.conv2.conv_offset.bias, layer3.4.conv2.conv_offset.weight, layer3.4.conv2.conv_offset.bias, layer3.5.conv2.conv_offset.weight, layer3.5.conv2.conv_offset.bias, layer4.0.conv2.conv_offset.weight, layer4.0.conv2.conv_offset.bias, layer4.1.conv2.conv_offset.weight, layer4.1.conv2.conv_offset.bias, layer4.2.conv2.conv_offset.weight, layer4.2.conv2.conv_offset.bias

Any help on this will be appreciated. Thanks

**Comment by YLyeliang** [comment]
> > > > It seems like your error happened in building the lr hook. If that's true, you should check your modified config file, check your lr_config=dict(policy='xx',...). Make sure it's correct according to the original schedule config.
> > > > And, when you use binary cross-entropy loss(BCE), your class number should be 1, not 2 of background and object. Besides, the score in testing time also needed to change to sigmoid and set a threshold to predict the fore or background.
> > > 
> > > 
> > > Hi thanks and yes I fixed the policy issue by modifying the optimizer. However, I was wondering that why should I keep the number of classes as 1? because in other sample datasets with only one object class and the other background class, the number of classes is equal to 2. Kindly elaborate on this part. Thanks
> > 
> > 
> > The reason number of classes should be 1 is that you used sigmoid instead of softmax. The sigmoid output the scores of the object belong to fore or background. Your output of sigmoid on logits will limit the score to [0,1]. Then, a threshold will be set to determine the classes, normally it's 0.5( In this case, it's equal softmax in two classes segmentation task). In this case, 1 channel can be represented to fore or background according to the score in this channel. While, in the softmax way, each channel represents a class, and argmx on the channel will find the best matched classes.
> > And the BCE loss, if you read the documentation, you will find that the shape of input and target should be the same. In the cumstom_dataset, the shape of the target would be [N,1,H,W]. where channel-1 represents the classes index. In this case, the shape of the target and input are not the same.
> > Hope that helps.
> > When setting number of classes to 1 on my dataset, the trainer gives me an error may be due to the class wise pixel distribution in my images to be in the range of [0,num_of_classes-1] that is [0,1] for 2 classes. If I set the num of classes to 1, then show should I label the pixels in my image according to the formula above (mmsegmentation format). I have prepared my dataset according to the DRIVE and STARE datasets in the mmsegmentation datasets directory that also deal with binary class problems and consist of two classes (background and the object class). Nevertheless, I am currently using weighted cross entropy loss (due to the unbalanced nature of my dataset) and it seems to train ok. However, I have one more question, if I attempt to use dcn (deformable convolutions) in the backbone, I get the following error:
> 
> missing keys in source state_dict: layer2.0.conv2.conv_offset.weight, layer2.0.conv2.conv_offset.bias, layer2.1.conv2.conv_offset.weight, layer2.1.conv2.conv_offset.bias, layer2.2.conv2.conv_offset.weight, layer2.2.conv2.conv_offset.bias, layer2.3.conv2.conv_offset.weight, layer2.3.conv2.conv_offset.bias, layer3.0.conv2.conv_offset.weight, layer3.0.conv2.conv_offset.bias, layer3.1.conv2.conv_offset.weight, layer3.1.conv2.conv_offset.bias, layer3.2.conv2.conv_offset.weight, layer3.2.conv2.conv_offset.bias, layer3.3.conv2.conv_offset.weight, layer3.3.conv2.conv_offset.bias, layer3.4.conv2.conv_offset.weight, layer3.4.conv2.conv_offset.bias, layer3.5.conv2.conv_offset.weight, layer3.5.conv2.conv_offset.bias, layer4.0.conv2.conv_offset.weight, layer4.0.conv2.conv_offset.bias, layer4.1.conv2.conv_offset.weight, layer4.1.conv2.conv_offset.bias, layer4.2.conv2.conv_offset.weight, layer4.2.conv2.conv_offset.bias
> 
> Any help on this will be appreciated. Thanks

1, you must be used the DCN, the deformable convolution. the conv_offset only used for dcn and you set it.
2. following the above, your checkpoint didn't use DCN, then it's not match. The best way is don't care, since it has only
small effect on segmentation task.
3. The other way, if you want to exactly match your checkpoint to your model. Then, you should check your model config and see if it's the same as your loaded state_dict.

**Comment by rubeea** [comment]
@YLyeliang thanks for the suggestion but I guess it does not have a major effect on the training process so it seems ok. One last question, if I want to train using weighted binary cross entropy loss (instead of weighted cross entropy loss), I get the following error:

return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
   2583 
   2584 

RuntimeError: The size of tensor a (2) must match the size of tensor b (256) at non-singleton dimension 3

The training works fine with the binary cross entropy loss without using the weights. Does that mean that weighted BCE loss can not be used with imbalanced dataset?
