### ISSUE TITLE
Inconsistent evaluation results compared with other popular packages

### ISSUE THREAD

**Issue by Fivethousand5k** [open-mmlab/mmsegmentation#2888]
Hello, I've been trying to compute the Dice score for segmentation results, but I noticed some inconsistent results compared to popular packages like Monai and Torchmetrics. I was wondering if you could shed some light on why this might be the case? Thanks.

Here is a demo code to reproduce the situation:

``` python
import os
from mmseg.core.evaluation import mean_dice # dice calculation by mmseg
from monai.metrics import compute_dice  # dice calculation by monai
from torchmetrics.functional import dice    # dice calulation by torchmetrics
from PIL import Image
import torch
import numpy as np


def my_compute_dice(input,gt):
    input = input.flatten()
    gt = gt.flatten()

    # compute dice
    intersection = np.sum(input*gt)
    dice = 2*intersection/(np.sum(input)+np.sum(gt))
    return dice


test_pred = "im0162-pred.ah.png"
test_gt = "im0162-gt.ah.png"

# load image and gt
image = np.array(Image.open(test_pred))
gt = np.array(Image.open(test_gt))

image = image/255
gt = gt/255

print(np.unique(image))
print(np.unique(gt))

# compute dice with mmseg
mmseg_dice = mean_dice([image], [gt], num_classes=1, ignore_index=0)
print("mmseg dice: ", mmseg_dice)

# compute dice with monai
monai_dice = compute_dice(torch.from_numpy(image), torch.from_numpy(gt), include_background=False)
print("monai dice: ", monai_dice)

# compute dice with torchmetrics
torch_dice = dice(torch.from_numpy(image).int(), torch.from_numpy(gt).int(),ignore_index=0)
print("torch dice: ", torch_dice)

# mydice
mydice = my_compute_dice(image, gt)
print("my dice: ", mydice)
```

And its corresponding output:
```
[0. 1.]
[0. 1.]
mmseg dice:  {'aAcc': array(0.84950298), 'Dice': array([0.84950298]), 'Acc': array([0.84950298])}
monai dice:  tensor(0.8381)
torch dice:  tensor(0.8381)
my dice:  0.838130731133232
```
I also attach the files I test upon:
- pred
![im0162-pred ah](https://user-images.githubusercontent.com/38652084/231482018-877f5997-e73e-48fb-a919-e0e93be1e968.png)

- gt
![im0162-gt ah](https://user-images.githubusercontent.com/38652084/231482047-51a4eaea-576b-4ef7-974e-9a7b137abf2a.png)

**Comment by Fivethousand5k** [comment]
After changing the arguments `num_classes` to 2:  `mmseg_dice = mean_dice([image], [gt], num_classes=2, ignore_index=0)`

Here are the updated results, which look more weird.

```
mmseg dice:  {'aAcc': array(0.84950298), 'Dice': array([0.       , 0.9186284]), 'Acc': array([       nan, 0.84950298])}
monai dice:  tensor(0.8381)
torch dice:  tensor(0.8381)
my dice:  0.838130731133232
```

**Comment by MengzhangLI** [comment]
Try to use `ignore_index=255`?

**Comment by Fivethousand5k** [comment]
Thanks! It works. 
With the help of the kind mmseg maintainers, I eventually figure out how to calculate dice with mmseg.
Here is the final version of code and the results are listed as follows.


- Code
```
# compute dice with mmseg
mmseg_dice = mean_dice([image], [gt], num_classes=2,ignore_index=255)
print("mmseg dice: ", mmseg_dice)
```

- Results
```
mmseg dice:  {'aAcc': array(0.97661629), 'Dice': array([0.98739789, 0.83813073]), 'Acc': array([0.98636988, 0.84950298])}
monai dice:  tensor(0.8381)
torch dice:  tensor(0.8381)
my dice:  0.838130731133232
```

**Comment by Fivethousand5k** [comment]
Btw, I recommend you add more detailed examples in the annotations for this function. (Maybe I could initiate a pull request myself). Otherwise, new users may face similar issues like me since the argument setting is quite different from the other popular repos.

**Comment by zhengbiqing** [comment]
@Fivethousand5k  你好，我用deeplabv3plus训练2值数据，但是结果却一直是：
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background | 100.0 | 100.0 |
|    top     |  nan  |  nan  |
+------------+-------+-------+

请问你知道什么原因吗？ 你的训练配置能否分享下？

**Comment by Fivethousand5k** [comment]
Hi, could you visualize some outputs?

**Comment by zhengbiqing** [comment]
感谢回复。以下是输出（最后是ctrl+c退出的）：
(torch14) G:\BaiduNetdiskDownload\mmsegmentation-main\tools>python train-eye1.py
06/13 15:42:15 - mmengine - INFO -
------------------------------------------------------------
System environment:
    sys.platform: win32
    Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
    CUDA available: True
    numpy_random_seed: 1743944132
    GPU 0: GeForce RTX 2080
    CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
    NVCC: Cuda compilation tools, release 10.1, V10.1.10
    MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30140 版
    GCC: n/a
    PyTorch: 1.13.0+cu116
    PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

    TorchVision: 0.14.0+cu116
    OpenCV: 4.5.3
    MMEngine: 0.7.3

Runtime environment:
    cudnn_benchmark: True
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

06/13 15:42:16 - mmengine - INFO - Config:
norm_cfg = dict(type='SyncBN', requires_grad=True)
data_preprocessor = dict(
    type='SegDataPreProcessor',
    mean=[0.0255, 0.0238, 0.0066],
    std=[0.0818, 0.076, 0.0213],
    bgr_to_rgb=True,
    pad_val=0,
    seg_pad_val=255,
    size=(512, 512))
model = dict(
    type='EncoderDecoder',
    data_preprocessor=dict(
        type='SegDataPreProcessor',
        mean=[0.0255, 0.0238, 0.0066],
        std=[0.0818, 0.076, 0.0213],
        bgr_to_rgb=True,
        pad_val=0,
        seg_pad_val=255,
        size=(512, 512)),
    pretrained='open-mmlab://resnet50_v1c',
    backbone=dict(
        type='ResNetV1c',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True),
    decode_head=dict(
        type='ASPPHead',
        in_channels=2048,
        in_index=3,
        channels=512,
        dilations=(1, 12, 24, 36),
        dropout_ratio=0.1,
        num_classes=2,
        out_channels=1,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=2,
        out_channels=1,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=0.4)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'Eye1Dataset'
data_root = 'G:\\BaiduNetdiskDownload\\mmsegmentation-main\\datasets'
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(
        type='RandomResize',
        scale=(2048, 512),
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(2048, 512), keep_ratio=True),
    dict(type='LoadAnnotations'),
    dict(type='PackSegInputs')
]
img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
tta_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(
        type='TestTimeAug',
        transforms=[[{
            'type': 'Resize',
            'scale_factor': 0.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 0.75,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.0,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.25,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.75,
            'keep_ratio': True
        }],
                    [{
                        'type': 'RandomFlip',
                        'prob': 0.0,
                        'direction': 'horizontal'
                    }, {
                        'type': 'RandomFlip',
                        'prob': 1.0,
                        'direction': 'horizontal'
                    }], [{
                        'type': 'LoadAnnotations'
                    }], [{
                        'type': 'PackSegInputs'
                    }]])
]
train_dataloader = dict(
    batch_size=2,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type='Eye1Dataset',
        data_root='G:\\BaiduNetdiskDownload\\mmsegmentation-main\\datasets',
        data_prefix=dict(
            img_path='JPEGImages', seg_map_path='SegmentationClass'),
        ann_file='ImageSets/Segmentation/train.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(
                type='RandomResize',
                scale=(2048, 512),
                ratio_range=(0.5, 2.0),
                keep_ratio=True),
            dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(type='PackSegInputs')
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='Eye1Dataset',
        data_root='G:\\BaiduNetdiskDownload\\mmsegmentation-main\\datasets',
        data_prefix=dict(
            img_path='JPEGImages', seg_map_path='SegmentationClass'),
        ann_file='ImageSets/Segmentation/val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(2048, 512), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ]))
test_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='Eye1Dataset',
        data_root='G:\\BaiduNetdiskDownload\\mmsegmentation-main\\datasets',
        data_prefix=dict(
            img_path='JPEGImages', seg_map_path='SegmentationClass'),
        ann_file='ImageSets/Segmentation/val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(2048, 512), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ]))
val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
test_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
default_scope = 'mmseg'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='SegLocalVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    name='visualizer')
log_processor = dict(by_epoch=False)
log_level = 'INFO'
load_from = None
resume = False
tta_model = dict(type='SegTTAModel')
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005),
    clip_grad=None)
param_scheduler = [
    dict(
        type='PolyLR',
        eta_min=0.0001,
        power=0.9,
        begin=0,
        end=20000,
        by_epoch=False)
]
train_cfg = dict(type='IterBasedTrainLoop', max_iters=2000, val_interval=100)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50, log_metric_by_epoch=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', by_epoch=False, interval=100),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='SegVisualizationHook'))
launcher = 'none'
work_dir = 'J:\\zbq\\ai_data\\mmlab-mmsegmentation\\work-dir-eye'

g:\baidunetdiskdownload\mmsegmentation-main\mmseg\models\backbones\resnet.py:431: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
g:\baidunetdiskdownload\mmsegmentation-main\mmseg\models\decode_heads\decode_head.py:136: UserWarning: threshold is not defined for binary, and defaultsto 0.3
  warnings.warn('threshold is not defined for binary, and defaults'
g:\baidunetdiskdownload\mmsegmentation-main\mmseg\models\builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()``
  warnings.warn('``build_loss`` would be deprecated soon, please use '
g:\baidunetdiskdownload\mmsegmentation-main\mmseg\models\losses\cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
06/13 15:42:18 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
g:\baidunetdiskdownload\mmsegmentation-main\mmseg\engine\hooks\visualization_hook.py:61: UserWarning: The draw is False, it means that the hook for visualization will not take effect. The results will NOT be visualized or stored.
  warnings.warn('The draw is False, it means that the '
06/13 15:42:18 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook
(BELOW_NORMAL) LoggerHook
 --------------------
before_train:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(VERY_LOW    ) CheckpointHook
 --------------------
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) DistSamplerSeedHook
 --------------------
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
 --------------------
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) SegVisualizationHook
(BELOW_NORMAL) LoggerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
after_train_epoch:
(NORMAL      ) IterTimerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
before_val_epoch:
(NORMAL      ) IterTimerHook
 --------------------
before_val_iter:
(NORMAL      ) IterTimerHook
 --------------------
after_val_iter:
(NORMAL      ) IterTimerHook
(NORMAL      ) SegVisualizationHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(BELOW_NORMAL) LoggerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
after_train:
(VERY_LOW    ) CheckpointHook
 --------------------
before_test_epoch:
(NORMAL      ) IterTimerHook
 --------------------
before_test_iter:
(NORMAL      ) IterTimerHook
 --------------------
after_test_iter:
(NORMAL      ) IterTimerHook
(NORMAL      ) SegVisualizationHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_run:
(BELOW_NORMAL) LoggerHook
 --------------------
06/13 15:42:18 - mmengine - WARNING - The prefix is not set in metric class IoUMetric.
06/13 15:42:20 - mmengine - INFO - load model from: open-mmlab://resnet50_v1c
06/13 15:42:20 - mmengine - INFO - Loads checkpoint by openmmlab backend from path: open-mmlab://resnet50_v1c
06/13 15:42:20 - mmengine - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

06/13 15:42:20 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
06/13 15:42:20 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
06/13 15:42:20 - mmengine - INFO - Checkpoints will be saved to J:\zbq\ai_data\mmlab-mmsegmentation\work-dir-eye.
06/13 15:42:30 - mmengine - INFO - Exp name: deeplabv3_r50-d8_4xb4-20k_voc12aug-512x512_20230613_154208
06/13 15:42:30 - mmengine - INFO - Iter(train) [  10/2000]  lr: 9.9960e-03  eta: 0:34:24  time: 1.0377  data_time: 0.0367  memory: 4796  loss: 0.3570  decode.loss_ce: 0.1936  decode.acc_seg: 100.0000  aux.loss_ce: 0.1634  aux.acc_seg: 100.0000
06/13 15:42:51 - mmengine - INFO - Iter(train) [  50/2000]  lr: 9.9782e-03  eta: 0:20:00  time: 0.5114  data_time: 0.0022  memory: 3525  loss: 0.0035  decode.loss_ce: 0.0001  decode.acc_seg: 100.0000  aux.loss_ce: 0.0034  aux.acc_seg: 100.0000
06/13 15:43:17 - mmengine - INFO - Iter(train) [ 100/2000]  lr: 9.9559e-03  eta: 0:17:56  time: 0.5263  data_time: 0.0017  memory: 3525  loss: 0.0016  decode.loss_ce: 0.0000  decode.acc_seg: 100.0000  aux.loss_ce: 0.0016  aux.acc_seg: 100.0000
06/13 15:43:17 - mmengine - INFO - Saving checkpoint at 100 iterations
06/13 15:43:27 - mmengine - INFO - per class results:
06/13 15:43:27 - mmengine - INFO -
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background | 100.0 | 100.0 |
|    top     |  nan  |  nan  |
+------------+-------+-------+
06/13 15:43:27 - mmengine - INFO - Iter(val) [5/5]    aAcc: 100.0000  mIoU: 100.0000  mAcc: 100.0000  data_time: 0.4138  time: 0.7890
06/13 15:43:53 - mmengine - INFO - Iter(train) [ 150/2000]  lr: 9.9336e-03  eta: 0:16:58  time: 0.5189  data_time: 0.0021  memory: 3862  loss: 0.0013  decode.loss_ce: 0.0000  decode.acc_seg: 100.0000  aux.loss_ce: 0.0013  aux.acc_seg: 100.0000
06/13 15:44:20 - mmengine - INFO - Iter(train) [ 200/2000]  lr: 9.9113e-03  eta: 0:16:19  time: 0.5166  data_time: 0.0020  memory: 3525  loss: 0.0009  decode.loss_ce: 0.0000  decode.acc_seg: 100.0000  aux.loss_ce: 0.0009  aux.acc_seg: 100.0000
06/13 15:44:20 - mmengine - INFO - Saving checkpoint at 200 iterations
06/13 15:44:28 - mmengine - INFO - per class results:
06/13 15:44:28 - mmengine - INFO -
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background | 100.0 | 100.0 |
|    top     |  nan  |  nan  |
+------------+-------+-------+
06/13 15:44:28 - mmengine - INFO - Iter(val) [5/5]    aAcc: 100.0000  mIoU: 100.0000  mAcc: 100.0000  data_time: 0.0027  time: 0.1308
06/13 15:44:53 - mmengine - INFO - Iter(train) [ 250/2000]  lr: 9.8890e-03  eta: 0:15:42  time: 0.5167  data_time: 0.0019  memory: 3525  loss: 0.0009  decode.loss_ce: 0.0000  decode.acc_seg: 100.0000  aux.loss_ce: 0.0009  aux.acc_seg: 100.0000
06/13 15:45:20 - mmengine - INFO - Iter(train) [ 300/2000]  lr: 9.8667e-03  eta: 0:15:12  time: 0.5176  data_time: 0.0019  memory: 3525  loss: 0.0008  decode.loss_ce: 0.0000  decode.acc_seg: 100.0000  aux.loss_ce: 0.0008  aux.acc_seg: 100.0000
06/13 15:45:20 - mmengine - INFO - Saving checkpoint at 300 iterations
06/13 15:45:28 - mmengine - INFO - per class results:
06/13 15:45:28 - mmengine - INFO -
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background | 100.0 | 100.0 |
|    top     |  nan  |  nan  |
+------------+-------+-------+
06/13 15:45:28 - mmengine - INFO - Iter(val) [5/5]    aAcc: 100.0000  mIoU: 100.0000  mAcc: 100.0000  data_time: 0.0028  time: 0.1300
Traceback (most recent call last):
  File "train-eye1.py", line 104, in <module>
    main()
  File "train-eye1.py", line 100, in main
    runner.train()
  File "G:\ProgramData\Anaconda3\envs\torch14\lib\site-packages\mmengine\runner\runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "G:\ProgramData\Anaconda3\envs\torch14\lib\site-packages\mmengine\runner\loops.py", line 278, in run
    self.run_iter(data_batch)
  File "G:\ProgramData\Anaconda3\envs\torch14\lib\site-packages\mmengine\runner\loops.py", line 304, in run_iter
    self.runner.call_hook(
  File "G:\ProgramData\Anaconda3\envs\torch14\lib\site-packages\mmengine\runner\runner.py", line 1783, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "G:\ProgramData\Anaconda3\envs\torch14\lib\site-packages\mmengine\hooks\runtime_info_hook.py", line 120, in after_train_iter
    runner.message_hub.update_scalar(f'train/{key}', value)
  File "G:\ProgramData\Anaconda3\envs\torch14\lib\site-packages\mmengine\logging\message_hub.py", line 132, in update_scalar
    checked_value = self._get_valid_value(value)
  File "G:\ProgramData\Anaconda3\envs\torch14\lib\site-packages\mmengine\logging\message_hub.py", line 332, in _get_valid_value
    value = value.item()
KeyboardInterrupt
^C
