### ISSUE TITLE
train.py No module named 'mmseg.datasets.samplers'

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmsegmentation#2892]
my environment list:
- branch: dev-1.x
- mmcv :  2.0.0rc4 
- mmdet : 3.0.0rc6
- mmengine  :  0.7.0     
- mmsegmentation  : 1.0.0rc6  

command:
```
python ./tools/train.py /opt/mmsegmentation/configs/pspnet/pspnet_r50-d8_4xb2-40k_cityscapes-512x1024.py --cfg-options runner.max_iters=1 --work-dir work-dir
```

Traceback:
```
/opt/mmsegmentation/mmseg/models/backbones/resnet.py:431: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
/opt/mmsegmentation/mmseg/models/builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()`` 
  warnings.warn('``build_loss`` would be deprecated soon, please use '
/opt/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:236: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  'Default ``avg_non_ignore`` is False, if you would like to '
/opt/mmsegmentation/mmseg/engine/hooks/visualization_hook.py:61: UserWarning: The draw is False, it means that the hook for visualization will not take effect. The results will NOT be visualized or stored.
  warnings.warn('The draw is False, it means that the '
Traceback (most recent call last):
  File "/opt/mmsegmentation/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/mmsegmentation/mmengine/mmengine/runner/loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "/opt/mmsegmentation/mmengine/mmengine/runner/base_loop.py", line 27, in __init__
    dataloader, seed=runner.seed, diff_rank_seed=diff_rank_seed)
  File "/opt/mmsegmentation/mmengine/mmengine/runner/runner.py", line 1360, in build_dataloader
    default_args=dict(dataset=dataset, seed=sampler_seed))
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/mmsegmentation/mmengine/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 442, in get
    self.import_from_location()
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 376, in import_from_location
    import_module(loc)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmseg.datasets.samplers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "/opt/mmsegmentation/tools/train.py", line 100, in main
    runner.train()
  File "/opt/mmsegmentation/mmengine/mmengine/runner/runner.py", line 1673, in train
    self._train_loop)  # type: ignore
  File "/opt/mmsegmentation/mmengine/mmengine/runner/runner.py", line 1467, in build_train_loop
    runner=self, dataloader=self._train_dataloader))
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/mmsegmentation/mmengine/mmengine/registry/build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
ModuleNotFoundError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: No module named 'mmseg.datasets.samplers'
```

**Comment by LHamnett** [comment]
I am also experiencing this issue. Trying to train a segmentation model via google colab.

Versions:
mmcv_version: 2.0.0
mmengine_version: 0.7.2
mmsegmentation_version: 1.0.0rc6

Config:
`Config:
norm_cfg = dict(type='BN', requires_grad=True)
data_preprocessor = dict(
    type='SegDataPreProcessor',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    bgr_to_rgb=True,
    pad_val=0,
    seg_pad_val=255,
    size=(512, 512))
model = dict(
    type='EncoderDecoder',
    data_preprocessor=dict(
        type='SegDataPreProcessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_val=0,
        seg_pad_val=255,
        size=(256, 256)),
    pretrained='pretrain/mit_b4.pth',
    backbone=dict(
        type='MixVisionTransformer',
        in_channels=3,
        embed_dims=64,
        num_stages=4,
        num_layers=[3, 8, 27, 3],
        num_heads=[1, 2, 5, 8],
        patch_sizes=[7, 3, 3, 3],
        sr_ratios=[8, 4, 2, 1],
        out_indices=(0, 1, 2, 3),
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.1,
        norm_cfg=dict(type='BN', requires_grad=True)),
    decode_head=dict(
        type='SegformerHead',
        in_channels=[64, 128, 320, 512],
        in_index=[0, 1, 2, 3],
        channels=256,
        dropout_ratio=0.1,
        num_classes=5,
        norm_cfg=dict(type='BN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'CancerDataset'
data_root = '/content/gdrive/MyDrive/BCSS_dataset'
crop_size = (256, 256)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='RandomResize', scale=(512, 512)),
    dict(type='RandomCrop', crop_size=(256, 256)),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackSegInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(256, 256), keep_ratio=True),
    dict(type='LoadAnnotations'),
    dict(type='PackSegInputs')
]
img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
tta_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(
        type='TestTimeAug',
        transforms=[[{
            'type': 'Resize',
            'scale_factor': 0.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 0.75,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.0,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.25,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.75,
            'keep_ratio': True
        }],
                    [{
                        'type': 'RandomFlip',
                        'prob': 0.0,
                        'direction': 'horizontal'
                    }, {
                        'type': 'RandomFlip',
                        'prob': 1.0,
                        'direction': 'horizontal'
                    }], [{
                        'type': 'LoadAnnotations'
                    }], [{
                        'type': 'PackSegInputs'
                    }]])
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type='CancerDataset',
        data_root='/content/gdrive/MyDrive/BCSS_dataset',
        data_prefix=dict(
            img_path=
            '/content/gdrive/MyDrive/BCSS_dataset/patched_images_masks/images',
            seg_map_path=
            '/content/gdrive/MyDrive/BCSS_dataset/patched_images_masks/masks'),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(type='RandomResize', scale=(512, 512)),
            dict(type='RandomCrop', crop_size=(256, 256)),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PackSegInputs')
        ],
        ann_file='splits/train.txt'))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='CancerDataset',
        data_root='/content/gdrive/MyDrive/BCSS_dataset',
        data_prefix=dict(
            img_path=
            '/content/gdrive/MyDrive/BCSS_dataset/patched_images_masks/images',
            seg_map_path=
            '/content/gdrive/MyDrive/BCSS_dataset/patched_images_masks/masks'),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(256, 256), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ],
        ann_file='splits/val.txt'))
test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='CancerDataset',
        data_root='/content/gdrive/MyDrive/BCSS_dataset',
        data_prefix=dict(
            img_path=
            '/content/gdrive/MyDrive/BCSS_dataset/patched_images_masks/images',
            seg_map_path=
            '/content/gdrive/MyDrive/BCSS_dataset/patched_images_masks/masks'),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(256, 256), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ],
        ann_file='splits/val.txt'))
val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
test_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
default_scope = 'mmseg'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='SegLocalVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    name='visualizer')
log_processor = dict(by_epoch=False)
log_level = 'INFO'
load_from = '/content/mmsegmentation/checkpoints'
resume = False
tta_model = dict(type='SegTTAModel')
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW', lr=6e-05, betas=(0.9, 0.999), weight_decay=0.01),
    paramwise_cfg=dict(
        custom_keys=dict(
            pos_block=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0),
            head=dict(lr_mult=10.0))))
param_scheduler = [
    dict(
        type='LinearLR', start_factor=1e-06, by_epoch=False, begin=0,
        end=1500),
    dict(
        type='PolyLR',
        eta_min=0.0,
        power=1.0,
        begin=1500,
        end=160000,
        by_epoch=False)
]
train_cfg = dict(type='IterBasedTrainLoop', max_iters=100, val_interval=20)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=20, log_metric_by_epoch=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', by_epoch=False, interval=100),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='SegVisualizationHook'))
work_dir = './work_dirs/tutorial'
randomness = dict(seed=0)` 

Command used:
runner.train()

Traceback:
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
    120             else:
--> 121                 obj = obj_cls(**args)  # type: ignore
    122 

15 frames
[/usr/local/lib/python3.9/dist-packages/mmengine/runner/loops.py](https://localhost:8080/#) in __init__(self, runner, dataloader, max_iters, val_begin, val_interval, dynamic_intervals)
    218             dynamic_intervals: Optional[List[Tuple[int, int]]] = None) -> None:
--> 219         super().__init__(runner, dataloader)
    220         self._max_iters = int(max_iters)

[/usr/local/lib/python3.9/dist-packages/mmengine/runner/base_loop.py](https://localhost:8080/#) in __init__(self, runner, dataloader)
     25                 'diff_rank_seed', False)
---> 26             self.dataloader = runner.build_dataloader(
     27                 dataloader, seed=runner.seed, diff_rank_seed=diff_rank_seed)

[/usr/local/lib/python3.9/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in build_dataloader(dataloader, seed, diff_rank_seed)
   1357             sampler_seed = None if diff_rank_seed else seed
-> 1358             sampler = DATA_SAMPLERS.build(
   1359                 sampler_cfg,

[/usr/local/lib/python3.9/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in build(self, cfg, *args, **kwargs)
    544         """
--> 545         return self.build_func(cfg, *args, **kwargs, registry=self)
    546 

[/usr/local/lib/python3.9/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     97         if isinstance(obj_type, str):
---> 98             obj_cls = registry.get(obj_type)
     99             if obj_cls is None:

[/usr/local/lib/python3.9/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in get(self, key)
    441         # lazy import the modules to register them into the registry
--> 442         self.import_from_location()
    443 

[/usr/local/lib/python3.9/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in import_from_location(self)
    375             for loc in self._locations:
--> 376                 import_module(loc)
    377                 print_log(

[/usr/lib/python3.9/importlib/__init__.py](https://localhost:8080/#) in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

/usr/lib/python3.9/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'mmseg.datasets.samplers'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-51-041c98d1998d>](https://localhost:8080/#) in <cell line: 4>()
      2 # from mmseg.datasets import samplers
      3 # mmseg.datasets.samplers = DATA_SAMPLERS
----> 4 runner.train()

[/usr/local/lib/python3.9/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in train(self)
   1670                 'initializing runner.')
   1671 
-> 1672         self._train_loop = self.build_train_loop(
   1673             self._train_loop)  # type: ignore
   1674 

[/usr/local/lib/python3.9/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in build_train_loop(self, loop)
   1462 
   1463         if 'type' in loop_cfg:
-> 1464             loop = LOOPS.build(
   1465                 loop_cfg,
   1466                 default_args=dict(

[/usr/local/lib/python3.9/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in build(self, cfg, *args, **kwargs)
    543             >>> model = MODELS.build(cfg)
    544         """
--> 545         return self.build_func(cfg, *args, **kwargs, registry=self)
    546 
    547     def _add_child(self, registry: 'Registry') -> None:

[/usr/local/lib/python3.9/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
    133             cls_location = '/'.join(
    134                 obj_cls.__module__.split('.'))  # type: ignore
--> 135             raise type(e)(
    136                 f'class `{obj_cls.__name__}` in '  # type: ignore
    137                 f'{cls_location}.py: {e}')

ModuleNotFoundError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: No module named 'mmseg.datasets.samplers'
`

**Comment by LHamnett** [comment]
Seems like a workaround for this issue is to use mmengine version 0.7 . I installed the packages like:
!mim install 'mmengine==0.7'
!mim install 'mmcv >= 2.0.0rc1'
And it seems to avoid this specific error message
