### ISSUE TITLE
ImportError: cannot import name 'MMSegInference' from 'mmseg.apis' (/home/cyj/mmsegmentation/mmseg/apis/__init__.py)

### ISSUE THREAD

**Issue by cyj95** [open-mmlab/mmsegmentation#2895]
i think there is something wrong about package version. 
![图片](https://user-images.githubusercontent.com/31176427/231726037-a00900bc-e92d-4cbf-b05f-15e57ba8816e.png)

my pip list:
Package                 Version    Editable project location
----------------------- ---------- -------------------------
absl-py                 1.4.0
addict                  2.4.0
aiofiles                23.1.0
aiohttp                 3.8.4
aiosignal               1.3.1
albumentations          1.3.0
altair                  4.2.2
anomalib                0.3.6      /home/cyj/anomalib-main
antlr4-python3-runtime  4.9.3
anyio                   3.6.2
async-timeout           4.0.2
attrs                   22.2.0
cachetools              5.3.0
certifi                 2022.9.24
charset-normalizer      2.1.1
click                   8.1.3
colorama                0.4.6
comet-ml                3.32.3
configobj               5.0.8
contourpy               1.0.5
cycler                  0.11.0
docker-pycreds          0.4.0
docstring-parser        0.15
dulwich                 0.21.3
einops                  0.6.0
entrypoints             0.4
everett                 3.1.0
faiss-cpu               1.7.2
faiss-gpu               1.7.2
fastapi                 0.92.0
ffmpy                   0.3.0
filelock                3.8.0
fonttools               4.37.4
frozenlist              1.3.3
fsspec                  2023.1.0
gitdb                   4.0.10
GitPython               3.1.31
google-auth             2.16.1
google-auth-oauthlib    0.4.6
gradio                  3.20.0
grpcio                  1.51.3
h11                     0.14.0
httpcore                0.16.3
httpx                   0.23.3
huggingface-hub         0.10.1
idna                    3.4
imageio                 2.22.2
imbalanced-learn        0.10.1
imgaug                  0.4.0
importlib-metadata      6.0.0
importlib-resources     5.12.0
Jinja2                  3.1.2
joblib                  1.2.0
jsonargparse            4.20.0
jsonschema              4.17.3
kiwisolver              1.4.4
kornia                  0.6.10
linkify-it-py           2.0.0
Markdown                3.4.1
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.6.1
mdit-py-plugins         0.3.3
mdurl                   0.1.2
mmcv                    2.0.0
mmengine                0.7.2
mmsegmentation          1.0.0      /home/cyj/mmsegmentation
model-index             0.1.11
multidict               6.0.4
munch                   2.5.0
networkx                2.8.7
numpy                   1.24.2
oauthlib                3.2.2
omegaconf               2.3.0
opencv-python           4.7.0.68
opencv-python-headless  4.7.0.72
openmim                 0.3.7
ordered-set             4.1.0
orjson                  3.8.7
packaging               21.3
pandas                  1.5.3
patchcore               0.1.0      /home/cyj/fusion
pathtools               0.1.2
Pillow                  9.2.0
pip                     22.2.2
pkgutil_resolve_name    1.3.10
pretrainedmodels        0.7.4
prettytable             3.7.0
promise                 2.3
protobuf                3.20.1
psutil                  5.9.4
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycryptodome            3.17
pydantic                1.10.5
pyDeprecate             0.3.2
pydub                   0.25.1
Pygments                2.15.0
pyparsing               3.0.9
pyrsistent              0.19.3
python-box              6.1.0
python-dateutil         2.8.2
python-multipart        0.0.6
pytorch-lightning       1.6.5
pytz                    2022.7.1
PyWavelets              1.4.1
PyYAML                  6.0
qudida                  0.0.4
requests                2.28.1
requests-oauthlib       1.3.1
requests-toolbelt       0.10.1
rfc3986                 1.5.0
rich                    13.3.3
rsa                     4.9
scikit-image            0.19.3
scikit-learn            1.1.2
scipy                   1.9.3
semantic-version        2.10.0
sentry-sdk              1.16.0
setproctitle            1.3.2
setuptools              63.4.1
shapely                 2.0.1
shortuuid               1.0.11
simplejson              3.18.3
six                     1.16.0
smmap                   5.0.0
sniffio                 1.3.0
starlette               0.25.0
tabulate                0.9.0
tensorboard             2.12.0
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
termcolor               2.2.0
threadpoolctl           3.1.0
tifffile                2022.10.10
timm                    0.5.4
toolz                   0.12.0
torch                   1.12.0
torchmetrics            0.9.3
torchtext               0.13.0
torchvision             0.13.0
tqdm                    4.64.1
typeshed-client         2.2.0
typing_extensions       4.4.0
uc-micro-py             1.0.1
urllib3                 1.26.12
uvicorn                 0.20.0
wandb                   0.12.17
wcwidth                 0.2.6
websocket-client        1.3.3
websockets              10.4
Werkzeug                2.2.3
wheel                   0.37.1
wrapt                   1.15.0
wurlitzer               3.0.3
yapf                    0.32.0
yarl                    1.8.2
zipp                    3.15.0

how to fix this ?

**Comment by xiexinch** [comment]
Hi @cyj95,
Try import `MMSegInferencer`.

https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/apis/mmseg_inferencer.py#L27
