### ISSUE TITLE
DCN with backbone in mmsegmentation

### ISSUE THREAD

**Issue by rubeea** [open-mmlab/mmsegmentation#290]
Can we use deformable convolutions with the backbone in mmsegmentation? When attempting to use dcn for my ResNetV1c backbone, I get the following error:

if I attempt to use dcn (deformable convolutions) in the backbone, I get the following error:

missing keys in source state_dict: layer2.0.conv2.conv_offset.weight, layer2.0.conv2.conv_offset.bias, layer2.1.conv2.conv_offset.weight, layer2.1.conv2.conv_offset.bias, layer2.2.conv2.conv_offset.weight, layer2.2.conv2.conv_offset.bias, layer2.3.conv2.conv_offset.weight, layer2.3.conv2.conv_offset.bias, layer3.0.conv2.conv_offset.weight, layer3.0.conv2.conv_offset.bias, layer3.1.conv2.conv_offset.weight, layer3.1.conv2.conv_offset.bias, layer3.2.conv2.conv_offset.weight, layer3.2.conv2.conv_offset.bias, layer3.3.conv2.conv_offset.weight, layer3.3.conv2.conv_offset.bias, layer3.4.conv2.conv_offset.weight, layer3.4.conv2.conv_offset.bias, layer3.5.conv2.conv_offset.weight, layer3.5.conv2.conv_offset.bias, layer4.0.conv2.conv_offset.weight, layer4.0.conv2.conv_offset.bias, layer4.1.conv2.conv_offset.weight, layer4.1.conv2.conv_offset.bias, layer4.2.conv2.conv_offset.weight, layer4.2.conv2.conv_offset.bias

Any help on this will be appreciated. Thanks

**Comment by rubeea** [comment]
I guess we can use it.

**Comment by aitelkob** [comment]
hey i have the same error did you find solution ?
