### ISSUE TITLE
Something went wrong when there is no augmentataion

### ISSUE THREAD

**Issue by HaisongW** [open-mmlab/mmsegmentation#2929]
Hello, Openmmlab-team, I get some bugs when I delete all the data-augmentation dicts, the information is :
```
  File "/home/fss/mmcv/mmcv/parallel/collate.py", line 23, in collate
    if not isinstance(batch, Sequence):
  File "/D/anaconda/envs/solobrh/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/D/anaconda/envs/solobrh/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I used my own datasets, before I delete all the augmentation dicts, the config file looks like:
![image](https://user-images.githubusercontent.com/95306032/233073713-d9f5527c-7d3c-4b8e-9b8e-4dc6c36b0f6a.png)
everything went well, I can train my model successfully, but when I delete all the augmentation dicts, the config file looks like:
![image](https://user-images.githubusercontent.com/95306032/233073916-ac26ebdb-fbbb-44de-8d9f-5effddd896de.png)
then the program can't work, is there any nice people can tell what's wrong in it?

And, by the way, maybe I missed something in mmsegmentation docs, I don't know how to train my model without data-augmentation, that's why I just delete all the augmentation dicts, can someone tell me how? Thanks a lot!

**Comment by ff98li** [comment]
Not sure if these are the causes of the issue but judging from your modified config, two things caught my attention:

1. `dict(type='PackSegInputs')`is missing in both of your train and test pipelines. You will also need to inlcude `dict(type='LoadAnnotations')` in your test pipeline. You might also want to add`dict(type='Normalize', **img_norm_cfg)` to both train and test pipelines, before `dict(type='PackSegInputs')`.
2. The path to the data root in your config doesn't seem to follow the linux directory structure (given the path to your `mmcv` directory in the error message).

**Comment by HaisongW** [comment]
> 

Thanks a lot!!
1.Maybe my mmseg version is too old, there is no `dict(type='PackSegInputs')` in default dataset config file, but it is OK when I trained my own datasets without this dict. Another weird thing is, there is also no `dict(type='LoadAnnotations')` in test_pipeline, but it worked perfectly, but now I am confused how mmseg ccalculate mIoU without `dict(type='LoadAnnotations')` . I think maybe missing `dict(type='Normalize', **img_norm_cfg)` caused this error, I will try it later.
2. The data path is OK, there are several hard drive mounted on this server, the windows-style name can be easily distinguished.

Thanks so much for replying :)

**Comment by xiexinch** [comment]
Hi @HaisongW,
In the old versions of mmseg, `LoadAnnotations` was hard code to dataset class.
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L108
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L258

In the old versions of mmseg, `Collect` is required, it won't modify your data. If you want to remove any data augmentations, might modify the default parameters of `Collect`.
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/formatting.py#L259

**Comment by HaisongW** [comment]
Thanks! @xiexinch ,
I tried to modify the dataset config file and `formatting.py` file many many times, but they all can't run successfully, so I gived up. Maybe I need get more familiar with mmsegmentation.
Thanks all, I will close this issue.

**Comment by BalasubramanyamEvani** [comment]
Hello @xiexinch I'm working on the 0.30.0 version of mmsegmentation. My training loop works fine but I'm facing a similar issue as mentioned in this thread evaluation. Below is my train and test pipeline:

```
train_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(type="LoadAnnotations"),
    dict(type="DefaultFormatBundle"),
    dict(type="Collect", keys=["img", "gt_semantic_seg"]),
]

test_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(type="DefaultFormatBundle"),
    dict(type="Collect", keys=["img"]),
]
```

The error I'm getting is as below:

```
raise TypeError(f'{name} must be a list, but got '
TypeError: imgs must be a list, but got <class 'torch.Tensor'>
```
which happens in this function:
```
def forward_test(self, imgs, img_metas, **kwargs):
        """
        Args:
            imgs (List[Tensor]): the outer list indicates test-time
                augmentations and inner Tensor should have a shape NxCxHxW,
                which contains all images in the batch.
            img_metas (List[List[dict]]): the outer list indicates test-time
                augs (multiscale, flip, etc.) and the inner list indicates
                images in a batch.
        """
        for var, name in [(imgs, 'imgs'), (img_metas, 'img_metas')]:
            if not isinstance(var, list):
                raise TypeError(f'{name} must be a list, but got '
                                f'{type(var)}')
```

Can you please let me know what's causing this and how to resolve it. I'd greatly appreciate it
