### ISSUE TITLE
A question on GPU memory usage of each layer in network

### ISSUE THREAD

**Issue by blackfeather-wang** [open-mmlab/mmsegmentation#297]
Thank you for this awesome repo. It is really helpful.

I hope to check the GPU memory usage of each layer in the segmentation models. Therefore I stop after the forward process of each layer (I run deeplabv3_r101-d8_769x769_40k_cityscapes.py in 4 Titan XP), and check the memory usage (using nvidia-smi). However, I found that the memory usage grows to ~4.8G and ~11G after self.stem self.layer1 in ResNet-101. With all the following layers (self.layer2,3,4), the GPU memory usage stays at ~11G.

I have a question on this observation. Why do the following layers contribute to such little memory usage?

**Comment by xvjiarui** [comment]
Hi @blackfeather-wang 
The memory usage is fixed during training after first iteration.
