### ISSUE TITLE
crop_size and img_scale order

### ISSUE THREAD

**Issue by nizhib** [open-mmlab/mmsegmentation#30]
In base dataset-related configs you usually have something like, e.g. in cityscapes
```python3
crop_size = (512, 1024)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(2048, 1024), ratio_range=(0.5, 2.0)),
```
does it mean that `crop_size` has height-width order while `img_scale` in `Resize` has width-height order as cityscapes is obviously has the width equal to ~2x of the height and crops are expected to have similar ratio?

**Comment by xvjiarui** [comment]
For term `size`, we usually use hight-width order in this codebase.
For term `img_scale` in `Resize` transform, the order doesn't matter. The smaller one will be considered as the short side, the larger one will be considered as the long side. Specifically, `img_scale=(2048, 1024)` means the max scale of the resized image is of long side 2048, short side 1024.

**Comment by nizhib** [comment]
Ok, got it, so `img_scale` is like "it must be able to fit into a rectangle of this size, optionally transposed".

**Comment by xvjiarui** [comment]
Hi @nizhib 
Yes. Note that `img_scale` is not the shape/size of the rectangle. `max(img_scale)` is the long side of the rectangle, `min(img_scale)` is the short side of the rectangle. And this rectangle's width is always larger than height.

**Comment by nizhib** [comment]
That is covered with "optionally transposed" :)

**Comment by xvjiarui** [comment]
Cool.

**Comment by ParashRahman** [comment]
For MMSegmentation 0.29, this does not seem to hold true. Now the order of img_scale seems to matter where the first element is the width and the second element is the height. Can you confirm this?

**Comment by ParashRahman** [comment]
After investigating, I found that mmcv.imresize takes in (w,h) while mmcv.pad takes in (h,w). When img_scale=(w,h) is passed as a tuple to mmseg with no other scaling parameters, it is passed to mmcv.imresize(w,h) properly. 

The way mmseg uses mmcv needs crop and pad to be (h, w).
