### ISSUE TITLE
Can I use the loss in mmdet directly in mmsegmentation?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#301]
Thank you for your amazing job!
I have a small question about “Loss”
Can I use the loss in mmdet directly in mmsegmentation?
For example, I found that there is no focal loss in mmsegmentation, but there is in mmdet. 
Can I directly take the focal loss in mmdet and use it in mmsegmentation? Or do I need to modify the focal loss of mmdet?
Any help will highly be appreciated.

**Comment by zhongqiu1245** [comment]
Any help will highly be appreciated.

**Comment by rubeea** [comment]
Hey,

I used the debug version from the mmdet focal loss version

**Comment by zhongqiu1245** [comment]
Thank you!@rubeea
