### ISSUE TITLE
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'roi_head\': {\'bbox_head\': {\'num_classes\': 1}, \'mask_head\': {\'num_classes\': 1}}}\nNone'

### ISSUE THREAD

**Issue by yogurtbuddy** [open-mmlab/mmsegmentation#3013]
how to fix it?

**Comment by 5201314ckz** [comment]
![image](https://github.com/open-mmlab/mmsegmentation/assets/34836949/dfc2019d-3331-4d00-89fd-b272bdd9bb21)

**Comment by 5201314ckz** [comment]
if i delete the code"_delete_=True,",it would be like this:
![1684155434940](https://github.com/open-mmlab/mmsegmentation/assets/34836949/b5b360e0-973b-4cbd-9699-3ff8c999f5af)

**Comment by xiexinch** [comment]
你可以用生成的配置文件对照源码中的参数，看一下缺少了什么。

**Comment by yogurtbuddy** [comment]
> 你可以用生成的配置文件对照源码中的参数，看一下缺少了什么。

请问一下源码的参数在哪里寻找，我的配置文件是根据官方文档中提供的例子进行修改的，没有添加或删除格式部分，仅修改了参数和路径。

**Comment by xiexinch** [comment]
这个看起来是 mmdetection 中的组件，您可以去 mmdetection 中查找对应的 detector。

**Comment by yogurtbuddy** [comment]
> 这个看起来是 mmdetection 中的组件，您可以去 mmdetection 中查找对应的 detector。

我在/configs里找到了用mask_rcnn训练cityscape数据集的配置文件，
![image](https://github.com/open-mmlab/mmsegmentation/assets/34836949/cad37fe9-e18d-47a8-bf9c-8954b5a385f6)
除了bbox_head以外，其他部份没有大的区别，因此我模仿该配置文件修改了我自己的配置文件，得到了以下的结果
![image](https://github.com/open-mmlab/mmsegmentation/assets/34836949/c1fea8da-757d-4b1b-9adf-0364108e7398)
发现这好像并不是配置文件的问题，而是其他问题

**Comment by yogurtbuddy** [comment]
> 这个看起来是 mmdetection 中的组件，您可以去 mmdetection 中查找对应的 detector。

关于您提到的detector的问题，可以请您详细讲述一下吗，我目前并不清楚如何修改detector使得模型能跑动。

**Comment by xiexinch** [comment]
您可以查阅 mmdetection 的文档 https://mmdetection.readthedocs.io/en/latest/
然后所有的检测器可以在这里找到 https://github.com/open-mmlab/mmdetection/tree/main/mmdet/models/detectors
Mask-RCNN 的代码在这里 https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/detectors/mask_rcnn.py
你可以检查一下你的配置文件缺失了哪些参数或者配置文件有没有写错。

**Comment by yogurtbuddy** [comment]
> 您可以查阅 mmdetection 的文档 https://mmdetection.readthedocs.io/en/latest/ 然后所有的检测器可以在这里找到 https://github.com/open-mmlab/mmdetection/tree/main/mmdet/models/detectors Mask-RCNN 的代码在这里 https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/detectors/mask_rcnn.py 你可以检查一下你的配置文件缺失了哪些参数或者配置文件有没有写错。

我使用的模型是cascade-mask_rcnn

**Comment by xiexinch** [comment]
您可以在mmdet中查找这个算法的配置文件。

**Comment by yogurtbuddy** [comment]
> 您可以查阅 mmdetection 的文档 https://mmdetection.readthedocs.io/en/latest/ 然后所有的检测器可以在这里找到 https://github.com/open-mmlab/mmdetection/tree/main/mmdet/models/detectors Mask-RCNN 的代码在这里 https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/detectors/mask_rcnn.py 你可以检查一下你的配置文件缺失了哪些参数或者配置文件有没有写错。

我查阅了mmdet的文档中，如何自定义训练自己的训练集，并完全跟随着他的指导完成
![1684314610051](https://github.com/open-mmlab/mmsegmentation/assets/34836949/3e1640c6-c702-4fa7-a80b-c783efbcf5ed)
，这是文档的教程，
![1684314644487](https://github.com/open-mmlab/mmsegmentation/assets/34836949/0a30f402-8f0e-45c5-8289-bb5a729abc1d)
我的配置文件完全按照他的指示更改并无问题

**Comment by xiexinch** [comment]
你可以给mmdet的开发者提issue说明这个问题

**Comment by skyfreetree** [comment]
可以检查一下data_prefix的路径
