### ISSUE TITLE
How to output eval summary(mean result)  when I'm training?

### ISSUE THREAD

**Issue by vanyuming** [open-mmlab/mmsegmentation#3016]
in old version 0.29.1,eval outputs every class's result and summary,but in new version1.0.0,it only output  class's reult.I want ImoU,but only output iou.

**Comment by xiexinch** [comment]
Hi @vanyuming,
Could you show me the results? The last table is the summary results.

**Comment by vanyuming** [comment]
version0.29.1:
eval
+------------+-------+-------+-------+--------+-----------+--------+
|   Class         |  IoU    |  Acc    |  Dice   | Fscore  | Precision  | Recall    |
+------------+-------+-------+-------+--------+-----------+--------+
| background | 91.27 | 97.14  | 95.44  | 95.44    |   93.79      | 97.14    |
| landslide    | 34.52   | 43.23  | 51.32  | 51.32    |   63.13      | 43.23    |
+------------+-------+-------+-------+--------+-----------+--------+
2023-05-17 06:06:34,818 - mmseg - INFO - Summary:
+-------+------+-------+-------+---------+------------+---------+
|  aAcc   | mIoU |  mAcc | mDice | mFscore | mPrecision | mRecall |
+-------+------+-------+-------+---------+------------+---------+
| 91.66   | 62.9   | 70.19  | 73.38  |  73.38    |   78.46        |  70.19    |
+-------+------+-------+-------+---------+------------+---------+

config:
evaluation = dict(interval=1000, metric=['mIoU', 'mDice', 'mFscore'])

version1.0.0:
eval
+------------+-------+-------+-------+--------+-----------+--------+
|   Class         |  IoU    |  Acc     |  Dice  | Fscore  | Precision  | Recall   |
+------------+-------+-------+-------+--------+-----------+--------+
| background | 87.67 | 99.94 | 93.43   | 93.43    |   87.71      | 99.94   |
| landslide     |  0.29   |  0.29  |  0.58    |  0.58     |   42.61      |  0.29    |
+------------+-------+-------+-------+--------+-----------+--------+

config:
val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU', 'mDice', 'mFscore'])

my issue: no results of summary when I'm training in new version.

**Comment by vanyuming** [comment]
@xiexinch

**Comment by xiexinch** [comment]
Hi @vanyuming,

```shell
05/17 14:40:01 - mmengine - INFO - 
+------------+-------+-------+-------+--------+-----------+--------+
|   Class    |  IoU  |  Acc  |  Dice | Fscore | Precision | Recall |
+------------+-------+-------+-------+--------+-----------+--------+
| background | 97.91 | 98.75 | 98.94 | 98.94  |   99.13   | 98.75  |
|   vessel   |  69.3 | 84.65 | 81.87 | 81.87  |   79.26   | 84.65  |
+------------+-------+-------+-------+--------+-----------+--------+
05/17 14:40:01 - mmengine - INFO - Iter(test) [2/2]    aAcc: 98.0000  mIoU: 83.6000  mAcc: 91.7000  mDice: 90.4100  mFscore: 90.4100  mPrecision: 89.2000  mRecall: 91.7000  data_time: 0.1328  time: 1.8789
```
Might find the summary at the last line of the log.

**Comment by vanyuming** [comment]
> Hi @vanyuming,
> 
> ```shell
> 05/17 14:40:01 - mmengine - INFO - 
> +------------+-------+-------+-------+--------+-----------+--------+
> |   Class    |  IoU  |  Acc  |  Dice | Fscore | Precision | Recall |
> +------------+-------+-------+-------+--------+-----------+--------+
> | background | 97.91 | 98.75 | 98.94 | 98.94  |   99.13   | 98.75  |
> |   vessel   |  69.3 | 84.65 | 81.87 | 81.87  |   79.26   | 84.65  |
> +------------+-------+-------+-------+--------+-----------+--------+
> 05/17 14:40:01 - mmengine - INFO - Iter(test) [2/2]    aAcc: 98.0000  mIoU: 83.6000  mAcc: 91.7000  mDice: 90.4100  mFscore: 90.4100  mPrecision: 89.2000  mRecall: 91.7000  data_time: 0.1328  time: 1.8789
> ```
> 
> Might find the summary at the last line of the log.

Thanks!
