### ISSUE TITLE
In version 1.x, how to use multi-metric evaluation, such as mIoU and mFscore

### ISSUE THREAD

**Issue by ander002** [open-mmlab/mmsegmentation#3018]
In version 0.x, it is implemented with the following code:
`evaluation = dict(interval=500, metric=('mIoU', 'mFscore'), save_best='mIoU')`
The output when evaluated is as follows：
![image](https://github.com/open-mmlab/mmsegmentation/assets/36130880/1fa6770e-ce16-4287-b341-956d338f12f5)

But how should the configuration file be written in version 1.x?

**Comment by xiexinch** [comment]
Hi @ander002,
Might modify the default dataset config.
https://github.com/open-mmlab/mmsegmentation/blob/main/configs/_base_/datasets/ade20k.py#L67
```python
val_evaluator = dict(type='IoUMetric', iou_metrics=['mDice', 'mIoU', 'mFscore'])
```
