### ISSUE TITLE
RuntimeError: The model and loaded state dict do not match exactly！

### ISSUE THREAD

**Issue by Scotter-Qian** [open-mmlab/mmsegmentation#302]
Does anyone know how to instantiate the model structure during the mmsegmentation project test?
There is a question， _RuntimeError: The model and loaded state dict do not match exactly_, when i loaded the trained model which resnet backbone had been changed! The Following parameters of the trained model could not be unexpected, which caused by the instantiated model not matching the model trained by me. 

_unexpected key in source state_dict: backbone.gcnet1.conv_mask.weight, backbone.gcnet1.conv_mask.bias, backbone.gcnet1.channel_add_conv.0.weight,               backbone.gcnet1.channel_add_conv.0.bias, backbone.gcnet1.channel_add_conv.1.weight, backbone.gcnet1.channel_add_conv.1.bias, backbone.gcnet1.chann              el_add_conv.3.weight, backbone.gcnet1.channel_add_conv.3.bias_

Looking forward to your early reply.

Thanks very much!

**Comment by xvjiarui** [comment]
Hi @Scotter-Qian 
Sorry for the late reply. Which model are you using for test? It seems that you defined new model. In that case, you may need to map the keys of the checkpoint.
