### ISSUE TITLE
pip install mmcv-full==latest+torch1.7.0+cu110 -f https://download.openmmlab.com/mmcv/dist/index.html

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmsegmentation#303]
Hello!When I install mmcv in my computer,it happend such a question.And my pip version is 20.2.4, I have tried much time on it, but did't sovel it. And I had search the web of "https://download.openmmlab.com/mmcv/dist/index.html".It did't have such a version.So can you help me sovel it?Thank you very much!And my cuda is 11.0,my gpu is RTX3090.

**Comment by rubeea** [comment]
> Hello!When I install mmcv in my computer,it happend such a question.And my pip version is 20.2.4, I have tried much time on it, but did't sovel it. And I had search the web of "[https://download.openmmlab.com/mmcv/dist/index.html".It](https://download.openmmlab.com/mmcv/dist/index.html%22.It) did't have such a version.So can you help me sovel it?Thank you very much!And my cuda is 11.0,my gpu is RTX3090.

May I know your pytorch and torchvision version? If it is torch==1.7.0+cu101 torchvision==0.8.1. You can try the following:
pip install mmcv-full==1.1.4

**Comment by baibaidedongdong** [comment]
yes，my torch version is1.7and torchversion is 0.8.1，I will try your method，thanks。



发自我的&nbsp;iPad


------------------ Original ------------------

**Comment by rubeea** [comment]
> yes，my torch version is1.7and torchversion is 0.8.1，I will try your method，thanks。 发自我的&nbsp;iPad
> […](#)
> ------------------ Original ------------------ From: rubeea <notifications@github.com&gt; Date: Tue,Dec 22,2020 10:30 AM To: open-mmlab/mmsegmentation <mmsegmentation@noreply.github.com&gt; Cc: baibaidedongdong <1716838988@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [open-mmlab/mmsegmentation] pip install mmcv-full==latest+torch1.7.0+cu110 -f https://download.openmmlab.com/mmcv/dist/index.html (#303) Hello!When I install mmcv in my computer,it happend such a question.And my pip version is 20.2.4, I have tried much time on it, but did't sovel it. And I had search the web of "[https://download.openmmlab.com/mmcv/dist/index.html".It](https://download.openmmlab.com/mmcv/dist/index.html%22.It) did't have such a version.So can you help me sovel it?Thank you very much!And my cuda is 11.0,my gpu is RTX3090. May I know your pytorch and torchvision version? If it is torch==1.7.0+cu101 torchvision==0.8.1. You can try the following: pip install mmcv-full==1.1.4 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes instead of writing mmcv-full==latest, write the exact version according to your pytorch and cuda such as mmcv-full==1.1.4
