### ISSUE TITLE
Loss = 0.0000 during training model for my CustomDataset

### ISSUE THREAD

**Issue by selecta81** [open-mmlab/mmsegmentation#304]
Hello, I am new here and I have a question to ask. I want to train a model with only one category.

I used CustomDataset (custom.py)

![image](https://user-images.githubusercontent.com/56350193/102283474-c7ec5100-3f32-11eb-8c9e-b0b2104d435f.png)

Model : 
![image](https://user-images.githubusercontent.com/56350193/102284655-d50a3f80-3f34-11eb-8748-373ae23620f1.png)

During training, my 'losses' are zero ? :

![image](https://user-images.githubusercontent.com/56350193/102284548-a1c7b080-3f34-11eb-82c9-01d7dcba21a6.png)

Please help me, how to solve my problem. Looking forward to your reply. Thank you.

**Comment by rubeea** [comment]
You want to train the model with one category the other category being the background? If yes, then keep the number of classes as 2.

**Comment by selecta81** [comment]
I got it :), thanks a lot for the reply. Can I train a model without a background class, can I achieve that with **reduce_zero_label = True**? The number of classes is 2?

**Comment by rubeea** [comment]
> I got it :), thanks a lot for the reply. Can I train a model without a background class, can I achieve that with **reduce_zero_label = True**? The number of classes is 2?

Hi,

I assume you are attempting to perform One class classification (OCC) or the unary classification. However, the methods used for that are quite different from the ones used for binary or multi class classification problems. I am not sure if you can achieve that with the current mmsegmentation framework. You can however, give it a try and report your results here as well for the knowledge of others :)

**Comment by selecta81** [comment]
> > I got it :), thanks a lot for the reply. Can I train a model without a background class, can I achieve that with **reduce_zero_label = True**? The number of classes is 2?
> 
> Hi,
> 
> I assume you are attempting to perform One class classification (OCC) or the unary classification. However, the methods used for that are quite different from the ones used for binary or multi class classification problems. I am not sure if you can achieve that with the current mmsegmentation framework. You can however, give it a try and report your results here as well for the knowledge of others :)

Thnx, rubeea. Definitely in the current mmsegmentation, I have to have two classes, for the model to work well.
