### ISSUE TITLE
AttributeError: 'EncoderDecoder' object has no attribute 'forward_dummy'

### ISSUE THREAD

**Issue by Carol-Liu-lin** [open-mmlab/mmsegmentation#3056]
**Describe the bug**
I use mmsegmentation 0.30 version since my code is built upon this.
But when I use the get_flops.py,  the error comes: 
AttributeError: 'EncoderDecoder' object has no attribute 'forward_dummy'

However, I check the class EncoderDecoder, which indeed has the function forward_dummy.
Could you tell me where does the error come from?

**Comment by Carol-Liu-lin** [comment]
I already solved this problem, so I will close this issue.

**Comment by yankee624** [comment]
@Carol-Liu-lin How did you solve the problem? I'm having the same issue

**Comment by ZiAn-Su** [comment]
delete 'model.forward = model.forward_dummy' in pytorch2torchscript.py
