### ISSUE TITLE
mask2former模型测试，debug

### ISSUE THREAD

**Issue by prosmail** [open-mmlab/mmsegmentation#3146]
模型测试的时候，想debug一遍代码，显示“Collecting data...”。不能显示正常的数据结构。请问是什么原因？

**Comment by MengzhangLI** [comment]
> 模型测试的时候，想debug一遍代码，显示“Collecting data...”。不能显示正常的数据结构。请问是什么原因？

https://www.cnblogs.com/r0xFED/p/12995166.html

**Comment by prosmail** [comment]
> > 模型测试的时候，想debug一遍代码，显示“Collecting data...”。不能显示正常的数据结构。请问是什么原因？
> 
> https://www.cnblogs.com/r0xFED/p/12995166.html

thank you！
