### ISSUE TITLE
How to prepare instance segmentation dataset for Mask2Former

### ISSUE THREAD

**Issue by Taited** [open-mmlab/mmsegmentation#3161]
Hi, I'm new to instance segmentation and only find a dataset preparation for semantic segmentation. How could I prepare an instance segmentation dataset for Mask2Former? Or mmseg do not support to train on instance segmentation?

**Comment by xiexinch** [comment]
Please refer to [mmdetection](https://github.com/open-mmlab/mmdetection/tree/main/configs/mask2former).
