### ISSUE TITLE
How to achieve single-machine multi-Gpus training on windows？

### ISSUE THREAD

**Issue by wujiang0156** [open-mmlab/mmsegmentation#3164]
How to achieve single-machine multi-Gpus training on windows？ 
I only find doc as:
sh tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM} [optional arguments]

How to achieve single-machine multi-Gpus training on windows？ 
can anybody tell me , please, thank you

**Comment by wujiang0156** [comment]
I have solved , thank you

**Comment by zhqshen** [comment]
hi, @wujiang0156, I have the same problem, how you solve this problem?

**Comment by zhqshen** [comment]
I find the way to solve the problem for training mmsegmentation model under multi-GPUs in one pc with windows OS. The key points are: (1) modify the backend='nccl' as backend='gloo' in env_cfg in the file default_runtime.py; (2) with the torch.distributed.launch, the --master_addr should be IPV6 address.

default_runtime.py:
default_scope = 'mmseg'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='gloo'),
)

command line:
python -m torch.distributed.launch --master_addr=IPV6_address --master_port=29500 --nnodes=1 --nproc_per_node=2 --node_rank=0 E:/open-mmlab/mmsegmentation/tools/train.py
