### ISSUE TITLE
ImportError: Failed to import custom modules from {'imports': 'mmpretrain.models', 'allow_failed_imports': False}, the current sys.path is: 

### ISSUE THREAD

**Issue by shallweiwei** [open-mmlab/mmsegmentation#3168]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I was trying to use train.py and it told me I have to set PYTHONPATH
**Reproduction**

1. What command or script did you run?

   ```none
   tool/train.py
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes.Yes
3. What dataset did you use?
My own dataset.
**Environment**
sys.platform: linux
Python: 3.8.16 (default, Jun 12 2023, 18:09:05) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7,8,9: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1
OpenCV: 4.7.0
MMEngine: 0.7.3
MMSegmentation: 1.1.0+0079076

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
ImportError: Failed to import mmpretrain.models
ModuleNotFoundError: No module named 'mmpretrain'

anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import mmpretrain.models
the current sys.path is: 
    /DeepLearning/xxx/test/mmsegmentation/tools
    /DeepLearning/xxx/test/mmsegmentation
    /home/xxx/anaconda3/envs/openmmlab/lib/python38.zip
    /home/xxx/anaconda3/envs/openmmlab/lib/python3.8
    /home/xxx/anaconda3/envs/openmmlab/lib/python3.8/lib-dynload
    /home/xxx/anaconda3/envs/openmmlab/lib/python3.8/site-packages
    /tmp/tmp_9hk8f9w

You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

**Comment by aroundabout** [comment]
same question

**Comment by shallweiwei** [comment]
I have saved this ,but it's quite weird.I just installed mmpretrain.But as we have to use pretrain model sometimes,mm doesn't install it automatically?

**Comment by HePengguang** [comment]
same issue, did you solve this?

**Comment by Ogier1024** [comment]
`pip install mmpretrain mmdet`

**Comment by Ogier1024** [comment]
`pip install mmpretrain mmdet`
it works for me

**Comment by Ogier1024** [comment]
`pip install mmpretrain mmdet`

**Comment by 1074727076** [comment]
> `pip install mmpretrain mmdet`

correctly
