### ISSUE TITLE
What does this d8 in r50-d8 mean?

### ISSUE THREAD

**Issue by JoyLuo** [open-mmlab/mmsegmentation#317]
What does this d8 in r50-d8 mean? r50-d8 is from fcn_r50-d8_512x512_40k_voc12aug.py.

**Comment by xvjiarui** [comment]
Hi @JoyLuo D-8 stands for dilate 8, which means the output stride is 8 with dilation.

**Comment by rubeea** [comment]
> Hi @JoyLuo D-8 stands for dilate 8, which means the output stride is 8 with dilation.

Can we apply DCN to the backbone?

**Comment by JoyLuo** [comment]
> Hi @JoyLuo D-8 stands for dilate 8, which means the output stride is 8 with dilation.

output of resnet is 8 times downsampling as input

**Comment by waqarsqureshi** [comment]
Does this mean the stem block downsample from 512 x 512 to 64 x 64*64, which is 8 times down sampling
