### ISSUE TITLE
About the function of "img_ratios"

### ISSUE THREAD

**Issue by daeunni** [open-mmlab/mmsegmentation#3173]
Hi, 
What is the function of `img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]`? 
I thought that it moderate input image scales(=resolution) diversely for data augmentation. 
It is true? or are there other important functions?

**Comment by shallweiwei** [comment]
Yes,it's used in testing time

**Comment by daeunni** [comment]
Thanks a lot.
