### ISSUE TITLE
Albumentations default key mapping mismatch

### ISSUE THREAD

**Issue by Alias-z** [open-mmlab/mmsegmentation#3179]
**Describe the bug**
Masks would not transform along with input images using the default key mapping `self.keymap_to_albu = { 'img': 'image',  'gt_masks': 'masks'}`

**Reproduction**

Using default setting:

```
 train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        keymap={'img': 'image', 'gt_masks': 'masks'}),
    dict(type='Resize', scale=crop_size, keep_ratio=False, interpolation='lanczos'), 
    dict(type='PackSegInputs', meta_keys=('img_path', 'img_shape', 'img', 'gt_masks'))
]
```
![A thaliana Lucia 07 2022 col-0 30m-1h after Infection 22162057 object id 0 png_0](https://github.com/open-mmlab/mmsegmentation/assets/66273343/e6e794e8-2827-4489-b3e9-51a7cc32f36c)

Using `keymap={'img': 'image', 'gt_seg_map': 'mask'}`

```
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=False),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        keymap={'img': 'image', 'gt_seg_map': 'mask'}),
    dict(type='Resize', scale=crop_size, keep_ratio=False, interpolation='lanczos'), 
    dict(type='PackSegInputs', meta_keys=('img_path', 'img_shape', 'img', 'gt_seg_map'))
]
```
![A thaliana Lucia 07 2022 col-0 3H LIGHT 22154449 object id 66 png_0](https://github.com/open-mmlab/mmsegmentation/assets/66273343/aadbaef3-561b-4dc7-8fe8-391b4b7bde63)

**Bug fix**
 `keymap={'img': 'image', 'gt_seg_map': 'mask'}`

**Comment by xiexinch** [comment]
Hi @Alias-z,
Could you create a pull request to fix this problem? We really appreciate it!

**Comment by Alias-z** [comment]
> 

Sure! See PR: https://github.com/open-mmlab/mmsegmentation/pull/3195
