### ISSUE TITLE
Bug in PR #71 : Erroneous GT semantic maps when label_map is not None

### ISSUE THREAD

**Issue by pavanteja295** [open-mmlab/mmsegmentation#320]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Erroneous gt semantic maps modification while using with custom_classes.

**Reproduction**

1. What command or script did you run?

    ```
 tools/dist_train.sh 1234  configs/fcn/fcn_r50-d8_512x1024_80k_cityscapes.py  2
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified? - **No modification**
3. What dataset did you use? - **Cityscapes**

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1050 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.1.6
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.7.0+e07e927

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
#71 - This bug arises when **label_map** is not None in the function **get_gt_seg_maps** in **mmseg/datasets/custom.py** and   **__call__** function of **LoadAnnotations** annotations class in **mmseg/datasets/pipelines/loading.py.**  In both of these functions when label_maps is not None the gt_seg_map is modified as follows: 

```
            for old_id, new_id in results['label_map'].items():
                gt_semantic_seg[gt_semantic_seg == old_id] = new_id
```
Here the above code only works as its indended purpose when the old_ids and new_ids are disjoint. Since the modification of gt_semantic_seg is done inplace  gt_semantic_seg results in erroneous map when the old_ids and new_ids are **not disjoint**.
A sample example is consider 
label_map ={0:1, 1:2} and our gt_semantic_seg map only consists of 1s and 2s 
Now, in the first iteration all **0 valued indices in gt_semantic_seg** are converted to **1s** and in the second iteration all 1 valued indexes in gt_semantic_seg **which includes previously converted 0s** valued indices  converted to 2s.  We finally end up with **modified semantic seg map with all 2s** which is not intended. 

A simple fix would be not modify gt_semantic_seg **inplace** and use a tempporary numpy array.

**Comment by xvjiarui** [comment]
Hi @pavanteja295 
Thanks for pointing out! Would you like to create a PR to fix it?

**Comment by pavanteja295** [comment]
Yes I would like to. However, I would also like to point out that fixing the above problem still did not stabilize my training. As a test case I'm trying to compare cityscapes training with and without label_maps. This is done by providing the set(custom_classes) = self.CLASSES. I will try to fix this and will get back to you over the full error report.

**Comment by xvjiarui** [comment]
Sounds good. Thx!

**Comment by pavanteja295** [comment]
Hello, I think the above can be fixed by the solution that has been proposed above. The only thing that one needs to take care of is passing custom_classes as a list or an ordered data which is very crucial in case of distributed training as custom_classes can be ordered differently if an unordered data type is used for custom classes.
