### ISSUE TITLE
Configuration crop_size in RandomCrop vs img_scale in Resize 

### ISSUE THREAD

**Issue by hasirk** [open-mmlab/mmsegmentation#3201]
In the configuration (e.g. configs\_base_ \datasets\citiscapes.py), there are below options to set crop_size and img_scale.
`crop_size = (512, 1024)`
`dict(type='Resize', img_scale=(2048, 1024), ratio_range=(0.5, 2.0)),`
` dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),`

Is it correct to assume `crop_size = (height, width)`  and `img_scale = (width, height)` when editing the file ?

Why is that width and height interchange ? Please explain the reason.

**Comment by ff98li** [comment]
You are correct.

`RandomCrop`: based on its docstring
https://github.com/open-mmlab/mmsegmentation/blob/00790766aff22bd6470dbbd9e89ea40685008395/mmseg/datasets/transforms/transforms.py#L205-L228

`crop_size` indeed follows the order of `(height, width)`.

`Resize`: a snippet of its code doing the actual resizing:
https://github.com/open-mmlab/mmcv/blob/987d34b0cf8d6cd8725258332fcfc8c54529b1ab/mmcv/transforms/processing.py#L185-L190
And after taking a closer look at `mmcv.imresize`
https://github.com/open-mmlab/mmcv/blob/987d34b0cf8d6cd8725258332fcfc8c54529b1ab/mmcv/image/geometric.py#L110-L117
It's essentially a wrapper of PIL/cv2's resizing functions, both of which assumes a shape order of `(width, height)`.

**Comment by hasirk** [comment]
Thank you for the explanation !
