### ISSUE TITLE
How to add custom loss like KL divergence? 

### ISSUE THREAD

**Issue by daeunni** [open-mmlab/mmsegmentation#3208]
Hi, how can I add custom loss to mmseg? :0 
please anyone help me

**Comment by daeunni** [comment]
I wanna calculate KL divergence loss between two outputs during training

**Comment by xiexinch** [comment]
Hi @daeunni,
Might follow our document https://mmsegmentation.readthedocs.io/en/latest/advanced_guides/add_models.html#add-new-loss
