### ISSUE TITLE
Estimated training time is too long

### ISSUE THREAD

**Issue by OSSome01** [open-mmlab/mmsegmentation#3209]
I was training a SETR ViT-L MLA model for 80k iterations on my custom dataset with a batch size of 1. The estimated time shown is 44 days!! I am training this model on a V100 GPU.

![image](https://github.com/open-mmlab/mmsegmentation/assets/47481859/afa15463-8bd8-47f2-9ba2-aa5ab51ef9d0)

I have trained other models like Segformer with MiT-b5 backbone (not the mmsegmentation implementation), which is of similar size to SETR, and I was able to do that in a day. 
I have just created 3 new files for training on my custom dataset:
1. A xyzData.py inside of mmseg/datasets/ which defines a class called xyzData 
2. A xyzData.py inside of configs/_base_/dataset/. I used the cityscapes.py file as a reference and just changed the path to my dataset, and the dataset type
3.  I wrote a config file setr_vit-l_mla_8xb1-80k_xyxData.py, which is again similar to the cityscapes config file.

I'm getting similar issues with other models as well. I got a eta of 33 days for KNet, and 30 days for PIDNet. Is this some issue with mmengine/mmsegmentation 
How should I fix this?

**Comment by xiexinch** [comment]
Hi @OSSome01,
It's really weird. Could you check whether your GPU is in use? You might check out the occupation of the GPU memory when the training program is running.

**Comment by OSSome01** [comment]
I checked it. The code was running on the CPU and not the GPU. 
I linked the issue back to my installation of pytorch. I used this command to install pytorch: `conda install pytorch torchvision -c pytorch` as given in the instructions in get_started.md But it doesn't install the GPU version of pytorch. I had to use `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia` which is mentioned on the pytorch website.
I think you should update the get_started.md to reflect this.
