### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmsegmentation#321]
Why the memory recorded in the log does not match the actual memory usage. And in the case of the same configuration, mmseg occupies more memory than other frameworks, such as pytorch-encoding, during training.

**Comment by shuaizzZ** [comment]
It uses 1.4 times the memory compared to pytorch-encoding.

**Comment by xvjiarui** [comment]
Hi @shuaizzZ 
The log is obtained with `torch.backends.cudnn.benchmark=True`. To get accurate memory usage, you should set it to `False` as stated [here](https://mmsegmentation.readthedocs.io/en/latest/model_zoo.html#common-settings).

**Comment by shuaizzZ** [comment]
@xvjiarui Thank you, exactly as you said.
