### ISSUE TITLE
Reason for seperate annotation loading during train and test

### ISSUE THREAD

**Issue by pavanteja295** [open-mmlab/mmsegmentation#322]
Hello, is there any specific reason to load annotations during train time using LoadAnnotations from mmseg/datasets/pipelines/loading.py differently during test using get_gt_seg_maps from mmseg/datasets/custom.py. Why cant one utilize LoadAnnotations during test time and just load the annotations needed whenever required? Am I missing some problem if I do the above change?

Thanks!

**Comment by xvjiarui** [comment]
Hi @pavanteja295 
Since in most inference cases, the annotation is not available. So we separate them as inference and evaluation.
