### ISSUE TITLE
KeyError: 'contrib/mobilenet_v3_large'

### ISSUE THREAD

**Issue by mtttsd** [open-mmlab/mmsegmentation#323]
Hi, thanks for your great work! I notice that MobileNetV3 is supported now. I tried 

> python tools/train.py configs/mobilenet_v3/lraspp_m-v3-d8_512x1024_320k_cityscapes.py

but got this

> KeyError: 'contrib/mobilenet_v3_large'

Any help to get the right pretrained MobileNetV3 backbone?

**Comment by xvjiarui** [comment]
Hi @mtttsd 
Please update your mmcv to the latest version 1.2.5.

**Comment by mtttsd** [comment]
@xvjiarui Thanks!
