### ISSUE TITLE
unet-s5-d16_fcn:The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by AnRanbel** [open-mmlab/mmsegmentation#3246]
**config file:** unet-s5-d16_fcn_4xb4-40k_chase-db1-128x128
**pretrained weight file:** download from [https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_128x128_40k_chase_db1/fcn_unet_s5-d16_128x128_40k_chase_db1_20201223_191051-11543527.pth](url)
TorchVision: 0.10.0+cu111
OpenCV: 4.8.0
MMEngine: 0.7.4
mmsegmentation:latest

it seems miss the backbone and head prefix? can it be modified and used? thank you.

**unexpected key in source state_dict:** backbone.encoder.0.0.convs.0.conv.weight, backbone.encoder.0.0.convs.0.bn.weight, backbone.encoder.0.0.convs.0.bn.bias, backbone.encoder.0.0.convs.0.bn.running_mean, backbone.encoder.0.0.convs.0.bn.running_var, backbone.encoder.0.0.convs.0.bn.num_batches_tracked, backbone.encoder.0.0.convs.1.conv.weight, backbone.encoder.0.0.convs.1.bn.weight, backbone.encoder.0.0.convs.1.bn.bias, backbone.encoder.0.0.convs.1.bn.running_mean, backbone.encoder.0.0.convs.1.bn.running_var, backbone.encoder.0.0.convs.1.bn.num_batches_tracked, backbone.encoder.1.1.convs.0.conv.weight, backbone.encoder.1.1.convs.0.bn.weight, backbone.encoder.1.1.convs.0.bn.bias, backbone.encoder.1.1.convs.0.bn.running_mean, backbone.encoder.1.1.convs.0.bn.running_var, backbone.encoder.1.1.convs.0.bn.num_batches_tracked, backbone.encoder.1.1.convs.1.conv.weight, backbone.encoder.1.1.convs.1.bn.weight, backbone.encoder.1.1.convs.1.bn.bias, backbone.encoder.1.1.convs.1.bn.running_mean, backbone.encoder.1.1.convs.1.bn.running_var, backbone.encoder.1.1.convs.1.bn.num_batches_tracked, backbone.encoder.2.1.convs.0.conv.weight, backbone.encoder.2.1.convs.0.bn.weight, backbone.encoder.2.1.convs.0.bn.bias, backbone.encoder.2.1.convs.0.bn.running_mean, backbone.encoder.2.1.convs.0.bn.running_var, backbone.encoder.2.1.convs.0.bn.num_batches_tracked, backbone.encoder.2.1.convs.1.conv.weight, backbone.encoder.2.1.convs.1.bn.weight, backbone.encoder.2.1.convs.1.bn.bias, backbone.encoder.2.1.convs.1.bn.running_mean, backbone.encoder.2.1.convs.1.bn.running_var, backbone.encoder.2.1.convs.1.bn.num_batches_tracked, backbone.encoder.3.1.convs.0.conv.weight, backbone.encoder.3.1.convs.0.bn.weight, backbone.encoder.3.1.convs.0.bn.bias, backbone.encoder.3.1.convs.0.bn.running_mean, backbone.encoder.3.1.convs.0.bn.running_var, backbone.encoder.3.1.convs.0.bn.num_batches_tracked, backbone.encoder.3.1.convs.1.conv.weight, backbone.encoder.3.1.convs.1.bn.weight, backbone.encoder.3.1.convs.1.bn.bias, backbone.encoder.3.1.convs.1.bn.running_mean, backbone.encoder.3.1.convs.1.bn.running_var, backbone.encoder.3.1.convs.1.bn.num_batches_tracked, backbone.encoder.4.1.convs.0.conv.weight, backbone.encoder.4.1.convs.0.bn.weight, backbone.encoder.4.1.convs.0.bn.bias, backbone.encoder.4.1.convs.0.bn.running_mean, backbone.encoder.4.1.convs.0.bn.running_var, backbone.encoder.4.1.convs.0.bn.num_batches_tracked, backbone.encoder.4.1.convs.1.conv.weight, backbone.encoder.4.1.convs.1.bn.weight, backbone.encoder.4.1.convs.1.bn.bias, backbone.encoder.4.1.convs.1.bn.running_mean, backbone.encoder.4.1.convs.1.bn.running_var, backbone.encoder.4.1.convs.1.bn.num_batches_tracked, backbone.decoder.0.conv_block.convs.0.conv.weight, backbone.decoder.0.conv_block.convs.0.bn.weight, backbone.decoder.0.conv_block.convs.0.bn.bias, backbone.decoder.0.conv_block.convs.0.bn.running_mean, backbone.decoder.0.conv_block.convs.0.bn.running_var, backbone.decoder.0.conv_block.convs.0.bn.num_batches_tracked, backbone.decoder.0.conv_block.convs.1.conv.weight, backbone.decoder.0.conv_block.convs.1.bn.weight, backbone.decoder.0.conv_block.convs.1.bn.bias, backbone.decoder.0.conv_block.convs.1.bn.running_mean, backbone.decoder.0.conv_block.convs.1.bn.running_var, backbone.decoder.0.conv_block.convs.1.bn.num_batches_tracked, backbone.decoder.0.upsample.interp_upsample.1.conv.weight, backbone.decoder.0.upsample.interp_upsample.1.bn.weight, backbone.decoder.0.upsample.interp_upsample.1.bn.bias, backbone.decoder.0.upsample.interp_upsample.1.bn.running_mean, backbone.decoder.0.upsample.interp_upsample.1.bn.running_var, backbone.decoder.0.upsample.interp_upsample.1.bn.num_batches_tracked, backbone.decoder.1.conv_block.convs.0.conv.weight, backbone.decoder.1.conv_block.convs.0.bn.weight, backbone.decoder.1.conv_block.convs.0.bn.bias, backbone.decoder.1.conv_block.convs.0.bn.running_mean, backbone.decoder.1.conv_block.convs.0.bn.running_var, backbone.decoder.1.conv_block.convs.0.bn.num_batches_tracked, backbone.decoder.1.conv_block.convs.1.conv.weight, backbone.decoder.1.conv_block.convs.1.bn.weight, backbone.decoder.1.conv_block.convs.1.bn.bias, backbone.decoder.1.conv_block.convs.1.bn.running_mean, backbone.decoder.1.conv_block.convs.1.bn.running_var, backbone.decoder.1.conv_block.convs.1.bn.num_batches_tracked, backbone.decoder.1.upsample.interp_upsample.1.conv.weight, backbone.decoder.1.upsample.interp_upsample.1.bn.weight, backbone.decoder.1.upsample.interp_upsample.1.bn.bias, backbone.decoder.1.upsample.interp_upsample.1.bn.running_mean, backbone.decoder.1.upsample.interp_upsample.1.bn.running_var, backbone.decoder.1.upsample.interp_upsample.1.bn.num_batches_tracked, backbone.decoder.2.conv_block.convs.0.conv.weight, backbone.decoder.2.conv_block.convs.0.bn.weight, backbone.decoder.2.conv_block.convs.0.bn.bias, backbone.decoder.2.conv_block.convs.0.bn.running_mean, backbone.decoder.2.conv_block.convs.0.bn.running_var, backbone.decoder.2.conv_block.convs.0.bn.num_batches_tracked, backbone.decoder.2.conv_block.convs.1.conv.weight, backbone.decoder.2.conv_block.convs.1.bn.weight, backbone.decoder.2.conv_block.convs.1.bn.bias, backbone.decoder.2.conv_block.convs.1.bn.running_mean, backbone.decoder.2.conv_block.convs.1.bn.running_var, backbone.decoder.2.conv_block.convs.1.bn.num_batches_tracked, backbone.decoder.2.upsample.interp_upsample.1.conv.weight, backbone.decoder.2.upsample.interp_upsample.1.bn.weight, backbone.decoder.2.upsample.interp_upsample.1.bn.bias, backbone.decoder.2.upsample.interp_upsample.1.bn.running_mean, backbone.decoder.2.upsample.interp_upsample.1.bn.running_var, backbone.decoder.2.upsample.interp_upsample.1.bn.num_batches_tracked, backbone.decoder.3.conv_block.convs.0.conv.weight, backbone.decoder.3.conv_block.convs.0.bn.weight, backbone.decoder.3.conv_block.convs.0.bn.bias, backbone.decoder.3.conv_block.convs.0.bn.running_mean, backbone.decoder.3.conv_block.convs.0.bn.running_var, backbone.decoder.3.conv_block.convs.0.bn.num_batches_tracked, backbone.decoder.3.conv_block.convs.1.conv.weight, backbone.decoder.3.conv_block.convs.1.bn.weight, backbone.decoder.3.conv_block.convs.1.bn.bias, backbone.decoder.3.conv_block.convs.1.bn.running_mean, backbone.decoder.3.conv_block.convs.1.bn.running_var, backbone.decoder.3.conv_block.convs.1.bn.num_batches_tracked, backbone.decoder.3.upsample.interp_upsample.1.conv.weight, backbone.decoder.3.upsample.interp_upsample.1.bn.weight, backbone.decoder.3.upsample.interp_upsample.1.bn.bias, backbone.decoder.3.upsample.interp_upsample.1.bn.running_mean, backbone.decoder.3.upsample.interp_upsample.1.bn.running_var, backbone.decoder.3.upsample.interp_upsample.1.bn.num_batches_tracked, decode_head.conv_seg.weight, decode_head.conv_seg.bias, decode_head.convs.0.conv.weight, decode_head.convs.0.bn.weight, decode_head.convs.0.bn.bias, decode_head.convs.0.bn.running_mean, decode_head.convs.0.bn.running_var, decode_head.convs.0.bn.num_batches_tracked, auxiliary_head.conv_seg.weight, auxiliary_head.conv_seg.bias, auxiliary_head.convs.0.conv.weight, auxiliary_head.convs.0.bn.weight, auxiliary_head.convs.0.bn.bias, auxiliary_head.convs.0.bn.running_mean, auxiliary_head.convs.0.bn.running_var, auxiliary_head.convs.0.bn.num_batches_tracked

**missing keys in source state_dict:** encoder.0.0.convs.0.conv.weight, encoder.0.0.convs.0.bn.weight, encoder.0.0.convs.0.bn.bias, encoder.0.0.convs.0.bn.running_mean, encoder.0.0.convs.0.bn.running_var, encoder.0.0.convs.1.conv.weight, encoder.0.0.convs.1.bn.weight, encoder.0.0.convs.1.bn.bias, encoder.0.0.convs.1.bn.running_mean, encoder.0.0.convs.1.bn.running_var, encoder.1.1.convs.0.conv.weight, encoder.1.1.convs.0.bn.weight, encoder.1.1.convs.0.bn.bias, encoder.1.1.convs.0.bn.running_mean, encoder.1.1.convs.0.bn.running_var, encoder.1.1.convs.1.conv.weight, encoder.1.1.convs.1.bn.weight, encoder.1.1.convs.1.bn.bias, encoder.1.1.convs.1.bn.running_mean, encoder.1.1.convs.1.bn.running_var, encoder.2.1.convs.0.conv.weight, encoder.2.1.convs.0.bn.weight, encoder.2.1.convs.0.bn.bias, encoder.2.1.convs.0.bn.running_mean, encoder.2.1.convs.0.bn.running_var, encoder.2.1.convs.1.conv.weight, encoder.2.1.convs.1.bn.weight, encoder.2.1.convs.1.bn.bias, encoder.2.1.convs.1.bn.running_mean, encoder.2.1.convs.1.bn.running_var, encoder.3.1.convs.0.conv.weight, encoder.3.1.convs.0.bn.weight, encoder.3.1.convs.0.bn.bias, encoder.3.1.convs.0.bn.running_mean, encoder.3.1.convs.0.bn.running_var, encoder.3.1.convs.1.conv.weight, encoder.3.1.convs.1.bn.weight, encoder.3.1.convs.1.bn.bias, encoder.3.1.convs.1.bn.running_mean, encoder.3.1.convs.1.bn.running_var, encoder.4.1.convs.0.conv.weight, encoder.4.1.convs.0.bn.weight, encoder.4.1.convs.0.bn.bias, encoder.4.1.convs.0.bn.running_mean, encoder.4.1.convs.0.bn.running_var, encoder.4.1.convs.1.conv.weight, encoder.4.1.convs.1.bn.weight, encoder.4.1.convs.1.bn.bias, encoder.4.1.convs.1.bn.running_mean, encoder.4.1.convs.1.bn.running_var, decoder.0.conv_block.convs.0.conv.weight, decoder.0.conv_block.convs.0.bn.weight, decoder.0.conv_block.convs.0.bn.bias, decoder.0.conv_block.convs.0.bn.running_mean, decoder.0.conv_block.convs.0.bn.running_var, decoder.0.conv_block.convs.1.conv.weight, decoder.0.conv_block.convs.1.bn.weight, decoder.0.conv_block.convs.1.bn.bias, decoder.0.conv_block.convs.1.bn.running_mean, decoder.0.conv_block.convs.1.bn.running_var, decoder.0.upsample.interp_upsample.1.conv.weight, decoder.0.upsample.interp_upsample.1.bn.weight, decoder.0.upsample.interp_upsample.1.bn.bias, decoder.0.upsample.interp_upsample.1.bn.running_mean, decoder.0.upsample.interp_upsample.1.bn.running_var, decoder.1.conv_block.convs.0.conv.weight, decoder.1.conv_block.convs.0.bn.weight, decoder.1.conv_block.convs.0.bn.bias, decoder.1.conv_block.convs.0.bn.running_mean, decoder.1.conv_block.convs.0.bn.running_var, decoder.1.conv_block.convs.1.conv.weight, decoder.1.conv_block.convs.1.bn.weight, decoder.1.conv_block.convs.1.bn.bias, decoder.1.conv_block.convs.1.bn.running_mean, decoder.1.conv_block.convs.1.bn.running_var, decoder.1.upsample.interp_upsample.1.conv.weight, decoder.1.upsample.interp_upsample.1.bn.weight, decoder.1.upsample.interp_upsample.1.bn.bias, decoder.1.upsample.interp_upsample.1.bn.running_mean, decoder.1.upsample.interp_upsample.1.bn.running_var, decoder.2.conv_block.convs.0.conv.weight, decoder.2.conv_block.convs.0.bn.weight, decoder.2.conv_block.convs.0.bn.bias, decoder.2.conv_block.convs.0.bn.running_mean, decoder.2.conv_block.convs.0.bn.running_var, decoder.2.conv_block.convs.1.conv.weight, decoder.2.conv_block.convs.1.bn.weight, decoder.2.conv_block.convs.1.bn.bias, decoder.2.conv_block.convs.1.bn.running_mean, decoder.2.conv_block.convs.1.bn.running_var, decoder.2.upsample.interp_upsample.1.conv.weight, decoder.2.upsample.interp_upsample.1.bn.weight, decoder.2.upsample.interp_upsample.1.bn.bias, decoder.2.upsample.interp_upsample.1.bn.running_mean, decoder.2.upsample.interp_upsample.1.bn.running_var, decoder.3.conv_block.convs.0.conv.weight, decoder.3.conv_block.convs.0.bn.weight, decoder.3.conv_block.convs.0.bn.bias, decoder.3.conv_block.convs.0.bn.running_mean, decoder.3.conv_block.convs.0.bn.running_var, decoder.3.conv_block.convs.1.conv.weight, decoder.3.conv_block.convs.1.bn.weight, decoder.3.conv_block.convs.1.bn.bias, decoder.3.conv_block.convs.1.bn.running_mean, decoder.3.conv_block.convs.1.bn.running_var, decoder.3.upsample.interp_upsample.1.conv.weight, decoder.3.upsample.interp_upsample.1.bn.weight, decoder.3.upsample.interp_upsample.1.bn.bias, decoder.3.upsample.interp_upsample.1.bn.running_mean, decoder.3.upsample.interp_upsample.1.bn.running_var

**Comment by HobbitArmy** [comment]
Hi bro,  met the same problem. follow the bugs, i found in mmengine/model/base_module.py Line-52, that mm2 do not support "pretrained" in model cfg now,
while the good method is use:
`init_cfg = dict(type='Pretrained', checkpoint=pretrained)`

`SOURCE CODE MENTION:
        # Backward compatibility in derived classes
        # if pretrained is not None:
        #     warnings.warn('DeprecationWarning: pretrained is a deprecated \
        #         key, please consider using init_cfg')
        #     self.init_cfg = dict(type='Pretrained', checkpoint=pretrained)
`

**Comment by AnRanbel** [comment]
> Hi bro,  met the same problem. follow the bugs, i found in mmengine/model/base_module.py Line-52, that mm2 do not support "pretrained" in model cfg now,
> while the good method is use:
> `init_cfg = dict(type='Pretrained', checkpoint=pretrained)`
> 
> `SOURCE CODE MENTION:
>         # Backward compatibility in derived classes
>         # if pretrained is not None:
>         #     warnings.warn('DeprecationWarning: pretrained is a deprecated \
>         #         key, please consider using init_cfg')
>         #     self.init_cfg = dict(type='Pretrained', checkpoint=pretrained)
> `
> 

thank you!
