### ISSUE TITLE
MMSegmentation vs MMDetection

### ISSUE THREAD

**Issue by GeorgePearse** [open-mmlab/mmsegmentation#3252]
I'm a little confused by this repo, a few segmentation models are available in MMDetection (at least maskrcnn anyway, which MMSegmentation does not contain), but am I better off using this?

Is there a problem that MaskRCNN can't address which this repo is designed for? 

Is this repo for Semantic Segmentation only, while MaskRCNN address Panoptic Segmentation

**Comment by xiexinch** [comment]
Hi @GeorgePearse,
MMSegmentation only supports semantic segmentation and MMDetection supports object detection, instance segmentation, and panoptic segmentation.
