### ISSUE TITLE
mmcv 版本报错

### ISSUE THREAD

**Issue by pawn0414** [open-mmlab/mmsegmentation#3255]
按照教程安装了mmcv2.0.0.rc4
运行下面代码提示安装
python demo/image_demo.py demo/demo.png configs/pspnet/pspnet_r50-d8_4xb2-40k_cityscapes-512x1024.py pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth --device cuda:0 --out-file result.jpg
报错AssertionError: MMCV==2.0.0rc4 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.
安装mmcv 1.7.0再次运行
报错AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4.
环境
OrderedDict([('sys.platform', 'linux'), ('Python', '3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'NVIDIA GeForce RTX 3090 Ti'), ('CUDA_HOME', '/usr'), ('NVCC', 'Cuda compilation tools, release 10.1, V10.1.24'), ('GCC', 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0'), ('PyTorch', '1.11.0+cu113'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.2\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.12.0+cu113'), ('OpenCV', '4.8.0'), ('MMEngine', '0.8.4'), ('MMCV', '2.0.0rc4'), ('MMCV Compiler', 'GCC 9.3'), ('MMCV CUDA Compiler', '11.3')])

**Comment by xiexinch** [comment]
Hi @pawn0414,
请问你用的是哪个版本的 mmseg 呢?

**Comment by pawn0414** [comment]
> Hi @pawn0414, 请问你用的是哪个版本的 mmseg 呢？ 可以按照官方文档 https://mmsegmentation.readthedocs.io/zh_CN/latest/get_started.html 安装 mmseg.

就是才参考的官方文档版本,mmseg 版本1.1.1

**Comment by pawn0414** [comment]
> Hi @pawn0414, 请问你用的是哪个版本的 mmseg 呢？ 可以按照官方文档 https://mmsegmentation.readthedocs.io/zh_CN/latest/get_started.html 安装 mmseg.

mmcv                          2.0.0rc4
mmdet                         2.28.1
mmengine                      0.8.4
mmsegmentation                1.1.1        /home/u/mmsegmentation

**Comment by xiexinch** [comment]
为什么要安装 mmdet 2.28.1 呢

**Comment by pawn0414** [comment]
24

**Comment by xiexinch** [comment]
mmdet 2.x 版本和 mmcv 2.x 版本不兼容，所以会报错

**Comment by pawn0414** [comment]
> 为什么要安装 mmdet 2.28.1 呢

请问需要下载多少版本

**Comment by xiexinch** [comment]
只有需要用到 MaskFormer 和 Mask2Former 的时候才需要安装 mmdet 3.0.0rc5以上的mmdet版本，否则不需要安装 mmdet

**Comment by pawn0414** [comment]
之前的问题解决了，还有请问我在运行
https://github.com/OpenGVLab/InternImage中的

python test.py configs/ade20k/upernet_internimage_t_512_160k_ade20k.py checkpoint_dir/seg/upernet_internimage_t_512_160k_ade20k.pth --eval mIoU
时
报错No module named 'mmcv.parallel'
import mmcv是没有问题的，这是什么问题

**Comment by xiexinch** [comment]
https://github.com/OpenGVLab/InternImage 这个项目使用的是旧版本 mmseg 和 mmcv，即0.x版本的mmseg和1.x版本的mmcv，对应的接口和新版本有很大的冲突，请按照他们的安装文档安装对应的依赖库。 https://github.com/OpenGVLab/InternImage/tree/master/segmentation

**Comment by pawn0414** [comment]
请问能找到早期版本的对应关系吗，您提供的文件mmcv版本都在2以上https://mmsegmentation.readthedocs.io/zh_CN/latest/notes/faq.html#id1

**Comment by xiexinch** [comment]
https://mmsegmentation.readthedocs.io/en/0.x/faq.html

**Comment by pawn0414** [comment]
我知道了，我是因为查看了https://github.com/OpenGVLab/InternImage中的这一句话安装了mmdet==2.28.1
pip install -U openmim
mim install mmcv-full==1.5.0
pip install timm==0.6.11 mmdet==2.28.1
也就是说在这个项目中我需要mmdet==2.28.1 and 0开头的mmsegmentation 是这样吗
