### ISSUE TITLE
I want to introduce multi-labels such as edge labels to supervise the increased edge branch training. How can I achieve it through mmseg

### ISSUE THREAD

**Issue by HiDay1** [open-mmlab/mmsegmentation#326]
A picture corresponds to a semantic label and edge label.
How can I  introduce another label  to Construct a  new loss function?

**Comment by Junjun2016** [comment]
Hi @HiDay1
Refer to the reimplementation of [DecoupleSegNet](https://github.com/Junjun2016/mmsegmentation/tree/dsn).
