### ISSUE TITLE
Is MAE result in this repo reproducible? I only get 47.5.

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmsegmentation#3262]

**Comment by xiexinch** [comment]
[20230817_123954.json.txt](https://github.com/open-mmlab/mmsegmentation/files/12391479/20230817_123954.json.txt)

There will be small fluctuations in training results, but the result is reproducible.

**Comment by carlosh93** [comment]
> [20230817_123954.json.txt](https://github.com/open-mmlab/mmsegmentation/files/12391479/20230817_123954.json.txt)
> 
> There will be small fluctuations in training results, but the result is reproducible.

Hi, could you please share your exact config and the number of GPUs you used? Also, batch_size, type of GPU, etc? I can not reproduce the results
