### ISSUE TITLE
当我按照EpochBasedTrainLoop训练时，我的数据集里的训练集只有8张图，train_dataloader按如下设置，为什么会显示一轮的迭代次数是408呢，难道不应该是8吗

### ISSUE THREAD

**Issue by dys-master** [open-mmlab/mmsegmentation#3265]
![image](https://github.com/open-mmlab/mmsegmentation/assets/57054682/6641a035-6aa0-4425-84dd-915dc42da15e)
train_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='img_dir/train', seg_map_path='ann_dir/train'),
        pipeline=train_pipeline))

**Comment by chenslcool** [comment]
请问怎么解决的？
