### ISSUE TITLE
High cpu usage on High-level API for testing images

### ISSUE THREAD

**Issue by YLyeliang** [open-mmlab/mmsegmentation#328]
When using the example code `High-level APIs for testing images` given by the `getting_started.md` . I used the api 'inference_segmentor`, the other part of the code is normal reading files, and a for loop to inference the image.
something like below
```python
# model config, init
...
model = init_segmentor(xx)

imgs =mmcv.scandir(img_path)

for img in imgs:
    ... # process img abs path.
    result = inference_segmentor(model,img)
```
I found that my cpu usage is very high, by top command on linux, it can reach 3800%( we have 72 cores), almost every core have usage of nearly 100%. That is very strange. 
The config file is deeplabv3_m-v2-d8_512x512_160k_ade20k.py.  
Tried many methods, commented some codes. Still didn't know why. May someone solves my confusion.

**Comment by xvjiarui** [comment]
Hi @YLyeliang 
There should be no CPU intense operators at this stage. Could you reproduce it with a simple script? We may take a look.

**Comment by YLyeliang** [comment]
Hi @xvjiarui 
version:
with latest mmsegmentation, and mmcv_full 1.1.6 cu101, pytorch 1.5.0. rtx 2080ti. 

note: When the problem happened, I didn't do any model inference, which means that the model(xx,**data) has commented.
script:
```python
from mmseg.apis import inference_segmentor, init_segmentor
import mmcv
import os
config_file = 'configs/mobilenet_v2/deeplabv3_m-v2-d8_512x512_160k_ade20k.py'
checkpoint_file = 'pretrained ckpt.pth'

# build the model from a config file and a checkpoint file
model = init_segmentor(config_file, checkpoint_file, device='cuda:0')

img_dir = "xxx"
files = mmcv.scandir(img_dir)
for file in files:
    img = os.path.join(img_dir,file)
    # test a single image and show the results
    result = inference_segmentor(model, img)
```
Above is the script. The first time I met this problem is not with this script. However, it still reproduces this problem with above scirpt.

Tried debugs:
in the `mmseg/apis/inference.py`. When I comment the line `data=collate([data],samples_pergpu=1)` in function `inference_segmentor(model,img)`

1. Resize function
first debug: I canceled the Resize in the test pipeline, and cpu usage has down about 1/2.
So I think it's the reason cv2.resize, I changed the backend to pillow, and the cpu usage has down 1/2.
All these process only refer to reading data, without model inference and collate.
```python
def inference_segmentor(model, img):
    """Inference image(s) with the segmentor.

    Args:
        model (nn.Module): The loaded segmentor.
        imgs (str/ndarray or list[str/ndarray]): Either image files or loaded
            images.

    Returns:
        (list[Tensor]): The segmentation result.
    """
    cfg = model.cfg
    device = next(model.parameters()).device  # model device
    # build the data pipeline

    test_pipeline = [LoadImage()] + cfg.data.test.pipeline[1:]
    test_pipeline = Compose(test_pipeline)
    # prepare data
    data = dict(img=img)
    data = test_pipeline(data)
    #data = collate([data], samples_per_gpu=1)
    if next(model.parameters()).is_cuda:
        # scatter to specified GPU
        data = scatter(data, [device])[0]
    else:
        data['img_metas'] = data['img_metas'][0].data

    # forward the model
    # I comment below code, for just reading data iteratively.
    # with torch.no_grad():
    #    result = model(return_loss=False, rescale=True, **data)
    result = None
    return result
```

2. collate function
After I comment the collate function, the cpu usage immediately down from 3900% to abought 300%.
```python
def inference_segmentor(model, img):
    """Inference image(s) with the segmentor.

    Args:
        model (nn.Module): The loaded segmentor.
        imgs (str/ndarray or list[str/ndarray]): Either image files or loaded
            images.

    Returns:
        (list[Tensor]): The segmentation result.
    """
    cfg = model.cfg
    device = next(model.parameters()).device  # model device
    # build the data pipeline

    test_pipeline = [LoadImage()] + cfg.data.test.pipeline[1:]
    test_pipeline = Compose(test_pipeline)
    # prepare data
    data = dict(img=img)
    data = test_pipeline(data)
    # 2. after I comment below code, the cpu usage down from 3900% to nearly 300%.
    data = collate([data], samples_per_gpu=1)
    if next(model.parameters()).is_cuda:
        # scatter to specified GPU
        data = scatter(data, [device])[0]
    else:
        data['img_metas'] = data['img_metas'][0].data

    # forward the model
    # I comment below code, for just reading data iteratively.
    # with torch.no_grad():
    #    result = model(return_loss=False, rescale=True, **data)
    result = None
    return result
```
Note:
By using mmdetection, with the same reading data process of high-level api test. cpu usages is only 100%.  
With pycharm Ide debugger, I watched the data content of both two data, which is the same.
Didn't know why.

Thanks for help.

**Comment by YLyeliang** [comment]
@xvjiarui 
By the way, with `tools/train.py`， the cpu usage is normal.

**Comment by YLyeliang** [comment]
Finally, I resolved this problem by adding the function `torch.set_num_threads(1)`  after initializing the model. Still don't know why the cpu usage can achieve 4000%. However, this is resolved.
