### ISSUE TITLE
 [Potential Bug] FAIL : Load model from end2end.onnx failed:Fatal error: mmdeploy:grid_sampler(-1) is not a registered function/op

### ISSUE THREAD

**Issue by hasanirtiza** [open-mmlab/mmsegmentation#3290]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched it on mmdeploy as well. Could not find a work around.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I am trying to convert mmsegmentation model mask2former (mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth ). I have successfully converted previously certain models, so my installation etc seems fine. The command I am running is the following

python3 tools/deploy.py   configs/mmseg//segmentation_onnxruntime_static-512x512.py   ../mmsegmentation/configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py   ../mmsegmentation/checkpoints/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth   ../mmsegmentation/demo_images/a2.png   --work-dir ./work_dirs/mmseg-onnx   --device cpu   --dump-info

It works just fine, I get the end2end.onnx model and the converted demo images of pytorch and onnx appear perfect. However when I try to load this model in onnxruntime I get the following error

" FAIL : Load model from end2end_semantic.onnx failed:Fatal error: mmdeploy:grid_sampler(-1) is not a registered function/op"

My onnxruntime version is 1.8.1
and I saw some bits which were not helpful in this previous version documentation.
https://mmcv.readthedocs.io/en/v1.3.10/deployment/onnxruntime_op.html

**Reproduction**

1. What command or script did you run?

`python3 tools/deploy.py   configs/mmseg//segmentation_onnxruntime_static-512x512.py   ../mmsegmentation/configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py   ../mmsegmentation/checkpoints/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth   ../mmsegmentation/demo_images/a2.png   --work-dir ./work_dirs/mmseg-onnx   --device cpu   --dump-info`

3. Did you make any modifications on the code or config? Did you understand what you have modified?
None

4. What dataset did you use?

**Environment**

08/25 13:48:03 - mmengine - INFO - TorchVision: 0.15.2+cu117
08/25 13:48:03 - mmengine - INFO - OpenCV: 4.8.0
08/25 13:48:03 - mmengine - INFO - MMEngine: 0.8.4
08/25 13:48:03 - mmengine - INFO - MMCV: 2.0.1
08/25 13:48:03 - mmengine - INFO - MMCV Compiler: GCC 9.3
08/25 13:48:03 - mmengine - INFO - MMCV CUDA Compiler: 11.7
08/25 13:48:03 - mmengine - INFO - MMDeploy: 1.0.0rc3+a7e9be2
08/25 13:48:03 - mmengine - INFO -

08/25 13:48:03 - mmengine - INFO - **********Backend information**********
08/25 13:48:03 - mmengine - INFO - tensorrt:    None
08/25 13:48:03 - mmengine - INFO - ONNXRuntime: 1.8.1
08/25 13:48:03 - mmengine - INFO - ONNXRuntime-gpu:     None
08/25 13:48:03 - mmengine - INFO - ONNXRuntime custom ops:      Available
08/25 13:48:03 - mmengine - INFO - pplnn:       None
08/25 13:48:03 - mmengine - INFO - ncnn:        None
08/25 13:48:03 - mmengine - INFO - snpe:        None
08/25 13:48:03 - mmengine - INFO - openvino:    None
08/25 13:48:03 - mmengine - INFO - torchscript: 2.0.1
08/25 13:48:03 - mmengine - INFO - torchscript custom ops:      NotAvailable
08/25 13:48:04 - mmengine - INFO - rknn-toolkit:        None
08/25 13:48:04 - mmengine - INFO - rknn-toolkit2:       None
08/25 13:48:04 - mmengine - INFO - ascend:      None
08/25 13:48:04 - mmengine - INFO - coreml:      None
08/25 13:48:04 - mmengine - INFO - tvm: None
08/25 13:48:04 - mmengine - INFO -

08/25 13:48:04 - mmengine - INFO - **********Codebase information**********
08/25 13:48:04 - mmengine - INFO - mmdet:       3.1.0
08/25 13:48:04 - mmengine - INFO - mmseg:       1.1.1
08/25 13:48:04 - mmengine - INFO - mmcls:       None
08/25 13:48:04 - mmengine - INFO - mmocr:       None
08/25 13:48:04 - mmengine - INFO - mmedit:      None
08/25 13:48:04 - mmengine - INFO - mmdet3d:     None
08/25 13:48:04 - mmengine - INFO - mmpose:      None
08/25 13:48:04 - mmengine - INFO - mmrotate:    None
08/25 13:48:04 - mmengine - INFO - mmaction:    None

**Comment by hasanirtiza** [comment]
As told by the moderators on [mmdeploy](https://github.com/open-mmlab/mmdeploy/issues/2377): 

path = "./site-packages/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so"
model_path = "end2end-mask2former.onnx"
session_options = ort.SessionOptions()
session_options.register_custom_ops_library(path)
ort_session = ort.InferenceSession(model_path,session_options)`

**Comment by guojingsai** [comment]
> As told by the moderators on [mmdeploy](https://github.com/open-mmlab/mmdeploy/issues/2377):
> 
> path = "./site-packages/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so" model_path = "end2end-mask2former.onnx" session_options = ort.SessionOptions() session_options.register_custom_ops_library(path) ort_session = ort.InferenceSession(model_path,session_options)`

Thank you for your suggestion. I have followed your prompts to run through the program, but the Inference speed is too slow.Do you have similar questions?

**Comment by hasanirtiza** [comment]
@guojingsai In general say mask2former is a heavy model, so one would expect it to be somewhat slow. But, I did not notice a significant delay. What is your average time per image and what is the image resolution.
