### ISSUE TITLE
can not use pretrained unet

### ISSUE THREAD

**Issue by JoyLuo** [open-mmlab/mmsegmentation#333]
Can not use pretrained unet because the layer name is different between the net and pretrained model
layer name of net is  encoder.0.0.convs.0.conv.weight
layer name of pretrained is backbone.encoder.0.0.convs.0.conv.weight

**Comment by Junjun2016** [comment]
Hi @JoyLuo 
We have not provided  pretrained UNet (backbone),  we provided the checkpoints of backbone (UNet) + decode_head (FCN, DeeplabV3, and PSPNet).

**Comment by JoyLuo** [comment]
The value of pretrained in config is used in backbone, not the total model
when i use the pretrained unet, i need to use the load-from in tools/train.py

this is the config of unet
model = dict(
    type='EncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='UNet',
        in_channels=3,
        base_channels=64,
        num_stages=5,
        strides=(1, 1, 1, 1, 1),
        enc_num_convs=(2, 2, 2, 2, 2),
        dec_num_convs=(2, 2, 2, 2),
        downsamples=(True, True, True, True),
        enc_dilations=(1, 1, 1, 1, 1),
        dec_dilations=(1, 1, 1, 1),
        with_cp=False,
        conv_cfg=None,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='ReLU'),
        upsample_cfg=dict(type='InterpConv'),
        norm_eval=False),
    decode_head=dict(
        type='FCNHead',
        in_channels=64,
        in_index=4,
        channels=64,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))
)

**Comment by JoyLuo** [comment]
> Hi @JoyLuo
> We have not provided pretrained UNet (backbone), we provided the checkpoints of backbone (UNet) + decode_head (FCN, DeeplabV3, and PSPNet).

The value of pretrained in config is used in backbone, not the total model
when i use the pretrained unet, i need to use the load-from in tools/train.py

this is the config of unet
model = dict(
type='EncoderDecoder',
pretrained=None,
backbone=dict(
type='UNet',
in_channels=3,
base_channels=64,
num_stages=5,
strides=(1, 1, 1, 1, 1),
enc_num_convs=(2, 2, 2, 2, 2),
dec_num_convs=(2, 2, 2, 2),
downsamples=(True, True, True, True),
enc_dilations=(1, 1, 1, 1, 1),
dec_dilations=(1, 1, 1, 1),
with_cp=False,
conv_cfg=None,
norm_cfg=norm_cfg,
act_cfg=dict(type='ReLU'),
upsample_cfg=dict(type='InterpConv'),
norm_eval=False),
decode_head=dict(
type='FCNHead',
in_channels=64,
in_index=4,
channels=64,
num_convs=1,
concat_input=False,
dropout_ratio=0.1,
num_classes=2,
norm_cfg=norm_cfg,
align_corners=False,
loss_decode=dict(
type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))
)

**Comment by Junjun2016** [comment]
> > Hi @JoyLuo
> > We have not provided pretrained UNet (backbone), we provided the checkpoints of backbone (UNet) + decode_head (FCN, DeeplabV3, and PSPNet).
> 
> The value of pretrained in config is used in backbone, not the total model
> when i use the pretrained unet, i need to use the load-from in tools/train.py
> 
> this is the config of unet
> model = dict(
> type='EncoderDecoder',
> pretrained=None,
> backbone=dict(
> type='UNet',
> in_channels=3,
> base_channels=64,
> num_stages=5,
> strides=(1, 1, 1, 1, 1),
> enc_num_convs=(2, 2, 2, 2, 2),
> dec_num_convs=(2, 2, 2, 2),
> downsamples=(True, True, True, True),
> enc_dilations=(1, 1, 1, 1, 1),
> dec_dilations=(1, 1, 1, 1),
> with_cp=False,
> conv_cfg=None,
> norm_cfg=norm_cfg,
> act_cfg=dict(type='ReLU'),
> upsample_cfg=dict(type='InterpConv'),
> norm_eval=False),
> decode_head=dict(
> type='FCNHead',
> in_channels=64,
> in_index=4,
> channels=64,
> num_convs=1,
> concat_input=False,
> dropout_ratio=0.1,
> num_classes=2,
> norm_cfg=norm_cfg,
> align_corners=False,
> loss_decode=dict(
> type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))
> )

Yes, or use load_from in config.

**Comment by rubeea** [comment]
@JoyLuo Can you specify that you used which pretrained U-Net for your model training? Thanks

**Comment by JoyLuo** [comment]
> @JoyLuo Can you specify that you used which pretrained U-Net for your model training? Thanks

@rubeea i use deeplabv3_unet_s5-d16_256x256_40k_hrf_20201226_094047-3a1fdf85.pth， unet with aspp is better than unet only
