### ISSUE TITLE
[Errno 2] No such file or directory: 'iter_4000.pth'

### ISSUE THREAD

**Issue by PiPiJ** [open-mmlab/mmsegmentation#335]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.

right

2. The bug has not been fixed in the latest version.

**Describe the bug**
When I use mmsegmentation to deeplabvsp on ade20k on windows,I miss a problem after first 4000 iters for training finishing and next  iter for validation,error says ‘No such file or directory: 'iter_4000.pth'，but I check the file path,there exactly is the file 'iter_4000.pth'.

**Reproduction**

1. What command or script did you run?

 python tools/train.py config configs\deeplabv3plus\deeplabv3plus_r50-d8_512x512_4k_ade20k.py --work-dir checkpoints/deeplabv3plus\deeplabv3plus_r50-d8_512x512_4k_ade20k

2. Did you make any modifications on the code or config? Did you understand what you have modified?

no

3. What dataset did you use?

ade20k

**Environment**

sys.platform: win32
Python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
NVCC: Not Available
GCC: n/a
PyTorch: 1.7.0+cu110
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192729112
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.4
  - Magma 2.5.3
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.8.1+cu110
OpenCV: 4.4.0
MMCV: 1.2.0
MMCV Compiler: MSVC 191627045
MMCV CUDA Compiler: 11.0
MMSegmentation: 0.10.0+
'tail' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
fatal: not a git repository (or any of the parent directories): .git

**Error traceback**

[Errno 2] No such file or directory: 'iter_4000.pth'
  File "D:\mmcv-1.2.0\mmcv\runner\iter_based_runner.py", line 215, in save_checkpoint
    shutil.copy(filename, dst_file)
  File "D:\mmcv-1.2.0\mmcv\runner\hooks\checkpoint.py", line 62, in _save_checkpoint
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "D:\mmcv-1.2.0\mmcv\runner\dist_utils.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "D:\mmcv-1.2.0\mmcv\runner\hooks\checkpoint.py", line 101, in after_train_iter
    self._save_checkpoint(runner)
  File "D:\mmcv-1.2.0\mmcv\runner\base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "D:\mmcv-1.2.0\mmcv\runner\iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "D:\mmcv-1.2.0\mmcv\runner\iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\mmsegmentation\mmseg\apis\train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "D:\mmsegmentation\tools\train.py", line 176, in main
    meta=meta)
  File "D:\mmsegmentation\tools\train.py", line 180, in <module>
    main()

**Bug fix**

When I use the same version pytorch,mmcv and mmseg in ubuntu20.04 ,I do not counter this bug,but why this error come to win10 ?

**Comment by PiPiJ** [comment]
oh ,i solve it by changging codes in mmcv.runner.hook..checkpoint.py ! It's an bug in mmcv for windows10!

**Comment by xvjiarui** [comment]
Hi @PiPiJ 
Could you please describe the bug in more details? Or would you mind make a PR in mmcv to fix it?

**Comment by SUNK000000** [comment]
Hi @PiPiJ
Could you please describe your solution for this bug,thanks very much.

**Comment by SUNK000000** [comment]
> oh ,i solve it by changging codes in mmcv.runner.hook..checkpoint.py ! It's an bug in mmcv for windows10!

i met the same question,could you help me?

**Comment by xiaweiguang** [comment]
>hello
I also encountered the same problem. Have you solved it？
