### ISSUE TITLE
CE loss RuntimeError: CUDA error: an illegal memory access was encountered for cocostuff dataset

### ISSUE THREAD

**Issue by sipie800** [open-mmlab/mmsegmentation#3358]
I try to train segformer with cocostuff.
There are 171 classes. And many 255 label for ignore.
Use the build-in dataset_type. 

batch size 8, train crop size 512^2. RTX4090. Win10. torch 2.0.1 cuda118
error:

\models\losses\cross_entropy_loss.py", line 47, in cross_entropy
    loss = F.cross_entropy(
  File "D:\yc\python310\lib\site-packages\torch\nn\functional.py", line 3031, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Checked that mmseg impl dose ignore 255 here. So it's not due to ignore index:
    loss = F.cross_entropy(
        pred, #8 171 512 512
        label, # 8 512 512
        weight=class_weight,
        reduction='none',
        ignore_index=ignore_index) # 255 passed

This issue does raise a lot of report and it seems that many fixing has been disucssed. However it's not fixed really.
It's believed that it actually is a memory issue. OOM is not happening. With batch size 8, the training memory is not more than 8GB. 
N,171,512,512 prediction for CE is kind of large. Reducing batch size to 1 does not work. It's still too large.
Reducing crop size to 128^2 does fix it. But that's wrong because small crop lead to bad training.

So it may require a fix for 8,171,512,512 input at least. Other trick won't fix the issue for CocoStuff.

**Comment by sipie800** [comment]
The issue might be caused by an error in doc. 
The COCOStuffDataset says there are 171 classes for both 10k and 164k. So I set model num_classes to 171.
After too much debug trying in vain, I check the downloaded coco official 164k data seg maps.
The max ID is 181 !!!

**Comment by xiexinch** [comment]
Hi @sipie800,
The number of classes is exactly 171, see the official repo: https://github.com/nightrome/cocostuff#highlights
Please follow our documentation to preprocess the downloaded data.
https://mmsegmentation.readthedocs.io/en/latest/user_guides/2_dataset_prepare.html#coco-stuff-164k
https://github.com/open-mmlab/mmsegmentation/blob/main/tools/dataset_converters/coco_stuff164k.py
