### ISSUE TITLE
Results of Deeplab-v2

### ISSUE THREAD

**Issue by wqtwjt1996** [open-mmlab/mmsegmentation#338]
# Deeplab-v2 pretrained results and models?

**Motivation**
In semi-supervised learning for semantic segmentation, Deeplab-v2 is widely used.
1.  https://arxiv.org/pdf/1908.05724v1.pdf
2. https://arxiv.org/pdf/2007.07936.pdf

So is it possible to provide some results and pretrained models with Deeplab-v2 in Cityscapes and VOC-12 datasets?

**Comment by Junjun2016** [comment]
> # Deeplab-v2 pretrained results and models?
> **Motivation**
> In semi-supervised learning for semantic segmentation, Deeplab-v2 is widely used.
> 
> 1. https://arxiv.org/pdf/1908.05724v1.pdf
> 2. https://arxiv.org/pdf/2007.07936.pdf
> 
> So is it possible to provide some results and pretrained models with Deeplab-v2 in Cityscapes and VOC-12 datasets?

Maybe you can use DeepLabV3 and DeepLabV3+, or you can train it by yourself through registering a DeepLabV2 decode_head.
