### ISSUE TITLE
No such file  mmseg/utils/bpe_simple_vocab_16e6.txt.gz

### ISSUE THREAD

**Issue by acdart** [open-mmlab/mmsegmentation#3383]
**Describe the bug**

![128191697364505_ pic](https://github.com/open-mmlab/mmsegmentation/assets/17796156/ac9f0dc8-ddda-41fe-ad25-466fafa0166f)

**Comment by xiexinch** [comment]
Hi @acdart,
Thanks for your bug report, we'll find a solution soon.

**Comment by xiexinch** [comment]
[mmsegmentation-1.2.0.tar.gz](https://github.com/open-mmlab/mmsegmentation/files/12911627/mmsegmentation-1.2.0.tar.gz)

A temporary solution:
```shell
pip install mmsegmentation-1.2.0.tar.gz
```

We'll release v1.2.1 to solve this problem. If there are any other bugs, please report them to us, we really appreciate it!

**Comment by andresinsitu** [comment]
i got the same error

**Comment by lxtGH** [comment]
Updating mmseg to v1.2.1 can solve this problem.
