### ISSUE TITLE
'EncoderDecoder is not in the mmengine::model registry.'

### ISSUE THREAD

**Issue by Sere1nz** [open-mmlab/mmsegmentation#3395]
![image](https://github.com/open-mmlab/mmsegmentation/assets/32921181/17f1c28c-903d-47ad-946f-0d7874d4e40d)

However, EncoderDecoder is a official model type.

**Comment by Sere1nz** [comment]
![image](https://github.com/open-mmlab/mmsegmentation/assets/32921181/0a42d27f-c455-480b-b4a8-e4b0ce7a6f44)

**Comment by yovyo0099** [comment]
same question

**Comment by nitec427** [comment]
I have the same problem nowadays, I try to install all of the possible scenarios that was proposed in the official docs, but it failed in every way. Is there someone who solved the problem.

**Comment by saikatdutta** [comment]
I am also facing the same issue.

**Comment by kingstarcraft** [comment]
I solve this problem by adding default_scope = 'mmseg' to my custom config.py file

**Comment by marino137** [comment]
> I solve this problem by adding default_scope = 'mmseg' to my custom config.py file

thanks,buddy
