### ISSUE TITLE
Testing after every epoch during training

### ISSUE THREAD

**Issue by anirbala98** [open-mmlab/mmsegmentation#3419]
Hi,

I can see that there is a script at tools/test.py for testing the trained models. Instead of doing the test separately, is it possible to integrate the testing during the training process itself (something like running the test after every epoch along with validation)?

**Comment by chenslcool** [comment]
hi, how did you solve it?

**Comment by anirbala98** [comment]
Hi,

I added few lines of code to loops.py and runner.py files in the mmengine/runner folder. 
I made the following changes to the corresponding files:

a) mmengine/runner/loops.py

I added the highlighted line to the run() function

<img width="430" alt="loops py" src="https://github.com/open-mmlab/mmsegmentation/assets/26120836/e448599b-05ac-4e39-9f1f-15928ba719f6">

b) mmengine/runner/runner..py

I added the following lines to the train() function.

```
if self._test_loop is not None:
            self._test_loop = self.build_test_loop(self._test_loop)
```
