### ISSUE TITLE
where can I get the pretrained model : resnet50_v1c and resnet101_v1c

### ISSUE THREAD

**Issue by tangsanli5201** [open-mmlab/mmsegmentation#342]
Wonderful work!

I'd like to train the deeplabv3 (resnet50) on VOC12, but I cannot find the pretrained model resnet50_v1c. The link in the model zoo is gone.  I tried to manually download it from: http://download/openmmlab.com/pretrain/third_party/resnet50_v1c-2cccclad.pth, but didn't work.

So, where can I get the pretrained model? Looking forward to your response.

Thanks!

**Comment by MANDYCHAO** [comment]
I meet this problem, too. Have you solved it ?
