### ISSUE TITLE
how to visualize the result without background?

### ISSUE THREAD

**Issue by shinpaul14** [open-mmlab/mmsegmentation#3427]
Hello. 

I just had a question about visualization. 

I am hoping to overpay my model's prediction to the input image, however, the appearance of the background and the name tag is the big problem. 
How can I remove them when I visualize my results?

Thank you.

**Comment by guozhen-dev** [comment]
According to my understanding, I assume you want to have an export result image without a background and the label text. I am working on supporting a switch to enable the selection of layers on this.

**Comment by guozhen-dev** [comment]
Just want to make sure this is the feature you want to have. 
<img width="1028" alt="image" src="https://github.com/open-mmlab/mmsegmentation/assets/39869385/0e8f51fd-83ac-484f-ae21-42bddecd0439">

**Comment by shinpaul14** [comment]
Yes, I want to show only the prediction without the background and the name tag.

**Comment by xiexinch** [comment]
Please check the use case in this PR https://github.com/open-mmlab/mmsegmentation/pull/3466

**Comment by bjzhb666** [comment]
@xiexinch @guozhen-dev  Hi, I am running tools/test.py and facing the same problem. How to solve it?
 https://github.com/open-mmlab/mmsegmentation/issues/3648

```
python tools/test.py configs.py \
 work_dirs/0.pth \
 --show-dir work_dirs
```
