### ISSUE TITLE
Issue about UNet Loss

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmsegmentation#343]
In paper, pre-compute the weight map for each ground truth segmentation. But I not found the code.

**Comment by Junjun2016** [comment]
Hi @as754770178 
In our experimental setting, we do not use weighted CE loss.
If you want to use weighted CE, you can calculate the class weights by yourself.

**Comment by as754770178** [comment]
I train unet on voc, I the result is very poor`(mDice: 0.1437, mAcc: 0.1112, aAcc: 0.7578)`. 
```
_base_ = [
    '../_base_/models/unet_s5-d16.py', '../_base_/datasets/pascal_voc12.py',
    '../_base_/default_runtime.py', '../_base_/schedules/schedule_40k.py'
]
test_cfg = dict(crop_size=(64, 64), stride=(42, 42))
evaluation = dict(metric='mDice')
```

**Comment by Junjun2016** [comment]
> I train unet on voc, I the result is very poor`(mDice: 0.1437, mAcc: 0.1112, aAcc: 0.7578)`. I change the num_classes of head to 21.
> 
> ```
> _base_ = [
>     '../_base_/models/unet_s5-d16.py', '../_base_/datasets/pascal_voc12.py',
>     '../_base_/default_runtime.py', '../_base_/schedules/schedule_40k.py'
> ]
> test_cfg = dict(crop_size=(64, 64), stride=(42, 42))
> evaluation = dict(metric='mDice')
> ```

Increase the crop size.
