### ISSUE TITLE
What does v1c stand for?

### ISSUE THREAD

**Issue by Klopotek0** [open-mmlab/mmsegmentation#3447]
I tried to look for models that are not pretrained on any big dataset, but I couldn't find anything. Is it possible to perform a training for ex. with Deeplabv3+ with resnet-101 pretrained on imagenet? I don't think that's an option, or maybe somewhere? What does v1c in backbones stand for? Does it means it's pretrained on imagenet? I found a glimse that all backbones are  pretrained on imagenet, but I cannot find any clarifacation

**Comment by xiexinch** [comment]
It is a modified version of ResNet, you can check out this paper.
https://arxiv.org/abs/1812.01187
