### ISSUE TITLE
mmseg - INFO - Loaded 0 images

### ISSUE THREAD

**Issue by Deicide-PiLi** [open-mmlab/mmsegmentation#345]
2021-01-13 23:56:21,176 - mmseg - INFO - Loaded 0 images
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 150, in main
    train_segmentor(
  File "/media/solan/3E2E97F633AB301E/1-dlz/mmsegmentation/mmseg/apis/train.py", line 45, in train_segmentor
    data_loaders = [
  File "/media/solan/3E2E97F633AB301E/1-dlz/mmsegmentation/mmseg/apis/train.py", line 46, in <listcomp>
    build_dataloader(
  File "/media/solan/3E2E97F633AB301E/1-dlz/mmsegmentation/mmseg/datasets/builder.py", line 140, in build_dataloader
    data_loader = dataloader(
  File "/home/solan/anaconda3/envs/dlz-mmseg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/home/solan/anaconda3/envs/dlz-mmseg/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 95, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by Deicide-PiLi** [comment]
use dataset in Citycapes format, and occur this error

**Comment by xvjiarui** [comment]
Hi @Deicide-PiLi 
You may check if your file path or data path is correct.

**Comment by elmira784** [comment]
I have same problem however I am sure that data path is correct but I don't know what you mean by file path?


> Hi @Deicide-PiLi
> You may check if your file path or data path is correct.

**Comment by Litou-lyh** [comment]
I think you need to check the data_root, img_dir and suffix of imgs and masks in in mmseg/dataset/[dataset_type].py

**Comment by CachCheng** [comment]
you should fix dataset file in mmseg/cityscapes.py:
@DATASETS.register_module()
class CityscapesDataset(CustomDataset):
    """Cityscapes dataset.

    The ``img_suffix`` is fixed to '_leftImg8bit.png' and ``seg_map_suffix`` is
    fixed to '_gtFine_labelTrainIds.png' for Cityscapes dataset.
    """

    CLASSES = ('sky', 'tree', 'road', 'grass', 'water', 'bldg', 'mntn', 'fg obj')

    PALETTE = [[128, 128, 128], [129, 127, 38],
               [120, 69, 125], [53, 125, 34],
               [0, 11, 123], [118, 20, 12],
               [122, 81, 25], [241, 134, 51]]

    def __init__(self, **kwargs):
        super(CityscapesDataset, self).__init__(
            img_suffix='.jpg',
            seg_map_suffix='.png',
            **kwargs)

**Comment by Linda-L** [comment]
This problem will not be reported during multi-GPU training. This problem will be reported during single-card training.

**Comment by gingerZone27** [comment]
There may be solutions below to this problem:

- check your path to your images and annotations in your config file
- check which dataset type you are using, and go to mmseg/datasets/ and check the requirement of the corresponding dataset type. You should check **the format of image and annotation** and its **suffix**.

For the second solution, make sure that your image is indeed "jpg" instead of "png". But you also change the format requirement if necessary.

Hope you solve your problem.

**Comment by Anderien** [comment]
maybe you should modify the codes in `mmseg/datasets/yourdataset.py` 
 `img_suffix='.jpg',
        seg_map_suffix='.png',
`  to `img_suffix='',
        seg_map_suffix=''`, I solve my problem in this way :)

**Comment by N-Jaro** [comment]
> maybe you should modify the codes in `mmseg/datasets/yourdataset.py` `img_suffix='.jpg', seg_map_suffix='.png', ` to `img_suffix='', seg_map_suffix=''`, I solve my problem in this way :)

This actually works for me
