### ISSUE TITLE
Error when running the tutorial. Got "SegDataSample' object has no attribute '_gt_sem_seg"

### ISSUE THREAD

**Issue by shinpaul14** [open-mmlab/mmsegmentation#3458]
`from mmseg.apis import init_model, inference_model, show_result_pyplot

config_path = r'pspnet_r50-d8_4xb2-40k_cityscapes-512x1024.py'
checkpoint_path = r'pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth'
img_path = 'demo/demo.png'

try:
    # build the model from a config file and a checkpoint file
    model = init_model(config_path, checkpoint_path, device='cuda:0')

    # inference on given image
    result = inference_model(model, img_path)

    # display the segmentation result
    vis_image = show_result_pyplot(model, img_path, result)

    # save the visualization result
    vis_image = show_result_pyplot(model, img_path, result, out_file='work_dirs/result.png')

except Exception as e:
    print(f"An error occurred: {e}")`
    
    when I run the tutorial I get `An error occurred: 'SegDataSample' object has no attribute '_gt_sem_seg'`
    This error has anyone gotten the same error that has solved this?

**Comment by wujiang0156** [comment]
yeth, i met the same error. Did you solve it?

**Comment by wujiang0156** [comment]
> yeth, i met the same error. Did you solve it?
you should add the next code:
sem_seg = torch.from_numpy(sem_seg)
gt_sem_seg_data = dict(data=sem_seg)
gt_sem_seg = PixelData(**gt_sem_seg_data)
data_sample = SegDataSample()
data_sample.gt_sem_seg = gt_sem_seg

**Comment by yzb2** [comment]
I just ran into this, and it was because I didn't have `LoadAnnotations` in my `test_pipeline`. After 4 hours of debugging, I am filled with rage and sadness. I am inconsolable, my day is ruined, and I have only myself to blame. 

May this comment hopefully protect you from my fate.

**Comment by chcchc97** [comment]
@wujiang0156 @shinpaul14 hello，how can you solve this problem?
