### ISSUE TITLE
我导出onnx模型后，使用tensorrt预测，得到的结果和pytorch预测的结果不一样？

### ISSUE THREAD

**Issue by iralhx** [open-mmlab/mmsegmentation#3459]
我使用KNet和Segformer模型，使用onnx和pytorch进行预测，得到的结果是正确的，但是使用tensorrt来预测，无法得到正确的结果。使用的预处理是一样的。onnx和pytorch是用python，tensorrt使用C++。
cuda:11.7
pytorch:1.3
toserrt:8.5.1.7
是我哪里有问题吗？谢谢！

**Comment by iralhx** [comment]
原因是因为预处理的时候，输入的数据是RGB方式排列的，需要改成RRRRRRR,GGGGGG,BBBBBB

**Comment by OSSome01** [comment]
Hey, I have been trying to convert the KNet model to ONNX but have not been able to do so. Can you please let me know you did it?

**Comment by iralhx** [comment]
> 我一直在尝试将 KNet 模型转换为 ONNX 但未能成功。 你能让我知道你做到了吗？
> 
> Hey, I have been trying to convert the KNet model to ONNX but have not been able to do so. Can you please let me know you did it?

可以参考这个链接的文档。
https://mmdeploy.readthedocs.io/zh-cn/latest/05-supported-backends/tensorrt.html
