### ISSUE TITLE
how to solve the keyError："GTADataset: ' is not in the pipeline registry'"

### ISSUE THREAD

**Issue by 1377534928** [open-mmlab/mmsegmentation#3477]

**Comment by 1377534928** [comment]
when I add the GTADataSet into the mmseg.datasets， the error appears. I check every init.py ,I have add the initialization of the gtadataset. Can someone give me the solution?

**Comment by ryanalexmartin** [comment]
It seems you are trying to add a custom dataset.

Can you please provide your 

1.) config file 
2.) relevant code
3.) The command you ran
4.) the full console output, not just the abbreviated error?

and talk a bit about what it is you are trying to accomplish?

Also, what is GTADataset?  Is it a collection of screenshots?  Videos?  I'm assuming it has something to do with the video game franchise "Grand Theft Auto".

**Comment by 1377534928** [comment]
I have solved it，thanks！

**Comment by NeoGeon** [comment]
how do u solve this?

**Comment by 1377534928** [comment]
It is my fault.&nbsp;I accidentally deleted a GTAdataset word.&nbsp;
&nbsp;


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月16日(星期二) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [open-mmlab/mmsegmentation] how to solve the keyError：&quot;GTADataset: &#39; is not in the pipeline registry&#39;&quot; (Issue #3477)





 
how do u solve this?
