### ISSUE TITLE
about photometric aug（for randomly swap channels）

### ISSUE THREAD

**Issue by sumenpuyuan** [open-mmlab/mmsegmentation#349]
in transform.py, photometric function says that it will randomly swap channels,but it does not.
 
what i want to know it that why delete the swap channel codes.

it is harmfuly for miou or just forgort ?

**Comment by xvjiarui** [comment]
Hi @sumenpuyuan 
We don't use swap channels. But I haven't tried if it is harmful. The docstring is wrong. I will correct it later.

**Comment by sumenpuyuan** [comment]
thx!
