### ISSUE TITLE
Mask2Former错误CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by mxmdpc** [open-mmlab/mmsegmentation#3498]
您好！运行mask2former的mask2former/mask2former_swin-b-in22k-384x384-pre_8xb2-160k_ade20k-640x640.py出现错误，请问是timm版本错误吗？试了几个都不行，该如何解决呢？
![image](https://github.com/open-mmlab/mmsegmentation/assets/71645197/14601d61-093c-4f2b-ab75-2c2a1695408d)
![image](https://github.com/open-mmlab/mmsegmentation/assets/71645197/dd8bfe4a-369b-46bf-9abb-cca0ada05e46)

**Comment by WLBer** [comment]
你好！请问解决了嘛，怎么解决的呢？
