### ISSUE TITLE
mmcv2.1.0 has no attribute 'FileClient' 

### ISSUE THREAD

**Issue by Cj-lwh** [open-mmlab/mmsegmentation#3508]
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\sgiit\anaconda3\envs\mmsegmentation\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\sgiit\anaconda3\envs\mmsegmentation\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\sgiit\anaconda3\envs\mmsegmentation\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\sgiit\anaconda3\envs\mmsegmentation\lib\site-packages\mmengine\dataset\dataset_wrapper.py", line 290, in __getitem__
    return self.dataset[sample_idx]
  File "C:\Users\sgiit\anaconda3\envs\mmsegmentation\lib\site-packages\mmengine\dataset\base_dataset.py", line 410, in __getitem__
    data = self.prepare_data(idx)
  File "C:\Users\sgiit\anaconda3\envs\mmsegmentation\lib\site-packages\mmengine\dataset\base_dataset.py", line 793, in prepare_data
    return self.pipeline(data_info)
  File "C:\Users\sgiit\anaconda3\envs\mmsegmentation\lib\site-packages\mmengine\dataset\base_dataset.py", line 60, in __call__
    data = t(data)
  File "e:\graduation project\mmsegmentation-main\mmsegmentation\mmseg\datasets\transforms\loading.py", line 66, in __call__
    self.file_client = mmcv.FileClient(**self.file_client_args)
AttributeError: module 'mmcv' has no attribute 'FileClient'

here is my code:
@TRANSFORMS.register_module()
class LoadTiffImageFromFile(object):
    """Load an tiff image from file.

    Required keys are "img_prefix" and "img_info" (a dict that must contain the
    key "filename"). Added or updated keys are "filename", "img", "img_shape",
    "ori_shape" (same as `img_shape`), "pad_shape" (same as `img_shape`),
    "scale_factor" (1.0) and "img_norm_cfg" (means=0 and stds=1).

    Args:
        to_float32 (bool): Whether to convert the loaded image to a float32
            numpy array. If set to False, the loaded image is an uint8 array.
            Defaults to False.
        color_type (str): The flag argument for :func:`mmcv.imfrombytes`.
            Defaults to 'color'.
        file_client_args (dict): Arguments to instantiate a FileClient.
            See :class:`mmcv.fileio.FileClient` for details.
            Defaults to ``dict(backend='disk')``.
        imdecode_backend (str): Backend for :func:`mmcv.imdecode`. Default:
            'cv2'
    """

    def __init__(self,
                 to_float32=False,
                 color_type='color',
                 file_client_args=dict(backend='disk'),
                 imdecode_backend='tiff'):
        self.to_float32 = to_float32
        self.color_type = color_type
        self.file_client_args = file_client_args.copy()
        self.file_client = None
        self.imdecode_backend = imdecode_backend

    def __call__(self, results):
        """Call functions to load image and get image meta information.

        Args:
            results (dict): Result dict from :obj:`mmseg.CustomDataset`.

        Returns:
            dict: The dict contains loaded image and meta information.
        """

        if self.file_client is None:
            self.file_client = mmcv.FileClient(**self.file_client_args)

        if results.get('img_prefix') is not None:
            filename = os.path.join(results['img_prefix'],
                                results['img_info']['filename'])
        else:
            filename = results['img_info']['filename']
        # 原来的数据加载语句
        # img_bytes = self.file_client.get(filename)
        # img = mmcv.imfrombytes(
        #     img_bytes, flag=self.color_type, backend=self.imdecode_backend)
        # 现在的数据加载语句
        dataset = gdal.Open(filename)
        img = dataset.ReadAsArray()
        img = img.transpose((2,1,0)) #GDAL读取文件是（C,W,H）,而numpy是(H,W,C),需要转换一下

        if self.to_float32:
            img = img.astype(np.float32)

        results['filename'] = filename
        results['ori_filename'] = results['img_info']['filename']
        results['img'] = img
        results['img_shape'] = img.shape
        results['ori_shape'] = img.shape
        # Set initial values for default meta_keys
        results['pad_shape'] = img.shape
        results['scale_factor'] = 1.0
        num_channels = 1 if len(img.shape) < 3 else img.shape[2]
        results['img_norm_cfg'] = dict(
            mean=np.zeros(num_channels, dtype=np.float32),
            std=np.ones(num_channels, dtype=np.float32),
            to_rgb=False)
        return results

    def __repr__(self):
        repr_str = self.__class__.__name__
        repr_str += f'(to_float32={self.to_float32},'
        repr_str += f"color_type='{self.color_type}',"
        repr_str += f"imdecode_backend='{self.imdecode_backend}')"
        return repr_str

**Comment by Cj-lwh** [comment]
already solved.

**Comment by Jason-u** [comment]
Can you tell me how you solved this issue? I am currently facing the same problem.

**Comment by Cj-lwh** [comment]
use "mmengine.fileio.file_client.FileClient" to replace "mmcv.FileClient".

**Comment by Jason-u** [comment]
ORZ!Thank u!!!!
