### ISSUE TITLE
使用pytorch2torchscript.py来导出mask2former模型，当导出为gpu上的torchscript模型后，测试发现精度损失很厉害，而cpu的pt模型不会

### ISSUE THREAD

**Issue by edition3234** [open-mmlab/mmsegmentation#3515]
我也尝试了直接使用下面代码来导出模型，当使用得到的traced_model，输入和给torchscript模型一样的数据后查看结果，发现和gpu的pt模型推理结果一样，精度损失以至于分割效果很差。

```
model = init_model(config_path, checkpoint_path, device='cuda:0')

verify = True
imgs = torch.randn(1,3,512,512).to("cuda")
traced_model = torch.jit.trace(model,example_inputs=imgs,check_trace=verify)
traced_model.save(output_file)
```

使用result = mmseg.apis.inference_model(model, img)来推理，分割结果正常，**使用cpu的torchscript模型来推理测试，结果也符合预期**

**请问是不是mmsegmentation对于导出mask2former模型，在gpu上的torchscript模型有bug，不适配**

我也尝试使用traced_model = torch.jit.script(model)来导出，但是失败。

下面是使用pytorch2torchscript.py导出gpu上的torchscript模型时，输出的一些警告和log(导出cpu版本的时候，警告一样）

```
functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]

TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for list, use a tuple instead. for dict, use a NamedTuple instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
module._c._create_method_from_trace(

Successfully exported TorchScript model: mask2former_gpu.pt
```

**Comment by edition3234** [comment]
问题已解决，是MultiScaleDeformableAttention层的GPU实现不"适配”trace，CPU的实现可以正常trace出来，所以将mmcv/ops/multi_scale_deform_attn.py中的GPU实现，改成和cpu一样，即可导出精度没损失的gpu上的pt模型

**Comment by stihuangyuan** [comment]
> 问题已解决，是MultiScaleDeformableAttention层的GPU实现不"适配”trace，CPU的实现可以正常trace出来，所以将mmcv/ops/multi_scale_deform_attn.py中的GPU实现，改成和cpu一样，即可导出精度没损失的gpu上的pt模型

请问multi_scale_deform_attn.py中gpu实现改成和cpu一样，推理速度会降低吗？训练模型过程中需不需要也改？
