### ISSUE TITLE
What is the definition of  IOU and ACC of test result?

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmsegmentation#353]
Hello

Could you please provide the inference of the methods of how to calculate the IOU and ACC of the test result?

Thank you so much!

**Comment by xvjiarui** [comment]
Hi @minan19605 
IoU stands for intersection over union.
Acc stands for accuracy.

**Comment by minan19605** [comment]
Thank you for your information.
Would you mind providing more information about how the mmsegmentation to calculate the IOU and Acc.
Also I want to know:
1. is the Acc for classes?
2. How to calculate the Acc?
I assume the IOU is calculated by the predicted area and ground truth. But how to calculate the Acc?

**Comment by xvjiarui** [comment]
Acc is also calculated by prediction and ground truth. Percentage of how much pixel is predicted the same as ground truth.
