### ISSUE TITLE
TypeErrorTypeError: : 'DataContainer' object is not iterable'DataContainer' object is not iterable

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#356]
ori_shapes = [_['ori_shape'] for _ in img_meta]TypeErrorori_shapes = [_['ori_shape'] for _ in img_meta]
:
'DataContainer' object is not iterable
TypeErrorTypeError: : 'DataContainer' object is not iterable'DataContainer' object is not iterable

    ori_shapes = [_['ori_shape'] for _ in img_meta]
TypeError: 'DataContainer' object is not iterable
    ori_shapes = [_['ori_shape'] for _ in img_meta]
TypeError: 'DataContainer' object is not iterable
Killing subprocess 82946
Killing subprocess 82947
Killing subprocess 82948
Killing subprocess 82949
Killing subprocess 82950
Killing subprocess 82951
Killing subprocess 82952
Killing subprocess 82953

pytorch version '1.8.0.dev20210111'
mmcv version '1.2.5'

commod line: ./tools/dist_train.sh configs/unet/fcn_unet_s5-d16_128x128_40k_chase_db1.py 8

**Comment by YLyeliang** [comment]
This is because your data pre-processing transformed the metadata into  DataContainer, and didn't transform it back to the normal list in collate process, check your collate function, make sure it properly transformed the meta data.

**Comment by jianlong-yuan** [comment]
> This is because your data pre-processing transformed the metadata into DataContainer, and didn't transform it back to the normal list in collate process, check your collate function, make sure it properly transformed the metadata.

But I just use the standard config -->> configs/unet/fcn_unet_s5-d16_128x128_40k_chase_db1.py

**Comment by Suspext** [comment]
Have you solved this problem? I have the same problem.

> > This is because your data pre-processing transformed the metadata into DataContainer, and didn't transform it back to the normal list in collate process, check your collate function, make sure it properly transformed the metadata.
> 
> But I just use the standard config -->> configs/unet/fcn_unet_s5-d16_128x128_40k_chase_db1.py

**Comment by JackeyGHD1** [comment]
> > This is because your data pre-processing transformed the metadata into DataContainer, and didn't transform it back to the normal list in collate process, check your collate function, make sure it properly transformed the metadata.
> 
> But I just use the standard config -->> configs/unet/fcn_unet_s5-d16_128x128_40k_chase_db1.py

Have you solved this problem?

**Comment by Lature-Yang** [comment]
Have you solved this problem?

**Comment by zachcoleman** [comment]
I recreated this error in the workflow involving the `mmcv.parallel` _collate_ function. The _collate_ function preserves the DataContainer object for "img_metas" after being called on input data like so:
```python 
from mmcv.parallel import DataContainer
data = {"img_metas": DataContainer({"info": "foo"})}
data = collate([data], samples_per_gpu=1)
```

If you were running the model inference on CPU, you'd hit the error on this line:
```python
data["img_metas"] = [i.data[0] for i in data["img_metas"]]
```

However, if the inference is run on a _cuda_ device, the `scatter` function accesses the `data` attribute of the DataContainer here:
```python
if isinstance(obj, DataContainer):
            if obj.cpu_only:
                return obj.data
            else:
                return Scatter.forward(target_gpus, obj.data)
```

Then, the error is not tripped until the `forward_test` of the model is called on `**data` which results in a DataContainer being in the "img_metas" argument.

This seems to me to be a dependency of the `pipeline` requiring the use of test time augmentation from the `MultiScaleFlipAug` transform. If you don't use this module, the `results` dictionary at the end of the pipeline will not be a dictionary of lists necessarily and the `collate` will not transform the DataContainer into a list of list of dictionaries as described in the method signature: 
```python
def forward_test(self, imgs, img_metas, **kwargs):
        """
        Args:
            imgs (List[Tensor]): the outer list indicates test-time
                augmentations and inner Tensor should have a shape NxCxHxW,
                which contains all images in the batch.
            img_metas (List[List[dict]]): the outer list indicates test-time
                augs (multiscale, flip, etc.) and the inner list indicates
                images in a batch.
        """
```

Are y'all using the `MultiScaleFlipAug` in the test and val pipeline?

**Comment by Junjun2016** [comment]
> I recreated this error in the workflow involving the `mmcv.parallel` _collate_ function. The _collate_ function preserves the DataContainer object for "img_metas" after being called on input data like so:
> 
> ```python
> from mmcv.parallel import DataContainer
> data = {"img_metas": DataContainer({"info": "foo"})}
> data = collate([data], samples_per_gpu=1)
> ```
> 
> If you were running the model inference on CPU, you'd hit the error on this line:
> 
> ```python
> data["img_metas"] = [i.data[0] for i in data["img_metas"]]
> ```
> 
> However, if the inference is run on a _cuda_ device, the `scatter` function accesses the `data` attribute of the DataContainer here:
> 
> ```python
> if isinstance(obj, DataContainer):
>     if obj.cpu_only:
>         return obj.data
>     else:
>         return Scatter.forward(target_gpus, obj.data)
> ```
> 
> Then, the error is not tripped until the `forward_test` of the model is called on `**data` which results in a DataContainer being in the "img_metas" argument.
> 
> This seems to me to be a dependency of the `pipeline` requiring the use of test time augmentation from the `MultiScaleFlipAug` transform. If you don't use this module, the `results` dictionary at the end of the pipeline will not be a dictionary of lists necessarily and the `collate` will not transform the DataContainer into a list of list of dictionaries as described in the method signature:
> 
> ```python
> def forward_test(self, imgs, img_metas, **kwargs):
>       """
>       Args:
>           imgs (List[Tensor]): the outer list indicates test-time
>               augmentations and inner Tensor should have a shape NxCxHxW,
>               which contains all images in the batch.
>           img_metas (List[List[dict]]): the outer list indicates test-time
>               augs (multiscale, flip, etc.) and the inner list indicates
>               images in a batch.
>       """
> ```
> 
> Are y'all using the `MultiScaleFlipAug` in the test and val pipeline?
> 
> @xvjiarui can we reopen this issue?

Sure.

**Comment by ShoufaChen** [comment]
@zachcoleman 

Hi, the `MultiScaleFlipAug` is used in my case. How can I solve this problem?

**Comment by roberto-amoroso** [comment]
Any solutions for the problem described by @zachcoleman?

**Comment by rumozam** [comment]
Any solutions for this problem described by @zachcoleman and again by @roberto-amoroso?

**Comment by rumozam** [comment]
Any solutions for the problem described by @zachcoleman, @roberto-amoroso?

**Comment by rumozam** [comment]
I solved my problem! If this is still happening to you, possible solutions might be:
- Downgrading from torch 1.12 to 1.11 (https://github.com/open-mmlab/mmsegmentation/issues/1742#issuecomment-1177371937)
- Pulling from mmcv, because the problem was fixed!

**Comment by sym330** [comment]
> _

Have you sloved the problem？thank you
