### ISSUE TITLE
whether the mmsegmentation support multiple-gpus training on windows？ when i run it, i got this error: "RuntimeError: No rendezvous handler for env://"

### ISSUE THREAD

**Issue by lyf6** [open-mmlab/mmsegmentation#357]

**Comment by xvjiarui** [comment]
Hi @lyf6 
We haven't test multi GPU training on windows. You may switch to linux for multi GPU training.

**Comment by lyf6** [comment]
Thank you for your replying. The nccl is not supported in Windows，i can run with gloo backed.



发自我的iPhone


------------------ Original ------------------
