### ISSUE TITLE
可视化在多卡训练时的一些问题

### ISSUE THREAD

**Issue by liblacklucy** [open-mmlab/mmsegmentation#3570]
![image](https://github.com/open-mmlab/mmsegmentation/assets/55016725/4ad5e119-6da2-4866-8450-65b0f0527551)
在使用多卡训练，并且保存推理结果时，每次仅保存单卡的推理结果，比如验证集共1000张，4卡训练，结果仅保存250张图像。可视化hook的设置上图

**Comment by AAAdecade** [comment]
您好，请问如何实现不同分支的特征图可视化？
