### ISSUE TITLE
pretrained model evaluation？and train from scratch

### ISSUE THREAD

**Issue by leeyegy** [open-mmlab/mmsegmentation#358]
I have downloaded some pretrained model and tested them. However, I got some weird results as follow:

|scope| miou | macc | aAcc |
|global| 0.07  | xxx    |xxx     |
（dataset:ade20k）

the command I used for testing is as follow:
`CUDA_VISIBLE_DEVICES=4 python tools/test.py configs/deeplabv3/deeplabv3_r50-d8_512x512_80k_ade20k.py checkpoints/deeplabv3/deeplabv3_r50-d8_512x512_80k_ade20k_20200614_185028-0bb3f844.pth --eval mIoU`

Also, I have tried to train a model in ade20k using a single GPU, and I tested the model, then got similar weird results(very low miou).
the command I used for testing is as follow:

`CUDA_VISIBLE_DEVICES=4 python tools/test.py configs/resnest/deeplabv3_s101-d8_512x512_160k_ade20k.py  work_dirs/deeplabv3_s101-d8_512x512_160k_ade20k/latest.pth  --eval mIoU`

Any suggestion would be appreciated~ :)

**Comment by zhangxiaobaibai** [comment]
I also have this problem.

**Comment by zhangxiaobaibai** [comment]
Even can not get normal results when using official pretrained model

**Comment by yamengxi** [comment]
Sorry for the bug, it is fixed [here](https://github.com/xvjiarui/mmsegmentation/tree/fix_ade_test).
