### ISSUE TITLE
推理得到的语义分割图如何取消图像中的分类标注

### ISSUE THREAD

**Issue by MrRa1ndrop** [open-mmlab/mmsegmentation#3588]
如题，经过推理得到的图像会自动标注上类别文字，如果取消标注。

**Comment by MrRa1ndrop** [comment]
新版本需要在def show_result_pyplot(..),中将with_labels: Optional[bool] = True改为False即可。

**Comment by hhuzzz** [comment]
请问您使用的是demo/image_demo.py推理的吗，是在windows环境吗
