### ISSUE TITLE
The issue of image size in the model configuration file

### ISSUE THREAD

**Issue by O1dCoo1** [open-mmlab/mmsegmentation#3599]
model configuration file: configs/fcn/fcn_r50-d8_4xb2-40k_cityscapes-512x1024.py 
512 x 1024 in the model configuration file refer to using images with a height of 512 and a width of 1024 for training, or images with a height of 1024 and a width of 512 for training?

**Comment by Zoulinx** [comment]
Height of 512 and a width of 1024 for training.(https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html)
