### ISSUE TITLE
loss goes to NAN

### ISSUE THREAD

**Issue by nipeone** [open-mmlab/mmsegmentation#36]
GPU: NVIDIA 1080TI
I defined a custom datasets with 2 classes(backgroud, class1), i train the datasets with OCRnet，the config like below:
```
_base_ = [
    '../_base_/models/ocrnet_hr18.py', 
    '../_base_/datasets/mycustom.py',
    '../_base_/default_runtime.py', 
    '../_base_/schedules/schedule_120k.py'
]
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(decode_head=[
    dict(
        type='FCNHead',
        in_channels=[18, 36, 72, 144],
        channels=sum([18, 36, 72, 144]),
        in_index=(0, 1, 2, 3),
        input_transform='resize_concat',
        kernel_size=1,
        num_convs=1,
        concat_input=False,
        dropout_ratio=-1,
        num_classes=2,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    dict(
        type='OCRHead',
        in_channels=[18, 36, 72, 144],
        in_index=(0, 1, 2, 3),
        input_transform='resize_concat',
        channels=512,
        ocr_channels=256,
        dropout_ratio=-1,
        num_classes=2,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
])
# batch size
data = dict(samples_per_gpu=2, workers_per_gpu=2)
test_cfg = dict(mode='whole')
work_dir = './work_dirs/ocrnet_hr18_1024x1024_120k'
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
```

but, i got  a  problem  which decode_0.loss  and  total loss is NAN after a few  iters:

```
2020-07-23 10:00:23,185 - mmseg - INFO - Iter [3100/120000]	lr: 9.770e-03, eta: 1 day, 15:08:41, time: 1.217, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 63.5359, decode_1.loss_seg: 0.0001, decode_1.acc_seg: 63.5359, loss: 0.0002
2020-07-23 10:01:21,304 - mmseg - INFO - Iter [3150/120000]	lr: 9.766e-03, eta: 1 day, 15:06:21, time: 1.162, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 64.1833, decode_1.loss_seg: 0.0001, decode_1.acc_seg: 64.1833, loss: 0.0003
2020-07-23 10:02:21,155 - mmseg - INFO - Iter [3200/120000]	lr: 9.762e-03, eta: 1 day, 15:05:07, time: 1.197, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 65.1630, decode_1.loss_seg: 0.0003, decode_1.acc_seg: 65.1630, loss: 0.0005
2020-07-23 10:03:23,215 - mmseg - INFO - Iter [3250/120000]	lr: 9.758e-03, eta: 1 day, 15:05:12, time: 1.241, data_time: 0.011, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 10.9057, decode_1.loss_seg: nan, decode_1.acc_seg: 18.0268, loss: nan
2020-07-23 10:04:24,325 - mmseg - INFO - Iter [3300/120000]	lr: 9.755e-03, eta: 1 day, 15:04:41, time: 1.222, data_time: 0.011, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 4.1666, decode_1.loss_seg: nan, decode_1.acc_seg: 10.4796, loss: nan
2020-07-23 10:05:25,908 - mmseg - INFO - Iter [3350/120000]	lr: 9.751e-03, eta: 1 day, 15:04:27, time: 1.232, data_time: 0.013, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 3.5404, decode_1.loss_seg: nan, decode_1.acc_seg: 18.5238, loss: nan
2020-07-23 10:06:27,386 - mmseg - INFO - Iter [3400/120000]	lr: 9.747e-03, eta: 1 day, 15:04:07, time: 1.230, data_time: 0.012, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 3.5969, decode_1.loss_seg: nan, decode_1.acc_seg: 13.0671, loss: nan
2020-07-23 10:07:27,093 - mmseg - INFO - Iter [3450/120000]	lr: 9.744e-03, eta: 1 day, 15:02:45, time: 1.193, data_time: 0.012, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 4.8962, decode_1.loss_seg: nan, decode_1.acc_seg: 11.4185, loss: nan
```

**Comment by nipeone** [comment]
i have tried pspnet,deeplabv3, there are the same problems

**Comment by xvjiarui** [comment]
Hi @nipeone 
You may try the following suggestions:
1. Warmup 
2. Make the learning rate smaller.

**Comment by Deeachain** [comment]
> GPU: NVIDIA 1080TI
> I defined a custom datasets with 2 classes(backgroud, class1), i train the datasets with OCRnet，the config like below:
> 
> ```
> _base_ = [
>     '../_base_/models/ocrnet_hr18.py', 
>     '../_base_/datasets/mycustom.py',
>     '../_base_/default_runtime.py', 
>     '../_base_/schedules/schedule_120k.py'
> ]
> norm_cfg = dict(type='SyncBN', requires_grad=True)
> model = dict(decode_head=[
>     dict(
>         type='FCNHead',
>         in_channels=[18, 36, 72, 144],
>         channels=sum([18, 36, 72, 144]),
>         in_index=(0, 1, 2, 3),
>         input_transform='resize_concat',
>         kernel_size=1,
>         num_convs=1,
>         concat_input=False,
>         dropout_ratio=-1,
>         num_classes=2,
>         norm_cfg=norm_cfg,
>         align_corners=False,
>         loss_decode=dict(
>             type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
>     dict(
>         type='OCRHead',
>         in_channels=[18, 36, 72, 144],
>         in_index=(0, 1, 2, 3),
>         input_transform='resize_concat',
>         channels=512,
>         ocr_channels=256,
>         dropout_ratio=-1,
>         num_classes=2,
>         norm_cfg=norm_cfg,
>         align_corners=False,
>         loss_decode=dict(
>             type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
> ])
> # batch size
> data = dict(samples_per_gpu=2, workers_per_gpu=2)
> test_cfg = dict(mode='whole')
> work_dir = './work_dirs/ocrnet_hr18_1024x1024_120k'
> optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
> ```
> 
> but, i got a problem which decode_0.loss and total loss is NAN after a few iters:
> 
> ```
> 2020-07-23 10:00:23,185 - mmseg - INFO - Iter [3100/120000]	lr: 9.770e-03, eta: 1 day, 15:08:41, time: 1.217, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 63.5359, decode_1.loss_seg: 0.0001, decode_1.acc_seg: 63.5359, loss: 0.0002
> 2020-07-23 10:01:21,304 - mmseg - INFO - Iter [3150/120000]	lr: 9.766e-03, eta: 1 day, 15:06:21, time: 1.162, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 64.1833, decode_1.loss_seg: 0.0001, decode_1.acc_seg: 64.1833, loss: 0.0003
> 2020-07-23 10:02:21,155 - mmseg - INFO - Iter [3200/120000]	lr: 9.762e-03, eta: 1 day, 15:05:07, time: 1.197, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 65.1630, decode_1.loss_seg: 0.0003, decode_1.acc_seg: 65.1630, loss: 0.0005
> 2020-07-23 10:03:23,215 - mmseg - INFO - Iter [3250/120000]	lr: 9.758e-03, eta: 1 day, 15:05:12, time: 1.241, data_time: 0.011, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 10.9057, decode_1.loss_seg: nan, decode_1.acc_seg: 18.0268, loss: nan
> 2020-07-23 10:04:24,325 - mmseg - INFO - Iter [3300/120000]	lr: 9.755e-03, eta: 1 day, 15:04:41, time: 1.222, data_time: 0.011, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 4.1666, decode_1.loss_seg: nan, decode_1.acc_seg: 10.4796, loss: nan
> 2020-07-23 10:05:25,908 - mmseg - INFO - Iter [3350/120000]	lr: 9.751e-03, eta: 1 day, 15:04:27, time: 1.232, data_time: 0.013, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 3.5404, decode_1.loss_seg: nan, decode_1.acc_seg: 18.5238, loss: nan
> 2020-07-23 10:06:27,386 - mmseg - INFO - Iter [3400/120000]	lr: 9.747e-03, eta: 1 day, 15:04:07, time: 1.230, data_time: 0.012, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 3.5969, decode_1.loss_seg: nan, decode_1.acc_seg: 13.0671, loss: nan
> 2020-07-23 10:07:27,093 - mmseg - INFO - Iter [3450/120000]	lr: 9.744e-03, eta: 1 day, 15:02:45, time: 1.193, data_time: 0.012, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 4.8962, decode_1.loss_seg: nan, decode_1.acc_seg: 11.4185, loss: nan
> ```

Can you show me your ../_base_/models/ocrnet_hr18.py content，I'm adding custom dataset too.
But i can't load my data correct.Can you give some notes to help me done?

**Comment by nipeone** [comment]
> > GPU: NVIDIA 1080TI
> > I defined a custom datasets with 2 classes(backgroud, class1), i train the datasets with OCRnet，the config like below:
> > ```
> > _base_ = [
> >     '../_base_/models/ocrnet_hr18.py', 
> >     '../_base_/datasets/mycustom.py',
> >     '../_base_/default_runtime.py', 
> >     '../_base_/schedules/schedule_120k.py'
> > ]
> > norm_cfg = dict(type='SyncBN', requires_grad=True)
> > model = dict(decode_head=[
> >     dict(
> >         type='FCNHead',
> >         in_channels=[18, 36, 72, 144],
> >         channels=sum([18, 36, 72, 144]),
> >         in_index=(0, 1, 2, 3),
> >         input_transform='resize_concat',
> >         kernel_size=1,
> >         num_convs=1,
> >         concat_input=False,
> >         dropout_ratio=-1,
> >         num_classes=2,
> >         norm_cfg=norm_cfg,
> >         align_corners=False,
> >         loss_decode=dict(
> >             type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
> >     dict(
> >         type='OCRHead',
> >         in_channels=[18, 36, 72, 144],
> >         in_index=(0, 1, 2, 3),
> >         input_transform='resize_concat',
> >         channels=512,
> >         ocr_channels=256,
> >         dropout_ratio=-1,
> >         num_classes=2,
> >         norm_cfg=norm_cfg,
> >         align_corners=False,
> >         loss_decode=dict(
> >             type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
> > ])
> > # batch size
> > data = dict(samples_per_gpu=2, workers_per_gpu=2)
> > test_cfg = dict(mode='whole')
> > work_dir = './work_dirs/ocrnet_hr18_1024x1024_120k'
> > optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
> > ```
> > 
> > 
> > but, i got a problem which decode_0.loss and total loss is NAN after a few iters:
> > ```
> > 2020-07-23 10:00:23,185 - mmseg - INFO - Iter [3100/120000]	lr: 9.770e-03, eta: 1 day, 15:08:41, time: 1.217, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 63.5359, decode_1.loss_seg: 0.0001, decode_1.acc_seg: 63.5359, loss: 0.0002
> > 2020-07-23 10:01:21,304 - mmseg - INFO - Iter [3150/120000]	lr: 9.766e-03, eta: 1 day, 15:06:21, time: 1.162, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 64.1833, decode_1.loss_seg: 0.0001, decode_1.acc_seg: 64.1833, loss: 0.0003
> > 2020-07-23 10:02:21,155 - mmseg - INFO - Iter [3200/120000]	lr: 9.762e-03, eta: 1 day, 15:05:07, time: 1.197, data_time: 0.012, memory: 10420, decode_0.loss_seg: 0.0002, decode_0.acc_seg: 65.1630, decode_1.loss_seg: 0.0003, decode_1.acc_seg: 65.1630, loss: 0.0005
> > 2020-07-23 10:03:23,215 - mmseg - INFO - Iter [3250/120000]	lr: 9.758e-03, eta: 1 day, 15:05:12, time: 1.241, data_time: 0.011, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 10.9057, decode_1.loss_seg: nan, decode_1.acc_seg: 18.0268, loss: nan
> > 2020-07-23 10:04:24,325 - mmseg - INFO - Iter [3300/120000]	lr: 9.755e-03, eta: 1 day, 15:04:41, time: 1.222, data_time: 0.011, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 4.1666, decode_1.loss_seg: nan, decode_1.acc_seg: 10.4796, loss: nan
> > 2020-07-23 10:05:25,908 - mmseg - INFO - Iter [3350/120000]	lr: 9.751e-03, eta: 1 day, 15:04:27, time: 1.232, data_time: 0.013, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 3.5404, decode_1.loss_seg: nan, decode_1.acc_seg: 18.5238, loss: nan
> > 2020-07-23 10:06:27,386 - mmseg - INFO - Iter [3400/120000]	lr: 9.747e-03, eta: 1 day, 15:04:07, time: 1.230, data_time: 0.012, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 3.5969, decode_1.loss_seg: nan, decode_1.acc_seg: 13.0671, loss: nan
> > 2020-07-23 10:07:27,093 - mmseg - INFO - Iter [3450/120000]	lr: 9.744e-03, eta: 1 day, 15:02:45, time: 1.193, data_time: 0.012, memory: 10420, decode_0.loss_seg: nan, decode_0.acc_seg: 4.8962, decode_1.loss_seg: nan, decode_1.acc_seg: 11.4185, loss: nan
> > ```
> 
> Can you show me your '../_base_/datasets/mycustom.py', content，I'm adding custom dataset too.
> But i can't load my data correct.Can you give some notes to help me done?

`# dataset settings
dataset_type = 'MyCustomDataset'
data_root = 'data_root/mydataset'
img_norm_cfg = dict(
    mean = [202.96784291306867, 194.26054198646997, 186.87468503533643],
    std = [33.64280427231711, 37.77336383632645, 42.91415736063068],
    to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=[(256,256), (512,512), (1024, 1024)], multiscale_mode = 'value'),
    # dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    # dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(256,256), (512,512), (1024, 1024)],
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize',multiscale_mode = 'value', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(256,256), (512,512), (1024, 1024)],
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize',multiscale_mode = 'value', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='train/images',
        ann_dir='train/mask',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='test/images',
        ann_dir='test/mask',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='test/images',
        ann_dir='test/mask',
        pipeline=test_pipeline))
`
the file is just like cityscapes.py

**Comment by Deeachain** [comment]
Hi @nipeone 
I've created an and a cityscapes.py Structurally consistent road.py in configs/datasets/ folder and mmseg/datasets/ folder,
but encounter the new error  
```Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 131, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'RoadDataset is not in the dataset registry'
```
Can you share your modefied project for me to learn?

**Comment by nipeone** [comment]
> Hi @nipeone
> You may try the following suggestions:
> 
> 1. Warmup
> 2. Make the learning rate smaller.

@xvjiarui but the loss is absolutely low

**Comment by nipeone** [comment]
> Hi @nipeone
> I've created an and a cityscapes.py Structurally consistent road.py in configs/datasets/ folder and mmseg/datasets/ folder,
> but encounter the new error
> 
> ```
>   File "tools/train.py", line 158, in <module>
>     main()
>   File "tools/train.py", line 131, in main
>     datasets = [build_dataset(cfg.data.train)]
>   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/datasets/builder.py", line 73, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
>     f'{obj_type} is not in the {registry.name} registry')
> KeyError: 'RoadDataset is not in the dataset registry'
> ```
> 
> Can you share your modefied project for me to learn?
> My Email address is [Deeachain@163.com](mailto:Deeachain@163.com),thanks~

in mmseg/datasets/__init__.py , add your custom dataset class

**Comment by nipeone** [comment]
> > Hi @nipeone
> > I've created an and a cityscapes.py Structurally consistent road.py in configs/datasets/ folder and mmseg/datasets/ folder,
> > but encounter the new error
> > ```
> >   File "tools/train.py", line 158, in <module>
> >     main()
> >   File "tools/train.py", line 131, in main
> >     datasets = [build_dataset(cfg.data.train)]
> >   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/datasets/builder.py", line 73, in build_dataset
> >     dataset = build_from_cfg(cfg, DATASETS, default_args)
> >   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
> >     f'{obj_type} is not in the {registry.name} registry')
> > KeyError: 'RoadDataset is not in the dataset registry'
> > ```
> > 
> > 
> > Can you share your modefied project for me to learn?
> > My Email address is [Deeachain@163.com](mailto:Deeachain@163.com),thanks~
> 
> in mmseg/datasets/__init__.py , add your custom dataset class

**Comment by nipeone** [comment]
> Hi @nipeone
> I've created an and a cityscapes.py Structurally consistent road.py in configs/datasets/ folder and mmseg/datasets/ folder,
> but encounter the new error
> 
> ```
>   File "tools/train.py", line 158, in <module>
>     main()
>   File "tools/train.py", line 131, in main
>     datasets = [build_dataset(cfg.data.train)]
>   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/datasets/builder.py", line 73, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
>     f'{obj_type} is not in the {registry.name} registry')
> KeyError: 'RoadDataset is not in the dataset registry'
> ```
> 
> Can you share your modefied project for me to learn?
> My Email address is [Deeachain@163.com](mailto:Deeachain@163.com),thanks~

if you defined a class like RoadDataset in mmseg/datasets/road.py, u must add the class to mmseg/datasets/\_\_init\_\_.py,there are examples in \_\_init\_\_.py

**Comment by Deeachain** [comment]
> > Hi @nipeone
> > I've created an and a cityscapes.py Structurally consistent road.py in configs/datasets/ folder and mmseg/datasets/ folder,
> > but encounter the new error
> > ```
> >   File "tools/train.py", line 158, in <module>
> >     main()
> >   File "tools/train.py", line 131, in main
> >     datasets = [build_dataset(cfg.data.train)]
> >   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/datasets/builder.py", line 73, in build_dataset
> >     dataset = build_from_cfg(cfg, DATASETS, default_args)
> >   File "/home/ding/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
> >     f'{obj_type} is not in the {registry.name} registry')
> > KeyError: 'RoadDataset is not in the dataset registry'
> > ```
> > 
> > 
> > Can you share your modefied project for me to learn?
> > My Email address is [Deeachain@163.com](mailto:Deeachain@163.com),thanks~
> 
> if you defined a class like RoadDataset in mmseg/datasets/road.py, u must add the class to mmseg/datasets/__init__.py,there are examples in __init__.py

Thank you very much for your reply.
Before I ask you question, I've tried to add the class ‘RoadDataset in mmseg/datasets/road.py,’ defined by me in  __init__.py.
show as follow
```
**from .road import RoadDataset**

__all__ = [
    'CustomDataset', 'build_dataloader', 'ConcatDataset', 'RepeatDataset',
    'DATASETS', 'build_dataset', 'PIPELINES', 'CityscapesDataset',
    'PascalVOCDataset', 'ADE20KDataset'**, 'RoadDataset'**
]
```
But it didn't work with  error `KeyError: 'RoadDataset is not in the dataset registry'`
I guess I should know your approach, I will try again

**Comment by zhujiesuper** [comment]
KeyError: 'aeroscapes is not in the dataset registry'   I have add in init.py  but same aeroscapes is not in the dataset registry

**Comment by ke-dev** [comment]
try this `python setup.py develop` your problem will be solved
