### ISSUE TITLE
Error when loading an outside config file in segformer

### ISSUE THREAD

**Issue by cncloudli** [open-mmlab/mmsegmentation#3621]
```
 File "D:\mmsegmentation\venv\Lib\site-packages\mmengine\config\config.py", line 1658, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\mmsegmentation\\configs\\segformer\\./segformer_mit-b0_512x512_160k_ade20k.py'
```

when I was trying to load a config file which already exists in the segformer folder, this issue won't happened. When I was trying to load an outside config file, it came out. I download this file from DeSRA project, I've checked the format of this config, it's completely same as those original ones.

从DeSRA的谷歌盘里下载的config，在这里用不了。路径换成其他segformer文件夹里已经有的配置文件的路径都没有这个问题。已经检查过了配置文件的格式都是一样的。

**Comment by zhanghaochen-817** [comment]
hi ，have you solved th problem
