### ISSUE TITLE
Can the code rune on CPU machine , without GPU?

### ISSUE THREAD

**Issue by arijanyan94** [open-mmlab/mmsegmentation#363]
I have no GPU on my laptop, and I wonder if it is possible to run it one a CPU.

**Comment by 24hours** [comment]
There is a few problem in CPU training. 

1. There is a bug in mmcv preventing CPU training. 
2. You will need to change SyncBN to BN 
3. Training in CPU is ridiculously long, it is not practical other than testing.

**Comment by xvjiarui** [comment]
Yep. And we don't support CPU training officially.
