### ISSUE TITLE
MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

### ISSUE THREAD

**Issue by DeShinHwa** [open-mmlab/mmsegmentation#3637]
I have encountered this problem when running inference_demo.ipynb with this line of code.

import torch
import matplotlib.pyplot as plt
from mmengine.model.utils import revert_sync_batchnorm
from mmseg.apis import init_model, inference_model, show_result_pyplot

my setup (cuda: 12.1, pytorch:2.1.0, mmseg: 1.2.2, mmcv: 2.1.0, mmengine: 0.10.3)

**Comment by DeShinHwa** [comment]
I have encountered this problem when running inference_demo.ipynb with this line of code. 

import torch
import matplotlib.pyplot as plt
from mmengine.model.utils import revert_sync_batchnorm
from mmseg.apis import init_model, inference_model, show_result_pyplot

**Comment by AkramSyed002** [comment]
same with me did you guys find any solution

**Comment by antoineedy** [comment]
> > same with me did you guys find any solution
> 
> just reinstall all packages should be fine.

No, it did not work. Same happens with all the demos of MMSegmentation, but MMDet as well, and probably others.

**Comment by anamce** [comment]
Please install mmcv compatible with the pytorch, and cuda 
These two links helps you better: https://mmsegmentation.readthedocs.io/en/latest/get_started.html
https://mmcv.readthedocs.io/en/latest/get_started/installation.html

**Comment by yifanlu0227** [comment]
Edit the `__init__.py` for mmseg (`<PYTHON_DIR>/site-packages/mmseg/__init__.py`) and remove the `mmcv_max_version` requirment.
```python 
assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
    f'Please install mmcv>=2.0.0rc4.'
```
to
```python 
assert (mmcv_min_version <= mmcv_version, \
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
    f'Please install mmcv>=2.0.0rc4.'
```

**Comment by anamce** [comment]
Hi ,

After configuring out this m not able to run swin ViT as this gives other inter module error like *** module is not available In mmcv .util can you please Suggest me a complete guidline to install mmsegmentation which is compatible with cuda etc and then run swin?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by antoineedy** [comment]
Hi @anamce, these simple steps helped me:
- Create a new venv (pip or conda),
- Find your torch package (in the case of torch, tensorflow and others might work the same way) with a specific cuda version working for your machine [here](https://pytorch.org/get-started/previous-versions/).
- Install `openmim` first by doing `pip install -U openmim`.
- Then `mim install mmengine` & `mim install mmcv`.
- Install mmseg from source:
```
git clone -b main https://github.com/open-mmlab/mmsegmentation.git
cd mmsegmentation
pip install -v -e .
```

In my case, openmim automatically detected my pytorch and cuda version, and installed the mmcv version compatible with them!

_(main source, the [mmseg doc](https://mmsegmentation.readthedocs.io/en/latest/get_started.html))_

**Comment by anamce** [comment]
Yeah, I have done that so many times I failed to run model I will try again and let you know my error statement for further proceeding .

Thank-you! so much for Your quick response.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shubhamk-76** [comment]
@yifanlu0227  Even after editing the __init__.py file still getting the same error. Please tell me how you resolved the error. 

File "/mnt/DATA/CS24S001/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/__init__.py", line 61, in <module>
    assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4.

**Comment by yifanlu0227** [comment]
> @yifanlu0227 Even after editing the **init**.py file still getting the same error. Please tell me how you resolved the error.
> 
> File "/mnt/DATA/CS24S001/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/**init**.py", line 61, in assert (mmcv_min_version <= mmcv_version < mmcv_max_version), AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4.

It seems you still have the assert code in `/mnt/DATA/CS24S001/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/init.py`. Just go into this file and remove this line 61.
