### ISSUE TITLE
Validation mIoU on Pascal VOC 2012

### ISSUE THREAD

**Issue by atiszabo** [open-mmlab/mmsegmentation#364]
We are training (@hjraad) with **DeepLabV3+ with R-101-D8 backbone on Pascal VOC 2012 + Aug** should reach around **mIoU=78** running it for 40000 iterations according to the [model zoo](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3plus).

However, when I tried a couple of times with a **4 GPU** machine, I could only reach around **max 68 of mIoU** on **validation** set. The configuration is the default, however, I modified the code to use Data Parallel models instead of DDP. The same configuration works fairly well on Cityscapes, reaching 2% difference max compared to the reported numbers when **trained** with similar DeepLabV3+ and backbone and a **bit longer** to accommodate the **slower parallelization and lower number of GPUs.** 

Unfortunately, 68 vs 78 is a much larger margin with Pascal (trained for 52k iterations in my setup). I've noticed that for the model in question **the reported [log]**(https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3plus/deeplabv3plus_r101-d8_512x512_40k_voc12aug/deeplabv3plus_r101-d8_512x512_40k_voc12aug_20200613_205333.log.json) only shows **mIoU in 'train' mode**. Can it be that it is a **train mIoU?** Or is it just a **logging mistake** there?

Any other reasons why there is such a big difference? Data is prepared as it is required and described in mmseg docs.

Thank you for the help.
@xvjiarui

**Comment by atiszabo** [comment]
Hi,
we are a bit stuck with this, any updates on the item? @xvjiarui 
Thank you for your help!

**Comment by xvjiarui** [comment]
Hi @atiszabo Sorry for the late reply.
As you side, it is a logging mistake due to the bug in MMCV. 
I think the reason may due to the SyncBN since DP doesn't support SyncBN.

**Comment by atiszabo** [comment]
Thanks for the response @xvjiarui! 
Yes, with DP we have to use normal BN, but it is the same **with our Cityscapes run,** where **we reach performance close** to the **DDP models and SyncBN.** 

I don't see a difference in just changing the data. It **should** perform **close to nominal** value too with **PASCAL.** In a **single** process (with **DP**) we don't need syncing, but **BN should do the same** without any trouble like generally with any Pytorch DP models. So my point is, that it sees **similar** amount of **data in a batch**, only **DP** is a **bit slower** than DDP (known issue in Pytorch) but still with longer training iterations we should reach similar performance. Shouldn't we?

Am I missing anything important on SynBN, what else comes with it apart from the syncing between the processes? Could there be any mistake on the data preparation? I followed the description, both normal pacal and aug are in the respective folders.
4 GPU with 16GB each should be enough for PASCAL training.

**Comment by xvjiarui** [comment]
HI @atiszabo 
Have you run experiments with DDP on pascal VOC? It would be a good sanity check it see if data and. other stuff is all right. 
I don't think you are missing anything on SyncBN. SyncBN in DDP is just sync the statistics between GPUs (processes). But we haven't verify our framework with DP training. So there might be some unexpected behavior...

Hope these is helpful.
