### ISSUE TITLE
Difference between cityscapes metric and mIoU metric?

### ISSUE THREAD

**Issue by Jacobew** [open-mmlab/mmsegmentation#366]
Hi, I noticed that cityscapes has its own evaluation [here](https://github.com/open-mmlab/mmsegmentation/blob/6879b0d43c02ae9764d1e5cb23f55cbc5b2ef1fc/mmseg/datasets/cityscapes.py#L153). 
What is the difference between cityscapes metric and the custom mIoU metric?

**Comment by xvjiarui** [comment]
Hi @Jacobew 
There are some class weights for cityscapes eval. The difference is ~0.1%
