### ISSUE TITLE
MMsegmentation supports Deepspeed + zero or FSDP?

### ISSUE THREAD

**Issue by JKL-uxf** [open-mmlab/mmsegmentation#3670]
I want to test some model which is coded with mmsegmentation, since my gpu memory isn't enough to test the model, I want to try the model with Deepspeed + Zero or FSDP.

If mmsegmentation supports these, where can I find some kind of tutorial or code?

**Comment by xiexinch** [comment]
Hi @JKL-uxf,
Please follow MMEngine docs. https://mmengine.readthedocs.io/en/latest/common_usage/large_model_training.html

**Comment by JKL-uxf** [comment]
@xiexinch 

Thank you. I will try this.
