### ISSUE TITLE
Implement Multi-scale HRNet

### ISSUE THREAD

**Issue by callzhang** [open-mmlab/mmsegmentation#369]
# Describe the feature

**Motivation**
Implement the SOTA model Hierarchical Multi-Scale HRNet described [here](https://github.com/NVIDIA/semantic-segmentation)

**Related resources**
See links

**Additional context**
I am new to CV tasks. Any suggestion to reconstruct the architecture would be appreciated.

**Comment by xvjiarui** [comment]
Hi @callzhang 
You may need to modify a bunch of things, data pipeline, training, and inference of your model.

**Comment by callzhang** [comment]
after read all documents I could not figure out how to implement the hirerachical model structure. would you please provide in sight on this?
________________________________

**Comment by Junjun2016** [comment]
Hi @callzhang 
Could you please create a PR?

**Comment by callzhang** [comment]
Thanks for getting back. However I couldn't create a PR because I am not very familiar with HRNet. I would like to request this feature because I think HRNet is a pretty good option for Semseg.

**Comment by Junjun2016** [comment]
Hi @callzhang 
Paper https://arxiv.org/abs/2005.10821？

**Comment by Junjun2016** [comment]
> Thanks for getting back. However I couldn't create a PR because I am not very familiar with HRNet. I would like to request this feature because I think HRNet is a pretty good option for Semseg.

![image](https://user-images.githubusercontent.com/16716329/142842173-25c6b909-fe69-4e94-b96e-8a1e4ff5c05f.png)

Did you mean integrating HRNet with `Hierarchical multi-scale attention`?
