### ISSUE TITLE
How to remove class names in predict image

### ISSUE THREAD

**Issue by AtaraxyAdong** [open-mmlab/mmsegmentation#3710]
I want to delete the labels in the figure, but after reading the code, I can't find where I should modify.
Can you please help me take a look? Thank you very much!!
![image](https://github.com/open-mmlab/mmsegmentation/assets/50112227/885790eb-e239-439a-ae10-a0d4a5db7557)

**Comment by SherlockEuru** [comment]
Find the visualization floder in the mmseg(floder) change the local_visualizer.py line268 change with_labels:True to False. True will show the class, False is none.

**Comment by AtaraxyAdong** [comment]
Thank you very much for your answer. I've been searching for a long time and couldn't find it. Thanks again!!

**Comment by the0807** [comment]
Annotate lines 142 through 178, the class will no longer appear.

https://github.com/open-mmlab/mmsegmentation/blob/b040e147adfa027bbc071b624bedf0ae84dfc922/mmseg/visualization/local_visualizer.py#L142-L178
