### ISSUE TITLE
Different test results from the same model when testing multiple times

### ISSUE THREAD

**Issue by bjzhb666** [open-mmlab/mmsegmentation#3719]
I am using Segnext. I found that when I used the same model, the same batch size and set round_up=False in DefaultSampler. I have 1000 images and batch size is 1 for each GPU (8 GPUS in total).

But the results (IOU) are not the same. Is that a normal situation? What is the reason? No data augmentation during testing.
![image](https://github.com/open-mmlab/mmsegmentation/assets/71651717/87058ccc-201c-47a1-86bc-bb99a3c13708)

**Comment by LYKlyk** [comment]
I also meet the same problem. How to solve it?

**Comment by bjzhb666** [comment]
See [https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segnext](https://github.com/open-mmlab/mmsegmentation/tree/main/configs/segnext)

**Comment by LYKlyk** [comment]
I have tried this solution. However, it does not work! How to solve it? Thank you! @bjzhb666
