### ISSUE TITLE
Error in colab tutorial

### ISSUE THREAD

**Issue by Qiqi-0810** [open-mmlab/mmsegmentation#373]
Hi, 

I think here is an error in the *colab tutorial*, since you have already move 'train_cfg' and 'test_cfg' into 'model':

in the *train and evaluation* part, it used to be like:
```Python
model = build_segmentor(
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
```
it should be:
```Python
model = build_segmentor(
    cfg.model)
```

**Comment by Junjun2016** [comment]
Hi @Qiqi-0810 
Thanks for your feedback.
Fixed in PR https://github.com/open-mmlab/mmsegmentation/pull/1551.
