### ISSUE TITLE
How do I build a model using config？

### ISSUE THREAD

**Issue by dongxiaofei12** [open-mmlab/mmsegmentation#3780]
![1727408538309](https://github.com/user-attachments/assets/157b370b-d863-4be5-8107-bedd49195d2e)
![1727408621993](https://github.com/user-attachments/assets/ffd4383e-b663-4115-944c-0a9e444ad208)

**Comment by AI-Tianlong** [comment]
如果 是要构建一个，推理模型的话，可以参考demo：https://github.com/open-mmlab/mmsegmentation/blob/c7ac97d5dba5715785a9bde012f9e4360e0b2c37/demo/image_demo_with_inferencer.py#L38-L50

**Comment by AI-Tianlong** [comment]
如果单纯是想 通过config 构建一个model来查看模型的话，感觉可以看看：https://github.com/open-mmlab/mmengine/blob/c9b59962d679484245d4b867da57326602904bcf/mmengine/runner/runner.py#L429

**Comment by dongxiaofei12** [comment]
> 如果单纯是想 通过config 构建一个model来查看模型的话，感觉可以看看：https://github.com/open-mmlab/mmengine/blob/c9b59962d679484245d4b867da57326602904bcf/mmengine/runner/runner.py#L429

thanks
