### ISSUE TITLE
input channel > 3

### ISSUE THREAD

**Issue by superxiaoying** [open-mmlab/mmsegmentation#384]
hi,

If the input channel of my data >3, how to deal with this kind of case? Whether existing code can deal with the data H*W*C where C>3?

Best,
Ying

**Comment by xvjiarui** [comment]
HI @superxiaoying 
You may change the `input_channel` of the network. However, the pertained weight won't match.

**Comment by superxiaoying** [comment]
thx

**Comment by Geoffrey1500** [comment]
> thx
I have the same issue with you. Have you already figured it out?

**Comment by Geoffrey1500** [comment]
> HI @superxiaoying
> You may change the `input_channel` of the network. However, the pertained weight won't match.

 It would be very helpful if you could provide more details since I am not able to find the input_channel in the config files.

**Comment by MeowZheng** [comment]
Might try `in_channels`
