### ISSUE TITLE
PSPNet pretrained models  

### ISSUE THREAD

**Issue by xiamingfu** [open-mmlab/mmsegmentation#386]
When I use the pretrained models to test on PascalVocAug dataset with PSPNet，the mIoU is 74.47  with resnet 50 backbone. It's lower than the offered 76.78 about two percentage points. It's quite weird.

**Comment by xvjiarui** [comment]
Hi @xiamingfu 
Thanks for the report. I will check it.

**Comment by xiexinch** [comment]
Hi @xiamingfu 
We test the pretrained model, and the test result is as follow. Can you share how you test it?
![961614222940_ pic](https://user-images.githubusercontent.com/15952744/109097697-d046e080-775a-11eb-8042-260803f50f3d.jpg)

**Comment by xiamingfu** [comment]
> Hi @xiamingfu
> We test the pretrained model, and the test result is as follow. Can you share how you test it?
> ![961614222940_ pic](https://user-images.githubusercontent.com/15952744/109097697-d046e080-775a-11eb-8042-260803f50f3d.jpg)

Thanks a lot! First, I download the corresponding pretrained model, and configure the dataset path.Then, I run the following test command:
python tools/test.py configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py     checkpoints/pspnet_r50-d8_512x512_20k_voc12aug_20200617_101958-ed5dfbd9.pth     --eval mIoU
The result is as follows:
![image](https://user-images.githubusercontent.com/29396726/109098734-c7570e80-775c-11eb-94db-6154594b0360.png)

**Comment by xiexinch** [comment]
Hi @xiamingfu 
Did you use the latest version of MMseg? I test the model on a single GPU following the same test command as yours, but the mIoU is still 76.78, I can't reproduce your test result..
Perhaps you can test other pretrained models or datasets.

**Comment by xiamingfu** [comment]
> Hi @xiamingfu
> Did you use the latest version of MMseg? I test the model on a single GPU following the same test command as yours, but the mIoU is still 76.78, I can't reproduce your test result..
> Perhaps you can test other pretrained models or datasets.

Thank for  your careful reply ! Maybe I mistook some details, I will check my configs and test other models.

**Comment by xiamingfu** [comment]
> I met the same problem with you.
> I test the pretrained model PSPnet-r101-d8 512x512 40k on pascal VOC aug dataset with the latest code.
> The mIoU result i got is 77.11 while the result in the repo is 78.52.
> 
> Do you have any idea why this happens?
> ![捕获](https://user-images.githubusercontent.com/16838065/117523820-e2f85400-afec-11eb-81e1-7611824ae94c.PNG)

I'm sorry to hear it. Actually, I change the datasets to test, it seems the pretrained models work well on Cityscapes. Maybe you can change the datasets to evaluate algorithms.
