### ISSUE TITLE
Inference with CPU

### ISSUE THREAD

**Issue by jspablo** [open-mmlab/mmsegmentation#387]
Hi!

I trained a psp model with GPU and I can get predictions with no problem. When trying to get predictions using the CPU I get the following error:
`ValueError: SyncBatchNorm expected input tensor to be on GPU`

I am using the CPU value as documentation suggests:
`model = init_segmentor(cfg, palette, checkpoint_file, device='cpu')`

Is possible to use just the CPU?

Thank you

**Comment by xvjiarui** [comment]
Hi @jspablo 
You may change to `BN` in the config.

**Comment by jspablo** [comment]
Hi @xvjiarui

You are right, setting all cfg.norm_cfg to BN and setting device parameter to "cpu" solves the problem

Thank you

**Comment by Adityajain732** [comment]
Hi @xvjiarui @jspablo setting all the cfg.norm_cfg to BN and setting parameter to "cpu" still raises the same error(`ValueError: SyncBatchNorm expected input tensor to be on GPU`) for SWIN configs. Does SWIN models use SyncBatchNorm somewhere internally? Can you please check?
