### ISSUE TITLE
MMSegmentation_Tutorial.ipynb run error 'ConfigDict' object has no attribute 'train_cfg'

### ISSUE THREAD

**Issue by cswwp** [open-mmlab/mmsegmentation#391]
Thanks for sharing so great repo, but i meet error when i run MMSegmentation_Tutorial.ipynb, and it shows 'ConfigDict' object has no attribute 'train_cfg'

**Comment by hrsma2i** [comment]
@cswwp 
I can run it by only passing `cfg.model` which includes `train_cfg`.

```
model = build_segmentor(cfg.model)
```
