### ISSUE TITLE
Deeplabv3plus      RutimeError:it is expected output_size equals to 2 ,but got size 3     occur in the /mmseg/ops/wrappers.py

### ISSUE THREAD

**Issue by godlin-bd** [open-mmlab/mmsegmentation#40]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by rassabin** [comment]
Met the same problem during training - the reason of the problem is that data_batch['gt_semantic_seg'] has the shape = (batch, 1, H, W, 3) (for RGB mask)
 
Easy fix it just : data_batch['gt_semantic_seg'] = data_batch['gt_semantic_seg'][:,:,:,:,0] if your mask contains pixel  of classes like (0,0,0) , (1,1,1,) etc.

**Comment by godlin-bd** [comment]
Thank you very much for your patient answer, which has been very useful to me！




| |
彭泽林
|
|
邮箱：godlin_bd@126.com
|

签名由 网易邮箱大师 定制

On 07/28/2020 22:36, rassabin wrote:

Met the same problem during training - the reason of the problem is that data_batch['gt_semantic_seg'] has the shape = (batch, 1, H, W, 3) (for RGB mask)

Easy fix it just : data_batch['gt_semantic_seg'] = data_batch['gt_semantic_seg'][:,:,:,:,0] if your mask contains pixel of classes like (0,0,0) , (1,1,1,) etc.

**Comment by rassabin** [comment]
> Thank you very much for your patient answer, which has been very useful to me！ | | 彭泽林 | | 邮箱：godlin_bd@126.com | 签名由 网易邮箱大师 定制 On 07/28/2020 22:36, rassabin wrote: Met the same problem during training - the reason of the problem is that data_batch['gt_semantic_seg'] has the shape = (batch, 1, H, W, 3) (for RGB mask) Easy fix it just : data_batch['gt_semantic_seg'] = data_batch['gt_semantic_seg'][:,:,:,:,0] if your mask contains pixel of classes like (0,0,0) , (1,1,1,) etc. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

You are wellcome. But if you convert you masks into 1 dimensional format and save it, you don't need to change the code at all.
