### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by Michael971022** [open-mmlab/mmsegmentation#403]
The docker file can't run  because of the line 19 .
The word segmentation is misspelled .

But when I solve that problem another error occur
there are no [ requirements/build.txt ] file ?
I search for the pattern in whole folder , found that  [/mmsegmentation/setup.py] use it too.

**Comment by xvjiarui** [comment]
Hi @Michael971022 
Sorry for the late reply. `build.txt` is not used for now. Do you encounter any errors about it?

**Comment by MeowZheng** [comment]
No response for a long time
