### ISSUE TITLE
Invaid GT caused by PhotoMetricDistortion transformer 

### ISSUE THREAD

**Issue by sanshibayuan** [open-mmlab/mmsegmentation#404]
When I trained HrNet+OcrNet on my custom dataset(2 category), the loss was werid and the model seems no to be learning anything. After checking my GT annotation( "P" mode image with GT value "1" and BG value 0)  and my config file, I've narrowed it down to the ​ PhotoMetricDistortion in my config. When I removed this operation, it all went fine. So I guess the fault was on the realization of this one.

I havent had time to look closely into this one, just throw it out in case anyone else facing the same trouble later. After I find the bug I will update this issue too. 

![image](https://user-images.githubusercontent.com/30117384/110317397-121f3300-8047-11eb-9e32-4579ecc30424.png)

**Comment by ghoshaw** [comment]
Hi, as in your case, the Acc for class 1 is 0.0, is that right?  The mIOU is not good, seems to predict all the pixel to be class 0,  how did you solve this problem or it is normal?

**Comment by paidaxing485** [comment]
Hi, may I ask if you have solved this problem? How did you solve this problem? Thank you very much
