### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by ydhongHIT** [open-mmlab/mmsegmentation#406]
When I train the models on cityscapes, I find a crop size of 768x768 occupies more gpu memory than a crop size of 769x769. I can train with the default 769x769 but ''CUDA out of memory" occurs with crop size of 768x768.

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

First, what is your local environment, such as GPU number and type.

Second, if your GPU memory is not rich, you could lower batchsize for training/testing. Here is [config tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/config.md), you could search key words "batch" to find where to modify.

Best,
