### ISSUE TITLE
Can't download the model

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#407]
config/unet        all  'model' and 'log'
"You have no right to access this object because of bucket acl"
![屏幕截图 2021-03-10 141107](https://user-images.githubusercontent.com/48090608/110584954-00ef3700-81ab-11eb-8545-d029b30c312c.jpg)

adress:
https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_64x64_40k_drive/fcn_unet_s5-d16_64x64_40k_drive_20201223_191051-26cee593.pth

Could you tell me how to solve it？

**Comment by xvjiarui** [comment]
HI @zhongqiu1245 
We will fix it soon.

**Comment by zhongqiu1245** [comment]
@xvjiarui Thank you
