### ISSUE TITLE
Speed of mIoU calculate

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#408]
Hi, good work. but I find that it uses numpy to calculate miou. Why not use pytorch? Isn't pytorch faster?

**Comment by xvjiarui** [comment]
HI @jianlong-yuan 
We use numpy since it is easier to export to other repo. We may try pytorch later to see if it speeds up.

**Comment by jianlong-yuan** [comment]
@xvjiarui  My experiments show that pytorch will be much faster. I look forward to your results.

**Comment by xvjiarui** [comment]
Hi @jianlong-yuan 
We have a PR with that. Comments are welcome!
