### ISSUE TITLE
FWIoU

### ISSUE THREAD

**Issue by godlin-bd** [open-mmlab/mmsegmentation#41]
The eval metric is Miou now， I need to add FWIou，how can I operate?，I search the configs.MD and eval_hook.py, but I can not solve my problem.
Thank you for your help.

**Comment by xvjiarui** [comment]
Maybe you could try to implement a new dataset inherited from `CustomDataset` and overwrite `evaluate()`.

**Comment by godlin-bd** [comment]
Thank you very much for your patient answer, which has been very useful to me！





| |
彭泽林
|
|
邮箱：godlin_bd@126.com
|

签名由 网易邮箱大师 定制

On 07/30/2020 01:12, Jerry Jiarui XU wrote:

Maybe you could try to implement a new dataset inherited from CustomDataset and overwrite evaluate().
