### ISSUE TITLE
The UNet model link is error

### ISSUE THREAD

**Issue by sshuair** [open-mmlab/mmsegmentation#415]
the following link access is denied.
Backbone: UNet-S5-D16
Head: FCN
https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_64x64_40k_drive/fcn_unet_s5-d16_64x64_40k_drive_20201223_191051-26cee593.pth

**Comment by xvjiarui** [comment]
Hi @sshuair 
Sorry about that. We will fix it soon.

**Comment by MengzhangLI** [comment]
Still not working.

We would fix it ASAP.

**Comment by MengzhangLI** [comment]
Prepare to fix it.
Please check its related PR: https://github.com/open-mmlab/mmsegmentation/pull/660

Best,

**Comment by MengzhangLI** [comment]
Hi, @sshuair 

This problem is fixed, we just checked several new links of UNet (FCN) model and their results is correct.

Please, check it out.
