### ISSUE TITLE
Could you support recall, F-score and Precision

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#420]
**Motivation**
 They are very useful for mmsegmentation.

**Related resources**
https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/utils/metrics.py

 Thank you!

**Comment by sshuair** [comment]
@xvjiarui I am trying to add new feature support `Recall`, `Precision` and `F-score`. The core code has been implemented. 

But there is a problem that needs to be discussed:

currently, the `mIoU` and `mDice` only return two metrics, `IoU Acc` or `Dice Acc`.

For `f-score`, usually these are three metrics `Recall`, `Precision` and `F-score` appear at the same time. But the `mmseg/datasets/custom.py` `evaluate` method only handle two metrics.

Should we consider refactor the `evaluate` and the `metrics.py` method? 

Here is the proposal:
1. change the `metrics.py/mean_dice` `metrics.py/mean_iou` and `metrics.py/mean_fscore` function return value from tuple to dict.
2. the returned dict contain the metrics name to generate the summary data and print log.

**Comment by MengzhangLI** [comment]
It is an excellent suggestion and great PR.

I will close it but feel free to re-open it anytime you want.

Best,
