### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by lyc1995452-star** [open-mmlab/mmsegmentation#43]
你好，我想知道我是只有一张显卡应该如何训练，--resume-from ${CHECKPOINT_FILE}: Resume from a previous checkpoint file.这是要我先下载预训练模型吗？我该如何使用不同的网络结构进行不同的训练呢？

**Comment by xvjiarui** [comment]
Hi @lyc1995452-star 
Please use English or English/Chinese for issue. 
Yes. You need to download the pre-trained weight first. And to fine-tune on your own dataset, you need to use `--load-from`.
