### ISSUE TITLE
confuse about usage of mmsegmentation

### ISSUE THREAD

**Issue by bladesaber** [open-mmlab/mmsegmentation#431]
Dear everyone:
    Hi, it seems that parameter num_classes in the model config should be added 1 because of the background label. But I find that in the mmsegmentation/config/_base_/models, the num_classes of all the model config is 19 for cityscape data set, so I am confuse whether I misunderstand. I meet this question is when I used the num_classes without background include in custom dataset. And then I find the result of inference, there is no any pixel is background.

Thanks for all your wonderful work of mmsegmentation package.

**Comment by xvjiarui** [comment]
Hi @bladesaber 
In cityscapes, there is no background class. There are some ignored pixel indeed. See [here](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py#L62) for more details.
