### ISSUE TITLE
How to set the mask thresold?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#434]
Hi dear authors
Sorry to bother you.

I want to set a threshold for the mask predicted by mmseg, like the test pipeline in mmdet, a threshold is set, and those higher than this threshold will be displayed on the mask, and those below this threshold will not be displayed on the mask.  What should I do in mmseg?
Thank you!

**Comment by xvjiarui** [comment]
Hi @zhongqiu1245 
In segmentation, we select argmax class. You may check it out [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L266).

**Comment by zhongqiu1245** [comment]
@xvjiarui Thank you!
