### ISSUE TITLE
Does pytorch2onnx exports also the data test pipeline?

### ISSUE THREAD

**Issue by Brainkite** [open-mmlab/mmsegmentation#439]
I'm currently experimenting with the ONNX exporting function, but it does not seem to include the data pre-processing pipeline such as image resizing. Also I don't know if it includes image stats normalization.
If not, how can I integrate those transformations to the ONNX exportation?

**Comment by xvjiarui** [comment]
Hi @Brainkite 
Transform is not supported yet.

**Comment by Brainkite** [comment]
Then how could I customize the model so I can insert before the backbone a torch module that is going to resize and normalize the  input?
This way, the preprocessing is part of the model and should be integrated in the ONNX version.

**Comment by xvjiarui** [comment]
Hi @Brainkite 
You may change https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py. 
You could add resize operator there.
