### ISSUE TITLE
Config File using HRNet and Point Rend

### ISSUE THREAD

**Issue by rubeea** [open-mmlab/mmsegmentation#441]
Is it possible to combine HRNet backbone with PointRend head? I guess in this case, no FPN neck would be required then right? Can you kindly post a config file for this model?
Thanks a ton.

**Comment by xvjiarui** [comment]
Hi @rubeea 
We haven't tried this. But it is doable. Maybe @xiexinch could post an example here and verify it.

**Comment by rubeea** [comment]
Hi @xvjiarui,
Thanks for your response. Waiting for @xiexinch to post the config file. Thanks a ton :)

**Comment by tanveer6715** [comment]
Hi @rubeea ,
Have you got your config file using HRNet with pointrend?

**Comment by rubeea** [comment]
> Hi @rubeea , Have you got your config file using HRNet with pointrend?

Hi,
No, sorry I didn't explore and experiment with it further. However, if you are working on a problem we can collaborate.

**Comment by tanveer6715** [comment]
hi I open this issue #1386 today. waiting for the contributors and authors response. I am not sure if it is supported by mmsegmentation.
