### ISSUE TITLE
Excuse me, how to change the backbone to load the pretraining model

### ISSUE THREAD

**Issue by ly19970621** [open-mmlab/mmsegmentation#446]
I added an attention model to the backbone, which can run without pretraining. However, after loading the pretraining, I need to calibrate it. After studying for several days, I found that I can't find out where to calibrate the model and the pretraining model. Could you tell me the code to calibrate the model and the pretraining model and where to add this code?

**Comment by rubeea** [comment]
I believe this is not possible. Previously, I also added DCN (deformable convs) to my backbone and the pretrained network did not have them. Anyways, I did train the network with my modified BB and the default pretrained network.  If I understand it correctly, one way you can achieve calibration is by training your new network (with attention module) on the pretrained network dataset (ImageNet or COCO etc.) and save the model as the pretrained one, then use that model as pretrained network for fine tuning on your custom dataset.

**Comment by ly19970621** [comment]
> I believe this is not possible. Previously, I also added DCN (deformable convs) to my backbone and the pretrained network did not have them. Anyways, I did train the network with my modified BB and the default pretrained network. If I understand it correctly, one way you can achieve calibration is by training your new network (with attention module) on the pretrained network dataset (ImageNet or COCO etc.) and save the model as the pretrained one, then use that model as pretrained network for fine tuning on your custom dataset.

I have searched whether this method is feasible, and the answer is yes. The method is to find the common layer of the network, reserve the pre training parameters, and then load them into the network. I tried to add this code, but it is not feasible no matter where it is added. The sample code is as follows:
net_dict = model_ft.state_dict()
predict_model = torch.load('resnet18-5c106cde.pth')
state_dict = {k: v for k, v in predict_model.items() if k in net_dict.keys()}#Find the public layer in the network and keep the pre training parameters
net_dict.update(state_dict)#Update pre training parameters to new network layer
model_ft.load_state_dict(net_dict)#Loading pre training parameters

**Comment by xvjiarui** [comment]
Hi @ly19970621 
What do you mean by calibrating? You should be able to load the pre-trained model with load function in MMCV, even if you modified the network arch.

**Comment by ly19970621** [comment]
> 嗨@ ly19970621
> 您的校准是什么意思？即使您修改了网络架构，您也应该能够在MMCV中使用加载功能加载预训练模型。

HI,After modifying the backbone, the prompt does not match the  pre-trained model, and the training result indicates that the  pre-trained model has not been loaded successfully. Then I searched the related questions and said that I need to match the common layer of the backbone and  pre-trained before loading.

**Comment by xvjiarui** [comment]
Hi @ly19970621 
Part of the model is already initialized by pre-trained model in this case.

**Comment by ly19970621** [comment]
> @ ly19970621
> ，您好：在这种情况下，模型的一部分已经由预训练模型初始化。

Yes, what I want to ask is where the pre trained function is loaded, and whether it is matched in order or by name?What you're talking about is that the sequential matching failed, so it was initialized. What I need is that after the attention model is added to the backbone, layers other than attention model can load the pre-trained model. How to load by name matching?

**Comment by xvjiarui** [comment]
Hi @ly19970621 
It is matched by name. 
For example, if your model has key A and B. And your pre-trained model has key A. Then B is initialized by default method. A is loaded from pre-train model.

**Comment by ly19970621** [comment]
> Hi @ly19970621
> It is matched by name.
> For example, if your model has key A and B. And your pre-trained model has key A. Then B is initialized by default method. A is loaded from pre-train model.



> Hi @ly19970621
> It is matched by name.
> For example, if your model has key A and B. And your pre-trained model has key A. Then B is initialized by default method. A is loaded from pre-train model.

What and where is the function for this operation?

**Comment by xvjiarui** [comment]
It is implemented by the default load function, with `strict=False`.

**Comment by zhongqiu1245** [comment]
@xvjiarui hi
Do you mean that the above effect can be achieved by setting strict=False ？

**Comment by xvjiarui** [comment]
Yes.

**Comment by ly19970621** [comment]
> 是的。

The default is false？Is it in mmcv/runner/checkpoint.py?

**Comment by MengzhangLI** [comment]
Here is tutorial of [add_backbone](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_models.md#add-new-backbones), hoping it is helpful to you.

Although difference between original backbone and modified backbone, just as @xvjiarui mentioned, part of weights of parameters whose keys could also be found by config file would still be loaded. But we do not know whether those part of pre-trained parameters would help model performance.

Best,

**Comment by das-ankur** [comment]
@MengzhangLI Hey, can you post the link again. previous link is unreachable now

**Comment by MengzhangLI** [comment]
> @MengzhangLI Hey, can you post the link again. previous link is unreachable now

https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_models.md#add-new-backbones

**Comment by das-ankur** [comment]
> > @MengzhangLI Hey, can you post the link again. previous link is unreachable now
> 
> https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_models.md#add-new-backbones

 Thanks
