### ISSUE TITLE
Bug on [.github/workflows] installing mmcv-full==latest+torch1.3.0+cpu

### ISSUE THREAD

**Issue by daavoo** [open-mmlab/mmsegmentation#447]
**Describe the bug**

The `build` workflow fails for torch 1.3.0 version:

https://github.com/open-mmlab/mmsegmentation/runs/2220532295?check_suite_focus=true

 Because of how the install command is invoked:

https://github.com/open-mmlab/mmsegmentation/blob/master/.github/workflows/build.yml#L80

**Reproduction**

1. What command or script did you run?

    ```shell
    pip install mmcv-full==latest+torch1.3.0+cpu -f https://download.openmmlab.com/mmcv/dist/index.html
    ```

**Error traceback**

If applicable, paste the error trackback here.

```
Looking in links: https://download.openmmlab.com/mmcv/dist/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full==latest+torch1.3.0+cpu
```

**Bug fix**

I think the install command used in the workflow should be updated to the format:

```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.3.0/index.html
```

**Comment by xvjiarui** [comment]
Hi @daavoo 
We will upload the missing pre-built soon.
