### ISSUE TITLE
ModuleNotFoundError: No module named 'mmseg.version'

### ISSUE THREAD

**Issue by zhujiesuper** [open-mmlab/mmsegmentation#45]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
You need to install mmseg following the documentation.

**Comment by ausk** [comment]
@hellock In the [mmsegmentation/mmseg/__init__.py](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/__init__.py#L1-L3)
```
from .version import __version__, short_version, version_info

__all__ = ['__version__', 'short_version', 'version_info']
```

But there is not version.py.

Just copy  one from mmdetection.

**Comment by hellock** [comment]
@ausk Please follow the installation guide. `version.py` will be automatically generated when you install it.
