### ISSUE TITLE
Bug: self.CLASSES is None

### ISSUE THREAD

**Issue by igonro** [open-mmlab/mmsegmentation#452]
I'm running an experiment and I'm getting the following error: `TypeError: object of type 'NoneType' has no len()`

https://github.com/open-mmlab/mmsegmentation/blob/b9f9cf6558093c866dcd795185b3100c8ed93039/mmseg/models/segmentors/base.py#L245

This error seems to be legit, because `self.CLASSES` is never defined in the segmentators... In this case, `self` represents an object of type `EncoderDecoder` so, how should it have the CLASSES attribute? It looks like a bug to me...

A possible solution could be replacing `len(self.CLASSES)` with `self.num_classes`.

Please, correct me if I'm wrong with my statements. Thanks.

**Comment by xvjiarui** [comment]
Hi @igonro 
Sorry for the late reply. Could please you provide the command you run?

**Comment by igonro** [comment]
I run it through the following script:

```
import copy
import mmcv
from mmseg import __version__
from mmseg.apis import train_segmentor
from mmseg.datasets import build_dataset
from mmseg.models import build_segmentor

if isinstance(config, str):
    config = mmcv.Config.fromfile(config)

model = build_segmentor(
    config.model, train_cfg=config.train_cfg, test_cfg=config.test_cfg
)

datasets = [build_dataset(config.data.train)]
if len(config.workflow) == 2:
    val_dataset = copy.deepcopy(config.data.val)
    val_dataset.pipeline = config.data.train.pipeline
    datasets.append(build_dataset(val_dataset))

if config.checkpoint_config is not None:
    config.checkpoint_config.meta = dict(
        mmseg_version=__version__,
        config=config.text,
        CLASSES=datasets[0].CLASSES,
        PALETTE=datasets[0].PALETTE,
    )

train_segmentor(
    model,
    datasets,
    config,
    distributed=False,
    validate=True,
    timestamp=timestamp,
    meta=meta,
)
```

This problem may be fixed by manually adding the following line before the `train_segmentor` call:
```
model.CLASSES = datasets[0].CLASSES
```

**Comment by sennnnn** [comment]
Actually, you can find this code in tools/train.py. The CLASSES of model object needs to be set manually.

**Comment by akash-3196** [comment]
> Actually, you can find this code in tools/train.py. The CLASSES of model object needs to be set manually.

Can you show a snippet how to and where to add this code?
