### ISSUE TITLE
An issue about slurm_train.sh

### ISSUE THREAD

**Issue by Jun-jieChen** [open-mmlab/mmsegmentation#454]
Dear sir,

There is one thing I would like to know - whehter the multiple machines need the same Cuda version and Pytorch version when I train the same model?

**Comment by xvjiarui** [comment]
Hi @Jun-jieChen 
Sorry for the late reply. 
Yes. Please use the same environment.

**Comment by Jun-jieChen** [comment]
Thanks for your reply. @xvjiarui 

And then I have the second question want to know: Which file can train the model with multiple machines, whehter `slurm_train.sh` or `dist_train.sh`?

**Comment by xvjiarui** [comment]
You need `slurm_train.sh` for multiple machines.

**Comment by Jun-jieChen** [comment]
OK, do you have any blogs or tutorials about training with multiple machines? I have two machines, each with 4x2080Ti. But I don't know how to let them communicate with each other. Thanks!

**Comment by xvjiarui** [comment]
Hi @Jun-jieChen 
You are using two separate machines? If so, even with multiple machine training, the communication cost between machines will be very high.

**Comment by Jun-jieChen** [comment]
Yes, I have two separate machines connected through LAN. Maybe I can use the high-speed Pcie cable to make them connected, however, I don't know how to make them communicate by using Pytorch. Oops!

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Have you fixed this issue and how?

Best,

**Comment by MengzhangLI** [comment]
Maybe you could check out [rain.md_train-with-multiple-machines](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/train.md#train-with-multiple-machines) for useful guidance.

Best,

**Comment by Jun-jieChen** [comment]
@MengzhangLI Thanks, I willl try it.
