### ISSUE TITLE
Joint Learning

### ISSUE THREAD

**Issue by Hossam-Tarek33** [open-mmlab/mmsegmentation#456]
Hello,
i have added a decode_head that suppose to generate 3 outputs and i need each one of them to be trained "Joint Learning". I am actually lost between the files and I don't know what to modify in order to compute the loss and accuracy for the 3 outputs and not just single output as usual in all the models.

Can anyone please help me ?

Thanks a lot in advance
Hossam

**Comment by xvjiarui** [comment]
Hi @Hossam-Tarek33 
You may consider following the example of DA Head (https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/decode_heads/da_head.py)

**Comment by Hossam-Tarek33** [comment]
Hi @xvjiarui 
Thank you very much
