### ISSUE TITLE
Why does mmseg use IterBasedRunner instead of EpochBasedRunner？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#461]
Hi, dear authers
Sorry to bother you.
Could you tell me why does mmseg use IterBasedRunner instead of EpochBasedRunner？
Are there any benefits to choosing IterBasedRunner?  (Compared to EpochBasedRunner)
What is the reason behind？
Thank you！

**Comment by xpngzhng** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/76

**Comment by zhongqiu1245** [comment]
thank you
