### ISSUE TITLE
What does Mem (GB) means column in configs README's tables?

### ISSUE THREAD

**Issue by KaizerJ** [open-mmlab/mmsegmentation#462]
Hi there!

First of all, thanks for your work, it's very helpful. 

Secondly, what does `Mem (GB)` column means is READMEs from configs folders? In the tables like the following: 

![image](https://user-images.githubusercontent.com/55793536/114041742-b251bd00-987c-11eb-9c74-a40a0d366b08.png)

I've searched in Issues and the docs but didnt find anything.

Thanks.

**Comment by xvjiarui** [comment]
Hi @KaizerJ 
It means training memory.

**Comment by KaizerJ** [comment]
Thanks @xvjiarui
