### ISSUE TITLE
dmnet checkpoints link is valid

### ISSUE THREAD

**Issue by KangolHsu** [open-mmlab/mmsegmentation#470]
dmnet checkpoints link is valid,msg is below:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>You have no right to access this object because of bucket acl.</Message>
<RequestId>6071AD384EBCCF4B42985A95</RequestId>
<HostId>download.openmmlab.com</HostId>
</Error>

**Comment by KaizerJ** [comment]
I assume that you mean that the link is invalid.

I'm having the same trouble, can't download dmnet trained on ADE20K checkpoints.

**Comment by Junjun2016** [comment]
Hi @KangolHsu and @KaizerJ 
Sorry for the late reply and we will fix it ASAP.

**Comment by MengzhangLI** [comment]
Done.

Please check it out.
