### ISSUE TITLE
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

### ISSUE THREAD

**Issue by Jing-W98** [open-mmlab/mmsegmentation#472]
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by xvjiarui** [comment]
Hi @Jing-W98 
What command did you run?

**Comment by Jing-W98** [comment]
I run the demo.py by"
python demo/image_demo.py demo/demo.png configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py \
    checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth --device cuda:0 --palette cityscapes "

**Comment by xvjiarui** [comment]
Are you running from a computer with GUI or not?

**Comment by Jing-W98** [comment]
No, I run it with Mobaxterm on Linux.

**Comment by xvjiarui** [comment]
Hi @Jing-W98 
You should check if your xserver is correctly installed. You may try some simple `plt.plot`. If it fails, you may try to re-install xserver.

**Comment by lllz815** [comment]
HI,do you solve this problem,i have the same problem as you now,Can you give me some  suggestion

**Comment by kyre-99** [comment]
I got same problem, it was from opencv-python version problem for me.
My Linux machine's environment is as following:
 pip uninstall opencv-python
 pip install opencv-python==4.3.0.36
 pip list|grep opencv-python
