### ISSUE TITLE
instance segmentation在mmsegmentation还是在mmdetection中？

### ISSUE THREAD

**Issue by jinxiazhangchina** [open-mmlab/mmsegmentation#473]
请问instance segmentation包含在mmsegmentation还是在mmdetection中？

**Comment by sennnnn** [comment]
mmsegmsentation 是专供语义分割的哦, instance segmentation 应该属于 mmdetection 里, 比如 [Mask-RCNN](https://github.com/open-mmlab/mmdetection/tree/master/configs/mask_rcnn) 就在 mmdetection 的仓库里。

**Comment by sennnnn** [comment]
Is there any other problem? @jinxiazhangchina

**Comment by jinxiazhangchina** [comment]
I have no other questions. Thanks a lot for your quick reply. -------- 原始邮件 --------发件人： sennnnn ***@***.***>日期： 2021年4月14日周三 上午10:40收件人： open-mmlab/mmsegmentation ***@***.***>抄送： jinxiazhangchina ***@***.***>, Mention ***@***.***>主    题： Re: [open-mmlab/mmsegmentation] instance segmentation在mmsegmentation还是在mmdetection中？ (#473)
Is there any other problem? @jinxiazhangchina

**Comment by sennnnn** [comment]
> I have no other questions. Thanks a lot for your quick reply. -------- 原始邮件 --------发件人： sennnnn ***@***.***>日期： 2021年4月14日周三 上午10:40收件人： open-mmlab/mmsegmentation ***@***.***>抄送： jinxiazhangchina ***@***.***>, Mention ***@***.***>主 题： Re: [open-mmlab/mmsegmentation] instance segmentation在mmsegmentation还是在mmdetection中？ (#473) Is there any other problem? @jinxiazhangchina —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

I can't understand what this message want to express. Can you reply again?

**Comment by sennnnn** [comment]
If there is not any other problem, I will close this issue.
