### ISSUE TITLE
Abnormal memory footprint while training with evaluation.

### ISSUE THREAD

**Issue by SoyMario** [open-mmlab/mmsegmentation#477]
I try to train fast-scnn using default configs, in  which the train pipeline is set to evaluate every 8000 iterations(total 80000), but after the first evaluation,  it seems that the  the validation process doesn't release the memory it consumes, and eventually the program crashes due to "**OSError: [Errno 12] Cannot allocate memory**" . So I had to cancel evaluation. I have 16GB memory and 16GB swap. Is it a bug or just design like that?  Thanks.

**Comment by SoyMario** [comment]
It seems that it's the "efficient test" feature :)

**Comment by bobopit** [comment]
I have met the same problem, so could you tell me  how to fix the problem?

**Comment by SoyMario** [comment]
> I have met the same problem, so could you tell me  how to fix the problem?

you have to disable evaluation during train or expand the swap of your Linux (but it will make your computer very slow)
