### ISSUE TITLE
How to apply ms+flip for validation set?

### ISSUE THREAD

**Issue by Jun-jieChen** [open-mmlab/mmsegmentation#478]
Hey! 

I would like to know how to apply `ms+flip` for validation set or test set?

Do I need to add some codes in `cityscapes.py` file?

**Comment by xvjiarui** [comment]
Hi @Jun-jieChen 
You may use https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L20

**Comment by Jun-jieChen** [comment]
@xvjiarui 
I see, Thanks!
