### ISSUE TITLE
run test, but do not get predicted png

### ISSUE THREAD

**Issue by rock4you** [open-mmlab/mmsegmentation#479]
./tools/dist_test.sh configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py \
    checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth \
    4 --format-only --eval-options "imgfile_prefix=./pspnet_test_results"

do not get the dir and the png

**Comment by Magic-Ha** [comment]
same issure！

**Comment by ganyz** [comment]
> me too
I understand, in tools/test.py

if args.format_only:
        dataset.format_results(outputs, **kwargs)

the cityscape dataset has achieved the function format_results. （see the mmseg/datasets/cityscapes.py)
but the ade20k dataset class hasn't achieved the format_results. ( None in mmseg/datasets/ade.py)
So you have to write the codes yourself for ade dataset.

**Comment by xvjiarui** [comment]
Fixed in #544

**Comment by sennnnn** [comment]
When training, we set reduce_zero_label=True. So, the label value range is from 0-149. But the label value range of test set if from 0-150. So, we add 1.

**Comment by sennnnn** [comment]
> > Fixed in #544
> 
> Thank you!
> In addition, I have a question in the new 'ade.py'
> 
> ```
>        if len(result.shape) == 2:
>             # print(result.shape)
>             png_filename = osp.join(imgfile_prefix, f'{basename}.png')
> 
>             result = result + 1
> 
>             output = Image.fromarray(result.astype(np.uint8))
>             output.save(png_filename)
>             result_files.append(png_filename)
> ```
> 
> Why the result should add 1 ?
> @xvjiarui Thank you! :>

When training, we set reduce_zero_label=True. So, the label value range is from 0-149. But the label value range of test set if from 0-150. So, we add 1.

**Comment by sennnnn** [comment]
If there aren't any other problems. I will close this issue.
