### ISSUE TITLE
where is "/nfs/xxxx/psp_r50_512x1024_40ki_cityscapes"? and what does it mean?  when i run --line 14: srun: command not found

### ISSUE THREAD

**Issue by zhujiesuper** [open-mmlab/mmsegmentation#48]

**Comment by xvjiarui** [comment]
Hi @zhujiesuper 
Please use [error report template](https://github.com/open-mmlab/mmsegmentation/blob/master/.github/ISSUE_TEMPLATE/error-report.md).

**Comment by zhujiesuper** [comment]
sorry，i can not find what i want





------------------ Original ------------------

**Comment by hellock** [comment]
Please use the `error report` template, otherwise we cannot help.
