### ISSUE TITLE
Implementation of LR-ASPP

### ISSUE THREAD

**Issue by Shiming94** [open-mmlab/mmsegmentation#480]
Hey,

I try to use the LR-ASPP MobileNetV3 for a segmentation task. But your implementation of LR-ASPP seems different from the original design of the MobileNetV3.

Why you adopt this implementation? Do you have some other references? How will the performance be improved through this implementation?

Best 
Shiming

**Comment by xvjiarui** [comment]
Hi @Shiming94 
Could you illustrate the difference?

**Comment by Shiming94** [comment]
Hi Jiarui,

The main difference is:

the implementation of the original design uses one shortcut from the 1/8 resolution feature map, while your implementation uses two shortcuts from, respectively, 1/4 resolution feature map and 1/2 resolution feature map.

Best,
Shiming

**Comment by xvjiarui** [comment]
Hi @Shiming94 
I just checked. We also referred to [this repo](https://github.com/ekzhang/fastseg) for implementation details.
