### ISSUE TITLE
fastscnn RuntimeError!

### ISSUE THREAD

**Issue by jacob081** [open-mmlab/mmsegmentation#481]
When I used the fastscnn model, and I found somemistake, such as 'RuntimeError: fast_scnn_4x8x80k_lr0.12_cityscapes-f5096c79.pth is a zip archive'.  Should I how to solve this problem or the model is error itself?

**Comment by sennnnn** [comment]
The scripts may be run on a pytorch version older than v1.6.0. After pytorch v1.6.0, the torch.save() will save file in .zip format.

**Comment by sennnnn** [comment]
If there is no response, I will close this issue. You can try to change your pytorch version.
