### ISSUE TITLE
show_dir is different with single gpu and multi gpus

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#484]
if not distributed:
        model = MMDataParallel(model, device_ids=[0])
        outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,  # with show dir
                                  efficient_test, args.opacity)
    else:
        model = MMDistributedDataParallel(
            model.cuda(),
            device_ids=[torch.cuda.current_device()],
            broadcast_buffers=False)
        outputs = multi_gpu_test(model, data_loader, args.tmpdir,  # without show dir
                                 args.gpu_collect, efficient_test)

Hi, why can't saving image be used when using multi GPU?

**Comment by jianlong-yuan** [comment]
Any news?

**Comment by sennnnn** [comment]
When we use multiple GPUs to test, we usually deploy our codes on server which may not have GUI to show result.
