### ISSUE TITLE
How to use multiple losses

### ISSUE THREAD

**Issue by liwensheng2020** [open-mmlab/mmsegmentation#486]
Hello,
       Are there some examples for using multiple losses? I set the following codes to use multiple losses, but there occured an Error: forward() got an unexpected keyword argument 'weight'.

decode_head=dict(
                               loss_decode=[dict(type='DiceLoss', loss_weight=0.5), 
                                                      dict(type='CrossEntropyLoss', loss_weight=0.5)]
))

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Seems like you pass a parameters `weight` in `loss_decode` dict but from your description I do not find it.

Your setting seems not wrong thus detailed bug/error information are needed.

Here is tutorial of [add-new-loss](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_models.md#add-new-loss).

Best,

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Multiple losses is not supported yet. We plan to support it ASAP.

Best,

**Comment by MengzhangLI** [comment]
Hi, @liwensheng2020 

Right now MMSegmentation does not support multiple loss officially (but it is on the way).

You could just git clone my branch here: https://github.com/open-mmlab/mmsegmentation/pull/818 . My implementation is based on latest code. Thus you shall meet little problems. 

Best,
