### ISSUE TITLE
 work_dirs/SETR_MLA_480x480_80k_pascal_context_bs_8_MS.py/latest.pth is not a checkpoint file

### ISSUE THREAD

**Issue by miaochunle** [open-mmlab/mmsegmentation#489]
Thanks for your error report and we appreciate it a lot.

**Comment by sennnnn** [comment]
Sorry, I don't understand what your problem is. Can you explain it with more details?

**Comment by sennnnn** [comment]
If there is no response, I will close this issue. The offcial support of SETR will come soon.
