### ISSUE TITLE
where is the auxiliary_head added to total model?

### ISSUE THREAD

**Issue by hasayake007** [open-mmlab/mmsegmentation#503]
for example deeplabv3+

**Comment by sennnnn** [comment]
It depends on the arg: in_index. Backbone will pass multiple stage outputs. Head use arg: in_index and function: _transform_inputs() to extract input from backbone output.

**Comment by sennnnn** [comment]
If there is no any other problem, we will close this issue.

**Comment by zyuanbing** [comment]
@sennnnn I noticed that the config file do not specify the channel number of backbones due to the size inclusivity of CNNs, so do you mean _decode_head_ and _auxiliary_head_ are image size awared?
Thanks in advance.

**Comment by StevenAZy** [comment]
Thanks for your contributions to this excellent work!
I do not know why adding an auxiliary_dead?  Normally, A Encoder_Decoder structure has a single encoder and decoder module. So I have no idea how to deal with the outputs of auxiliary_head. Do I need to concatenate the outputs of decoder_head and auxiliary_head or do other operations on the outputs of auxiliary_head?

**Comment by hasayake007** [comment]
> Thanks for your contributions to this excellent work!
> I do not know why adding an auxiliary_dead? Normally, A Encoder_Decoder structure has a single encoder and decoder module. So I have no idea how to deal with the outputs of auxiliary_head. Do I need to concatenate the outputs of decoder_head and auxiliary_head or do other operations on the outputs of auxiliary_head?
The aim of auxiliary_dead is to achieve deep-supervised, which is a common-used tricks for boosting the performance.  Usually, You can directly ignore the output of the auxiliary_header and use only the outputs of decoder_head when inference.

**Comment by hasayake007** [comment]
The aim of auxiliary_dead is to achieve deep-supervised, which is a common-used tricks for boosting the performance.  Usually, You can directly ignore the output of the auxiliary_header and use only the outputs of decoder_head when inference.

**Comment by ChenJiangxi** [comment]
Thank you for your powerful framework!
I have a question about the auxiliary decoder. For a auxiliary FCNdecoder to HRNet-w48, if I set `in_index = [0,1,2]`, and  `in_channels=[48,96,192]`, does that mean the FCNdecoder get the output from stage3 of HRNet-w48?
