### ISSUE TITLE
What is the aug.txt of Pascal voc 2012?

### ISSUE THREAD

**Issue by MrDavinci** [open-mmlab/mmsegmentation#504]
FileNotFoundError: PascalVOCDataset: [Errno 2] No such file or directory:'data/VOCdevkit/VOC2012\\ImageSets/Segmentation/aug.txt'

I just arranged the Pascal data path as the document, but I got this error, what is this file?

**Comment by xiexinch** [comment]
Hi @MrDavinci 
Did you run the command to process the dataset?  See [document](https://mmsegmentation.readthedocs.io/en/latest/dataset_prepare.html#pascal-voc).

**Comment by MrDavinci** [comment]
I run the coverting code, and successfully prepare the dataset.
But, when start training by :
python tools\train.py configs\deeplabv3\deeplabv3_r50-d8_512x512_20k_voc12aug.py --gpus 1

The new error occured:
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by xiexinch** [comment]
You may check this issue #235 .

**Comment by MrDavinci** [comment]
Cow Beer.
跑起来了
非常感谢

**Comment by weiqingtangx** [comment]
> Cow Beer. 跑起来了 非常感谢

兄弟，如何解决的，遇到了同样的问题。

**Comment by duduzai2019** [comment]
> > Cow Beer. 跑起来了 非常感谢
> 
> 兄弟，如何解决的，遇到了同样的问题。

兄弟请问怎么解决

**Comment by xiexinch** [comment]
> > > Cow Beer. 跑起来了 非常感谢
> > 
> > 
> > 兄弟，如何解决的，遇到了同样的问题。
> 
> 兄弟请问怎么解决


你是单卡就把syncbn改成bn
或者用dist_train.sh脚本
```shell
sh ./tools/dist_train.sh configs/xxx 1
```

**Comment by duduzai2019** [comment]
> 

![image](https://user-images.githubusercontent.com/96464964/187583161-b0653b82-c36d-4e8b-a466-1b414eb15d90.png)
xi'o
兄弟你好，我下载的数据集没有VOCaug这个文件夹
报错如下
![image](https://user-images.githubusercontent.com/96464964/187583354-35459902-bcbe-435b-9697-ad5d1c12a9a8.png)

**Comment by xiexinch** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/96464964/187583161-b0653b82-c36d-4e8b-a466-1b414eb15d90.png) xi'o 兄弟你好，我下载的数据集没有VOCaug这个文件夹 报错如下 ![image](https://user-images.githubusercontent.com/96464964/187583354-35459902-bcbe-435b-9697-ad5d1c12a9a8.png)

你看我们文档写的那个[链接](http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz)呀，还要下载一个增强数据集，再跑一下我们的脚本才可以开始训练。

**Comment by duduzai2019** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/96464964/187583161-b0653b82-c36d-4e8b-a466-1b414eb15d90.png) xi'o 兄弟你好，我下载的数据集没有VOCaug这个文件夹 报错如下 ![image](https://user-images.githubusercontent.com/96464964/187583354-35459902-bcbe-435b-9697-ad5d1c12a9a8.png)
> 
> 你看我们文档写的那个[链接](http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz)呀，还要下载一个增强数据集，再跑一下我们的脚本才可以开始训练。

首先感谢兄弟的回答，现在已经可以成功训练
还想问一个问题：我看了一下，增加数据集里面的文件是mat格式
我想把自己数据集转换成voc格式，但是不知道自己数据集怎么制作这种mat格式对应的文件
![image](https://user-images.githubusercontent.com/96464964/187587422-600ab942-8598-443b-862f-5c8153723a43.png)

**Comment by xiexinch** [comment]
Hi @duduzai2019,
这个我没了解过，我一般做成cityscapes那种格式，直接把mask存为图片，感觉比较简单。

**Comment by duduzai2019** [comment]
> Hi @duduzai2019, 这个我没了解过，我一般做成cityscapes那种格式，直接把mask存为图片，感觉比较简单。

是的，我之前也是转成cityscapes数据集进行训练
但是这次我用百度的eiseg标注了两百张数据集，发现转不了cityscapes格式！！！

**Comment by xiexinch** [comment]
> > Hi @duduzai2019, 这个我没了解过，我一般做成cityscapes那种格式，直接把mask存为图片，感觉比较简单。
> 
> 是的，我之前也是转成cityscapes数据集进行训练 但是这次我用百度的eiseg标注了两百张数据集，发现转不了cityscapes格式！！！

或许可以试一下我们提供的标注工具 :) 
https://github.com/open-mmlab/labelbee-client

**Comment by duduzai2019** [comment]
> 

非常感谢您提供的标注工具，想问一下LabelBee标注出来的图片可以转换成cityscape格式在mmsegmentation中训练吗
