### ISSUE TITLE
Pascal Context or Pascal Context_59

### ISSUE THREAD

**Issue by Jun-jieChen** [open-mmlab/mmsegmentation#517]
Excause me, 

I would like to ask, what's the diffierence between `Pascal Context` and `Pascal Context 59`?

Thanks.

**Comment by sennnnn** [comment]
Actually, Pascal Context dataset contains almost 459 classes. But, many of the object categories of this dataset are too sparse. Therefore, a subset of 59 frequent classes are usually selected for use. When using 59 classes subset, other classes are seen as background. Pascal Context will consider background class. Pascal Context 59 will not consider background class.

**Comment by sennnnn** [comment]
In detail, the model trained and evaluated on Pascal Context will try to predict 59 frequent classes with 1 background class and the model output num_classes is 60. However, the model trained and evaluated on Pascal Context will just try to predict 59 frequent classes and the model output num_classes is 59.

**Comment by Jun-jieChen** [comment]
@sennnnn 
Thanks for your reply.
