### ISSUE TITLE
[UNet] Cannot download checkpoint and log

### ISSUE THREAD

**Issue by Cliu2** [open-mmlab/mmsegmentation#527]
Hi,

I tried to download the checkpoint and corresponding log file of UNet at [here](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/unet). While the other models can be viewed, the first row of the table, `UNet-S5-D16 FCN` for DRIVE returns 'AccessDenied' error. Would you please check with that? Thanks.

URL: https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_64x64_40k_drive/fcn_unet_s5-d16_64x64_40k_drive-20201223_191051.log.json

Result:
![image](https://user-images.githubusercontent.com/21998065/116856844-5f2a1a80-ac2e-11eb-8e30-475c0263a86d.png)

Thank you for your help

**Comment by aikeyz** [comment]
check [https://github.com/open-mmlab/mmsegmentation/blob/master/configs/unet/README.md](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/unet/README.md) please, if it helps.

**Comment by Cliu2** [comment]
@aikeyz Thank you for the reply. But I follow the exact link as yours, and the above screenshot in the problem description is what I got when I try to download the first model. Does it work on your machine? 

![image](https://user-images.githubusercontent.com/21998065/118766685-592f6d00-b8af-11eb-8d6f-6bfc5b93869a.png)

**Comment by aikeyz** [comment]
nope, not this model, the link is invalid

Lcon7 ***@***.***> 于2021年5月19日周三 下午2:35写道：

**Comment by shireen1512** [comment]
same problem with HRnet.

**Comment by Junjun2016** [comment]
Hi @Cliu2, @aikeyz,and @shireen1512 
Sorry for the late reply.
We will check and fix it ASAP.
