### ISSUE TITLE
Could you give a config.py to explain how to use OHEM_pixel_sampler it?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#537]
Could you give a config.py to explain how to use OHEM_pixel_sampler it?
Thank you!

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Please check the tutorial [training_tricks](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/training_tricks.md#online-hard-example-mining-ohem).

Hoping it is helpful to you.

Best,
