### ISSUE TITLE
Doubts about deeplabv3plus and FCN in mmseg

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#539]
Hi dear author
Sorry to bother you.
The `deeplabv3plus` of `mmseg` is not the same as the official `deeplabv3plus`. It is found that the `deeplabv3plus` of `mmseg` does not have the same decoder structure(like Unet), right?
And FCN and Unet in mmseg also have no decoder structure.

**Comment by caodroid** [comment]
hi, the decoder of deeplabv3p is not like Unet， in the offcial paper ,the final decoder is that only the 1-th layer  is concatenated after a 1x1 convolution， which the in_channels =256, out_channels = 48. you can read it again for more details.

**Comment by zhongqiu1245** [comment]
@caodroid Hi
Sorry, I made a mistake. The decoder part of mmseg's deeplabV3plus is similar to the original text.
But mmseg's FCN is different. mmseg's `fcn_head.py` has no upsampling process, only two convolution operations, which are partly different from the original FCN.
Am I right？

**Comment by caodroid** [comment]
@zhongqiu1245 是的，在原文中FCN更像是Unet结构，连接了2，3 层的特征输出，但是大部分论文中的FCN就是值什么也不连接的，这个可以在DAnet和PSPnet里证明。

**Comment by zhongqiu1245** [comment]
@caodroid 你好，感谢你的回复！
请问那种不加decoder的FCN的效果会比加了decoder的FCN的差多少？

**Comment by caodroid** [comment]
> @caodroid 您好，感谢您的回复！
> 请问那种不加decoder的FCN的效果会比加了decoder的FCN的差多少？

这个就不知道了，加了多层融合的就有点像unet了。

**Comment by zhongqiu1245** [comment]
> > @caodroid 您好，感谢您的回复！
> > 请问那种不加decoder的FCN的效果会比加了decoder的FCN的差多少？
> 
> 这个就不知道了，加了多层融合的就有点像unet了。

谢谢
