### ISSUE TITLE
How can I add two encoders in a network? I want to encode RGB images and thremal images respectively.

### ISSUE THREAD

**Issue by 18779042442** [open-mmlab/mmsegmentation#541]

**Comment by zabir-nabil** [comment]
How did you solve this? @18779042442

**Comment by 18779042442** [comment]
> How did you solve this? @18779042442

I just used two backbones, and overwrote the init_weights(). You can register a new backbone, and then define two backbones, such as ResNet. All you need to modify is the 'in_channels'. Make sure pretrained models are loaded into two backbones.
