### ISSUE TITLE
weights of DMNet?

### ISSUE THREAD

**Issue by Anikily** [open-mmlab/mmsegmentation#548]
I can't download the weights of DMNet, could you help me?

**Comment by Junjun2016** [comment]
Hi @Anikily 
We will fix it ASAP.

**Comment by MengzhangLI** [comment]
Prepare to fix it.
Please check its related PR: https://github.com/open-mmlab/mmsegmentation/pull/660

Best,

**Comment by MengzhangLI** [comment]
Hi, @Anikily 

This problem is fixed, we just checked several new links of DMNet model and their results is correct.

Please, check it out.
z
