### ISSUE TITLE
CityscapesDataset - Deeplabv3+ :   mmseg - INFO - Loaded 0 images 

### ISSUE THREAD

**Issue by manhph2211** [open-mmlab/mmsegmentation#551]
Hello, I'd used Deeplabv3+ (with dataset_type = 'CityscapesDataset') to train my own dataset, and I've met this error:  `mmseg - INFO - Loaded 0 images`. I think it's about the `ann_dir` in my config file, but I don't know what kinds of files should be inside the `ann_dir`. Currently, I just have JSON file in coco format :confused:  

Could anyone help me with this?  Thanks in advance!

**Comment by sennnnn** [comment]
You can check [this file](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/cityscapes.py). We assign path of dataset in the data attribute of this config. Furthermore, you may need to check the folder structure of your cityscapes dataset. It follows this structure:

```
data
├── cityscapes
│   ├── leftImg8bit
│   │   ├── train
│   │   ├── val
│   ├── gtFine
│   │   ├── train
│   │   ├── val
```

**Comment by manhph2211** [comment]
Many thanks for your help @sennnnn. Actually, I got problems with the annotation file as well. I don't know what's kind of format for the annotation file in my case. Could you help me with that :love_letter:

**Comment by sennnnn** [comment]
You are welcome. We use [tools/convert_dataset/cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/convert_datasets/cityscapes.py) to generate train seg map from polygon.json.

**Comment by sennnnn** [comment]
If there is no any other problems. I will close this issue.
