### ISSUE TITLE
compatibility with different MMCV versions

### ISSUE THREAD

**Issue by Hrayo712** [open-mmlab/mmsegmentation#555]
Hi,

Thanks for the great work.

I was wondering if you have a list with the different MMSegmentation versions, and their compatibility across different MMCV versions. 

I am looking for something like this (example from MMClassification):
![image](https://user-images.githubusercontent.com/34102313/118443754-94357300-b6ec-11eb-863c-5ed594dc4f6f.png)

Thanks in advance!

**Comment by sennnnn** [comment]
Hi, you can check get_started.md now. We add this compatiable table yesterday.

**Comment by Hrayo712** [comment]
Thanks!
