### ISSUE TITLE
Where can we download the pretrained model weights?

### ISSUE THREAD

**Issue by aikeyz** [open-mmlab/mmsegmentation#557]
Hi everyone, 

I'm new to mmsegmentation, honestly it's really cool. But I have a question: where can we download these pretrained model weights? e.g: deeplabv3plus_r50-d8_512x1024_80k_cityscapes

I found that there are a lot of model configs, but I have no clue where the checkpoints are. Can anyone help? Thanks all.

**Comment by xvjiarui** [comment]
Hi @aikeyz 
You may check the README.md of each config folder.

**Comment by aikeyz** [comment]
> Hi @aikeyz
> You may check the README.md of each config folder.

Thanks a lot!
