### ISSUE TITLE
How to use mask image for mmsegmentation

### ISSUE THREAD

**Issue by tvkarthik05** [open-mmlab/mmsegmentation#559]
Hi,

This is a great package and i have been trying to explore this for one of my use case. I have a few questions,

1) I could not find any examples for images which contain mask rather than the regions.txt file and layers.txt file. Is it possible to use mask data i.e. .tif images which contain the mask for training the model i.e. something like the image given below where the mask is kept in the labels folder and the original image in the train folder?

![image](https://user-images.githubusercontent.com/19267747/118666002-7103e400-b810-11eb-8fe2-1c8abff3e1cf.png)

2) Also in my case i have only one class, but when i try with just one class the output appears like this,
![image](https://user-images.githubusercontent.com/19267747/118670036-e624e880-b813-11eb-8035-5badeb7c39d5.png)

Any help on this is highly appreciated!

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Seems like it is brain semgnetation task and modality is MR. Maybe it is BraTs.

A1: You would better transform the format from .tif/.nii/.dcm to png. Right now MMSegmentation only support natural images such as png file. Please check [CHASE_DB1_data_preparation_doc](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/dataset_prepare.md#chase-db1). 

Just follow its folder orgnization and data format, and I have to mention right now the whole framework only support 2D image.

A2: Seems like your config file is not correct or your data folder is not correct, I can not judge at this time.

My suggestion is:
(1) Follow default data preparation process.
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/dataset_prepare.md
(2) Reading documents of [config](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/config.md), [customize dataset](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md) and [data pipeline](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/data_pipeline.md).
