### ISSUE TITLE
Custom Dataset Format

### ISSUE THREAD

**Issue by zhengjie6** [open-mmlab/mmsegmentation#563]
Hello, I am intending to train on custom dataset and I have read the documentation. I would like to check what is the custom dataset format and which tool i should use to prepare my dataset?

Thanks.

**Comment by xvjiarui** [comment]
Hi @zhengjie6 
You may have the same file structure as cityscapes dataset.

**Comment by zhengjie6** [comment]
Thanks @xvjiarui for the answer. Do you have a tutorial on how to do that from labelme?

**Comment by Adarine99** [comment]
> Thanks @xvjiarui for the answer. Do you have a tutorial on how to do that from labelme
convert json file to png label,you can use labelme2voc.py or labelme2coco.py 
https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation

**Comment by zhengjie6** [comment]
Thanks
