### ISSUE TITLE
Load a web-camera video feed and do segmentation on that.

### ISSUE THREAD

**Issue by zhengjie6** [open-mmlab/mmsegmentation#564]
Hi, I am looking at using this for live video and would like to know how to be able to use a web camera video to do segmentation.

**Comment by xvjiarui** [comment]
Hi @zhengjie6 
Sorry. Welcome demo is not supported yet. You could modify the code according to https://github.com/open-mmlab/mmdetection/blob/master/demo/webcam_demo.py

**Comment by zhengjie6** [comment]
Thank you @xvjiarui I manage to get them to work. However, the fps seems very slow as compared to the benchmark. Is it running on my CPU or GPU?

**Comment by PardisTaghavi** [comment]
@zhengjie6 did you solve this issue?
