### ISSUE TITLE
SyncBN v.s. torch.nn.SyncBatchNorm.convert_sync_batchnorm()

### ISSUE THREAD

**Issue by zwei-adobe** [open-mmlab/mmsegmentation#565]
If I plan to use SyncBN in my model, I found two ways when using mmsegmentation package. The first way is to directly set all `norm-cfg` to SyncBN, the second is to go ahead with BN but after the whole model if defined, I can use `torch.nn.SyncBatchNorm.convert_sync_batchnorm()`. 
My question is: will they lead to the same behavior?

**Comment by xvjiarui** [comment]
Hi @zwei-adobe 
Yes. They are the same.
