### ISSUE TITLE
Error when running Tutorial with only 2 classes

### ISSUE THREAD

**Issue by joshneighbor** [open-mmlab/mmsegmentation#566]
I noticed when playing around with the Tutorial that if I truncate the classes and palette to only two classes I get a RuntimeError: CUDA error: an illegal memory access was encountered. I am trying to implement my own dataset with only two class and also hitting this error. Is there something about only 2 classes that doesn't work. If I set it to 3 classes it does seem to train. 
Thanks!

classes = ('sky', 'tree')
palette = [[128, 128, 128], [129, 127, 38]]
cfg.model.decode_head.num_classes = 2
cfg.model.auxiliary_head.num_classes = 2

/root/miniconda/envs/pytorch3d/lib/python3.7/site-packages/mmcv/utils/misc.py:304: UserWarning: "flip_ratio" is deprecated in `RandomFlip.__init__`, please use "prob" instead
  f'"{src_arg_name}" is deprecated in '
2021-05-20 21:05:01,587 - mmseg - INFO - Loaded 572 images
/home/mmsegmentation/mmseg/models/builder.py:61: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
2021-05-20 21:05:02,349 - mmseg - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2021-05-20 21:05:04,498 - mmseg - INFO - Loaded 572 images
2021-05-20 21:05:04,499 - mmseg - INFO - load checkpoint from checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
2021-05-20 21:05:04,661 - mmseg - WARNING - The model and loaded state dict do not match exactly

size mismatch for decode_head.conv_seg.weight: copying a param with shape torch.Size([19, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 512, 1, 1]).
size mismatch for decode_head.conv_seg.bias: copying a param with shape torch.Size([19]) from checkpoint, the shape in current model is torch.Size([2]).
size mismatch for auxiliary_head.conv_seg.weight: copying a param with shape torch.Size([19, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 256, 1, 1]).
size mismatch for auxiliary_head.conv_seg.bias: copying a param with shape torch.Size([19]) from checkpoint, the shape in current model is torch.Size([2]).
2021-05-20 21:05:04,667 - mmseg - INFO - Start running, host: root@6bf0b24db596, work_dir: /home/mmsegmentation/work_dirs/tutorial
2021-05-20 21:05:04,668 - mmseg - INFO - workflow: [('train', 1)], max: 1000 iters

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-7bdd94941119> in <module>
     24 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
     25 train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
---> 26                 meta=dict())

/home/mmsegmentation/mmseg/apis/train.py in train_segmentor(model, dataset, cfg, distributed, validate, timestamp, meta)
    114     elif cfg.load_from:
    115         runner.load_checkpoint(cfg.load_from)
--> 116     runner.run(data_loaders, cfg.workflow)

~/miniconda/envs/pytorch3d/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py in run(self, data_loaders, workflow, max_iters, **kwargs)
    128                     if mode == 'train' and self.iter >= self._max_iters:
    129                         break
--> 130                     iter_runner(iter_loaders[i], **kwargs)
    131 
    132         time.sleep(1)  # wait for some hooks like loggers to finish

~/miniconda/envs/pytorch3d/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py in train(self, data_loader, **kwargs)
     58         data_batch = next(data_loader)
     59         self.call_hook('before_train_iter')
---> 60         outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
     61         if not isinstance(outputs, dict):
     62             raise TypeError('model.train_step() must return a dict')

~/miniconda/envs/pytorch3d/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py in train_step(self, *inputs, **kwargs)
     65 
     66         inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
---> 67         return self.module.train_step(*inputs[0], **kwargs[0])
     68 
     69     def val_step(self, *inputs, **kwargs):

/home/mmsegmentation/mmseg/models/segmentors/base.py in train_step(self, data_batch, optimizer, **kwargs)
    151         """
    152         losses = self(**data_batch)
--> 153         loss, log_vars = self._parse_losses(losses)
    154 
    155         outputs = dict(

/home/mmsegmentation/mmseg/models/segmentors/base.py in _parse_losses(losses)
    202                 loss_value = loss_value.data.clone()
    203                 dist.all_reduce(loss_value.div_(dist.get_world_size()))
--> 204             log_vars[loss_name] = loss_value.item()
    205 
    206         return loss, log_vars

RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by xvjiarui** [comment]
Hi @joshneighbor 
You need to modify label to have only 2 classes.

**Comment by wyattoboyd** [comment]
Hi @xvjiarui, can you elaborate on what you mean by label?

**Comment by RoyZhDec** [comment]
> Hi @xvjiarui, can you elaborate on what you mean by label?

It means your gt map should only contain number 0 or 1 in it.

**Comment by Senwang98** [comment]
If your own dataset only have 2 class, that means that your mask only contains 0 or 1. value.
if your dataset have n class, mask contains [0, n-1].
So, you need to convert your mask which is [0,255] to [0,n-1]
