### ISSUE TITLE
How to create a multi input, multi output segmentation model?

### ISSUE THREAD

**Issue by zabir-nabil** [open-mmlab/mmsegmentation#568]
I have a dataset with multi-modal images, I need to predict multiple maps from multiple inputs. How can I do that?

**Comment by xvjiarui** [comment]
Hi @zabir-nabil 
You may need to change the data loading part. In https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/loading.py

**Comment by Junjun2016** [comment]
Hi @zabir-nabil 
Any news?

**Comment by MeowZheng** [comment]
No Response for a long time

**Comment by yyyxs1125** [comment]
any updates?
