### ISSUE TITLE
what does the mean of out_indices,in_channels,in_index,channels ?

### ISSUE THREAD

**Issue by zhujiesuper** [open-mmlab/mmsegmentation#57]
what does the mean of out_indices,in_channels,in_index,channels ?

**Comment by JoyLuo** [comment]
out_indices代表主干网输出的不同阶段特征的索引。比如，resnet有4个block(在mmseg中是4个)，每个block有一个输出，就会构成4个输出

**Comment by zhujiesuper** [comment]
谢啦，能加个好友吗？一起交流，我QQ：６５３７２５２１５



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JoyLuo"<notifications@github.com&gt;; 
发送时间: 2020年8月10日(星期一) 下午4:56
收件人: "open-mmlab/mmsegmentation"<mmsegmentation@noreply.github.com&gt;; 
抄送: "朱一大爱"<653725215@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmsegmentation] what does the mean of out_indices,in_channels,in_index,channels ? (#57)





 
out_indices代表主干网输出的不同阶段特征的索引。比如，resnet有4个block(在mmseg中是4个)，每个block有一个输出，就会构成4个输出

**Comment by zhujiesuper** [comment]
主干网输出的不同阶段特征的索引,其实我真的没弄明白，有推荐的相关博客或者论文吗？

**Comment by JoyLuo** [comment]
> 主干网输出的不同阶段特征的索引,其实我真的没弄明白，有推荐的相关博客或者论文吗？

之前没有解释清楚，我更新了

**Comment by zhujiesuper** [comment]
在哪里解释了呀
