### ISSUE TITLE
Can mmseg support multi-level prediction（like prediction in mmdet)?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#574]
Hi,dear authors
Sorry to bother you
Can mmseg support multi-level prediction（like prediction in mmdet）？
I mean like fpn predict in mmdet, small-scale feature maps are used to predict large targets and large-scale feature maps are used to predict small targets.
Please forgive my bad English.
Thank you!

**Comment by Junjun2016** [comment]
Hi @zhongqiu1245,
That's a really interesting question, I have thought about it.
In object detection task, we can use BBox to define scale, while in semantic segmentation, it is hard to define a scale, maybe we should find or define a metric for the scale of each pixel, e.g. the proportion of pixels of the same category in the local area.

**Comment by zhongqiu1245** [comment]
Hi @Junjun2016 
Thank you for you reply!
I think there are two ways to solve the "metric" problem you mentioned:
  1. If mmseg supports the `coco` data format, we can read in the annotations of `bbox` and `segmention` at the same time, and then assign `GT` to each layer of `FPN` according to the IoU of `bbox` and `GT` (this is the same as object detection, which should be directly transplantable `mmdet` code), after the allocation is completed, use the segmention label for training, like this;
![微信图片_20210601125301](https://user-images.githubusercontent.com/48090608/120268685-dbb92300-c2d8-11eb-9a17-09e6f2cf3627.jpg)
  2. Directly replace the label of `bbox` with the label of `segmention`, calculate the IoU of segmention, and then assign the same as 1.
For 1, in fact, as long as there is a segmention label in the data set, we can directly calculate the bbox information (here bbox can be considered as the circumscribed rectangle of each segmention). So it’s not that important to support the coco data format.
Do you think the above method is feasible?
  It would be great if mmseg can complete this kind of hierarchical prediction, and the accuracy will definitely be greatly improved.
  Because target detection has developed FCOS based on semantic segmentation, semantic segmentation should also learn from the results of target detection, and I think the FPN classification prediction of target detection is worthy of reference for semantic segmentation.

**Comment by Junjun2016** [comment]
@zhongqiu1245 Good ideas.
But there is no instance concept in semantic segmentation, we can not distinguish instance from label mask.
In object detection, the BBox defines the scale of all the pixels in this BBox, which means the pixels in this BBox share the same scale and regress the same BBox. But for semantic segmentation, we need to classify every pixel to a semantic label, there is a difference from object detection. Give an example, one pixel in the center of the human body and the other one near the boundary of the human body, these two pixels share the same BBox and the same category, so they share the same scale for object detection. Are they share the same scale for semantic segmentation? It is hard to say or define, in my opinion, they should belong to different scales. So, I think it is most important to find or define a metric to quantize the scale of each pixel for semantic segmentation.

**Comment by zhongqiu1245** [comment]
Hi @Junjun2016
Thank you for you reply!
What do you mean is that semantic segmentation is much finer than object detection. Such a fine scale will actually cause difficulty in layering?

**Comment by zhongqiu1245** [comment]
However, if the points on the boundary of the human body and the points inside the human body are labeled as "human" when labeling, wouldn't the two points have the same scale?

**Comment by Junjun2016** [comment]
In my opinion, they should belong to different scales.

**Comment by zhongqiu1245** [comment]
thank you
