### ISSUE TITLE
pytorch2torchscript.py needs pytorch>=1.8.0

### ISSUE THREAD

**Issue by CuttlefishXuan** [open-mmlab/mmsegmentation#577]
Why this code needs pytorch>=1.8.0? Specifically, which function/package restricts the version of PyTorch?

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Personally I suggest you upgrade PyTorch >= 1.8.0 to resolve this error. Refer to [doc of useful_tools](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/useful_tools.md):

`Convert to TorchScript (experimental)`

> It's only support PyTorch>=1.8.0 for now.

> This tool is still experimental. Some customized operators are not supported for now.

Right now we do not modify this function for basic usage especially pytorch < 1.8.0, we may add this needs in the future (while no exact timeline) if needed.

Best,
