### ISSUE TITLE
Are there any rotation augmentation in   segmentaion data pipeline?

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#581]
As a beginer of mmsegmentation, i can not find any rotation augmentation code.Can u give me some explanation?

**Comment by zhongqiu1245** [comment]
@MengHao666 Hi
You can use mmseg's albu for a variety of augmentation, and the method of use is similar to mmdet's ablu augmentation methods.
PR is here: https://github.com/open-mmlab/mmsegmentation/pull/392

**Comment by MengHao666** [comment]
Thanks, I will try later.
