### ISSUE TITLE
The model and loaded state dict do not match exactly 

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#582]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
The model and loaded state dict do not match exactly .

**Reproduction**

1. What command or script did you run?

    ```none
    GPUS=8 GPUS_PER_NODE=8 ./tools/slurm_train.sh HA_3D visible configs/ocrnet/my_ocrnet_hr48_256x256_350_my2hands_visible_remote.py

    ```

**Error traceback**
![image](https://user-images.githubusercontent.com/47114466/120747370-7a40c080-c533-11eb-8b08-08364a8e9950.png)

**Comment by xvjiarui** [comment]
Hi @MengHao666 
This is expected behavior for HRNet. These weights are used during image classification pretraining but are ignore during segmentation.

**Comment by MengHao666** [comment]
So could it  be overlooked?

**Comment by xvjiarui** [comment]
Yes.
