### ISSUE TITLE
how can I disable MultiScaleFlipAug when testing?

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#585]
I am a beiginner in mmsegmentation. My code is as follows:

> test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(256, 256),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            # dict(type='Resize', keep_ratio=True),
            dict(type='My_RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

**Comment by xvjiarui** [comment]
Hi @MengHao666 
The multi-scale testing is disabled by default. You don't need to remove MultiScaleFlipAug.

**Comment by MengHao666** [comment]
Do u mean multi-scale testing is disabled by  `# img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],`？I think I  only need `Normalize`,`ImageToTensor`,`Collect`,But must I use `dict(type='MultiScaleFlipAug',` to make it?

**Comment by Junjun2016** [comment]
Hi @MengHao666 
Sorry for the late reply. You can try
```python
type='MultiScaleFlipAug',
img_scale=None,
img_ratios=[1.0, ],
```

**Comment by MengHao666** [comment]
> Hi @MengHao666
> Sorry for the late reply. You can try
> 
> ```python
> type='MultiScaleFlipAug',
> img_scale=None,
> img_ratios=[1.0, ],
> ```

ok , I will try.
