### ISSUE TITLE
Can mmseg integrate object detection on the basis of semantic segmentation?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#588]
Hi, dear authors!
Sorry to bother you
Can mmseg integrate object detection on the basis of semantic segmentation?(**Not Instance Segmentation**)

The idea is this:
Step 1: Similar to object detection, first locate the approximate range of the target (or provide candidate areas)
Step 2: Only perform semantic segmentation on the approximate range (or candidate area) generated in the first step (instead of segmenting the entire image)

Benefits:
1. We can learn from the prior knowledge of object detection to perform semantic segmentation, making the semantic segmentation model richer;
2. Object detection and semantic segmentation can also be unified under a more unified framework, which is convenient for switching;
3. It may also improve the speed of semantic segmentation, because the semantic classification operation of non-target areas has been filtered out in the Step 1, so this part of the time is also saved.

This idea is not as refined as instance segmentation.
This idea only needs to distinguish different types of objects like semantic segmentation, and it does not need to be so refined as to distinguish different individuals of the same species like instance segmentation.
The role of object detection in this idea is only to provide candidate regions.

Finally please forgive my bad English.

Is this idea feasible?

Thank you!

**Comment by zhongqiu1245** [comment]
Any news？

**Comment by xvjiarui** [comment]
Hi @zhongqiu1245 

Thanks for your advice. 
However, it seems that step 2 won't be faster than performing the whole image segmentation. Since we still need to use conventional to slide the whole image.

**Comment by zhongqiu1245** [comment]
Thank you
