### ISSUE TITLE
Output predictions as json format

### ISSUE THREAD

**Issue by kentaroy47** [open-mmlab/mmsegmentation#589]
Thanks for the great repo!

Looking at https://mmsegmentation.readthedocs.io/en/latest/inference.html?highlight=format%20only#test-a-dataset,
there seems to be an option to output the inference results as images.

However, is it possible to output the predictions in a json format?

I've tried pickle output, but it did not show which file it was inferencing..

**Comment by kentaroy47** [comment]
I got around by adding some codes in `test.py` to save the output.
But it will be useful to support outputting predictions like mmdet does.

**Comment by MengzhangLI** [comment]
Hi, thanks for your nice word on MMSegmentation!

I guess json format you mentioned in MMDetection is about bounding boxes, while in segmentation task, usual output of prediction is label with same shape of input images. Thus we do not provide json format option.

Anyway, very happy for your successful customizing your codebase. If more people prefer this json format output in MMSegmentation, we would consider adding it in the next version of it.

Best,

**Comment by Michelvl92** [comment]
I would prefer the have the inference/test predictions in json format just as is usual one in detectron2 or Megvii repos.
I would be nice if it is just as pycocotools it expects the predictions on a dataset as follows: 
```
[{'image_id': 793, 'category_id': 1, 'bbox': [0.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582}, 
{'image_id': 793, 'category_id': 1, 'bbox': [590.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582},
......
{'image_id': 795, 'category_id': 1, 'bbox': [1180.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582}]
```

Is there a possibility to het the predictions in such a format (this is usually built in many frameworks), or how can I implement this easily en quickly by myself?

**Comment by DarrenWong** [comment]
@kentaroy47 can you mind sharing the modification of the test.py about converting to json format? I want to use the prediction as to the initial label of a custom dataset using labelme.
I tried to use a tool (https://github.com/jsbroks/imantics) to convert the point prediction results to polygons but only bitmask supported it. 
https://github.com/open-mmlab/mmsegmentation/blob/17b500f9dff04802d3ab1fe09d4666d38dbe20e5/tools/test.py#L257
