### ISSUE TITLE
If a pixel belongs to more than one category, how should we prepare mask_gt?

### ISSUE THREAD

**Issue by xungeer29** [open-mmlab/mmsegmentation#59]
In my task, some pixels belong to classA and classB, and we can't classify these pixels into a new category, how should we prepare mask_gt in mmseg?

**Comment by xvjiarui** [comment]
Hi @xungeer29 
What do you mean by belonging to classA and classB? Are you implying we are doing multi-label classification? 
If so, what should be desired output?

**Comment by xungeer29** [comment]
Thank you for your great repo.

Simple example: I want to segment the horizontal and vertical lines on the image, but the horizontal lines and vertical lines have intersection points. In this case, the pixels in the intersection area belong to both horizontal and vertical lines.
How do we deal with this case?

In my previous work, the shape of the output in my networks is (N, n_classes, H, W), one channel predicts one class. I don't know how to do in mmseg.

**Comment by xvjiarui** [comment]
Hi @xungeer29 
So in your previous work, the intersection would be with multi-label. 
Currently, mmseg only supports read annotation from images. You may need to write your own pipeline. 
As for loss, you may set `use_signoid=True` in your case.

**Comment by xungeer29** [comment]
Thanks, I will try it.

**Comment by hannachoum** [comment]
> Thanks, I will try it.

Hello, did you suceed to create a pipeline for mulit-label ? i have the same problem as you, my pixels sometimes belongs to several classes... 

Thank you for your help !
