### ISSUE TITLE
RTX 3080 supports

### ISSUE THREAD

**Issue by mhyeonsoo** [open-mmlab/mmsegmentation#590]
Hello,

Thanks for the great sources.
I am not facing issue that my gpu which is RTX 3080 is not comaptible with cuda 10 version.
Is there a way to support this?

I tried to install cuda11.0, but mmseg returned the error after then.

Thanks.

**Comment by MengzhangLI** [comment]
Hi, could you successfully run mmcv?

If not, please check [installation guidance](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/get_started.md#installation) for mmcv installation.

Seems like right now [mmcv](https://github.com/open-mmlab/mmcv) only support **cuda 11.0 && pytorch 1.7**. 
For example:

> pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html

After mmcv successful installation, I guess mmsegmentation will not face errors anymore.

Hoping for your response.

Best,
