### ISSUE TITLE
convert onnx model(pspnet) to tensorrt failed

### ISSUE THREAD

**Issue by Adarine99** [open-mmlab/mmsegmentation#591]
This PR adds tools to convert the ONNX model to TensorRT.
FCN, PSPNet, Deeplabv3, and Deeplabv3+ have been tested.
**But when I convert Pspnet to TensorRT,got this error:**
      Traceback(most recent call last):
           file"onnx2tensorrt.py",line 275,in <module>
                verbose=args.verbose)
           file "onnx2tensorrt.py",line 127,in onnx2tensorrt
                 max_workspase_size=max_workspace_size)
           file"tensorrt_utils.py",line 62,in onnx2trt
      RuntimeError:parse onnx failed:
      In Node 144(parseGraph): INVALID_GRAPH:Assertion failed"ctx->tensors().count(inputName)
Pytorch->1.7.0，tensorRT->7.0.0.11
Thanks~

**Comment by MengzhangLI** [comment]
Hi, I did not meet this error before but I try to answer it.

First, you could try upgrading `onnx-tensorrt` to a proper version and check whether you could fix this error.

The essence of this  issue is some input of the node in your onnx graph does not exist. The onnx graph is not stored in standard format. You could also check whether onnx is valid, i.e., using `torch.onnx.load` to load model and check its format.

You can refer to this issue:
https://github.com/onnx/onnx/issues/2474. 

Best,
