### ISSUE TITLE
ImportError: /home/xxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

### ISSUE THREAD

**Issue by davidjin97** [open-mmlab/mmsegmentation#592]
I use the setup script to install mmsegmentation
``` shell
conda create -n open-mmlab python=3.7 -y
conda activate open-mmlab

conda install pytorch=1.6.0 torchvision cudatoolkit=10.1 -c pytorch
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/index.html
git clone https://github.com/open-mmlab/mmsegmentation.git
cd mmsegmentation
pip install -e .  # or "python setup.py develop"
```
After this, when I run the following verification code,
```Python
from mmseg.apis import inference_segmentor, init_segmentor
import mmcv

config_file = 'configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py'
checkpoint_file = 'checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth'

# build the model from a config file and a checkpoint file
model = init_segmentor(config_file, checkpoint_file, device='cuda:0')

# test a single image and show the results
img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_segmentor(model, img)
# visualize the results in a new window
model.show_result(img, result, show=True)
# or save the visualization results to image files
# you can change the opacity of the painted segmentation map in (0, 1].
model.show_result(img, result, out_file='result.jpg', opacity=0.5)

# test a video and show the results
video = mmcv.VideoReader('video.mp4')
for frame in video:
   result = inference_segmentor(model, frame)
   model.show_result(frame, result, wait_time=1)
```
this error occured.
> ImportError: /home/xxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

**Comment by cxhttt233** [comment]
same

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

The log shows the environment is:

Python 3.7
pytorch=1.6.0 
cuda10.1

Could you tell me your current pytorch and cuda version?
If not match, you could re-install the suitable mmcv version with cuda and pytorch version.
Here is the [link](https://github.com/open-mmlab/mmcv)

===========================SNAPSHOT=========================================
<img width="727" alt="截屏2021-06-23 下午1 21 26" src="https://user-images.githubusercontent.com/24582831/123040716-c4c4a700-d426-11eb-8cbd-42121b56288a.png">

===========================SNAPSHOT=========================================
Best,
