### ISSUE TITLE
typo in the Dockerfile

### ISSUE THREAD

**Issue by BALMASPhilippe** [open-mmlab/mmsegmentation#595]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
In the Dockerfile, there is a typo :  line 19: "RUN git clone https://github.com/open-mmlab/mmsegmenation.git /mmsegmentation"  should be replaced by "RUN git clone https://github.com/open-mmlab/mmsegmentation.git /mmsegmentation"   (a "t" is missing in "/segmenation.git")

**Reproduction**

1. What command or script did you run?
 
docker build -t mmseg .

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

If applicable, paste the error trackback here.

"remote: Repository not found.
fatal: repository 'https://github.com/open-mmlab/mmsegmenation.git/' not found"

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Junjun2016** [comment]
Hi @BALMASPhilippe and @amrit110
Thank you so much!
