### ISSUE TITLE
how to define class_weights?

### ISSUE THREAD

**Issue by passion3394** [open-mmlab/mmsegmentation#60]
We know, the class imbalance is a common problem in semantic segmentation, where can I adjust the class weight of each class in this repo?

**Comment by xvjiarui** [comment]
Hi @passion3394 
Please refer to [this tutorial](https://mmsegmentation.readthedocs.io/en/latest/tutorials/training_tricks.html#class-balanced-loss) for details.

**Comment by passion3394** [comment]
thanks, I will try.
