### ISSUE TITLE
change BB and load from self pretrain model 

### ISSUE THREAD

**Issue by Michael971022** [open-mmlab/mmsegmentation#603]
I use your trained model to fit another datasets, but I have change the BB layer. 
In training stage it works, but when I use the same BB and load self pth file to continue training, it still show missing key in pth file.
I check the pth file , it does exist (ex. backbone.strip_pooling1.conv1_1.1.weight)
In which part might the problem occur? when training save or load ? Thanks!

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

If the key do exist in .pth file but the problem still happens. I guess it may be the novel components in backbone you added and perhaps old keys in old backbones are still stored in config files.

You may `set _delete_=True` to ignore some of fields in base configs. You may refer to our [tutorial of configs for detailed information](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/config.md) for detailed information.

Hoping it is helpful for you.

Best,

**Comment by MengzhangLI** [comment]
Or you can check whether loading your own .pth file or our default .pth file.

**Comment by Michael971022** [comment]
I try this _delete_=True can't work, so I turn to check whether .pth file loading well
In my train.py, I set following config

cfg.load_from = 'checkpoints/deeplabv3plus_r50-d8_512x512_160k_ade20k_20200615_124504-6135c7e0.pth'
model = build_segmentor(cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))

when I trace the code, I found it init weight  at  mmseg/models/backbone/[resnet.py](https://github.com/open-mmlab/mmsegmentation/blob/3e70d932857f39ced7be01540f27a7df50b15fa6/mmseg/models/backbones/vit.py#L314), the pretrained variable is "[pretrained='open-mmlab://resnet50_v1c](https://github.com/open-mmlab/mmsegmentation/blob/3e70d932857f39ced7be01540f27a7df50b15fa6/configs/_base_/models/deeplabv3_r50-d8.py#L5)" not equal to cfg.load_from , then after _load_checkpoint(self.pretrained, logger=logger) the missing key and unexpect key warning occur (ps. your new resnet.py had remove init_weight! )

When I assign pretrained='./deeplabv3plus_r50-d8_512x512_160k_ade20k_20200615_124504-6135c7e0.pth' 
![image](https://user-images.githubusercontent.com/65302905/123107516-3115c980-d46c-11eb-9a7a-23b5da8f0f7a.png)
![image](https://user-images.githubusercontent.com/65302905/123107690-573b6980-d46c-11eb-988b-dc271f6d77c8.png)
It seems that key is the same, but the pth key append string 'backbone' in prefix .
Does this mean that my fine tuing was unsuccessful?
Thank you for your reply, sorry that the description is a bit messy...

**Comment by MengzhangLI** [comment]
> I try this _delete_=True can't work, so I turn to check whether .pth file loading well
> In my train.py, I set following config
> 
> cfg.load_from = 'checkpoints/deeplabv3plus_r50-d8_512x512_160k_ade20k_20200615_124504-6135c7e0.pth'
> model = build_segmentor(cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
> 
> when I trace the code, I found it init weight at mmseg/models/backbone/[resnet.py](https://github.com/open-mmlab/mmsegmentation/blob/3e70d932857f39ced7be01540f27a7df50b15fa6/mmseg/models/backbones/vit.py#L314), the pretrained variable is "[pretrained='open-mmlab://resnet50_v1c](https://github.com/open-mmlab/mmsegmentation/blob/3e70d932857f39ced7be01540f27a7df50b15fa6/configs/_base_/models/deeplabv3_r50-d8.py#L5)" not equal to cfg.load_from , then after _load_checkpoint(self.pretrained, logger=logger) the missing key and unexpect key warning occur (ps. your new resnet.py had remove init_weight! )
> 
> When I assign pretrained='./deeplabv3plus_r50-d8_512x512_160k_ade20k_20200615_124504-6135c7e0.pth'
> ![image](https://user-images.githubusercontent.com/65302905/123107516-3115c980-d46c-11eb-9a7a-23b5da8f0f7a.png)
> ![image](https://user-images.githubusercontent.com/65302905/123107690-573b6980-d46c-11eb-988b-dc271f6d77c8.png)
> It seems that key is the same, but the pth key append string 'backbone' in prefix .
> Does this mean that my fine tuing was unsuccessful?
> Thank you for your reply, sorry that the description is a bit messy...

Sorry for late reply.

Seems it may happen because key of our provided trained model would include its `head` name such as `backbone.`, `decode_head.`, but key of original using `pretrained` model such as `ResNet50_V1c` does not have this prefix.

You could rename name of model key: (1) load this `.pth` file (2) build a new dict with new key (i.e., from `backbone.stem.0.weight` to `stem.0.weight`) and its corresponding value (3) save this dict as a brand new `.pth` file and use this new model.

Hoping for your responses.

Best,
