### ISSUE TITLE
FCN's difference between code and paper 

### ISSUE THREAD

**Issue by JoyLuo** [open-mmlab/mmsegmentation#61]
FCN's implement of mmseg concatenate feature using one block feature, but multi blocks feature is concatenated in FPN of paper.
this is key point of FCN, and its different between code and paper

**Comment by xvjiarui** [comment]
Hi @JoyLuo 
Since we are using dilate 8 backbone, we just implement the most basic version, which is similar to C1 decoder [here](https://github.com/CSAILVision/semantic-segmentation-pytorch).

**Comment by JoyLuo** [comment]
i got it, you just implement the most basic version. and we can construct the better version by ourselves. thanks.
