### ISSUE TITLE
fp16 TensorRT model is slower than fp32.

### ISSUE THREAD

**Issue by DonggeunYu** [open-mmlab/mmsegmentation#632]
This was done on V100. What's the problem?

**Model File size**
ONNX: 47M
TensorRT FP32: 171M
TensorRT FP16: 52M

**Inference Speed**
fp32-> fp16 = 0.0072s -> 0.0079s

**PyTorch**
| Class        | IoU   | Acc   |
|------|----|----|
| clear        | 64.03 | 84.3  |
| thick cloud  | 61.68 | 85.53 |
| thin cloud   | 24.48 | 27.43 |
| cloud shadow | 21.59 | 62.97 |

Summary:
| Scope  | mIoU  | mAcc  | aAcc  |
|----|----|----|----|
| global | 42.95 | 65.06 | 68.42 |

**TensorRT FP32**
| Class        | IoU   | Acc   |
|---|---|---|
| clear        | 64.04 | 84.25 |
| thick cloud  | 61.64 | 85.57 |
| thin cloud   | 24.46 | 27.41 |
| cloud shadow | 21.57 | 63.02 |

Summary:
| Scope  | mIoU  | mAcc  | aAcc  |
|---|---|---|---|
| global | 42.93 | 65.06 | 68.41 |

**TensorRT FP16**
| Class        | IoU   | Acc   |
|---|---|---|
| clear        | 63.38 | 86.08 |
| thick cloud  | 61.65 | 85.1  |
| thin cloud   | 21.12 | 23.19 |
| cloud shadow | 22.28 | 62.0  |

Summary:
| Scope  | mIoU  | mAcc  | aAcc  |
|---|---|---|---|
| global | 42.11 | 64.09 | 67.82 |

**Comment by grimoire** [comment]
Hi
Could you provide the model and test scripts so we can provide further help?

**Comment by DonggeunYu** [comment]
For security reasons, we cannot give you a model.
Sorry.

**Comment by grimoire** [comment]
OK, so could you tell me which model in [mmseg config](https://github.com/open-mmlab/mmsegmentation/tree/master/configs) are you using?
And can you provide a code snippet about how do you convert the model and how do you measure inference time?

**Comment by MeowZheng** [comment]
No response for a long time
