### ISSUE TITLE
I want to know whether mmdetection can be used in conjunction with this segmentation library, I want to use a framework that combines detection and segmentation

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmsegmentation#636]
I need a head that is segmented for an instance and need such a data set to realize the joint training of detection and segmentation labels

**Comment by MengzhangLI** [comment]
Hi, thanks for issue.

Although many modules are from the same source, right now MMSeg and MMDet could not be used in conjunction.

Could you tell us your ideal scene of combining detection and segmentation tasks?

In my view, do you mean certain model such as Mask RCNN which has segmentation and detection head together?

Best,

**Comment by Bin-ze** [comment]
I don't want to achieve similar mask RCNN structure, but like FCN&nbsp;structure&nbsp;, and I hope that in the coco data set up to realize it, as a branch of detection task, in simple terms, I under the network of sampling inspection task, another branch on the sample to do the segmentation task, they head to unification, in order to facilitate training together, I don't know if what I have described is clear, but I really need this experience very much, and I am looking forward to your reply. Could you please give me some suggestions? How can I achieve such a structure by modifying the network and redesigning such a head to achieve the unity of tasks



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 24, 2021 22:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmsegmentation] I want to know whether mmdetection can be used in conjunction with this segmentation library, I want to use a framework that combines detection and segmentation (#636)




 
Hi, thanks for issue.
 
Although many modules are from the same source, right now MMSeg and MMDet could not be used in conjunction.
 
Could you tell us your ideal scene of combining detection and segmentation tasks?
 
In my view, do you mean certain model such as Mask RCNN which has segmentation and detection head together?
 
Best,

**Comment by Bin-ze** [comment]
My thoughts are the same as you. I just want to apply the segmentation head in MMSEG to MMDEt, but I found that the coding and decoding structure of MMSEg is the logic of writing, while MMDET is the backbone, neck, and head structure. Obviously they have different logics And because the code is too engineering, many split classes inherit a large number of common classes, resulting in very poor portability, because if you don't want to write code, then those inherited classes need to introduce it, I want to talk to you , Is my above statement correct?

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

I think your idea has values, but I really dont know too much about detection. My suggestion is you should define your task into `segmentation` or `detection` thus you can choose the framework(`MMSegmentation` or `MMDetection`) for your next research. 

Best,
