### ISSUE TITLE
I want to know whether the label information used by mask rcnn is the same as the regular segmentation information

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmsegmentation#638]
I want to know whether the label information used by mask rcnn is the same as the regular segmentation information. Mask rcnn is based on roi, so I am thinking that its information should be cropped in the proposal area as a GT. I don’t know if my understanding is correct. , Because I just read his paper instead of carefully watching the source code, and I observed that the FCN you implemented does not have a coco segmentation configuration. Is it because it is difficult to have a good effect on the coco data set? The label of coco is not compatible with the design of FCN, and a new design may be needed. I really want to reproduce FCN on the coco data set. I need your help. I may be a novice, so I hope you can give me detailed Comments to facilitate my work, thank you very much

**Comment by Junjun2016** [comment]
Hi @Bin-ze 
Sorry for the late reply!
Instance segmentation is a little different from semantic segmentation!
Instance segmentation should distinguish every instance mask even if they share the same category.
Instance segmentation can degrade to semantic segmentation by merging the instance masks of the same category,
and the annotation labels should be the label index to represent the category!

**Comment by Bin-ze** [comment]
I understand what you mean. I mean whether the instance segmentation of the mask R-cnn series is performed on the basis of the region proposal. I think it is. That is to say, there is actually only one object in the obtained region. Mask prediction is to predict the mask of this object, instead of operating on the entire image like FCN to get the result.

**Comment by Junjun2016** [comment]
> I understand what you mean. I mean whether the instance segmentation of the mask R-cnn series is performed on the basis of the region proposal. I think it is. That is to say, there is actually only one object in the obtained region. Mask prediction is to predict the mask of this object, instead of operating on the entire image like FCN to get the result.

Yes, exactly!
