### ISSUE TITLE
In decoder_head, don't the convolution kernels other than the cls layer need to be initialized?  

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#644]
Hi, dear authors!
Sorry to bother you. 
I see that your `decoder_head` only initializes the convolution kernel of the `cls` layer, but the other convolution kernels are not initialized. 
Do those uninitialized convolution kernels really have to be initialized?
Could you recommend a better initialization method for the convolution kernel of `decode_head` (except for the `cls`)?
Thank you!

**Comment by Junjun2016** [comment]
Hi @Junjun2016 
The  `ConvMudule ` is initialized by default in PyTorch (refer to [_ConvNd)](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L138).

**Comment by zhongqiu1245** [comment]
@Junjun2016 Thank you！
