### ISSUE TITLE
accelerate pretrained-model downloading

### ISSUE THREAD

**Issue by zhikunluo175** [open-mmlab/mmsegmentation#65]
Hi, i found downloading pretrained models from  'https://open-mmlab.s3.ap-northeast-2.amazonaws.com/' is so slow (I'm at Chinese mainland), does it support downloading from accelerating site like 'openmmlab.oss-accelerate.aliyuncs.com' ?

**Comment by xvjiarui** [comment]
Hi, @zhikunluo175 
The link has been updated in https://github.com/open-mmlab/mmcv/pull/490.
You may have a try.
