### ISSUE TITLE
Request for adding MCC loss and Focal Phi Loss

### ISSUE THREAD

**Issue by rubeea** [open-mmlab/mmsegmentation#651]
Hi,

The Matthews Correlation Coeffcicient Loss function (MCC loss ref. https://ieeexplore.ieee.org/abstract/document/9433782/) and its recently introduced variant Focal MCC/Phi loss (ref: https://www.mdpi.com/1424-8220/21/8/2803) provides automatic data/class imbalance handling usually encountered for small or thin objects in binary semantic segmentation tasks (objects vs the background pixels). Kindly include the loss functions in your official code repo. I cannot make a pull request because I didnot fork the from the official mmsegmentation repo. I have implemented the loss functions in this github repo for your reference (https://github.com/rubeea/focal_phi_loss_mmsegmentation/blob/master/mmseg/models/losses/phi_loss.py)

**Related resources**
My official github repo for the focal phi loss: https://github.com/rubeea/focal_phi_loss_mmsegmentation

**Comment by MengzhangLI** [comment]
Hi, thanks for your issue and implementation of MMSegmentation.

We would record this issue and check it in the July, 2021.

Wish you all the best. 

Best,

**Comment by MengzhangLI** [comment]
Hi, @rubeea .

We has recorded this request but are sorry that in next several months we do not have time to add this feature.

I noticed you have implemented on MMSeg. So we welcome you to make new pull request if your time available.

Related information:
[Contributing to mmsegmentation](https://github.com/open-mmlab/mmsegmentation/blob/master/.github/CONTRIBUTING.md)
[pull_request_template](https://github.com/open-mmlab/mmsegmentation/tree/3e70d932857f39ced7be01540f27a7df50b15fa6/.github)

Feel free to contact us!

Best,
