### ISSUE TITLE
When the mask is obtained by semantic segmentation, what threshold is generally used to take 0 or 1

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmsegmentation#652]

**Comment by YLyeliang** [comment]
For binary classification, if you modified the head as sigmoid output, then the threshold normally set to 0.5, it has impacts on the performance like precision and recall when you tune it higher or lower. When the threshold became higher the precision became greater and the recall vice versa. 
While for softmax output, normally we just use arg max to select the label having the highest digit.

**Comment by Bin-ze** [comment]
I want to know each class to predict a feature graph, that is to say, the number of channels represents the number of categories, such a prediction mask method needs to use sigmoid to process the output or argmax to process, what is the difference between them



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 30, 2021 11:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmsegmentation] When the mask is obtained by semantic segmentation, what threshold is generally used to take 0 or 1 (#652)




 
For binary classification, if you modified the head as sigmoid output, then the threshold normally set to 0.5, it has impacts on the performance like precision and recall when you tune it higher or lower. When the threshold became higher the precision became greater and the recall vice versa.
 While for softmax output, normally we just use arg max to select the label having the highest digit.

**Comment by MengzhangLI** [comment]
Hi, @Bin-ze sorry for late reply! And thanks for warm-hearted reply @YLyeliang !
In my opinion, just as @YLyeliang mentioned, the threshold would affect precision and recall but segmentation output is usually a binary classification task, i.e., only Arg Max class (channel) matters. Thus the change of threshold would not affect numerical results too much.

So in my opinion, in most tasks, setting 0.5 is OK, and if you want better recall/precision, you need to make threshold lower/higher. 

Best,
