### ISSUE TITLE
error in train.py

### ISSUE THREAD

**Issue by JoyLuo** [open-mmlab/mmsegmentation#653]
error in line 134 in mmsegmentation/tools/train.py 
model.init_weights() is error 
model.init_weight() is ok

**Comment by MengzhangLI** [comment]
Hi, `.init_weights()` is usually set in test mode. Sorry I cannot get across your problem.

Could you use **error template**? Please check the green bottom on the right above.

Best,

**Comment by Junjun2016** [comment]
> error in line 134 in mmsegmentation/tools/train.py
> model.init_weights() is error
> model.init_weight() is ok

Hi @JoyLuo 
The `init_weights` is inherited from [`BaseModule`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_module.py#L39) in `MMCV`.

**Comment by JoyLuo** [comment]
> > error in line 134 in mmsegmentation/tools/train.py
> > model.init_weights() is error
> > model.init_weight() is ok
> 
> Hi @JoyLuo
> The `init_weights` is inherited from [`BaseModule`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_module.py#L39) in `MMCV`.

BaseModule use init_weight in V1.3.1
please revise the readme to install mmcv

**Comment by Junjun2016** [comment]
Hi @JoyLuo 
Thanks for your kind reminder.
Appreciate it a lot.
