### ISSUE TITLE
How to registry the custom optimizer?

### ISSUE THREAD

**Issue by jinseok-karl** [open-mmlab/mmsegmentation#654]
Hi, thanks to [documentation](https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_models.html),
I almost followed the customizing process.
I made mmseg/core/optimizer/__init__.py also.
But still registered optimizer is default optimizer. As I debug, I don't know how to register this custom optimizers with default optimizer?

It seem to need Register('Optimizer') part. But, It already used in mmcv part.

Sincerely

**Comment by Junjun2016** [comment]
Hi @jinseok-karl 
sorry for the late reply!
Could you please provide your code?
Please refer to [MMCV](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/optimizer/builder.py#L20)
