### ISSUE TITLE
What is the size of test img in Cityscapes？

### ISSUE THREAD

**Issue by Jun-jieChen** [open-mmlab/mmsegmentation#663]
Hi, I would like to know whether the size of test img between the 769x769 and 512x1024 in configs are the same or not?

When I saw the the `pspnet_r50-d8_769x769_40k_cityscapes.py`, it has the following code:
```
model = dict(
    decode_head=dict(align_corners=True),
    auxiliary_head=dict(align_corners=True),
    test_cfg=dict(mode='slide', crop_size=(769, 769), stride=(513, 513)))
```
but when I saw the `pspnet_r50-d8_512x1024_40k_cityscapes.py`, however, this file doesn't has the `test_cfg` part.

When I choose 769x769 config, if the size of test or val img will also  crop to (769, 769)?

**Comment by Junjun2016** [comment]
Hi @Jun-jieChen 
testing img_scale is `1024x2048`, but the inference mode is `whole `for `512x1024` and slide for `769x769`.

> but when I saw the pspnet_r50-d8_512x1024_40k_cityscapes.py, however, this file doesn't has the test_cfg part.
Inherit from `__base__`

**Comment by Jun-jieChen** [comment]
@Junjun2016 
There is something wrong in [标准与模型库](https://mmsegmentation.readthedocs.io/zh_CN/latest/model_zoo.html#id3): `其余情况，对于输入大小为 8x+1 (比如 512，1024)，我们使用 align_corners=False`, it must be `8x` in the correct situation.

**Comment by Jun-jieChen** [comment]
Hi, @Junjun2016 
I would also like why in `cityscapes_769x769.py`, it has the following code:
`
train_pipeline = [
    ...
    dict(type='Resize', img_scale=(2049, 1025), ratio_range=(0.5, 2.0)),
    ...
]
test_pipeline = [
    ....
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2049, 1025),
    ...
]
`
however, in `cityscapes.py`, it has different size of img_scale as the following code:
`
train_pipeline = [
    ...
    dict(type='Resize', img_scale=(2048, 1024), ratio_range=(0.5, 2.0)),
    ...
]
test_pipeline = [
    ...
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 1024),
   ...
]
`
why they will be coded as (2049,1025) or (2048,1024)?

**Comment by MengzhangLI** [comment]
> @Junjun2016
> There is something wrong in [标准与模型库](https://mmsegmentation.readthedocs.io/zh_CN/latest/model_zoo.html#id2): `其余情况，对于输入大小为 8x+1 (比如 512，1024)，我们使用 align_corners=False`, it must be `8x` in the correct situation.

It is the typo. When `align_corners=False`, the input size is `8x (i.e., 512, 1024)` and when `align_corners=True`, the input size is `8x + 1, (i.e., 513, 769)`.

**Comment by MengzhangLI** [comment]
> @Junjun2016
> There is something wrong in [标准与模型库](https://mmsegmentation.readthedocs.io/zh_CN/latest/model_zoo.html#id2): `其余情况，对于输入大小为 8x+1 (比如 512，1024)，我们使用 align_corners=False`, it must be `8x` in the correct situation.


It is the typo. When `align_corners=False`, the input size is `8x (i.e., 512, 1024)` and when `align_corners=True`, the input size is `8x + 1, (i.e., 513, 769)`.

**Comment by MengzhangLI** [comment]
> Hi, @Junjun2016
> I would also like why in `cityscapes_769x769.py`, it has the following code:
> 
> ```
> train_pipeline = [
>     ...
>     dict(type='Resize', img_scale=(2049, 1025), ratio_range=(0.5, 2.0)),
>     ...
> ]
> test_pipeline = [
>     ....
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(2049, 1025),
>     ...
> ]
> ```
> 
> however, in `cityscapes.py`, it has different size of img_scale as the following code:
> 
> ```
> train_pipeline = [
>     ...
>     dict(type='Resize', img_scale=(2048, 1024), ratio_range=(0.5, 2.0)),
>     ...
> ]
> test_pipeline = [
>     ...
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(2048, 1024),
>    ...
> ]
> ```
> 
> why they will be coded as (2049,1025) or (2048,1024)?

Hi, you can global search `cityscapes_769x769.py` and would found corresponding `align_corners` is `True`.

![image](https://user-images.githubusercontent.com/24582831/125617580-8c00c733-67fc-4448-98f0-f755c6a1680d.png)

**Comment by MengzhangLI** [comment]
> @MengzhangLI
> I see.
> But I would like to know why the img_scale is different between `cityscapes_769x769.py` (2049, 1025) and `cityscapes.py` (2048, 1024)?

Just as I said before, `cityscapes_769x769.py` means slide is `769x769`, its corresponding `align_corners` is `True` thus its whole image size should also be `8x + 1` for correct processing.

Best,

**Comment by Jun-jieChen** [comment]
> > @MengzhangLI
> > I see.
> > But I would like to know why the img_scale is different between `cityscapes_769x769.py` (2049, 1025) and `cityscapes.py` (2048, 1024)?
> 
> Just as I said before, `cityscapes_769x769.py` means slide is `769x769`, its corresponding `align_corners` is `True` thus its whole image size should also be `8x + 1` for correct processing.
> 
> Best,

I see, I see... Thanks.
