### ISSUE TITLE
Crop size

### ISSUE THREAD

**Issue by DaraOrange** [open-mmlab/mmsegmentation#673]
Hello! Is it possible to choose crop size from some distribution or only use fixed?

**Comment by Junjun2016** [comment]
Hi @DaraOrange 
Could you please give an example or describe it in more detail?

**Comment by Junjun2016** [comment]
Hi @DaraOrange 
Any news?

**Comment by DaraOrange** [comment]
Hello! I found solution by creation custom augmentation.
