### ISSUE TITLE
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=[1, 3, 7], <=[1, 4, 0].

### ISSUE THREAD

**Issue by kadi-hocine** [open-mmlab/mmsegmentation#674]
**Describe the bug**
I try to run mmsegmentation on colab and after pytorch and mmcv installations, when I try to **import mmseg** I had this error : **AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=[1, 3, 7], <=[1, 4, 0]**.

I checked https://download.openmmlab.com/mmcv/dist/index.html without finding the matching verions. 
The problem is, I already run mmsegmentation with success and from 4 days I had this error. 

Complet error :
AssertionError                            Traceback (most recent call last)
<ipython-input-2-a28a07eafcbf> in <module>()
      4 
      5 # Check MMSegmentation installation
----> 6 import mmseg
      7 #print(mmseg.__version__)

/content/mmsegmentation/mmseg/__init__.py in <module>()
     25 
     26 assert (mmcv_min_version <= mmcv_version <= mmcv_max_version), \
---> 27     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
     28     f'Please install mmcv>={mmcv_min_version}, <={mmcv_max_version}.'
     29 

AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=[1, 3, 7], <=[1, 4, 0].

**Comment by Junjun2016** [comment]
Hi @kadi-hocine 
Please check it [here](https://github.com/open-mmlab/mmcv#installation) in MMCV.

**Comment by zhouzaida** [comment]
hi @kadi-hocine , you can install mmcv-full via `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`

For example, if your cuda verison is 10.1 and torch version is 1.6.0 , you can type `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html`

**Comment by kadi-hocine** [comment]
> Hi @kadi-hocine
> Please check it [here](https://github.com/open-mmlab/mmcv#installation) in MMCV.



> hi @kadi-hocine , you can install mmcv-full via `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`
> 
> For example, if your cuda verison is 10.1 and torch version is 1.6.0 , you can type `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html`

**Comment by kadi-hocine** [comment]
> > Hi @kadi-hocine
> > Please check it [here](https://github.com/open-mmlab/mmcv#installation) in MMCV.
> 
> > hi @kadi-hocine , you can install mmcv-full via `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`
> > For example, if your cuda verison is 10.1 and torch version is 1.6.0 , you can type `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html`

Thank you for your responses. The solution given by @zhouzaida worked for me I install mmcv in this version !pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.5.0/index.html and it works
