### ISSUE TITLE
segmentation result image

### ISSUE THREAD

**Issue by lmunan** [open-mmlab/mmsegmentation#68]
I want to know where I can change the overlay effect of the segmentation result image and the original image, I just want to change the background color to black.

**Comment by lmunan** [comment]
I found it,thank you.

**Comment by zyhhhy** [comment]
I met the same question. Could you please tell me how to solve if?

**Comment by zyhhhy** [comment]
I got it.
Modify the mmsegmentation/mmseg/models/segmentors/base.py in Line 255
img = color_seg
