### ISSUE TITLE
Chasedb1, stare convert_dataset scripts generating only black validation masks

### ISSUE THREAD

**Issue by prnvjb** [open-mmlab/mmsegmentation#681]
Hi,
I downloaded CHASE_DB1 and STARE datasets. I used tools/convert_dataset/ *py fies to convert archived files to make them mmsegmentation compatible. How ever after running the scripts I'm getting only black images. 
Example in the mmseg/datasets/chase_db1.py the palettes are:

    CLASSES = ('background', 'vessel')
    PALETTE = [[120, 120, 120], [6, 230, 230]], I think it should be = [[0, 0, 0], [255, 255, 255]]

can you please point me in the right direction to train these datasets?
Thanks.

**Comment by Junjun2016** [comment]
Hi @prnvjb 
Since label mask or TrainID is saved as a *.png file, it ranges from 0 to num classes -1. 
In the CHASE DB1 and STARE databases, the label is either 0 or 1. 
And the ignore index is normally set to 255.

**Comment by MengzhangLI** [comment]
Because the "black" picture contains `0` for background and `1` for foreground (vessel), both of which are all very small for full value `255` in `png, jpg, jpeg` format. Thus it seems like only black masks.

You could check above words by code.
