### ISSUE TITLE
Does 'workflow' conflict with 'Evaluation config' ?

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#684]
Hi, I am a beignner of mmsegmentation.
In the [tutorial](https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_runtime.html#), workflow might be `[('train', 1),('val', 1)] ` and Evaluation config might be  `evaluation = dict(interval=1, metric='mIoU')`.

The former is based on epoch number ,while the latter is based on iteration muber.Will they conflict with each other?

**Comment by sennnnn** [comment]
We already replace validation workflow to eval hook. If you set ('val', 1), there may evaluate model twice.
