### ISSUE TITLE
请问下，如果我想推理时最短边不低于640，同时不希望使用MultiScaleFlipAug，我应该怎么写test_pipline？

### ISSUE THREAD

**Issue by cjt222** [open-mmlab/mmsegmentation#686]

**Comment by Junjun2016** [comment]
```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 640),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        img_ratios=[1.0,],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

and set --aug-test to False.

**Comment by cjt222** [comment]
我使用的是image_demo.py去预测单张的图片，里面没有--aug-test这个选项

**Comment by cjt222** [comment]
而且能不能不使用多尺度推理这种方式进行单张图推理？

**Comment by Junjun2016** [comment]
> ```python
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(2048, 640),
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         img_ratios=[1.0,],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> ```
> 

It will not use MS test.
