### ISSUE TITLE
how

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#691]
I have 2 train set ,2 validate set and 2 test set. How can I concatenate the test and validate dataset?
I wonder if the following code is ok :

> # contacte
>  data = dict(
    imgs_per_gpu=12,
    workers_per_gpu=12,
    train=[
        dataset1,
        dataset2
    ],
    val=[
        dataset3,
        dataset4
    ],
    test=[
        dataset5,
        dataset6
    ]
)

If the code is not ok , how can I modify the code for my own use?

**Comment by Junjun2016** [comment]
Hi @MengHao666 
Please refer to this [tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md).
