### ISSUE TITLE
Are you going to add 3D picture segmentation model?

### ISSUE THREAD

**Issue by 459737087** [open-mmlab/mmsegmentation#701]
I have some medical pictures , and I wang to send them to mmseg

**Comment by Junjun2016** [comment]
Hi @459737087 
We will support it in the future, but there is a shortage of people at present
Contributions are welcome and looking forward to your PR!

**Comment by 459737087** [comment]
I met some challenges, how to deal with nii image.
I don't wang to split it into many slices.
Do you have any suggestions?

**Comment by Junjun2016** [comment]
Extend UNet to 3D UNet by replacing 2D operators with 3D operators.

**Comment by MengzhangLI** [comment]
> I met some challenges, how to deal with nii image.
> I don't wang to split it into many slices.
> Do you have any suggestions?
> @Junjun2016

(1) You could use nnUNet at this time. https://github.com/MIC-DKFZ/nnUNet 
You just need to convert data into proper directory folder organization and it could run automatically. The result is also very very impressive, but this framework is hard to understand and modify.

(2) If you want to deal with nifti image by yourself, you could use `nibabel` or 'simgpleITK' to load nii file into numpy array, please note that other information such as `origin`, 'spacing' and 'direction' are still very important.

**Comment by 459737087** [comment]
> > I met some challenges, how to deal with nii image.
> > I don't wang to split it into many slices.
> > Do you have any suggestions?
> > @Junjun2016
> 
> (1) You could use nnUNet at this time. https://github.com/MIC-DKFZ/nnUNet
> You just need to convert data into proper directory folder organization and it could run automatically. The result is also very very impressive, but this framework is hard to understand and modify.
> 
> (2) If you want to deal with nifti image by yourself, you could use `nibabel` or `simgpleITK` to load nii file into numpy array, please note that other information such as `origin`, `spacing` and `direction` are still very important.

thank you!!!
