### ISSUE TITLE
ConatctDataset object has no attrribute "evluate"

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#703]
Hi, I want to contact two validate set, however following error occurs .

![image](https://user-images.githubusercontent.com/47114466/125602285-1d23d3a7-47ff-4086-8681-f28620a2a6e0.png)

**Comment by Junjun2016** [comment]
[MMSegmentation supports to mix dataset for training while not for validation. Currently, it supports to concat and repeat datasets.](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md)

**Comment by MengHao666** [comment]
ok,thanks.
