### ISSUE TITLE
DRAN model 

### ISSUE THREAD

**Issue by JIA-HONG-CHU** [open-mmlab/mmsegmentation#708]
Hi, Thank you for providing such a good kit for us to use. Will you be adding the DRAN model in the near future? Tks. https://github.com/junfu1115/DRAN

**Comment by Junjun2016** [comment]
Hi @JIA-HONG-CHU 
We may consider it in the future, but not in the next few monthes.
PR is welcome!

**Comment by JIA-HONG-CHU** [comment]
ok Tks for reply
