### ISSUE TITLE
KeyError: 'PALETTE' when use method init_segmentor()

### ISSUE THREAD

**Issue by wgggSg** [open-mmlab/mmsegmentation#710]
The error code:
```
Use load_from_local loader
~/workspace/mmcv-test/mmseg/models/backbones/hrnet.py:298: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-da74faa07110> in <module>
      7     pth_file = osp.join(work_dir, 'iter_30000.pth')
      8     print(torch.load(pth_file))
----> 9     model = init_segmentor(cfg, pth_file, device='cuda:0')
     10 else:
     11     model.cfg = cfg

~/workspace/mmcv-test/mmseg/apis/inference.py in init_segmentor(config, checkpoint, device)
     33         checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
     34         model.CLASSES = checkpoint['meta']['CLASSES']
---> 35         model.PALETTE = checkpoint['meta']['PALETTE']
     36     model.cfg = config  # save the config in the model for convenience
     37     model.to(device)

KeyError: 'PALETTE'
```
My CustomDataset:
```
@DATASETS.register_module()
class BDD100KLaneLabelDataset(CustomDataset):
  CLASSES = classes
  PALETTE = palette
  def __init__(self, split, **kwargs):
    super().__init__(img_suffix='.jpg', seg_map_suffix='.png', 
                     split=split, **kwargs)
    assert osp.exists(self.img_dir) and self.split is not None
print('done')
```
I solved it using a simple way:
modify `model.PALETTE = checkpoint['meta']['PALETTE']` to `model.PALETTE = my_paletee`
 at line 35 in `mmseg/apis/inference.py`.

But I want to know an official way to solve this error, please tell me.
thanks

**Comment by Junjun2016** [comment]
Hi @wgggSg 
Maybe you have not saved the `meta` or `PALETTE` in the `checkpoint`.

**Comment by wgggSg** [comment]
@Junjun2016 
It is indeed the problem you said. I have solved it by add the code
```
cfg.checkpoint_config.meta = dict(
    CLASSES=classes,
    PALETTE=palette)
```
to my config file, thanks!

**Comment by 459737087** [comment]
Good job!

**Comment by LansonChen** [comment]
> @Junjun2016 It is indeed the problem you said. I have solved it by add the code
> 
> ```
> cfg.checkpoint_config.meta = dict(
>     CLASSES=classes,
>     PALETTE=palette)
> ```
> 
> to my config file, thanks!
@wgggSg
hi,did you use jupyter notebook to modify those configs? Could u share one copy of the ipynb to me, thanks!

**Comment by wgggSg** [comment]
> > @Junjun2016 It is indeed the problem you said. I have solved it by add the code
> > ```
> > cfg.checkpoint_config.meta = dict(
> >     CLASSES=classes,
> >     PALETTE=palette)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to my config file, thanks!
> > @wgggSg
> > hi,did you use jupyter notebook to modify those configs? Could u share one copy of the ipynb to me, thanks!

sorry, it have been a long time I didn't use mmsegmentation, so that my code file couldn't be found.....
I remembered i add the code above to train.py so that the error is solved, maybe just add PALETTE and CLASSES to your checkpoint could also solve this problem.
