### ISSUE TITLE
Question abound normalize mean and std

### ISSUE THREAD

**Issue by blakeliu** [open-mmlab/mmsegmentation#73]
I found VOC   mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375] , the range is not 0-1,  why not image divide 255???  

Thanks for answering my question！！

**Comment by xvjiarui** [comment]
Hi @blakeliu 
The 255 is absorbed by mean and std.
It is equivalent to dividing 255 first, and normalize with [0, 1] ranged mean/std.

**Comment by blakeliu** [comment]
@xvjiarui Thanks！

**Comment by KangolHsu** [comment]
max = (255-123.67)/58.395 =2.248999
min = (0-123.67)/58.395=-2.11


range = (-2.11,2.248999)


why ?

**Comment by KangolHsu** [comment]
max = (255-123.67)/58.395 =2.248999
min = (0-123.67)/58.395=-2.11


range = (-2.11,2.248999)


why ?

**Comment by xvjiarui** [comment]
max, min does not necessary be something like 0, 1
