### ISSUE TITLE
Performance gap for deeplabv3+ on cityscapes dataset 

### ISSUE THREAD

**Issue by foreverbest** [open-mmlab/mmsegmentation#730]
Hi, 
  Thanks for your excellent job in this project! Recently I tried to train DeepLabV3+ with ResNet 50 backbone for 40k iters on cityscapes dataset (512x1024) and the result's mIoU is confusing: 
```
2021-07-27 10:13:38,440 - mmseg - INFO - 
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 91.71 | 51.32 | 62.62 |
+-------+-------+-------+
2021-07-27 10:13:38,491 - mmseg - INFO - Exp name: deeplabv3plus_r50-d8_512x1024_40k_cityscapes.py 
```
which is much lower than your trained model in model zoo.

  I use the single GPU (Nvidia Quadro P5000 16G) and default config (only change 'syncBN' to 'BN') to train the model.
Could you provide some clues for this result?

**Comment by Junjun2016** [comment]
Hi @foreverbest 
Please try the official setting!
4 GPUs, 2 images/GPU, and syncBN.

**Comment by foreverbest** [comment]
I see. Unfortunately I don't have enough gpu to train the model. Does the number of GPUs have such a big impact on the results? And can I just increase the iteration to reach the claimed performance? 
Thanks again for your patience.

**Comment by Junjun2016** [comment]
You should train it with more iterations.
Since the total iteration is the same, but the total batch size is 1x2 instead of 4x2.

**Comment by foreverbest** [comment]
Got it. Thanks a lot.
