### ISSUE TITLE
请问能否提供deeplabV3plus的PointRend的config?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#735]
作者你好！
PointRend的原文中提到了deeplabV3plus的对比，请问您能否提供deeplabV3plus的PointRend的config?(不用neck)
谢谢！

**Comment by Junjun2016** [comment]
Hi @zhongqiu1245 
Replace 'FPN' and `FPNHead` with `DepthwiseSeparableASPPHead`.

**Comment by zhongqiu1245** [comment]
谢谢您，但是我有另外一个问题
我尝试着把pointrend-deeplabV3plus的backbone替换成resnet18(我也对`DepthwiseSeparableASPPHead`进行了更改，使他的channels符合resnet18，并且测试resnet18的deeplabV3plus可以跑通）,但是pointrend-deeplabV3plus跑不通,总显示
RuntimeError: Given groups=1, weight of size [256, 275, 1], expected input[1, 83, 8196] to have 275 channels, but got 83 channels instead
请问该如何修改其中的pointrend的设置部分？
谢谢您
配置如下：

`
model = dict(
    type='CascadeEncoderDecoder',
    num_stages=2,
    pretrained='open-mmlab://resnet18_v1c',
    backbone=dict(
        type='ResNetV1c',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=norm_cfg,
        norm_eval=False,
        style='pytorch',
        contract_dilation=True),
    decode_head=[
        dict(
            type='DepthwiseSeparableASPPHead',
            in_channels=512,
            in_index=3,
            channels=128,
            dilations=(1, 12, 24, 36),
            c1_in_channels=64,
            c1_channels=48,
            dropout_ratio=0.1,
            num_classes=19,
            norm_cfg=norm_cfg,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)
        ),
        dict(
            type='PointHead',
            in_channels=[256],
            in_index=[0],
            channels=256,
            num_fcs=3,
            coarse_pred_each_layer=True,
            dropout_ratio=-1,
            num_classes=19,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))
    ],
    # model training and testing settings
    train_cfg=dict(
        num_points=2048,
        oversample_ratio=3,
        importance_sample_ratio=0.75),
    test_cfg=dict(
        mode='whole',
        subdivision_steps=2,
        subdivision_num_points=8196,
        scale_factor=2))
`

**Comment by zhongqiu1245** [comment]
Any news？

**Comment by Junjun2016** [comment]
Hi @zhongqiu1245 
Sorry for the late reply!
It is better to use English!
The list output channels of r18 is `[64, 128, 256, 512]` instead of `[256, 512, 1024, 2018]`.
So the `in_channels` and `in_index` are mismatched in the following config:
```python
dict(
            type='PointHead',
            in_channels=[256],
            in_index=[0],
            channels=256,
            num_fcs=3,
            coarse_pred_each_layer=True,
            dropout_ratio=-1,
            num_classes=19,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))
    ]
```

**Comment by zhongqiu1245** [comment]
@Junjun2016 Thank you！
