### ISSUE TITLE
Match mmdetection default EpochBasedRunner

### ISSUE THREAD

**Issue by mmeendez8** [open-mmlab/mmsegmentation#739]
# Describe the feature

**Motivation**

`IterBasedRunner` is the [default runner in train api](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/apis/train.py#L75). That's not really comfortable since most libraries and publications use epochs as reference. 

I think it would be more convenient to change this behavior and match mmdetection one, that gets epochs from config file, if value is present, and sets this value in the `EpochBasedRunner` (see [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/apis/train.py#L75))

**Additional context**
I am willing to implement this changen and send a PR

**Comment by Junjun2016** [comment]
Hi @mmeendez8 
We use `IterBasedRunner` for all the benchmarks in MMSegmentation codebase, so the default runner is `IterBasedRunner`.
https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/configs/_base_/schedules/schedule_20k.py#L7

`EpochBasedRunner` is also supported, 
Replace 
```
runner = dict(type='IterBasedRunner', max_iters=20000) 
```
with 
```
runner = dict(type='EpochBasedRunner', max_epochs=40)
```
https://github.com/open-mmlab/mmdetection/blob/2295154d0413a5d9df26579c56ef067be30e48b9/configs/_base_/schedules/schedule_1x.py#L11

**Comment by mmeendez8** [comment]
Yes, I just was wondering why this change wrt mmdetection

**Comment by Junjun2016** [comment]
> Yes, I just was wondering why this change wrt mmdetection

Usually,  the LR update policy is based on iteration for semantic segmentation while object detection is based on epoch.
