### ISSUE TITLE
Questions about OHEM

### ISSUE THREAD

**Issue by ydhongHIT** [open-mmlab/mmsegmentation#740]
It seems abnormal that the loss still goes down fast after using ohemsample on cityscapes dataset, as fast as that without ohem.

**Comment by Junjun2016** [comment]
OHEM is used for hard example mining.
The decrease of loss has no clear relationship with OHEM.
Why does OHEM slow down the decrease of loss?

> It seems abnormal that the loss still goes down fast after using ohemsample on cityscapes dataset, as fast as that without ohem.

Could you please provide some references?

**Comment by MengzhangLI** [comment]
Hi, loss drops faster means OHEM works. 

If it is as fast as original settings, it means OHEM sampler makes little improvements which is also very common.

Best,
