### ISSUE TITLE
为什么只识别出一种种类，其他的全为nan，这是什么出了问题?

### ISSUE THREAD

**Issue by mhyu19** [open-mmlab/mmsegmentation#744]
![图片](https://user-images.githubusercontent.com/58076940/127772727-ef091d7e-bdc1-46e3-b343-bc6b3806ac7f.png)
![图片](https://user-images.githubusercontent.com/58076940/127772738-e1c47658-af39-45cb-8f43-fca2b89df9b5.png)

**Comment by xiexinch** [comment]
Hi @mhyu19 
1. What command, model and config did you run?
2.  Did you make any modifications on the code or config?

**Comment by xiexinch** [comment]
Hi @mhyu19 
It seems that you have modified the dataset setting, can you show us your modification? It may help to locate your problem.

**Comment by mhyu19** [comment]
1、刚开始并没有修改代码以及配置文件，训练测试结果出现nan.
2、于是我把在pspnet_r18-d8_512x1024_80k_cityscapes.py中修改了:num_classes=1, 在mmseg/core/evaluation/class_names.py 中做如下修改：
def cityscapes_classes():
    """Cityscapes class names for external use."""
    return ['sidewalk']
    #return [
    #    'road', 'sidewalk', 'building', 'wall', 'fence', 'pole',
    #    'traffic light', 'traffic sign', 'vegetation', 'terrain', 'sky',
    #    'person', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle',
    #    'bicycle'
    #]
在datasets/cityspaces.py中做出一下修改：
    CLASSES =('sidewalk',)
    # CLASSES = ('road', 'sidewalk', 'building', 'wall', 'fence', 'pole',
    #            'traffic light', 'traffic sign', 'vegetation', 'terrain', 'sky',
    #            'person', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle',
    #            'bicycle')
训练测试出的结果还是和1中的情况一样。
我想很可能是数据集的原因。
谢谢回答！

**Comment by mhyu19** [comment]
![图片](https://user-images.githubusercontent.com/58076940/127955307-40a22003-a8f9-4b9b-8baf-ee4aa6af1b36.png)
重新获取数据集之后训练500iter结果正常

**Comment by mhyu19** [comment]
重新获取数据集之后测试结果正常，是我数据的问题
![图片](https://user-images.githubusercontent.com/58076940/127955547-08df591e-ad9c-46ed-b69e-e54233650784.png)

**Comment by RoyZhDec** [comment]
> 重新获取数据集之后测试结果正常，是我数据的问题 

请问下重新获取数据集是什么操作呢？

**Comment by mhyu19** [comment]
> > 重新获取数据集之后测试结果正常，是我数据的问题
> 
> 请问下重新获取数据集是什么操作呢？

重新下了cityscapes数据集

**Comment by ke-dev** [comment]
Hi, I have the same problem, has your problem been solved? @mhyu19

**Comment by 2807402145** [comment]
you must keep the value of mask is between 0 and num_class-1.
