### ISSUE TITLE
Why print same info twice?

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#745]
![image](https://user-images.githubusercontent.com/18137551/127877057-9679f757-6117-4b0e-8ab4-46783c288fa2.png)

**Comment by jianlong-yuan** [comment]
any news?

**Comment by zhouzaida** [comment]
hi @jianlong-yuan , please upgrade your mmcv-full to latest version.
more datails at https://github.com/open-mmlab/mmcv/pull/1164

**Comment by Junjun2016** [comment]
Try the latest PR of mmcv and mmseg (https://github.com/open-mmlab/mmsegmentation/issues/758)
