### ISSUE TITLE
Can UNet be used with multiple classes? Is there a more preferred network for multiclass segmentation?

### ISSUE THREAD

**Issue by kgiannakelos** [open-mmlab/mmsegmentation#751]
Hello and thanks for your great work!

I just started using mmsegmentation to train a UNet with multiple classes (my problem consists of satellite images) but i don't know if the current implementation and configs in the model zoo supports multiclass training.

Can UNet be used in that way in mmsegmentation? If not, can i use another model to solve a multiclass segmentation problem (maybe DeepLabV3)?

**Comment by Junjun2016** [comment]
Hi @kgiannakelos 
Multi-class is supported.
Just set the `num_classes` in decode_head.
UNet is considered as the backbone and the head can be FCN, DeepLabV3, and so on.

**Comment by kgiannakelos** [comment]
@Junjun2016 Yeah i noticed the backbone and decode head architecture after i tried to train my own network using your predefined configurations in the model zoo (just changed the num_classes to a bigger number).

But it seems that for some reason the GPU memory is very high (11gb) even though your logs in the chase_db1 [configuration ](https://download.openmmlab.com/mmsegmentation/v0.5/unet/unet_s5-d16_128x128_40k_chase_db1/unet_s5-d16_128x128_40k_chase_db1-20201223_191051.log.json ) of UNet report about 5gb memory usage. Is this normal? 

I thought that maybe i am using multiclass incorrectly and wanted to verify how is multi class implemented. 

I also have stumbled upon another weird problem where my training process suddenly stops without error when it reaches the first save checkpoint or the beginning of 2nd epoch (2000 iterations out of 18000). Ii am trainig in epochs instead of iterations but i guess this is not a problem. 

Are there any clues?

**Comment by Junjun2016** [comment]
Try our default config to check the GPU memory consumption.
What is the size of the validation dataset?

**Comment by kgiannakelos** [comment]
Train Size: ~19000 imgs
Val Size: 6000 imgs

I get 11gb consumption in logs but 8.4gb consumption using nvidia-smi

**Comment by Junjun2016** [comment]
The GPU memory consumption is more accurate when setting `cudnn_benchmark = False`.

**Comment by kgiannakelos** [comment]
@Junjun2016 Thanks a lot. That was it! My gpu memory usage was reduced from 11gb to 5.6gb similar to the logs in the model zoo after setting `cudnn_benchmark = False`

My model now trains past the 2nd epoch now without any problems, so it must have been some out of memory issue (either gpu or RAM).

I've got a final question and we can close this issue. I want to use the Dice Loss assuming it works for a multiclass problem (but i haven't found any configurations with it to confirm it). Do we i my model with num_of_classes_of_interest + 1 for the background class or we ignore the background class completely when using Dice Loss? 

Thank you so much for your help!

**Comment by Junjun2016** [comment]
> @Junjun2016 Thanks a lot. That was it! My gpu memory usage was reduced from 11gb to 5.6gb similar to the logs in the model zoo after setting `cudnn_benchmark = False`
> 
> My model now trains past the 2nd epoch now without any problems, so it must have been some out of memory issue (either gpu or RAM).
> 
> I've got a final question and we can close this issue. I want to use the Dice Loss assuming it works for a multiclass problem (but i haven't found any configurations with it to confirm it). Do we i my model with num_of_classes_of_interest + 1 for the background class or we ignore the background class completely when using Dice Loss?
> 
> Thank you so much for your help!

Hi @xiexinch 
Please provide some examples.
We may add some benchmarks for DiceLoss and LovaszLoss next month.

**Comment by kgiannakelos** [comment]
Any news on this? Also is there a more preferred decode head for multiclass segmentation ? Currently i am using FCN head but i get mediocre results.

**Comment by Junjun2016** [comment]
You can try different decode heads, all decode heads can be used for multiclass segmentation.

**Comment by kgiannakelos** [comment]
@Junjun2016 Yeah i know i can try more heads it just takes 2-3 days to complete the training due to single GPU and large image set. I am just asking if there is some decode head based on experience which performs better than others so i can skip unnecessary trainings which take a lot of time.

**Comment by Junjun2016** [comment]
The conclusion is different from the datasets. You can check which benchmark dataset we provide is more similar to yours, and then choose a method with higher results.

**Comment by kgiannakelos** [comment]
Ok thanks! I will close this issue since i have the information that i need!
