### ISSUE TITLE
404 error on tutorial dataset

### ISSUE THREAD

**Issue by lucy-the-marketer** [open-mmlab/mmsegmentation#757]
To do tutorial, I am getting 404 error for the dataset.
I am using Colab tutorial code without changing any codes.

!wget https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth -P checkpoints

The error message is:
mkdir: cannot create directory ‘checkpoints’: File exists
--2021-08-05 17:00:25--  https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmsegmentation/models/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
Resolving open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)... 52.219.144.62
Connecting to open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)|52.219.144.62|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-05 17:00:25 ERROR 404: Not Found.

Would you please check?

**Comment by xiexinch** [comment]
Hi @lucy-the-marketer 
Thanks for your feedback! You may use this link https://download.openmmlab.com/mmsegmentation/v0.5/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth.
We will fix the tutorial soon.

**Comment by lucy-the-marketer** [comment]
thank you and I am closing the issue.
