### ISSUE TITLE
With newest mmcv==1.3.10, text log bug

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#758]
![image](https://user-images.githubusercontent.com/18137551/128449260-79b8b1dc-e5f8-47c4-b118-bb17787e6a32.png)

**Comment by Junjun2016** [comment]
Hi @jianlong-yuan 
Please provide more details.

**Comment by jianlong-yuan** [comment]
> Hi @jianlong-yuan
> Please provide more details.

What detail do you want?

**Comment by Junjun2016** [comment]
Hi @jianlong-yuan 
Sorry for the bug!
We will fix it ASAP!

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmcv/pull/1252
