### ISSUE TITLE
Why is cropsize set to 769,769 for cityscapes? 

### ISSUE THREAD

**Issue by wusitong98** [open-mmlab/mmsegmentation#763]
I find the config file for cityscapes has two versions: cityscapes.py and cityscapes_769x769.py. I just want to know, why to choice the (769,769) as cropsize in cityscapes_769x769.py? Why not (768,768), which is the power of 2.

By the way, how to choice these two config file if I want to train a model on Cityscapes? Do you have any advice? 

Thanks for your contribution of mmseg for the community! Hope for your reply!

**Comment by kgiannakelos** [comment]
@wusitong98 Check [here](https://github.com/open-mmlab/mmsegmentation/issues/663)

**Comment by MengzhangLI** [comment]
Hi, thanks for your nice help @kgiannakelos 

Best,
