### ISSUE TITLE
mmseg0.16在win编译安装失败问题

### ISSUE THREAD

**Issue by Gavin-Hanks** [open-mmlab/mmsegmentation#768]
![QQ图片20210810112315](https://user-images.githubusercontent.com/49432828/128803515-60691d5c-4539-449a-b9bd-b68e9f860a75.png)
在win上，mmseg存在编译安装错误。报错PermissionError: [WinError 5] 拒绝访问。: '..\\..\\tools' -> 'mmseg\\.mim\\tools'。
请问，如何解决呢？

**Comment by Junjun2016** [comment]
Hi @Gavin-Hanks 
Please check the access permission.
