### ISSUE TITLE
Implementation of DeepLabv2

### ISSUE THREAD

**Issue by nakashima-kodai** [open-mmlab/mmsegmentation#771]
Hi,

DeepLabv2 is still widely used. Therefore, I think it would be more convenient if deeplabv2 can be used in mmsegmentation, is there any plan to implement it?

Thanks.

**Comment by Junjun2016** [comment]
Hi @nakashima-kodai 
Since deeplabv3 is already supported, you can use deeplabv3 or deeplabv3+ instead.

**Comment by fabvio** [comment]
I jump into the discussion just to say that having DeepLabv2 implemented could be helpful to fairly compare with other methods in research, since it is a widely used baseline for domain adaptation purposes.

**Comment by Junjun2016** [comment]
Hi @nakashima-kodai @fabvio 
Got it, PR is welcome and we will benchmark it.
