### ISSUE TITLE
Error when we test some images

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#777]
![image](https://user-images.githubusercontent.com/18137551/129022861-f2134e6b-f5cb-4273-b3b7-c131fdb87713.png)

When we test some images and save images, it will break shown in the figure

**Comment by Junjun2016** [comment]
Have a check for the failed image.

**Comment by jianlong-yuan** [comment]
> Have a check for the failed image.

We've checked it.  When we start two processes on the same machine, an error will be reported. If there is only one process, it can pass smoothly.

**Comment by jianlong-yuan** [comment]
In addition, this question is random

**Comment by Junjun2016** [comment]
So it could be other problems.
Please check it carefully.

**Comment by 459737087** [comment]
I can share you with some solution
1. you should  check out your label. Maybe there is many large number pixel in your label.
2. convert rgb to single channel
3. you can put a little datasets to train, If there is no problem, It shows there is must a problem in your datasets.

**Comment by jianlong-yuan** [comment]
@Junjun2016 @459737087  
Actually, we just save the prediction. According to your meaning, it should be to read GTs. But, we don't read GTs. And the number of classes is just 11. 
When we read rgb images for testing, everything goes well. 
But, when we save predictions, the program has occasional errors.

**Comment by Junjun2016** [comment]
It is hard to debug if it happens randomly.

Can you find which image causes this error?

**Comment by jianlong-yuan** [comment]
> Can you find which image causes this error?

This has nothing to do with what pictures are used. This process occurs in the saved data, which is only related to the prediction results.
