### ISSUE TITLE
class_weight for BCEloss when set use_sigmoid=True

### ISSUE THREAD

**Issue by Tycheslost** [open-mmlab/mmsegmentation#782]
I am a novice in CV. I would like to ask, when setting _use_sigmoid_ to True, I need to provide the weight of each pixel, is there any way to use the weight of each class as for use_sigmoid=Flase. Or how to use weights when using the sigmoid function. 

I saw Focal loss in mmdetection, but it seems to be only for two class. I don't know if there are multiclass versions.

Thanks for your help.

**Comment by MengzhangLI** [comment]
Hi, @Tycheslost .

The first question, you could use [OHEM](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/training_tricks.md#online-hard-example-mining-ohem).

The second question, you need to introduce one-hot encoding method into focal loss (i.e., every class take up one independent dimension in certain array).

Best,
