### ISSUE TITLE
Make a custom dataset

### ISSUE THREAD

**Issue by pablobots** [open-mmlab/mmsegmentation#785]
Hi, I'm looking for a tutorial for make a custom dataset, from raw images.
I don't understand which is the annotation format that mmsegmentation requires an how get that.
Thanks for your help!

**Comment by Junjun2016** [comment]
Hi @pablobots 
The annotation should be label index with each number indicates a specific category.

**Comment by pablobots** [comment]
> Hi @pablobots
> The annotation should be label index with each number indicates a specific category.

Thanks @Junjun2016
Could you give an example for an image? 
Which software is used to do this?

**Comment by Junjun2016** [comment]
Following the dataset preparation tutorial (https://github.com/open-mmlab/mmsegmentation/blob/master/docs/dataset_prepare.md#prepare-datasets).

Take a look at the processed images and annotations.

**Comment by pablobots** [comment]
> Following the dataset preparation tutorial (https://github.com/open-mmlab/mmsegmentation/blob/master/docs/dataset_prepare.md#prepare-datasets).
> 
> Take a look at the processed images and annotations.

In this link I find a list of datasets, but how do I make my custom dataset and what software should I use?

**Comment by Junjun2016** [comment]
You should write some scripts according to your datasets.

The same as https://github.com/open-mmlab/mmsegmentation/tree/master/tools/convert_datasets.

**Comment by pablobots** [comment]
Thanks for your help.
