### ISSUE TITLE
make custom dataset

### ISSUE THREAD

**Issue by haspberry** [open-mmlab/mmsegmentation#786]
I executed the "python tools/convert_datasets/drive.py /path/to/training.zip /path/to/test.zip"instruction. to create custom data

training.zip, test.zip
-images
  - validation
    - img
  - training
    - img

-annotaions
  - validation
    - annotation.json
  - training
    - annotation.json  

but error msg : FileNotFoundError : [Errno 2] No such file directory : 'tmp/tmpykjvn95t2/training/images'

please help me.

Previously, there was a custom made with cocodataset in mmdetection.  But mmsegmentaion is first.
Am I the exact segmentation contour? boundary? I am trying to use mmsegmentaion to find.

**Comment by MengzhangLI** [comment]
Hi, @haspberry 

Seems like the file directory is not been searched by MMSeg. You could check out the path specifically.

Looking forward to your reply.

Best,

**Comment by haspberry** [comment]
@MengzhangLI 
What path are you talking about?
training.zip, test.zip is located in the following path. (home/ubuntu/mmseg/mmsegmentation)
my command is "python tools/convert_datasets/drive.py mmseg/training.zip mmseg/test.zip"

**Comment by MengzhangLI** [comment]
> @MengzhangLI
> What path are you talking about?
> training.zip, test.zip is located in the following path. (home/ubuntu/mmseg/mmsegmentation)
> my command is "python tools/convert_datasets/drive.py mmseg/training.zip mmseg/test.zip"

Hi, because `FileNotFoundError :` is raised when the path is not been read correctly.

Seems like your `tools/convert_datasets/drive.py` is located at `./mmsegmentation/` while `training.zip` and `test.zip` are located out of `./mmsegmentation/` folder?  Move those `.zip` file into `./mmsegmentation/` and have a shot. 

Best,

**Comment by haspberry** [comment]
@MengzhangLI 
First thanks for your help.
Still getting the same error
![경로](https://user-images.githubusercontent.com/50361786/129299100-0dd5346f-8193-4f7b-a004-00f0d45e99f2.PNG)
![terminal](https://user-images.githubusercontent.com/50361786/129299105-ca324993-995f-4eca-8b01-fb74e9e8a41c.PNG)
.

**Comment by MengzhangLI** [comment]
I can't figure out why `/tmp/tmpaSjznirg` is in the error. 

This string is in `https://drive.grand-challenge.org/` or is your customized path?

Best,

**Comment by haspberry** [comment]
@MengzhangLI 
This string is in https://drive.grand-challenge.org/ or is your customized path? 
 - I was trying to use my custom data.  training.zip 
 - In the training file, there is an annotation.json file with img and cocodataset. (This is the datasets I used for mmdetection custom data training.)
 - Shouldn't mmdetection datasets be used in mmsegementaion?... I don't know how to configure the datasets.
 

For example in drivedatasets
│   ├── DRIVE
│   │   ├── images
│   │   │   ├── training
│   │   │   ├── validation
│   │   ├── annotations
│   │   │   ├── training
│   │   │   ├── validation
Are the images and annotations mentioned here different from those in mmdetection?
Thanks again for your kind reply. @

**Comment by haspberry** [comment]
@MengzhangLI 
Thanks for your help. It was a problem with my customdatasets. :'-(
