### ISSUE TITLE
Problem when training custom Dataset

### ISSUE THREAD

**Issue by winterfell2021** [open-mmlab/mmsegmentation#789]
I build my dataset from labelme annotations, which has three categories (A,B,C). I make the mask png by labelme utils shapes_to_label by marking '_background_' as 0, A as 1, B as 2, C as 3. Code:
`lbl, lbl_names = utils.shape.shapes_to_label(img.shape, data['shapes'],label_name_to_value)`

So the png is a pixel map of 0,1,2,3. As all the pictures have been split completely, '_background_'(0) only appears in few pics.
And then I do the following steps:
* Move all file in ade20k folder format, then register dataset:
```
@DATASETS.register_module()
class MyDataset(CustomDataset):
    CLASSES = ('background','A','B','C')
    PALETTE = [[0,0,0],[0,0,255],[0,255,0],[255,0,0]]
    def __init__(self, **kwargs):
        super(WxDataset, self).__init__(
            img_suffix='.jpg',
            seg_map_suffix='.png',
            **kwargs)
        assert osp.exists(self.img_dir)
```
* Modify `init.py` in mmseg source file.
* Modify `dataset_type = 'MyDataset'` in ade20k.py
* Modify `configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py`
changing the head num classes from 150 to 4:
```
decode_head=dict(in_channels=[96, 192, 384, 768], num_classes=4),
auxiliary_head=dict(in_channels=384, num_classes=4))
```
Then train. But when evaluation, the last category **C** always got acc with 0, except background get high acc. 

I tried to see the visual result on test set using code:
```python
from mmseg.apis import inference_segmentor, init_segmentor
import mmcv
import os
config_file = 'configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py'
checkpoint_file = 'out/latest.pth'

model = init_segmentor(config_file, checkpoint_file, device='cuda:0')
_dir = 'data/test/'

import numpy as np
import skimage.io
from tqdm import tqdm
os.system('rm -rf result && mkdir result')
for vo in tqdm(os.listdir(_dir)):
    if '.jpg' in vo:
        img =  _dir + vo
        result = inference_segmentor(model, img)
        model.show_result(img, result, out_file='result/' + vo, opacity=0.2)
```
All pictures mask with wrong color.
Please tell me which step is wrong, thank you!

**Comment by winterfell2021** [comment]
solved by fill background pixel by 1

**Comment by xiximelon** [comment]
> solved by fill background pixel by 1

can you describe more particularly . Do u mean that the  make the background of custom dataset from (0,0 ,0)to (0,0,1) or from label 0 to label 1. Thanks! I met the same question as you ,i got the prediction results marked with wrong color!

**Comment by Lsz-20** [comment]
@MengzhangLI @winterfell2021 the same question as @xiximelon ,I have the wrong color either.
