### ISSUE TITLE
Error in accuracy computation?

### ISSUE THREAD

**Issue by dadada101** [open-mmlab/mmsegmentation#792]
hi, for the new release version , as for accuracy evaluation:
1. https://github.com/open-mmlab/mmsegmentation/blob/2acd563231cf83ff0b9edad9a92ffe2f0d3dd9bb/mmseg/models/losses/accuracy.py#L47
 correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True) should be corrected as :
 correct_k = correct[k].reshape(-1).float().sum(0, keepdim=True)?

2. in target, there are 255 ignored elements, it seems not excluded in the evaluation process

**Comment by Junjun2016** [comment]
Hi @dadada101 
1. The difference is Top-K accuracy or K-th accuracy.
2. The ignore index will be ignored in the evaluation process.
