### ISSUE TITLE
what does "img_norm_cfg" mean?

### ISSUE THREAD

**Issue by wujf98** [open-mmlab/mmsegmentation#793]
Hi, thank you for your code, I found that the following code appears in different datasets, what does it mean?
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

If I use a custom dataset, should I modify it? Actually, in addition to RGB channels, my dataset also has infrared band and DEM, it means one image has 5 channels, What should I pay attention to when customizing the dataset?

**Comment by MengzhangLI** [comment]
Hi, @wujf98:

The `img_nor_cfg` is image normalization configuration which is used for image normalization before being inputed into network. It is related with our used pretrained models (most of them are based on ImageNet) and pretrained models are very important for model training.

Thus, if you also want to use [pretrained model](https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json), please keep the `img_norm_cfg` identical.

Right now, MMSegmentation just support RGB input, we would consider add more features for other modalities or input images.

Best,

**Comment by wujf98** [comment]
Thanks a lot, @MengzhangLI
