### ISSUE TITLE
Will the mmsegmentation support BiSeNetV1 and  BiSeNetV2 in the future?

### ISSUE THREAD

**Issue by ChenDirk** [open-mmlab/mmsegmentation#797]
Hi, at present, mmsegmentation does not support a lot of real-time networks, it seems that only Fast SCNN. Will the mmsegmentation support more real-time networks, such as BiSeNetV1 and  BiSeNetV2 in the future?

**Comment by MengzhangLI** [comment]
Hi, BiSeNetV2 is on the way.

Best,

**Comment by MengzhangLI** [comment]
Hi, @ChenDirk 

Sorry for late reply, BiSeNet V1 & V2 are both supported, please check it out!

Best,
