### ISSUE TITLE
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

### ISSUE THREAD

**Issue by w-yasuo** [open-mmlab/mmsegmentation#803]
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

**Comment by MengzhangLI** [comment]
Hi, seems like your installation of mmcv-full is not successful.

Please check the website: https://github.com/open-mmlab/mmcv

Best,

**Comment by wujiang0156** [comment]
> ImportError: DLL load failed while importing _ext: 找不到指定的程序。

please ,check your mmcv version, which depending on the type of system, CUDA version, PyTorch version, and MMCV version
