### ISSUE TITLE
Implementing iteration based class_weights

### ISSUE THREAD

**Issue by prnvjb** [open-mmlab/mmsegmentation#807]
Hi everyone,

In Segformer repo somebody implemented this functionality:

> i use class weight [1,2] at beging of train,and change is to [1,1] after 2000 iter,the result is beter
> 
> 2021-06-16 22:13:30,789 - mmseg - INFO - per class results:
> Class                  IoU       pAcc        Acc     Recall
> background          100.00     100.00       0.00       0.00
> crack                80.51      91.85      98.04     100.00

I searched through mmseg documentation but haven't find any code examples regarding. How could I implement such implementation to change class_weights based on iterations?

Thanks..

**Comment by MengzhangLI** [comment]
Hi, @prnvjb 

You can set `class_weight` in `loss_decode`.

Related Issue you mentioned from `segformer`:  https://github.com/NVlabs/SegFormer/issues/6

Related PR about `class_weight`: https://github.com/open-mmlab/mmsegmentation/pull/513

Related example of config file, using`CGNet` as an example: https://github.com/open-mmlab/mmsegmentation/blob/fb24bf54b69ad8e83098e4b18d789f25d0762874/configs/_base_/models/cgnet.py

Noted:
(1) CGNet is tested on `Cityscapes` thus you can find there are `19` weights in `class_weight` list in the config file I provided above.

(2) If I remember well, currently MMSeg does not support change class weight during training. You can only set class weight before training.

Best,
