### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'prev_output'

### ISSUE THREAD

**Issue by CuberrChen** [open-mmlab/mmsegmentation#808]
Hi! im tring to reproduce PointRend by myself. but when i change the mmseg code to my style code. i find there is a input for PointHead that i can't understand. what should i do if i want to solve it?

**Comment by MengzhangLI** [comment]
Hi, @CuberrChen 

Could you give more information such as your error log?

Based on your description, I think problem you met is a lack of `prev_output (list[Tensor]): Prediction of previous decode head. `

Thus, you have to provide your own code with the prediction previous decoder head. Only current prediction is not enough.

Best,

**Comment by CuberrChen** [comment]
@MengzhangLI Thanks for your reply!  I has realized the key point of my problem.
