### ISSUE TITLE
Model training using TIF satellite data

### ISSUE THREAD

**Issue by CarlosFora** [open-mmlab/mmsegmentation#810]
Hi,

I was wondering if there is a way to use TIF data, given that I am trying to train a model to detect clouds on Sentinel-2 satellite images, which contain 12-channels, hence the need for TIF data format.

I am aware of this issue #559, but I would like to know if data loaders can be manually modified so that multi-channel TIF images are loaded into the pipeline.

Thanks in advance,
Borja García

**Comment by MengzhangLI** [comment]
Hi,
I am sorry that right now MMSegmentation mainly support 3 channels i.e., RGB image format. We realize it is very important to add more flexibilities on ohter image format, whose channel numbers are not 3, especially. We would support those image format in the future.

Right now we only support [RGB2gray](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/transforms.py#L714), while Gray(or other format whose channel numbers are not `3`) to RGB is not supported. But hoping the link above is useful to you.

Best,

**Comment by CarlosFora** [comment]
Okay, thanks for the info. Closing the issue now.
