### ISSUE TITLE
the train setting of PointRend(CVPR2020)

### ISSUE THREAD

**Issue by CuberrChen** [open-mmlab/mmsegmentation#812]
Hi! im tring to repoduce the result of PointRend. i can't find the gpu numbers setting of mmseg implementation for PointRend(ResNet101,FPN,Cityscapes512*1024). if i am right, the nums of gpu is 4 V100? and the batchsize is 2 for per gpu? 
i am looking forward your reply.
best,

**Comment by MengzhangLI** [comment]
Hi, @CuberrChen 

The default environment of MMSegmentation is `4 GPUs (V100) x 2 batch sizes`.

Best,

**Comment by CuberrChen** [comment]
@MengzhangLI Thanks
