### ISSUE TITLE
Can you provide an illustration of the architecture (i.e how backbone and decode head work) ?

### ISSUE THREAD

**Issue by kgiannakelos** [open-mmlab/mmsegmentation#820]
Hello,

is it possible to provide some visual illustration of the architecture? 

For example how the backbone, decode head and auxiliary heads work together in this [config](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py)? Is only the encoder part of UNet used? And if yes, how does the FCN acts as a decoder in this case? 

I believe it would help many people understand how mmsegmentation works behind the scenes and avoid digging too much in the code to find such details.

Thank you!

**Comment by MengzhangLI** [comment]
Hi, @kgiannakelos 

Thanks for your suggestions, because lack of enough developer, we did not add this feature into our model. We would consider it and take it into our to-do list.

Best,

**Comment by kgiannakelos** [comment]
@MengzhangLI I think you misunderstood what i meant. It is not a feature that you can integrate into your model. 

What i meant is that it would be good to have a picture and some description about how does the architecture work. It is not something that needs development. It's a documentation thing.
