### ISSUE TITLE
Can we use both fastai and mmsegmentation?

### ISSUE THREAD

**Issue by bowenroom** [open-mmlab/mmsegmentation#835]
Can we use both fastai and mmsegmentation? Fastai supply us with a series of methods of data blocks and training tricks which reduce the training time at a large margin, mmsegmentation supply us with a lot of useful models. Can we conveniently  use both of them?

**Comment by Junjun2016** [comment]
Hi @bowenroom 
Could you please provide more details about data blocks?

**Comment by bowenroom** [comment]
This is the fastai datablock website and there is a lot of useful tricks implemented in fastai package. We really hope we could integrate both fastai and mmsegmentation.

**Comment by MengzhangLI** [comment]
Hi, @bowenroom

We just provide some [training ticks](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/training_tricks.md), could you plese list some training tricks here especially which you think help your training a lot ? We hope we could integrate them into MMSeg in the future.

Best,
