### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by kaishijeng** [open-mmlab/mmsegmentation#836]
I am doing a training and like to change batch size of the training.
Do you know which file contains batch size which I can change?

Thanks,

**Comment by MengzhangLI** [comment]
Hi, @kaishijeng 

For example, if you want to change `batch_size` in from `2` to `4` in [pspnet_r50-d8_512x1024_80k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/pspnet/pspnet_r50-d8_512x1024_80k_cityscapes.py). You just need to add these lines:

```
_base_ = [
    '../_base_/models/pspnet_r50-d8.py', '../_base_/datasets/cityscapes.py',
    '../_base_/default_runtime.py', '../_base_/schedules/schedule_80k.py'
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,)
```

Best,

**Comment by kaishijeng** [comment]
@MengzhangLI 

   It works and thanks
