### ISSUE TITLE
when i run   ./tools/dist_train.sh configs/fcn/fcn_r50-d8_512x512_40k_voc12aug.py 4    a error RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1587428091666/work/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled system error, NCCL version 2.4.8

### ISSUE THREAD

**Issue by zhujiesuper** [open-mmlab/mmsegmentation#84]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by zhujiesuper** [comment]
thank you ! i solve this issue

**Comment by coolKeen** [comment]
> thank you ! i solve this issue

Hi, I also meet this problem. Could you tell me how to sovle it?
Thanks!

**Comment by wsj20010128** [comment]
> thank you ! i solve this issue

I also met this problem. Could you please let me know how you solved it? Thank you!
