### ISSUE TITLE
How to make sure that RESNET-50 weights loaded properly?

### ISSUE THREAD

**Issue by ramchandracheke** [open-mmlab/mmsegmentation#842]
```python 
Config:
norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    backbone=dict(
        type='ResNetV1c',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True,
        pretrained='/work/Imagenet/resnet50-19c8e357.pth'
    ),
```

I am using about code for loading a weights from a local disk. How to make sure that RESNET-50 weights loaded properly?

Please help me.

**Comment by MengzhangLI** [comment]
> ```python
> Config:
> norm_cfg = dict(type='BN', requires_grad=True)
> model = dict(
>     type='EncoderDecoder',
>     backbone=dict(
>         type='ResNetV1c',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         dilations=(1, 1, 2, 4),
>         strides=(1, 2, 1, 1),
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=False,
>         style='pytorch',
>         contract_dilation=True,
>         pretrained='/work/Imagenet/resnet50-19c8e357.pth'
>     ),
> ```
> 
> I am using about code for loading a weights from a local disk. How to make sure that RESNET-50 weights loaded properly?
> 
> Please help me.

Hi, you should make sure your internet is linked, thus MMSegmentation would automatically downloads pretrained model.

If your Internet is not good, please download the model from [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json) in advance. (For your config, it should be  "resnet50_v1c": "https://download.openmmlab.com/pretrain/third_party/resnet50_v1c-2cccc1ad.pth".) And put this `.pth` file into suitable place. 

Please make sure your file `resnet50-19c8e357.pth` is in suitable directory (are you sure your MMSegmentation could find this absolute directory `'/work/Imagenet/`? ) and its version is ResNet50-V1c. 

Best,

**Comment by ramchandracheke** [comment]
Hi @MengzhangLI 

Thank you for your help.

```python

# Build the detector
model = build_segmentor(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Print model's state_dict
print("Model's state_dict:")
for param_tensor in model.state_dict():
    print(param_tensor, "\t", model.state_dict()[param_tensor].size())

from collections import OrderedDict
new_state_dict = OrderedDict()

ckpt1 = torch.load('/work//Resnet_r50_400ep_md5_919c6612.pth')
ram = ckpt1['model']

# create new OrderedDict that does not contain `module.`
from collections import OrderedDict
new_state_dict = OrderedDict()

# because my pretrained model is in format  module.encoder.layer3.1.conv1.weight and your downloaded model is in format 
 backbone.layer3.1.conv1.weight. Therefore I am replacing module.encoder., backbone. rest of the things are same.

for k, v in ram.items():
    name =  k.replace("module.encoder.","backbone.")
    new_state_dict[name] = v

print('Before.layer1.0.conv1.weight ', "\t", model.state_dict()['backbone.layer1.0.conv1.weight'])

model.load_state_dict(new_state_dict,strict=False)

print('After.layer1.0.conv1.weight ', "\t", model.state_dict()['backbone.layer1.0.conv1.weight'])

# train_segmentor(model, datasets, cfg, distributed=False, validate=True, meta=dict())

```

I have ran the code and checked that weights are updated. Can you please tell me these weights will be taken as starting weights of train_segmentor(model, datasets, cfg, distributed=False, validate=True, meta=dict()) can again change weight?

Thanks in advance.
