### ISSUE TITLE
TypeError: cannot unpack non-iterable int object: h_stride, w_stride = int(self.test_cfg.stride) 

### ISSUE THREAD

**Issue by MarioCarvalhoBr** [open-mmlab/mmsegmentation#843]
My Setup: 
Python 3.8.11 (default, Aug  3 2021, 15:09:35) 

I get the error with fcn_unet_s5-d16_256x256_40k: 

```
 h_stride, w_stride = int(self.test_cfg.stride)
TypeError: cannot unpack non-iterable int object


h_crop, w_crop = self.test_cfg.crop_size
TypeError: cannot unpack non-iterable int object
```
I fix this problem editing file: 
**_mmsegmentation/mmseg/models/segmentors/encoder_decoder.py_**
Lines 160 and 161: 
```
        h_stride, w_stride = self.test_cfg.stride
        h_crop, w_crop = self.test_cfg.crop_size
```

To:
```
        h_stride = self.test_cfg.stride
        w_stride = self.test_cfg.stride

        h_crop = self.test_cfg.crop_size
        w_crop = self.test_cfg.crop_size
```
or
```
        h_stride = w_stride = self.test_cfg.stride
        h_crop = w_crop = self.test_cfg.crop_size
```

I hope your correction and that my issue can contribute to the project. 
Congratulations for the project.

At.te
Mário Carvalho

**Comment by MengzhangLI** [comment]
Hi, I used this config file last week and it works.

Do you use your customized dataset?

**Comment by MarioCarvalhoBr** [comment]
> Hi, I used this config file last week and it works.
> 
> Do you use your customized dataset?

Yes, my dataset is customized.
