### ISSUE TITLE
Need help understanding Resize

### ISSUE THREAD

**Issue by MrOCW** [open-mmlab/mmsegmentation#846]
HI, assuming my training dataset has image sizes of H W = (480,640), and having Resize at (2048,1024) with ratio range (0.5,2.0), does this mean my images will all resized before training to a random size between (2048*0.5~2048*2 , 1024*0.5~1024*2.0) with  width = max(2048*0.5~2048*2 , 1024*0.5~1024*2.0) and height = min(2048*0.5~2048*2 , 1024*0.5~1024*2.0) ??

How does the resize work?

for RandomCrop, the crop_size can just be any value that is smaller than the Resize img_scale?

**Comment by MengzhangLI** [comment]
What does `(20480.5~20482 , 10240.5~10242.0) ` mean?

**Comment by MrOCW** [comment]
oop sorry it auto formatted


Hi, assuming my training dataset has image sizes of H W = (480,640), and having Resize at (2048,1024) with ratio range (0.5,2.0), does this mean my images will all resized before training to a random size between (2048 x 0.5~2048 x 2 , 1024 x 0.5~1024 x 2.0) with width = max(2048 x 0.5~2048 x2 , 1024 x 0.5~1024 x 2.0) and height = min(2048 x 0.5~2048 x 2 , 1024 x 0.5~1024 x 2.0) ??

How does the resize work?

for RandomCrop, the crop_size can just be any value that is smaller than the Resize img_scale?

**Comment by MengzhangLI** [comment]
First: 
Q1: `my training dataset has image sizes of H W = (480,640), and having Resize at (2048,1024) with ratio range (0.5,2.0), does this mean my images will all resized before training to a random size between (2048 x 0.5 to 2048 x 2 , 1024 x 0.5 to 1024 x 2.0) with width = max(2048 x 0.5 to 2048 x 2 , 1024 x 0.5 to 1024 x 2.0) and height = min(2048 x 0.5 to 2048 x 2 , 1024 x 0.5 to 1024 x 2.0) ??`
A1: Yes, you are right.

Q2:  `for RandomCrop, the crop_size can just be any value that is smaller than the Resize img_scale`
A2: No, the crop size could be larger than resize img_scale, MMSeg would automatically keep the smaller resized shape if crop size is larger.

**Comment by MrOCW** [comment]
ok got it. so to provide an example, say Cityscapes with image dimensions (1024,2048), if my config 
Resize img_scale = (480,640), ratio_range = (1.0,1.0),
RandomCrop = (480,640)
Q1. all images in Cityscape will be resized to (480,640)?
Q2. RandomCrop will be useless in this case?

**Comment by MengzhangLI** [comment]
> ok got it. so to provide an example, say Cityscapes with image dimensions (1024,2048), if my config
> Resize img_scale = (480,640), ratio_range = (1.0,1.0),
> RandomCrop = (480,640)
> Q1. all images in Cityscape will be resized to (480,640)?
> Q2. RandomCrop will be useless in this case?

Yes, in this situation it would be useless.

**Comment by ThejanW** [comment]
This helped. Thanks..
