### ISSUE TITLE
Is there a way to register a custom evaluation metric?

### ISSUE THREAD

**Issue by ThejanW** [open-mmlab/mmsegmentation#847]
Is there a way to register a custom evaluation metric by defining a class? 
If possible, can you provide an example?

**Comment by MengzhangLI** [comment]
Hi, right now our `metric` is not managed by register.

**Comment by ThejanW** [comment]
Hi @MengzhangLI  thank you for the prompt response. How do I come up with a new metric and incorporate it within my training pipeline?

**Comment by MengzhangLI** [comment]
Hi, @ThejanW 
Please check out this PR: [add metric mFscore](https://github.com/open-mmlab/mmsegmentation/pull/509)!

You can add metric you want just like this `Fscore`, here is change files comparison: https://github.com/open-mmlab/mmsegmentation/commit/e16e0e303bebfd3b8362bc52bac58e27aed8fb52

Hoping it is useful to you.

Best,

**Comment by ThejanW** [comment]
@MengzhangLI  this PR helped me understand how it's done. Thanks for pointing out towards the right direction.
