### ISSUE TITLE
How to stop downloading .pth files

### ISSUE THREAD

**Issue by zjk958162734** [open-mmlab/mmsegmentation#85]
Hello, I would like to ask, when I execute the train.py file, it will automatically download the .pth file. If I manually download the file and put it in the corresponding location, how should I stop the download that comes with the system, and Come to read in the .pth file I manually put in, thanks.

**Comment by zjk958162734** [comment]
Sorry to disturb you again, I have a new question that I want to consult. I have a total of four GPUs. Now devices:0 are occupied. When I use multi-card for training, 
my code is: CUDA_VIDIBLE_DEVICES=1, 2,3 sudo bash ./tools/dist_train.sh configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py 2. 
At the same time, my gpu-ids is displayed as [1,2], but why does it prompt that my GPU: 0 has insufficient memory? , I have clearly specified other GPUs, I hope you can help me answer them, thank you.

**Comment by xvjiarui** [comment]
It should be `CUDA_VISIBLE_DEVICES`.
