### ISSUE TITLE
Training a model on custom dataset from scratch

### ISSUE THREAD

**Issue by cspearl** [open-mmlab/mmsegmentation#853]
I want to train a segmentation model on my custom dataset- binary segmentation but from scratch. My masks are black and white.
So if i set cfg.load_from = None. Will that work and training will start from scratch?

Also is it possible to train model for images having 4 channels instead of just 3 ? 4 = 3(RGB)+1(NIR) 
How can I use this repo to train such images if you could please help.
Thank you!

**Comment by MengzhangLI** [comment]
Hi, 
(1) Just set `pretrained=None,` in config file, such as [this config](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/pspnet_r50-d8.py).

(2) Right now MMSegmentation just supports 3 channels (i.e., RGB) or 1 channels (i.e., repeat 3 times in `channel` dimension). We would support other channels in the future. The main difficulities of it is data augmentation policy  are based on 2D.

Best,
