### ISSUE TITLE
mmcv-full version not satisfied according to the given url in Dockerfile

### ISSUE THREAD

**Issue by luciagan** [open-mmlab/mmsegmentation#856]
I built the environment from the given Dockerfile with mmcv-full part as belows
> RUN pip install mmcv-full==latest+torch1.6.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html

but the latest version of mmcv-full is 1.3.5 according to the given url [https://download.openmmlab.com/mmcv/dist/index.html](url), which causes the following ERROR when start training:

`*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from mmseg import __version__
  File "/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=(1, 3, 7, 0, 0, 0), <=(1, 4, 0, 0, 0, 0).
Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from mmseg import __version__
  File "/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=(1, 3, 7, 0, 0, 0), <=(1, 4, 0, 0, 0, 0).
Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from mmseg import __version__
  File "/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=(1, 3, 7, 0, 0, 0), <=(1, 4, 0, 0, 0, 0).
Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from mmseg import __version__
  File "/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=(1, 3, 7, 0, 0, 0), <=(1, 4, 0, 0, 0, 0).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=3', './configs/setr/setr_pup_512x512_160k_b16_ade20k_jslseg.py', '--launcher', 'pytorch', '--load-from', 'checkpoints/setr/pretrained/setr_pup_512x512_160k_b16_ade20k_20210619_191343-7e0ce826.pth']' returned non-zero exit status 1.
`

**Comment by MengzhangLI** [comment]
Hi, based on your description. I think you should use MMCV-full version `>=1.3.7` and `<1.4.0`, which would be compatibal with latest MMSegmentation.

I can not open the link you mention "latest version==1.3.5".  But anyways, you can follow the instruction [here](https://github.com/open-mmlab/mmcv) for solving it. I will check out dockerfile on my own.

Please let us know whether you fix it after MMCV-full installation.

Best,

**Comment by luciagan** [comment]
Hi, @MengzhangLI  it works following the mmcv instruction you suggested. I install the correct mmcv through `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`

Thanks a lot for your timely reply.

Best,

**Comment by luciagan** [comment]
Hi, @MengzhangLI maybe it is still necessary to check the Dockerfile anyway. It seems that [the given url](https://download.openmmlab.com/mmcv/dist/index.html) in the Dockerfile does not match mmsegmentation-v0.17.0 when installing mmcv, because the latest version of mmcv in this given url is 1.3.5 while it requires mmcv>=(1, 3, 7, 0, 0, 0), <=(1, 4, 0, 0, 0, 0) using v0.17.0.

**Comment by MengzhangLI** [comment]
OK, I will write it down and discuss it with my colleagues.

Thanks for your nice reminder.

Best,

**Comment by luciagan** [comment]
Thanks a lot. Wish you all the best! @MengzhangLI

**Comment by Junjun2016** [comment]
Hi @luciagan 
FIx https://github.com/open-mmlab/mmsegmentation/pull/860
Have a try.

**Comment by luciagan** [comment]
Hi, @Junjun2016 thanks!
