### ISSUE TITLE
UNetDecoder dim mismatched problem

### ISSUE THREAD

**Issue by jjjcs** [open-mmlab/mmsegmentation#858]
Hi, for some reasons, there are problems when i test my model use the standard test config pipeline. So i just formulate my model my self. The model is trained well and when i load the trained state_dict, it matched alos well. But only when i input an image with correct size (3,256,256) to predict the result, there is a mismatched problem.
RuntimeError: Given groups=1, weight of size [128, 256, 3, 3], expected input[16, 768, 32, 32] to have 256 channels, but got 768 channels instead
I dont know why, the model trained well, but when predict with same dataset, problem appears. How can i fix it?

encoder = VGG(in_channel=3, init_channels=32, num_blocks=2)
center = MCTrans(
        d_model=128,
        nhead=8, # nhead = 8
        d_ffn=512,
        dropout=0.1,
        act="relu",
        n_levels=3,
        n_points=4,
        n_sa_layers=6
)
decoder = UNetDecoder(in_channels=[32, 64, 128, 128, 128])
bshead = BasicSegHead(in_channels=32, num_classes=2,
                      post_trans=[dict(type="Activations", softmax=True),
                                  dict(type="AsDiscrete", argmax=True)],
                      losses=[dict(type="DiceLoss", softmax=True, to_onehot_y=True),
                              dict(type="CrossEntropyLoss"),
                              dict(type="FLoss")])
auxhead = MCTransAuxHead(
        d_model=128,
        d_ffn=512,
        act="relu",
        num_classes=2,
        in_channles=[32, 64, 128, 128, 128],
        losses=[dict(type="MCTransAuxLoss", sigmoid=True, loss_weight=0.1)]
)
model = nn.Sequential(OrderedDict([
    (('encoder', encoder)),
    (('decoder', decoder)),
    (('seg_head',bshead)),
    (('center', center)),
    (('aux_head', auxhead)),
                    ]))

**Comment by MengzhangLI** [comment]
Seems like some concatenation operation made channels sum up `768 = 512 + 256`.

Based on your description, the training works well while testing raises error. 

It should have nothing to do with channels between training and testing. I will check it in the next few days. You'd better ask author of MCTrans how he combining MMSegmentation and MONAI if you want to solve this problem quickly.

Looking forward to your feedback if you solve this problem. ;)

Best,

**Comment by jjjcs** [comment]
Just few hours after the issue, the problem solved, although i have been working with it for few days. 玄学

**Comment by MengzhangLI** [comment]
How did you modify the code?

**Comment by jjjcs** [comment]
I have make the module sequential wrong, but just focused on the source code.
