### ISSUE TITLE
torch.distributed.launch API alternative?

### ISSUE THREAD

**Issue by prnvjb** [open-mmlab/mmsegmentation#861]
As we know, in the current mmsegmentation framework we launch distributed training as:
```
python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
    $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}
```
However is there any way I can call torch.distributed.launch as an api form within the code, so I can configure $GPUS based on availability before training.

Thanks!!

**Comment by MengzhangLI** [comment]
Hi, you can have a shot, be like:
`CUDA_VISIBLE_DEVICES=0,1 ./tools/dist_train.sh configs/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes.py`
