### ISSUE TITLE
mIoU large gap between my trained model and the repository reported

### ISSUE THREAD

**Issue by hellohwang** [open-mmlab/mmsegmentation#87]
Hi:
I have trained and evaluated with the config file(https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3plus/deeplabv3plus_r50-d8_512x1024_40k_cityscapes.py), finally, I got mIoU = 78.59(no MS), while mIoU reported from this repo with the config is 79.61, almost 1.1 mIoU drop, is it normal?

**Comment by hellohwang** [comment]
@hellock

**Comment by hellohwang** [comment]
I got the same result when applying the multi-scale testing, and I closed the issue.

**Comment by hellohwang** [comment]
@xvjiarui Can you give an explanation, please.

**Comment by yamengxi** [comment]
> @xvjiarui Can you give an explanation, please.

We are searching for the reason, please wait.

**Comment by Wangt-CN** [comment]
I have tried the non_local model with r50 on Cityscapes dataset. (/configs/nonlocal_net/nonlocal_r50-d8_769x769_40k_cityscapes.py).
I didn't change anything in the config and just run.
However, the mIoU also had a large gap with your reports. (**77.4 and 79.9**)
![image](https://user-images.githubusercontent.com/32795963/91582508-7ec3c180-e982-11ea-85f2-eb3c01863746.png)

I am very confused.

**Comment by xvjiarui** [comment]
Hi @Wangt-CN 
We are actively looking into these. We will get back to you ASAP.

**Comment by Wangt-CN** [comment]
Hi @xvjiarui . Thanks a lot for your quick reply and look forward to the update.
Moreover, I have also just tried the nonlocal network on Pascal VOC Aug dataset and the performance is also a little gap.
Just for your reference.
![image](https://user-images.githubusercontent.com/32795963/91628556-79528f80-e9f3-11ea-8448-1832f34323a5.png)

**Comment by xvjiarui** [comment]
Hi @Wangt-CN @hellohwang 
Here is some update. I just re-benchmark models of ResNet 101, which match the model zoo. We are still actively investigating why ResNet50 drops.

**Comment by Wangt-CN** [comment]
Hi, @xvjiarui , do you have any ideas? From my perspective, I found that most of the ResNet-50 models seem cannot match the reported accuracy and some have even huge gaps (>1 mIoU). 
I haven't tried ResNet101 yet. But I have tried for a long time in R50 but it still doesn't work. Unfortunately, maybe I don't have more time to solve it. Hope you guys can find the problem. 
And if there's something wrong with the reported R50 model accuracy, it would be appreciated if you guys can correct the model zoo readme to avoid misunderstanding. Thanks a lot.

**Comment by xvjiarui** [comment]
Hi @Wangt-CN 
Sorry for the late reply. 
Sometimes, the results on the cityscapes dataset could fluctuate a lot. You may train with `--seed 0` argument, which will help reduce the variance to ~0.5 mIoU. 
All models in modelzoo are trained with `--seed 0`. And we also tried this recently and find the results are consistent with modelzoo within 0.5 mIoU. You may also have a try.

**Comment by Wangt-CN** [comment]
Thanks a lot for your reply and I will have a try.
Moreover, I want to ensure that the default config is the ms+fp setting during validation and test?

**Comment by xvjiarui** [comment]
Hi @Wangt-CN 
The default is single scale testing without ms+flip. To enable ms+flip, you may use `--aug-test` to run `test.py`.

**Comment by Wangt-CN** [comment]
ah....Sorry. I am still new in segmentation. I think I didn't enable ms_flip during testing, which means the performance gap may be reasonable. Sorry again and I will check. Thanks a lot for your help.

**Comment by Beanocean** [comment]
Hi @xvjiarui,

I have tried to set the random seed `--seed 0` in my experiments, but still can't reproduce the performance of the nonlocal network in cityscapes. I have run the resnet50 experiments for 5 times, and the highest score is 77.64 in single scale test mode. And the experiments for 101 is 76.56. I conducted my experiments on 4 GPU cards. Should I use 8 cards for training, or is there anything else I need to pay attention to?

**Comment by noahcao** [comment]
I have a similar issue that I used the default config of **deeplabv3plus-d8-512x1024-40k-cityscape.py**, my output mIoU accuracy is only 79.0, having a 1.21 mIoU gap with the reported 80.21 mIoU in this repo. I didn't try --seed 0 yet. will update the result after that.
