### ISSUE TITLE
How to insert custom plugin into the backbone?

### ISSUE THREAD

**Issue by foreverbest** [open-mmlab/mmsegmentation#870]
Hi, thanks for your excellent job on this project!
Currently I would like to applied attention mechanism （e.g., CBAM） into the backbone (i.e., ResNet-r50). According to the original paper, I should put it in every residual blocks. I found the plugin function in `resnet.py` but unfortunately it seem it didn't support yet. Could you give me some insight on how to apply them in to the bottleneck? Should I define the CBAM somewhere (I don't know where to define) or simply put the code into the Bottleneck class in  `resnet.py`?
Thanks again for your patience.

**Comment by Junjun2016** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/plugins/dropblock.py#L10,  https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/gcnet/mask_rcnn_r50_fpn_r4_gcb_c3-c5_1x_coco.py#L3, https://github.com/open-mmlab/mmcv/blob/99088c81a8db77ec4bb3fb16f8703a82e2433210/mmcv/cnn/bricks/conv_module.py#L15,  https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/cnn/bricks/generalized_attention.py, https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/cnn/bricks/non_local.py#L245,  and https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/cnn/bricks/context_block.py#L16.

**Comment by Junjun2016** [comment]
First, you should register `CBAM` to `PLUGIN_LAYERS` as `ContextBlock` does, and then [build it from config](https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/gcnet/mask_rcnn_r50_fpn_r4_gcb_c3-c5_1x_coco.py#L3).

**Comment by foreverbest** [comment]
Thanks very much!
But the code seems to be located in mmcv.

**Comment by foreverbest** [comment]
sop

**Comment by foreverbest** [comment]
Thanks very much!

**Comment by foreverbest** [comment]
Anathor question: I tried context_block plugin and print the network structure by `tools/print_config.py`, but I cannot find it. More over, the parameters calculated by `tools/get_flops.py` didn't change neither. 
I set up the plugins by:

```
def __init__(self, **kwargs):
        super(ResNetV1c_context, self).__init__(
            deep_stem=True, avg_down=False, **kwargs)
        self.plugins=[
            dict(cfg=dict(type='context_block', ratio=1. / 4),
            stages=(False,True,True,True),
            position='after_conv3')
        ]
```
I'm not sure I'm doing the right thing. And I want to know how can I verify that the plugin was successfully installed.

**Comment by Junjun2016** [comment]
Check the model architecture in the log.
