### ISSUE TITLE
Test on Cityscapes server

### ISSUE THREAD

**Issue by ydhongHIT** [open-mmlab/mmsegmentation#875]
I follow the instructions in your document to form the png files which can be evaluated by the official server. But the generated files are colored images instead of images encoded with class ids.

**Comment by Junjun2016** [comment]
> I follow the instructions in your document to form the png files which can be evaluated by the official server. But the generated files are colored images instead of images encoded with class ids.

Right.

**Comment by ydhongHIT** [comment]
> > I follow the instructions in your document to form the png files which can be evaluated by the official server. But the generated files are colored images instead of images encoded with class ids.
> 
> Right.

How can I get the files which can be directly evaluated on the official server, namely images encoded with class ids.

**Comment by Junjun2016** [comment]
Please follow [this tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/inference.md#test-a-dataset).

**Comment by Junjun2016** [comment]
The formatted images are enough.

**Comment by ydhongHIT** [comment]
> The formatted images are enough.

I have tried it. The formatted images are colored images which can not be directly submitted to the server.

**Comment by Junjun2016** [comment]
> Please follow [this tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/inference.md#test-a-dataset).

This tutorial works, please check it carefully and try it again.

**Comment by ydhongHIT** [comment]
> > Please follow [this tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/inference.md#test-a-dataset).
> 
> This tutorial works, please check it carefully and try it again.

Thanks very much. It's right. The colored images can also be directly evaluated.

**Comment by wzr0108** [comment]
> Please follow [this tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/inference.md#test-a-dataset).

The page is invalid
