### ISSUE TITLE
Do mmsegmentation support Apex of NVIDIA?

### ISSUE THREAD

**Issue by buaalingming** [open-mmlab/mmsegmentation#88]
hi, 
   Do mmsegmentation support Apex of NVIDIA(https://github.com/NVIDIA/apex)?
   And what's difference between Mmsegmentation's "Mixed Precision (FP16) Training"  and Apex.
   Thank you.

**Comment by xvjiarui** [comment]
Hi @buaalingming 
The basic logic is the same. But we implemented it by ourselves.
