### ISSUE TITLE
Question about `align_corners=True`

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#887]
Hi, dear authors!
Sorry to bother you.
I have a question about `align_corners=True`
I want to set `align_corners=True` to improve Dice metric，but when I set `align_corners=True`, the following warning always appears：

train: UserWarning: When align_corners=True, the output would more aligned if input size (80, 80) is `x+1` and out size (320, 320) is `nx+1`

val: UserWarning: When align_corners=True, the output would more aligned if input size (104, 104) is `x+1` and out size (416, 416) is `nx+1`

Here is my config about `train_pipeline` and `test_pipeline`:
```
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize',
         img_scale=[(320, 320), (416, 416)],
         keep_ratio=True),
    dict(type='RandomCrop',
         crop_size=crop_size,
         cat_max_ratio=0.9),
    dict(type='RandomFlip', prob=0.5),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        keymap=dict(img='image', gt_semantic_seg='mask'),
        update_pad_shape=False),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(416, 416),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```
Could you tell me how to use`align_corners=True` correctly? How to fix this config up?
Thank you!

**Comment by HarborYuan** [comment]
If you can read Chinese, this link may help you:
https://zhuanlan.zhihu.com/p/87572724
In short, use align_corners=True when you rescale image from x+1 to nx+1, and use align_corners=False when you rescale image from x to nx.

**Comment by zhongqiu1245** [comment]
@HarborYuan Thank you for your reply!
You mean this:
```train_pipeline = [
    ...
    dict(type='Resize',
         img_scale=[(321, 321), (417, 417)],
         keep_ratio=True)
    ...
]
test_pipeline = [
    ...
    dict(
        type='MultiScaleFlipAug',
        img_scale=(417, 417),
     ...
        ])
]```

**Comment by HarborYuan** [comment]
I am not an expert on this. I usally use align_coners=False with even number of resolution. Some papers, e.g. max-deeplab will use 1025x1025 and 641x641 as the resolution. You may need check their implementations to figure it out. 
This will emprically improve the performance in dense predictions.

**Comment by MengzhangLI** [comment]
Hi, just set img scale like `img_scale` as odd value, not even value.

**Comment by zhongqiu1245** [comment]
@MengzhangLI Thank you for your reply!
Like this？
```
train_pipeline = [
    ...
    dict(type='Resize',
         img_scale=[(321, 321), (417, 417)],
         keep_ratio=True)
    ...
]
test_pipeline = [
    ...
    dict(
        type='MultiScaleFlipAug',
        img_scale=(417, 417),
     ...
]
```

**Comment by zhongqiu1245** [comment]
> I am not an expert on this, it seems that you also need to ensure that the original image is with odd number of resolution.
> I usally use align_coners=False with even number of resolution. Some papers, e.g. max-deeplab will use 1025x1025 and 641x641 as the resolution. You may need to check their implementations to figure it out.
> This will emprically improve the performance in dense predictions.

Thank you！

**Comment by MengzhangLI** [comment]
> @MengzhangLI Thank you for your reply!
> Like this？
> 
> ```
> train_pipeline = [
>     ...
>     dict(type='Resize',
>          img_scale=[(321, 321), (417, 417)],
>          keep_ratio=True)
>     ...
> ]
> test_pipeline = [
>     ...
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(417, 417),
>      ...
> ]
> ```

Just like [cityscapesx769](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/cityscapes_769x769.py), if I remember well, the `crop_size` and `img_scale ` are both set as odd number. Just have a shot and looking forward to your reply. 

Best,

**Comment by zhongqiu1245** [comment]
@MengzhangLI Thank you very much！It works perfectly！
Thanks! It works perfectly
There is another question. If the ”image“ files that I input has 5 channels (such as a medical dataset, lots of modes), how can I make mmseg read them successfully? And can the data augmentation methods in mmseg be applied to this 5-channel file?

**Comment by MengzhangLI** [comment]
> @MengzhangLI Thank you very much！It works perfectly！
> Thanks! It works perfectly
> There is another question. If the ”image“ files that I input has 5 channels (such as medical dataset, lots of modes), how can I make mmseg read them successfully? And can the data augmentation methods in mmseg be applied to this 5-channel file?

Sad. Right now we just support 3 channels RGB input and 1 channel input. We already realized it is important to support multi channel input but because of limited human resources we do not support it yet.

We would support it as soon as possible.

**Comment by zhongqiu1245** [comment]
@MengzhangLI 
Thank you!

**Comment by zhongqiu1245** [comment]
Hi, dear authors!
Sorry to bother you.
I found when I use TTA, the same question/warning appeared again.
If I suppress TTA,  the question/warning disappeared.
Here is my config about `test_pipeline`
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(417, 417),
        img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=True,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```
But I set the` img_scale=(417, 417)`, which are odd numbers.
Could you tell me how to fix it up?

**Comment by MengzhangLI** [comment]
Because of scaling transform of `img_scale` * certain `img_ratio` may get even number size at TTA. So you may set `img_scale` as a list of dict, i.e., `[(209, 209), (313, 313), (417, 417), ...]` and uncomment `img_ratios`.

For multi-GPU test, right now I use SLURM on remote server or single GPU command on my local PC. So I could not give an example which I really use and promising it really works. You could report error you met even if you have read our instructions, and we would solve it as soon as possible.

**Comment by zhongqiu1245** [comment]
@MengzhangLI Thank you！
