### ISSUE TITLE
 How to calculate auc and draw the PR curve？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#888]
Hi, dear authors
sorry to bother you. 
Could you tell me how to draw the PR crew and calculate the auc in mmsegmentation?
(The main problem is that I don't know where to set the threshold of Mask.)
 Thank you.

**Comment by zhongqiu1245** [comment]
Any news？

**Comment by xvjiarui** [comment]
Hi, @zhongqiu1245 

Sorry. Currently, we don't support draw PR curve. You may get the score of the mask [here](https://github.com/open-mmlab/mmsegmentation/blob/62f70ebedd93338e8966c64ce9dc35d508ee9efa/mmseg/models/segmentors/encoder_decoder.py#L256)
