### ISSUE TITLE
Why is the test performance of the model trained using the official configuration file so much worse than the official model?  

### ISSUE THREAD

**Issue by wongyufei** [open-mmlab/mmsegmentation#889]
The mmsegmentation is 0.17.0
The configuration file I use is psanet_r50-d8_512x512_20k_voc12aug.py
The specific train  instruction is CUDA_VISIBLE_DEVICES=0 python tools/train.py   configs/psanet/psanet_r50-d8_512x512_20k_voc12aug.py
The test instruction is CUDA_VISIBLE_DEVICES=0 python tools/test.py   configs/psanet/psanet_r50-d8_512x512_20k_voc12aug.py  work_dirs/psanet_r50-d8_512x512_20k_voc12aug/latest.pth  --eval  mIoU

Here are the test results:
+------+-------+-------+
| aAcc |  mIoU |  mAcc |
+------+-------+-------+
| 84.1 | 54.14 | 83.17 |
+------+-------+-------+

The official model results are:
+-------+-------+------+
|  aAcc |  mIoU | mAcc |
+-------+-------+------+
| 94.68 | 76.39 | 85.3 |
+-------+-------+------+

Why is there such a big gap between the two?

**Comment by MengzhangLI** [comment]
I guess because default setting is 4 GPUs x 2 Batch sizes.

**Comment by wongyufei** [comment]
Thanks for your reply！ I will test whether this is the reason through experiments.
