### ISSUE TITLE
segformer head compare with fpn head 

### ISSUE THREAD

**Issue by cjt222** [open-mmlab/mmsegmentation#893]
Excuse me, the head of segformer directly extracts the feature maps of the four stages for concat. Has this method been compared with fpn head? What is the difference between the two methods? Thanks

**Comment by MengzhangLI** [comment]
Hi, thanks you for your constructive question. I have asked my colleagues and currently we have not compared segformer and fpn yet. But personally I think this question is very valuable, you could have a shot.

Looking forward to your reply.

Best,

**Comment by cjt222** [comment]
I tried to use fpn head instead of segformer head, and found that fpn head was not as good as segformer head, and often missed and mis-segmented
