### ISSUE TITLE
can't find 'detail' package by 'pip install detail' or 'conda install detail'

### ISSUE THREAD

**Issue by MacavityT** [open-mmlab/mmsegmentation#894]
tools/convert_datasets/pascal_context.py  line 8，
from detail import Detail

but I can't install the 'detail' package through the above two ways.

**Comment by MacavityT** [comment]
I find the script needs to reveive a param 'json_path', but now it seems can only download .mat format file on the website. Maybe somewhere gets changed in the dataset website.

**Comment by Junjun2016** [comment]
https://github.com/zhanghang1989/detail-api

**Comment by MacavityT** [comment]
> https://github.com/zhanghang1989/detail-api
Got it, thank you!
