### ISSUE TITLE
In mmseg, which *.py file is responsible for reading images?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#899]
Hi, dear authors!
Sorry to bother you.
In mmseg, which `*.py` file is responsible for reading images?
If I want to change it so that it can read 5-channel files(python, *.mat)，which parts should I modify?
Thank you!

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/loading.py

**Comment by zhongqiu1245** [comment]
@Junjun2016 Hi, thank you for your reply!
this code?
```
 img = mmcv.imfrombytes(img_bytes, flag=self.color_type, backend=self.imdecode_backend)
```

**Comment by zhongqiu1245** [comment]
Thank you!
