### ISSUE TITLE
workflow 流程里的val 功能代码不能正常运行，代码传参不匹配，有bug

### ISSUE THREAD

**Issue by liujianghao** [open-mmlab/mmsegmentation#904]
base.py里的def val_step(self, data_batch, **kwargs)没有optimizer这个参数，和epoch_based_runner.py 里的outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)不匹配

**Comment by MengzhangLI** [comment]
Hi, welcome to create a new pull request.
