### ISSUE TITLE
How to use `test_time_aug.py` in mmseg?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#909]
Hi, dear authors!
Sorry to bother you.
Could you tell me how to use `mmseg/datasets/pipelines/test_time_aug.py` in mmseg?  If I use it, is it different from `python test.py ...  --aug-test`?
Thank you!

**Comment by MacavityT** [comment]
test_time_aug(TTA) can be used as following:

"""
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2049, 1025),
        img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
"""
The point is input image needs to be multiscale.

**Comment by zhongqiu1245** [comment]
> test_time_aug(TTA) can be used as following:
> 
> """
> test_pipeline = [
> dict(type='LoadImageFromFile'),
> dict(
> type='MultiScaleFlipAug',
> img_scale=(2049, 1025),
> img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
> flip=False,
> transforms=[
> dict(type='Resize', keep_ratio=True),
> dict(type='RandomFlip'),
> dict(type='Normalize', **img_norm_cfg),
> dict(type='ImageToTensor', keys=['img']),
> dict(type='Collect', keys=['img']),
> ])
> """
> The point is input image needs to be multiscale.

Thank you for your reply!
If input image needs to be multiscale, the `img_scale` in
`MultiScaleFlipAug` should be `img_scale=[(xxx, xxx), (xxx, xxx)]`?

**Comment by MacavityT** [comment]
@zhongqiu1245 
Yes, you can set multiscale in two ways. As you mentioned, or you can use my settings "image_ratios=[(xxx),(xxx)]"

**Comment by zhongqiu1245** [comment]
@MacavityT Thank you！
