### ISSUE TITLE
Question about calculating metrics if input multiscale images

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmsegmentation#910]
Hi, dear authors!
Sorry to bother you.
If the image sizes of val are totally different(multiscale), how to calculate acc, recall, dice and other metrics in mmseg? Is it resize to uniform size calculation?

For example:
image_1_in_val：（314， 314， 3）
image_2_in_val：（512， 512， 3）
image_3_in_val：（111， 111， 3）
config:
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(312, 312),  (417, 417)],
        flip=True,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```
Do they resize to an uniform size to calculate? 
Or in other way to calculate?
Thank you!

**Comment by MengzhangLI** [comment]
Hi, the metric are all calculated by original size. So it's OK for different size images on val or test set.

**Comment by zhongqiu1245** [comment]
@MengzhangLI Thank you for your reply！
If I want to save the score mask of each image(with the score of each pixel), could you tell me how to save it? Which part of mmseg should be modfied if I want to save it?And how does the mmseg calculate the precision and recall?

**Comment by zhongqiu1245** [comment]
Any news？

**Comment by zhongqiu1245** [comment]
I figured it out. The former.
