### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yangrisheng** [open-mmlab/mmsegmentation#911]
when I use "python tools/train.py configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py" to train a model.
It has a error "ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory"
how can I solute it?
Thank you.

**Comment by NyanAung436** [comment]
hi how did you solve it? @yangrisheng
