### ISSUE TITLE
(Training with FP16 ) 请问训练时是否有使用混合精度

### ISSUE THREAD

**Issue by wusitong98** [open-mmlab/mmsegmentation#912]
1. 发现训练速度比自己写的代码快了不少，请问这是为什么呢？
2. 是否有使用了混合精度呢？ 如果用了的话，怎么能控制开关呢？（在doc中没找到答案）

**Comment by MengzhangLI** [comment]
Hi, here is two config files w and w/o FP16, hope it is useful to you.

[BiSeNetV2 (FP16)](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/bisenetv2/bisenetv2_fcn_fp16_4x4_1024x1024_160k_cityscapes.py) and [BiSeNetV2](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/bisenetv2/bisenetv2_fcn_4x4_1024x1024_160k_cityscapes.py)

**Comment by wusitong98** [comment]
Got it. Thanks so much!
