### ISSUE TITLE
A mistake

### ISSUE THREAD

**Issue by lartpang** [open-mmlab/mmsegmentation#92]
https://github.com/open-mmlab/mmsegmentation/blob/bafc0e5db679b66a739db626dd57a48f8d3a4f6e/mmseg/apis/test.py#L34

It should be:

```python
        if isinstance(result, list):
            results.extend(result)
        else:
            results.append(result)
```

In this case, the if statement here is reasonable.

**Comment by xvjiarui** [comment]
Hi @lartpang 
Thanks for pointing out!
Would you like to create a PR to fix it?

**Comment by lartpang** [comment]
OK! 😅
