### ISSUE TITLE
runner type selection 

### ISSUE THREAD

**Issue by MacavityT** [open-mmlab/mmsegmentation#926]
Hello developer,

I notice that  'runner' type are 'EpochBasedRunner' in mmcls & mmdet examples, but 'IterBasedRunner in mmseg examples. 

I know we can change the type in our configuration, but why should they be 'IterBasedRunner'  in those examples. Perhaps it will be better in segmentation tasks? Thanks for your attention!

**Comment by MengzhangLI** [comment]
Because many segmentation models use iteration based settings rather than epoch based.

To change iteration to epoch, the usage can be found in `config.md` in ./docs/tutorials/ folder

runner = dict(
    type='IterBasedRunner', # Type of runner to use (i.e. IterBasedRunner or EpochBasedRunner)
    max_iters=40000) # Total number of iterations. For EpochBasedRunner use `max_epochs`

Best,

**Comment by MacavityT** [comment]
Thanks a lot!

**Comment by jhaggle** [comment]
What is the difference between IterBasedRunner or EpochBasedRunner?
