### ISSUE TITLE
UNET with different methods

### ISSUE THREAD

**Issue by AKMourato** [open-mmlab/mmsegmentation#930]
Greetings.

I don't quite understand why in:
https://github.com/open-mmlab/mmsegmentation/tree/master/configs/unet
It's presented U-NET with different methods (FCN, DeepLab), what do you mean by that?
Where can I see what varies between the implementation methods you refer to and where is the standard version of it?
Thanks

**Comment by Junjun2016** [comment]
Hi @AKMourato 
Since we decompose segmentor into backbone, neck, and head.
UNet is regarded as backbone while FCN and DeepLab are regards as heads (or method).

**Comment by AKMourato** [comment]
Thank you @Junjun2016
