### ISSUE TITLE
error for using dist_train.sh 

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#938]
Excuse me
I'm Trainning with multiple GPUs,for example:./tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM} [optional arguments] and I have 2 GPUs try to use
Traceback (most recent call last):
File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in
main()
File "/home/anaconda3/envs/py37_torch1.6/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/py37_torch1.6/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/SETR/SETR_Naive_768x768_40k_cityscapes_bs_8.py', '--launcher', 'pytorch', '--load-from=./pth/jx_vit_large_p16_384-b3be5167.pth']' returned non-zero exit status 1.

Thanks for your answer！

**Comment by Kittywyk** [comment]
> > it
> 
> Thanks for your answer.I'll try first

Hi, I have the same problem. Have you solved it through upgrading mmsegmentation?

**Comment by MengzhangLI** [comment]
> > > it
> > 
> > 
> > Thanks for your answer.I'll try first
> 
> Hi, I have the same problem. Have you solved it through upgrading mmsegmentation?

I guess it is more likely caused by installation version because there are several version upgrading iteration. What's your env version info?

**Comment by Lsz-20** [comment]
> > > 它
> > 
> > 谢谢你的回答。我先试试
> 
> 嗨，我也有同样的问题。你通过升级彩信解决了吗？

I have tried several versions，but there still seems to be a problem/(ㄒoㄒ)/

**Comment by Lsz-20** [comment]
> > > > 它
> > > 
> > > 谢谢你的回答。我先试试
> > 
> > 嗨，我也有同样的问题。你通过升级彩信解决了吗？
> 
> 我想更可能是安装版本引起的，因为有几个版本升级迭代。你的env版本信息是什么？

I have tried download master and mmcv-full=1.3.14 、mmseg=0.17.0 and mmcv-full=1.3.14 with torch1.7.0 cu110，it always show me the same error

**Comment by MengzhangLI** [comment]
> > > > > 它
> > > > 
> > > > 
> > > > 谢谢你的回答。我先试试
> > > 
> > > 
> > > 嗨，我也有同样的问题。你通过升级彩信解决了吗？
> > 
> > 
> > 我想更可能是安装版本引起的，因为有几个版本升级迭代。你的env版本信息是什么？
> 
> I have tried download master and mmcv-full=1.3.14 、mmseg=0.17.0 and mmcv-full=1.3.14 with torch1.7.0 cu110，it always show me the same error

Do you install by dockerfile? There was similar error caused by this. Related PR: https://github.com/open-mmlab/mmsegmentation/issues/856

**Comment by Lsz-20** [comment]
> > I have tried download master and mmcv-full=1.3.14 、mmseg=0.17.0 and mmcv-full=1.3.14 with torch1.7.0 cu110，it always show me the same error
> 
> Do you install by dockerfile? There was similar error caused by this. Related issue: #856

I just follow the dockerfile, the problem same as issue: #856,and i have update the mmseg's version as it told me ,but give me the same error agian.
