### ISSUE TITLE
Are there any examples of modular design in this repo?

### ISSUE THREAD

**Issue by timothylimyl** [open-mmlab/mmsegmentation#941]
Hi, I cannot seem to find any examples/tutorial on how to go about changing the modules. For example, I am interested in changing DeepLabV3Plus backbone to MobileNet-V3 (currently it is only ResNet-50/ variants of it).

E: Just to be clear, I know how to change the configs to put MobileNet as the backbone, but how do you go about connecting it with ANY decoder head?

**Comment by MengzhangLI** [comment]
You could modify config file of DeepLabV3Plus `_base_` [file](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/deeplabv3plus_r50-d8.py) whose backbone is ResNet to MobileNet-V3.

This modification could be implemented only in ./config/deeplabv3plus, you could code mobilenet backbone to overwrite its original backbone in `_base_` by config, more details could be referred [here](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/config.md).

Hope it could help you.

**Comment by timothylimyl** [comment]
Hi @MengzhangLI , I will give it a go. Thank you for your effort, get back to you soon.

**Comment by MengzhangLI** [comment]
> Hi @MengzhangLI , I will give it a go. Just to confirm from your comments, the mobilenet backbone needs some re-coding to get it to work with deeplabv3plus decoder head?
> 
> Thank you for your effort, get back to you soon.

Yes, such as channel numers or other things. Just make comparison between your new config files and old one.
