### ISSUE TITLE
How can I get counts of result segmentation by labels?

### ISSUE THREAD

**Issue by accforaus** [open-mmlab/mmsegmentation#949]
Hi guys, I have some questions about results in segmentation. 

I tried inference using the pre-trained model. It works well, And I need to get counts of results by labels.

For example in cityscapes, there are 19 counts of classes. 

And I want get counts of each classes like:
```python
{'road': 0, 'sky': 1, 'sidewalk': 0, 'car': 10, ...}
```
moreover, I want to plot label each class on segmentations,
How can I get counts? 

Thanks for reading this.

**Comment by MengzhangLI** [comment]
> I am not sure, but here is what I am thinking. MMsegmentation looks at all the car objects in the images as a single instances. To count the occurences of an object model should look at it as multiple instances. You should check [mmdetection](https://github.com/open-mmlab/mmdetection) repo. For example in the pic below, the model can count the no of cars and benches. So This might work
> 
> ![image](https://user-images.githubusercontent.com/25660247/136741904-f852b0de-c043-4d40-a5f8-41083dea8686.png)
> 
> what do you say?

Yes, you are right. Semantic segmentation would classify pixels into classes so if certain pixel belongs to CAR, no matter which car actually in image, they would be all classified into class of car. Right now instance segmentation is in MMDetection because many instance segmentation algorithms would use detection model to discriminate object, then do segmentation.

Best,

**Comment by zeynepiskenderoglu** [comment]
> @purnasai Hi purnasai!
> 
> I considered using detection models also.
> 
> But Object Detection Model will detect some objects.
> 
> I need to detect sky, road or etc. But there is no detected sky or roads someone else, So I have to use semantic segmentation models.
> 
> I got the results of each class per pixel area like:
> 
> ```python
> [[False, False, False, False, True, True, True, False, ...], [False, False, True, True, ...]]
> ```
> 
> But I don't know how I extract the area of detected class area.

i have the same problem

**Comment by vincentleooo** [comment]
Hi there, might be a bit late now, but I did write an article in the middle of last year that might help point you to the right direction.

https://vinleonardo.com/detecting-objects-in-pictures-and-extracting-their-data-using-mmdetection/

Hope it helps!

**Comment by zeynepiskenderoglu** [comment]
Thanks for the feedback, the article was very helpful to me, but I have one more problem. Maybe you can help.
The article wishes to continue the process using bboxes results. But I need segmentation results, ie masks. Let's explain in the example below. I need the mask exactly on the bench, not the boxes on the side of the bench. How can I do that?
![136741904-f852b0de-c043-4d40-a5f8-41083dea8686](https://user-images.githubusercontent.com/114475074/218087322-34d061c0-fcc4-472d-9db6-43d9a5ed4a81.png)
