### ISSUE TITLE
A mistake about saving result image with `ori_filename`.

### ISSUE THREAD

**Issue by lartpang** [open-mmlab/mmsegmentation#95]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

Main code related on this issue

1. `ori_filename` is a abs path: 
    * https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L130
    * https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/loading.py#L67
2. here, we use `ori_filename` to save result images: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/apis/test.py#L53

These steps will cause the output image to overwrite the original data (:<), and the name of the output image here should also remain consistent with the original ground truth(`.png`), but here it is consistent with the input image(`.jpg`).

**My config about the dataset**

```python
dataset_type = "SingleFrameDavis16Dataset"
data_root = "/home/lart/Datasets/VideoSeg/DAVIS-2017-trainval-480p/DAVIS"
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir="JPEGImages/480p",
        ann_dir="Annotations/480p",
        split="ImageSets/2016/train.txt",
        pipeline=train_pipeline,
    ),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir="JPEGImages/480p",
        ann_dir="Annotations/480p",
        split="ImageSets/2016/val.txt",
        pipeline=test_pipeline,
    ),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir="JPEGImages/480p",
        ann_dir="Annotations/480p",
        split="ImageSets/2016/val.txt",
        pipeline=test_pipeline,
    ),
)
```

**Comment by xvjiarui** [comment]
Hi @lartpang 
`out_dir` will be appended in the path. So the original file won't be overwritten.

**Comment by lartpang** [comment]
I write a dome code:

```python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> ori_filename = '/aaa/bbb/ccc.jpg'
>>> out_dir = '/ddd/eee'
>>> os.path.join(out_dir, ori_filename)
'/aaa/bbb/ccc.jpg'
```

If `ori_filename` is an absolute path, in the `os.path.join`, the arg `out_dir` will not used.

**Comment by xvjiarui** [comment]
Hi @lartpang 
Sorry for the late reply. In this case, there will be trouble. 
A temporary workaround would be using symlink instead of absolute path.

**Comment by lartpang** [comment]
Okay, thanks.
