### ISSUE TITLE
Support MaskFormer in MMSegmentation

### ISSUE THREAD

**Issue by Qianyu666** [open-mmlab/mmsegmentation#968]
Hi, 

Thanks for your practical codebase, I find it very helpful.

I am writing this issue to know that do you have any plan to support MaskFormer [1] in the mmsegmentation recently? I find it very hard to transfer the original code into the mmsegmentation. 

[1]. Per-Pixel Classification is Not All You Need for Semantic Segmentation. NeurIPS 2021

**Comment by MengzhangLI** [comment]
Hi, right now we do not have clear time schedule for MaskFormer because of limited human sources. But any pull request from community are very welcomed. We encourage every users and researchers could join us to make PR for their own.

Best,
