### ISSUE TITLE
Why can't I use the following statement to generate a visual segmentation result?

### ISSUE THREAD

**Issue by luohao1099416321** [open-mmlab/mmsegmentation#971]
Hi!
Why can't I use the following statement to generate a visual segmentation result?
python tools/test.py tools/swin_vaihingen/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py tools/swin_vaihingen/latest.pth --show-dir upernetResults --eval mFscore
I just got the original pictures.

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply. FYI, yhis bug is related with `--show-dir`. It has been fixed by this repo. https://github.com/open-mmlab/mmsegmentation/pull/1091
