### ISSUE TITLE
[TensorRT] Is batching possible ?

### ISSUE THREAD

**Issue by timothylimyl** [open-mmlab/mmsegmentation#976]
I set `dynamic-export` for pytorch2onnx and then I set `--min-shape 10 3 224 224 --max-shape 10 3 224 224` for onnx2tensorrt. However, when I run a batch of 10 images through the tensorrt engine file generated, I get this error: 

```
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::445, condition: batchSize > 0 && 

batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 10, but engine max batch size was: 1

```

**Comment by RunningLeon** [comment]
@timothylimyl Hi, could you provide the full scripts that you ran?

**Comment by timothylimyl** [comment]
the engine can be created successfully, but loading the engine is problematic now cause the first dimension is of shape -1.

**Comment by timothylimyl** [comment]
I think the issue is with the creation of the engine cause no matter how i create it, the batch size is still always 1. Thus, if you call `engine.get_binding_shape(binding)`, you will always get back shape like `-1,3,224,224` for input  and the output is weirdly `1, -1,302,480` (i was expecting `-1,1,302,480`).

The engine.max_batch_size staying at 1 also will mess up the allocation bytes size but you can just manually change that.

**Comment by RunningLeon** [comment]
Could you try with `whole` mode with `--cfg-options model.test_cfg.mode=whole` for `pytorch2onnx.py`? `Slide` mode does not support dynamic shape.

**Comment by timothylimyl** [comment]
Hi @RunningLeon,

I have repeated the steps with `whole` mode. Error is still the same, the attribute `engine.max_batch_size` is still set to 1. Do you face this problem too?

Same error:
```
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::445, condition: batchSize > 0 && batchSize <= 

mEngine.getMaxBatchSize(). Note: Batch size was: 10, but engine max batch size was: 1
```

I realised that the binding is actually incorrect too:
```
    for binding in engine:
        print('binding:', binding, engine.get_binding_shape(binding))
```
The shape is for input is correct (10,3,224,224) but the shape of the output is wrong (1,10,224,224), the batch dimension and channel dimension was switched.

Terminal commands run is the same:

```
python tools/pytorch2onnx.py resnet18_build/config.py --checkpoint latest.pth 

--output-file batch_resnet18.onnx --dynamic-export --cfg-options model.test_cfg.mode="whole"

```
```
 python tools/onnx2tensorrt.py resnet18_build/config.py batch_resnet18.onnx 

--trt-file batch_resnet18.engine --min-shape 10 3 224 224 --max-shape 10 3 224 224

*note: i tried min-shape = 1 3 224 224 , gives me the same error.
```

**Comment by RunningLeon** [comment]
> Hi @RunningLeon,
> 
> I have repeated the steps with `whole` mode. Error is still the same, the attribute `engine.max_batch_size` is still set to 1. Do you face this problem too?
> 
> Same error:
> 
> ```
> [TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::445, condition: batchSize > 0 && batchSize <= 
> 
> mEngine.getMaxBatchSize(). Note: Batch size was: 10, but engine max batch size was: 1
> ```
> 
> I realised that the binding is actually incorrect too:
> 
> ```
>     for binding in engine:
>         print('binding:', binding, engine.get_binding_shape(binding))
> ```
> 
> The shape is for input is correct (10,3,224,224) but the shape of the output is wrong (1,10,224,224), the batch dimension and channel dimension was switched.
> 
> Terminal commands run is the same:
> 
> ```
> python tools/pytorch2onnx.py resnet18_build/config.py --checkpoint resnet18_build/latest.pth 
> 
> --output-file batch_resnet18.onnx --dynamic-export --cfg-options model.test_cfg.mode="whole"
> ```
> 
> ```
>  python tools/onnx2tensorrt.py resnet18_build/config.py batch_resnet18.onnx 
> 
> --trt-file batch_resnet18.engine --min-shape 10 3 224 224 --max-shape 10 3 224 224
> 
> *note: i tried min-shape = 1 3 224 224 , gives me the same error.
> ```
> 
> Edit: tried for the standard resnet50 config too (deeplabv3plus-cityscapes)
> 
> Edit2: There is values for the output but it is all zeros.

Hi, @timothylimyl, works on my machine. No need to change batch_size of engine manually.

### env
```
python mmseg/utils/collect_env.py 
sys.platform: linux
Python: 3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2080
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.5.2
MMCV: 1.3.16
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.18.0+9feaa7c
```
### pytorch2onnx
```
configs/deeplabv3plus/deeplabv3plus_r50-d8_769x769_40k_cityscapes.py
--checkpoint
checkpoints/deeplabv3plus_r50-d8_769x769_40k_cityscapes_20200606_114143-1dcb0e3c.pth
--show
--verify
--dynamic-export
--output-file
checkpoints/deeplabv3plus_r50-d8_769x769_40k_cityscapes.onnx
--shape
300
--dynamic-export
--input-img
demo/demo.png
--cfg-options
model.test_cfg.mode=whole
```

### onnx2tensorrt, no error happens in here, visualization looks good.
``` 
configs/deeplabv3plus/deeplabv3plus_r50-d8_769x769_40k_cityscapes.py
checkpoints/deeplabv3plus_r50-d8_769x769_40k_cityscapes.onnx
--show
--verify
--trt-file
checkpoints/deeplabv3plus_r50-d8_769x769_40k_cityscapes.trt
--min-shape
10
3
224
224
--max-shape
10
3
224
224
--verbose
--input-img
demo/demo.png
--workspace-size
1
```

### verify with trtexec tool
```
trt_model=deeplabv3plus_r50-d8_769x769_40k_cityscapes.trt
trtexec \
  --loadEngine=$trt_model \
  --shapes=input:10x3x300x300 \
  --workspace=1 \
##[11/09/2021-15:52:22] [I] total compute time: 3.00006 s
&&&& PASSED TensorRT.trtexec # trtexec --loadEngine=deeplabv3plus_r50-d8_769x769_40k_cityscapes.trt --shapes=input:10x3x300x300 --workspace=1

```

**Comment by timothylimyl** [comment]
Hi @RunningLeon, thank you for checking, appreciate it. I will give it another try. Just to confirm, why did u put `--shape` ==300 at pytorch2onnx? Is it a typo?

**Comment by RunningLeon** [comment]
> Hi @RunningLeon, thank you for checking, appreciate it. I will give it another try. Just to confirm, why did u put `--shape` ==300 at pytorch2onnx? Is it a typo?

Just to have a smaller input.

**Comment by timothylimyl** [comment]
It works, I guess it somehow still require mmcv dependencies. I got it to work only when I ran:
```
.
.

from mmcv.tensorrt import (TRTWrapper, onnx2trt, save_trt_engine,
                                   is_tensorrt_plugin_loaded)

assert is_tensorrt_plugin_loaded(), 'Requires to complie TensorRT plugins in mmcv

## Run inference with TensorRT
trt_model = TRTWrapper(trt_file, ['input'], ['output'])

with torch.no_grad():
    trt_outputs = trt_model({'input': inputs})
    output = trt_outputs['output']

```

**Comment by RunningLeon** [comment]
> It works, I guess it somehow still require mmcv dependencies. I got it to work only when I ran:
> 
> ```
> .
> .
> 
> from mmcv.tensorrt import (TRTWrapper, onnx2trt, save_trt_engine,
>                                    is_tensorrt_plugin_loaded)
> 
> assert is_tensorrt_plugin_loaded(), 'Requires to complie TensorRT plugins in mmcv
> 
> ## Run inference with TensorRT
> trt_model = TRTWrapper(trt_file, ['input'], ['output'])
> 
> with torch.no_grad():
>     trt_outputs = trt_model({'input': inputs})
>     output = trt_outputs['output']
> ```

Yes, because there are some custom TensorRT plugins in mmcv which the TensorRT engine depends on.

**Comment by timothylimyl** [comment]
I see, my bad. I thought that once the engine is created, there is no need for the plugins of mmcv any more. Somehow, it actually worked for batch size of 1 though.

Anyways, thanks for your help.
