### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by zyywansui123** [open-mmlab/mmsegmentation#980]
RUN SEGFORMER

RuntimeError: weight tensor should be defined either for all or no classes at /opt/conda/conda-bld/pytorch_1607370141920/work/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu:27

**Comment by jhaggle** [comment]
If I follow this tutorial completely unchanged it works fine.

https://github.com/open-mmlab/mmsegmentation/blob/main/demo/MMSegmentation_Tutorial.ipynb

I then try to add Class Balanced Loss as in these tips & tricks:

https://mmsegmentation.readthedocs.io/en/latest/advanced_guides/training_tricks.html#class-balanced-loss

I therefore add this line to the cell in the tutorial where the config is modified:

cfg.model.decode_head.loss_decode.update(dict(class_weight=[0.1, 0.1, 0.7, 0.1, 0.1, 0.1, 0.7, 0.1])) 

HOWEVER, this results in this cuda error:

File /jupyterlab/mmsegmentation/mmseg/models/losses/accuracy.py:49, in accuracy(pred, target, topk, thresh, ignore_index)
     47     correct = correct & (pred_value > thresh).t()
     48 if ignore_index is not None:
---> 49     correct = correct[:, target != ignore_index]
     50 res = []
     51 eps = torch.finfo(torch.float32).eps

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

If I add os.environ['CUDA_LAUNCH_BLOCKING'] = "1" to the code in accordance with the cuda error I instead get this:

File /jupyterlab/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:66, in <listcomp>(.0)
     62         avg_factor = label.numel()
     64 else:
     65     # the average factor should take the class weights into account
---> 66     label_weights = torch.stack([class_weight[cls] for cls in label
     67                                  ]).to(device=class_weight.device)
     69     if avg_non_ignore:
     70         label_weights[label == ignore_index] = 0

RuntimeError: CUDA error: device-side assert triggered

How can I avoid this error? And what is causing it?
