### ISSUE TITLE
dice loss error?

### ISSUE THREAD

**Issue by cnnAndBn** [open-mmlab/mmsegmentation#982]
hi, @MengzhangLI 
in https://github.com/open-mmlab/mmsegmentation/blob/6d35d76195f173fbc6b119a7d7815e67d78024c6/mmseg/models/losses/dice_loss.py#L108
the prediction just go through softmax function ,which not formulated to the one hot format,is this right?

**Comment by dadada101** [comment]
@MengzhangLI   https://github.com/open-mmlab/mmsegmentation/blob/6d35d76195f173fbc6b119a7d7815e67d78024c6/mmseg/models/losses/dice_loss.py#L110
It seems one hot is for target,not the prediction
