### ISSUE TITLE
AssertionError: both backbone and segmentor set pretrained weight

### ISSUE THREAD

**Issue by Awihbaaaaaa** [open-mmlab/mmsegmentation#990]
Hello everone,

In the implementation of 
MMSegemntation_Tutorial.ipynb
In the evaluation part of training a model on a new dataset
I am getting the follwoing error:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

~/dml-project/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py in __init__(self, backbone, decode_head, neck, auxiliary_head, train_cfg, test_cfg, pretrained, init_cfg)
     33             assert backbone.get('pretrained') is None, \
---> 34                 'both backbone and segmentor set pretrained weight'
     35             backbone.pretrained = pretrained

AssertionError: both backbone and segmentor set pretrained weight

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_21918/176345022.py in <module>
      9 # Build the detector
     10 model = build_segmentor(
---> 11     cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
     12 # Add an attribute for visualization convenience
     13 model.CLASSES = datasets[0].CLASSES

~/dml-project/mmsegmentation/mmseg/models/builder.py in build_segmentor(cfg, train_cfg, test_cfg)
     47         'test_cfg specified in both outer field and model field '
     48     return SEGMENTORS.build(
---> 49         cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py in build(self, *args, **kwargs)
    210 
    211     def build(self, *args, **kwargs):
--> 212         return self.build_func(*args, **kwargs, registry=self)
    213 
    214     def _add_children(self, registry):

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py in build_model_from_cfg(cfg, registry, default_args)
     25         return Sequential(*modules)
     26     else:
---> 27         return build_from_cfg(cfg, registry, default_args)
     28 
     29 

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     53     except Exception as e:
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 
     57 

AssertionError: EncoderDecoder: both backbone and segmentor set pretrained weight
---------------------------------------------------------------------------

Anyone has an idea how to solve it????

**Comment by mfernezir** [comment]
I ran into this one as well.

What happens is that `cfg.model` is fine when you first run
```
model = build_segmentor(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
```

However, this line modifies `cfg.model` and it fails if you run the same cell again.

It adds the key `pretrained` in the backbone dictionary in `cfg.model`, which gives this assertion error on the second run.

Running build_segmentor the first time gives the warning:
``` 
[python3.9/site-packages/mmseg/models/backbones/resnet.py:431](): UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
```
