### ISSUE TITLE
Demo Doesn't work on Colab

### ISSUE THREAD

**Issue by mavaylon1** [open-mmlab/mmsegmentation#997]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
There are a couple issues in the demo when running on Colab without any changes

1. # Install MMCV
!pip install mmcv-full==latest+torch1.5.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html

This returns: pip._vendor.packaging.version.InvalidVersion: Invalid version: 'latest+torch1.5.0+cu101'

2. from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
from mmseg.core.evaluation import get_palette

This returns: ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

3. from mmseg.apis import set_random_seed

This Returns: This returns: ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

**Reproduction**

1. What command or script did you run?

    ```none
    A placeholder for the command.
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified? 
No Modifications were made.
3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by VoyagerXVoyagerXisavailable** [comment]
###  Hi, you can query the default torch and cuda version with the command below(colab may update cuda and torch):
!pip list | grep torch
This returns: torch                         1.9.0+cu111
### Then just install the corresponding mmcv version.
!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
I successfully installed an hour ago!

**Comment by givkashi** [comment]
Thanks. let me know, please.
I prepared this [notebook](https://colab.research.google.com/drive/1KYOdF6CQoYH3ybUA0opIFdCSBavcRcnj?usp=sharing) like the demo but I got the below error, you can use it and help me to fix that. thanks .
@MengzhangLI 
 DisabledFunctionError: cv2.imshow() is disabled in Colab, because it causes Jupyter sessions
to crash; see https://github.com/jupyter/notebook/issues/3935.
As a substitution, consider using
  from google.colab.patches import cv2_imshow

**Comment by fokobrice3** [comment]
Hello to all, 
I watched the demo on mmsegmentation on colab but apparently the mmseg module is deprecated and does not work when imported. Is there a solution or another demo available?

Thanks in advance
